### ISSUE TITLE
Allow legacy behaviour if 2 servlets map to same path

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1000]
Older versions of jetty would allow duplicate servlets (either same name or different) to be mapped to the same path, choosing whichever mapping was defined last.

Newer servlet spec 3.1 behaviour requires an error to thrown and the deployment to fail if this happens. 

Make either behaviour optional, defaulting to 3.1 behaviour.

**Comment by janbartel** [comment]
Checked in to jetty-9.3 and above.

**Comment by ludoch** [comment]
Thanks!.
Now, I am wondering how do I get hold of the ServletContext from a WebAppContext? (i.e how a runtime would configure this setting?)

**Comment by ludoch** [comment]
Our stack trace looks like:
java.lang.IllegalStateException: Multiple servlets map to path: /incentive: IncentiveService,IncentiveServlet
at org.eclipse.jetty.servlet.ServletHandler.updateMappings(ServletHandler.java:1504)
at org.eclipse.jetty.servlet.ServletHandler.doStart(ServletHandler.java:156)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.security.SecurityHandler.doStart(SecurityHandler.java:361)
at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:448)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:116)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:803)
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1379)
at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1341)
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.createHandler(AppVersionHandlerMap.java:237)

**Comment by ludoch** [comment]
Nevermind, I think I know what to do:-)
