### ISSUE TITLE
Flaky `EventsHandlerTest.testUsingEventsResponseAsContentSourceFailsWithTrailers`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10087]
**Jetty version(s)**
12

**Description**

`EventsHandlerTest.testUsingEventsResponseAsContentSourceFailsWithTrailers` sometimes fails with:

```
java.io.IOException: written 0 < 6 content-length
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1208)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:589)
	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:349)
	at org.eclipse.jetty.io.internal.ContentCopier.process(ContentCopier.java:73)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.io.Content.copy(Content.java:91)
	at org.eclipse.jetty.test.client.transport.EchoHandler.handle(EchoHandler.java:54)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:96)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
	at org.eclipse.jetty.server.Server.handle(Server.java:177)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:615)
	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:128)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.Invocable.invokeNonBlocking(Invocable.java:156)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.invokeAsNonBlocking(AdaptiveExecutionStrategy.java:490)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:426)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
Suppressed: 
	|java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "onFailure" is null
	|	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$2(HttpChannelState.java:436)
	|	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	|	at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:117)
	|	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1225)
	|	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:589)
	|	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:349)
	|	at org.eclipse.jetty.io.internal.ContentCopier.process(ContentCopier.java:73)
	|	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
	|	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	|	at org.eclipse.jetty.io.Content.copy(Content.java:91)
	|	at org.eclipse.jetty.test.client.transport.EchoHandler.handle(EchoHandler.java:54)
	|	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
	|	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:96)
	|	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
	|	at org.eclipse.jetty.server.Server.handle(Server.java:177)
	|	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:615)
	|	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
	|	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:128)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:421)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	|	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	|	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	|	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	|	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	|	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	|	at org.eclipse.jetty.util.thread.Invocable.invokeNonBlocking(Invocable.java:156)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.invokeAsNonBlocking(AdaptiveExecutionStrategy.java:490)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:426)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	|	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lorban** [comment]
There seems to be a race condition in `HttpStreamOverHTTP2` between `onTrailer()` and `read()`. If a trailer gets parsed before `read()` is ever called, it's going to be stored in `_chunk`, which will prevent any call to `HTTP2Stream.readData()`, so the data is left in the stream's queue.
