### ISSUE TITLE
Flaky EE10 `AsyncServletTest.testStartWaitComplete`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10089]
**Jetty version(s)**
12

**Description**

`AsyncServletTest.testStartWaitComplete` sometimes fail with:

```
java.lang.AssertionError: 

Expected: a string starting with "HTTP/1.1 200 OK"
     but: was "HTTP/1.1 500 Server Error
Server: Jetty(12.0.0-SNAPSHOT)
Date: Mon, 10 Jul 2023 08:49:21 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 62
Connection: close

ERROR DISPATCH: /ctx/error/custom
500
AsyncContext timeout
"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.ee10.servlet@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncServletTest.testStartWaitComplete(AsyncServletTest.java:345)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:172)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:152)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	Suppressed: java.lang.AssertionError: 
Expected: a string containing "200 "
     but: was "500 62 http://localhost/ctx/path/info?start=200&complete=50"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
		at org.eclipse.jetty.ee10.servlet@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncServletTest.tearDown(AsyncServletTest.java:140)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
		at java.base/java.lang.reflect.Method.invoke(Method.java:578)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterEachMethod(TimeoutExtension.java:110)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:520)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeAfterEachMethodAdapter$24(ClassBasedTestDescriptor.java:510)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachMethods$10(TestMethodTestDescriptor.java:243)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:276)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:276)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:275)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachMethods(TestMethodTestDescriptor.java:241)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:142)
		... 27 more
```

When this happens, stderr shows this:

```
2023-07-10 08:49:21.181:INFO :oejs.Server:ForkJoinPool-1-worker-3: jetty-12.0.0-SNAPSHOT; built: 2023-07-10T08:32:46.461Z; git: 8d87a8041083dd7d43cef76632fdf67893b97aea; jvm 19.0.2+7
2023-07-10 08:49:21.183:INFO :oejsh.ContextHandler:ForkJoinPool-1-worker-3: Started oeje10s.ServletContextHandler@2b291b54{/ctx,/ctx,b=null,a=AVAILABLE,h=oeje10s.ServletHandler@1c35a629{STARTED}}
2023-07-10 08:49:21.183:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-3: Started oeje10s.ServletContextHandler@2b291b54{/ctx,/ctx,b=null,a=AVAILABLE,h=oeje10s.ServletHandler@1c35a629{STARTED}}
2023-07-10 08:49:21.183:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-3: Started ServerConnector@5d3a05f5{HTTP/1.1, (http/1.1)}{0.0.0.0:42919}
2023-07-10 08:49:21.183:INFO :oejs.Server:ForkJoinPool-1-worker-3: Started oejs.Server@55f21402{STARTING}[12.0.0-SNAPSHOT,sto=0] @8743ms
java.lang.IllegalStateException: s=HANDLING rs=EXPIRING os=OPEN is=IDLE awp=false se=false i=false al=2
	at org.eclipse.jetty.ee10.servlet@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletRequestState.complete(ServletRequestState.java:671)
	at org.eclipse.jetty.ee10.servlet@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncContextState.complete(AsyncContextState.java:61)
	at org.eclipse.jetty.ee10.servlet@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncServletTest$AsyncServlet$1.run(AsyncServletTest.java:901)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
2023-07-10 08:49:21.498:INFO :oejs.Server:ForkJoinPool-1-worker-3: Stopped oejs.Server@55f21402{STOPPING}[12.0.0-SNAPSHOT,sto=0]
2023-07-10 08:49:21.498:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-3: Stopped ServerConnector@5d3a05f5{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
2023-07-10 08:49:21.498:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-3: Stopped oeje10s.ServletContextHandler@2b291b54{/ctx,/ctx,b=null,a=AVAILABLE,h=oeje10s.ServletHandler@1c35a629{STOPPED}}
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1350/testReport/junit/org.eclipse.jetty.ee10.servlet/AsyncServletTest/Parallel_Stage___Build___Test___JDK19___testStartWaitComplete/

**Comment by gregw** [comment]
Fixed with 8d87a8041083dd7d43cef76632fdf67893b97aea
Sorry didn't do a PR.
