### ISSUE TITLE
Error/exception thrown 'java.lang.IllegalStateException': AsyncContext completed and/or Request lifecycle recycled.

### ISSUE THREAD

**Issue by ThiyagarajanManivannan** [eclipse/jetty.project#10092]
**Jetty version**
pax-web-jetty -  9.4.50.v20221201

**Java version**
openjdk version "11.0.18"

**Question**

Below error occurred while closing the output stream in order to commit the response. The specific exception thrown is java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled.

It suggests that the asynchronous context has already been completed or the request lifecycle has been recycled before the response was fully processed.

Can you provide your input to identify the root cause of this issue? which packages do I need to enable logging and debug information in the Jetty library? in order to track the flow of execution and identify any inconsistencies or unexpected behavior?

 o.g.j.server.ServerRuntime$Responder:709 writeResponse Error while closing the output stream in order to commit response."}
java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
        at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:52)
        at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:72)
        at org.glassfish.jersey.servlet.async.AsyncContextDelegateProviderImpl$ExtensionImpl.complete(AsyncContextDelegateProviderImpl.java:102)
        at org.glassfish.jersey.servlet.internal.ResponseWriter.commit(ResponseWriter.java:173)
        at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:390)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:707)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:373)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:363)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:857)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:889)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:845)

**Comment by gregw** [comment]
@ThiyagarajanManivannan the first thing I note is that this call does not look like normal completion, specifically it is coming via an `Errors.process` call, so some error has already happened, that may have completed the response, or more probably an error has occurred after the response was committed?  So you need to start from what that original exception was.

However, we will be unable to look more closely at this since jetty 9.4 is at end of community support. See #7958.   To get further support from the jetty developers, you will either need to obtain commercial support or upgrade to a more recent release of Jetty.
