### ISSUE TITLE
nullSessionCache - Unable to release Session

### ISSUE THREAD

**Issue by VASConsulting** [eclipse/jetty.project#10094]
**Jetty version(s)**
jetty-server:11.0.15

**Java version/vendor** `(use: java -version)`
Kotlin version 1.8.21 

**OS type/version**
Linux Fedora 36

**Description**
org.eclipse.jetty.server.session.SessionHandler - Unable to release Session 
Version 9.4.48.v20220622 and prior to this are working 
![Captura desde 2023-07-10 14-22-34](https://github.com/eclipse/jetty.project/assets/69988121/e9cdf9c8-815c-4ca5-9382-8ca6466ce533)

**How to reproduce?**
After a few request, error shows up ...
`
fun sqlSessionHandler() = SessionHandler().apply {
        // Error comes out when using NullSessionCache & jetty-server 11.0.15 
        sessionCache = NullSessionCache(this).apply {
            /* */
            sessionDataStore = JDBCSessionDataStoreFactory().apply {
                setDatabaseAdaptor(DatabaseAdaptor().apply {
                    datasource = HikariCP.dataSource()
                })
            }.getSessionDataStore(sessionHandler)
        }
        httpOnly = true
 }
`
![Captura desde 2023-07-10 14-50-03](https://github.com/eclipse/jetty.project/assets/69988121/f7ab1ac3-6091-4457-89d7-ea068293718a)

**Comment by janbartel** [comment]
Does your code retain references to the session object?

As you are using the NullSessionCache every request will have its own Session object, although they are all using the same session data from the database. Any changes to these Session objects will result in writes to the database, possibly overlapping from different requests.

Also, have you updated the version of your jdbc drivers from the time it was last working?

**Comment by gregw** [comment]
@janbartel interesting that this JDBC driver and/or database do not appear to support concurrent updates to the same row.   It is interesting as we've never seen this before... probably because the NullSessionCache is more likely used with a no-sql style database.

@VASConsulting Can you confirm this happens when you do actually have concurrent requests for the same session?
Also, can you consider using the default session cache, potentially with aggressive passivisation settings, so that you do not have multiple instances of the same session in memory?

**Comment by VASConsulting** [comment]
>@janbartel Does your code retain references to the session object?

We have two container running the same app and a loadbalancer. That's why we need to use NullSessionCache

>@janbartel Also, have you updated the version of your jdbc drivers from the time it was last working?

Done (using latest version: jaybird:5.0.2.java11) ... problem persist ...

> @janbartel interesting that this JDBC driver and/or database do not appear to support concurrent updates to the same row. It is interesting as we've never seen this before... probably because the NullSessionCache is more likely used with a no-sql style database.

As already mentioned: Same code is working as expected when using Jetty Version 9.4.48.v20220622 and prior

>@gregw Can you confirm this happens when you do actually have concurrent requests for the same session?

Yes ... exactly as you mention .. 

>@gregw  Also, can you consider using the default session cache, potentially with aggressive passivisation settings, so that you do not have multiple instances of the same session in memory?

Our need is having two o more containers running the same app ... 

Thanks a lot guys ... we really apreciate your help

**Comment by janbartel** [comment]
@VASConsulting can I see the full stacktrace please?

Does your application write to the session very frequently, or is it read-mostly once it is created?

I am also assuming your loadbalancer is not using sticky sessions?

There are no code changes in the `JDBCSessionDataStore` between jetty-9.4 and jetty-10/11.  There are minor code changes in the `AbstractSessionDataStore` to ensure that all subclasses read/write session data from within the scope of the webapp classloader. So far my supposition is that any concurrency issues you're seeing is simply due to timing differences in the different code bases and reveals an underlying problem with using a `NullSessionCache` if the session is frequently mutated. Even if you are not frequently mutating the session attributes, I suppose that the last accessed time may be being frequently updated if you have multiple concurrent requests for the same session - I need to see more of the stacktrace to get a better understanding of the context. If not the change in timing of the jetty code, the other alternative explanation is that the change in jetty versions is coincidental and for some reason (increased load?) the firebird database transactions are taking a little longer, but is still revealing an underlying problem with the usage of the `NullSessionCache` in firebird.

You could try setting the `savePeriodSec` to avoid every new request (which will mutate the `expiry` time) from causing a write. However, that's still no guarantee that concurrent requests won't both decide the `savePeriodSec` has expired and both try to do the update.

Reading here: https://stackoverflow.com/questions/56335663/firebird-deadlock-update-conflicts-with-concurrent-update, and following the links to here: https://ib-aid.com/en/transactions-in-firebird-acid-isolation-levels-deadlocks-and-update-conflicts-resolution/  it would seem that it's not really a `deadlock` per se (there's only one row in one table, it's not that there are two transactions trying to update multiple rows/table and they've grabbed locks in different orders and are waiting for each other to release the lock to proceed).  However, it seems that is the design of Firebird: if 2 transactions want to update the same row, only 1 succeeds and the other fails. 

While I wait to see the full stacktrace, here's some suggestions for things you could try:

A)  change your loadbalancer to sticky sessions - this will reduce the likelihood of simultaneous concurrent requests _between_ nodes, but not within a node
B)  change to using the `DefaultSessionCache` - configure the `EVICT_ON_SESSION_EXIT` mode to ensure the session is evicted from the cache when the last simultaneous request exists. This will ensure integrity of the session (and sessiondata) _within_ a node. If you don't also do A) then all the pitfalls of non-sticky sessions still apply (but you're already dealing with those). 
C) exclusive of A) and B) you could try fine tuning your firebird setup. This documentation refers to table-level locking, which may prevent the concurrent update errors: https://firebirdsql.github.io/jaybird-manual/jaybird_manual.html#transactions-table-reservation.  You could also (maybe) retry failed updates. Both of those options go beyond the scope of the generic `JDBCSessionDataStore`, so you'd need to subclass it to implement the behaviour that seems best for your application

**Comment by VASConsulting** [comment]
> @janbartel I am following all your instructions, meanwhile I am sending the stack trace for you to review
> Does your application write to the session very frequently, or is it read-mostly once it is created?
Most of the time, it is read only (we just write when creating and when exiting) 
> I am also assuming your loadbalancer is not using sticky sessions?
(Stand alone application that, during log in process presents the issue)
Right now our app is runnin from the IntelliJ IDE (no loadbalancer ...
we use containers and loadbalancer just in our test and production platform)

`/usr/lib/jvm/java-17-openjdk-17.0.7.0.7-5.fc37.x86_64/bin/java -javaagent:/var/lib/snapd/snap/intellij-idea-community/442/lib/idea_rt.jar=35115:/var/lib/snapd/snap/intellij-idea-community/442/bin -Dfile.encoding=UTF-8 -classpath /home/gsuarez/IdeaProjects/VueProjects/DATBright/build/classes/kotlin/main:/home/gsuarez/IdeaProjects/VueProjects/DATBright/build/resources/main:/home/gsuarez/.gradle/caches/modules-2/files-2.1/io.javalin/javalin/5.6.1/8ba687740a87baf2b786de22c331b86e3b63da35/javalin-5.6.1.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.8.21/67f57e154437cd9e6e9cf368394b95814836ff88/kotlin-stdlib-jdk8-1.8.21.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/2.0.7/bfa4d4dad645a5b11c022ae0043bac2df6cf16b5/slf4j-simple-2.0.7.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-kotlin/2.15.0/8a0d8abf0efc4c9bdeb54d0049078ffec1a2f35f/jackson-module-kotlin-2.15.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.webjars.npm/vue/2.6.14/8e9364ec340efc157ab40ccc0be59d0a3a29557f/vue-2.6.14.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.webjars.npm/vuetify/2.6.9/7d778d89aecfd0948239f6e9890a7820b1b7ad7e/vuetify-2.6.9.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.webjars.npm/mdi__font/7.0.96/6b731e6848b707f951d215b4254d58b5c020c641/mdi__font-7.0.96.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.webjars/font-awesome/6.3.0/413ca3b565acbea94a60c85289af00951dfdcd25/font-awesome-6.3.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.webjars.npm/roboto-fontface/0.10.0/7ec3471e43e7fa5693e831b81fec449e97675779/roboto-fontface-0.10.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.webjars.npm/sweetalert2/11.6.15/4d28eebee0643d6af8285db609ccb56f4d31d23a/sweetalert2-11.6.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/com.zaxxer/HikariCP/5.0.1/a74c7f0a37046846e88d54f7cb6ea6d565c65f9c/HikariCP-5.0.1.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.firebirdsql.jdbc/jaybird/5.0.2.java11/10ba111adcdc3a5a59fea6cb899f7111b7a2b893/jaybird-5.0.2.java11.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/com.github.seratch/kotliquery/1.9.0/7f672ac0d395357c08535e94e81b5b96b46f16d1/kotliquery-1.9.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.mindrot/jbcrypt/0.4/af7e61017f73abb18ac4e036954f9f28c6366c07/jbcrypt-0.4.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.8.21/662838019bc1141f8a311180d93b9e13765c7f55/kotlin-reflect-1.8.21.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-email/1.5/e8e677c6362eba14ff3c476ba63ccb83132dbd52/commons-email-1.5.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.12.0/c6842c86792ff03b9f1d1fe2aab8dc23aa6c6f0e/commons-lang3-3.12.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/24.0.1/13c5c75c4206580aa4d683bffee658caae6c9f43/annotations-24.0.1.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.websocket/websocket-jetty-server/11.0.15/f7b97864b77599f594b8d44449acad3f6f60920f/websocket-jetty-server-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-webapp/11.0.15/ba945a86dbd910346c32e1eacdb36aa15a5c18dd/jetty-webapp-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-server/11.0.15/ce2fc063638c702f2df749dd23cde6c41c7b0c06/jetty-server-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/2.0.7/41eb7184ea9d556f23e18b5cb99cad1f8581fc00/slf4j-api-2.0.7.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.websocket/websocket-jetty-api/11.0.15/32eba5745565d8a02c4564abb5c20a1047c7e785/websocket-jetty-api-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.8.21/7473b8cd3c0ef9932345baf569bc398e8a717046/kotlin-stdlib-jdk7-1.8.21.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.21/43d50ab85bc7587adfe3dda3dbe579e5f8d51265/kotlin-stdlib-1.8.21.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.15.0/d41caa3a4e9f85382702a059a65c512f85ac230/jackson-databind-2.15.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.15.0/89b0fd554928425a776a6e97ed010034312af21d/jackson-annotations-2.15.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/com.sun.mail/javax.mail/1.5.6/ab5daef2f881c42c8e280cbe918ec4d7fdfd7efe/javax.mail-1.5.6.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-annotations/11.0.15/f63b1aef0df6076243af8bc4ecd6e64ddc4163c2/jetty-annotations-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.websocket/websocket-servlet/11.0.15/cd9d5af178d8f78ffd155c9b1355a4ae45ece6b4/websocket-servlet-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-servlet/11.0.15/1947cbf5c92f4edf9712a162f4926c838dfd03a/jetty-servlet-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.websocket/websocket-jetty-common/11.0.15/f03ea072ebf26547c33f15890026e253daf02c93/websocket-jetty-common-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.toolchain/jetty-jakarta-servlet-api/5.0.2/27fce6d666a203526236d33d00e202a4136230f/jetty-jakarta-servlet-api-5.0.2.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-xml/11.0.15/8189a8dfd871415b768d6568476e33a553e80b3/jetty-xml-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-http/11.0.15/6eb099ce51496de87ecfe9b8c62c2e8f3f5e848/jetty-http-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-io/11.0.15/e334388b4ae2aa4c59a1715f707237e31d663d81/jetty-io-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.21/d749cd5ae25da36d06e5028785038e24f9d37976/kotlin-stdlib-common-1.8.21.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.15.0/12f334a1dc9c6d2854c43ae314024dde8b3ad572/jackson-core-2.15.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/javax.activation/activation/1.1/e6cb541461c2834bdea3eb920f1884d1eb508b50/activation-1.1.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-plus/11.0.15/e9a632c5a041c0e3ac473e902e9a1fbe5af9d558/jetty-plus-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/jakarta.annotation/jakarta.annotation-api/2.1.1/48b9bda22b091b1f48b13af03fe36db3be6e1ae3/jakarta.annotation-api-2.1.1.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/9.5/19ab5b5800a3910d30d3a3e64fdb00fd0cb42de0/asm-commons-9.5.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/9.5/dc6ea1875f4d64fbc85e1691c95b96a3d8569c90/asm-9.5.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.websocket/websocket-core-server/11.0.15/9de6c8b8c2c0c8760d0c2934462a32b0887f2b6f/websocket-core-server-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-security/11.0.15/b59d5d57f476502b5382a53ef208e2c382c3e2d2/jetty-security-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.websocket/websocket-core-common/11.0.15/84dc1b8cc2f36f7c7113dd9247d17ab3f842c132/websocket-core-common-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-util/11.0.15/de81765b3da6dc68ddf5acc87dfe9a63408c64fb/jetty-util-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/ch.randelshofer/fastdoubleparser/0.8.0/85c25540369921659556ead85e02c99ef0d24280/fastdoubleparser-0.8.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-jndi/11.0.15/b30ae05ab1e2b9db05ff09dffd1e71ed3b6d7769/jetty-jndi-11.0.15.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/jakarta.transaction/jakarta.transaction-api/2.0.0/24a0525b4acfbca4086d2f1278be3a084fe1c67d/jakarta.transaction-api-2.0.0.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/9.5/fd33c8b6373abaa675be407082fdfda35021254a/asm-tree-9.5.jar:/home/gsuarez/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.11.0/da4c58430c8f55f3c3fdf13653d2b629ce1fcc1d/joda-time-2.11.0.jar MainKt
[main] INFO Config - Database url: jdbc:firebirdsql://localhost:3050/dat-bright?encoding=UTF8
[main] INFO Config - Database user: sysdba
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[main] INFO com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.firebirdsql.jdbc.FBConnection@1e9e725a
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[main] INFO io.javalin.Javalin - Starting Javalin ...
[main] INFO io.javalin.Javalin - No port specified, starting on port 8080. Call start(port) to change ports.
[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.15; built: 2023-04-11T18:37:53.775Z; git: 5bc5e562c8d05c5862505aebe5cf83a61bdbcb96; jvm 17.0.7+7
[main] INFO org.eclipse.jetty.server.session.DefaultSessionIdManager - Session workerName=node0
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started i.j.j.@436c81a3{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@3c73951{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started Server@7bd4937b{STARTING}[11.0.15,sto=0] @572ms
[main] INFO io.javalin.Javalin - 
       __                  ___          ______
      / /___ __   ______ _/ (_)___     / ____/
 __  / / __ `/ | / / __ `/ / / __ \   /___ \
/ /_/ / /_/ /| |/ / /_/ / / / / / /  ____/ /
\____/\__,_/ |___/\__,_/_/_/_/ /_/  /_____/

       https://javalin.io/documentation

[main] INFO io.javalin.Javalin - Static file handler added: StaticFileConfig(hostedPath=/, directory=public, location=CLASSPATH, precompress=false, aliasCheck=null, headers={Cache-Control=max-age=0}, mimeTypes=io.javalin.http.staticfiles.MimeTypesConfig@3163987e). File system location: 'file:///home/gsuarez/IdeaProjects/VueProjects/DATBright/build/resources/main/public/'
[main] INFO io.javalin.Javalin - Static file handler added: StaticFileConfig(hostedPath=/, directory=META-INF/resources/webjars, location=CLASSPATH, precompress=false, aliasCheck=null, headers={Cache-Control=max-age=31622400}, mimeTypes=io.javalin.http.staticfiles.MimeTypesConfig@3af37506). File system location: 'jar:file:/home/gsuarez/.gradle/caches/modules-2/files-2.1/org.webjars.npm/vue/2.6.14/8e9364ec340efc157ab40ccc0be59d0a3a29557f/vue-2.6.14.jar!/META-INF/resources/webjars'
[main] INFO io.javalin.Javalin - Listening on http://localhost:8080/
[main] INFO io.javalin.Javalin - You are running Javalin 5.6.1 (released June 22, 2023).
[main] INFO io.javalin.Javalin - Javalin started in 402ms \o/
[JettyServerThreadPool-27] INFO Main - IP:127.0.0.1 GET / completed in 6.391026 ms
[JettyServerThreadPool-27] INFO Main - IP:127.0.0.1 GET /login completed in 176.52129 ms
[JettyServerThreadPool-25] INFO Main - IP:127.0.0.1 POST /api/sign-in completed in 240.29192 ms
[JettyServerThreadPool-26] INFO Main - IP:127.0.0.1 GET / completed in 19.008066 ms
[ForkJoinPool.commonPool-worker-1] INFO Main - IP:127.0.0.1 GET /api/headquarters completed in 34.971294 ms
[ForkJoinPool.commonPool-worker-1] INFO Main - IP:127.0.0.1 GET /api/image completed in 8.520611 ms
[ForkJoinPool.commonPool-worker-1] INFO Main - IP:127.0.0.1 GET /api/image completed in 5.89879 ms
[ForkJoinPool.commonPool-worker-2] INFO Main - IP:127.0.0.1 GET /api/image completed in 11.100439 ms
[ForkJoinPool.commonPool-worker-1] INFO Main - IP:127.0.0.1 GET /api/image completed in 13.093023 ms
[ForkJoinPool.commonPool-worker-2] INFO Main - IP:127.0.0.1 GET /api/image completed in 12.427012 ms
[ForkJoinPool.commonPool-worker-3] INFO Main - IP:127.0.0.1 GET /api/image completed in 7.759323 ms
[ForkJoinPool.commonPool-worker-4] INFO Main - IP:127.0.0.1 GET /api/image completed in 9.392712 ms
[ForkJoinPool.commonPool-worker-4] WARN org.eclipse.jetty.server.session.SessionHandler - Unable to release Session Session@2f0ad7dd{id=node0wiwkxg8m6rxctqcepe0ui6zl0,x=node0wiwkxg8m6rxctqcepe0ui6zl0.node0,req=0,res=true}
java.sql.SQLException: deadlock; update conflicts with concurrent update; concurrent transaction number is 5601 [SQLState:40001, ISC error code:335544336]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:618)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:384)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:152)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:97)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.processOperation(AbstractWireOperations.java:207)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readOperationResponse(AbstractWireOperations.java:173)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readResponse(AbstractWireOperations.java:167)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.readResponse(AbstractFbWireDatabase.java:216)
	at org.firebirdsql.gds.ng.wire.version10.V10Statement.execute(V10Statement.java:273)
	at org.firebirdsql.jdbc.FBStatement.internalExecute(FBStatement.java:878)
	at org.firebirdsql.jdbc.FBPreparedStatement.internalExecute(FBPreparedStatement.java:562)
	at org.firebirdsql.jdbc.FBPreparedStatement.executeUpdate(FBPreparedStatement.java:199)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.eclipse.jetty.server.session.JDBCSessionDataStore.doUpdate(JDBCSessionDataStore.java:786)
	at org.eclipse.jetty.server.session.JDBCSessionDataStore.doStore(JDBCSessionDataStore.java:712)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.lambda$store$2(AbstractSessionDataStore.java:191)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1448)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1485)
	at org.eclipse.jetty.server.session.SessionContext.run(SessionContext.java:87)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.store(AbstractSessionDataStore.java:202)
	at org.eclipse.jetty.server.session.AbstractSessionCache.release(AbstractSessionCache.java:564)
	at org.eclipse.jetty.server.session.SessionHandler.complete(SessionHandler.java:358)
	at org.eclipse.jetty.server.Request.lambda$leaveSession$0(Request.java:427)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1448)
	at org.eclipse.jetty.server.Request.leaveSession(Request.java:427)
	at org.eclipse.jetty.server.Request.onCompleted(Request.java:1469)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:966)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:485)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:457)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1208)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:727)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:67)
	at io.javalin.http.servlet.JavalinServlet.writeResponseAndLog(JavalinServlet.kt:108)
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:57)
	at io.javalin.http.servlet.JavalinServlet.handleUserFuture$lambda$3(JavalinServlet.kt:69)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: deadlock
[ForkJoinPool.commonPool-worker-2] WARN org.eclipse.jetty.server.session.SessionHandler - Unable to release Session Session@5dc8c92{id=node0wiwkxg8m6rxctqcepe0ui6zl0,x=node0wiwkxg8m6rxctqcepe0ui6zl0.node0,req=0,res=true}
java.sql.SQLException: deadlock; update conflicts with concurrent update; concurrent transaction number is 5601 [SQLState:40001, ISC error code:335544336]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:618)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:384)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:152)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:97)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.processOperation(AbstractWireOperations.java:207)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readOperationResponse(AbstractWireOperations.java:173)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readResponse(AbstractWireOperations.java:167)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.readResponse(AbstractFbWireDatabase.java:216)
	at org.firebirdsql.gds.ng.wire.version10.V10Statement.execute(V10Statement.java:273)
	at org.firebirdsql.jdbc.FBStatement.internalExecute(FBStatement.java:878)
	at org.firebirdsql.jdbc.FBPreparedStatement.internalExecute(FBPreparedStatement.java:562)
	at org.firebirdsql.jdbc.FBPreparedStatement.executeUpdate(FBPreparedStatement.java:199)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.eclipse.jetty.server.session.JDBCSessionDataStore.doUpdate(JDBCSessionDataStore.java:786)
	at org.eclipse.jetty.server.session.JDBCSessionDataStore.doStore(JDBCSessionDataStore.java:712)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.lambda$store$2(AbstractSessionDataStore.java:191)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1448)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1485)
	at org.eclipse.jetty.server.session.SessionContext.run(SessionContext.java:87)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.store(AbstractSessionDataStore.java:202)
	at org.eclipse.jetty.server.session.AbstractSessionCache.release(AbstractSessionCache.java:564)
	at org.eclipse.jetty.server.session.SessionHandler.complete(SessionHandler.java:358)
	at org.eclipse.jetty.server.Request.lambda$leaveSession$0(Request.java:427)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1448)
	at org.eclipse.jetty.server.Request.leaveSession(Request.java:427)
	at org.eclipse.jetty.server.Request.onCompleted(Request.java:1469)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:966)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:485)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:457)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1208)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:727)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:67)
	at io.javalin.http.servlet.JavalinServlet.writeResponseAndLog(JavalinServlet.kt:108)
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:57)
	at io.javalin.http.servlet.JavalinServlet.handleUserFuture$lambda$3(JavalinServlet.kt:69)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: deadlock
`
Thanks a lot @janbartel  ...

**Comment by janbartel** [comment]
@VASConsulting is this issue resolved?

**Comment by janbartel** [comment]
There's been no updates on this for a year, so I'm going to close. If necessary we can reopen.
