### ISSUE TITLE
Sessions created via https throw "invalid for write" exception

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1014]
If a session is created via a secure request (ie https), then the following exception is thrown:

java.lang.IllegalStateException: Not valid for write: id=node0v4tuib9mp2np18xkv8jy2jt840 not resident
	at org.eclipse.jetty.server.session.Session.checkValidForWrite(Session.java:611)
	at org.eclipse.jetty.server.session.Session.setAttribute(Session.java:748)
	at org.eclipse.jetty.server.session.SessionHandler.newHttpSession(SessionHandler.java:796)
	at org.eclipse.jetty.server.Request.getSession(Request.java:1530)

**Comment by janbartel** [comment]
Fixed in jetty-9.4 and above.

**Comment by shark-horse** [comment]
We're getting this in 9.4.20.v20190813 when we use a `NullSessionCache`, but not when we use `DefaultSessionCache`:

```
2019-10-01 12:28:54.948 [INFO] [Jetty] log - Logging initialized @4455ms to org.eclipse.jetty.util.log.Slf4jLog
2019-10-01 12:28:55.448 [INFO] [org.reflections.Reflections] Reflections took 428 ms to scan 1 urls, producing 245 keys and 2556 values 
2019-10-01 12:28:58.786 [INFO] [Jetty] Server - jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_212-b04
2019-10-01 12:28:58.794 [INFO] [Jetty] session - DefaultSessionIdManager workerName=my-awesome-computer
2019-10-01 12:28:58.795 [INFO] [Jetty] session - my-awesome-computer Scavenging every 11000ms
2019-10-01 12:28:58.839 [INFO] [Jetty] ContextHandler - Started o.e.j.s.ServletContextHandler@37c3f600{/,null,AVAILABLE,@App}
2019-10-01 12:28:58.846 [INFO] [Jetty] ContextHandler - Started o.e.j.s.ServletContextHandler@-3a3fa988{/,null,AVAILABLE,@Admin}
2019-10-01 12:28:58.846 [INFO] [Jetty] ContextHandler - Started o.e.j.s.ServletContextHandler@-43d7c3c5{/,null,AVAILABLE,@Health}
2019-10-01 12:28:58.863 [INFO] [Jetty] AbstractConnector - Started App@6ff6d367{HTTP/1.1,[http/1.1, h2c]}{localhost:8081}
2019-10-01 12:28:58.865 [INFO] [Jetty] AbstractConnector - Started Admin@11002256{HTTP/1.1,[http/1.1]}{localhost:8088}
2019-10-01 12:28:58.867 [INFO] [Jetty] AbstractConnector - Started Health@ceecb326{HTTP/1.1,[http/1.1]}{localhost:9100}
2019-10-01 12:28:58.868 [INFO] [Jetty] Server - Started @8375ms
...
2019-10-01 12:29:04.752 [INFO] [Jetty] TypeUtil - JVM Runtime does not support Modules
Trying to execute transaction asynchronously
Not valid for write: id=<huge-id> not resident
java.lang.IllegalStateException: Not valid for write: id=<huge-id> not resident
	at org.eclipse.jetty.server.session.Session.checkValidForWrite(Session.java:636)
	at org.eclipse.jetty.server.session.Session.setAttribute(Session.java:767)
	at <our-code>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:819)
```

I can't give you minimal steps to reproduce this right now, but I can tell you more about our platform. We're using embedded Jetty with a `JDBCSessionDataStore`. This happens on both Windows 10 and Ubuntu 18.04.
```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
Eclipse OpenJ9 VM (build openj9-0.14.2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190521_315 (JIT enabled, AOT enabled)
OpenJ9   - 4b1df46fe
OMR      - b56045d2
JCL      - a8c217d402 based on jdk8u212-b04)
```

**Comment by joakime** [comment]
Can you provide a minimal reproduction case?

**Comment by shark-horse** [comment]
I'll post if-and-when I do. :)

**Comment by janbartel** [comment]
@shark-horse it looks from the stack trace like you have retained a reference to a Session object that one of your application threads is accessing outside the scope of a request.  It is never good practise for an application to retain a reference to the session object - if you need to access a session you should always call request.getSession().

When using the NullSessionCache, the session is never resident in the server's memory, but is accessible for the duration of the request: after that time, you cannot write to the session.  When using the DefaultSessionCache the session is retained in the server's memory so that it can be shared amongst concurrent and sequential requests, so you will not see the "non resident" exception (but you shouldn't retain a reference to it anyway).

**Comment by shark-horse** [comment]
@janbartel Ah, you're exactly right! Thank you.

**Comment by shark-horse** [comment]
@janbartel I might have agreed a little too soon. Why is it "never good practise for an application to retain a reference to the session object"? In our case it's only for a second after the request ends. I see [examples](https://stackoverflow.com/a/1499625/5447019) on the web of people suggesting to keep up with a map of sessions by id so that they can be looked up by id when there is no request. The Java Servlet 3 spec says:

> Multiple servlets executing request threads may have active access to the same
session object at the same time. The container must ensure that manipulation of
internal data structures representing the session attributes is performed in a thread
safe manner. 

I don't think it's thread-safe to kill the session contents when the request is over.

That said, I'm not complaining if you say NullSessionCache is fine as it is because it's a non-default option. We don't need to use NullSessionCache anyway; I'm just trying to understand with greater certainty if we did something that would cause nondeterministic behavior before I take time to change it.

(Sorry if my case is not on-topic with the original issue--I can post elsewhere if you like.)

**Comment by janbartel** [comment]
@shark-horse it is not a good idea to retain references to session objects because the lifecycle of these objects are not under control of the application, but the container.  There is nothing in the servlet spec that says that if an application calls getSession() twice that the same HttpSession object is returned: access to the same _session data_ must be provided in a thread-safe way, but there is no requirement for the same _object_ to be returned. Thus, applications should not retain references to container managed resources like HttpSessions - references to lists of session ids maybe, but not HttpSessions themselves.

Likewise there is no provision in the servlet spec to access HttpSessions outside of a HttpServletRequest: the api requires that a HttpSession is obtained only from a call to HttpServletRequest.getSession() or HttpServletRequest.getSession(boolean). In the case of async servlet handling, it's also very hairy trying to access a HttpSession from a HttpServletRequest, because it is difficult to determine what, if any, context the request is in (and session data must never be shared between contexts as mandated by the spec). Thus, to safely access session data with async, it is best to copy out any of the session attributes you want to access.

In fact, in your case you are trying to mutate session data outside of a request - which I strongly recommend you never do:  containers may passivate the HttpSession when the request exists in order to persist the attributes. Thus, depending on the timing of when you're mutating the session, those changes may or make not make it into the backing store, so that if the session ever needs to be retrieved from the store again (eg because the session migrates to a different node, or is recovered on the same node after an outage) you can't be sure of the attribute contents.

**Comment by shark-horse** [comment]
@janbartel Thank you for explaining that. I had never heard of session passivation and activation until now. The fact that the Servlet API only has `request.getSession(..)` to get a session has always made me suspicious of solutions involving a cache of `HttpSession` objects.
