### ISSUE TITLE
basehome error when enabling slf4j-simple-impl

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse/jetty.project#1019]
Getting the following error when attempting to activated the slf4j-simple-impl module for use with the logging-slf4j module. 

```
java -jar ../start.jar --add-to-start=slf4j-simple-impl
INFO  : slf4j-simple-impl initialized in ${jetty.base}/start.d/slf4j-simple-impl.ini
INFO  : resources       transitively enabled
DOWNLD: http://central.maven.org/maven2/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar to ${jetty.base}/lib/slf4j/slf4j-simple-1.7.21.jar
java.lang.IllegalArgumentException: File does not exist: basehome:modules/slf4j-impl
	at org.eclipse.jetty.start.fileinits.BaseHomeFileInitializer.create(BaseHomeFileInitializer.java:52)
	at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:282)
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:321)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:248)
	at org.eclipse.jetty.start.Main.start(Main.java:405)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
MKDIR : ${jetty.base}/resources
WARN  : Failed to process all file resources.
 - [IllegalArgumentException] File does not exist: basehome:modules/slf4j-impl - null
java.lang.RuntimeException: Failed to process all file resources.
 - [IllegalArgumentException] File does not exist: basehome:modules/slf4j-impl - null
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:341)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:248)
	at org.eclipse.jetty.start.Main.start(Main.java:405)
	at org.eclipse.jetty.start.Main.main(Main.java:75)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

**Comment by joakime** [comment]
This appears to have been fixed in #1023
