### ISSUE TITLE
JSTL URI can not be resolved

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#10208]
**Jetty version(s)**
jetty 12

** Description **

The Jetty JSP demo app errors with the stack trace below when clicking the _JSTL Expression_ link.

** Output **

2023-08-01 12:32:09.050:WARN :oejes.ServletChannel:qtp399931359-38: /jetty-ee10-demo-jsp-webapp-12.0.0.beta4/jstl.jsp
org.apache.jasper.JasperException: The absolute uri: [http://java.sun.com/jsp/jstl/core] cannot be resolved in either web.xml or the jar files deployed with this application
        at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:54)
        at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:294)
        at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:81)
        at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTldResourcePath(TagLibraryInfoImpl.java:251)
        at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:122)
        at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:429)
        at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:487)
        at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1444)
        at org.apache.jasper.compiler.Parser.parse(Parser.java:138)
        at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:245)
        at org.apache.jasper.compiler.ParserController.parse(ParserController.java:106)
        at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:211)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:396)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:372)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:603)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:396)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:380)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:328)
        at org.eclipse.jetty.ee10.jsp.JettyJspServlet.service(JettyJspServlet.java:101)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
        at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1369)
        at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1608)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1541)
        at org.eclipse.jetty.ee10.servlet.ServletChannel$RequestDispatchable.dispatch(ServletChannel.java:910)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:686)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:483)
        at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:510)
        at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:663)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:808)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:179)
        at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
        at org.eclipse.jetty.server.Server.handle(Server.java:177)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:616)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:480)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jmcc0nn3ll** [comment]
_Mapping to &lt;jsp-file&gt;_ option as well.

**Comment by joakime** [comment]
Both of the URLs in the demos work for me.

```
http://localhost:8080/ee10-demo-jsp/jstl.jsp
http://localhost:8080/ee10-demo-jsp/foo/
```

Which URLs are you using when you triggered this exception?

**Comment by jmcc0nn3ll** [comment]
This is a false alarm, I didn't add the jstl module.

**Comment by joakime** [comment]
To be clear, jesse manually copied the `ee10-demo-jsp.war` to the `${jetty.base}/webapps/` directory.
But didn't have the `ee10-jstl` module enabled (which it requires).

He only had `server,http,ee10-deploy,ee10-jsp` enabled when he encountered this stack trace.
