### ISSUE TITLE
UnknownFormatConversionException in `start.jar --debug` if path has `%` sign

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#10213]
**Jetty version(s)**
12.0.0

**Java version/vendor** `(use: java -version)`
17.0.5

**OS type/version**
Linux

**Description**
If a scanned directory for the jetty.base has a percent sign, and debug is enabled, it can result in an `java.util.UnknownFormatConversionException`

Example: create a base directory called `foo%bar` and do the following

```
$ mkdir foo%bar
$ cd foo%bar
$ java -jar /path/to/jetty-home-12.0.0.jar --add-modules=http,core-deploy
$ java -jar /path/to/jetty-home-12.0.0.jar --debug --list-config
```

```
 java.util.UnknownFormatConversionException: Conversion = 'b'
 	at java.base/java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2855)
 	at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2891)
 	at java.base/java.util.Formatter.parse(Formatter.java:2747)
 	at java.base/java.util.Formatter.format(Formatter.java:2671)
 	at java.base/java.io.PrintStream.format(PrintStream.java:1209)
 	at java.base/java.io.PrintStream.printf(PrintStream.java:1105)
 	at org.eclipse.jetty.start.StartLog.outLog(StartLog.java:44)
 	at org.eclipse.jetty.start.StartLog.debug(StartLog.java:51)
 	at org.eclipse.jetty.start.PathFinder.addHit(PathFinder.java:45)
 	at org.eclipse.jetty.start.PathFinder.preVisitDirectory(PathFinder.java:82)
 	at org.eclipse.jetty.start.PathFinder.preVisitDirectory(PathFinder.java:31)
 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2817)
 	at org.eclipse.jetty.start.BaseHome.getPaths(BaseHome.java:374)
 	at org.eclipse.jetty.start.StartArgs.expandModules(StartArgs.java:435)
 	at org.eclipse.jetty.start.StartArgs.expandEnvironments(StartArgs.java:216)
 	at org.eclipse.jetty.start.Main.processCommandLine(Main.java:375)
 	at org.eclipse.jetty.start.Main.main(Main.java:74)
 
 Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
        java -jar $JETTY_HOME/start.jar --help  # for more information
```

This is due to a bad usage of the `StartLog.debug()` method.

**Comment by joakime** [comment]
Merged PR #10214
