### ISSUE TITLE
HttpConfiguration.setIdleTimeout() breaks long running requests

### ISSUE THREAD

**Issue by ekupcik** [eclipse/jetty.project#10229]
**Jetty version(s)**
12 beta 4

**Java version/vendor** `(use: java -version)`
17

**OS type/version**
Windows

**Description**
I am not sure whether this might be intentional or not. But it looks more like a bug to me or at least like an unexpected change in Jetty 12.

From my understanding HttpConfiguration.idleTimeout refers to timeout in IO operations, not long running application code. In my code i was setting idleTimeoutout in Jetty 9 and 10 without any issues but with Jetty 12 long running request fail this error when the application code takes longer than the idleTimeout. Also note the suppressed NPE

<html><body>
<h2>HTTP ERROR 500 java.util.concurrent.TimeoutException: Idle timeout expired: 5015/5000 ms</h2>

URI: | http://localhost:8080/
-- | --
500
java.util.concurrent.TimeoutException: Idle timeout expired: 5015/5000 ms
java.util.concurrent.TimeoutException: Idle timeout expired: 5015/5000 ms

<h3>Caused by:</h3><pre>java.util.concurrent.TimeoutException: Idle timeout expired: 5015/5000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:112)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "onFailure" is null
		at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$2(HttpChannelState.java:437)
		at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
		... 1 more
</pre>
</body>
</html>

**How to reproduce?**

``` java
        public static void main(String... args) throws Exception
	{
		HttpServlet servlet = new HttpServlet()
		{
			@Override
			protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException
			{
				try
				{
					Thread.sleep(10000);
				}
				catch (InterruptedException e)
				{
					Thread.currentThread().interrupt();
				}

				resp.getWriter().printf("hello world");
			}
		};

		ServletContextHandler handler = new ServletContextHandler();
		handler.setContextPath("/");
		handler.addServlet(servlet, "/*");

		Server server = new Server();
		server.setHandler(handler);

		HttpConfiguration configuration = new HttpConfiguration();
		configuration.setIdleTimeout(5000);

		ServerConnector connector = new ServerConnector(server, new HttpConnectionFactory(configuration));
		connector.setPort(8080);
		server.setConnectors(new ServerConnector[]{connector});

		server.start();
	}
```

**Comment by gregw** [comment]
Unintentional change.  We  know that the servlet spec requires that long running requests are not interrupted by idle timeout.... however, we struggle to not close the connection under them sometimes.
We have the mechanism to ignore idle timeouts, we just need to correctly use it in ee10 servlets.  This might not make 12.0.0.... specially as we need to review why our tests for this didn't spot it.  But 12.0.1 is only weeks away.

**Comment by gregw** [comment]
I've created draft PR #10233 that has a unit test that reproduces the problem.

Note that I also do not like the NPE that is suppressed, so there are at least 2 issues to fix.
