### ISSUE TITLE
com.sterlingcommerce.perimeter.api.nio.PsSocketChannel throws java.io.IOException: FULL_CLOSE when running on Jetty 9.4.51 and IBM JDK

### ISSUE THREAD

**Issue by 4devwithgit** [eclipse/jetty.project#10223]
**Jetty version(s)**

9.4.51

**Java version/vendor** `(use: java -version)`
IBM JDK 8 SR7 FP20

**OS type/version**
linux RHEL7, windows

**Description**

Errors found in jetty logs with 9.4.51

Below exception observed in jetty logs:

```
[2023-08-03 09:38:27.425] 
ALL 000000000000 GLOBAL_SCOPE 2023-08-03 09:38:27.410:DBUG:oejis.SslConnection:qtp_SELENIUM_HTTP_SANITY_512_SHA1_HttpServerAdapter_node1-114647: DecryptedEndPoint@b8cf66c3{l=/127.0.0.1:59095,r=/127.0.0.1:61678,CLOSED,fill=,flush=,to=81/30000} stored flush exception org.eclipse.jetty.io.EofException
   at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:280)
   at org.eclipse.jetty.io.ssl.SslConnection.networkFlush(SslConnection.java:489)
   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1112)
   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doShutdownOutput(SslConnection.java:1329)
   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doClose(SslConnection.java:1411)
   at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:220)
   at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
   at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175)
   at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:254)
   at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:233)
   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1620)
   at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:381)
   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:265)
   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
   at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
   at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
   at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:152)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
   at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
   at java.lang.Thread.run(Thread.java:825) 
Caused by: java.io.IOException: FULL_CLOSE
   at com.sterlingcommerce.perimeter.api.nio.PsSocketChannel.write(PsSocketChannel.java:382)
   at java.nio.channels.SocketChannel.write(SocketChannel.java:513)
   at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:274)
   at org.eclipse.jetty.io.ssl.SslConnection.networkFlush(SslConnection.java:489)
   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1112)
   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doShutdownOutput(SslConnection.java:1329)
   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doClose(SslConnection.java:1411)
   at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:220)
   at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
   at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175)
   at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:254)
   at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:233)
   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1620)
   at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:381)
   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:265)
   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
   at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
   at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
   at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
   at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:152)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
   at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
   at java.lang.Thread.run(Thread.java:825) [2023-08-03 09:38:27.425] 
ALL 000000000000 GLOBAL_SCOPE 2023-08-03 09:38:27.425:DBUG:oejis.SslConnection:qtp_SELENIUM_HTTP_SANITY_512_SHA1_HttpServerAdapter_
```

Another log observation,
```
[2023-08-03 15:59:36.136] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:36.136:DBUG:oejis.SslConnection:qtp_SELENIUM_HTTP_SANITY_512_SHA1_HttpServerAdapter_node1-2211: <flush  SslConnection@6e531712::SocketChannelEndPoint@33c923b7{l=/127.0.0.1:59095,r=/127.0.0.1:44128,OPEN,fill=,flush=,to=5/30000}

{io=0/0,kio=0,kro=5}
>SslConnection@6e531712{NOT_HANDSHAKING,eio=-1/85,di=-1,fill=IDLE,flush=IDLE}~>DecryptedEndPoint@79b29eca{l=/127.0.0.1:59095,r=/127.0.0.1:44128,CLOSED,fill=,flush=-,to=114/30000}=>HttpConnection@3a1d2f87[p=HttpParser\{s=CLOSED,0 of -1},g=HttpGenerator@433bebef\{s=START}]=>HttpChannelOverHttp@84f7f389{s=HttpChannelState@3e954f80

{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}
[2023-08-03 15:59:36.139] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:36.138:DBUG:oejis.SslConnection:qtp_SELENIUM_HTTP_SANITY_512_SHA1_HttpServerAdapter_node1-2211: <c.onFillable SslConnection@6e531712::SocketChannelEndPoint@33c923b7{l=/127.0.0.1:59095,r=/127.0.0.1:44128,CLOSED,fill=,flush=,to=7/30000}{io=0/0,kio=-1,kro=-1}->SslConnection@6e531712{NOT_HANDSHAKING,eio=1/85,di=-1,fill=IDLE,flush=IDLE}~>DecryptedEndPoint@79b29eca{l=/127.0.0.1:59095,r=/127.0.0.1:44128,CLOSED,fill=,flush=-,to=116/30000}=>HttpConnection@3a1d2f87[p=HttpParser\{s=CLOSED,0 of -1},g=HttpGenerator@433bebef\{s=START}]=>HttpChannelOverHttp@84f7f389{s=HttpChannelState@3e954f80{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0}
,r=1,c=false/false,a=IDLE,uri=null,age=0}
[2023-08-03 15:59:37.743] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:37.743:DBUG:oeji.CyclicTimeout:qtp-1964098795-2106: Installed timeout in 6000000 ms, existing wake up in 5948977 ms
[2023-08-03 15:59:37.766] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:37.766:DBUG:oeji.CyclicTimeout:qtp-1964098795-2126: Installed timeout in 6000000 ms, existing wake up in 5948953 ms
[2023-08-03 15:59:37.889] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:37.889:DBUG:oeji.CyclicTimeout:qtp-1964098795-2126: Installed timeout in 6000000 ms, existing wake up in 5948831 ms
[2023-08-03 15:59:40.063] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:40.062:DBUG:oeji.CyclicTimeout:qtp-1964098795-2106: Installed timeout in 6000000 ms, existing wake up in 5946657 ms
[2023-08-03 15:59:40.089] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:40.089:DBUG:oeji.CyclicTimeout:qtp-1964098795-2184: Installed timeout in 6000000 ms, existing wake up in 5946631 ms
[2023-08-03 15:59:40.172] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:40.172:DBUG:oeji.CyclicTimeout:qtp-1964098795-2184: Installed timeout in 6000000 ms, existing wake up in 5946547 ms
[2023-08-03 15:59:42.327] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:42.327:DBUG:oeji.CyclicTimeout:qtp-1964098795-2106: Installed timeout in 6000000 ms, existing wake up in 5944392 ms
[2023-08-03 15:59:42.347] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:42.347:DBUG:oeji.CyclicTimeout:qtp-1964098795-2135: Installed timeout in 6000000 ms, existing wake up in 5944373 ms
[2023-08-03 15:59:42.438] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:42.438:DBUG:oeji.CyclicTimeout:qtp-1964098795-2135: Installed timeout in 6000000 ms, existing wake up in 5944282 ms
[2023-08-03 15:59:44.649] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:44.649:DBUG:oeji.CyclicTimeout:qtp-1964098795-2106: Installed timeout in 6000000 ms, existing wake up in 5942071 ms
[2023-08-03 15:59:44.67] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:44.670:DBUG:oeji.CyclicTimeout:qtp-1964098795-2184: Installed timeout in 6000000 ms, existing wake up in 5942050 ms
[2023-08-03 15:59:44.783] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:44.783:DBUG:oeji.CyclicTimeout:qtp-1964098795-2184: Installed timeout in 6000000 ms, existing wake up in 5941937 ms
[2023-08-03 15:59:46.868] ALL 000000000000 GLOBAL_SCOPE 2023-08-03 15:59:46.868:DBUG:oeji.CyclicTimeout:qtp-1964098795-2106: Installed t
```

**How to reproduce?**
connecting to HTTP Server adapter running on the jetty and executing basic operations.

**Comment by olamy** [comment]
Please note Jetty 9.4 is End of Community support. See https://github.com/eclipse/jetty.project/issues/7958
Can you reproduce your issue with Jetty 10?

**Comment by 4devwithgit** [comment]
We do have plans to upgrade jetty to 10, but not immediately. The impact and scope of change is huge hence it needs larger planning.

**Comment by joakime** [comment]
```
Caused by: java.io.IOException: FULL_CLOSE
   at com.sterlingcommerce.perimeter.api.nio.PsSocketChannel.write(PsSocketChannel.java:382)
```

You have bugs in your PsSocketChannel or PsSelector, contact Sterling Commerce.
Not a Jetty bug.

See #6759

**Comment by 4devwithgit** [comment]
I am part of the Sterling commerce. Since these exceptions are logged by jetty, so reached out to you.
The bug reported in https://github.com/eclipse/jetty.project/issues/6759 is already addressed.

Also this was observed in 9.4.51, but didnt had these messages with 9.4.47.

**Comment by joakime** [comment]
Yes, it is logged by Jetty, but at DEBUG level.

The thrown IOException has the message `FULL_CLOSE`, an exception message that Jetty does not use.

https://github.com/search?q=repo%3Aeclipse%2Fjetty.project+FULL_CLOSE&type=code

It was thrown from com.sterlingcommerce.perimeter.api.nio.PsSocketChannel.write(PsSocketChannel.java:382)

That exception, from the sterling commerce code, was caught and wrapped in a EofException by Jetty.

https://github.com/eclipse/jetty.project/blob/b45c405e4544384de066f814ed42ae3dceacdd49/jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java#L272-L281

Which was then logged at DEBUG level at by SslConnection.

https://github.com/eclipse/jetty.project/blob/b45c405e4544384de066f814ed42ae3dceacdd49/jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java#L1524-L1525

Which eventually leads to a handshake failure.
This starts with the Exception being thrown from the Sterling Commerce code.

This is my final message on this issue for Jetty 9.x (as it's End of Community Support)

If you can replicate this on Jetty 10+ with OpenJDK (_not IBM JDK, esp when testing with SSL/TLS_) report back on this issue.

If it happens without your Sterling Commerce layer, then we have a Jetty behavior we need to address (and possibly fix).
If only happens when your Sterling Commerce layer is present, then that is useful to know, but harder for us to fix.

Please report back on this issue when you can replicate on a supported versions of Jetty.
