### ISSUE TITLE
Error on configuring slf4j-simple-impl module

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1023]
Testing jetty-9.4.0.RC1 in staging:

I configured the session-store-gcloud,session-store-cache modules, which produced an expected error:

ERROR : Module jcl-slf4j requires a module providing slf4j-impl from one of [slf4j-simple-impl, slf4j-logback, slf4j-jul, slf4j-log4j2, slf4j-log4j]
ERROR : Unsatisfied module dependencies: jcl-slf4j

However, I then enabled the slf4j-simple-impl module and got another error:

[2565] java -jar ../start.jar --add-to-start=slf4j-simple-impl
INFO  : slf4j-simple-impl initialized in ${jetty.base}/start.d/slf4j-simple-impl.ini
java.lang.IllegalArgumentException: File does not exist: basehome:modules/slf4j-impl
	at org.eclipse.jetty.start.fileinits.BaseHomeFileInitializer.create(BaseHomeFileInitializer.java:52)
	at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:282)
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:321)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:248)
	at org.eclipse.jetty.start.Main.start(Main.java:405)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
WARN  : Failed to process all file resources.
 - [IllegalArgumentException] File does not exist: basehome:modules/slf4j-impl - null
java.lang.RuntimeException: Failed to process all file resources.
 - [IllegalArgumentException] File does not exist: basehome:modules/slf4j-impl - null
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:341)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:248)
	at org.eclipse.jetty.start.Main.start(Main.java:405)
	at org.eclipse.jetty.start.Main.main(Main.java:75)

**Comment by joakime** [comment]
Seems related to issue #1020 ?

**Comment by gregw** [comment]
no so simple to do the impl of simple-impl  :)

**Comment by gregw** [comment]
@joakime no #1020 was just depending on resources when it was not required.  This one was just one place that `slf4j-impl` had not been renamed to `slf4j-simple-impl` when doing the overlay conversion.
