### ISSUE TITLE
CPU usages reaches 100%

### ISSUE THREAD

**Issue by prashanth007** [eclipse/jetty.project#1033]
I run jetty 9.2.18 in amazon ec2 instance.

Java Environment
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

At times, the server usage spikes to 100% and never comes down.

Did a little bit of googling to pin the issue to the selector threads.

Here is my stack trace:

"qtp1125981799-54-selector-ServerConnectorManager@1ad3c643/1" prio=10 tid=0x00007f0b4896c000 nid=0x452c runnable [0x00007f0b332f1000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x00000007014c62d0> (a sun.nio.ch.Util$2)
	- locked <0x00000007014c62c0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007010c2158> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:601)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

"qtp1125981799-53-selector-ServerConnectorManager@1ad3c643/0" prio=10 tid=0x00007f0b4865f000 nid=0x452b runnable [0x00007f0b333f2000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x000000070153a3d8> (a sun.nio.ch.Util$2)
	- locked <0x000000070153bd90> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000070102add0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:601)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

"qtp1125981799-52-acceptor-0@76d5ab05-ServerConnector@2ed233bc{SSL-http/1.1}{0.0.0.0:443}" prio=10 tid=0x00007f0b4865d000 nid=0x452a runnable [0x00007f0b334f3000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:241)
	- locked <0x000000070106feb0> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

"qtp1125981799-51-acceptor-0@7f5083c7-ServerConnector@6054fbbe{HTTP/1.1}{0.0.0.0:80}" prio=10 tid=0x00007f0b4865b000 nid=0x4529 runnable [0x00007f0b335f4000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:241)
	- locked <0x000000070106f270> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

"qtp1125981799-50-selector-ServerConnectorManager@372318b7/1" prio=10 tid=0x00007f0b48659000 nid=0x4528 runnable [0x00007f0b336f5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x00000007014bf5c8> (a sun.nio.ch.Util$2)
	- locked <0x00000007014bf5d8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007014bf580> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:601)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

"qtp1125981799-49-selector-ServerConnectorManager@372318b7/0" prio=10 tid=0x00007f0b48657000 nid=0x4527 runnable [0x00007f0b337f6000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x00000007014bfb18> (a sun.nio.ch.Util$2)
	- locked <0x00000007014bfb28> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007014bfad0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:601)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

"qtp1125981799-48-selector-ServerConnectorManager@63577d06/1" prio=10 tid=0x00007f0b48654800 nid=0x4526 runnable [0x00007f0b338f7000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x000000070103a350> (a sun.nio.ch.Util$2)
	- locked <0x000000070103a340> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000070103a1e8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:601)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

"qtp1125981799-47-selector-ServerConnectorManager@63577d06/0" prio=10 tid=0x00007f0b48652800 nid=0x4525 runnable [0x00007f0b339f8000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x000000070104f470> (a sun.nio.ch.Util$2)
	- locked <0x000000070104f460> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000070103a6f0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:601)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
	at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

"qtp1125981799-46-acceptor-0@fcf0de2-ServerConnector@2a859b96{HTTP/1.1}{0.0.0.0:8082}" prio=10 tid=0x00007f0b48650800 nid=0x4524 runnable [0x00007f0b33af9000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:241)
	- locked <0x000000070104f8a8> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

 Could anyone provide some insight on why the cpu usage is so high?

**Comment by janbartel** [comment]
@prashanth007  Just one stack trace isn't going to tell us a great deal. You'd need to do several stack trace dumps during the period of 100% cpu in order to see the change in which threads are busy.  In the one dump that you posted I see some threads in accept and some in select - which is normal.

**Comment by prashanth007** [comment]
@janbartel I just have the stack trace dumps taken during the high cpu usage attaching it here now.
[jstackdumps.zip](https://github.com/eclipse/jetty.project/files/555296/jstackdumps.zip)

Hope this could shed some light.

**Comment by sbordet** [comment]
Stack traces are helpful, but not enough.

That the CPU usage reaches 100% is not, per se, a problem if your server is actually doing things.

If the server is idle, and you still have 100% CPU, then that is a problem.

You can try to connect to your server via JMC (Java Mission Control). With JMC you can enable CPU profiling that will tell you exactly what thread is consuming CPU (in the "Threads" tab, there is a checkbox "CPU Profiling").
You can see what threads take most CPU, and what is their stack trace.

A screenshot of JMC would be great.

Have you tried upgrading Jetty to 9.3.x ?

**Comment by prashanth007** [comment]
@sbordet Awesome tip regarding the JMC. Just enabled it and connected to my server. Will keep an eye on it. Again thank you so much since i was clueless regarding what was consuming the cpu. The issue got fixed post a jetty restart yesterday. Will get the JMC results when it occurs again.
