### ISSUE TITLE
Unsuppressed exceptions from HttpClientContinueTest

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#10386]
**Jetty version(s)**
12

**Jetty Environment**
ee9

**Description**

[INFO] Running org.eclipse.jetty.ee9.test.client.transport.HttpClientContinueTest
in https://jenkins.webtide.net/blue/rest/organizations/jenkins/pipelines/jetty.project/branches/jetty-12.0.x/runs/1451

```java
2023-08-22 21:59:28.456:WARN :oejusS.config:ForkJoinPool-1-worker-2: No Client EndPointIdentificationAlgorithm configured for Client@62efee91[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
2023-08-22 21:59:28.460:INFO :oejs.Server:ForkJoinPool-1-worker-2: Stopped oejs.Server@5fc393ed{STOPPING}[12.0.1-SNAPSHOT,sto=0]
2023-08-22 21:59:28.460:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-2: Stopped ServerConnector@24c13f7f{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
2023-08-22 21:59:28.460:WARN :oejut.SerializedInvoker:server-1975: Serialized invocation error
java.lang.NullPointerException: Cannot read field "_stream" because "httpChannelState" is null
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.failed(HttpChannelState.java:1542)
	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$2(HttpChannelState.java:484)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2023-08-22 21:59:28.462:INFO :oejs.Server:ForkJoinPool-1-worker-2: jetty-12.0.1-SNAPSHOT; built: 2023-08-22T21:15:43.448Z; git: a51c67dbb4d6f78dc8dc7cbca6997b19308dec65; jvm 21-ea+32-2482
2023-08-22 21:59:28.463:INFO :oejsh.ContextHandler:ForkJoinPool-1-worker-2: Started oeje9n.ContextHandler$CoreContextHandler@24714cda{ROOT,/,b=null,a=AVAILABLE,h=oeje9n.ContextHandler$CoreContextHandler$CoreToNestedHandler@3340b9b9{STARTED}}
2023-08-22 21:59:28.493:INFO :oejus.SslContextFactory:ForkJoinPool-1-worker-2: x509=X509@5a886fc6(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Server@74b1ffd1[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
2023-08-22 21:59:28.506:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-2: Started ServerConnector@428a1d8f{SSL, (ssl, http/1.1)}{0.0.0.0:43559}
2023-08-22 21:59:28.506:INFO :oejs.Server:ForkJoinPool-1-worker-2: Started oejs.Server@654b7963{STARTING}[12.0.1-SNAPSHOT,sto=0] @10129ms
2023-08-22 21:59:28.536:INFO :oejus.SslContextFactory:ForkJoinPool-1-worker-2: x509=X509@4cc2558f(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Client@1e001b71[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
2023-08-22 21:59:28.548:WARN :oejusS.config:ForkJoinPool-1-worker-2: No Client EndPointIdentificationAlgorithm configured for Client@1e001b71[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
2023-08-22 21:59:28.559:INFO :oejs.Server:ForkJoinPool-1-worker-2: Stopped oejs.Server@654b7963{STOPPING}[12.0.1-SNAPSHOT,sto=0]
2023-08-22 21:59:28.559:WARN :oejut.SerializedInvoker:server-1995: Serialized invocation error
java.lang.NullPointerException: Cannot read field "_stream" because "httpChannelState" is null
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.failed(HttpChannelState.java:1542)
	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$2(HttpChannelState.java:484)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2023-08-22 21:59:28.560:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-2: Stopped ServerConnector@428a1d8f{SSL, (ssl, http/1.1)}{0.0.0.0:0}
2023-08-22 21:59:28.562:INFO :oejs.Server:ForkJoinPool-1-worker-2: jetty-12.0.1-SNAPSHOT; built: 2023-08-22T21:15:43.448Z; git: a51c67dbb4d6f78dc8dc7cbca6997b19308dec65; jvm 21-ea+32-2482
2023-08-22 21:59:28.563:INFO :oejsh.ContextHandler:ForkJoinPool-1-worker-2: Started oeje9n.ContextHandler$CoreContextHandler@111d9593{ROOT,/,b=null,a=AVAILABLE,h=oeje9n.ContextHandler$CoreContextHandler$CoreToNestedHandler@5ed7dac1{STARTED}}
```

There is also a lot of verbose output like:
```
2023-08-22 21:59:22.527:WARN :oejusS.config:ForkJoinPool-1-worker-1: No Client EndPointIdentificationAlgorithm configured for Client@4b014d71[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
Expected error empty push builder
Expected error no path reset
Expected error null method
Pass 
Pass POST
Pass PUT
Pass DELETE
Pass CONNECT
Pass OPTIONS
Pass TRACE
2023-08-22 21:59:22.547:INFO :oejs.Server:ForkJoinPool-1-worker-1: Stopped oejs.Server@6a0e2c09{STOPPING}[12.0.1-SNAPSHOT,sto=0]
2023-08-22 21:59:22.547:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-1: Stopped ServerConnector@68171179{SSL, (ssl, alpn, h2)}{0.0.0.0:0}
2023-08-22 21:59:22.550:INFO :oejs.Server:ForkJoinPool-1-worker-1: jetty-12.0.1-SNAPSHOT; built: 2023-08-22T21:15:43.448Z; git: a51c67dbb4d6f78dc8dc7cbca6997b19308dec65; jvm 21-ea+32-2482
2023-08-22 21:59:22.551:INFO :oejsh.ContextHandler:ForkJoinPool-1-worker-1: Started oeje9n.ContextHandler$CoreContextHandler@47e65fb3{ROOT,/,b=null,a=AVAILABLE,h=oeje9n.ContextHandler$CoreContextHandler$CoreToNestedHandler@2eb818f7{STARTED}}
2023-08-22 21:59:22.551:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-1: Started ServerConnector@19f070b6{h2c, (h2c)}{0.0.0.0:36735}
2023-08-22 21:59:22.552:INFO :oejs.Server:ForkJoinPool-1-worker-1: Started oejs.Server@3ed3db83{STARTING}[12.0.1-SNAPSHOT,sto=0] @4175ms
2023-08-22 21:59:22.582:INFO :oejus.SslContextFactory:ForkJoinPool-1-worker-1: x509=X509@6f615d7f(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Client@ea8237e[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
2023-08-22 21:59:22.594:WARN :oejusS.config:ForkJoinPool-1-worker-1: No Client EndPointIdentificationAlgorithm configured for Client@ea8237e[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
SIMON: target = /
SIMON: target = /old
SIMON: target = /new
```

**Comment by lorban** [comment]
The `java.lang.NullPointerException: Cannot read field "_stream" because "httpChannelState" is null` warning got fixed as part of #10844; while the other verbose output was cleaned earlier.

I've nevertheless created an enhancement PR to fix some EE9 H3 tests and cleanup `AbstractTest`.
