### ISSUE TITLE
How to add JettyJasperInitializer to WebAppContext programmatically in Jetty 12

### ISSUE THREAD

**Issue by wodeidaiga** [eclipse/jetty.project#10405]
**Jetty Version**
Jetty 12

**Jetty Environment**

ee8
**Java Version**
JDK17
**Question**
During migrating to Jetty12 from jetty9.4, I have an issue adding JettyJasperInitializer to WebAppContext programmatically. 
I was able to add it in 9.4 in the following way:
deploymentManager.setContextAttribute("org.eclipse.jetty.containerInitializers" , Arrays.asList (
                new ContainerInitializer(new JettyJasperInitializer(), null)));

Now the behavior of DeploymentManager has changed ,  so I can't add it in here anymore.

I tried to configure it in the jetty-web.xml like this:

```
<Configure class="org.eclipse.jetty.ee8.webapp.WebAppContext">
  <Call name="addServletContainerInitializer">
    <Arg>
      <New class="org.eclipse.jetty.ee8.apache.jsp.JettyJasperInitializer"></New>
    </Arg>
  </Call>
</Configure>
```

But there is an exception saying :
[main] WARN org.eclipse.jetty.ee8.webapp.WebAppContext - Failed startup of context oeje8w.WebAppContext@4a883b15{jspapp,/jspapp,file:///home/cpe-juice/work/jetty-demo/target/classes/webapps/jspapp/,false}{/home/cpe-juice/work/jetty-demo/target/classes/webapps/jspapp}
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:795)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:1003)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:968)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:526)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:442)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:365)
	at org.eclipse.jetty.ee8.webapp.JettyWebXmlConfiguration.lambda$configure$0(JettyWebXmlConfiguration.java:72)
	at org.eclipse.jetty.ee8.webapp.WebAppClassLoader.runWithServerClassAccess(WebAppClassLoader.java:140)
	at org.eclipse.jetty.ee8.webapp.JettyWebXmlConfiguration.configure(JettyWebXmlConfiguration.java:71)
	at org.eclipse.jetty.ee8.webapp.Configurations.configure(Configurations.java:422)
	at org.eclipse.jetty.ee8.webapp.WebAppContext.configure(WebAppContext.java:473)
	at org.eclipse.jetty.ee8.webapp.WebAppContext.startContext(WebAppContext.java:1133)
	at org.eclipse.jetty.ee8.nested.ContextHandler.doStartInContext(ContextHandler.java:593)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1197)
	at org.eclipse.jetty.ee8.nested.ContextHandler.doStart(ContextHandler.java:582)
	at org.eclipse.jetty.ee8.servlet.ServletContextHandler.doStart(ServletContextHandler.java:258)
	at org.eclipse.jetty.ee8.webapp.WebAppContext.doStart(WebAppContext.java:490)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:395)
	at org.eclipse.jetty.server.handler.ContextHandler.lambda$doStart$0(ContextHandler.java:657)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1203)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:657)
	at org.eclipse.jetty.ee8.nested.ContextHandler$CoreContextHandler.doStart(ContextHandler.java:2133)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:395)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:601)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:395)
	at org.eclipse.jetty.server.Server.doStart(Server.java:542)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.example.Main.main(Main.java:81)
Caused by: java.lang.IllegalStateException: ServletContainerInitializers should be added before starting
	at org.eclipse.jetty.ee8.servlet.ServletContextHandler.addServletContainerInitializer(ServletContextHandler.java:439)
	... 41 more
I find a way to add it eventually:

        DeploymentManager deploymentManager = server.getBean(DeploymentManager.class);
        deploymentManager.start();
        Collection<App> apps = deploymentManager.getApps();
        ContextHandler contextHandler = apps.stream().collect(Collectors.toList()).get(0).getContextHandler();
        Field field = org.eclipse.jetty.ee8.nested.ContextHandler.CoreContextHandler.class.getDeclaredField("this$0");
        field.setAccessible(true);
        WebAppContext outer = (WebAppContext) field.get(contextHandler);
        outer.addServletContainerInitializer(new JettyJasperInitializer());
        server.start();

But I think I probably should not add it like this. Is there any other way I can add it programmatically using java or xml configuration?
My requirement is that I have to generate the WebAppContext from web.xml so I can't create ServletContextHandler directly in java code.

Thanks!

**Comment by janbartel** [comment]
As a starting point, you can take a look at an ee9 example here: https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/OneWebAppWithJsp.java

If that's not what you're after, can you explain more about your use-case and we'll see if we can  give you more specific advice.

**Comment by wodeidaiga** [comment]
> As a starting point, you can take a look at an ee9 example here: https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/OneWebAppWithJsp.java
> 
> If that's not what you're after, can you explain more about your use-case and we'll see if we can give you more specific advice.

Thank you for your reply. I follow the example you give and I can start jetty with jsp . My question is do I still need a deployment manager if I want the directory to be automaticaly scanned?

**Comment by janbartel** [comment]
@chiqiu you need the `DeploymentManager` if you want Jetty to find, configure and deploy your webapp for you. Otherwise you have to create, configure and add it to your handler hierarchy programmatically.

**Comment by wodeidaiga** [comment]
@janbartel Thanks!
