### ISSUE TITLE
ThreadPoolBudget violation if threads required equals maxThreads

### ISSUE THREAD

**Issue by dhorn712** [eclipse/jetty.project#10404]
Hello Jetty Team.

I assume Jetty (from v9.4 up to v12.0) has a flaw in asserting the `ThreadPoolBudget`, introduced with commit [7d98cbb](https://github.com/eclipse/jetty.project/commit/7d98cbb8703d23a30ce830f24f8cfd0fce9fc08a) for issue [#1851](https://github.com/eclipse/jetty.project/issues/1851). It does not allow the `required` threads to be `maxThreads`.

I suppose that in 

```java
int required = getLeasedThreads();
int left = maxThreads - required;
if (left <= 0)
{
    printInfoOnLeases();
    throw new IllegalStateException(String.format("Insufficient configured threads: required=%d < max=%d for %s", required, maxThreads, pool));
}
```

the [restriction](https://github.com/eclipse/jetty.project/blame/52d94174e2c7a6e794c6377dcf9cd3ed0b9e1806/jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadPoolBudget.java#L146) should not be `left <= 0` but `left < 0`.

I suggest to change the code to

```java
int required = getLeasedThreads();
if (required > maxThreads)
{
    printInfoOnLeases();
    throw new IllegalStateException(String.format("Insufficient configured threads: required=%d <= max=%d for %s", required, maxThreads, pool));
}
```

**Comment by dhorn712** [comment]
We use the Camel v3.19 component Jetty Websocket. It auto configures Jetty's `maxThreads = 1 + Runtime.getRuntime().availableProcessors() * 2` with "1 + selectors + acceptors" in mind. 

On a system with just one CPU that results in `maxThreads = 3`. At startup exactly three threads are required. Although that meets the budget the startup fails:

```
13:06:11.339 [main] INFO  o.e.j.util.thread.ThreadPoolBudget - ReservedThreadExecutor@26f0ab88{reserved=0/1,pending=0} requires 1 threads from QueuedThreadPool[CamelJettyWebSocketServer]@28df2da8{STARTED,1<=1<=3,i=1,r=-1,q=0}[ReservedThreadExecutor@26f0ab88{reserved=0/1,pending=0}]
13:06:11.339 [main] INFO  o.e.j.util.thread.ThreadPoolBudget - ServerConnector@7b5e1b16{HTTP/1.1, (http/1.1)}{0.0.0.0:9292} requires 1 threads from QueuedThreadPool[CamelJettyWebSocketServer]@28df2da8{STARTED,1<=1<=3,i=1,r=-1,q=0}[ReservedThreadExecutor@26f0ab88{reserved=0/1,pending=0}]
13:06:11.339 [main] INFO  o.e.j.util.thread.ThreadPoolBudget - SelectorManager@ServerConnector@7b5e1b16{HTTP/1.1, (http/1.1)}{0.0.0.0:9292} requires 1 threads from QueuedThreadPool[CamelJettyWebSocketServer]@28df2da8{STARTED,1<=1<=3,i=1,r=-1,q=0}[ReservedThreadExecutor@26f0ab88{reserved=0/1,pending=0}]
13:06:11.342 [main] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED SelectorManager@ServerConnector@7b5e1b16{HTTP/1.1, (http/1.1)}{0.0.0.0:9292}: java.lang.IllegalStateException: Insufficient configured threads: required=3 < max=3 for QueuedThreadPool[CamelJettyWebSocketServer]@28df2da8{STARTED,1<=1<=3,i=1,r=-1,q=0}[ReservedThreadExecutor@26f0ab88{reserved=0/1,pending=0}]
java.lang.IllegalStateException: Insufficient configured threads: required=3 < max=3 for QueuedThreadPool[CamelJettyWebSocketServer]@28df2da8{STARTED,1<=1<=3,i=1,r=-1,q=0}[ReservedThreadExecutor@26f0ab88{reserved=0/1,pending=0}]
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.check(ThreadPoolBudget.java:165)
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseTo(ThreadPoolBudget.java:141)
	at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseFrom(ThreadPoolBudget.java:191)
	at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:255)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:323)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.apache.camel.component.websocket.WebsocketComponent.connect(WebsocketComponent.java:205)
	at org.apache.camel.component.websocket.WebsocketEndpoint.connect(WebsocketEndpoint.java:118)
	at org.apache.camel.component.websocket.WebsocketConsumer.doStart(WebsocketConsumer.java:38)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3733)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRouteConsumers(InternalRouteStartupManager.java:401)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartRouteConsumers(InternalRouteStartupManager.java:319)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:213)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:147)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3418)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:3086)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:3041)
	at org.apache.camel.spring.boot.SpringBootCamelContext.doStart(SpringBootCamelContext.java:43)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2690)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:119)
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at some.App.main(App.java:22)
```

**Comment by dhorn712** [comment]
For Spring Boot as a workaround `maxThreads` can be manually configured in the `application.yaml`as follows:

```yaml
camel:
  component:
    websocket:
      max-threads: 200 # any value greater than threads required
```

**Comment by sbordet** [comment]
@dhorn712 the assert is correct.

If you have 3 threads in the thread pool, and they are all leased to Jetty components, there will be no threads available to process requests.

Camel's default is too conservative, IMHO, because it will not allow for much concurrency in case of blocking I/O.
Assuming 1 acceptor and 1 selector, and 8 cores, Camel's defaults at 17, leaving 15 threads for request processing.
This means that if 15 requests block on I/O (very common when interacting with databases), then there are no threads to process other requests.
You would have a system that is completely idle, waiting on I/O and unable to process more requests.

Basing the number of pooled threads on the number of cores is only valid for systems that are 100% non-blocking, which are quite rare (for example, none of the REST libraries based on JAX-RS, nor anything based on JDBC).

For the other cases, one needs to analyze the traffic the system must withstand, the possible bottlenecks of the system, the calls that block on I/O, etc. and come up with a number, typically with trial/error.

It is typically best to start with the defaults, and monitor the system from there.

Note also that overprovisioning Jetty is not a problem: if threads are not needed, Jetty won't create them.
Even in case of load spikes, the excess threads could be quickly evicted (read the documentation here: https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-arch-threads-thread-pool.

**Comment by dhorn712** [comment]
Thank you for your quick response.
