### ISSUE TITLE
Question: how do I configure Jetty to exit with an error code when a webapp context fails to initialise?

### ISSUE THREAD

**Issue by danwashusen** [eclipse/jetty.project#10505]
**Jetty version(s)**
jetty-10.0.16; built: 2023-08-25T19:11:25.422Z; git: a2735a9ae9d1afc124974253f1e223e5678be1f4; jvm 11.0.20.1+9-LTS

**Jetty Environment**

**Java version/vendor** `(use: java -version)`
Corretto 11.0.20.1+9-LTS
**OS type/version**
Ubuntu 20.04

**Description**

For quiet a while now our webapp context deployment file has included the `throwUnavailableOnStartupException` flag with the intention of having Jetty exit with an error code if the (only) app fails to initialise. We used this state to start a deployment rollback process...

However we've just noticed (after upgrading to 10.x quiet a while ago) that this is no longer the case. Despite the fatal deployment error in the webapp context the Java process remains running and reports healthy...

**How to reproduce?**
Add an XML file to a webapp that has an initialisation issue:

```xml
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="resourceBase">/path/to/webapp</Set>
  <Set name="throwUnavailableOnStartupException">true</Set>
</Configure>
```

Observe the Jetty logs:
```
2023-09-13T03:01:44.743000+00:00 i-08a098adce6edddfe Starting Jetty: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2023-09-13T03:01:44.743000+00:00 i-08a098adce6edddfe /usr/local/jetty/bin/jetty.sh: line 504: disown: 4409: no such job
2023-09-13T03:01:49.123000+00:00 i-08a098adce6edddfe ok Wed Sep 13 03:01:44 UTC 2023
2023-09-13T03:01:58.274000+00:00 i-08a098adce6edddfe 2023-09-13 03:01:57.720:INFO :oejs.Server:main: jetty-10.0.16; built: 2023-08-25T19:11:25.422Z; git: a2735a9ae9d1afc124974253f1e223e5678be1f4; jvm 11.0.20.1+9-LTS
2023-09-13T03:02:03.122000+00:00 i-08a098adce6edddfe 2023-09-13 03:01:58.086:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/]
2023-09-13T03:02:15.122000+00:00 i-08a098adce6edddfe 2023-09-13 03:02:10.630:INFO :oejshC.userapp_xml:main: 3 Spring WebApplicationInitializers detected on classpath
2023-09-13T03:03:29.762000+00:00 i-08a098adce6edddfe 2023-09-13 03:03:29.520:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@33f349ae{userapp.xml,/,file:///usr/local/our/app/path/,UNAVAILABLE}
2023-09-13T03:03:29.762000+00:00 i-08a098adce6edddfe org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Failed to obtain a connection
	at ...our app stack
	at org.eclipse.jetty.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:148)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:1658)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:901)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:516)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:186)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:462)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:58)
	at org.eclipse.jetty.util.Scanner$DiscreteListener.pathAdded(Scanner.java:282)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:836)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:802)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:709)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:597)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:158)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:246)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:470)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:415)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1919)
```

```
$ ps -ef | grep jetty
jetty       5617       1  0 06:11 ?        00:00:00 xargs /usr/bin/java
jetty       5619    5617 92 06:11 ?        00:01:58 /usr/bin/java -Djava.io.tmpdir=/tmp -Djetty.home=/usr/local/jetty -Djetty.base=/var/lib/jetty ...
```

**Comment by danwashusen** [comment]
Here's the cleaned up log output for our exact scenario:

```
2023-09-13T03:01:44.743000+00:00 i-08a098adce6edddfe Starting Jetty: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2023-09-13T03:01:44.743000+00:00 i-08a098adce6edddfe /usr/local/jetty/bin/jetty.sh: line 504: disown: 4409: no such job
2023-09-13T03:01:49.123000+00:00 i-08a098adce6edddfe ok Wed Sep 13 03:01:44 UTC 2023
2023-09-13T03:01:58.274000+00:00 i-08a098adce6edddfe 2023-09-13 03:01:57.720:INFO :oejs.Server:main: jetty-10.0.16; built: 2023-08-25T19:11:25.422Z; git: a2735a9ae9d1afc124974253f1e223e5678be1f4; jvm 11.0.20.1+9-LTS
2023-09-13T03:02:03.122000+00:00 i-08a098adce6edddfe 2023-09-13 03:01:58.086:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/]
2023-09-13T03:02:15.122000+00:00 i-08a098adce6edddfe 2023-09-13 03:02:10.630:INFO :oejshC.userapp_xml:main: 3 Spring WebApplicationInitializers detected on classpath
2023-09-13T03:03:29.762000+00:00 i-08a098adce6edddfe 2023-09-13 03:03:29.520:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@33f349ae{userapp.xml,/,file:///usr/local/our/app/path/,UNAVAILABLE}
2023-09-13T03:03:29.762000+00:00 i-08a098adce6edddfe org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Failed to obtain a connection
	at ...our app stack
	at org.eclipse.jetty.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:148)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:1658)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:901)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:516)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:186)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:462)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:58)
	at org.eclipse.jetty.util.Scanner$DiscreteListener.pathAdded(Scanner.java:282)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:836)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:802)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:709)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:597)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:158)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:246)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:470)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:415)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1919)
``` 

The line about `disown` also seems to be new...

**Comment by danwashusen** [comment]
When I change the `throwUnavailableOnStartupException` flag to false I see very similar output, but different ordering...

```
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1919)
2023-09-13 04:40:50.997:INFO :oejus.SslContextFactory:main: x509=X509@471cf780(jetty,h=[xyz.com],a=[],w=[]) for Server@74929c6e[provider=null,keyStore=file:///var/lib/jetty/etc/keystore,trustStore=null]
2023-09-13 04:40:51.016:INFO :oejs.AbstractConnector:main: Started ServerConnector@8c527b8{[proxy], ([proxy], http/1.1)}{0.0.0.0:8080}
2023-09-13 04:40:51.018:INFO :oejs.AbstractConnector:main: Started ServerConnector@7610aa61{SSL, (ssl, http/1.1)}{0.0.0.0:8443}
2023-09-13 04:40:51.021:INFO :oejs.Server:main: Started Server@754de353{STARTING}[10.0.16,sto=5000] @100848ms
```

**Comment by joakime** [comment]
> 2023-09-13T03:01:44.743000+00:00 i-08a098adce6edddfe /usr/local/jetty/bin/jetty.sh: line 504: disown: 4409: no such job

This disown issue is being handled by PR #10473

**Comment by danwashusen** [comment]
> > 2023-09-13T03:01:44.743000+00:00 i-08a098adce6edddfe /usr/local/jetty/bin/jetty.sh: line 504: disown: 4409: no such job
> 
> This disown issue is being handled by PR #10473

I've confirmed that the `jetty.sh` from PR #10473 no longer logs the disown message, although no change to the jetty startup behaviour... :/

**Comment by danwashusen** [comment]
We've managed to work-around this bug/feature using the ExecStartPost systemd setting and a bodgy shell script:

```
ExecStartPost=/usr/local/jetty/bin/monitor-jetty-deployment.sh 'WebAppContext.*,AVAILABLE' 90
```

```sh
#!/bin/bash

# Jetty offers an excellent 'feature' that leaves the server running despite a failed deployment.
# This script monitors the jetty.log file for a successful deployment, and if it doesn't find one
# within the specified timeout duration, it stops Jetty and fails the deployment.
# To use script add the following to you systemd service file:
# ExecStartPost=/usr/local/jetty/bin/monitor-jetty-deployment.sh 'WebAppContext.*,AVAILABLE' 90

# Initialize default success pattern
DEFAULT_SUCCESS_PATTERN="WebAppContext.*,AVAILABLE"

# Initialize default timeout duration in seconds
DEFAULT_TIMEOUT_DURATION=180

# Get SUCCESS_PATTERN and TIMEOUT_DURATION from arguments, or use defaults
SUCCESS_PATTERN=${1:-$DEFAULT_SUCCESS_PATTERN}
TIMEOUT_DURATION=${2:-$DEFAULT_TIMEOUT_DURATION}

# Log initial message to syslog
JETTY_LOG=${JETTY_LOG:-/var/log/jetty.log}
logger -t "JettyMonitor" "Monitoring $JETTY_LOG for pattern '$SUCCESS_PATTERN' with a timeout of $TIMEOUT_DURATION seconds."

# Monitor jetty.log for the specified timeout duration
timeout $TIMEOUT_DURATION tail -f $JETTY_LOG -n 1000 | grep --line-buffered -m 1 "$SUCCESS_PATTERN"
GREP_EXIT_CODE=$?

# Define exit codes
SUCCESS_EXIT_CODE=0
FAILURE_EXIT_CODE=1

# Check grep's exit code
if [ $GREP_EXIT_CODE -eq 0 ]; then
  # Log a success message to syslog
  logger -t "JettyMonitor" "Jetty has successfully deployed apps."
  exit $SUCCESS_EXIT_CODE
else
  # Log a failure message to syslog
  logger -t "JettyMonitor" "Jetty failed to deploy apps, stopping and failing..."
  
  # Stop Jetty
  /usr/local/jetty/bin/jetty.sh stop
  exit $FAILURE_EXIT_CODE
fi
```

With this in place systemd will wait for the `monitor-jetty-deployment.sh` script to cleanly exit before reporting success...

**Comment by janbartel** [comment]
Just commenting to confirm for other readers of  this issue that when run from the _command line_, with a webapp with `setThrowUnavailableOnStartupException(true)` the server fails to start and jetty stops as expected.

@joakime is there some further fix needed in the `jetty.sh` script given the last comment from @danwashusen?

**Comment by danwashusen** [comment]
Thanks for testing @janbartel.

We are starting Jetty via systemd with a config file that looks very similar to the one provided in the distribution. We are observing systemd report that Jetty has successfully started within about 10 seconds, *way way* before our app has finished initialisation (about 60 seconds).

Eventually Jetty logs that our app failed to deploy, but the Java process remains:
```
Starting Jetty: ok Fri Sep 15 01:17:55 UTC 2023
2023-09-15 01:18:08.373:INFO :oejs.Server:main: jetty-10.0.16; built: 2023-08-25T19:11:25.422Z; git: a2735a9ae9d1afc124974253f1e223e5678be1f4; jvm 11.0.20.1+9-LTS
2023-09-15 01:18:08.704:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/]
2023-09-15 01:18:21.179:INFO :oejshC.userapp_xml:main: 3 Spring WebApplicationInitializers detected on classpath
2023-09-15 01:19:40.130:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@48b2dbc4{userapp.xml,/,file:///usr/local/digitalpigeon/userapp/,UNAVAILABLE}
```

Another interesting/weird log message appears in syslog:
```
Sep 15 02:02:54 ip-10-1-2-95 systemd[1]: Starting Jetty Web Application Server...
Sep 15 02:02:55 ip-10-1-2-95 systemd[1]: jetty.service: Can't open PID file /run/jetty/jetty.pid (yet?) after start: Operation not permitted
Sep 15 02:03:04 ip-10-1-2-95 systemd[1]: jetty.service: Supervising process 6508 which is not our child. We'll most likely not notice when it exits.
Sep 15 02:03:04 ip-10-1-2-95 systemd[1]: Started Jetty Web Application Server.
```

The PID mentioned above is the java process:
```sh
# ps -ef | grep java
jetty       6506       1  0 02:02 ?        00:00:00 xargs /usr/bin/java
jetty       6508    6506 98 02:02 ?        00:02:06 /usr/bin/java -Djava.io.tmpdir=/tmp -Djetty.home=/usr/local/jetty -Djetty.base=/var/lib/jetty ...
```

The `/run/jetty/jetty.pid` file does exist and contains the correct PID:
```sh
# cat /run/jetty/jetty.pid
6508
```

We init the Jetty base dir fresh each time:
```sh
java -jar {{ jetty.home }}/start.jar --create-startd
            --add-module="server,http,ssl,https,proxy-protocol,websocket,http-forwarded,jsp,jstl,ext,resources,webapp,deploy"
```

Additionally, if I assign the `jetty` system user a shell and exec `/usr/local/jetty/bin/jetty.sh start` I observe that the script doesn't exit and the java process remains running until I hit ctrl+c, at which point the script exits but the java process remains running.

**Comment by joakime** [comment]
I've renamed issue #10473

* #10473

This issue is related to the core bug in #10473 that is present in `jetty.sh` starting in Jetty 10.0.16 (if you test 10.0.15, this configuration will work)

**Comment by joakime** [comment]
The latest changes in `jetty.sh` on PR #10501 should behave correctly now.

To test this yourself ...

Take the existing jetty-home-10.0.16 archive, unpack it, and replace the unpacked `bin/jetty.sh` with the version from PR #10501

Link: https://github.com/eclipse/jetty.project/blob/fix/10.0.x/alt-jettysh-pgrep/jetty-home/src/main/resources/bin/jetty.sh

**Comment by janbartel** [comment]
@danwashusen going back to basics here .... I've used your sample context xml file from your original post and tried to start jetty _via the command line_ with just the following modules enabled: `server,ext,resources,http,deploy,webapp`. When I do that, jetty does _not_ fail the startup due to the non-existant `/path/to/webapp`. However, if I change your file to call `setWar()` instead of `setResourceBase()` like so:

``` xml
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="war">/path/to/webapp</Set>
  <Set name="throwUnavailableOnStartupException">true</Set>
</Configure>
```

then jetty _does_ throw the exception on startup and fail the start. I haven't involved `jetty.sh` with this as I just want to make sure we're looking at the right problem and not assuming it is something in `jetty.sh`.

Can you go back and try setting `war` instead of `resourceBase` with your original jetty version and your `jetty.sh` and check if that is working for you?

**Comment by danwashusen** [comment]
Thanks for the followup @janbartel. I believe the issue I was facing was related to the issues mentioned in https://github.com/eclipse/jetty.project/issues/10473.
