### ISSUE TITLE
NPE in HTTP2 StreamResetTest.testClientResetConsumesQueuedData

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#10539]
**Jetty version(s)**
12

**Jetty Environment**
all

**Java version/vendor** `(use: java -version)`

**OS type/version**

**Description*

Whilst building a javadoc only change: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-10527/5/pipeline/

```
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 15.19 s -- in org.eclipse.jetty.http2.tests.MaxConcurrentStreamsTest
2023-09-17 19:40:53.633:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@5a705a25{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:40:53.633:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@4173b1bb{h2c, (h2c)}{0.0.0.0:0}
2023-09-17 19:40:53.636:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:40:53.638:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@1fbf0f15{h2, (h2)}{0.0.0.0:38411}
2023-09-17 19:40:53.638:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@6d7bd9fc{STARTING}[12.0.2-SNAPSHOT,sto=0] @86209ms
2023-09-17 19:40:54.646:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@6d7bd9fc{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:40:54.646:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@1fbf0f15{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:40:54.650:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:40:54.653:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@480bfcd6{h2, (h2)}{0.0.0.0:42721}
2023-09-17 19:40:54.653:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@5e2969e3{STARTING}[12.0.2-SNAPSHOT,sto=0] @87224ms
2023-09-17 19:40:57.160:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@5e2969e3{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:40:57.160:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@480bfcd6{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:40:57.163:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:40:57.164:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@72bf65a8{h2, (h2)}{0.0.0.0:35889}
2023-09-17 19:40:57.164:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@182b5240{STARTING}[12.0.2-SNAPSHOT,sto=0] @89735ms
2023-09-17 19:40:59.171:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@182b5240{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:40:59.171:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@72bf65a8{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:40:59.175:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:40:59.177:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@178e10f5{h2, (h2)}{0.0.0.0:45199}
2023-09-17 19:40:59.177:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@24c55980{STARTING}[12.0.2-SNAPSHOT,sto=0] @91748ms
2023-09-17 19:41:01.184:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@24c55980{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:41:01.185:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@178e10f5{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:41:01.189:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:41:01.190:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@28ab56e5{h2, (h2)}{0.0.0.0:43899}
2023-09-17 19:41:01.190:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@3d92874{STARTING}[12.0.2-SNAPSHOT,sto=0] @93761ms
2023-09-17 19:41:02.198:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@3d92874{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:41:02.199:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@28ab56e5{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:41:02.203:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:41:02.205:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@383f097b{h2, (h2)}{0.0.0.0:42439}
2023-09-17 19:41:02.205:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@2e512670{STARTING}[12.0.2-SNAPSHOT,sto=0] @94776ms
processing request /1
processing request /2
2023-09-17 19:41:03.713:WARN :oejuts.AdaptiveExecutionStrategy:server-4008: Task run failed
java.lang.NullPointerException: Cannot read field "_callback" because "this._request" is null
	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onIdleTimeout$1(HttpChannelState.java:402)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-09-17 19:41:03.713:WARN :oejuts.AdaptiveExecutionStrategy:server-4005: Task run failed
java.lang.NullPointerException: Cannot read field "_callback" because "this._request" is null
	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onIdleTimeout$1(HttpChannelState.java:402)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-09-17 19:41:03.947:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@2e512670{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:41:03.947:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@383f097b{h2, (h2)}{0.0.0.0:0}
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 27.93 s -- in org.eclipse.jetty.http2.tests.IdleTimeoutTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StreamResetTest.testClientResetConsumesQueuedData:443 expected: <0> but was: <32768>
```

**Comment by lorban** [comment]
Probably related to #10382

**Comment by GaryWKeim** [comment]
We (Terracotta) are seeing this in 12.0.16:

```
2025-01-29 21:15:55,115 [jetty-immediate-executor] ERROR com.tc.server.TCServerMain - Thread:Thread[jetty-immediate-executor,5,TC Thread Group] got an uncaught exception. calling CallbackOnExitDefaultHandlers.
     java.lang.NullPointerException: Cannot read field "_callback" because "this._request" is null
     	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$1(HttpChannelState.java:444)
     	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by lorban** [comment]
@GaryWKeim (_long time no see!_) I assume you're using HTTP 1 only, and this NPE happens on the `jetty-immediate-executor` thread, which tend to indicate that you're hitting a different problem with a similar symptom.

So could you please open a new issue for this problem?

Thanks!

**Comment by GaryWKeim** [comment]
Hey Lodovic! Hope things are going well.
 
That is correct, 1.1.
 
```
INFO :oejs.AbstractConnector:main: Started [ServerConnector@28cb86b2{HTTP/1.1](mailto:ServerConnector@28cb86b2%7bHTTP/1.1), (http/1.1)}{0.0.0.0:9889}
INFO :oejs.AbstractConnector:main: Started ServerConnector@3b3056a6{SSL, (ssl, http/1.1)}{0.0.0.0:9443}
```

I did already create another issue but have little information to offer other than that the server barfed on this.
