### ISSUE TITLE
build jetty 9.3.14 and 9.4.0 get error at test step "Test set: org.eclipse.jetty.http.client.ServerTimeoutsTest"

### ISSUE THREAD

**Issue by hieplq** [eclipse/jetty.project#1055]
I build jetty from source for 9.3.14 and 9.4.0
but it stop with bellow error 

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project test-http-client-transport: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/hieplq/Downloads/jetty.project-jetty-9.3.14.v20161028/tests/test-http-client-transport/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :test-http-client-transport

i did get any solution from [maven](http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException)

my environment is:
mint 18-64x
maven 3.3.9
openjdk 1.8.0_91
ant 1.9.6
[org.eclipse.jetty.http.client.ServerTimeoutsTest.txt]attack is error log for test case error (https://github.com/eclipse/jetty.project/files/566613/org.eclipse.jetty.http.client.ServerTimeoutsTest.txt)

**Comment by joakime** [comment]
The test failure isn't terribly useful to troubleshoot from.
Jenkins isn't reporting this failure too.

**Comment by joakime** [comment]
The likely reason for your failure is that your machine is slower then the testcase timeout (which is what's triggering the test failure)

https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/ServerTimeoutsTest.java#L254

**Comment by joakime** [comment]
@sbordet want to up the timeout on that test case?

**Comment by hieplq** [comment]
By increase blockingTimeout i can success build 9.3.14.
but for 9.4.0, i still encounter issue relate fine alpn-boot.
from log, seem need to set value for version of alpn-boot.

[ERROR] mvn install:install-file -DgroupId=org.mortbay.jetty.alpn -DartifactId=alpn-boot -Dversion=undefined -Dpackaging=jar -Dfile=/path/to/file

bellow is full console log.
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:copy (copy) on project http2-alpn-tests: Unable to find artifact. Failure to find org.mortbay.jetty.alpn:alpn-boot:jar:undefined in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command:
[ERROR] mvn install:install-file -DgroupId=org.mortbay.jetty.alpn -DartifactId=alpn-boot -Dversion=undefined -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there:
[ERROR] mvn deploy:deploy-file -DgroupId=org.mortbay.jetty.alpn -DartifactId=alpn-boot -Dversion=undefined -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR] org.mortbay.jetty.alpn:alpn-boot:jar:undefined
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:copy (copy) on project http2-alpn-tests: Unable to find artifact.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to find artifact.
	at org.apache.maven.plugin.dependency.fromConfiguration.AbstractFromConfigurationMojo.getArtifact(AbstractFromConfigurationMojo.java:265)
	at org.apache.maven.plugin.dependency.fromConfiguration.AbstractFromConfigurationMojo.getProcessedArtifactItems(AbstractFromConfigurationMojo.java:171)
	at org.apache.maven.plugin.dependency.fromConfiguration.CopyMojo.doExecute(CopyMojo.java:105)
	at org.apache.maven.plugin.dependency.AbstractDependencyMojo.execute(AbstractDependencyMojo.java:167)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Failure to find org.mortbay.jetty.alpn:alpn-boot:jar:undefined in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

Try downloading the file manually from the project website.

Then, install it using the command: 
    mvn install:install-file -DgroupId=org.mortbay.jetty.alpn -DartifactId=alpn-boot -Dversion=undefined -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
    mvn deploy:deploy-file -DgroupId=org.mortbay.jetty.alpn -DartifactId=alpn-boot -Dversion=undefined -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]


  org.mortbay.jetty.alpn:alpn-boot:jar:undefined

from the specified remote repositories:
  central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)

	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:221)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:154)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:555)
	at org.apache.maven.plugin.dependency.fromConfiguration.AbstractFromConfigurationMojo.getArtifact(AbstractFromConfigurationMojo.java:257)
	... 25 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.mortbay.jetty.alpn:alpn-boot:jar:undefined in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:215)
	... 28 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.mortbay.jetty.alpn:alpn-boot:jar:undefined in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 32 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :http2-alpn-tests

**Comment by joakime** [comment]
The `org.mortbay.jetty.alpn:alpn-boot:jar:undefined` tells us that you are using a JDK version that is unsupported by that specific build.

There's no `<profile>` section in the maven build for the JDK you are using, which is a requirement for everything ALPN in the build.

Each JDK has to have a specific alpn-boot.jar built for it, so that we can insert the ALPN specific layers into the JDK for HTTP/2 support to function.  (this requirement should go away with JDK 9, as ALPN is a more formal API in the JDK then)
