### ISSUE TITLE
NPE thrown when sending redirects for folder address after the request is filtered by spring security

### ISSUE THREAD

**Issue by wodeidaiga** [eclipse/jetty.project#10579]
**Jetty version(s)**

12.0.1
**Jetty Environment**

ee10
**Java version/vendor** `(use: java -version)`
17
**OS type/version**
Ubuntu 22.04
**Description**

If user accesses a folder resource url without the end slash , and the request is filtered and wrapped by spring security FirewalledRequest, a NPE is thrown.

This is because in org.eclipse.jetty.ee10.servlet.ServletCoreRequest

``` java
 HttpURI.Mutable builder = HttpURI.build(request.getRequestURI());
        if (included)
            builder.path(addEncodedPaths(request.getContextPath(), encodePath(DefaultServlet.getIncludedPathInContext(request, includedServletPath, false))));
        else if (request.getDispatcherType() != DispatcherType.REQUEST)
            builder.path(addEncodedPaths(request.getContextPath(), encodePath(URIUtil.addPaths(_servletRequest.getServletPath(), _servletRequest.getPathInfo()))));
        builder.query(request.getQueryString()); <============  the uri is a relative uri like /webapp/folder, the _host will be null
        _uri = builder.asImmutable();
```

So when the folder uri triggers redirection, the HttpURI's _host is null and  an NPE is thrown.

``` java
static int getServerPort(Request request)
    {
        if (request == null)
            return -1;

        // Does the request have an explicit port?
        HttpURI uri = request.getHttpURI();
        if (uri.hasAuthority() && uri.getPort() > 0)
            return uri.getPort();

        // Is there a configured server authority?
        HostPort authority = request.getConnectionMetaData().getHttpConfiguration().getServerAuthority();
        if (authority != null && authority.getPort() > 0)
            return authority.getPort();

        // Is there a scheme with a default port?
        HttpScheme scheme = HttpScheme.CACHE.get(request.getHttpURI().getScheme());<=================== NPE thrown
```

```
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
	at org.eclipse.jetty.util.AbstractTrie.get(AbstractTrie.java:66)
	at org.eclipse.jetty.server.Request.getServerPort(Request.java:459)
	at org.eclipse.jetty.server.Request.toRedirectURI(Request.java:572)
	at org.eclipse.jetty.server.Response.sendRedirect(Response.java:317)
	at org.eclipse.jetty.server.Response.sendRedirect(Response.java:265)
	at org.eclipse.jetty.server.Response.sendRedirect(Response.java:243)
	at org.eclipse.jetty.server.ResourceService.sendRedirect(ResourceService.java:239)
	at org.eclipse.jetty.server.ResourceService.sendWelcome(ResourceService.java:465)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:174)
	at org.eclipse.jetty.ee10.servlet.DefaultServlet.doGet(DefaultServlet.java:534)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1378)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1608)
	at org.eclipse.jetty.ee10.servlets.HeaderFilter.doFilter(HeaderFilter.java:112)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at com.hp.alm.platform.web.XSSProtectionFilter.doFilter(XSSProtectionFilter.java:34)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:219)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
	at org.hp.qc.web.restapi.authentication.FilterChainProxyWrapper.doFilter(FilterChainProxyWrapper.java:92)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:208)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at com.mercury.optane.core.state.ServerStatusFilter.doFilter(ServerStatusFilter.java:37)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at org.hp.qc.web.restapi.authentication.LwssoRedirectFilter.doFilter(LwssoRedirectFilter.java:57)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at com.hp.alm.platform.web.NoSniffFilter.doFilter(NoSniffFilter.java:20)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at com.hp.alm.platform.web.HttpsHeaderFilter.doFilter(HttpsHeaderFilter.java:20)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at com.hp.alm.platform.web.HTTPMethodsFilter.doFilter(HTTPMethodsFilter.java:52)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at org.hp.qc.web.restapi.authentication.osp.OspCookieFilter.doFilter(OspCookieFilter.java:144)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at org.hp.qc.web.restapi.authentication.osp.OspCodeRedirectFilter.doFilter(OspCodeRedirectFilter.java:90)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at com.microfocus.alm.osp.filter.AlmOspFilter.doFilter(AlmOspFilter.java:132)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at org.hp.qc.web.restapi.filters.SendErrorFilter.doFilter(SendErrorFilter.java:57)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1541)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:885)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:490)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:550)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:663)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:811)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:712)
	at org.eclipse.jetty.server.Server.handle(Server.java:176)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:471)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by joakime** [comment]
Duplicate of #10558
