### ISSUE TITLE
NPE when including a directory that should be resolved with servlet-mapped welcome file

### ISSUE THREAD

**Issue by grgrzybek** [eclipse/jetty.project#10582]
**Jetty version(s)**
12.0.2-SNAPSHOT

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
```
$ java -version
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)
```

**OS type/version**
```
$ uname -srv
Linux 6.4.15-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:25:01 UTC 2023
```

**Description**
See https://github.com/grgrzybek/jetty.project/commit/53f7a6eaf7dd05a3edf0fede0490b3caf7b83d34 for reproducer.

When doing `dispatcher.include()` for a resource which is a directory and with welcome files configured, I'm getting this NPE:
```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "method" is null
	at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:522)
	at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1609)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1542)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.Dispatcher.include(Dispatcher.java:152)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.DispatcherTest$DispatchServletServlet.doGet(DispatcherTest.java:1186)
	at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1609)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1542)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:886)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:491)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:812)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:177)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:713)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.Server.handle(Server.java:176)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:649)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:471)
	at org.eclipse.jetty.io/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It's a bit of follow up of #10558, my work on Pax Web 10 (with Jetty 12, Tomcat 10.1 and Undertow 2.3 progresses) and while I've finally managed to unify this _path info only_ behavior, this is the problem I got in Jetty.

In my adjusted Pax Web tests, included directory which should be resolved by processing welcome files is empty because of how DefaultServlet handles include dispatch:
```java
// Check whether a Servlet may serve the welcome resource.
if (_welcomeServletMode != WelcomeServletMode.NONE && welcomeTarget == null)
{
    if (!isDefaultMapping(getServletRequest(coreRequest)) && !isIncluded(getServletRequest(coreRequest)))
        welcomeTarget = URIUtil.addPaths(getServletRequest(coreRequest).getPathInfo(), welcome);
    ServletHandler.MappedServlet entry = _servletContextHandler.getServletHandler().getMappedServlet(welcomeInContext);
    // Is there a different Servlet that may serve the welcome resource?
    if (entry != null && entry.getServletHolder().getServletInstance() != DefaultServlet.this)
    {
        if (_welcomeServletMode == WelcomeServletMode.MATCH || entry.getPathSpec().getDeclaration().equals(welcomeInContext))
        {
            welcomeTarget = welcomeInContext;
            // Do not break the loop, because we want to try other welcome resources
            // that may be files and take precedence over Servlet welcome resources.
        }
    }
}
```

I didn't change it and while in Pax Web I'm not getting welcome file resolved, in Jetty tests I have NPE.

**Comment by janbartel** [comment]
@grgrzybek I've opened PR #10587.

Basically, the test wasn't very good: we were using a `ServletRequestWrapper` expecting that the test servlets would override the `service()` method. But of course `DefaultServlet` does not. I've fixed the test, so take a look at the PR branch.

**Comment by grgrzybek** [comment]
This new `org.eclipse.jetty.ee10.servlet.DispatcherTest#testServletIncludeWelcome()` is fine. When sending `/context/dispatch/test?include=/r/` request, `org.eclipse.jetty.ee10.servlet.DefaultServlet.ServletResourceService#getWelcomeTarget()` uses `welcomeInContext="/r/index.x"` and `DispatcherTest$RogerThatServlet` servlet is found from this mapping:
```
_servletMappings: java.util.List  = {java.util.ArrayList@3507}  size = 3
 0 = {org.eclipse.jetty.ee10.servlet.ServletMapping@3525} "[/dispatch/*]=>org.eclipse.jetty.ee10.servlet.DispatcherTest$DispatchServletServlet-5a7fe64f"
 1 = {org.eclipse.jetty.ee10.servlet.ServletMapping@3526} "[/]=>org.eclipse.jetty.ee10.servlet.DefaultServlet-38145825"
 2 = {org.eclipse.jetty.ee10.servlet.ServletMapping@3527} "[*.x]=>org.eclipse.jetty.ee10.servlet.DispatcherTest$RogerThatServlet-41330d4f"
```

However I have more complex scenario, where additional `/r/*` mapped resource servlet is used:
```
_servletMappings: java.util.List  = {java.util.ArrayList@5193}  size = 5
 0 = {org.eclipse.jetty.ee10.servlet.ServletMapping@5211} "[/]=>default"
 1 = {org.eclipse.jetty.ee10.servlet.ServletMapping@5212} "[/r/*]=>resource"
 2 = {org.eclipse.jetty.ee10.servlet.ServletMapping@5213} "[/s/*]=>resource2"
 3 = {org.eclipse.jetty.ee10.servlet.ServletMapping@4409} "[*.x, *.y]=>indexx"
 4 = {org.eclipse.jetty.ee10.servlet.ServletMapping@5214} "[/gateway/*]=>gateway"
...
_servlets: java.util.List  = {java.util.ArrayList@5192}  size = 5
 0 = {org.eclipse.jetty.ee10.servlet.ServletHolder@4403} "default==org.ops4j.pax.web.service.jetty.internal.web.JettyResourceServlet@5c13d641{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:<null>,STARTED}"
 1 = {org.eclipse.jetty.ee10.servlet.ServletHolder@4405} "resource==org.ops4j.pax.web.service.jetty.internal.web.JettyResourceServlet@ebabc40e{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:<null>,STARTED}"
 2 = {org.eclipse.jetty.ee10.servlet.ServletHolder@4407} "resource2==org.ops4j.pax.web.service.jetty.internal.web.JettyResourceServlet@89ccbde4{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:<null>,STARTED}"
 3 = {org.eclipse.jetty.ee10.servlet.ServletHolder@4408} "indexx==org.ops4j.pax.web.service.jetty.internal.UnifiedJettyTest$3@b969f1e6{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:<null>,STARTED}"
 4 = {org.eclipse.jetty.ee10.servlet.ServletHolder@4410} "gateway==org.ops4j.pax.web.service.jetty.internal.UnifiedJettyTest$4@f4ba4644{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:<null>,STARTED}"
```

`org.ops4j.pax.web.service.jetty.internal.web.JettyResourceServlet` is almost the same as `org.eclipse.jetty.ee10.servlet.DefaultServlet` (one change related to OSGi which doesn't have to be present in Jetty itself).

When additional `/r/*` mapping exists, `dispatcher("/r/").include()` is handled by `/r/*` servlet and servlet mapping for `/r/index.x` finds not the `DispatcherTest$RogerThatServlet` servlet (or my `indexx` servlet), but the same resource servlet and `entry.getServletHolder().getServletInstance() != DefaultServlet.this` is false this time.

This issue (taking `/r/` servlet path or not when constructing URL to find mapping for welcome servlet) is related to #9910 discussion.
I have an impression that there's a decision that Jetty before 12 was incorrect and servlet path should NOT be taken into account - both when finding welcome files and when constructing final forward/redirect URI.

See changed unit test for the above scenario (with additional `/r/*` resources servlet): https://github.com/grgrzybek/jetty.project/commit/d3552703d09feea96832a81519fdd9dbb12fc9d2

And again - thank you very much @janbartel for your quick responses and patience ;)

**Comment by janbartel** [comment]
Opened related issues for further investigation:  #10608 and #10609

**Comment by grgrzybek** [comment]
thanks!

**Comment by janbartel** [comment]
Fixed via #10587

**Comment by grgrzybek** [comment]
Thanks @janbartel for this, but unfortunately I checked with tiny change to `org.eclipse.jetty.ee10.servlet.DispatcherTest#testServletIncludeWelcome()`:
```
08:15 $ git diff
diff --git a/jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DispatcherTest.java b/jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DispatcherTest.java
index 07dcfbb1eca..651cad601a8 100644
--- a/jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DispatcherTest.java
+++ b/jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DispatcherTest.java
@@ -419,6 +419,10 @@ public class DispatcherTest
         _contextHandler.addServlet(DispatchServletServlet.class, "/dispatch/*");
         ServletHolder defaultHolder = _contextHandler.addServlet(DefaultServlet.class, "/");
         defaultHolder.setInitParameter("welcomeServlets", "true");
+        defaultHolder.setInitParameter("dirAllowed", "false");
+        ServletHolder defaultHolder2 = _contextHandler.addServlet(DefaultServlet.class, "/r/*");
+        defaultHolder2.setInitParameter("welcomeServlets", "true");
+        defaultHolder2.setInitParameter("dirAllowed", "false");
         _contextHandler.addServlet(RogerThatServlet.class, "*.x");
         _server.start();
```

and it doesn't work... when there's only `/` mapped default servlet it works, but with `/r/*` mapped default servlet it fails - the content is not really included (no `"Roger That!"` from included servlet through `/r/*`...

**Comment by grgrzybek** [comment]
Ah - I see #10608 is still open.
