### ISSUE TITLE
Jetty 11 - Weird onWebSocketError() when work with NGINX proxy

### ISSUE THREAD

**Issue by nhancdt2602** [eclipse/jetty.project#10614]
**Jetty version(s)**
11.0.15

**Java version/vendor** `(use: java -version)`
openjdk 17.0.8.1 2023-08-24

**OS type/version**
Ubuntu

**Description**
When I followed setting up simple websocket server similar to this [example](https://github.com/jetty-project/embedded-jetty-websocket-examples/tree/10.0.x/native-jetty-websocket-example).
Then I write a simple client that continously send binary/text message to websocket, everything worked normally and no error callback was called.
However, when I setup nginx proxy with this config:
```
events {}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
 
    upstream websocket {
        server localhost:9010;
    }
 
    server {
        listen 80;
        location / {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
        }
    }
}

```
And then the client call to that proxy (port 80 instead of port 9010. There was nothing wrong in client side but in the server side, the `onWebSocketError()` callback was always called with exception when the server close websocket by calling `getSession().close(StatusCode.NORMAL, "Thanks")`
```
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onEof(WebSocketSessionState.java:169)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:253)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:482)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

You can easily reproduce this issue. Hope that jetty team will address this problem soon because most of industry use nginx as their proxy instead of publicly expose websocket directly to the Internet

**Comment by lachlan-roberts** [comment]
Jetty is behaving correctly here. The Jetty WebSocket server has sent a close Frame with a normal status code, and because of this it is waiting for the close response (described in  https://datatracker.ietf.org/doc/html/rfc6455#section-1.4).

The NGINX proxy never sends a close response frame to Jetty and instead just closes the connection. So you are seeing this error because Jetty has read EOF while awaiting the close response.

The NGINX proxy should instead wait for a close frame response from the client before closing the connection to the server, and then send a close frame with same code and status back to the server.

**Comment by lachlan-roberts** [comment]
I tested this a few times, and it seems sometimes NGINX is sending the close to the server and sometimes it is not, so maybe a bug in their proxy implementation.

**Comment by nhancdt2602** [comment]
@lachlan-roberts So it seems the error come from NGINX. Does this error affect the performance or potentially creates any memory leak in jetty server?
And do Jetty team have any next action to address this problem or we just ignore it?

**Comment by lachlan-roberts** [comment]
>  Does this error affect the performance or potentially creates any memory leak in jetty server?

I don't see any reason why this would be causing a memory leak in Jetty, unless you have any evidence that it does.

> And do Jetty team have any next action to address this problem or we just ignore it?

I don't see any action that we could take to address this. Perhaps you should open a bug with the NGINX team.

From the Jetty perspective, when we have sent a close frame, we may still receive some data frames before the response close frame. So if we see connection closed before the response close frame we report an error as the close handshake was never completed.

In the case you send an "error" status code, Jetty will send a close frame and then immediately close the connection not waiting for the close response. But for a normal close status we expect to complete the full close handshake.
