### ISSUE TITLE
HostPortHttpField should handle port-only values

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1063]
As identified in issue #1062 the syntax of the `Host` header in jmeter is like this ...

    Host: :8080

This format results in an illegal request format in Jetty ...

```
2016-11-02 14:52:29.900:WARN:oejh.HttpParser:qtp359037866-40: bad HTTP parsed: 400 Bad HostPort for HttpChannelOverHttp@f64c140{r=0,c=false,a=IDLE,uri=null}
org.eclipse.jetty.http.BadMessageException: 400: Bad HostPort
    at org.eclipse.jetty.http.HostPortHttpField.<init>(HostPortHttpField.java:48)
    at org.eclipse.jetty.http.HttpParser.parsedHeader(HttpParser.java:914)
    at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:1088)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1320)
    at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:350)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.IllegalArgumentException: Bad host
    at org.eclipse.jetty.util.HostPort.<init>(HostPort.java:82)
    at org.eclipse.jetty.http.HostPortHttpField.<init>(HostPortHttpField.java:44)
    at org.eclipse.jetty.http.HttpParser.parsedHeader(HttpParser.java:914)
    at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:1088)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1320)
    at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:350)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
```

**Comment by gregw** [comment]
@joakime I implemented this to allow the "" string through.  Tested in unit test, but not in context of #1062
