### ISSUE TITLE
Fix HTTP/3 Client handling of MAX_FIELD_SECTION_SIZE setting

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10759]
**Jetty version(s)**
10.0.x, 11.0.x, 12.0.x

**Description**
`ClientServerTest.testRequestHeadersTooLarge()` sometimes fail with:

```
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
	at org.eclipse.jetty.http3.tests.ClientServerTest.testRequestHeadersTooLarge(ClientServerTest.java:396)
```

See:
 - Jetty 12: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-10757/2/tests/
 - Jetty 10: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-10758/3/tests/

**Comment by lorban** [comment]
A first pass of investigation shows that the test fails when the headers are deemed not too large, which makes the request with the large header unexpectedly succeed.

Apparently, this seems to be caused by a race condition between the client parses the too-large header frame and the client receiving a settings frame in which the server tells the client to re-adjust its max headers size.
