### ISSUE TITLE
Connection rejected: No ALPN Processor for sun.security.ssl.SSLEngineImpl from [org.eclipse.jetty.alpn.conscrypt.server.ConscryptServerALPNProcessor]

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#10859]
**Jetty Version**
12.0.3

**Jetty Environment**
I am not using the servlet API.

**Java Version**
21.0.1

**Question**
I am running into a problem similar to https://github.com/jetty/jetty.project/issues/10561 but using Jetty 12. I am not shadowing any JAR file but it sounds like I must be missing something on the classpath.

I've got `jetty-alpn-server`, `jetty-alpn-conscrypt-server` on the classpath and I thought this would be enough. Do I need to add any other alpn-related artifacts to resolve this error?

Here is the error I'm getting:

```
java.lang.IllegalStateException: Connection rejected: No ALPN Processor for sun.security.ssl.SSLEngineImpl from [org.eclipse.jetty.alpn.conscrypt.server.ConscryptServerALPNProcessor@753c9d29]
	at org.eclipse.jetty.alpn.server@12.0.3/org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory.newServerConnection(ALPNServerConnectionFactory.java:106)
	at org.eclipse.jetty.server@12.0.3/org.eclipse.jetty.server.NegotiatingServerConnectionFactory.newConnection(NegotiatingServerConnectionFactory.java:102)
	at org.eclipse.jetty.server@12.0.3/org.eclipse.jetty.server.SslConnectionFactory.newConnection(SslConnectionFactory.java:161)
	at org.eclipse.jetty.server@12.0.3/org.eclipse.jetty.server.DetectorConnectionFactory.upgradeToConnectionFactory(DetectorConnectionFactory.java:109)
	at org.eclipse.jetty.server@12.0.3/org.eclipse.jetty.server.DetectorConnectionFactory.nextProtocol(DetectorConnectionFactory.java:131)
	at org.eclipse.jetty.server@12.0.3/org.eclipse.jetty.server.DetectorConnectionFactory$DetectorConnection.detectAndUpgrade(DetectorConnectionFactory.java:294)
	at org.eclipse.jetty.server@12.0.3/org.eclipse.jetty.server.DetectorConnectionFactory$DetectorConnection.onFillable(DetectorConnectionFactory.java:218)
	at org.eclipse.jetty.io@12.0.3/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.3/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io@12.0.3/org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at app.licensed.server/app.licensed.server.jetty.JettyServer.lambda$start$0(JettyServer.java:357)
	at app.licensed.common@1.0-SNAPSHOT/app.licensed.common.util.DelegatingThreadFactory.lambda$newThread$0(DelegatingThreadFactory.java:37)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```

Here is my Jetty-related classpath:
![image](https://github.com/jetty/jetty.project/assets/633348/abd53770-c42c-4907-9e36-22edf684a7eb)

**Comment by cowwoc** [comment]
I am using Java Modules, so they might somehow be related to the problem.

Here is the relevant section from my `module-info`:

```
requires transitive org.eclipse.jetty.client;
requires org.eclipse.jetty.http;
requires org.eclipse.jetty.http2.server;
requires org.eclipse.jetty.alpn.server;
requires org.eclipse.jetty.alpn.conscrypt.server;
requires org.eclipse.jetty.http3.server;
requires transitive org.eclipse.jetty.rewrite;
```

**Comment by sbordet** [comment]
You also need the Conscrypt implementation, `conscrypt-openjdk-uber-2.5.2.jar` or similar.

If it is there, you must make sure that Conscrypt is the provider you actually use, so you should have something like:

```java
// Set Conscrypt as the first provider.
Security.insertProviderAt(new OpenSSLProvider(), 1);

// Or, add Conscrypt and configure it.
Security.addProvider(new OpenSSLProvider());
sslContextFactory.setProvider("Conscrypt");
```

**Comment by cowwoc** [comment]
@sbordet Thank you. That was it. I consider this question answered, but I suggest documenting this in the Programming Guide or Operations Guide. Currently, it doesn't seem to be mentioned at all.

**Comment by sbordet** [comment]
What was it? Missing jar or missing call to `Security`?

**Comment by cowwoc** [comment]
I opted to use:

```
Security.addProvider(new OpenSSLProvider());
sslContextFactory.setProvider("Conscrypt");
````

The JAR was there. The configuration steps were not.

**Comment by sbordet** [comment]
Documentation updated in a9878863aa59bf953e35dc37d668ff576e28065f.
