### ISSUE TITLE
ShutdownHandler gets stuck during startup of jetty server

### ISSUE THREAD

**Issue by pierrecoquentin-datadome** [eclipse/jetty.project#10907]
**Jetty version(s)**
Jetty Server 10.0.18 (and newer versions)

**Java version/vendor** `(use: java -version)`
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

**OS type/version**
Ubuntu 22.04

**Description**
When configuring the `ShutdownHandler` to send a request during the server's startup to ensure no other server with the same config is still running, it will get stuck waiting for an answer. It was working with Jetty 9.x, but not anymore with Jetty 10.x and newer versions.
```
"main" #1 prio=5 os_prio=0 cpu=474,71ms elapsed=21,30s tid=0x00007ff50c02a680 nid=0x5f39 runnable  [0x00007ff5129fd000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.SocketDispatcher.read0(java.base@17/Native Method)
	at sun.nio.ch.SocketDispatcher.read(java.base@17/SocketDispatcher.java:47)
	at sun.nio.ch.NioSocketImpl.tryRead(java.base@17/NioSocketImpl.java:261)
	at sun.nio.ch.NioSocketImpl.implRead(java.base@17/NioSocketImpl.java:312)
	at sun.nio.ch.NioSocketImpl.read(java.base@17/NioSocketImpl.java:350)
	at sun.nio.ch.NioSocketImpl$1.read(java.base@17/NioSocketImpl.java:803)
	at java.net.Socket$SocketInputStream.read(java.base@17/Socket.java:966)
	at java.io.BufferedInputStream.fill(java.base@17/BufferedInputStream.java:244)
	at java.io.BufferedInputStream.read1(java.base@17/BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(java.base@17/BufferedInputStream.java:343)
	- locked <0x000000062d3cd1f0> (a java.io.BufferedInputStream)
	at sun.net.www.http.HttpClient.parseHTTPHeader(java.base@17/HttpClient.java:791)
	at sun.net.www.http.HttpClient.parseHTTP(java.base@17/HttpClient.java:726)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(java.base@17/HttpURLConnection.java:1688)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@17/HttpURLConnection.java:1589)
	at java.net.HttpURLConnection.getResponseCode(java.base@17/HttpURLConnection.java:529)
	at org.eclipse.jetty.server.handler.ShutdownHandler.sendShutdown(ShutdownHandler.java:109)
	at org.eclipse.jetty.server.handler.ShutdownHandler.doStart(ShutdownHandler.java:147)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:470)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:415)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at MainServer.main(MainServer.java:35)
```

Since Jetty 10.x, during the startup, the server will ensure it can bind to the provided port:
```java
            // Open network connector to ensure ports are available
            if (!_dryRun)
            {
                _connectors.stream().filter(NetworkConnector.class::isInstance).map(NetworkConnector.class::cast).forEach(connector ->
                {
                    try
                    {
                        connector.open();
                    }
                    catch (Throwable th)
                    {
                        mex.add(th);
                    }
                });
                // Throw now if verified start sequence and there was an open exception
                mex.ifExceptionThrow();
            }
```
The problem with doing that is that when the `ShutdownHandler` sends its request, the server will now accept its connection, but as it's not yet fully started, it will never answer, and the server will never start.

**How to reproduce?**
A quick example below: the console will never display `STARTED`, and the server will get stuck.
```java
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.HandlerList;
import org.eclipse.jetty.server.handler.ShutdownHandler;
import org.eclipse.jetty.servlet.ServletContextHandler;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class MainServer {

    public static void main(String[] args) throws Exception {
        Server server = new Server(8080);
        ServletContextHandler context = new ServletContextHandler();
        context.setContextPath("/");
        context.addServlet(HelloServlet.class, "/hello");
        ShutdownHandler shutdown = new ShutdownHandler("1234", false, true);
        HandlerList handlers = new HandlerList();
        handlers.setHandlers(new Handler[] {shutdown, context});
        server.setHandler(handlers);
        server.start();
        System.out.println("STARTED");
        server.join();
    }

    public static class HelloServlet extends HttpServlet {

        @Override
        protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
            resp.setContentType("text/plain");
            resp.getWriter().println("Hello World!");
        }
    }
}

**Comment by gregw** [comment]
Is this still an issue?

**Comment by pierrecoquentin-datadome** [comment]
I don't see the option `_sendShutdownAtStart` in Jetty `12.1.0`. So I would say that the feature is no longer broken, as it has been removed.

**Comment by pierrecoquentin-datadome** [comment]
@joakime I think you can close it. The option to shut down a pre-existing Jetty server on startup has been removed in this commit: https://github.com/jetty/jetty.project/commit/81f7031cfef0e1855009b1d0a6b96d2851f07aad#diff-16a3f15bffb7074c3e63f2f7bbcb8825a9aa9d7b82c95a4c126e300025300e46
