### ISSUE TITLE
jetty-runner jstl support

### ISSUE THREAD

**Issue by a-a-davydov** [eclipse/jetty.project#1092]
I use jetty-runner to run me .war applications.

I've migrate to jetty-runner 9.3.14.v20161028 from 9.3.0.M0 and got following exception

```
org.apache.jasper.JasperException:` The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55)
	at `org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:277)
```

So I google stackoverflow for reason and solution. I have found two workarounds

Add to pom
```
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>apache-jstl</artifactId>
            <version>9.3.14.v20161028</version>
        </dependency>
```

Or Add to pom
```
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
            <version>1.2</version>
        </dependency>
```

Both solutions works well (I have no time for deep tests, but some difficult pages rendered correct)

But as I see in jetty-runner jar and pom apache-jstl is already in. If it correct I should add jstl in my war directly or some kind of bug in runner implementation?

N.B. Jetty maven plugin in Netbeans works fine on the same jetty.xml without any additional dependency.

**Comment by janbartel** [comment]
@a-a-davydov you must have a context xml file that controls the deployment of your webapp, yes? 

The jetty-runner assumes that if you're using a context xml file, you will set up the names of all the configuration classes you want applied to the context. 
Unfortunately, if you don't specify the full set, it falls back to the minimum, which does not include the AnnotationConfiguration class that is these days essential for jsp/jstl to work properly.

To make it work properly, you need to add some xml like so to your context xml file:

```xml
  <Set name="configurationClasses">
    <Call class="org.eclipse.jetty.webapp.Configuration$ClassList" name="serverDefault">
      <Arg><Ref refid="Server" /></Arg>
      <Call name="addAfter">
        <Arg name="afterClass">org.eclipse.jetty.webapp.FragmentConfiguration</Arg>
        <Arg>
          <Array type="String">
<!-- only include if you want to do jndi
            <Item>org.eclipse.jetty.plus.webapp.EnvConfiguration</Item>
            <Item>org.eclipse.jetty.plus.webapp.PlusConfiguration</Item>
-->
            <Item>org.eclipse.jetty.annotations.AnnotationConfiguration</Item>
          </Array>
        </Arg>
      </Call>
    </Call>
  </Set>
```

I think this might be something we can solve with documentation, so I'll assign it to Chris to update the docs.

**Comment by a-a-davydov** [comment]
Tanks for answer. Now I don't use any context.xml. I run my server using following command:

nohup java -DconfigPath=file:config/web -jar dependency/jetty-runner.jar --stop-port 10000 --stop-key stop --port 8080 --config config/jetty.plugin.xml --path /helper myWebApp.war >logfile.log &2>1 &

I try to avoid any Jetty specified fetures in project. Now I use only minimal jetty-web.xml to setup gzip handler.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
    
    <Set name="gzipHandler">
        <New id="GzipHandler" class="org.eclipse.jetty.server.handler.gzip.GzipHandler">
... Some gzip setup ...
        </New>        
    </Set>      
</Configure>

**Comment by a-a-davydov** [comment]
If I add additional configs as in you comment to my jetty-web.xml I get following exception

2016-11-16 16:03:16.277:INFO:oejr.Runner:main: Runner
Error binding ShutdownMonitor to port 10000: java.net.BindException: Address alr
eady in use: JVM_Bind
2016-11-16 16:03:16.547:INFO:oejs.Server:main: jetty-9.3.14.v20161028
2016-11-16 16:03:21.529:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed
 time=3403ms
2016-11-16 16:03:21.599:WARN:oejw.WebAppContext:main: Failed startup of context
o.e.j.w.WebAppContext@2cfb4a64{/helper,file:///C:/Users/DELL/AppData/Local/Temp/
jetty-0.0.0.0-8080-web-1.0.0-SNAPSHOT.war-_helper-any-4764944523307549113.dir/we
bapp/,UNAVAILABLE}{file:///D:/14_novr/zzzzzzzz/web-1.0.0-SNAPSHOT.war}
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:4
91)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.jav
a:1361)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandle
r.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContex
tHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(Con
textHandlerCollection.java:161)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi
feCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:422)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container
LifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand
ler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:389)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
        at org.eclipse.jetty.runner.Runner.main(Runner.java:536)
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:31
7)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet
workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java
:235)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
        at org.eclipse.jetty.runner.Runner.main(Runner.java:536)

**Comment by a-a-davydov** [comment]
I've read http://www.eclipse.org/jetty/documentation/9.3.x/configuring-specific-webapp-deployment.html article and undestatd logic of configuration. So I creale simple jetty-context.xml

```
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath"><SystemProperty name="helper.context.path"/></Set>
  <Set name="war"><SystemProperty name="helper.war.file"/></Set>
  
  <Set name="configurationClasses">
    <Call class="org.eclipse.jetty.webapp.Configuration$ClassList" name="serverDefault">
      <Arg><Ref refid="Server" /></Arg>
      <Call name="addAfter">
        <Arg name="afterClass">org.eclipse.jetty.webapp.FragmentConfiguration</Arg>
        <Arg>
          <Array type="String">
<!-- only include if you want to do jndi
            <Item>org.eclipse.jetty.plus.webapp.EnvConfiguration</Item>
            <Item>org.eclipse.jetty.plus.webapp.PlusConfiguration</Item>
-->
            <Item>org.eclipse.jetty.annotations.AnnotationConfiguration</Item>
          </Array>
        </Arg>
      </Call>
    </Call>
  </Set>  
</Configure>

```
and run server using command:

```
java -DconfigPath=file:config/web -Dhelper.context.path=/helper -Dhelper.war.file=web-1.0.0-SNAPSHOT.war -jar dependency/jetty-runner.jar --stop-port 10000 --stop-key stop --port 8080 --config config/jetty.plugin.xml config/jetty-context.xml

and I got same exception as in initial issue report =(

org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55)
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:277)
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:75)
	at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTldResourcePath(TagLibraryInfoImpl.java:243)
	at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:124)
	at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:421)
	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:479)
	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1435)
	at org.apache.jasper.compiler.Parser.parse(Parser.java:139)
	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:227)
	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:100)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:199)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:385)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1243)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:462)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by a-a-davydov** [comment]
I found core reason of problem.

I have download sources of jetty-runner 9.3.14.v20161028 and run under IDE with debug. (Best document in open-source is source =))) )

So I found in class org.eclipse.jetty.runner.Runner line 79:
`
public static final String __containerIncludeJarPattern =  ".*/jetty-runner-[^/]*\\.jar$";

`

And lines after 424:


```
                        if (!ctx.isDirectory() && ctx.toString().toLowerCase(Locale.ENGLISH).endsWith(".xml"))
                        {
                            // It is a context config file
                            XmlConfiguration xmlConfiguration = new XmlConfiguration(ctx.getURL());
                            xmlConfiguration.getIdMap().put("Server", _server);
                            ContextHandler handler = (ContextHandler) xmlConfiguration.configure();
                            if (contextPathSet)
                                handler.setContextPath(contextPath);
                            _contexts.addHandler(handler);
                            handler.setAttribute("org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern", __containerIncludeJarPattern);
                        }
                        else 
                        {
                            // assume it is a WAR file
                            WebAppContext webapp = new WebAppContext(_contexts, ctx.toString(), contextPath);
                            webapp.setConfigurationClasses(__plusConfigurationClasses);
                            webapp.setAttribute("org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern",
                                    __containerIncludeJarPattern);
                        }

```
Then I update my maven scripts to generate enviroment using name "jetty-runner-actual.jar" instead of "jetty-runner.jar" and everething become fine.

So I see two ways to resolve:
1. Simple. Add info that runner jar name is VERY important for correct work
2. Use more sofisticated way to understand Runner.class jar file in system

**Comment by joakime** [comment]
So you are using a customized version of `jetty-runner.jar`?
Or are you just renaming the standard jetty-runner.jar file name?

Option #3 could be to discover the jar artifact name for the runner mainClass and use that in the __containerIncludeJarPattern.

Out of curiosity, you have some heavy configuration and customization going on, why are you not using the jetty-distribution and its `${jetty.base}` concepts instead?

**Comment by janbartel** [comment]
I still think we can solve this with documentation:  we just need to document the default setting of the containerIncludeJarPattern, and instructions on how to set it if you deviate from the standard name of the runner jar, **or** you have other jars with taglibs that you've put on the server classpath and need to have inspected.

**Comment by a-a-davydov** [comment]
Joakim, I just rename jar to avoid update my shell scripts every time I migrate to new jetty.

Jan, one more problem for documentation.
In http://www.eclipse.org/jetty/documentation/9.3.x/runner.html article has following information:

> Configuring the container classpath
> With a local installation of Jetty, you add jars and classes to the container’s classpath by putting them in the {$jetty.base}/lib directory. With the jetty-runner, you can use the --lib, --jar and --classes arguments instead to achieve the same thing.
> 
> --lib adds the location of a directory which contains jars to add to the container classpath. You can add 1 or more. Here’s an example of configuring 2 directories:

But as we see in sources (and as reproduce in test), scanning for resources, for tlds and for other stuff in META-INF will be performed only in jars with name support pattern jetty-runner-<xxx>.jar. So --lib has not exactly same behavior as put jar to {$jetty.base}/lib

**Comment by janbartel** [comment]
@a-a-davydov actually with the jetty distro, _no_ jars on the container classpath are scanned _unless_ their names match a pattern that is set on the containerIncludeJarPattern. We set a default pattern in the etc/jetty-deploy.xml that sets up the containerIncludeJarPattern to include the names of the jars that we know contain META-INF info that we need (really just the jstl jar). So in that sense, the use of the containerIncludeJarPattern is absolutely consistent, its just that with the runner we have to set it to a different default value.

I've changed the code slightly, so that if you use a context xml file to deploy your webapp, it will append the default pattern for the runner jar. That way you can use a context xml file to set up the conatinerIncludeJarPattern exactly how you want it:  if you happen to have renamed the jetty-runner jar, then the addition of the default pattern on the end is harmless.

**Comment by janbartel** [comment]
@a-a-davydov oh ok, and I've made one more change too:  now if you have a context xml file that describes your webapp, and you haven't explicitly set up any Configuration classes that you want  to use, we assume you're going to use everything, thus by default anyone wishing to use jsps will have all the necessary Configurations set up ready-to-go.

If, on the other hand, you want minimal setup, then make sure that your context xml file explicitly sets up only the configuration classes you need.

I know this wasn't your problem, but you got me thinking about it :)
