### ISSUE TITLE
Flaky test `MultiPartServletTest.testMultiPartGzip`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#10944]
**Jetty version(s)**
12.0.x

**Jetty Environment**
ee10

**Description**
`org.eclipse.jetty.ee10.servlet.MultiPartServletTest.testMultiPartGzip` sometimes fails with:

```
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.client.InputStreamResponseListener$Input.read(InputStreamResponseListener.java:304)
	at java.base/java.io.InputStream.read(InputStream.java:218)
	at org.eclipse.jetty.client.InputStreamResponseListener$Input.read(InputStreamResponseListener.java:279)
	at java.base/java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
	at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:266)
	at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.MultiPartServletTest.testMultiPartGzip(MultiPartServletTest.java:429)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:167)
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

When the test fails, the console contains this:

```
2023-11-29 06:14:45.499:INFO :oejs.Server:ForkJoinPool-1-worker-1: Stopped oejs.Server@3fbc5630{STOPPING}[12.0.4-SNAPSHOT,sto=0]
2023-11-29 06:14:45.500:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-1: Stopped ServerConnector@71fff4f{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
2023-11-29 06:14:45.500:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-1: Stopped oeje10s.ServletContextHandler@4fab223f{ROOT,/,b=null,a=AVAILABLE,h=GzipHandler@4995fe0{STOPPED,min=32,inflate=-1}}
2023-11-29 06:14:48.000:WARN :oeju.Blocker:qtp280894807-2683: Blocking.Shared incomplete
2023-11-29 06:14:48.001:WARN :oejs.Request:qtp280894807-2683: org.eclipse.jetty.ee10.servlet.ServletContextHandler$$Lambda$696/0x00000007c030bb38@70d2a834 threw
java.lang.IllegalStateException: s=HANDLING rs=BLOCKING os=ABORTED is=IDLE awp=false se=false i=true al=0
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannelState.recycle(ServletChannelState.java:1055)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.recycle(ServletChannel.java:417)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.CompletionStreamWrapper.onCompletion(CompletionStreamWrapper.java:74)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.CompletionStreamWrapper.failed(CompletionStreamWrapper.java:53)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.completeStream(HttpChannelState.java:704)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.failed(HttpChannelState.java:673)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.failed(HttpChannelState.java:1470)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.gzip.GzipResponseAndCallback.failed(GzipResponseAndCallback.java:115)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.abort(ServletChannel.java:834)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.handleException(ServletChannel.java:689)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:612)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:716)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.EagerFormHandler.lambda$handle$0(EagerFormHandler.java:73)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.content.ContentSourceCompletableFuture.parse(ContentSourceCompletableFuture.java:107)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1208)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextRequest$OnContextDemand.run(ContextRequest.java:74)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection$DemandContentCallback.succeeded(HttpConnection.java:690)
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1714/testReport/junit/org.eclipse.jetty.ee10.servlet/MultiPartServletTest/Parallel_Stage___Build___Test___JDK17___testMultiPartGzip_boolean__1__true/

**Comment by lorban** [comment]
I think the `IllegalStateException` in the console is caused by #11016 and doesn't explain why the test failed with an idle timeout.

**Comment by joakime** [comment]
@lorban doesn't PR #11016 fix this?

**Comment by lorban** [comment]
@joakime I think it does as this failure isn't reproducible anymore.

**Comment by joakime** [comment]
This is fixed.
we can open a new issue if it pops up again.
