### ISSUE TITLE
Exit startup if java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by eBoyy** [eclipse/jetty.project#1101]
Similar to the issue here: [Process doesn't exit if port is already in use #114](https://github.com/mesosphere/marathon/issues/114)

If two Jetty instances are started on the same machine on the same port, the second one throws an exception but never exits. It seems more appropriate to print an error and exit. Is there a reason to let the second process live?

Stack trace from second Jetty process:

    Exception in thread "main" java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at com.xx.xx.xx.Bootstrap.main(Bootstrap.java:101)
    Caused by: java.net.BindException: Address already in use
    	at sun.nio.ch.Net.bind0(Native Method)
    	at sun.nio.ch.Net.bind(Net.java:444)
    	at sun.nio.ch.Net.bind(Net.java:436)
    	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
    	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
    	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
    	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
    	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    	at org.eclipse.jetty.server.Server.doStart(Server.java:291)
    	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    	... 5 more

**Comment by joakime** [comment]
[Jetty 8 is EOL (End of Life)](https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00069.html), consider upgrading to some supported/stable version of Jetty.

On Jetty 9+ you'll experience a `org.eclipse.jetty.util.MultiException` thrown from your `com.xx.xx.xx.Bootstrap.main` which will iterate through all of the startup exceptions, including Connector bind errors.
