### ISSUE TITLE
NumberFormatException when calling getParameter

### ISSUE THREAD

**Issue by spielzeugland** [eclipse/jetty.project#1102]
Calling getParameter() in ServletFilter fails with NumberFormatException if one parameter name contains "%" character like "my%param".

The same was posted in mailing list some time ago by someone else:
Same as https://dev.eclipse.org/mhonarc/lists/jetty-users/msg05792.html

Proper URL encoding solves this issue from the client perspective. But I am wondering whether there should be an exception in such cases.

Stacktrace:
_java.lang.NumberFormatException: [...]
        at org.eclipse.jetty.util.TypeUtil.convertHexDigit(TypeUtil.java:375)
        at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:555)
        at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:611)
        at org.eclipse.jetty.server.Request.extractParameters(Request.java:357)
        at org.eclipse.jetty.server.Request.getParameter(Request.java:790)
        at com.company.servlet.filter.CustomFilter.doFilter(CustomFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:317)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:651)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)_

**Comment by joakime** [comment]
Two things.

1. The parameter `my%param` is invalid per URL/URI spec, you have to encode the `%` symbol to `my%25param`.  There is are no exceptions for invalid encoding.
2. It is an anti-pattern to be accessing `getParameter()` from a Filter.  Why?  Per the servlet spec, accessing `.getParameter()` will cause the Request URI to be parsed (for Path Parameters and Query Parameters), *and* (this is the critical piece) the Request Input Stream for form parameters.  Which means that any downstream servlet expecting to be able to read the `HttpServletRequest.getInputStream()` will be unable to, as its been read, in its entirety by your filter.

Would suggest you first correct your URL/URI encoding, then using the `HttpServletRequest.getQueryString()` in your Filter to access the information you need/want, as that will not trigger the `InputStream` read.

**Comment by spielzeugland** [comment]
Thanks for the second hint. I wasn't aware of this. However the issue will also occur when reading from the request in the servlet. I just think a server should be robust here instead of throwing an exception e.g. by ignoring the parameter and log an appropriate message like "Request contains invalid parameter {0}". In our case it were customers who accidental entered such invalid parameters. Similar issue but with different exception occurs for parameter values containing "%".

**Comment by gregw** [comment]
@spielzeugland Many users would like such URI errors to be programmatically and just logged.  However, probably just as many want them to be fatal to the request.
