### ISSUE TITLE
Jetty sockets get closed on windows

### ISSUE THREAD

**Issue by alinzirbo** [eclipse/jetty.project#11061]
After some time i started to get this warning error from jetty 9.4.51 on windows server 2019 

```
WARN   [qtp1896974503-1047][] - java.io.IOException: An operation was attempted on something that is not a socket
            at sun.nio.ch.SocketDispatcher.close0(Native Method)
            at sun.nio.ch.SocketDispatcher.close(SocketDispatcher.java:63)
            at sun.nio.ch.SocketChannelImpl.kill(SocketChannelImpl.java:878)
            at sun.nio.ch.WindowsSelectorImpl.implDereg(WindowsSelectorImpl.java:613)
            at sun.nio.ch.SelectorImpl.processDeregisterQueue(SelectorImpl.java:149)
            at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:186)
            at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
            at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:105)
            at org.eclipse.jetty.io.ManagedSelector.nioSelect(ManagedSelector.java:183)
            at org.eclipse.jetty.io.ManagedSelector.select(ManagedSelector.java:200)
            at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:605)
            at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:542)
            at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362)
            at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186)
            at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
            at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
            at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
            at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
            at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
            at java.lang.Thread.run(Thread.java:750)
```

And from time to time i also get :

```
WARN   [qtp407261422-4877][] - Fatal select() failure java.io.IOException: Unable to establish loopback connection
    at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:94)
    at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171)
    at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
    at java.nio.channels.Pipe.open(Pipe.java:155)
    at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:142)
    at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
    at java.nio.channels.Selector.open(Selector.java:227)
    at org.eclipse.jetty.io.SelectorManager.newSelector(SelectorManager.java:383)
    at org.eclipse.jetty.io.ManagedSelector.handleSelectFailure(ManagedSelector.java:221)
    at org.eclipse.jetty.io.ManagedSelector.select(ManagedSelector.java:210)
    at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:606)
    at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:543)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.SocketException: Socket operation on nonsocket: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:461)
    at sun.nio.ch.Net.bind(Net.java:453)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:78)
    at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:121)
    at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:76)
    ... 21 more

```
With that last warning jetty it will be dead and i need to restart the entire app to get everything back into working stated. I searched over the whole web and everywhere is related to vpn/firewall... but i need to know exactly what is the cause for this issue.

Thanks,
Alin.

**Comment by alinzirbo** [comment]
Any ideea or help on this?
Thanks,
Alin.

**Comment by sbordet** [comment]
Jetty 9.4.x is at end of community support, see #7958.
Update to Jetty 12 and try again.

I don't have Windows, so I cannot tell.

There is too little information to help you.

You do not specify the Jetty configuration, etc. nor what you are doing (load test?).

Make sure your OS is configured properly, you may hit some OS resource limit.
