### ISSUE TITLE
mvn test error : jetty-util failure:could not find build-resources-12.0.5.jar

### ISSUE THREAD

**Issue by fubingting** [eclipse/jetty.project#11222]
**Jetty version(s)**
12.0.5

**Jetty Environment**

maven@3.9.2  openjdk@17.0.2

**OS type/version**
centos8 aarch64

**Description**
mvn test error : jetty-util failure:could not find build-resources-12.0.5.jar,
maven repo url :https://repo.maven.apache.org/maven2/org/eclipse/jetty/build-resources/12.0.5/build-resources-12.0.5.jar,
In which maven repository should I download this jar package?

**How to reproduce?**

**Comment by joakime** [comment]
The process would be ...

``` shell
# Get a copy of the source repository
$ git clone git@github.com:jetty/jetty.project.git
# Change to cloned directory
$ cd jetty.project

# Change to Jetty 12 branch
$ git checkout jetty-12.0.x
# (OR) Change to Jetty 12.0.5 tag
$ git checkout jetty-12.0.5

# Compile only (no tests) [recommended]
$ mvn clean install -DskipTests
# Compile and test relevant code (skipping problematic test code) [recommended only if you care about testing]
$ mvn clean install -Pci
# Compile and test everything, even the known problematic test code. [not recommended for first timers]
$ mvn clean install 
```

**Comment by fubingting** [comment]
Thank you for

**Comment by fubingting** [comment]
The build-resources-12.0.5.jar problem has been solved by git, but the following error occurred in mvn test. Could you take a look at it again?
```
2024-01-08 11:37:04.610:INFO :oejs.Server:main: Stopped oejs.Server@c3719e5{STOPPING}[12.0.5,sto=0]
2024-01-08 11:37:04.611:INFO :oejs.AbstractConnector:main: Stopped HTTP3ServerConnector@5e180aaf{h3, (h3)}{0.0.0.0:40526}
Running org.eclipse.jetty.http3.tests.ClientServerTest.testConnectTriggersSettingsFrame()
Running ClientServerTest.testConnectTriggersSettingsFrame() testConnectTriggersSettingsFrame()
2024-01-08 11:37:04.624:INFO :oejs.Server:main: jetty-12.0.5; built: 2023-12-18T14:06:32.502Z; git: 3aed62e4959bb8c01f5975fe81e078e3ff626126; jvm 17.0.2+8-86
2024-01-08 11:37:04.631:INFO :oejhs.HTTP3ServerConnector:main: HTTP/3+QUIC support is experimental and not suited for production use.
2024-01-08 11:37:04.690:INFO :oejus.SslContextFactory:main: x509=X509@16b3c905(mykey,h=[localhost],a=[],w=[]) for Server@63f40ca0[provider=null,keyStore=file:///home/ceshi/jetty.project/jetty-core/jetty-http3/jetty-http3-tests/src/test/resources/keystore.p12,trustStore=null]
2024-01-08 11:37:04.716:INFO :oejs.AbstractConnector:main: Started HTTP3ServerConnector@608cd501{h3, (h3)}{0.0.0.0:36151}
2024-01-08 11:37:04.740:INFO :oejs.Server:main: Started oejs.Server@38fb50f8{STARTING}[12.0.5,sto=0] @335439ms
2024-01-08 11:37:04.783:INFO :oejhc.HTTP3Client:main: HTTP/3+QUIC support is experimental and not suited for production use.
2024-01-08 11:37:04.785:WARN :oeji.SelectorManager:client-236: Exception while notifying connection ClientQuicConnection@103dbdc2::DatagramChannelEndPoint@14023b1d[{l=/[0:0:0:0:0:0:0:0]:52728,r=null,OPEN,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=0}]->[ClientQuicConnection@103dbdc2]
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jetty.quic.quiche.QuicheConnection
        at org.eclipse.jetty.quic.client.ClientQuicConnection.onOpen(ClientQuicConnection.java:104)
        at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:325)
        at org.eclipse.jetty.io.ClientConnector$ClientSelectorManager.connectionOpened(ClientConnector.java:569)
        at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:401)
        at org.eclipse.jetty.io.ManagedSelector$Accept.run(ManagedSelector.java:897)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
        at java.base/java.lang.Thread.run(Thread.java:833)
2024-01-08 11:37:04.785:WARN :oeji.ManagedSelector:client-236: Could not accept sun.nio.ch.DatagramChannelImpl@5100b7f9: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jetty.quic.quiche.QuicheConnection
2024-01-08 11:37:34.787:INFO :oejs.Server:main: Stopped oejs.Server@38fb50f8{STOPPING}[12.0.5,sto=0]
2024-01-08 11:37:34.788:INFO :oejs.AbstractConnector:main: Stopped HTTP3ServerConnector@608cd501{h3, (h3)}{0.0.0.0:36151}
[ERROR] Tests run: 12, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 363.8 s <<< FAILURE! -- in org.eclipse.jetty.http3.tests.ClientServerTest
[ERROR] org.eclipse.jetty.http3.tests.ClientServerTest.testSettings -- Time elapsed: 31.63 s <<< ERROR!
java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
        at org.eclipse.jetty.http3.tests.AbstractClientServerTest.newSession(AbstractClientServerTest.java:123)
        at org.eclipse.jetty.http3.tests.ClientServerTest.testSettings(ClientServerTest.java:124)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[ERROR] org.eclipse.jetty.http3.tests.ClientServerTest.testEchoRequestContentAsResponseContent(int)[1] -- Time elapsed: 30.24 s <<< ERROR!
java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
        at org.eclipse.jetty.http3.tests.AbstractClientServerTest.newSession(AbstractClientServerTest.java:123)
        at org.eclipse.jetty.http3.tests.ClientServerTest.testEchoRequestContentAsResponseContent(ClientServerTest.java:312)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by joakime** [comment]
As the log says ...

> 2024-01-08 11:37:04.783:INFO :oejhc.HTTP3Client:main: HTTP/3+QUIC support is experimental and not suited for production use.

... the entire HTTP/3 codebase is experimental, and based on a native library called Quiche.

There is unlikely an `aarch64` architecture version for that native codebase.

**Comment by fubingting** [comment]
> As the log says ...
> 
> > 2024-01-08 11:37:04.783:INFO :oejhc.HTTP3Client:main: HTTP/3+QUIC support is experimental and not suited for production use.
> 
> ... the entire HTTP/3 codebase is experimental, and based on a native library called Quiche.
> 
> There is unlikely an `aarch64` architecture version for that native codebase.

The same error is reported on the linux x86_64 platform,
Whether related test cases can be adapted
