### ISSUE TITLE
Facing timeout issue when running mutilple test ng test

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#11258]
**Jetty version(s)**
10.0.17

**Jetty Environment**

**Java version/vendor** `(use: java -version)`
OpenJDK21U

**OS type/version**
RHEL7

**Description**

```
ava.lang.Thread.State: RUNNABLE
        at java.base@21/sun.nio.ch.Net.poll(Native Method)
        at java.base@21/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:191)
        at java.base@21/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:280)
        at java.base@21/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
        at java.base@21/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base@21/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base@21/java.net.Socket$SocketInputStream.read(Socket.java:1099)
        at java.base@21/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
        at java.base@21/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
        at java.base@21/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base@21/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461)
        at java.base@21/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066)
        at app//org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at app//org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at app//org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at app//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at app//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at app//org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at app//org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at app//org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at app//org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at app//org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at app//org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at app//org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at app//org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at app//org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at app//org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
QaApacheCustomConnector.java:246)
        at app//org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
        at app//org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:675)
        at app//org.glassfish.jersey.client.JerseyInvocation$$Lambda/0x00007f5424549cc0.call(Unknown Source)
        at app//org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
        at app//org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
        at app//org.glassfish.jersey.client.JerseyInvocation$$Lambda/0x00007f542437e2e8.call(Unknown Source)
        at app//org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at app//org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at app//org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at app//org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at app//org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
        at app//org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:674)
        at app//org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:450)
        at app//org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
        at java.base@21/java.lang.invoke.LambdaForm$DMH/0x00007f54240e0400.invokeVirtual(LambdaForm$DMH)
        at java.base@21/java.lang.invoke.LambdaForm$MH/0x00007f5424368400.invoke(LambdaForm$MH)
        at java.base@21/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
        at java.base@21/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:153)
        at java.base@21/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base@21/java.lang.reflect.Method.invoke(Method.java:580)
        at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
        at app//org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
        at app//org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
        at app//org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
        at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
        at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at java.base@21/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21/java.lang.Thread.run(Thread.java:1583)


java.base/jdk.internal.misc.Unsafe.park(Native Method)
java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758)
java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1475)
org.testng.TestRunner.privateRun(TestRunner.java:746)
org.testng.TestRunner.run(TestRunner.java:617)
org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
org.testng.SuiteRunner.run(SuiteRunner.java:254)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
org.testng.TestNG.run(TestNG.java:1057)
   THREAD I/O dispatcher 118
java.base@21/sun.nio.ch.EPoll.wait(Native Method)
java.base@21/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:121)
java.base@21/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
java.base@21/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:142)
app//org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
app//org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
app//org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
java.base@21/java.lang.Thread.runWith(Thread.java:1596)
java.base@21/java.lang.Thread.run(Thread.java:1583)
```

**How to reproduce?**
This issue is happening only on jdk21, when running on jdk19 the time out is not happening, any help is appreciated what can cause this issue and any possible solution.

**Comment by joakime** [comment]
There is no `org.eclipse.jetty.` in your various stack traces.

**Comment by joakime** [comment]
I think you want to reach out to Apache HTTP to get help from them, as that appears to be what you are actually using.
