### ISSUE TITLE
AsyncMiddleManServletTest Test failure 

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1127]
The `AsyncMiddleManServletTest` fails when run with other tests with

```
Running org.eclipse.jetty.proxy.AsyncMiddleManServletTest.testClientRequestLargeContentKnownLengthGzipped()
2016-11-24 09:47:25.873:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2016-11-24 09:47:25.873:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2016-11-24 09:47:25.873:WARN:oejs.session:main: No SessionScavenger set, using defaults
2016-11-24 09:47:25.873:INFO:oejs.session:main: Scavenging every 600000ms
2016-11-24 09:47:25.874:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@735b478{/,null,AVAILABLE}
2016-11-24 09:47:25.874:INFO:oejs.AbstractConnector:main: Started ServerConnector@5611ebc6{HTTP/1.1,[http/1.1]}{0.0.0.0:34175}
2016-11-24 09:47:25.874:INFO:oejs.Server:main: Started @1732ms
2016-11-24 09:47:25.875:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2016-11-24 09:47:25.876:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2016-11-24 09:47:25.876:WARN:oejs.session:main: No SessionScavenger set, using defaults
2016-11-24 09:47:25.876:INFO:oejs.session:main: Scavenging every 660000ms
2016-11-24 09:47:25.877:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@337d0578{/,null,AVAILABLE}
2016-11-24 09:47:25.877:INFO:oejs.AbstractConnector:main: Started ServerConnector@59e84876{HTTP/1.1,[http/1.1]}{0.0.0.0:45931}
2016-11-24 09:47:25.877:INFO:oejs.Server:main: Started @1735ms
2016-11-24 09:47:25.924:WARN:oejs.HttpChannel:proxy-209: /
java.lang.IllegalStateException
	at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:845)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1314)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:385)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:265)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2016-11-24 09:47:25.929:WARN:oejh.HttpParser:proxy-221: parse exception: java.lang.IllegalStateException: too much data seeking EOF in CLOSE for HttpChannelOverHttp@739fe26f{r=1,c=false,a=IDLE,uri=null}
2016-11-24 09:47:25.932:WARN:oeji.SelectorManager:proxy-207: Exception while notifying connection HttpConnectionOverHTTP@3b6ca8ac(l:/127.0.0.1:40662 <-> r:localhost/127.0.0.1:34175,closed=false)=>HttpChannelOverHTTP@3f532b19(exchange=HttpExchange@7a51a297 req=PENDING/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@15160dbc(req=BEGIN,snd=SENDING,failure=null)[HttpGenerator@4b61fe7a{s=START}],recv=HttpReceiverOverHTTP@6dcc0fec(rsp=IDLE,failure=null)[HttpParser{s=START,0 of 0}]]<-SocketChannelEndPoint@1a7e5dd8{localhost/127.0.0.1:34175<->/127.0.0.1:40662,OPEN,fill=FI,flush=-,to=1/30000}{io=1/1,kio=1,kro=8}->HttpConnectionOverHTTP@3b6ca8ac(l:/127.0.0.1:40662 <-> r:localhost/127.0.0.1:34175,closed=false)=>HttpChannelOverHTTP@3f532b19(exchange=HttpExchange@7a51a297 req=PENDING/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@15160dbc(req=BEGIN,snd=SENDING,failure=null)[HttpGenerator@4b61fe7a{s=START}],recv=HttpReceiverOverHTTP@6dcc0fec(rsp=IDLE,failure=null)[HttpParser{s=START,0 of 0}]]
java.lang.IllegalStateException: The same org.eclipse.jetty.client.AsyncContentProvider instance cannot be used in multiple requests
	at org.eclipse.jetty.client.util.DeferredContentProvider.setListener(DeferredContentProvider.java:117)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:200)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:83)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:202)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:215)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:83)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:329)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:287)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:277)
	at org.eclipse.jetty.client.HttpDestination.succeeded(HttpDestination.java:218)
	at org.eclipse.jetty.client.AbstractConnectionPool.proceed(AbstractConnectionPool.java:136)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(AbstractConnectionPool.java:113)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(AbstractConnectionPool.java:106)
	at org.eclipse.jetty.util.Promise$Wrapper.succeeded(Promise.java:130)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:91)
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:289)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:491)
	at org.eclipse.jetty.io.ManagedSelector.access$1700(ManagedSelector.java:60)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:667)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2016-11-24 09:47:25.935:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@59e84876{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2016-11-24 09:47:25.935:INFO:oejs.session:main: Stopped scavenging
2016-11-24 09:47:25.936:WARN:oejs.HttpChannel:server-202: /
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.proxy.EchoHttpServlet.service(EchoHttpServlet.java:35)
	at org.eclipse.jetty.proxy.AsyncMiddleManServletTest$1.service(AsyncMiddleManServletTest.java:208)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:838)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:269)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2016-11-24 09:47:25.936:WARN:oejs.HttpChannel:server-202: Error Dispatch already committed
2016-11-24 09:47:25.937:INFO:oejsh.ContextHandler:main: Stopped o.e.j.s.ServletContextHandler@337d0578{/,null,UNAVAILABLE}
2016-11-24 09:47:40.938:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@5611ebc6{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2016-11-24 09:47:40.938:INFO:oejs.session:main: Stopped scavenging
2016-11-24 09:47:40.939:INFO:oejsh.ContextHandler:main: Stopped o.e.j.s.ServletContextHandler@735b478{/,null,UNAVAILABLE}
```

**Comment by gregw** [comment]
Potentially related to changes made for #1074

**Comment by gregw** [comment]
I believe calls to HttpInput.run() when no input is present can be ignored.  not 100% on this so would like to walk through with @sbordet at some stage.  But deac849 fixes this test for now

**Comment by joakime** [comment]
@sbordet have walked through this with @gregw ?  can this issue be closed?

**Comment by joakime** [comment]
Closing, as this hasn't occurred in well over a year.
