### ISSUE TITLE
Jetty 12 Handling broken host headers

### ISSUE THREAD

**Issue by klassm** [eclipse/jetty.project#11287]
**Jetty version(s)**
12.0.5

**Jetty Environment**
jetty-12, jetty-websocket-jetty-server

**Java version/vendor** `(use: java -version)`
Java 18

**OS type/version**
MacOS

**Description**
I am using jetty-websocket-jetty-server to open a WebSocket server for an endpoint. The client library opens a request. Unfortunately this request does not contain a proper Host header, but rather something like `Host:   :9092`.
This is rejected by Jetty, as the server name is not set.
In Jetty 11 it was possible to still accept this issue by adding a `HttpConfiguration.Customizer` and adding a fallback for the host header (plus an ignore for UNSAFE_HOST_HEADER). 

In Jetty 12 this is not possible anymore, with the reason being that there is a new check in `HttpConnection#HttpStreamOverHTTP1#headerComplete`, which will always throw when the server name is not set. I have to admit I have no clue why this check is there in the first place, as the violation check already happens somewhere else.

Now I know this is not standard compliant behaviour - still I treat the opinion it should be possible to somehow hook into the behaviour, so to remain compatible to Jetty 11.

Is there any way to work around this currently?

**How to reproduce?**

Send any request with a broken host header, like `Host:  :9092`

**Comment by joakime** [comment]
You example results in a Bad Authority.

```
org.eclipse.jetty.http.BadMessageException: 400: Bad HostPort
	at org.eclipse.jetty.http@12.0.6-SNAPSHOT/org.eclipse.jetty.http.HostPortHttpField.<init>(HostPortHttpField.java:41)
	at org.eclipse.jetty.http@12.0.6-SNAPSHOT/org.eclipse.jetty.http.HttpParser.parsedHeader(HttpParser.java:1068)
	at org.eclipse.jetty.http@12.0.6-SNAPSHOT/org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1268)
	at org.eclipse.jetty.http@12.0.6-SNAPSHOT/org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1543)
	at org.eclipse.jetty.server@12.0.6-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:580)
	at org.eclipse.jetty.server@12.0.6-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:404)
	at org.eclipse.jetty.io@12.0.6-SNAPSHOT/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.6-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.6-SNAPSHOT/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util@12.0.6-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util@12.0.6-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util@12.0.6-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Bad Authority
	at org.eclipse.jetty.util@12.0.6-SNAPSHOT/org.eclipse.jetty.util.HostPort.<init>(HostPort.java:165)
	at org.eclipse.jetty.util@12.0.6-SNAPSHOT/org.eclipse.jetty.util.HostPort.<init>(HostPort.java:59)
	at org.eclipse.jetty.http@12.0.6-SNAPSHOT/org.eclipse.jetty.http.HostPortHttpField.<init>(HostPortHttpField.java:37)
	... 12 more
```

Which results in a 400 Bad Message directly from the `HttpParser`, it never reaches `HttpConnection#HttpStreamOverHTTP1#headerComplete`

**Comment by joakime** [comment]
Looks like the `HttpCompliance.UNSAFE_HOST_HEADER` setting needs to be passed into HostPortHttpField and then the HostPort constructor that accepts the unsafe boolean.

**Comment by janbartel** [comment]
@joakime has this issue been fixed in a PR?

**Comment by joakime** [comment]
@janbartel no, as we needed the compliance violation listener PR to settle first.

As I merged that PR in the last 24 hours, this is now a candidate to resolve for the next release 12.0.7

**Comment by joakime** [comment]
Nothing do in our code, we support the violation setting
