### ISSUE TITLE
Flaky test ServletTest.testSimpleIdleRead()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#11327]
**Jetty version(s)**
12+

**Jetty Environment**
ee10

**Description**
See #10945.

The problem is as follows:

The last request does not send the content, so the Servlet is blocked in a read.
The idle timeout fires, and runs the demand callback, which reads the failure, which wakes up the blocked by throwing, which is then caught and handled in `ServletChannel.handleException()`, resulting in a `sendError()` that succeeds.

In the process above, however, we do not notify the underlying `HttpStream` that there was a failure.
So in case of `HttpStreamOverHTTP1`, the underlying `EndPoint` remains fill interested (because the request was waiting for content that was never sent).

When the `sendError()` completes successfully, `HttpStreamOverHTTP1` is succeeded, where it checks if it was fill interested, finding that it was, and aborting with "read pending".

**Comment by sbordet** [comment]
The test also erroneously send 11 bytes of data instead of 10, due to the extra `\n` after the 10 digits.

**Comment by joakime** [comment]
This is still failing on CI.

Most recent on - https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-14289/1/tests

```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.078 s <<< FAILURE! -- in org.eclipse.jetty.ee10.servlet.ServletTest
[ERROR] org.eclipse.jetty.ee10.servlet.ServletTest.testSimpleIdleRead -- Time elapsed: 1.016 s <<< FAILURE!
java.lang.AssertionError: 

Expected: is <200>
     but: was <500>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.ee10.servlet@12.1.6-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletTest.testSimpleIdleRead(ServletTest.java:154)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1490)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2248)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:499)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:666)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by lorban** [comment]
The latest flaky test failure was caused by a bug in the test itself, but the theory in this bug's description still needs to be confirmed or disproved.
