### ISSUE TITLE
Jetty 12 and Spring boot 3.2.2, support for http2 h2c requests

### ISSUE THREAD

**Issue by nickjosph** [eclipse/jetty.project#11376]
Hello, 

We are making use of of spring boot 3.2.2 for our service and I got to know that 3.2.2 requires Jetty version 12 to work properly. We have upgraded the code to use Jetty server 12.0.6. The Http 1.1 requests are coming through successfully. however http2 h2c requests are failing with the following error.

The jetty server dependency is as follows

```xml
<dependency>
       <groupId>org.eclipse.jetty.http2</groupId>
        <artifactId>jetty-http2-server</artifactId>
        <version>12.0.6</version>
</dependency>
```

```
Failure while notifying listener org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener@5b25d3a2
java.lang.NoSuchMethodError: 'void org.eclipse.jetty.server.HttpChannel.initialize()'
	at org.eclipse.jetty.http2.server.internal.HTTP2ServerConnection.pollHttpChannel(HTTP2ServerConnection.java:261)
	at org.eclipse.jetty.http2.server.internal.HTTP2ServerConnection.onNewStream(HTTP2ServerConnection.java:141)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onNewStream(HTTP2ServerConnectionFactory.java:96)
	at org.eclipse.jetty.http2.HTTP2Session.notifyNewStream(HTTP2Session.java:1125)
	at org.eclipse.jetty.http2.server.internal.HTTP2ServerSession.onHeaders(HTTP2ServerSession.java:120)
	at org.eclipse.jetty.http2.HTTP2Connection.onHeaders(HTTP2Connection.java:240)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyHeaders(BodyParser.java:115)
	at org.eclipse.jetty.http2.parser.HeadersBodyParser.onHeaders(HeadersBodyParser.java:272)
	at org.eclipse.jetty.http2.parser.HeadersBodyParser.onHeaders(HeadersBodyParser.java:267)
	at org.eclipse.jetty.http2.parser.HeadersBodyParser.parse(HeadersBodyParser.java:211)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:229)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:156)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:121)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:349)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:512)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:258)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.server.internal.HTTP2ServerConnection.onOpen(HTTP2ServerConnection.java:115)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:435)
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.upgrade(HttpConnection.java:1482)
	at org.eclipse.jetty.server.internal.HttpConnection.upgrade(HttpConnection.java:594)
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.headerComplete(HttpConnection.java:1308)
	at org.eclipse.jetty.server.internal.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:959)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1251)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1543)
	at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:580)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:404)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Unknown Source)
```
	
does Jetty 12 not support http2 requests over h2c?

To reproduce,

- Build a service with Spring boot 3.2.2 and Jetty 12.0.6 server, enable http requests using the following property 
server:
  http2:
    enabled: true

try requests over http2 using curl

**Comment by sbordet** [comment]
You have multiple Jetty versions in your classpath, so that you are using the `jetty-http2` dependencies from one version, but the `jetty-server` dependencies from another version of Jetty.

Double check your classpath and make sure you only have Jetty dependencies for one version.

Are you using the Jetty BOM?

**Comment by nickjosph** [comment]
@sbordet, thank you for the quick response.

I am not using a Jetty bom, I am using the Spring boot starter Jetty version 3.2.2 (which internally uses the bom) and also the Jetty http2 server 12.0.6 dependency as well. 

I have ran the dependency tree command and filtered out the jetty specific dependencies and their parents.

[INFO] +- org.springframework.boot:spring-boot-starter-jetty:jar:3.2.2:compile
[INFO] |  +- jakarta.servlet:jakarta.servlet-api:jar:6.0.0:compile
[INFO] |  +- jakarta.websocket:jakarta.websocket-api:jar:2.1.1:compile
[INFO] |  +- jakarta.websocket:jakarta.websocket-client-api:jar:2.1.1:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:10.1.18:compile
[INFO] |  +- org.eclipse.jetty.ee10:jetty-ee10-servlets:jar:12.0.5:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:12.0.5:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-io:jar:12.0.5:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:12.0.5:compile
[INFO] |  +- org.eclipse.jetty.ee10:jetty-ee10-webapp:jar:12.0.5:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-session:jar:12.0.5:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:12.0.5:compile
[INFO] |  |  \- org.eclipse.jetty.ee10:jetty-ee10-servlet:jar:12.0.5:compile
[INFO] |  |     \- org.eclipse.jetty:jetty-security:jar:12.0.5:compile
[INFO] |  +- org.eclipse.jetty.ee10.websocket:jetty-ee10-websocket-jakarta-server:jar:12.0.5:compile
[INFO] |  |  +- org.eclipse.jetty.ee10:jetty-ee10-annotations:jar:12.0.5:compile
[INFO] |  |  |  +- org.eclipse.jetty.ee10:jetty-ee10-plus:jar:12.0.5:compile
[INFO] |  |  |  |  +- jakarta.transaction:jakarta.transaction-api:jar:2.0.1:compile
[INFO] |  |  |  |  +- org.eclipse.jetty:jetty-jndi:jar:12.0.5:compile
[INFO] |  |  |  |  \- org.eclipse.jetty:jetty-plus:jar:12.0.5:compile
[INFO] |  |  |  +- org.ow2.asm:asm:jar:9.6:compile
[INFO] |  |  |  \- org.ow2.asm:asm-commons:jar:9.6:compile
[INFO] |  |  |     \- org.ow2.asm:asm-tree:jar:9.6:compile
[INFO] |  |  +- org.eclipse.jetty.ee10.websocket:jetty-ee10-websocket-jakarta-client:jar:12.0.5:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-client:jar:12.0.5:compile
[INFO] |  |  |  |  \- org.eclipse.jetty:jetty-alpn-client:jar:12.0.5:compile
[INFO] |  |  |  +- org.eclipse.jetty.ee10.websocket:jetty-ee10-websocket-jakarta-common:jar:12.0.5:compile
[INFO] |  |  |  \- org.eclipse.jetty.websocket:jetty-websocket-core-client:jar:12.0.5:compile
[INFO] |  |  \- org.eclipse.jetty.ee10.websocket:jetty-ee10-websocket-servlet:jar:12.0.5:compile
[INFO] |  |     \- org.eclipse.jetty.websocket:jetty-websocket-core-server:jar:12.0.5:compile
[INFO] |  \- org.eclipse.jetty.ee10.websocket:jetty-ee10-websocket-jetty-server:jar:12.0.5:compile
[INFO] |     +- org.eclipse.jetty.websocket:jetty-websocket-jetty-api:jar:12.0.5:compile
[INFO] |     \- org.eclipse.jetty.websocket:jetty-websocket-jetty-common:jar:12.0.5:compile
[INFO] |        \- org.eclipse.jetty.websocket:jetty-websocket-core-common:jar:12.0.5:compile
[INFO] +- org.eclipse.jetty.http2:jetty-http2-server:jar:12.0.6:compile
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:12.0.5:compile
[INFO] |  +- org.eclipse.jetty.http2:jetty-http2-common:jar:12.0.5:compile
[INFO] |  |  \- org.eclipse.jetty.http2:jetty-http2-hpack:jar:12.0.5:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.11:compile

I do not see any major version mismatches here.

**Comment by sbordet** [comment]
> I do not see any major version mismatches here.

I see almost all the dependencies on 12.0.5, apart this line:

```
 [INFO] +- org.eclipse.jetty.http2:jetty-http2-server:jar:12.0.6:compile
```

Make everything 12.0.6 using the BOM, or everything 12.0.5 and the problem will go away.

**Comment by nickjosph** [comment]
This is fixed now, thank you @sbordet for the help
