### ISSUE TITLE
ExceptionInInitializerError after update to v.12.0.5

### ISSUE THREAD

**Issue by ab-tco** [eclipse/jetty.project#11419]
**Jetty version(s)**
v. 12.0.5, v.9.4.44.v20210927

**Java version/vendor**
openjdk 17.0.8.1 2023-08-22 LTS
OpenJDK Runtime Environment Corretto-17.0.8.8.1 (build 17.0.8.1+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.8.8.1 (build 17.0.8.1+8-LTS, mixed mode, sharing)

**OS**
Windows 11

**Question**
Hi,
we have a GWT (v.2.10) project and run into an ExceptionInInitializerError (see full StackTrace below) since an Jetty update from 11.0.15 to 12.0.5. Do you have any idea why this occurs?

Some more background information:
It's occurring when the GWT Super Dev Mode is used. With that, a jetty server is started that hosts the project in a development mode. Normally, GWT's internal Jetty server is used (v. 9.4.44.v20210927) for that, but we use the "-noServer" flag to use an external server instead. The external server is a Jetty server too, coming packaged with a project dependency. Before, the version of this Jetty server was 11.0.15 and everything worked fine. But now, after an update of the project dependency, it comes with version 12.0.5 and the following error occurs at startup:

java.lang.ExceptionInInitializerError
	at org.eclipse.jetty.http2.hpack.HpackFieldPreEncoder.getEncodedField(HpackFieldPreEncoder.java:49)
	at org.eclipse.jetty.http.PreEncodedHttpField.<init>(PreEncodedHttpField.java:102)
	at org.eclipse.jetty.http.PreEncodedHttpField.<init>(PreEncodedHttpField.java:108)
	at org.eclipse.jetty.http.MimeTypes$Type.<init>(MimeTypes.java:98)
	at org.eclipse.jetty.http.MimeTypes$Type.<clinit>(MimeTypes.java:56)
	at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:175)
	at com.google.gwt.dev.codeserver.WebServer.<clinit>(WebServer.java:90)
	at com.google.gwt.dev.codeserver.SourceHandler.<clinit>(SourceHandler.java:63)
	at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:500)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:204)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:192)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:151)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:104)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:666)
	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:785)
	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:551)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:888)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:705)
	at com.google.gwt.dev.DevMode.main(DevMode.java:432)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.http.HttpFieldPreEncoder.getEncodedField(org.eclipse.jetty.http.HttpHeader, String, String)" because "org.eclipse.jetty.http.PreEncodedHttpField.__encoders[i]" is null
	at org.eclipse.jetty.http.PreEncodedHttpField.<init>(PreEncodedHttpField.java:102)
	at org.eclipse.jetty.http.PreEncodedHttpField.<init>(PreEncodedHttpField.java:108)
	at org.eclipse.jetty.http2.hpack.HpackEncoder.<clinit>(HpackEncoder.java:81)
	... 28 more

**Comment by sbordet** [comment]
You are likely missing some jar from the classpath.

Please note that some artifact have changed their name, see: https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-11-to-12.

**Comment by ab-tco** [comment]
Sorry, forgot to give a feedback here.
Thanks for your hint, the changed names were indeed missing. 
Version pinning also helped.
