### ISSUE TITLE
org.eclipse.jetty.http2.client.Client does not connect in 9.4

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1144]
org.eclipse.jetty.http2.client.Client does not connect in 9.4

```
2016-12-01 15:57:54.800:INFO::main: Logging initialized @222ms to org.eclipse.jetty.util.log.StdErrLog
Exception in thread "main" java.util.concurrent.TimeoutException
	at org.eclipse.jetty.util.FuturePromise.get(FuturePromise.java:130)
	at org.eclipse.jetty.http2.client.Client.main(Client.java:55)
```
Same test works fine in 9.3

**Comment by sbordet** [comment]
Tried with `webtide.com` and with other known HTTP/2 servers and works fine. Could be your ISP or DNS ?
