### ISSUE TITLE
Cannot invoke "org.eclipse.jetty.util.compression.CompressionPool$Entry.get()" because "this.this$0._deflaterEntry" is null

### ISSUE THREAD

**Issue by okohub** [eclipse/jetty.project#11459]
**Jetty version(s)**
12.0.6 (along with Spring Boot 3.2.3)

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
21 (eclipse-temurin:21-jre-alpine)

**OS type/version**

**Description**

Sometimes we get an error like this;

LOGGER: org.eclipse.jetty.server.Response

writeError: status=500, message=java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.util.compression.CompressionPool$Entry.get()" because "this.this$0._deflaterEntry" is null, response=ErrorResponse@48cb5ada{500,POST@1407dc79 XXXXX HTTP/1.1}

Stacktrace is here:

```java
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.util.compression.CompressionPool$Entry.get()" because "this.this$0._deflaterEntry" is null
	at o.e.j.s.h.g.GzipResponseAndCallback$GzipBufferCB.process(GzipResponseAndCallback.java:370)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:250)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:231)
	at o.e.j.server.handler.gzip.GzipResponseAndCallback.gzip(GzipResponseAndCallback.java:157)
	at o.e.j.server.handler.gzip.GzipResponseAndCallback.write(GzipResponseAndCallback.java:135)
	at o.e.j.server.handler.gzip.GzipResponseAndCallback.succeeded(GzipResponseAndCallback.java:97)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.onCompleted(ServletChannel.java:751)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:421)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:763)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:597)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:716)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:81)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at o.e.j.s.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:619)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:410)
	at o.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at j.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(Unknown Source)
	at java.lang.VirtualThread.run(Unknown Source)
	Suppressed: org.eclipse.jetty.http.BadMessageException: 400: Early EOF
		at o.e.j.s.internal.HttpConnection$RequestHandler.earlyEOF(HttpConnection.java:1049)
		at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1637)
		at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:567)
		at org.eclipse.jetty.server.internal.HttpConnection.parseAndFillForContent(HttpConnection.java:492)
		at o.e.j.s.i.HttpConnection$HttpStreamOverHTTP1.read(HttpConnection.java:1344)
		at org.eclipse.jetty.server.HttpStream$Wrapper.read(HttpStream.java:161)
		at org.eclipse.jetty.server.HttpStream$Wrapper.read(HttpStream.java:161)
		at o.e.j.s.internal.HttpChannelState$ChannelRequest.read(HttpChannelState.java:883)
		at org.eclipse.jetty.server.Request$Wrapper.read(Request.java:808)
		at org.eclipse.jetty.server.Request$Wrapper.read(Request.java:808)
		at o.e.j.server.handler.EventsHandler$EventsRequest.read(EventsHandler.java:357)
		at org.eclipse.jetty.server.Request$Wrapper.read(Request.java:808)
		at o.eclipse.jetty.ee10.servlet.AsyncContentProducer.readChunk(AsyncContentProducer.java:319)
		at o.eclipse.jetty.ee10.servlet.AsyncContentProducer.produceChunk(AsyncContentProducer.java:305)
		at o.eclipse.jetty.ee10.servlet.AsyncContentProducer.isReady(AsyncContentProducer.java:243)
		at o.e.jetty.ee10.servlet.BlockingContentProducer.nextChunk(BlockingContentProducer.java:108)
		at org.eclipse.jetty.ee10.servlet.HttpInput.read(HttpInput.java:244)
		at org.eclipse.jetty.ee10.servlet.HttpInput.read(HttpInput.java:225)
		at org.eclipse.jetty.ee10.servlet.HttpInput.read(HttpInput.java:215)
		at java.io.FilterInputStream.read(Unknown Source)
		at java.io.PushbackInputStream.read(Unknown Source)
		at o.s.w.s.m.m.a.AbstractMessageConverterMethodArgumentResolver$EmptyBodyCheckingHttpInputMessage.<init>(AbstractMessageConverterMethodArgumentResolver.java:335)
		at o.s.w.s.m.m.a.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:174)
		at o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:159)
		at o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:134)
		at o.s.w.m.s.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)
		at o.s.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:228)
		at o.s.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:182)
		at o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
		at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:920)
		at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:830)
		at o.s.w.s.mvc.m...
```

**How to reproduce?**

I haven't got a minimal example for now.

**Comment by joakime** [comment]
Are there any previous warnings in your logs that indicate something that lead up to this?

Also this appears to be a POST request processing, and during read of the request the EOF was reached before the POST body was finished being read.
What kind of POST is this?  (normal? `application/x-www-form-urlencoded`? `multipart/form-data`?)  The stacktrace was cut off too soon, and these details are not present in the small portion you copy/pasted.

**Comment by okohub** [comment]
@joakime We are using "application/json" as Content-Type. While I was looking for some other informative logs I saw that related too:

`Resolved [org.springframework.http.converter.HttpMessageNotReadableException: I/O error while reading input message]`

I will try to get full stacktrace if I can

**Comment by okohub** [comment]
@joakime I got a slightly longer stacktrace now

```java
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.util.compression.CompressionPool$Entry.get()" because "this.this$0._deflaterEntry" is null
	at o.e.j.s.h.g.GzipResponseAndCallback$GzipBufferCB.process(GzipResponseAndCallback.java:370)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:250)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:231)
	at o.e.j.server.handler.gzip.GzipResponseAndCallback.gzip(GzipResponseAndCallback.java:157)
	at o.e.j.server.handler.gzip.GzipResponseAndCallback.write(GzipResponseAndCallback.java:135)
	at o.e.j.server.handler.gzip.GzipResponseAndCallback.succeeded(GzipResponseAndCallback.java:97)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.onCompleted(ServletChannel.java:751)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:421)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:763)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:597)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:716)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:81)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at o.e.j.s.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:619)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:410)
	at o.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at j.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(Unknown Source)
	at java.lang.VirtualThread.run(Unknown Source)
	Suppressed: org.eclipse.jetty.http.BadMessageException: 400: Early EOF
		at o.e.j.s.internal.HttpConnection$RequestHandler.earlyEOF(HttpConnection.java:1049)
		at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1637)
		at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:567)
		at org.eclipse.jetty.server.internal.HttpConnection.parseAndFillForContent(HttpConnection.java:492)
		at o.e.j.s.i.HttpConnection$HttpStreamOverHTTP1.read(HttpConnection.java:1344)
		at org.eclipse.jetty.server.HttpStream$Wrapper.read(HttpStream.java:161)
		at org.eclipse.jetty.server.HttpStream$Wrapper.read(HttpStream.java:161)
		at o.e.j.s.internal.HttpChannelState$ChannelRequest.read(HttpChannelState.java:883)
		at org.eclipse.jetty.server.Request$Wrapper.read(Request.java:808)
		at org.eclipse.jetty.server.Request$Wrapper.read(Request.java:808)
		at o.e.j.server.handler.EventsHandler$EventsRequest.read(EventsHandler.java:357)
		at org.eclipse.jetty.server.Request$Wrapper.read(Request.java:808)
		at o.eclipse.jetty.ee10.servlet.AsyncContentProducer.readChunk(AsyncContentProducer.java:319)
		at o.eclipse.jetty.ee10.servlet.AsyncContentProducer.produceChunk(AsyncContentProducer.java:305)
		at o.eclipse.jetty.ee10.servlet.AsyncContentProducer.isReady(AsyncContentProducer.java:243)
		at o.e.jetty.ee10.servlet.BlockingContentProducer.nextChunk(BlockingContentProducer.java:108)
		at org.eclipse.jetty.ee10.servlet.HttpInput.read(HttpInput.java:244)
		at org.eclipse.jetty.ee10.servlet.HttpInput.read(HttpInput.java:225)
		at org.eclipse.jetty.ee10.servlet.HttpInput.read(HttpInput.java:215)
		at java.io.FilterInputStream.read(Unknown Source)
		at java.io.PushbackInputStream.read(Unknown Source)
		at o.s.w.s.m.m.a.AbstractMessageConverterMethodArgumentResolver$EmptyBodyCheckingHttpInputMessage.<init>(AbstractMessageConverterMethodArgumentResolver.java:335)
		at o.s.w.s.m.m.a.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:174)
		at o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:159)
		at o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:134)
		at o.s.w.m.s.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)
		at o.s.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:228)
		at o.s.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:182)
		at o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
		at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:920)
		at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:830)
		at o.s.w.s.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
		at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
		at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
		at o.e.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
		at o.s.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
		at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
		at o.s.s.w.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)
		at o.s.s.w.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340)
		at o.s.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82)
		at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128)
		at o.s.s.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
		at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
		at o.s.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
		at o.s.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
		at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
		at o.s.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
		at o.s.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
		at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
		at o.s.s.w.a.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
		at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
		at a.client.web.integration.user.UserUnverifiedFilter.doFilterInternal(UserUnverifiedFilter.java:29)
		at o.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
		at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
		at a.client.web.integration.user.UserLastSeenFilter.doFilterInternal(UserLastSeenFilter.java:48)
		at o.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
		at o.s.s.w.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
		at o.s.s.w.a.r.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:145)
		at o.s.s.w.a.r.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
		at o.s.s.w.ObservationFilterChainDecorator$ObservationFilter.doFilter...
```
