### ISSUE TITLE
NPE in ClasspathPattern.match()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1151]
When classes are loaded from memory, like in case of class instrumentation via bytecode manipulation, `ClasspathPattern.match()` throws:

```
java.lang.NullPointerException
        at org.eclipse.jetty.webapp.ClasspathPattern.match(ClasspathPattern.java:526)
        at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:811)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:563)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.newrelic.agent.instrumentation.weaver.Verifier.getClassStructure(Verifier.java:321)
```

**Comment by joakime** [comment]
Fixed in commit 44c84ff
