### ISSUE TITLE
The worker thread "qtp" in "jetty", although in the "TIMED_WAITING" state, takes up a lot of CPU

### ISSUE THREAD

**Issue by 1172015211** [eclipse/jetty.project#11519]
jetty version: "9.4.48"
jdk version: "11.0.14.1"
The online environment is suddenly fast and slow. Jetty is using the default configuration. Through stack analysis, it is found that many jetty working threads have high CPU, but the strange thing is that these threads are in "TIMED_WAITING". They should not occupy such a high CPU. of memory. Is this a configuration issue or a jetty version issue? The snapshot sample information is as follows:

"qtp2098830440-7244" #7244 prio=5 os_prio=0 cpu=4952.28ms elapsed=1334.23s tid=0x00007f3bfc01f000 nid=0x1d04 waiting on condition [0x00007f3b7e96b000]
    java.lang.Thread.State: TIMED_WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@11.0.14.1/Native Method)
- parking to wait for <0x00000000bccc9788> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.14.1/LockSupport.java:234)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.14.1/AbstractQueuedSynchronizer.java:2123)
at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:974)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1018)
at java.lang.Thread.run(java.base@11.0.14.1/Thread.java:829)

**Comment by 1172015211** [comment]
Preliminary guess is that the parameter time of the awaitNanos method is too short, which causes the CPU to increase due to blocking wake-up. However, I cannot confirm why the parameter time is so short. The default should be 60 seconds.

**Comment by 1172015211** [comment]
初步猜测awaitNanos方法的参数时间过短，导致一直在循环堵塞唤醒导致cpu升高，但我不能确认参数的时间为什么会很短，默认应该是60秒

**Comment by 1172015211** [comment]
![code](https://github.com/jetty/jetty.project/assets/42506866/176ba851-6f2c-4f05-aaa0-1ee961eaedba)
Preliminary guess is that the parameter time of the awaitNanos method is too short, causing the cycle to block and wake up, causing the CPU to rise. However, I cannot confirm why the parameter time is so short. The default should be 60 seconds.

**Comment by sbordet** [comment]
Jetty 9.4.x is at end of community support, see #7958.

Jetty 10 and 11 also are at end of community support, see #10485.

Please upgrade to Jetty 12 and report back whether you still have this issue.

BTW, CPU time greater than elapsed time is normal in multithreaded systems.
Do not try to see more than there is in CPU time and elapsed time, it's not an issue, and certainly not a Jetty issue.
Please do some research online to understand the meaning of these two values.

**Comment by 1172015211** [comment]
> Jetty 9.4.x is at end of community support, see #7958.
> 
> Jetty 10 and 11 also are at end of community support, see #10485.
> 
> Please upgrade to Jetty 12 and report back whether you still have this issue.
> 
> BTW, CPU time greater than elapsed time is normal in multithreaded systems. Do not try to see more than there is in CPU time and elapsed time, it's not an issue, and certainly not a Jetty issue. Please do some research online to understand the meaning of these two values.

Thank you very much for your reply. It's not just that the CPU time seems to be long, but that the system performance has been affected. Moreover, there is not only one thread that is blocked and takes a long time. After they release the CPU, the system will return to normal.

**Comment by sbordet** [comment]
Update to 12 and report back if you still have the issue.
