### ISSUE TITLE
ClosedChannelException in 9.3.15-SNAPSHOT version

### ISSUE THREAD

**Issue by sxam** [eclipse/jetty.project#1154]
Hi guys,
Opening a new issue since it's probably not related to the fixed AsynchronousCloseException from https://github.com/eclipse/jetty.project/issues/1134 thread.

When trying version 9.3.15-SNAPSHOT  on 10 machines I got the following problem on one of them (only one !)

```
2016-12-06 01:09:19,291 [asyncCallback1] WARN  http.HttpDataAccess - Got exception. request: GET https://api.facebook.com/restserver.php params: {method=mobile.zero.campaign, access_token=SOME_ACCESS_TOKEN_OBFUSCATED, dialtone_enabled=false, X-Snaptu-Cluster=lla1c11} headers: {Accept-Encoding=gzip,deflate, User-Agent=Dalvik/1.4.0 (Linux; U; Android 2.3.6; GT-S5690 Build/GINGERBREAD) Source/1 [FBAN/EMA;UNITY_PACKAGE/None;FBBV/282;FBAV/18.0.0.4.146;FBDV/GT-S5690;FBLC/ar_AR;FBOP/20], X-Forwarded-For=SOME_FORWARDED_IP, X_Fb_Internal_Fwd_For=SOME_INTERNAL_IP} timeout: 30000 userAgent: Dalvik/1.4.0 (Linux; U; Android 2.3.6; GT-S5690 Build/GINGERBREAD) Source/1 [FBAN/EMA;UNITY_PACKAGE/None;FBBV/282;FBAV/18.0.0.4.146;FBDV/GT-S5690;FBLC/ar_AR;FBOP/20]
2016-12-06 01:09:19,291 [asyncCallback1] WARN  http.HttpDataAccess - Exception details: 
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.http2.HTTP2Session$ControlEntry.succeeded(HTTP2Session.java:1212) ~[http2-common-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_60]
	at org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:256) ~[http2-common-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:332) ~[jetty-io-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140) ~[jetty-io-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:244) ~[http2-common-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:365) ~[jetty-util-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:259) ~[http2-common-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.io.WriteFlusher$PendingState.complete(WriteFlusher.java:269) ~[jetty-io-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394) ~[jetty-io-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:101) ~[jetty-io-9.3.15-SNAPSHOT.jar:9.3.15-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at com.moblica.utils.LoggingThreadFactory$1.run(LoggingThreadFactory.java:38) ~[moblicaUtils-0.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

I sent logs to @olamy ,@sbordet, @gregw . Guys could you please take a look and analyze it?
(and also tell me how to deal with such scenarios - is closing and opening a client an option?)

**Comment by joakime** [comment]
Have not been able to reproduce.

**Comment by joakime** [comment]
Unable to Replicate.  Feel free to reopen if you have more information.
