### ISSUE TITLE
Issue with Jetty 12 and creating Session.Listener.AutoDemanding instances when using JPMS

### ISSUE THREAD

**Issue by cdivilly** [eclipse/jetty.project#11557]
**Jetty version(s)**

Jetty 12.0.7

**Jetty Environment**

core

**Java version/vendor** `(use: java -version)`

java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

**OS type/version**
ProductName:            macOS
ProductVersion:         14.3.1
BuildVersion:           23D60

**Description**

When using JPMS cannot instantiate socket instance, getting the following error:

```
[main] INFO org.eclipse.jetty.server.Server - jetty-12.0.7; built: 2024-02-29T21:19:41.771Z; git: c89aca8fd34083befd79f328a3b8b6ffff04347e; jvm 21.0.1+12-LTS-29
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started oejsh.ContextHandler@4d50efb8{ROOT,/,b=null,a=AVAILABLE,h=cej.Main$@2173f6d9{STARTED}}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@670b40af{HTTP/1.1, (http/1.1)}{0.0.0.0:58173}
[main] INFO org.eclipse.jetty.server.Server - Started oejs.Server@36d4b5c{STARTING}[12.0.7,sto=0] @201ms
[qtp1967205423-25] WARN org.eclipse.jetty.server.Response - writeError: status=500, message=java.lang.RuntimeException: Unable to access method public void com.example.jetty.Main$EchoSocket.onWebSocketOpen(org.eclipse.jetty.websocket.api.Session), response=org.eclipse.jetty.server.handler.ContextResponse@472838b5
java.lang.RuntimeException: Unable to access method public void com.example.jetty.Main$EchoSocket.onWebSocketOpen(org.eclipse.jetty.websocket.api.Session)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.toMethodHandle(JettyWebSocketFrameHandlerFactory.java:156)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.createListenerMetadata(JettyWebSocketFrameHandlerFactory.java:170)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.createMetadata(JettyWebSocketFrameHandlerFactory.java:129)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.getMetadata(JettyWebSocketFrameHandlerFactory.java:119)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.newJettyFrameHandler(JettyWebSocketFrameHandlerFactory.java:140)
	at org.eclipse.jetty.websocket.server@12.0.7/org.eclipse.jetty.websocket.server.internal.ServerFrameHandlerFactory.newFrameHandler(ServerFrameHandlerFactory.java:35)
	at org.eclipse.jetty.websocket.core.server@12.0.7/org.eclipse.jetty.websocket.core.server.internal.CreatorNegotiator.negotiate(CreatorNegotiator.java:69)
	at org.eclipse.jetty.websocket.core.server@12.0.7/org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker.upgradeRequest(AbstractHandshaker.java:70)
	at org.eclipse.jetty.websocket.core.server@12.0.7/org.eclipse.jetty.websocket.core.server.internal.HandshakerSelector.upgradeRequest(HandshakerSelector.java:45)
	at org.eclipse.jetty.websocket.core.server@12.0.7/org.eclipse.jetty.websocket.core.server.WebSocketMappings.upgrade(WebSocketMappings.java:296)
	at org.eclipse.jetty.websocket.server@12.0.7/org.eclipse.jetty.websocket.server.ServerWebSocketContainer.upgrade(ServerWebSocketContainer.java:353)
	at com.example.jetty.dynamic.websocket.problem/com.example.jetty.Main$1.handle(Main.java:48)
	at org.eclipse.jetty.server@12.0.7/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.eclipse.jetty.server@12.0.7/org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server@12.0.7/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:619)
	at org.eclipse.jetty.server@12.0.7/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411)
	at org.eclipse.jetty.io@12.0.7/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.7/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.7/org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util@12.0.7/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util@12.0.7/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util@12.0.7/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalAccessException: access to public member failed: com.example.jetty.Main$EchoSocket.onWebSocketOpen[Ljava.lang.Object;@d7dfc9/invokeVirtual, from class com.example.jetty.Main$EchoSocket (module com.example.jetty.dynamic.websocket.problem)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:894)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:3987)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:3923)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:4072)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:4065)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:3451)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.toMethodHandle(JettyWebSocketFrameHandlerFactory.java:152)
	... 22 more
```
**How to reproduce?**

Below is a sample reproducer (Note this *will* work fine if the containing project does *not* have a `module-info.java`). 

```
package com.example.jetty;

import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Response;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.server.handler.ContextHandler;
import org.eclipse.jetty.util.Callback;
import org.eclipse.jetty.websocket.api.Session;
import org.eclipse.jetty.websocket.server.ServerWebSocketContainer;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.WebSocket;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.CountDownLatch;

public class Main {

    public static void main(String...args) throws Exception {
        final var server = new Server();
        final var connector = new ServerConnector(server, 1, 1);
        server.addConnector(connector);
        final var context = new ContextHandler("/");

        context.setHandler(
                new Handler.Abstract() {

                    private ServerWebSocketContainer container;

                    @Override
                    protected void doStart() throws Exception {
                        super.doStart();
                        final var contextHandler =
                                ContextHandler.getCurrentContextHandler();
                        // Alternatively, the container can be created when the
                        // ContextHandler is created.
                        container =
                                ServerWebSocketContainer.ensure(
                                        getServer(), contextHandler);
                    }

                    @Override
                    public boolean handle(
                            Request request, Response response, Callback callback) {
                        // Direct upgrade.
                        return container.upgrade(
                                (upgradeRequest, upgradeResponse, upgradeCallback) ->
                                        new EchoSocket(),
                                request,
                                response,
                                callback);
                    }
                });
        server.setHandler(context);
        server.start();

        final var latch = new CountDownLatch(1);
        final var ws =
                HttpClient.newHttpClient()
                        .newWebSocketBuilder()
                        .buildAsync(
                                URI.create(
                                        "ws://"
                                                + server.getURI().getHost()
                                                + ":"
                                                + server.getURI().getPort()
                                                + "/echo"),
                                new WebSocketClient(latch))
                        .join();
        ws.sendText("Hello!", true);
        latch.await();
    }

    private static class WebSocketClient implements WebSocket.Listener {

        private final CountDownLatch latch;

        WebSocketClient(final CountDownLatch latch) {
            this.latch = latch;
        }

        @Override
        public CompletionStage<?> onText(WebSocket webSocket, CharSequence data, boolean last) {
            System.out.println(data);
            latch.countDown();
            return WebSocket.Listener.super.onText(webSocket, data, last);
        }

        @Override
        public void onError(WebSocket webSocket, Throwable error) {
            error.printStackTrace();
        }
    }

    public static class EchoSocket implements Session.Listener.AutoDemanding {

        private Session session;

        @Override
        public void onWebSocketOpen(Session session) {
            this.session = session;
        }

        @Override
        public void onWebSocketText(String message) {
            session.sendText(message, org.eclipse.jetty.websocket.api.Callback.NOOP);
        }
    }
}
```
This is the  `module-info.java`:

```
module com.example.jetty.dynamic.websocket.problem {
    requires java.net.http;

    requires transitive org.eclipse.jetty.server;
    requires transitive org.eclipse.jetty.websocket.api;
    requires transitive org.eclipse.jetty.websocket.server;
    requires org.slf4j;

    opens com.example.jetty to org.eclipse.jetty.websocket.common;
}
```

- I tried to open the package to `org.eclipse.jetty.websocket.common`, but this doesn't appear to help.

This is the output from running the above application:

```
/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=58219:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -p /Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-core-server/12.0.7/jetty-websocket-core-server-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/jetty-util/12.0.7/jetty-util-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-jetty-api/12.0.7/jetty-websocket-jetty-api-12.0.7.jar:/Users/cdivilly/development/orahub/experiments/jetty-12-dynamic-websocket-issue/target/classes:/Users/cdivilly/.m2/repository/org/eclipse/jetty/jetty-io/12.0.7/jetty-io-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-jetty-server/12.0.7/jetty-websocket-jetty-server-12.0.7.jar:/Users/cdivilly/.m2/repository/org/slf4j/slf4j-simple/2.0.10/slf4j-simple-2.0.10.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-jetty-common/12.0.7/jetty-websocket-jetty-common-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-core-common/12.0.7/jetty-websocket-core-common-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/jetty-http/12.0.7/jetty-http-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/jetty-server/12.0.7/jetty-server-12.0.7.jar:/Users/cdivilly/.m2/repository/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar -m com.example.jetty.dynamic.websocket.problem/com.example.jetty.Main
[main] INFO org.eclipse.jetty.server.Server - jetty-12.0.7; built: 2024-02-29T21:19:41.771Z; git: c89aca8fd34083befd79f328a3b8b6ffff04347e; jvm 21.0.1+12-LTS-29
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started oejsh.ContextHandler@4d50efb8{ROOT,/,b=null,a=AVAILABLE,h=cej.Main$@2173f6d9{STARTED}}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@670b40af{HTTP/1.1, (http/1.1)}{0.0.0.0:58221}
[main] INFO org.eclipse.jetty.server.Server - Started oejs.Server@36d4b5c{STARTING}[12.0.7,sto=0] @216ms
[qtp1967205423-25] WARN org.eclipse.jetty.server.Response - writeError: status=500, message=java.lang.RuntimeException: Unable to access method public void com.example.jetty.Main$EchoSocket.onWebSocketOpen(org.eclipse.jetty.websocket.api.Session), response=org.eclipse.jetty.server.handler.ContextResponse@57d96746
java.lang.RuntimeException: Unable to access method public void com.example.jetty.Main$EchoSocket.onWebSocketOpen(org.eclipse.jetty.websocket.api.Session)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.toMethodHandle(JettyWebSocketFrameHandlerFactory.java:156)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.createListenerMetadata(JettyWebSocketFrameHandlerFactory.java:170)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.createMetadata(JettyWebSocketFrameHandlerFactory.java:129)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.getMetadata(JettyWebSocketFrameHandlerFactory.java:119)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.newJettyFrameHandler(JettyWebSocketFrameHandlerFactory.java:140)
	at org.eclipse.jetty.websocket.server@12.0.7/org.eclipse.jetty.websocket.server.internal.ServerFrameHandlerFactory.newFrameHandler(ServerFrameHandlerFactory.java:35)
	at org.eclipse.jetty.websocket.core.server@12.0.7/org.eclipse.jetty.websocket.core.server.internal.CreatorNegotiator.negotiate(CreatorNegotiator.java:69)
	at org.eclipse.jetty.websocket.core.server@12.0.7/org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker.upgradeRequest(AbstractHandshaker.java:70)
	at org.eclipse.jetty.websocket.core.server@12.0.7/org.eclipse.jetty.websocket.core.server.internal.HandshakerSelector.upgradeRequest(HandshakerSelector.java:45)
	at org.eclipse.jetty.websocket.core.server@12.0.7/org.eclipse.jetty.websocket.core.server.WebSocketMappings.upgrade(WebSocketMappings.java:296)
	at org.eclipse.jetty.websocket.server@12.0.7/org.eclipse.jetty.websocket.server.ServerWebSocketContainer.upgrade(ServerWebSocketContainer.java:353)
	at com.example.jetty.dynamic.websocket.problem/com.example.jetty.Main$1.handle(Main.java:48)
	at org.eclipse.jetty.server@12.0.7/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.eclipse.jetty.server@12.0.7/org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server@12.0.7/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:619)
	at org.eclipse.jetty.server@12.0.7/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411)
	at org.eclipse.jetty.io@12.0.7/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.7/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.7/org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util@12.0.7/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util@12.0.7/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util@12.0.7/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalAccessException: access to public member failed: com.example.jetty.Main$EchoSocket.onWebSocketOpen[Ljava.lang.Object;@5f92aaf6/invokeVirtual, from class com.example.jetty.Main$EchoSocket (module com.example.jetty.dynamic.websocket.problem)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:894)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:3987)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:3923)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:4072)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:4065)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:3451)
	at org.eclipse.jetty.websocket.common@12.0.7/org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.toMethodHandle(JettyWebSocketFrameHandlerFactory.java:152)
	... 22 more
Exception in thread "main" java.util.concurrent.CompletionException: java.net.http.WebSocketHandshakeException
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.net.http.WebSocketHandshakeException
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.resultFrom(OpeningHandshake.java:224)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 9 more
Caused by: jdk.internal.net.http.websocket.CheckFailedException: Unexpected HTTP response status code 500
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.checkFailed(OpeningHandshake.java:341)
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.handleResponse(OpeningHandshake.java:250)
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.resultFrom(OpeningHandshake.java:220)
	... 10 more

```

If you remove `module-info.java` the program runs as expected:

```
/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=58328:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Users/cdivilly/development/orahub/experiments/jetty-12-dynamic-websocket-issue/target/classes:/Users/cdivilly/.m2/repository/org/eclipse/jetty/jetty-server/12.0.7/jetty-server-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/jetty-http/12.0.7/jetty-http-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/jetty-util/12.0.7/jetty-util-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/jetty-io/12.0.7/jetty-io-12.0.7.jar:/Users/cdivilly/.m2/repository/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-jetty-api/12.0.7/jetty-websocket-jetty-api-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-jetty-server/12.0.7/jetty-websocket-jetty-server-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-core-server/12.0.7/jetty-websocket-core-server-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-core-common/12.0.7/jetty-websocket-core-common-12.0.7.jar:/Users/cdivilly/.m2/repository/org/eclipse/jetty/websocket/jetty-websocket-jetty-common/12.0.7/jetty-websocket-jetty-common-12.0.7.jar:/Users/cdivilly/.m2/repository/org/slf4j/slf4j-simple/2.0.10/slf4j-simple-2.0.10.jar com.example.jetty.Main
[main] INFO org.eclipse.jetty.server.Server - jetty-12.0.7; built: 2024-02-29T21:19:41.771Z; git: c89aca8fd34083befd79f328a3b8b6ffff04347e; jvm 21.0.1+12-LTS-29
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started oejsh.ContextHandler@71bbf57e{ROOT,/,b=null,a=AVAILABLE,h=cej.Main$@51cdd8a{STARTED}}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@11438d26{HTTP/1.1, (http/1.1)}{0.0.0.0:58332}
[main] INFO org.eclipse.jetty.server.Server - Started oejs.Server@327471b5{STARTING}[12.0.7,sto=0] @212ms
Hello!
```

This is the `pom.xml` for the example:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>jetty-12-dynamic-websocket-issue</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>Archetype - jetty-12-dynamic-websocket-issue</name>
  <url>http://maven.apache.org</url>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.eclipse.jetty.websocket</groupId>
        <artifactId>websocket-jetty-client</artifactId>
        <version>${jetty-version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-server</artifactId>
        <version>${jetty-version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.websocket</groupId>
        <artifactId>jetty-websocket-jetty-api</artifactId>
        <version>${jetty-version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.websocket</groupId>
        <artifactId>jetty-websocket-jetty-server</artifactId>
        <version>${jetty-version}</version>
        <exclusions>
          <exclusion>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-annotations</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>2.0.10</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.websocket</groupId>
      <artifactId>jetty-websocket-jetty-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.websocket</groupId>
      <artifactId>jetty-websocket-jetty-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
    </dependency>

  </dependencies>

  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <jetty-version>12.0.7</jetty-version>
  </properties>

</project>

```

**Comment by cdivilly** [comment]
[jetty-12-websocket-jpms.zip](https://github.com/jetty/jetty.project/files/14729151/jetty-12-websocket-jpms.zip)
See attached sample maven project that demonstrates the issue

**Comment by cdivilly** [comment]
If I change the `module-info.java` to:

```
open module com.example.jetty.dynamic.websocket.problem {
    requires java.net.http;

    requires transitive org.eclipse.jetty.server;
    requires transitive org.eclipse.jetty.websocket.api;
    requires transitive org.eclipse.jetty.websocket.server;
    requires org.slf4j;
}
```

It also works without issue. So I guess my `opens` clause in my original module is not targeting the correct jetty module, but I'm not sure if/where this is documented.

It also seems like this behaviour is exposing an implementation detail of how Jetty supports all the various websocket implementations that it does, trying to use reflection and MethodHandles to dispatch calls on the websocket instance. 

Given that in this case the websocket is implementing an interface contract, that should be sufficient to be able to dispatch against the instance, the reflection could be argued to be unnecessary and creates extra friction when trying to use in a JPMS scenario.

**Comment by cdivilly** [comment]
I encountered this when upgrading from 11.x and have not seen this issue with the 11.x release

**Comment by sbordet** [comment]
@cdivilly the problem is that your classes are not exported.

You need to modify your `module-info.java` like so:

```java
module com.example.jetty.dynamic.websocket.problem {
    requires java.net.http;

    requires transitive org.eclipse.jetty.server;
    requires transitive org.eclipse.jetty.websocket.api;
    requires transitive org.eclipse.jetty.websocket.server;
    requires org.slf4j;

    exports com.example.jetty; // This is the key change.
}
```

Using `opens` is not necessary, as it would provide access for deep reflection, but using `exports` is enough for Jetty to use your endpoint classes.

I'll update the documentation accordingly.

**Comment by cdivilly** [comment]
Thanks for the quick response, makes sense 👍
