### ISSUE TITLE
Socks5Proxy does not support IP addresses with IP segments above 127

### ISSUE THREAD

**Issue by MarcinKozak005** [eclipse/jetty.project#11634]
**Jetty version(s)**
Jetty 10.0.20 (also 11.0.20 and 12.0.20)

**Java version/vendor** `(use: java -version)`
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu120.04)

**OS type/version**
Ubuntu 20.04.5 LTS

**Description**
When a `HttpClient` with `Socks5Proxy` does a request to a server with IP `"x.x.x.x"` where `x` is number above 127, a `NumberFormatException` is thrown:
```log
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NumberFormatException: Value out of range. Value:"128" Radix:10
	at org.example.App.main(App.java:20)
Caused by: java.util.concurrent.ExecutionException: java.lang.NumberFormatException: Value out of range. Value:"128" Radix:10
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:113)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:96)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:832)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:372)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:357)
	at org.example.App.main(App.java:17)
Caused by: java.lang.NumberFormatException: Value out of range. Value:"128" Radix:10
	at java.base/java.lang.Byte.parseByte(Byte.java:195)
	at java.base/java.lang.Byte.parseByte(Byte.java:219)
	at org.eclipse.jetty.client.Socks5Proxy$Socks5ProxyConnection.sendConnect(Socks5Proxy.java:273)
	at org.eclipse.jetty.util.Callback$3.succeeded(Callback.java:155)
	at org.eclipse.jetty.client.Socks5$UsernamePasswordAuthenticationFactory$UsernamePasswordAuthentication.succeeded(Socks5.java:217)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:375)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**How to reproduce?**
1. Set up a Socks5 proxy server (in my case: local [Dante](https://www.inet.no/dante/) instance on port 1080)
2. Set up any Web Server on port `x` where `x > 127` (in my case `python3 -m http.server 8000` on local machine)
3. Run the following code:
```java
public class App {
    public static void main(String[] args) throws Exception {
        HttpClient httpClient = new HttpClient();
        Socks5Proxy socks5Proxy = new Socks5Proxy("127.0.0.1", 1080);
        Socks5.UsernamePasswordAuthenticationFactory usernamePasswordAuthenticationFactory =
                new Socks5.UsernamePasswordAuthenticationFactory("danteUser", "dantePass");
        socks5Proxy.putAuthenticationFactory(usernamePasswordAuthenticationFactory);
        httpClient.getProxyConfiguration().addProxy(socks5Proxy);

        try {
            httpClient.start();
            ContentResponse response = httpClient.GET("http://127.0.0.128:8000");
            System.out.println("Response status: " + response.getStatus());
        } catch (Exception e) {
            throw new RuntimeException(e);
        } finally {
            httpClient.stop();
        }
    }
}
```

**Comment by MarcinKozak005** [comment]
Hey, @joakime is this issue/pull request missing sth in order to be reviewed? 

Asking because I don't know if I have to do sth with the issue or wait patiently for the review

**Comment by sbordet** [comment]
@MarcinKozak005 it's the latter, sorry. I'll review it in the next days.
