### ISSUE TITLE
HTTP Fields with OWS (Optional WhiteSpace) in value are not properly parsed in Jetty 12

### ISSUE THREAD

**Issue by alanvanness** [eclipse/jetty.project#11659]
**Jetty version(s)**
12.0.7

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
C:\tools\jdk21\bin>java -version
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-21.0.2.13.1 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (build 21.0.2+13-LTS, mixed mode, sharing)

**OS type/version**
Windows 10 Enterprise Version 22H2

**Description**
Jetty 12's HttpParser throws an exception when parsing an HTTP response that contains multiple spaces before the Content-Length header value. This does not happen with Jetty 11, and the extra space is not in violation of the spec. The exception is: 

```
Caused by: o.e.j.h.BadMessageException: 400: Invalid Content-Length Value
	at o.e.j.h.HttpParser.convertContentLength(HttpParser.java:1138)
	at o.e.j.h.HttpParser.parsedHeader(HttpParser.java:991)
	at o.e.j.h.HttpParser.parseFields(HttpParser.java:1199)
	at o.e.j.h.HttpParser.parseNext(HttpParser.java:1545)
	... 21 common frames omitted
Caused by: j.l.NumberFormatException: null
	... 25 common frames omitted
```
**How to reproduce?**
The following JUnit tests reproduce/illustrate the problem:

```
package jetty;

import org.eclipse.jetty.http.HttpTester;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
* These two tests illustrate an issue in Jetty 12 with respect to parsing a
* response that has more than one space before the Content-Length header value
* (and after the colon).
*/
class JettyHttpParserTest {

       // This test passes in both Jetty 11 and Jetty 12
       // Note that there is only one space before the Content-Length header value in this test 
       @Test
       @DisplayName("Content-Length with no leading spaces")
       void ParseResponseWithNoLeadingSpaces() throws Exception {
              String response = """
              HTTP/1.1 200 OK
              Content-Length: 12
              Content-Type: text/plain
              Hello World!
              """;

              Assertions.assertDoesNotThrow(() -> HttpTester.parseResponse(response));
       }

       // This test passes in Jetty 11, but fails in Jetty 12
       // Note that there are two spaces in front of the Content-Length header value in this test
       @Test
       @DisplayName("Content-Length with leading spaces")
       void ParseResponseWithLeadingSpaces() throws Exception {
              String response = """
              HTTP/1.1 200 OK
              Content-Length:  12
              Content-Type: text/plain
              Hello World!
              """;

              Assertions.assertDoesNotThrow(() -> HttpTester.parseResponse(response));
       }
}

```

**Comment by joakime** [comment]
Looks like we are not ignore OWS before the `Content-Length` value properly.
PR will be submitted shortly.

**Comment by joakime** [comment]
PR #11661 opened
