### ISSUE TITLE
 Can not run Http2Server example 

### ISSUE THREAD

**Issue by rosslight** [eclipse/jetty.project#1166]
i have to  run the Http2Server example with the following command,but throw following exception,
could you tell me why?

my computer enviroment:
win7 and java version "1.8.0_102"

command:
java -Xbootclasspath/p:alpn-boot-8.1.10.v20160720.jar; -jar example.jar

exception:
```
2016-12-13 16:43:56.551:INFO::main: Logging initialized @127ms to org.eclipse.jetty.util.log.StdErrLog
Exception in thread "main" java.lang.IllegalStateException: org.eclipse.jetty.alpn.ALPN must be on JVM boot classpath
at org.eclipse.jetty.server.NegotiatingServerConnectionFactory.isAvailableInBootClassPath(NegotiatingServerConnectionFactory.java:48)
at org.eclipse.jetty.server.NegotiatingServerConnectionFactory.checkProtocolNegotiationAvailable(NegotiatingServerConnectionFactory.java:38)
at com.hippo.rest.jetty.Http2Server.main(Http2Server.java:133)
```

**Comment by sbordet** [comment]
You are specifying a relative path for the ALPN boot jar, which evidently the JVM cannot resolve.
Please specify an absolute path for the ALPN boot jar, or make sure the JVM can properly resolve it.
