### ISSUE TITLE
NPE while completing a reset HTTP/2 stream

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1167]
```
2016-12-13 09:52:45.521:DBUG:oejhs.HttpTransportOverHTTP2:qtp1364335809-30: HTTP2 Response #13 failed to flush
org.eclipse.jetty.io.EofException: reset
	at org.eclipse.jetty.http2.HTTP2Flusher$Entry.complete(HTTP2Flusher.java:317)
	at org.eclipse.jetty.http2.HTTP2Flusher$Entry.access$200(HTTP2Flusher.java:294)
	at org.eclipse.jetty.http2.HTTP2Flusher.lambda$complete$0(HTTP2Flusher.java:217)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.eclipse.jetty.http2.HTTP2Flusher.complete(HTTP2Flusher.java:217)
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:192)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.http2.HTTP2Flusher.window(HTTP2Flusher.java:67)
	at org.eclipse.jetty.http2.HTTP2Session.onWindowUpdate(HTTP2Session.java:828)
	at org.eclipse.jetty.http2.HTTP2Session.onWindowUpdate(HTTP2Session.java:464)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyWindowUpdate(BodyParser.java:199)
	at org.eclipse.jetty.http2.parser.WindowUpdateBodyParser.onWindowUpdate(WindowUpdateBodyParser.java:98)
	at org.eclipse.jetty.http2.parser.WindowUpdateBodyParser.parse(WindowUpdateBodyParser.java:64)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:182)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:110)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:222)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillableBlocking(HTTP2Connection.java:120)
	at org.eclipse.jetty.http2.HTTP2Connection.access$1000(HTTP2Connection.java:41)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:277)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:129)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2016-12-13 09:52:45.521:DBUG:oejhs.HttpTransportOverHTTP2:qtp1364335809-30: HTTP2 Response #13/1d43d93b aborted
2016-12-13 09:52:45.522:DBUG:oejh.HTTP2Flusher:qtp1364335809-30: Failing, active/queued=1/0
2016-12-13 09:52:45.522:INFO:oejhp.BodyParser:qtp1364335809-30: Failure while notifying listener HTTP2ServerSession@1d43d93b{l:/10.150.34.245:443 <-> r:/93.144.157.110:42886,queueSize=0,sendWindow=4194304,recvWindow=65535,streams=0,NOT_CLOSED}
java.lang.NullPointerException
	at org.eclipse.jetty.http2.HTTP2Stream.failed(HTTP2Stream.java:392)
	at org.eclipse.jetty.util.Callback$Nested.failed(Callback.java:131)
	at org.eclipse.jetty.http2.HTTP2Flusher$Entry.failed(HTTP2Flusher.java:330)
	at org.eclipse.jetty.http2.HTTP2Flusher.lambda$onCompleteFailure$1(HTTP2Flusher.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.eclipse.jetty.http2.HTTP2Flusher.onCompleteFailure(HTTP2Flusher.java:266)
	at org.eclipse.jetty.util.IteratingCallback.failed(IteratingCallback.java:401)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:245)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.http2.HTTP2Flusher.window(HTTP2Flusher.java:67)
	at org.eclipse.jetty.http2.HTTP2Session.onWindowUpdate(HTTP2Session.java:828)
	at org.eclipse.jetty.http2.HTTP2Session.onWindowUpdate(HTTP2Session.java:464)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyWindowUpdate(BodyParser.java:199)
	at org.eclipse.jetty.http2.parser.WindowUpdateBodyParser.onWindowUpdate(WindowUpdateBodyParser.java:98)
	at org.eclipse.jetty.http2.parser.WindowUpdateBodyParser.parse(WindowUpdateBodyParser.java:64)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:182)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:110)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:222)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillableBlocking(HTTP2Connection.java:120)
	at org.eclipse.jetty.http2.HTTP2Connection.access$1000(HTTP2Connection.java:41)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:277)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:129)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbordet** [comment]
The reset should not have caused the whole flusher to fail.

**Comment by sbordet** [comment]
Only affects 9.4.x, since the NPE is triggered by the restriction that a write on a stream must be complete before the next write, added in 9.4.x.
