### ISSUE TITLE
`HttpClientAuthenticationTest.testDigestAnyRealm(Scenario)[1] HTTP` is flaky

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#11678]
**Jetty version(s)**
12.0.x

**Description**
`org.eclipse.jetty.client.HttpClientAuthenticationTest.testDigestAnyRealm(Scenario)[1] HTTP` sometimes fails with:

```
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
	at org.eclipse.jetty.client@12.0.9-SNAPSHOT/org.eclipse.jetty.client.HttpClientAuthenticationTest.testAuthentication(HttpClientAuthenticationTest.java:195)
	at org.eclipse.jetty.client@12.0.9-SNAPSHOT/org.eclipse.jetty.client.HttpClientAuthenticationTest.testDigestAnyRealm(HttpClientAuthenticationTest.java:151)
...
```

See: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-11637/16/tests

**Comment by lorban** [comment]
Here is the captured output:

```
Running org.eclipse.jetty.client.HttpClientGZIPTest.testLargeGZIPContentDoesNotPolluteByteBufferPool([2] HTTPS)
2024-04-21 19:25:47.769:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.9-SNAPSHOT; built: 2024-04-18T15:02:22.962Z; git: 4a943c9558f354c13c1f866e11c44d1836dede82; jvm 17.0.9+9
2024-04-21 19:25:47.830:INFO :oejs.Server:ForkJoinPool-1-worker-2: Stopped oejs.Server@5508355d{STOPPING}[12.0.9-SNAPSHOT,sto=0]
2024-04-21 19:25:47.830:INFO :oejus.SslContextFactory:ForkJoinPool-1-worker-4: x509=X509@3bb1b274(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Server@b3fb88d[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_PR-11637/jetty-core/jetty-client/src/test/resources/keystore.p12,trustStore=null]
2024-04-21 19:25:47.831:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-2: Stopped ServerConnector@50254c6c{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
```
