### ISSUE TITLE
`CreationTest.testSessionCreateForwardAndInvalidate()` is flaky

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#11676]
**Jetty version(s)**
12.0.x

**Jetty Environment**
ee10

**Description**
`org.eclipse.jetty.ee10.session.CreationTest.testSessionCreateForwardAndInvalidate()` sometimes fails with:

```
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:31)
	at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:231)
	at org.eclipse.jetty.ee10.session.CreationTest.testSessionCreateForwardAndInvalidate(CreationTest.java:391)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

See: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-10431/66/tests

**Comment by lorban** [comment]
Here is the output when the test fails:

```
Running org.eclipse.jetty.ee10.session.DuplicateCookieTest.testMultipleSessionCookiesOnlyOneExists()
Running org.eclipse.jetty.ee10.session.CreationTest.testSessionCreateForwardAndInvalidate()
2024-04-21 21:17:04.847:WARN :oejes.ServletContextHandler:ForkJoinPool-1-worker-6: Empty contextPath
2024-04-21 21:17:04.848:INFO :oejs.Server:ForkJoinPool-1-worker-6: jetty-12.0.9-SNAPSHOT; built: 2024-04-18T08:43:12.381Z; git: 74b76b9a2eeb568408854eb06f5eb308972ca384; jvm 22+36
2024-04-21 21:17:04.849:WARN :oejes.ServletContextHandler:ForkJoinPool-1-worker-7: Empty contextPath
2024-04-21 21:17:04.849:INFO :oejs.Server:ForkJoinPool-1-worker-7: jetty-12.0.9-SNAPSHOT; built: 2024-04-18T08:43:12.381Z; git: 74b76b9a2eeb568408854eb06f5eb308972ca384; jvm 22+36
2024-04-21 21:17:04.854:INFO :oejs.DefaultSessionIdManager:ForkJoinPool-1-worker-6: Session workerName=w27
2024-04-21 21:17:04.854:WARN :oejs.HouseKeeper:ForkJoinPool-1-worker-6: w27 short interval of 3sec for session scavenging.
2024-04-21 21:17:04.854:INFO :oejs.DefaultSessionIdManager:ForkJoinPool-1-worker-7: Session workerName=w28
2024-04-21 21:17:04.854:INFO :oejsh.ContextHandler:ForkJoinPool-1-worker-6: Started oeje10s.ServletContextHandler@6bb4e9cc{ROOT,/,b=null,a=AVAILABLE,h=oeje10s.SessionHandler@565a47a0{STARTED}}
2024-04-21 21:17:04.854:INFO :oejsh.ContextHandler:ForkJoinPool-1-worker-7: Started oeje10s.ServletContextHandler@2af1e54d{ROOT,/,b=null,a=AVAILABLE,h=oeje10s.SessionHandler@77e2db30{STARTED}}
2024-04-21 21:17:04.855:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-6: Started oeje10s.ServletContextHandler@6bb4e9cc{ROOT,/,b=null,a=AVAILABLE,h=oeje10s.SessionHandler@565a47a0{STARTED}}
2024-04-21 21:17:04.855:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-7: Started oeje10s.ServletContextHandler@2af1e54d{ROOT,/,b=null,a=AVAILABLE,h=oeje10s.SessionHandler@77e2db30{STARTED}}
2024-04-21 21:17:04.855:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-7: Started ServerConnector@79006bfd{HTTP/1.1, (http/1.1)}{0.0.0.0:38671}
2024-04-21 21:17:04.856:INFO :oejs.Server:ForkJoinPool-1-worker-7: Started oejs.Server@3c271469{STARTING}[12.0.9-SNAPSHOT,sto=0] @2113ms
2024-04-21 21:17:04.856:INFO :oejsh.ContextHandler:ForkJoinPool-1-worker-6: Started oeje10s.ServletContextHandler@519b9171{/contextB,/contextB,b=null,a=AVAILABLE,h=oeje10s.SessionHandler@1d2de807{STARTED}}
2024-04-21 21:17:04.856:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-6: Started oeje10s.ServletContextHandler@519b9171{/contextB,/contextB,b=null,a=AVAILABLE,h=oeje10s.SessionHandler@1d2de807{STARTED}}
2024-04-21 21:17:04.856:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-6: Started ServerConnector@19cecb45{HTTP/1.1, (http/1.1)}{0.0.0.0:46617}
2024-04-21 21:17:04.857:INFO :oejs.Server:ForkJoinPool-1-worker-6: Started oejs.Server@6482bc7{STARTING}[12.0.9-SNAPSHOT,sto=0] @2114ms
2024-04-21 21:17:04.874:INFO :oejs.Server:ForkJoinPool-1-worker-6: Stopped oejs.Server@6482bc7{STOPPING}[12.0.9-SNAPSHOT,sto=0]
2024-04-21 21:17:04.875:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-6: Stopped ServerConnector@19cecb45{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
2024-04-21 21:17:04.876:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-6: Stopped oeje10s.ServletContextHandler@519b9171{/contextB,/contextB,b=null,a=AVAILABLE,h=oeje10s.SessionHandler@1d2de807{STOPPED}}
2024-04-21 21:17:04.876:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-6: Stopped oeje10s.ServletContextHandler@6bb4e9cc{ROOT,/,b=null,a=AVAILABLE,h=oeje10s.SessionHandler@565a47a0{STOPPED}}
```
