### ISSUE TITLE
Flaky test: BadAppTests

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#11734]
**Jetty version(s)**
12.0.x

**Description**

Probably flaky test: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-12.0.x/2001/tests
```
Stacktrace
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
	at org.eclipse.jetty.tests.distribution.BadAppTests.testXmlThrowOnUnavailableFalse(BadAppTests.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Standard Error
```

**Comment by joakime** [comment]
something strange about this test failure.
The heading & stacktrace point to BadAppTest.

But the "Standard Error" output shows a different test (that deals with static content and infinispan)!?

```
Running org.eclipse.jetty.tests.distribution.DemoModulesTests.testStaticContent([2] ee9)
2024-05-02 00:55:02.424:INFO :org.eclipse.jetty.tests.testers.JettyHomeTester:ForkJoinPool-1-worker-4: Executing: [/home/jenkins/agent/tools/hudson.model.JDK/jdk21/bin/java, -Djava.io.tmpdir=/home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/tests/test-distribution/test-distribution-common/target/tests/oejtd.DemoModulesTests/testStaticContent%5B2%5D%20ee9/work, -jar, /home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/tests/test-distribution/test-distribution-common/target/tests/test-homes/1714609201579/jetty-home-12.0.9-SNAPSHOT/start.jar, --add-modules=http,ee9-demos, maven.local.repo=/home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/.repository, maven.repo.uri=http://nexus-service.nexus.svc.cluster.local:8081/repository/maven-public/]
2024-05-02 00:55:02.424:INFO :org.eclipse.jetty.tests.testers.JettyHomeTester:ForkJoinPool-1-worker-4: Working Dir: /home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/tests/test-distribution/test-distribution-common/target/tests/oejtd.DemoModulesTests/testStaticContent%5B2%5D%20ee9
2024-05-02 00:55:02.533:INFO :org.eclipse.jetty.tests.testers.ProcessWrapper:process/err: 2024-05-02 00:55:02.533:INFO :oejsh.ContextHandler:main: Started oeje10w.WebAppContext@41ab013{test,/test,b=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/tests/test-distribution/test-distribution-common/target/tests/oejtd.DistributionTests/testWebsocketClientInWebapp%255B5%255D%2520http,%2520ee10,%2520true/webapps/test/,a=AVAILABLE,h=oeje10s.SessionHandler@751d3241{STARTED}}{/home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/tests/test-distribution/test-distribution-common/target/tests/oejtd.DistributionTests/testWebsocketClientInWebapp%5B5%5D%20http,%20ee10,%20true/webapps/test}
2024-05-02 00:55:02.585:INFO :org.eclipse.jetty.tests.distribution.session.infinispan:docker-java-stream-759455398: STDOUT: ################################################################################
2024-05-02 00:55:02.585:INFO :org.eclipse.jetty.tests.distribution.session.infinispan:docker-java-stream-759455398: STDOUT: # IDENTITIES_BATCH not specified                                               #
2024-05-02 00:55:02.585:INFO :org.eclipse.jetty.tests.distribution.session.infinispan:docker-java-stream-759455398: STDOUT: # Generating Identities yaml using USER and PASS env vars.                     #
2024-05-02 00:55:02.585:INFO :org.eclipse.jetty.tests.distribution.session.infinispan:docker-java-stream-759455398: STDOUT: ################################################################################
2024-05-02 00:55:02.596:INFO :org.eclipse.jetty.tests.testers.ProcessWrapper:process/err: 2024-05-02 00:55:02.596:INFO :oejes.ServletContextHandler:main: Started oeje10w.WebAppContext@41ab013{test,/test,b=file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/tests/test-distribution/test-distribution-common/target/tests/oejtd.DistributionTests/testWebsocketClientInWebapp%255B5%255D%2520http,%2520ee10,%2520true/webapps/test/,a=AVAILABLE,h=oeje10s.SessionHandler@751d3241{STARTED}}{/home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/tests/test-distribution/test-distribution-common/target/tests/oejtd.DistributionTests/testWebsocketClientInWebapp%5B5%5D%20http,%20ee10,%20true/webapps/test}
2024-05-02 00:55:02.622:INFO :org.eclipse.jetty.tests.testers.ProcessWrapper:process/err: 2024-05-02 00:55:02.622:INFO :oejs.DefaultSessionIdManager:main: Session workerName=node0
2024-05-02 00:55:02.702:INFO :org.eclipse.jetty.tests.testers.ProcessWrapper:process/err: 2024-05-02 00:55:02.697:INFO :oejs.AbstractConnector:main: Started ServerConnector@45d84a20{HTTP/1.1, (http/1.1)}{0.0.0.0:36139}
2024-05-02 00:55:02.705:INFO :org.eclipse.jetty.tests.testers.ProcessWrapper:process/err: 2024-05-02 00:55:02.705:INFO :oejs.Server:main: Started oejs.Server@17f9d882{STARTING}[12.0.9-SNAPSHOT,sto=5000] @4211ms
```

**Comment by joakime** [comment]
@olamy got any ideas on this mix of details on the test failure? (see previous comment in this issue)
