### ISSUE TITLE
NPE in JsrSession when dealing with a response missing the `Sec-WebSocket-Extensions` header

### ISSUE THREAD

**Issue by philwebb** [eclipse/jetty.project#1202]
Using the JSR WebSocket client provided in Jetty 9.4.0.v20161208 the following NPE can be thrown:

```
java.lang.NullPointerException: null
	at org.eclipse.jetty.websocket.jsr356.JsrSession.getNegotiatedExtensions(JsrSession.java:247)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.initializeNativeSession(StandardWebSocketSession.java:184)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onOpen(StandardWebSocketHandlerAdapter.java:61)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrEndpointEventDriver.onConnect(JsrEndpointEventDriver.java:140)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:233)
	at org.eclipse.jetty.websocket.jsr356.endpoints.AbstractJsrEventDriver.openSession(AbstractJsrEventDriver.java:104)
	at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:504)
	at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:433)
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:200)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:566)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:432)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.upgrade(WebSocketUpgradeRequest.java:622)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.exchangeTerminating(HttpChannelOverHTTP.java:116)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:451)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:405)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:281)
	at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:1071)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1320)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:170)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:131)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:70)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:130)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:116)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

This happens if the `ClientUpgradeResponse` does not contain a `Sec-WebSocket-Extensions` header.

I believe that commit e0d353629f00bbebb83915ab88cf54fb2593b831 may have changed the behavior of `ClientUpgradeResponse` (specifically around [these lines](https://github.com/eclipse/jetty.project/blob/b950a2e2e46395207f27990663120d365417f762/jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeResponse.java#L53-L54)) meaning that `getExtensions()` now returns `null` rather than an empty list.

**Comment by joakime** [comment]
Closing as fixed with commit bf80d82
