### ISSUE TITLE
WebSocket migration from Jetty 11 to 12

### ISSUE THREAD

**Issue by lglowania** [eclipse/jetty.project#12074]
**Jetty Version**
12
**Jetty Environment**
ee10
**Java Version**
21
**Question**
With Jetty 11 in a `jetty-home`-setup i had servlets mapped in the web.xml that extended `org.eclipse.jetty.websocket.server.JettyWebSocketServlet` and handled the WebSocket upgrade, e.g.: 

```java
public class CommandWebSocketServlet extends JettyWebSocketServlet {

    @Override
    public void configure(JettyWebSocketServletFactory factory) {

        factory.register(CommandWebSocket.class);
        factory.setMaxBinaryMessageSize(16_000_000);
        factory.setMaxTextMessageSize(16_000_000);
        factory.setIdleTimeout(Duration.ofMinutes(5));
    }
}
```

Now with Jetty 12 that `JettyWebSocketServlet`-class is gone. How can i initiate a WebSocket-mapping via the web.xml? Thank you.

**Comment by joakime** [comment]
Use `org.eclipse.jetty.ee10.websocket.server.JettyWebSocketServlet`

* https://javadoc.jetty.org/jetty-12/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServlet.html

The migration guide should help you ...

https://jetty.org/docs/jetty/12/programming-guide/migration/11-to-12.html

**Comment by lglowania** [comment]
When i just use `org.eclipse.jetty.ee10.websocket.server.JettyWebSocketServlet`, it complains on the WebSocket-request:

```
23:14:19.287 [qtp1489933928-55] WARN  o.e.j.e.s.ServletChannel:661 - /_commands/livesync
jakarta.servlet.ServletException: java.lang.IllegalStateException: WebSocketComponents has not been created
	at org.eclipse.jetty.ee10.websocket.server.JettyWebSocketServlet.init(JettyWebSocketServlet.java:178) ~[jetty-ee10-websocket-jetty-server-12.0.11.jar:12.0.11]
	at jakarta.servlet.GenericServlet.init(GenericServlet.java:178) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
	at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:107) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHolder.initServlet(ServletHolder.java:637) ~[jetty-ee10-servlet-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.ee10.servlet.ServletHolder.getServlet(ServletHolder.java:495) ~[jetty-ee10-servlet-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.ee10.servlet.ServletHolder.prepare(ServletHolder.java:717) ~[jetty-ee10-servlet-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1545) ~[jetty-ee10-servlet-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824) ~[jetty-ee10-servlet-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436) ~[jetty-ee10-servlet-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464) ~[jetty-ee10-servlet-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575) ~[jetty-security-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703) ~[jetty-ee10-servlet-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:858) ~[jetty-server-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.server.Server.handle(Server.java:181) ~[jetty-server-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648) ~[jetty-server-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403) ~[jetty-server-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322) ~[jetty-io-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99) ~[jetty-io-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979) ~[jetty-util-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209) ~[jetty-util-12.0.11.jar:12.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164) ~[jetty-util-12.0.11.jar:12.0.11]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```
 
Is something additional required during boot?

**Comment by joakime** [comment]
How are you starting your webapp?
(embedded? standalone? etc)

**Comment by lglowania** [comment]
For now i'm starting in embedded mode.

**Comment by joakime** [comment]
In embedded mode, are you using WebAppContext, or ServletContextHandler?

**Comment by lglowania** [comment]
WebAppContext

**Comment by joakime** [comment]
For `ServletContextHandler` add the following ...

https://github.com/jetty/jetty.project/blob/91a9d0ac4363cc64845c997536c611c3b7f29bd5/jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/test/java/org/eclipse/jetty/ee10/websocket/server/browser/BrowserDebugTool.java#L99-L101

For `WebAppContext` the autowiring provided by `jakarta.servlet.ServletContainerInitializer` should kick in and do the work for you.
Just make sure your container classpath has both the `jetty-ee10-websocket-jetty-server-<ver>.jar` and `jetty-ee10-annotations-<ver>.jar` (along with associated dependent jars)

For standalone, you'll want to make sure the `ee10-websocket-jetty` module is enabled.

**Comment by lglowania** [comment]
It works. Thanks a lot!
