### ISSUE TITLE
SelectorProducer.produce loop doesn't stop sometimes upon WebSocketClient.stop

### ISSUE THREAD

**Issue by umutuzgur** [eclipse/jetty.project#1211]
Hi,

We are using Jetty Version `9.3.7.v20160115`. A scenario we come across time to time is that there some live threads left after we stop the WebSocketClient. This results in reaching to 100% cpu in production. Below, there is the thread dump of the problematic thread. All the other threads belonging to the same `QueuedThreadPool` are finished.

Thanks,
Umut

```
at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:178)
	at org.eclipse.jetty.util.thread.strategy.ProduceExecuteConsume.execute(ProduceExecuteConsume.java:50)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:143)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by joakime** [comment]
This is a Windows specific NIO bug, addressed in Issue #2218
