### ISSUE TITLE
From ee9 to ee10 upgrade - jetty 12.0.7

### ISSUE THREAD

**Issue by Joellao** [eclipse/jetty.project#12140]
**Version 12.0.7**

**ee10**

**17**

**I'm trying to update from ee9 to ee10**

I updated my dependencies in the code such as faces, annotations etc. The code seems to compile just fine and haven't found any issues for now. 
The next step was to update to ee10, so used the ee10-deploy, ee10-jstl modules. 
Other modules such as logging, ext etc didn't touch. Basically the ones that were handling ee9 became ee10.

The issue with this relies when starting the application, can't even bootstrap it since it fails with
```
java.lang.TypeNotPresentException: Type jakarta.annotation.Resource not present
        at java.base/sun.reflect.annotation.TypeNotPresentExceptionProxy.generateException(TypeNotPresentExceptionProxy.java:47)
        at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:89)
        at jdk.proxy3/jdk.proxy3.$Proxy6.value(Unknown Source)
        at org.eclipse.jetty.ee10.annotations.AnnotationConfiguration.createServletContainerInitializerAnnotationHandlers(AnnotationConfiguration.java:650)
...
```

In my application pom.xml I already have the jakarta-annotation but don't think this is related to that since it's in the very first step when the annotationconfiguration fires. 
Am I doing something wrong?

**Comment by Joellao** [comment]
Can be closed, the unzip was corrupted and didn't have the annotations jar in the lib folder for ee10, it was there for ee9 tho. Sorry for this
