### ISSUE TITLE
ReadPendingException is thrown when using o.e.j.websocket.api.Session.suspend

### ISSUE THREAD

**Issue by violetagg** [eclipse/jetty.project#1218]
Hi,

When trying to use `o.e.j.websocket.api.Session.suspend`
I'm receiving the exception below (test case is available in the PR)

```
2017-01-05 14:11:27.026:INFO::main: Logging initialized @224ms to org.eclipse.jetty.util.log.StdErrLog
2017-01-05 14:11:27.365:WARN:oeji.FillInterest:qtp1681433494-21: Read pending for AC.ReadCB@e0198ea2 ...
2017-01-05 14:11:27.367:WARN:oeji.FillInterest:qtp1681433494-21: Read pending for AC.ReadCB@e0198ea2 ...
2017-01-05 14:11:27.369:WARN:oejut.QueuedThreadPool:qtp1681433494-21: 
java.nio.channels.ReadPendingException
	at org.eclipse.jetty.io.FillInterest.register(FillInterest.java:63)
	at org.eclipse.jetty.io.AbstractEndPoint.fillInterested(AbstractEndPoint.java:353)
	at org.eclipse.jetty.io.AbstractConnection.fillInterested(AbstractConnection.java:134)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.fillInterested(AbstractWebSocketConnection.java:337)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:525)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$1.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-01-05 14:11:27.370:WARN:oejut.QueuedThreadPool:qtp1681433494-21: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$1@15cde8d in qtp1681433494{STARTED,8<=13<=200,i=3,q=0}

```

This happens because `o.e.j.websocket.api.SuspendToken.resume` is invoked while we are still in the
`o.e.j.websocket.common.io.AbstractWebSocketConnection.onFillable`.

My proposal is when resuming the suspended connection to invoke `o.e.j.websocket.common.io.AbstractWebSocketConnection.fillInterested()`
only if it's not in reading/filling mode.

What do you think?

Regards,
Violeta

**Comment by joakime** [comment]
Fixed in PR #1219
