### ISSUE TITLE
Authenticated sessions throw exception on invalidate

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1222]
If a session is marked as authenticated, and then invalidated an exception is thrown during the invalidation. This is because the session is already marked as being the the process of being invalidated, and thus not valid for writing when the SessionAuthentication class's valueUnbound() method is calls and it tries to remove a session attribute.
```
java.lang.IllegalStateException: Not valid for write: id=node0ny3627fybjya1dwi56h9qztt22 created=1483759714621 accessed=1483759768466 lastaccessed=1483759746463 maxInactiveMs=300000 expiry=1483760068466
	at org.eclipse.jetty.server.session.Session.checkValidForWrite(Session.java:609)
	at org.eclipse.jetty.server.session.Session.setAttribute(Session.java:749)
	at org.eclipse.jetty.server.session.Session.removeAttribute(Session.java:779)
	at org.eclipse.jetty.security.authentication.SessionAuthentication.doLogout(SessionAuthentication.java:92)
	at org.eclipse.jetty.security.authentication.SessionAuthentication.valueUnbound(SessionAuthentication.java:128)
	at org.eclipse.jetty.server.session.Session.unbindValue(Session.java:326)
	at org.eclipse.jetty.server.session.Session.callSessionAttributeListeners(Session.java:304)
	at org.eclipse.jetty.server.session.Session.doInvalidate(Session.java:912)
	at org.eclipse.jetty.server.session.SessionHandler.invalidate(SessionHandler.java:1235)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.invalidateAll(DefaultSessionIdManager.java:480)
	at org.eclipse.jetty.server.session.Session.invalidate(Session.java:869)
```

**Comment by janbartel** [comment]
Fixed in 9.4.1
