### ISSUE TITLE
Internal error during SSL handshake

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1228]
```
java.lang.IllegalStateException: Internal error
        at sun.security.ssl.SSLEngineImpl.initHandshaker(SSLEngineImpl.java:470)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1007)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:617)
        at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:322)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:231)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by laeubi** [comment]
Can you explain what was the cause for this?

**Comment by sbordet** [comment]
Steps to reproduce:

* Client establishes connection.
* Server reads 0 bytes, as the client may have not sent bytes yet; still, the server perform the `unwrap()` call that moves the `SSLEngine` into a state that will later trigger the internal error.
* Server shuts down the output (for example, idle timeout); `SSLEngine` state is changed to closed.
* Client sends bytes.
* Server reads N bytes (where N >= 5) and tries to `unwrap()` them and this throws `IllegalStateException("Internal error")`.

The fix was to guard the call to `unwrap()`: if the server read bytes, and it is handshaking, and the `SSLEngine` is closed, it now throws a `SSLHandshakeException`, rather than performing the `unwrap()` that throws the `IllegalStateException`.

The change in exception type is enough to trigger the catch of the exception (since `SSLHandshakeException` _is-a_ `IOException`) and handle it properly.
