### ISSUE TITLE
Unable to handle IllegalStateException: ABORTED

### ISSUE THREAD

**Issue by andyfieldberg** [eclipse/jetty.project#12293]
**Jetty version(s)**

11.0.20

**Jetty Environment**

Spring Boot

**Java version/vendor** `(use: java -version)`

Kotlin, Java 21

**OS type/version**

Linux ??

**Description**
```
  error 2024.08.14 07:34:57.874 eu-fra1 applepay-0000000-w00wb - - 5ddfdda418c5d000002c2ed9467b8f 2024-36121-g665353e1d2e0c4 488 ApplePayEndpoin service 89.113.152.11 Unable to handle /v1/orders/order.com.applepay.tracking.v2/38841051-61671 java.lang.IllegalStateException: ABORTED
	at org.eclipse.jetty.server.HttpChannelState.sendError(HttpChannelState.java:911)
	at org.eclipse.jetty.server.Response.sendError(Response.java:501)
	at org.eclipse.jetty.server.Response.sendError(Response.java:468)
	at com.ecwid.applepay.app.endpoints.core.RestApi.writeResponse(RestApi.kt:75)
	at com.ecwid.applepay.app.endpoints.core.RestApi.service(RestApi.kt:36)
	at com.ecwid.applepay.app.endpoints.applepay.ApplePayEndpointsServlet.service(ApplePayEndpointsServlet.kt:40)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at com.ecwid.skeleton.feature.http.wrappers.BaseServletWrapper.service(BaseServletWrapper.kt:16)
	at com.ecwid.skeleton.feature.http.wrappers.encoding.EncodingServletWrapper.service(EncodingServletWrapper.kt:23)
	at com.ecwid.skeleton.feature.http.wrappers.httpinfo.HttpContextServletWrapper.service(HttpContextServletWrapper.kt:32)
	at com.ecwid.skeleton.feature.http.wrappers.metrics.InstrumentedServletWrapper.traceRequest(InstrumentedServletWrapper.kt:54)
	at com.ecwid.skeleton.feature.http.wrappers.metrics.InstrumentedServletWrapper.service(InstrumentedServletWrapper.kt:28)
	at com.ecwid.skeleton.feature.http.wrappers.request.RequestHeadersServletWrapper.service(RequestHeadersServletWrapper.kt:21)
	at com.ecwid.skeleton.feature.http.wrappers.exception.ExceptionHandlerWrapper.service(ExceptionHandlerWrapper.kt:34)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	   ...skip 11 items...
	at com.ecwid.skeleton.feature.http.jetty.NoTraceServer.handle(NoTraceServer.kt:26)
	   ...skip 19 items...
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**How to reproduce?**

**Comment by sbordet** [comment]
Jetty 11 is at end of community support, see #10485.

Please upgrade to Jetty 12 and report back if you still have the issue.
