### ISSUE TITLE
SelectChannelServerSslTest.testWriteBodyAfterNoBodyResponse() produces SocketException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1240]
When running org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testWriteBodyAfterNoBodyResponse() testcase (locally and jenkins), the following exception is produced.

```
2017-01-11 08:22:22.357:INFO:oejus.SslContextFactory:main: x509=X509@7683ea43(mykey,h=[],w=[]) for SslContextFactory@6a9ac8b(file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore)
2017-01-11 08:22:22.358:INFO:oejs.AbstractConnector:main: Started ServerConnector@15a41088{SSL,[ssl, http/1.1]}{0.0.0.0:36100}
2017-01-11 08:22:22.358:INFO:oejs.Server:main: Started @35611ms
java.net.SocketException: Socket is closed
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1532)
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1553)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:124)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.eclipse.jetty.server.HttpServerTestBase$4.run(HttpServerTestBase.java:1538)
```

**Comment by gregw** [comment]
Couldn't reproduce
