### ISSUE TITLE
org.eclipse.jetty.servlets.DataRateLimitedServletTest produces RejectedExecutionException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1241]
On jenkins (not locally), the org.eclipse.jetty.servlets.DataRateLimitedServletTest emits an exception.

```
2017-01-11 08:28:57.983:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 08:28:57.984:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@6b52a40{/context,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-servlets/target/tests/testStream/,AVAILABLE}
2017-01-11 08:28:57.984:INFO:oejs.AbstractConnector:main: Started LocalConnector@178ba69f{HTTP/1.1,[http/1.1]}
2017-01-11 08:28:57.984:INFO:oejs.Server:main: Started @79801ms
2017-01-11 08:28:59.331:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@178ba69f{HTTP/1.1,[http/1.1]}
2017-01-11 08:28:59.332:INFO:oejsh.ContextHandler:main: Stopped o.e.j.s.ServletContextHandler@6b52a40{/context,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-servlets/target/tests/testStream/,UNAVAILABLE}
2017-01-11 08:28:59.332:WARN:/context:pool-25-thread-4: Async Error
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@d8c5ffc rejected from java.util.concurrent.ScheduledThreadPoolExecutor@9b3da95[Shutting down, pool size = 6, active threads = 1, queued tasks = 0, completed tasks = 127]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at org.eclipse.jetty.servlets.DataRateLimitedServlet$JettyDataStream.onWritePossible(DataRateLimitedServlet.java:288)
	at org.eclipse.jetty.servlets.DataRateLimitedServlet$JettyDataStream.run(DataRateLimitedServlet.java:300)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by gregw** [comment]
could not reproduce
