### ISSUE TITLE
org.eclipse.jetty.client.HttpRequestAbortTest.testAbortOnCommitWithContent[1]() results in EofException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1242]
On jenkins (not locally) the org.eclipse.jetty.client.HttpRequestAbortTest.testAbortOnCommitWithContent\[1\]()
execution results in an EofException ...

```
2017-01-11 08:30:29.619:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 08:30:29.691:INFO:oejus.SslContextFactory:main: x509=X509@7b3c0ecb(mykey,h=[],w=[]) for SslContextFactory@11c3ce6a(file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-client/src/test/resources/keystore.jks,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-client/src/test/resources/truststore.jks)
2017-01-11 08:30:29.691:INFO:oejs.AbstractConnector:main: Started ServerConnector@5bb99d1d{SSL,[ssl, http/1.1]}{0.0.0.0:37063}
2017-01-11 08:30:29.691:INFO:oejs.Server:main: Started @60385ms
2017-01-11 08:30:29.781:WARN:oejs.HttpChannel:server-4294: /
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.client.HttpRequestAbortTest$4.handle(HttpRequestAbortTest.java:274)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by sbordet** [comment]
Fixed by 77b1617fdd925f67642e918bdd12bd4e61245942.

**Comment by gregw** [comment]
Going to revert and see if we can suppress the warning in HttpChannel

**Comment by gregw** [comment]
I reverted and the exception I am seeing is:
```
Running org.eclipse.jetty.client.HttpRequestAbortTest.testAbortOnCommitWithContent[1]()
2017-01-12 09:01:02.308:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2017-01-12 09:01:02.342:INFO:oejus.SslContextFactory:main: x509=X509@424c0bc4(mykey,h=[],w=[]) for SslContextFactory@3c679bde(file:///home/gregw/src/jetty-9.4.x/jetty-client/src/test/resources/keystore.jks,file:///home/gregw/src/jetty-9.4.x/jetty-client/src/test/resources/truststore.jks)
2017-01-12 09:01:02.639:INFO:oejs.AbstractConnector:main: Started ServerConnector@3e9b1010{SSL,[ssl, http/1.1]}{0.0.0.0:38307}
2017-01-12 09:01:02.639:INFO:oejs.Server:main: Started @1088ms
2017-01-12 09:01:02.789:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@3e9b1010{SSL,[ssl, http/1.1]}{0.0.0.0:0}
2017-01-12 09:01:02.794:WARN:oejs.HttpChannel:server-34: 
java.lang.IllegalStateException: Error already set
	at org.eclipse.jetty.server.HttpChannelState.onError(HttpChannelState.java:723)
	at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:508)
	at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:450)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:442)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.client.HttpRequestAbortTest$4.handle(HttpRequestAbortTest.java:269)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-01-12 09:01:02.799:WARN:oejs.HttpChannel:server-34: ERROR Dispatch failed: 
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.client.HttpRequestAbortTest$4.handle(HttpRequestAbortTest.java:269)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:368)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Suppressed: 
	|org.eclipse.jetty.io.EofException
	|	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:675)
	|	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$2(HttpConnection.java:660)
	|	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:517)
	|	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:686)
	|	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:742)
	|	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234)
	|	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:218)
	|	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:392)
	|	at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1122)
	|	at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:525)
	|	at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:450)
	|	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:442)
	|	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	|	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	|	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	|	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	|	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	|	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	|	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	|	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	|	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	|	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	|	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	|	at java.lang.Thread.run(Thread.java:745)
```

So more analysis needed here....

**Comment by gregw** [comment]
re-added the ERROR parts, just looking at EarlyEOF now
