### ISSUE TITLE
org.eclipse.jetty.proxy.ProxyServletFailureTest.testServerException[0]() results in ServletException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1243]
When running the test org.eclipse.jetty.proxy.ProxyServletFailureTest.testServerException\[0\]() locally and jenkins, the testcase emits a stacktrace as such ...

```
Running org.eclipse.jetty.proxy.ProxyServletFailureTest.testServerException[0]()
2017-01-11 08:34:20.689:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 08:34:20.696:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-01-11 08:34:20.696:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-01-11 08:34:20.696:INFO:oejs.session:main: Scavenging every 660000ms
2017-01-11 08:34:20.697:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@25421809{/,null,AVAILABLE}
2017-01-11 08:34:20.697:INFO:oejs.AbstractConnector:main: Started ServerConnector@714bffd5{HTTP/1.1,[http/1.1]}{0.0.0.0:40551}
2017-01-11 08:34:20.697:INFO:oejs.Server:main: Started @51378ms
2017-01-11 08:34:20.698:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 08:34:20.699:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-01-11 08:34:20.699:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-01-11 08:34:20.699:INFO:oejs.session:main: Scavenging every 600000ms
2017-01-11 08:34:20.699:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@1f5d7fd5{/,null,AVAILABLE}
2017-01-11 08:34:20.699:INFO:oejs.AbstractConnector:main: Started ServerConnector@cf08c97{HTTP/1.1,[http/1.1]}{0.0.0.0:41180}
2017-01-11 08:34:20.699:INFO:oejs.Server:main: Started @51380ms
2017-01-11 08:34:20.705:WARN:oejs.HttpChannel:server-3956: /
javax.servlet.ServletException: Expected Test Exception
	at org.eclipse.jetty.proxy.ProxyServletFailureTest$5.doGet(ProxyServletFailureTest.java:408)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:838)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by joakime** [comment]
Note: this happens on most (if not all) of the parameterized executions of org.eclipse.jetty.proxy.ProxyServletFailureTest.testServerException\[1\]()
