### ISSUE TITLE
jetty：java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by jixiang8320216** [eclipse/jetty.project#12443]
**Jetty version(s)**

![image](https://github.com/user-attachments/assets/5f1ac3c7-1f3e-43b2-af37-00c435212279)

**Jetty Environment**

**Java version/vendor** `(use: java -version)`
jdk8
**OS type/version**
x86_64 x86_64 x86_64 GNU/Linux
**Description**

When the Timeout and idletimeout parameters of the Jetty client are set to 30 minutes and a REST request is sent, the server returns a response within 10 minutes. However, the client occasionally does not respond until the timeout period expires 30 minutes, and a timeout message is reported. The response information is as follows:

**How to reproduce?**

2024-10-29 11:32:59.821+0800 ERROR [pool-124-thread-1][ROOT][com.huawei.uniep.monitor.service.common.tools.MonitorOperationHandleUtil.postForCertOperation() 148] ERROR: productmonitorservice - http request failed=> exception.id: framework.client.EXPIRED; com.huawei.bsp.remoteservice.exception.ServiceException: exception.id: framework.client.EXPIRED; java.util.concurrent.TimeoutException\n\tat com.huawei.bsp.roa.util.restclient.HttpRest.sendHttpRequest(HttpRest.java:480) com.huawei.bsp.remoteservice.exception.ServiceException: exception.id: framework.client.EXPIRED; java.util.concurrent.TimeoutException
	at com.huawei.bsp.roa.util.restclient.HttpRest.sendHttpRequest(HttpRest.java:480)
	at com.huawei.bsp.roa.util.restclient.HttpRest.synHttpAdapter(HttpRest.java:415)
	at com.huawei.bsp.roa.util.restclient.HttpRest.post(HttpRest.java:958)
	at sun.reflect.GeneratedMethodAccessor317.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.huawei.cloudsop.common.tokenhelper.util.rpc.RestAdapterProxy.invoke(RestAdapterProxy.java:78)
	at com.sun.proxy.$Proxy90.post(Unknown Source)
	at com.huawei.cloudsop.common.tokenhelper.util.rpc.RestAdapter.post(RestAdapter.java:97)
	at com.huawei.uniep.monitor.service.core.impl.ProductMonitorUtil.sendPostROARequest(ProductMonitorUtil.java:193)
	at com.huawei.uniep.monitor.service.common.tools.MonitorOperationHandleUtil.postForCertOperation(MonitorOperationHandleUtil.java:131)
	at com.huawei.uniep.monitor.service.common.tools.MonitorOperationHandleUtil.sendOperationHandle(MonitorOperationHandleUtil.java:116)
	at com.huawei.uniep.monitor.service.common.tools.MonitorOperationHandleUtil.dealOperationHandle(MonitorOperationHandleUtil.java:105)
	at com.huawei.uniep.monitor.service.common.tools.MonitorOperationHandleUtil.scriptOperationHandle(MonitorOperationHandleUtil.java:93)
	at com.huawei.uniep.monitor.service.common.tools.MonitorOperationHandleUtil.scriptSync(MonitorOperationHandleUtil.java:59)
	at com.huawei.uniep.monitor.service.common.tools.MonitorUtil.sshExecute(MonitorUtil.java:445)
	at com.huawei.uniep.monitor.service.common.tools.MonitorUtil.sshExecute(MonitorUtil.java:514)
	at com.huawei.uniep.monitor.service.core.impl.SwitchNodeService.switchNodeService(SwitchNodeService.java:103)
	at com.huawei.uniep.monitor.service.innerservice.impl.ProductMonitorInnerServiceImpl$SwitchNodeTask.run(ProductMonitorInnerServiceImpl.java:146)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.TimeoutException
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:109)
	at com.huawei.bsp.roa.util.restclient.RequestProcessor.start(RequestProcessor.java:73)
	at com.huawei.bsp.roa.util.restclient.HttpRest.startProcess(HttpRest.java:499)
	at com.huawei.bsp.roa.util.restclient.HttpRest.sendHttpRequest(HttpRest.java:464)
	... 21 more

**Comment by sbordet** [comment]
Jetty 9, as well as Jetty 10 and 11, are at end of community support, see:

* #7958 
* #10485 

Commercial support by Webtide is available for those versions.

Upgrade to Jetty 12 and report back if the problem persists.
