### ISSUE TITLE
ProxyServletFailureTest.testClientRequestDoesNotSendContentProxyIdlesTimeout() results in EofException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1245]
Execution of testcase org.eclipse.jetty.proxy.ProxyServletFailureTest.testClientRequestDoesNotSendContentProxyIdlesTimeout() results in an EofException locally and jenkins.

```
2017-01-11 08:34:31.989:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 08:34:31.990:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-01-11 08:34:31.990:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-01-11 08:34:31.990:INFO:oejs.session:main: Scavenging every 660000ms
2017-01-11 08:34:31.991:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@b2da3a5{/,null,AVAILABLE}
2017-01-11 08:34:31.991:INFO:oejs.AbstractConnector:main: Started ServerConnector@6dbb3d7d{HTTP/1.1,[http/1.1]}{0.0.0.0:41485}
2017-01-11 08:34:31.991:INFO:oejs.Server:main: Started @62672ms
2017-01-11 08:34:31.993:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 08:34:31.993:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-01-11 08:34:31.993:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-01-11 08:34:31.993:INFO:oejs.session:main: Scavenging every 600000ms
2017-01-11 08:34:31.993:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@6aaa678d{/,null,AVAILABLE}
[GC (Allocation Failure) [PSYoungGen: 331392K->8105K(337920K)] 479340K->156162K(1037312K), 0.0135424 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
2017-01-11 08:34:32.035:INFO:oejs.AbstractConnector:main: Started ServerConnector@25dcf1b6{HTTP/1.1,[http/1.1]}{0.0.0.0:45514}
2017-01-11 08:34:32.036:INFO:oejs.Server:main: Started @62717ms
2017-01-11 08:34:34.171:WARN:oejs.HttpChannel:server-4453: /
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.proxy.EchoHttpServlet.service(EchoHttpServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:838)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:229)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1403)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:350)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by sbordet** [comment]
Cannot reproduce.
