### ISSUE TITLE
ProxyServletFailureTest.testClientRequestStallsContentProxyIdlesTimeout results in EofException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1246]
Running the testcase org.eclipse.jetty.proxy.ProxyServletFailureTest.testClientRequestStallsContentProxyIdlesTimeout[1]()
 results in an EofException locally and on jenkins.

This could be related to Issue #1245

```
2017-01-11 08:34:40.513:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 08:34:40.513:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-01-11 08:34:40.513:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-01-11 08:34:40.513:INFO:oejs.session:main: Scavenging every 600000ms
2017-01-11 08:34:40.514:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@2dde0a34{/,null,AVAILABLE}
2017-01-11 08:34:40.514:INFO:oejs.AbstractConnector:main: Started ServerConnector@61836cd9{HTTP/1.1,[http/1.1]}{0.0.0.0:40847}
2017-01-11 08:34:40.514:INFO:oejs.Server:main: Started @71195ms
2017-01-11 08:34:40.515:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 08:34:40.515:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-01-11 08:34:40.515:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-01-11 08:34:40.516:INFO:oejs.session:main: Scavenging every 600000ms
2017-01-11 08:34:40.516:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@42cfd794{/,null,AVAILABLE}
2017-01-11 08:34:40.516:INFO:oejs.AbstractConnector:main: Started ServerConnector@43778371{HTTP/1.1,[http/1.1]}{0.0.0.0:42988}
2017-01-11 08:34:40.516:INFO:oejs.Server:main: Started @71197ms
2017-01-11 08:34:42.524:WARN:oejs.HttpChannel:server-4720: /
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.proxy.EchoHttpServlet.service(EchoHttpServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:838)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbordet** [comment]
Fixed by #1242.
