### ISSUE TITLE
Exception when a Content-Length is set on a 304 response

### ISSUE THREAD

**Issue by drivron** [eclipse/jetty.project#12481]
**Jetty version(s)**
12

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.12" 2024-07-16

**OS type/version**
Ubuntu 24.04

**Description**
When a Content-Length is set on a 304 response, the following exception occurs :
```
java.io.IOException: written 0 < 454 content-length
        at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1271)
        at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:768)
        at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
        at org.eclipse.jetty.ee8.nested.HttpChannel.send(HttpChannel.java:837)
        at org.eclipse.jetty.ee8.nested.HttpChannel.sendResponse(HttpChannel.java:822)
        at org.eclipse.jetty.ee8.nested.HttpChannel.write(HttpChannel.java:891)
        at org.eclipse.jetty.ee8.nested.HttpOutput.channelWrite(HttpOutput.java:286)
        at org.eclipse.jetty.ee8.nested.HttpOutput.complete(HttpOutput.java:466)
        at org.eclipse.jetty.ee8.nested.Response.completeOutput(Response.java:852)
        at org.eclipse.jetty.ee8.nested.HttpChannel.handle(HttpChannel.java:553)
        at org.eclipse.jetty.ee8.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2376)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
        at org.eclipse.jetty.server.Server.handle(Server.java:182)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:414)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
RFC7230 allows a Content-Length on 304 responses, see #4208.
The pull request that introduced this control: #10948.

**Comment by sbordet** [comment]
See https://www.rfc-editor.org/rfc/rfc9110#section-8.6.

**Comment by joakime** [comment]
@sbordet the error says that the `Content-Length: 454` was set on the status code 304 response.

RFC9110 says ...

```
   A server MAY send a Content-Length header field in a 304 (Not
   Modified) response to a conditional GET request (Section 15.4.5); a
   server MUST NOT send Content-Length in such a response unless its
   field value equals the decimal number of octets that would have been
   sent in the content of a 200 (OK) response to the same request.
```

My interpretation is that if that same request, without the use of `Last-Modified` request header, would result in a 200 status with `Content-Length: 454`, then that response is 100% valid, without sending that content.

**Comment by sbordet** [comment]
@joakime I don't understand your comment.
We cannot send a 200 response with `Content-Length: 454` and then _not_ sending the content like your last paragraph says.

The OP is right that we should allow for the `Content-Length` header to be set by the application for 304 responses.

**Comment by gregw** [comment]
Our HttpGenerator explicitly allows for the content-length in a 304 response, but our write length sanity check does not.

**Comment by gregw** [comment]
I also note that we should be sending content headers with our own 304 responses: https://www.rfc-editor.org/rfc/rfc9110#status.304
