### ISSUE TITLE
HttpClientStreamTest.testDownloadWithCloseBeforeContent[transport: HTTPS]() results in ClosedChannelException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1251]
Running org.eclipse.jetty.http.client.HttpClientStreamTest.testDownloadWithCloseBeforeContent\[transport: HTTPS\]()
 (jenkins only, doesn't happen locally) results in a ClosedChannelException.

```
Running org.eclipse.jetty.http.client.HttpClientStreamTest.testDownloadWithCloseBeforeContent[transport: HTTPS]()
2017-01-11 09:02:55.905:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 09:02:55.909:INFO:oejus.SslContextFactory:main: x509=X509@b273a59(mykey,h=[],w=[]) for SslContextFactory@4e7095ac(file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/keystore.jks,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/truststore.jks)
2017-01-11 09:02:55.910:INFO:oejs.AbstractConnector:main: Started ServerConnector@251ebf23{SSL,[ssl, http/1.1]}{0.0.0.0:37026}
2017-01-11 09:02:55.910:INFO:oejs.Server:main: Started @77939ms
2017-01-11 09:02:55.952:WARN:oejs.HttpChannel:server-4494: /
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427)
	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:488)
	at org.eclipse.jetty.io.ssl.SslConnection.onClose(SslConnection.java:224)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:310)
	at org.eclipse.jetty.io.ManagedSelector.lambda$destroyEndPoint$0(ManagedSelector.java:505)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbordet** [comment]
Cannot reproduce.
