### ISSUE TITLE
HttpClientStreamTest.testInputStreamContentProviderThrowingWhileReading[transport: HTTPS]() results in Early EOF

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1252]
Running org.eclipse.jetty.http.client.HttpClientStreamTest.testInputStreamContentProviderThrowingWhileReading\[transport: HTTPS\]()
 (locally and jenkins) results in an Early Eof Exception

```
Running org.eclipse.jetty.http.client.HttpClientStreamTest.testInputStreamContentProviderThrowingWhileReading[transport: HTTPS]()
2017-01-11 09:03:00.078:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 09:03:00.080:INFO:oejus.SslContextFactory:main: x509=X509@4beddc56(mykey,h=[],w=[]) for SslContextFactory@79b663b3(file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/keystore.jks,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/truststore.jks)
2017-01-11 09:03:00.080:INFO:oejs.AbstractConnector:main: Started ServerConnector@1b812421{SSL,[ssl, http/1.1]}{0.0.0.0:37497}
2017-01-11 09:03:00.080:INFO:oejs.Server:main: Started @82110ms
2017-01-11 09:03:00.115:WARN:oejs.HttpChannel:server-4825: /
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.http.client.HttpClientStreamTest$12.handle(HttpClientStreamTest.java:480)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-01-11 09:03:00.115:WARN:oejs.HttpChannel:server-4825: /
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.http.client.HttpClientStreamTest$12.handle(HttpClientStreamTest.java:480)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:368)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-01-11 09:03:00.116:WARN:oejs.HttpChannel:server-4825: 
java.lang.IllegalStateException: Error already set
	at org.eclipse.jetty.server.HttpChannelState.onError(HttpChannelState.java:723)
	at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:508)
	at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:450)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:442)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.http.client.HttpClientStreamTest$12.handle(HttpClientStreamTest.java:480)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-01-11 09:03:00.116:WARN:oejs.HttpChannel:server-4825: ERROR Dispatch failed: 
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.http.client.HttpClientStreamTest$12.handle(HttpClientStreamTest.java:480)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:368)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Suppressed: 
	|java.nio.channels.ClosedChannelException
	|	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:507)
	|	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onIncompleteFlush(SslConnection.java:495)
	|	at org.eclipse.jetty.io.AbstractEndPoint$2.onIncompleteFlush(AbstractEndPoint.java:54)
	|	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:331)
	|	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
	|	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:736)
	|	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	|	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	|	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:518)
	|	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:686)
	|	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:742)
	|	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234)
	|	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:218)
	|	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:392)
	|	at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1122)
	|	at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:525)
	|	at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:450)
	|	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:442)
	|	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	|	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	|	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	|	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
	|	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
	|	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	|	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	|	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	|	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	|	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	|	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	|	at java.lang.Thread.run(Thread.java:745)
```

**Comment by joakime** [comment]
Same exception seen with org.eclipse.jetty.http.client.HttpClientStreamTest.testInputStreamContentProviderThrowingWhileReading\[transport: H2\]()

**Comment by joakime** [comment]
Similar exception seen on org.eclipse.jetty.http.client.HttpClientContinueTest.test_Expect100Continue_WithContent_WithResponseFailure_During100Continue\[transport: HTTP\]()

Not sure if this is actually the same exception or not.

```
Running org.eclipse.jetty.http.client.HttpClientContinueTest.test_Expect100Continue_WithInitialAndConcurrentDeferredContent_Respond100Continue[transport: HTTP]()
2017-01-11 09:07:37.534:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 09:07:37.534:INFO:oejs.AbstractConnector:main: Started ServerConnector@753b6846{HTTP/1.1,[http/1.1]}{0.0.0.0:35017}
2017-01-11 09:07:37.534:INFO:oejs.Server:main: Started @359564ms
2017-01-11 09:07:37.535:INFO:oejus.SslContextFactory:main: x509=X509@28b36817(mykey,h=[],w=[]) for SslContextFactory@6645c1f(file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/keystore.jks,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/truststore.jks)
2017-01-11 09:07:37.561:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@753b6846{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
Running org.eclipse.jetty.http.client.HttpClientContinueTest.test_Expect100Continue_WithContent_WithResponseFailure_During100Continue[transport: HTTP]()
2017-01-11 09:07:37.562:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 09:07:37.564:INFO:oejs.AbstractConnector:main: Started ServerConnector@b768e4d{HTTP/1.1,[http/1.1]}{0.0.0.0:38950}
2017-01-11 09:07:37.564:INFO:oejs.Server:main: Started @359593ms
2017-01-11 09:07:37.564:INFO:oejus.SslContextFactory:main: x509=X509@301608d(mykey,h=[],w=[]) for SslContextFactory@3c3a8246(file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/keystore.jks,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/truststore.jks)
2017-01-11 09:07:37.577:WARN:oejs.HttpChannel:server-9999: /
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.http.client.HttpClientContinueTest$14.handle(HttpClientContinueTest.java:397)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-01-11 09:07:37.578:WARN:oejs.HttpChannel:server-9999: /
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.http.client.HttpClientContinueTest$14.handle(HttpClientContinueTest.java:397)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:368)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-01-11 09:07:37.578:WARN:oejs.HttpChannel:server-9999: 
java.lang.IllegalStateException: Error already set
	at org.eclipse.jetty.server.HttpChannelState.onError(HttpChannelState.java:723)
	at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:508)
	at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:450)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:442)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1103)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1092)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at org.eclipse.jetty.util.IO.copy(IO.java:170)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.http.client.HttpClientContinueTest$14.handle(HttpClientContinueTest.java:397)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```
