### ISSUE TITLE
HttpClientStreamTest.testDownloadWithCloseBeforeContent[transport: H2C]() results in Broken Pipe

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1253]
When running org.eclipse.jetty.http.client.HttpClientStreamTest.testDownloadWithCloseBeforeContent\[transport: H2C\]()
 (seen on jenkins, not locally)

```
Running org.eclipse.jetty.http.client.HttpClientStreamTest.testDownloadWithCloseBeforeContent[transport: H2C]()
2017-01-11 09:03:06.020:INFO:oejs.Server:main: jetty-9.4.1-SNAPSHOT
2017-01-11 09:03:06.021:INFO:oejs.AbstractConnector:main: Started ServerConnector@14bae047{h2c,[h2c]}{0.0.0.0:36956}
2017-01-11 09:03:06.021:INFO:oejs.Server:main: Started @88050ms
2017-01-11 09:03:06.021:INFO:oejus.SslContextFactory:main: x509=X509@41477a6d(mykey,h=[],w=[]) for SslContextFactory@2bc12da(file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/keystore.jks,file:///opt/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/tests/test-http-client-transport/src/test/resources/truststore.jks)
2017-01-11 09:03:06.034:WARN:oejs.HttpChannel:server-5073: /
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:198)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.http2.HTTP2Session.frame(HTTP2Session.java:676)
	at org.eclipse.jetty.http2.HTTP2Session.data(HTTP2Session.java:663)
	at org.eclipse.jetty.http2.HTTP2Stream.data(HTTP2Stream.java:105)
	at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:197)
	at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:129)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:691)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:742)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:218)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:530)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.eclipse.jetty.http.client.HttpClientStreamTest$14.handle(HttpClientStreamTest.java:526)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.http2.HTTP2Connection.onOpen(HTTP2Connection.java:99)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onOpen(HTTP2ServerConnection.java:132)
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:289)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:491)
	at org.eclipse.jetty.io.ManagedSelector.access$1700(ManagedSelector.java:60)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:667)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:272)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:198)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.http2.HTTP2Session.frame(HTTP2Session.java:676)
	at org.eclipse.jetty.http2.HTTP2Session.data(HTTP2Session.java:663)
	at org.eclipse.jetty.http2.HTTP2Stream.data(HTTP2Stream.java:105)
	at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:197)
	at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:129)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:691)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:742)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:218)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:530)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.eclipse.jetty.http.client.HttpClientStreamTest$14.handle(HttpClientStreamTest.java:526)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produce(ExecuteProduceConsume.java:97)
	at org.eclipse.jetty.http2.HTTP2Connection.onOpen(HTTP2Connection.java:99)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onOpen(HTTP2ServerConnection.java:132)
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:289)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:491)
	at org.eclipse.jetty.io.ManagedSelector.access$1700(ManagedSelector.java:60)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:667)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by joakime** [comment]
Same exception seen with org.eclipse.jetty.http.client.HttpClientStreamTest.testDownloadWithCloseBeforeContent\[transport: H2\]()

**Comment by sbordet** [comment]
Cannot reproduce.
