### ISSUE TITLE
Change of behaviour with HttpServletResponse.sendError(0) in EE10

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#12609]
**Jetty version(s)**
12.0.x

**Jetty Environment**
ee10

**Description**
I noticed that `resp.sendError(0)` has a change of behaviour in EE10 compared to EE8 and Jetty 9.4

Previously Jetty would throw IAE for status 0.
Now this will send back a 200 response with no body.

```
java.lang.IllegalArgumentException
        at org.eclipse.jetty.ee8.nested.Response.setStatus(Response.java:666)
        at org.eclipse.jetty.ee8.nested.HttpChannelState.sendError(HttpChannelState.java:782)
        at org.eclipse.jetty.ee8.nested.Response.sendError(Response.java:449)
        at org.eclipse.jetty.ee8.nested.Response.sendError(Response.java:422)
        at org.example.DemoServlet.service(DemoServlet.java:16)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.eclipse.jetty.ee8.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1146)
        at org.eclipse.jetty.ee8.servlet.ServletHolder.handle(ServletHolder.java:640)
```

**Comment by gregw** [comment]
We should probably validate that the status is 100-599 or one of the known exceptional codes (-1 for abort).

**Comment by janbartel** [comment]
@lachlan-roberts looks like this change was deliberate:  see #9955

**Comment by lachlan-roberts** [comment]
> We should probably validate that the status is 100-599 or one of the known exceptional codes (-1 for abort).

Maybe we set upper limit at 999, because rfc9110 says: "Implementations often use three-digit integer values outside of that range (i.e., 600..999) for internal communication of non-HTTP status".

> looks like this change was deliberate: see https://github.com/jetty/jetty.project/issues/9955

This looks to be only for `getStatus` if the code hasn't been explicitly set.
