### ISSUE TITLE
ee9 / UnsupportedOperationException: Read Only

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#12603]
**Jetty version(s)**
12.0.x HEAD 

**Jetty Environment**
ee9 (but might exist in others too)

**Java version/vendor** `(use: java -version)`
Adoptium 21

**OS type/version**
Linux

**Description**
An exception seen during build ...

```
2024-12-03 07:01:38.656:WARN :oejen.HttpChannel:qtp1727361096-31: /context/resourceServlet/content.txt
java.lang.UnsupportedOperationException: Read Only
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.ResponseHttpFields$1.remove(ResponseHttpFields.java:153)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.Response.resetContent(Response.java:1249)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:532)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2873)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Suppressed: 
	|java.lang.UnsupportedOperationException: Read Only
	|	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.ResponseHttpFields$1.remove(ResponseHttpFields.java:153)
	|	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.Response.resetContent(Response.java:1249)
	|	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:566)
	|	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2873)
	|	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	|	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	|	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.Server.handle(Server.java:182)
	|	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	|	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	|	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	|	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	|	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	|	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	|	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	|	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	|	at java.base/java.lang.Thread.run(Thread.java:1570)
```

Edit: gregw - confirmed it is in 12.0.x

**Comment by gregw** [comment]
There appears to be a suppressed exception loop which is not logged:
```
java.lang.UnsupportedOperationException: Read Only
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.ResponseHttpFields$1.remove(ResponseHttpFields.java:153)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.Response.resetContent(Response.java:1249)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:532)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2873)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1570)
java.lang.UnsupportedOperationException: Read Only
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.ResponseHttpFields$1.remove(ResponseHttpFields.java:153)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.Response.resetContent(Response.java:1249)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:532)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2873)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1570)
java.lang.UnsupportedOperationException: Read Only
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.ResponseHttpFields$1.remove(ResponseHttpFields.java:153)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.Response.resetContent(Response.java:1249)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:532)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2873)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1570)
java.lang.UnsupportedOperationException: Read Only
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.ResponseHttpFields$1.remove(ResponseHttpFields.java:153)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.Response.resetContent(Response.java:1249)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:532)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2873)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1570)
java.lang.UnsupportedOperationException: Read Only
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.ResponseHttpFields$1.remove(ResponseHttpFields.java:153)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.Response.resetContent(Response.java:1249)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:532)
	at org.eclipse.jetty.ee9.nested@12.0.15-SNAPSHOT/org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2873)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server@12.0.15-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.15-SNAPSHOT/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1570)
        etc.
```

**Comment by joakime** [comment]
It showed up as a WARN level logging to me.

**Comment by janbartel** [comment]
I have not been able to reproduce in `ee10`, so looks like it is confined to `ee8/9`.

**Comment by gregw** [comment]
> It showed up as a WARN level logging to me.

Yes I see that, but behind that there is a nasty exception loop as well.
