### ISSUE TITLE
"java.io.IOException: Resource temporarily unavailable" thrown when using unixsocket.

### ISSUE THREAD

**Issue by mobstef** [eclipse/jetty.project#1263]
```
2017-01-14 08:58:14,624 [qtp447212746-20] WARN  org.eclipse.jetty.server.HttpChannel (HttpChannel.java:487) - /static/image/logo.jpg
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:733)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:518)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:672)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:728)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:771)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:870)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:747)
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:725)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:296)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:456)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:838)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at com.bemsoft.jetty.servlet.FilterBase.doFilter(FilterBase.java:32)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Resource temporarily unavailable
	at jnr.enxio.channels.NativeSocketChannel.write(NativeSocketChannel.java:93)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:270)
	... 52 more
```

What I understand from this exception is that the buffer, which is set in non blocking mode is filled, but the Exception is not handled properly (closes the connection). On the other hand, the non blocking mode is always forced by:
`serverChannel.configureBlocking(getAcceptors()>0);`
because
`getAcceptors()` will always return 0.

**Comment by sbordet** [comment]
The OP refers to Jetty 9.4.x and `UnixSocketConnector`.

**Comment by sxyzy1016** [comment]
Is there any update about this? I run into this with Jetty9.4.6 & GeoServer 2.11.1 recently.

**Comment by joakime** [comment]
@gregw I cannot find the other issue regarding this.

**Comment by sbordet** [comment]
Needs investigation.
