### ISSUE TITLE
`TLSHandshakeFailureTest.testTLSWrapAbruptSSLEngineClose` is flaky

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#12640]
**Jetty version(s)**
12.1.x

**Description**
`org.eclipse.jetty.test.client.transport.TLSHandshakeFailureTest.testTLSWrapAbruptSSLEngineClose(Transport)[1] HTTPS failed` sometimes fails with:

```
Assertion condition defined as a Lambda expression in org.eclipse.jetty.test.client.transport.AbstractTest Leaks: TrackedBuffer@5636ae5d of 16709 bytes on 2024-12-12T15:23:42.237737997Z wrapping 1 acquired at java.lang.Throwable: client-3333
 at org.eclipse.jetty.io.ArrayByteBufferPool$Tracking$TrackedBuffer.<init>(ArrayByteBufferPool.java:801)
 at org.eclipse.jetty.io.ArrayByteBufferPool$Tracking.acquire(ArrayByteBufferPool.java:768)
 at org.eclipse.jetty.io.ssl.SslConnection.acquireEncryptedInput(SslConnection.java:331)
 at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.fill(SslConnection.java:695)
 at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:272)
 at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:77)
 at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:97)
 at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:250)
 at org.eclipse.jetty.io.AbstractConnection$FillableCallback.succeeded(AbstractConnection.java:318)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
 at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:136)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
 at java.base/java.lang.Thread.run(Thread.java:1575)

0 retain(s)

0 release(s)

0 over-release(s)

Expected: is <0>
     but: was <1> within 5 seconds.Client Leaks:
```

See: https://github.com/jetty/jetty.project/pull/12635/checks?check_run_id=34332830955

**Comment by joakime** [comment]
Closing as fixed, as it hasn't happened in the past 10 months.
