### ISSUE TITLE
Jetty Reactive client hangs for HTTP 401 responses

### ISSUE THREAD

**Issue by bclozel** [eclipse/jetty.project#12652]
**Jetty version(s)**
org.eclipse.jetty:jetty-reactive-httpclient:4.0.8

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.13" 2024-10-15 LTS

**OS type/version**
macOS Sequoia 15.2 (24C101)

**Description**
When receiving an HTTP 401 response, the Jetty HTTP reactive client hangs and never publishes the response.

**How to reproduce?**

```java
HttpClient httpClient = new HttpClient();
httpClient.getProtocolHandlers().remove(WWWAuthenticationProtocolHandler.NAME);
httpClient.start();
Request request = httpClient.newRequest("https://httpbin.org/status/401");
ReactiveRequest reactiveRequest = ReactiveRequest.newBuilder(request).abortOnCancel(true).build();
Mono<ReactiveResponse> responseMono = Mono.fromDirect(reactiveRequest.response());
ReactiveResponse reactiveResponse = responseMono.block(Duration.ofSeconds(3));
System.out.println(reactiveResponse.getHeaders().toString());
System.out.println(reactiveResponse.getStatus());
```

The subscriber times out waiting:
```
java.lang.IllegalStateException: Timeout on blocking read for 3000000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:129) ~[reactor-core-3.6.12.jar:3.6.12]
	at reactor.core.publisher.Mono.block(Mono.java:1807) ~[reactor-core-3.6.12.jar:3.6.12]
```

Am I misusing the reactive API in this case? Note that changing the URL to "https://httpbin.org/status/404" works as expected.

**Comment by sbordet** [comment]
@bclozel you need to swap these 2 lines:

```java
httpClient.getProtocolHandlers().remove(WWWAuthenticationProtocolHandler.NAME);
httpClient.start();
```

to be:

```java
httpClient.start();
httpClient.getProtocolHandlers().remove(WWWAuthenticationProtocolHandler.NAME);
```

I agree that your code is more intuitive, but for historical reasons we add the `ProtocolHandler`s in `doStart()`.

Having said that, we do have a bug, as your test should have worked (with `WWWAuthenticationProtocolHandler` present).

The issue is that `ResponseListeners.emitEvents()` does not notify `onContentSource()` for zero-length content.
In case of the reactive `HttpClient` the missing notification does not invoke `ResponseListenerProcessor.onContentSource()` which is vital to set up the publisher/subscriber chain.

**Comment by mikebell90** [comment]
@sbordet was this released in 12.0.17? Don't see it in 12.0.17 or 12.0.18 changelogs.

**Comment by joakime** [comment]
> [@sbordet](https://github.com/sbordet) was this released in 12.0.17? Don't see it in 12.0.17 or 12.0.18 changelogs.

This is a bug in our changelog tooling.
I'm working through why it felt that PR had "no relevant commits" (meaning that of the list of commits, the files changed are collected, and if those files changed are test, build, or documentation changes then they are removed from the list.) but in this specific case all 3 flies were removed for some reason (when only the 1 test file should have been removed)
This is a good use case to work out the origin of this bug.

Meanwhile, I've manually added this one to https://github.com/jetty/jetty.project/releases/tag/jetty-12.0.17
