### ISSUE TITLE
Session scavenge needs to invalidate session

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1307]
Reported on issue #1224:

03/02 14:40:17.575 WARNING:
java.lang.IllegalStateException: Invalid for read: id=node014pzflh91fdtivf2vumo3k5bc27155 not resident
at org.eclipse.jetty.server.session.Session.checkValidForRead(Session.java:636)
at org.eclipse.jetty.server.session.Session.getAttribute(Session.java:656)
at com.ftl.wak.SessionListener.logSessionDestroyed(SessionListener.java:88)
at com.ftl.wak.SessionListener.sessionDestroyed(SessionListener.java:83)
at org.eclipse.jetty.server.session.SessionHandler.removeSession(SessionHandler.java:1056)
at org.eclipse.jetty.server.session.SessionHandler.invalidate(SessionHandler.java:1230)
at org.eclipse.jetty.server.session.DefaultSessionIdManager.expireAll(DefaultSessionIdManager.java:469)
at org.eclipse.jetty.server.session.SessionHandler.scavenge(SessionHandler.java:1268)
at org.eclipse.jetty.server.session.HouseKeeper.scavenge(HouseKeeper.java:269)
at org.eclipse.jetty.server.session.HouseKeeper$Runner.run(HouseKeeper.java:65)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

The problem is that when the session is being scavenged, it's state is not being set to INVALIDATING.

**Comment by janbartel** [comment]
Fix checked in to jetty-9.4.x branch.
