### ISSUE TITLE
AsyncProxyServletLoadTest fails

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1317]
The AsyncProxyServlet variant of the test fails about 1 in 10 runs with :+1: 
```
2017-02-09 15:22:17.115:WARN:oejp.AsyncProxyServletLoadTest:client-3: Error processing request 932
java.util.concurrent.TimeoutException
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:109)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:654)
	at org.eclipse.jetty.proxy.AsyncProxyServletLoadTest$ClientLoop.run(AsyncProxyServletLoadTest.java:210)
	at java.lang.Thread.run(Thread.java:745)
2017-02-09 15:22:17.115:INFO:oejp.AsyncProxyServletLoadTest:client-3: Shutting down thread client-3
```

I have commented out the test for now to get a more  reliable build.

**Comment by gregw** [comment]
@sbordet I have pushed a fix that I don't really like.
It is to call `provider.close()` if -1 is read.  This suggests that onAllDataRead() is not being called after a -1 is read?  Further investigation is needed.

**Comment by gregw** [comment]
It appears that onAllDataRead is mostly being called after -1 is read, but on the tests that fail it is not.  So we definitely have a bug.

**Comment by sbordet** [comment]
@gregw I was not able to convince myself that adding a state when calling `HttpChannelState.onReadEof()` was safe.
