### ISSUE TITLE
NPE in ClasspathPattern.add when using module logging-log4j2.mod and other logging modules

### ISSUE THREAD

**Issue by garypgithub** [eclipse/jetty.project#1331]
I'm getting the stack trace shown below (on Windows) when I add module logging-log4j to my start.ini.  This seems to be caused by the following lines in logging-log4j.mod:

```
[ini]
jetty.webapp.addServerClasses+=,file:${jetty.base}/lib/slf4j/,file:${jetty.base}/lib/log4j2/
```

These are not valid URIs.  Two slashes should follow the word "file:" so that the offending line looks like this;

```
jetty.webapp.addServerClasses+=,file://${jetty.base}/lib/slf4j/,file://${jetty.base}/lib/log4j2/
```

This same problem exists in other logging-xxxx.mod files.

Steps to reproduce:
1.  Add "--module=logging-log4j2" to start.ini.
2.  Be sure you're deploying at least one web application or have that in the webapps directory.
3.  Start jetty.

Thanks,
Gary

```
2017-02-14 20:15:01 WARN  Resource:121 - java.lang.IllegalArgumentException: URI is not hierarchical
2017-02-14 20:15:01 WARN  WebAppContext:549 - Failed startup of context o.e.j.w.WebAppContext@3fa247d1{/pivselfreg,null,null}{C:\Data\USArmy\jetty_base\webapps\pivselfreg.war}
java.lang.IllegalArgumentException: java.lang.NullPointerException
        at org.eclipse.jetty.webapp.ClasspathPattern.add(ClasspathPattern.java:417) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.webapp.ClasspathPattern.add(ClasspathPattern.java:387) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.webapp.ClasspathPattern.add(ClasspathPattern.java:60) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at java.util.AbstractCollection.addAll(Unknown Source) ~[?:1.8.0_121]
        at org.eclipse.jetty.webapp.ClasspathPattern.addAll(ClasspathPattern.java:485) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.webapp.ClasspathPattern.setAll(ClasspathPattern.java:476) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.webapp.ClasspathPattern.<init>(ClasspathPattern.java:342) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.webapp.WebAppContext.loadServerClasses(WebAppContext.java:893) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:474) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:539) [jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:452) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236) [jetty-deploy-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.server.Server.start(Server.Listening for transport dt_socket at address: 1952
java:452) [jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.server.Server.doStart(Server.java:419) [jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1511) [jetty-xml-9.4.1.v20170120.jar:9.4.1.v20170120]
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1438) [jetty-xml-9.4.1.v20170120.jar:9.4.1.v20170120]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1437) [jetty-xml-9.4.1.v20170120.jar:9.4.1.v20170120]
Caused by: java.lang.NullPointerException
        at org.eclipse.jetty.webapp.ClasspathPattern.add(ClasspathPattern.java:409) ~[jetty-webapp-9.4.1.v20170120.jar:9.4.1.v20170120]
        ... 37 more

```

**Comment by gregw** [comment]
What exactly is the value of `${jetty.base}` for you?   If it is in windows file format then we may have a problem.  

You should be able to explicitly set the value of jetty.base to work around this.

**Comment by gregw** [comment]
@joakime can you check this on windows

**Comment by garypgithub** [comment]
c:\Program Files\jetty.  I’d have to set it to:  //c:\Program Files\jetty.  But I think it might screw up other places where ${jetty.base} is used.  The solution that I proposed (adding // after file:) should work on all operating systems.

**Comment by WalkerWatch** [comment]
I've been able to reproduce this on Windows. I've tried all the logging modules with the following results:

`console-capture` => No issues 
`logging-jetty` => No issues
`logging-jul` => URI not hierarchical (but no NPE) 
`logging-log4j` => NPE, URI not hierarchical
`logging-log4j2` => NPE, URI not hierarchical
`logging-logback` => NPE, URI not hierarchical
`logging-slf4j` => NPE, URI not hierarchical (used `slf4j-simple-impl`)

**Comment by joakime** [comment]
Changing this from `file:${jetty.base}/...` to `${jetty.base.uri}/...` seems to fix this locally.
Doing a few more tests before I commit it though.

**Comment by joakime** [comment]
Pushed this to jetty-9.4.x
