### ISSUE TITLE
Missing servlet DTD and schema definitions in Jetty/Eclipse

### ISSUE THREAD

**Issue by bvingerh** [eclipse/jetty.project#1343]
(Posting here because we encounter this problem when using Jetty; also reported as bug in Eclipse platform: https://bugs.eclipse.org/bugs/show_bug.cgi?id=512427 )

We're using Eclipse 4.6.1 (http://download.eclipse.org/eclipse/updates/4.6/R-4.6.1-201609071200/) and Jetty 9.3.9.v20160517 (http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.3.9.v20160517/).
When using Jetty on a server in a network without public internet access, deploying web applications results in online DTD lookup errors (see stack trace below) with network timeouts (this is because DNS resolving still works; on a completely offline server we get host resolving failures for 'java.sun.com').
This is because local copies of DTDs and schemas referenced from web.xml are no longer included in the platform. They used to be shipped as a resource in javax.servlet 3.0.0.v201112011016 (our previous version when we used Eclipse 4.3) and redirected to accordingly in org.eclipse.jetty.webapp.WebDescriptor$1.mapResources(). However, the latter assumes that these resources are reachable via the classloader of javax.servlet.Servlet.
Eclipse 4.6.1 provides javax.servlet 3.1.0.v201410161800, which no longer includes these DTDs and schemas, causing the redirects in WebDescriptor to be bogus and the application falling back to online retrieval. This is something we want to avoid in corporate networks.

We can currently work around the problem by providing the DTDs ourselves and hacking into WebDescriptor to register different redirects (luckily WebDescriptor#_parserSingleton is a protected static field that can therefore be initialized outside Jetty before the web container starts).

Please fix either the Eclipse platform or Jetty by including the DTDs and schemas and correctly referring to them in code. Currently they are included in org.eclipse.jetty.toolchain:jetty-schemas but not shipped with either the Eclipse platform or Jetty.

Stacktrace:
Feb 15, 2017 10:18:15 AM CET [main] [WARNING] Failed startup of context o.e.j.w.WebAppContext@dbddbe3{/monitor,file:///D:/Apps/com.id.webapp.monitor/webapp/,null}{/D:/Apps/com.id.webapp.monitor/webapp/}
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:255)
	at org.eclipse.jetty.webapp.Descriptor.parse(Descriptor.java:54)
	at org.eclipse.jetty.webapp.WebDescriptor.parse(WebDescriptor.java:207)
	at org.eclipse.jetty.webapp.MetaData.setWebXml(MetaData.java:189)
	at org.eclipse.jetty.webapp.WebXmlConfiguration.preConfigure(WebXmlConfiguration.java:60)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at [our product's code]

**Comment by joakime** [comment]
They can be found in the schemas jar.

```xml
      <dependency>
        <groupId>org.eclipse.jetty.toolchain</groupId>
        <artifactId>jetty-schemas</artifactId>
        <version>3.1</version>
      </dependency>
```

**Comment by bvingerh** [comment]
I know where I can find them; the problem is that they're not included in the official release we include as target platform.
I'm reporting the bug that resources are loaded via a classloader for a class that is not located in the same jar as the resources.
Additionally I'd like to report the bug that you provide a target platform that does not include the resources you refer to from other code in that same target platform.

**Comment by jmcc0nn3ll** [comment]
Jetty publishes a P2 repository out of convenience for some OSGi users but has nothing to do with how Jetty is packaged or included with the Eclipse Platform

**Comment by joakime** [comment]
The official version of the servlet-api jar does not include the dtds.
See https://java.net/jira/browse/SERVLET_SPEC-115
and Issue #1287

**Comment by janbartel** [comment]
@bvingerh the jetty p2 repo does include a bundle that has both the servlet api and the schemas/dtds.  Its the org.eclipse.jetty.osgi-servlet-api bundle. I've checked the jetty-9.3.14 p2 repo and that bundle is definitely included.  Are you using it?

**Comment by bvingerh** [comment]
We have it included in our development target platform, but not referenced from any of our features, so it doesn't get included in our release (there wasn't call for before, because all the DTDs were included in javax.servlet).
We'll add org.eclipse.jetty.osgi-servlet-api to our release, thank you for finding out where all those DTD copies reside.

**Comment by janbartel** [comment]
Cool. I'll close this issue for now.
