### ISSUE TITLE
Some SSL requests fail to load in Chrome with ERR_SSL_PROTOCOL_ERROR 

### ISSUE THREAD

**Issue by meszarv** [eclipse/jetty.project#1355]
Hi,
I am running embedded jetty in my project and after I upgraded Jetty to version 9.3.7+ SSL does not work correctly in Chrome and Firefox, but works fine in IE/Edge.

When I tried version 9.3.7.RC1 and below, everything works fine. 
Starting with version 9.3.7.v20160115 I am getting the SSL error.

This is what I see in Chrome dev tools:
![image](https://cloud.githubusercontent.com/assets/11398000/23328386/df2cfc08-faed-11e6-94f0-bb89fa1b671f.png)

The failed resources are always the same and mostly it is failing to load resources larger then circa 50k.   

This is the exception I get in my servlet 
```
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:197)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:825)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:419)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:141)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:718)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:509)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:668)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:722)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:177)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:413)
	at org.webswing.server.common.util.CommonUtil.transferStreams(CommonUtil.java:117)
	at org.webswing.server.services.resources.ResourceHandlerImpl$ResourceUrl.respondGet(ResourceHandlerImpl.java:127)
	at org.webswing.server.services.resources.ResourceHandlerImpl.serve(ResourceHandlerImpl.java:38)
	at org.webswing.server.base.AbstractUrlHandler.serve(AbstractUrlHandler.java:80)
	at org.webswing.server.base.PrimaryUrlHandler.serve(PrimaryUrlHandler.java:151)
	at org.webswing.server.base.AbstractUrlHandler.serve(AbstractUrlHandler.java:80)
	at org.webswing.server.base.PrimaryUrlHandler.serve(PrimaryUrlHandler.java:151)
	at org.webswing.server.GlobalUrlHandler.serve(GlobalUrlHandler.java:100)
	at org.webswing.server.base.AbstractUrlHandler.secureServe(AbstractUrlHandler.java:117)
	at org.webswing.server.services.security.SecurityManagerServiceImpl$1.call(SecurityManagerServiceImpl.java:64)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.webswing.server.services.security.SecurityManagerServiceImpl.secure(SecurityManagerServiceImpl.java:61)
	at org.webswing.server.WebswingServlet.handleRequest(WebswingServlet.java:55)
	at org.webswing.server.WebswingServlet.doGet(WebswingServlet.java:98)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:197)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:175)
	... 58 more
```

The resources are not served by default servlet, but my own. Here is the code snippet:

```
public boolean respondGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
			resp.setStatus(HttpServletResponse.SC_OK);
			resp.setContentType(mime);
			if (url.getContentLength() >= 0)
				resp.setContentLength(url.getContentLength());
			OutputStream os = resp.getOutputStream();
			InputStream is= urlConnection.getInputStream();
			try {
				byte[] buf = new byte[bufferSize];
				int bytesRead;
				while ((bytesRead = is.read(buf)) != -1)
					os.write(buf, 0, bytesRead);
			} finally {
				is.close();
			}
		}
```

Any idea what could be wrong? 

Thanks
Viktor

**Comment by sbordet** [comment]
The code you posted and the stack trace do not match, as the stack trace reports a `transferStreams()` method that you don't show.
Your code looks like a proxy, so perhaps it's the upstream server at fault ?

Between Jetty 9.3.7.RC1 and 9.3.7.v20160115 we have changed the default `SslContextFactory` configuration to address the SLOTH vulnerability. You may want to read about that and see if you're using old TLS configuration that is affected and that won't work in 9.3.7.v20160115.

Would be strange that some work and some don't though, unless they are requests to different domains.

**Comment by meszarv** [comment]
Looks like the error is present only when all these conditions are met:
- the SLOTH fix (version 9.3.7.v20160115+)
- Bouncycastle JCE installed
- and load-on-startup set to 0 in web.xml

Removing any of the above conditions, will solve the issue.

Here is a simplified maven project to replicate the issue. [ssltest.zip](https://github.com/eclipse/jetty.project/files/804935/ssltest.zip)

Not sure what the root cause is though.
Thanks
Viktor

**Comment by joakime** [comment]
Why are you using Bouncycastle?  (not a criticism, just want to understand why)

**Comment by joakime** [comment]
Having BouncyCastle as position 2 in the providers list is also causing a problem.

Your setup (doesn't work)

1. Provider: SUN version 1.8
2. Provider: BC version 1.51   **&lt;-- your setup**
3. Provider: SunRsaSign version 1.8
4. Provider: SunEC version 1.8
5. Provider: SunJSSE version 1.8
6. Provider: SunJCE version 1.8
7. Provider: SunJGSS version 1.8
8. Provider: SunSASL version 1.8
9. Provider: XMLDSig version 1.8
10. Provider: SunPCSC version 1.8

BouncyCastle recommended setup (works)

1. Provider: SUN version 1.8
2. Provider: SunRsaSign version 1.8
3. Provider: SunEC version 1.8
4. Provider: SunJSSE version 1.8
5. Provider: SunJCE version 1.8
6. Provider: SunJGSS version 1.8
7. Provider: SunSASL version 1.8
8. Provider: XMLDSig version 1.8
9. Provider: SunPCSC version 1.8
10. Provider: BC version 1.51  **&lt;-- BC recommended setup**

**Comment by joakime** [comment]
Documentation at http://www.bouncycastle.org/wiki/display/JA1/Provider+Installation

**Comment by joakime** [comment]
Note: works in the first position as well. (just not in position 2)

**Comment by meszarv** [comment]
Unfortunately I don't control the part where the JCE is installed. It's being installed in ActiveMQ BrokerService  static initializer.

[https://github.com/apache/activemq/blob/master/activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java#L275](url)

**Comment by joakime** [comment]
You can, just specify the `org.apache.activemq.broker.BouncyCastlePosition` system property.

`-Dorg.apache.activemq.broker.BouncyCastlePosition=9`

**Comment by meszarv** [comment]
Right, that should work! I missed the system property there. 👍
