### ISSUE TITLE
Windows and paxexam failure due to "renaming bundle"

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1387]
On windows, the `test-jetty-osgi` project fails most of the time due to a "renaming bundle" issue.

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 0.625 sec <<< FAILURE! - in org.eclipse.jetty.osgi.test.
TestJettyOSGiBootWithJsp
testJspDump(org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJsp)  Time elapsed: 0.625 sec  <<< ERROR!
org.osgi.framework.BundleException: Error while renaming bundle file to final location: C:\code\jetty\jetty.project\jett
y-osgi\test-jetty-osgi\target\1489070454311-0\org.eclipse.osgi\1\0\bundleFile
        at org.eclipse.osgi.storage.Storage.getContentFile0(Storage.java:765)
        at org.eclipse.osgi.storage.Storage.getContentFile(Storage.java:741)
        at org.eclipse.osgi.storage.Storage.install(Storage.java:506)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:146)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:139)
        at org.ops4j.pax.swissbox.framework.RemoteFrameworkImpl.installBundle(RemoteFrameworkImpl.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
        at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
        at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
        at com.sun.proxy.$Proxy10.installBundle(Unknown Source)
        at org.ops4j.pax.exam.forked.ForkedTestContainer.installAndStartBundles(ForkedTestContainer.java:284)
        at org.ops4j.pax.exam.forked.ForkedTestContainer.start(ForkedTestContainer.java:165)
        at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)
        at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:267)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:98)
        at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by joakime** [comment]
This seems related to https://ops4j1.jira.com/browse/PAXEXAM-701

**Comment by joakime** [comment]
Whatever is the first bundle to start works fine.
All subsequent bundles fail.

Your usual Window JVM/file-locking issue?

**Comment by joakime** [comment]
Another interesting observation...

org.eclipse.jetty.util[org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper] : File does not exist file://C/code/jetty/jetty.project/jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty.xml Ignored FQCN: org.eclipse.jetty.util.log.Slf4jLog
org.eclipse.jetty.util[org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper] : Configuration error in file://C:/code/jetty/jetty.project/jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty.xml Ignored FQCN: org.eclipse.jetty.util.log.Slf4jLog

That file most definitely exists, but the URLs look "off".

Ex: `file://C/code/jetty/...` seems to be missing a `:`

**Comment by janbartel** [comment]
So is the renaming failure due to old zombie paxexam instances still running?

**Comment by joakime** [comment]
These failures are not related to the other zombie paxexam from issue #1049 

This seems to be a bad cross-behavior with paxexam + jetty + windows file locks.
paxexam seems to attempt to reuse its bundle directory between each testcase.
wish there was a way to force paxexam to use a new bundle directory for each testcase.

**Comment by janbartel** [comment]
I've upgraded paxexam and the osgi container version and cleaned up the logging. Please retry the tests on windows and see if it helps.

**Comment by joakime** [comment]
*much* better.

I consider this closed, next issue in the world of Windows and OSGi is #1390
