### ISSUE TITLE
HashLoginService and "this.web-inf.url" property are incompatible

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1390]
Looks like a funky URI is being passed into the HashLoginService.
This only shows up like this with `test-jetty-osgi`

```
Running org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJsp

2017-03-10 06:50:25.720:INFO::Start Level: Equinox Container: d30b2505-b0da-4433-a50e-33228b6c5c6a: Logging initialized @15625ms to org.eclipse.jetty.util.log.StdErrLog
2017-03-10 06:50:26.848:WARN:oejw.WebAppContext:Start Level: Equinox Container: d30b2505-b0da-4433-a50e-33228b6c5c6a: Failed startup of context o.e.j.w.WebAppContext@404769fc{/,file:///C:/Users/joakim/AppData/Local/Temp/jetty-0.0.0.0-59801-bundleFile-_-any-5050212073621695063.dir/webapp/,UNAVAILABLE}{/test.war}
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\C:\Users\joakim\AppData\Local\Temp\jetty-0.0.0.0-59801-bundleFile-_-any-5050212073621695063.dir\webapp\WEB-INF\realm.properties
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.io.File.toPath(File.java:2234)
        at org.eclipse.jetty.security.PropertyUserStore.setConfigPath(PropertyUserStore.java:121)
        at org.eclipse.jetty.security.HashLoginService.doStart(HashLoginService.java:189)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.security.SecurityHandler.doStart(SecurityHandler.java:361)
        at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:448)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
        at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:501)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:830)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1482)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1444)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:799)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:542)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
        at org.eclipse.jetty.osgi.boot.BundleWebAppProvider.bundleAdded(BundleWebAppProvider.java:211)
        at org.eclipse.jetty.osgi.boot.BundleWebAppProvider$WebAppTracker.addingBundle(BundleWebAppProvider.java:80)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:903)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:156)
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
        at org.eclipse.osgi.container.Module.start(Module.java:467)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
DEFAULT_HTTP_PORT=59801
DEFAULT_SSL_PORT=59802
```

**Comment by joakime** [comment]
It also causes a later failure.

```
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 17.408 sec <<< FAILURE! - in org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJsp
testJspDump(org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJsp)  Time elapsed: 17.399 sec  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<503>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJsp.testJspDump(TestJettyOSGiBootWithJsp.java:146)
```

**Comment by joakime** [comment]
Cannot use the `this.web-inf.url` property with `HashLoginService` on Windows.

It results in a URL that is tossed into a `new File()` call that will always be invalid on Windows.

Introducing `this.web-inf.path` property and also making `HashLoginService._config` be a `File` reference (as its required for the `PropertyUserStore` anyway.

**Comment by joakime** [comment]
Considering this working. closing.

**Comment by gregw** [comment]
Does not work for packed wars, which do not have paths.  Also the path property is not portable.
Would be better to allow a URI to be set.

**Comment by gregw** [comment]
I better solution would be to update HashLoginService to assume the config string is a resource. This would allow filenames or URIs to be passed.

The names of these attributes also don't really match with what we do elsewhere.  The pattern we have addopted else where is:

${web-inf} could be a path or a URI
${web-inf.uri} is the URI

**Comment by janbartel** [comment]
I've implemented Greg's suggestion and removed the this.web_url.path as it won't work for any packed wars, and added properties for web_inf and web_inf.uri. Changes checked in to jetty-9.3 and jetty-9.4.

In order to make the HashLoginService work with packed wars/jars, it will be necessary to modify the PropertyUserService, as it expects an actual config file or path on the file system that it can load.  I will raise another bug to change it to try to extract a config file if it isn't already a useable file.
