### ISSUE TITLE
Jetty 9.4.2 does not support constructors with varargs in XML config files

### ISSUE THREAD

**Issue by mrossi975** [eclipse/jetty.project#1404]
if you try to put the following config in jetty-http2.xml:

My config looks like this:

```xml
<Configure id="sslConnector" class="org.eclipse.jetty.server.ServerConnector">
  <Call name="addConnectionFactory">
    <Arg>
      <New class="org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory">
        <Arg name="config"><Ref refid="sslHttpConfig"/></Arg>
        <Arg>
                        <Array type="String">
                        <Item>h2</Item>
                        <Item>h2-17</Item>
                        <Item>h2-16</Item>
                        <Item>h2-15</Item>
                        <Item>h2-14</Item>
                </Array>
                </Arg>
        <Set name="maxConcurrentStreams"><Property name="jetty.http2.maxConcurrentStreams" deprecated="http2.maxConcurrentStreams" default="1024"/></Set>
        <Set name="initialStreamRecvWindow"><Property name="jetty.http2.initialStreamRecvWindow" default="65535"/></Set>
      </New>
    </Arg>
  </Call>

  <Ref refid="sslContextFactory">
    <Set name="CipherComparator">
      <Get class="org.eclipse.jetty.http2.HTTP2Cipher" name="COMPARATOR"/>
    </Set>
    <Set name="useCipherSuitesOrder">true</Set>
  </Ref>

</Configure>
```

You get the following stacktrace

```
java.security.PrivilegedActionException: null
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1437)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:222)
        at org.eclipse.jetty.start.Main.start(Main.java:486)
        at org.eclipse.jetty.start.Main.main(Main.java:79)
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.eclipse.jetty.util.TypeUtil.construct(TypeUtil.java:663)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:784)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1235)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1140)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$500(XmlConfiguration.java:274)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$AttrOrElementNode.getList(XmlConfiguration.java:1368)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$AttrOrElementNode.getList(XmlConfiguration.java:1343)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:706)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:417)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:358)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:259)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1499)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1438)
        ... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.eclipse.jetty.server.AbstractConnectionFactory.<init>(AbstractConnectionFactory.java:62)
        at org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory.<init>(AbstractHTTP2ServerConnectionFactory.java:59)
        at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory.<init>(HTTP2ServerConnectionFactory.java:58)
        ... 26 common frames omitted
```

Could it be that the problem is supporting constructors with varargs?

```
public HTTP2ServerConnectionFactory(@Name("config") HttpConfiguration httpConfiguration,String... protocols)
```

**Comment by mrossi975** [comment]
it looks like my XML bits were stripped, I will try to attach it now

**Comment by mrossi975** [comment]
`<Configure id="sslConnector" class="org.eclipse.jetty.server.ServerConnector">
  <Call name="addConnectionFactory">
    <Arg>
      <New class="org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory">
        <Arg name="config"><Ref refid="sslHttpConfig"/></Arg>
        <Arg>
                        <Array type="String">
                        <Item>h2</Item>
                        <Item>h2-17</Item>
                        <Item>h2-16</Item>
                        <Item>h2-15</Item>
                        <Item>h2-14</Item>
                </Array>
                </Arg>
        <Set name="maxConcurrentStreams"><Property name="jetty.http2.maxConcurrentStreams" deprecated="http2.maxConcurrentStreams" default="1024"/></Set>
        <Set name="initialStreamRecvWindow"><Property name="jetty.http2.initialStreamRecvWindow" default="65535"/></Set>
      </New>
    </Arg>
  </Call>

  <Ref refid="sslContextFactory">
    <Set name="CipherComparator">
      <Get class="org.eclipse.jetty.http2.HTTP2Cipher" name="COMPARATOR"/>
    </Set>
    <Set name="useCipherSuitesOrder">true</Set>
  </Ref>

</Configure>`

**Comment by mrossi975** [comment]
no way to attach or paste XML it seems, attaching a screenshot of it instead
![jetty-http2](https://cloud.githubusercontent.com/assets/3889052/24002461/17befabc-0a61-11e7-9025-9505f376720c.png)

**Comment by joakime** [comment]
Your fine, the XML bits show up in the first message ok.

**Comment by sbordet** [comment]
The problem is that we have one parameter annotated with `@Name`, but the other is not annotated.

So we ignore the second parameter.

I think we should fix it to be more tolerant, so that even if `@Name` is absent, it goes in parameter order.

**Comment by mrossi975** [comment]
looks like this one didn't make it into 9.4.4.. hope a fix is still in the pipeline. Currently I have had to disable HTTP/2.0 on my server :(
