### ISSUE TITLE
java.net.UnknownHostException: iwarehouse

### ISSUE THREAD

**Issue by ebremer** [eclipse/jetty.project#1422]
I'm using the Jetty client to download images.  It works, but intermittently, it fails to download an image and throws the following error:
java.util.concurrent.ExecutionException: java.net.UnknownHostException: iwarehouse
	at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:221)
	at edu.stonybrook.bmi.tcga.PA.downloadfile(PA.java:214)
	at edu.stonybrook.bmi.tcga.PA.grabfile(PA.java:265)
	at edu.stonybrook.bmi.tcga.PA.GetTargetIDs(PA.java:293)
	at edu.stonybrook.bmi.tcga.PA.main(PA.java:321)
Caused by: java.net.UnknownHostException: iwarehouse
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.eclipse.jetty.util.SocketAddressResolver$Async.lambda$resolve$1(SocketAddressResolver.java:167)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

The critical code snippet is as follows:

            InputStreamResponseListener listener = new InputStreamResponseListener();
            httpClient.newRequest(url).method(HttpMethod.GET).header("Accept", mimetype).send(listener);
            Response response = listener.get(240, TimeUnit.SECONDS);
            if (response.getStatus() == 200) {
                try (InputStream responseContent = listener.getInputStream()) {
                    int read = 0;
                    long counter = 0;
                    byte[] bytes = new byte[1024];
                    while ((read = responseContent.read(bytes)) != -1) {
                        counter = counter + bytes.length;
                        fos.write(bytes, 0, read);
                    }
                } finally {
                    fos.flush();
                    fos.close();
                }

My DNS checks out, and I've even swapped in Google's 8.8.8.8 public DNS server, but the error still occurs.  I've even replaced the DNS name of the web server with it's ip address, yet, this error is still thrown.  I'm using jetty-distribution-9.4.3.v20170317.  I have no idea where this "iwarehouse" host is coming from.

**Comment by ebremer** [comment]
Here is the URL that failed:
http://api.brain-map.org/api/v2/image_download/272984034
My program continues running, and successfully downloads many images, but, every so many download to the same URL (with only the ending ID changing), the error is thrown.

**Comment by ebremer** [comment]
Okay, the problem appears to be with api.brain-map.org.  They seem to be using redirection for every connection and it looks like one of their servers/DNS is on the fritz.  The "iwarehouse" address is coming from them on redirection perhaps to a load balancing server.  Is there a way to augment the error message in Jetty to indicate a host failure on redirect?
