### ISSUE TITLE
StackOverflowError when using URLStreamHandlerFactory in WebAppClassloader

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1448]
If an environment has a URLStreamHandler installed, its possible for a StackOverflowError to occur when in the WebAppClassloader ...

```
Exception in thread "FelixStartLevel" java.lang.StackOverflowError
 	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:495)
 	at java.net.URL.getURLStreamHandler(URL.java:1142)
 	at java.net.URL.<init>(URL.java:599)
 	at java.net.URL.<init>(URL.java:490)
 	at java.net.URL.<init>(URL.java:439)
 	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:166)
 	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:149)
 	at org.eclipse.jetty.util.TypeUtil.getLoadedFrom(TypeUtil.java:726)
 	at org.eclipse.jetty.webapp.ClasspathPattern.match(ClasspathPattern.java:518)
 	at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:811)
 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:563)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:495)
 	at java.net.URL.getURLStreamHandler(URL.java:1142)
 	at java.net.URL.<init>(URL.java:599)
 	at java.net.URL.<init>(URL.java:490)
 	at java.net.URL.<init>(URL.java:439)
 	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:166)
 	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:149)
 	at org.eclipse.jetty.util.TypeUtil.getLoadedFrom(TypeUtil.java:726)
 	at org.eclipse.jetty.webapp.ClasspathPattern.match(ClasspathPattern.java:518)
 	at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:811)
 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:563)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:495)
 	at java.net.URL.getURLStreamHandler(URL.java:1142)
 	at java.net.URL.<init>(URL.java:599)
 	at java.net.URL.<init>(URL.java:490)
```

**Comment by joakime** [comment]
Been able to reproduce in a simple testcase.

**Comment by joakime** [comment]
There is still a StackOverflowError present, this time from the following code path ...

```
Exception in thread "FelixStartLevel" java.lang.StackOverflowError
 	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:495)
 	at java.net.URL.getURLStreamHandler(URL.java:1142)
 	at java.net.URL.<init>(URL.java:599)
 	at java.net.URL.<init>(URL.java:490)
 	at java.net.URL.<init>(URL.java:439)
 	at java.net.URI.toURL(URI.java:1089)
 	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:87)
 	at org.eclipse.jetty.util.TypeUtil.getLoadedFrom(TypeUtil.java:724)
 	at org.eclipse.jetty.webapp.ClasspathPattern.match(ClasspathPattern.java:518)
 	at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:816)
 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:563)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:495)
 	at java.net.URL.getURLStreamHandler(URL.java:1142)
 	at java.net.URL.<init>(URL.java:599)
 	at java.net.URL.<init>(URL.java:490)
 	at java.net.URL.<init>(URL.java:439)
 	at java.net.URI.toURL(URI.java:1089)
 	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:87)
```

**Comment by janbartel** [comment]
@joakime great that this seems to work, however can you explain how it is working, when I still see references to URL in the new TypeUtil.getLocationOfClass method?

**Comment by joakime** [comment]
@janbartel The key is `new URL()` (and anything that uses `new URL()`, such as `URI.toURL()` and `Resource.newResource()`)

The lookup for `URLStreamHandler` occurs during `new URL()`, and **only on the first time** it encounters a new `protocol` (such as `jar`, `file`, `http`, `bundle`, etc).  

Internally in the JVM has a static / singleton cache of `protocol` to `URLStreamHandler`.

The working theory that produced that commit is .. if by the time you call `TypeUtil.getLocationOfClass(Class)` that particular `Class` instance has already been loaded via the ClassLoader and whatever `URLStreamhandler` it needed to load has been initialized already.

**Comment by joakime** [comment]
@gregw tested the new `jetty-9.4.x` HEAD (with your merge) against `felix-webapp`.
Works great.  
Closing issue.
