### ISSUE TITLE
Unable to find the JVM Lib directory in WebAppContext

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1449]
When running the WebAppClassLoaderTest, there is a WARN produced ...

```
java.lang.NullPointerException
	at org.eclipse.jetty.webapp.WebAppContext.<clinit>(WebAppContext.java:140)
	at org.eclipse.jetty.webapp.WebAppClassLoaderTest.init(WebAppClassLoaderTest.java:62)
```

**Comment by joakime** [comment]
Looks like this code isn't used.
Also it is an NPE everywhere on Windows.
The `System.class` has no Protection domain.
And you cannot use the Classloader to look up its URL.

Going to remove it from `WebAppClassLoader`.

**Comment by joakime** [comment]
@gregw you added this `__jvmLib` reference, but didn't use it? (could use a review)
