### ISSUE TITLE
Configuring Jetty.threadPool.maxThreads

### ISSUE THREAD

**Issue by venkata6** [eclipse/jetty.project#1464]
Dear All,
We are using jetty-9.4.1.v20170120 in our Rx Java based REST API server
Since our server is asynchronous, we though we should have less threads to avoid context switching overhead and configured 'Jetty.threadPool.maxThreads'  to a value of 8 ( in a 4 core box )

Server starts normally but dont respond to any HTTP request ( even though the TCP/IP connection is  made ) 

Upon increasing the number of threads, it worked .

It will be nice if we get any warning or error message to indicate the issue ( no thread to service the incoming requests ) 

We found the minimum  number of threads needed is related to the number of cores a box has. Hence it worked in few boxes and not in other.  This will lead to 'hard to find' bug if we push to AWS as we dont have any control on which hardware the code runs .

So we would appreciate an error or warning for this non-optimal customization

regards
venkatesh arjunan

**Comment by joakime** [comment]
What you experienced is the selector and acceptor configuration of the ServerConnector, and how it interacts with the ThreadPool (each acceptor and selector uses a thread from the threadpool)

Acceptors: 
https://github.com/eclipse/jetty.project/blob/jetty-9.4.3.v20170317/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java#L192-L197

Selectors:
https://github.com/eclipse/jetty.project/blob/jetty-9.4.3.v20170317/jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java#L222-L223

If there are no threads available, you'll get a `java.util.concurrent.RejectedExecutionException` indicating that.

As for the mechanical sympathy patterns (context switching overhead), we pride ourselves on having a default configuration that works spendidly for mechanical sympathy for 1 core to 23 cores (beyond that you need to tweak things).

https://webtide.com/jetty-9-goes-fast-with-mechanical-sympathy/

Tweaking the thread pool for lower thread maximum counts like you have done only makes sense in very limited environments (such as non-public configurations with only 1 client and/or connection)

Jetty uses a non-standard thread execution model called Eat-What-You-Kill and works better with more threads then you have configured.   

https://webtide.com/eat-what-you-kill/

Before you make changes to the default configurations, please get familiar with how Jetty functions.

**Comment by venkata6** [comment]
ok thanks for the documents , Joakime, please close this issue if this is expected behaviour

**Comment by venkata6** [comment]
Just a quick observation or two 
1) I dont think we got java.util.concurrent.RejectedExecutionException though we used the Spring embedded one (org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer)
2) If changing the config so crucial , should it be highlighted somewhere  ??

**Comment by venkata6** [comment]
Further investigating this issue, it seems like issue is specific to springboot applications. ( original issue was reported in the spring embedded server in a spring boot application ) 

1. Downloaded Jetty 9 and tried configuring the same parameters in ../etc/jetty.xml ..  Server failed to start , getting correct exception..

2017-04-16 16:43:23.179:INFO:oejs.Server:main: jetty-9.4.3.v20170317
2017-04-16 16:43:23.191:WARN:oejx.XmlConfiguration:main:
java.lang.IllegalStateException: Insufficient threads: max=8 < needed(acceptors=1 + selectors=8 + request=1)
	at org.eclipse.jetty.server.Server.doStart(Server.java:414)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1511)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1438)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1437)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:222)
	at org.eclipse.jetty.start.Main.start(Main.java:486)
	at org.eclipse.jetty.start.Main.main(Main.java:79)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:222)
	at org.eclipse.jetty.start.Main.start(Main.java:486)
	at org.eclipse.jetty.start.Main.main(Main.java:79)
Caused by: java.lang.IllegalStateException: Insufficient threads: max=8 < needed(acceptors=1 + selectors=8 + request=1)
	at org.eclipse.jetty.server.Server.doStart(Server.java:414)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1511)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1438)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1437)
	... 7 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:222)
	at org.eclipse.jetty.start.Main.start(Main.java:486)
	at org.eclipse.jetty.start.Main.main(Main.java:79)
Caused by: java.lang.IllegalStateException: Insufficient threads: max=8 < needed(acceptors=1 + selectors=8 + request=1)
	at org.eclipse.jetty.server.Server.doStart(Server.java:414)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1511)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1438)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1437)
	... 7 more
