### ISSUE TITLE
IllegalStateException in RolloverFileOutputStream

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1469]
Report at 1e46576bf4f888656271b0cbd6fd1605b1808730

> BTW, scheduleNextRollover() is called from within RollTask.run()
> so, __rollover.schedule(_rollTask, ***) leads to an exception
> Exception in thread "org.eclipse.jetty.util.RolloverFileOutputStream" java.lang.IllegalStateException: Task already scheduled or cancelled
> at java.util.Timer.sched(Timer.java:401)
> at java.util.Timer.schedule(Timer.java:193)
> at org.eclipse.jetty.util.RolloverFileOutputStream.scheduleNextRollover(RolloverFileOutputStream.java:216)
> at org.eclipse.jetty.util.RolloverFileOutputStream.access$200(RolloverFileOutputStream.java:48)
> at org.eclipse.jetty.util.RolloverFileOutputStream$RollTask.run(RolloverFileOutputStream.java:359)
> at java.util.TimerThread.mainLoop(Timer.java:555)
> at java.util.TimerThread.run(Timer.java:505)
> As result, first midnight switches OutputStream out, throws this exception and stops scheduling _rollTask.
> Suppose
> _rollTask = new RollTask();
> before
> __rollover.schedule(_rollTask...
> will fix that problem.

**Comment by joakime** [comment]
Simplest demonstration of problem.

``` java
package time;

import java.util.Timer;
import java.util.concurrent.CountDownLatch;

public class TimerToy
{
    public static void main(String[] args)
    {
        new TimerToy().run();
    }
    
    public class Task extends java.util.TimerTask
    {
        @Override
        public void run()
        {
            try
            {
                System.err.print('.');
                TimerToy.this.scheduleNext(); // can't schedule next from here
            }
            catch (Throwable t)
            {
                t.printStackTrace(System.err);
            }
        }
    }
    
    private Timer timer;
    private Task task;
    private CountDownLatch latch;
    
    public TimerToy()
    {
        latch = new CountDownLatch(40);
        task = new Task();
    }
    
    private void scheduleNext()
    {
        timer.schedule(task, 500);
    }
    
    private void run()
    {
        try
        {
            timer = new Timer();
            timer.schedule(task, 500);
            latch.await();
        }
        catch (Throwable t)
        {
            t.printStackTrace(System.err);
        }
    }
}
```

**Comment by joakime** [comment]
We cannot go back to periodic Timer usage, as the daylights savings time behavior breaks it for long running Jetty instances.

However, we could use a ScheduledExecutorService instead, like this ...

``` java
package time;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class TimerToyNG implements Runnable
{
    public static void main(String[] args) throws InterruptedException
    {
        int count = 10;
        TimerToyNG toy = new TimerToyNG(count);
        toy.scheduleNext();
        System.err.println("Waiting completion of " + count + " events");
        toy.latch.await();
        System.err.println("Done");
    }
    
    private ScheduledExecutorService timer;
    private CountDownLatch latch;
    private long lastEvent;
    
    public TimerToyNG(int count)
    {
        timer = Executors.newSingleThreadScheduledExecutor();
        latch = new CountDownLatch(count);
    }
    
    private void scheduleNext()
    {
        lastEvent = System.currentTimeMillis();
        timer.schedule(this, 500, TimeUnit.MILLISECONDS);
    }
    
    @Override
    public void run()
    {
        try
        {
            long now = System.currentTimeMillis();
            System.err.println(" -> " + now + " (" + (now - lastEvent) + ")");
            latch.countDown();
            if (latch.getCount() > 0)
                scheduleNext();
            else
                timer.shutdownNow(); // <-- ew HACK!
        }
        catch (Throwable t)
        {
            t.printStackTrace(System.err);
        }
    }
}
```

The biggest problem is the running scheduler that never shuts down, preventing the JVM from exiting.

**Comment by joakime** [comment]
Looks like I can instantiate the ScheduledThreadExecutor with a custom ThreadFactory to set the daemon flag on the threads to get around the shutdown requirement.

``` java
        timer = Executors.newSingleThreadScheduledExecutor(r ->
        {
            Thread t = Executors.defaultThreadFactory().newThread(r);
            t.setDaemon(true);
            return t;
        });
```

**Comment by joakime** [comment]
Going with a simple `new RollTask()` technique for now.
Will do the Timer -> Scheduler changeover in a different issue at a later date.
