### ISSUE TITLE
Some SSL requests fail to load in Chrome with ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by meszarv** [eclipse/jetty.project#1471]
This issue is related to #1355

The previous issue was resolved by setting the JCE position for bouncy castle using:
`-Dorg.apache.activemq.broker.BouncyCastlePosition=11`
with this fix SSL works well up to version `9.3.9.v20160517`

Starting with version `9.3.10.M0` (up to the latest version) the same issue is back. 

See updated maven project to replicate it: 
[ssltest2.zip](https://github.com/eclipse/jetty.project/files/920227/ssltest2.zip)

The issue is less frequent compared to #1355, and happens randomly (may have to refresh the page couple of times to get it)

Thanks
Viktor

**Comment by meszarv** [comment]
Also noticed 2 different exceptions appearing in logs with version `9.3.10.M0`:

```
[WARNING] Error for /css/style9.css
java.lang.StackOverflowError
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:175)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:839)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.shutdownOutput(SslConnection.java:928)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.close(SslConnection.java:967)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:893)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.shutdownOutput(SslConnection.java:928)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.close(SslConnection.java:967)

```

And
```
[WARNING] /css/style.css
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427)
	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:491)
	at org.eclipse.jetty.io.ssl.SslConnection.onClose(SslConnection.java:167)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345)
	at org.eclipse.jetty.io.ManagedSelector$2.run(ManagedSelector.java:442)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```
This is how it looks in Chrome now:
- sometimes fails after part of the file is downloaded
- other times fails and no data is transfered

![image](https://cloud.githubusercontent.com/assets/11398000/25014195/be70a2b8-2044-11e7-8f1a-11b5643d1b9e.png)

**Comment by joakime** [comment]
Use a stable release, `M0` is an unstable milestone release.
Try `9.3.18.v20170406` instead.

Issue #1355 recommended position 9, not 11.
Tip: the position is *HIGHLY* dependent on the JVM and its configuration.
Picking a number arbitrarily without knowing how your JVM is configured is like throwing darts at night while blindfolded with no idea which direction the dart board is.

This seems like either an activemq (configuration) bug, or a BouncyCastle (configuration) bug.

**Comment by joakime** [comment]
To figure out what your provider list looks like, run this ...

``` java
package jetty.tls;

import java.security.Provider;

import sun.security.jca.ProviderList;
import sun.security.jca.Providers;

public class JavaTlsDump
{
    public static void main(String[] args)
    {
        int i = 0;
        ProviderList list = Providers.getFullProviderList();
        for (Provider provider : list.providers())
        {
            System.out.printf("%3d: %s%n", i++, provider);
        }
    }
}
```

On Java 1.8.0_121 (64-bit) on Windows 10, with no additional JCA/JCE jars, I see ...

```
  0: SUN version 1.8
  1: SunRsaSign version 1.8
  2: SunEC version 1.8
  3: SunJSSE version 1.8
  4: SunJCE version 1.8
  5: SunJGSS version 1.8
  6: SunSASL version 1.8
  7: XMLDSig version 1.8
  8: SunPCSC version 1.8
  9: SunMSCAPI version 1.8
```

Yours will probably be different.
