### ISSUE TITLE
SIOOBE in ContextHandler startup

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#1475]
Seen in startup of Jetty 9.4.4 stage.

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at org.eclipse.jetty.util.log.AbstractLogger.condensePackageString(AbstractLogger.java:207)
        at org.eclipse.jetty.util.log.StdErrLog.<init>(StdErrLog.java:218)
        at org.eclipse.jetty.util.log.StdErrLog.<init>(StdErrLog.java:202)
        at org.eclipse.jetty.util.log.StdErrLog.newLogger(StdErrLog.java:636)
        at org.eclipse.jetty.util.log.AbstractLogger.getLogger(AbstractLogger.java:48)
        at org.eclipse.jetty.util.log.Log.getLogger(Log.java:317)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:768)
```

**Comment by joakime** [comment]
This bug seems to have been introduced with commit 50e87c05a70d2a7a3cca74cedb12a084a55125b3
