### ISSUE TITLE
overrideDescriptor leads to Unknown configuration type: web-app

### ISSUE THREAD

**Issue by StefanLindner** [eclipse/jetty.project#1497]
My setting:
Current docker image jetty:9.4-jre8
jetty 9.4.4
OpenJDK 1.8.0_121

I have a Context XML file like this
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">

   <Set name="contextPath">/aionline</Set>
   <Set name="war">/var/lib/jetty/webapps/AIOnline.war</Set>

   <Call name="setInitParameter">
      <Arg>myParam</Arg>
      <Arg>original</Arg>
   </Call>

   <Set name="overrideDescriptor">/var/lib/jetty/webapps/override-web.xml</Set>

</Configure>
```
and my override-web.xml looks like
```XML
<?xml version="1.0" encoding="ISO-8859-1"?>

<web-app xmlns="http://java.sun.com/xml/ns/javaee" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd" 
   version="2.5">

        <context-param>
                <param-name>myParam</param-name>
                <param-value>modified</param-value>
        </context-param>

</web-app>
```

First of all: this works and my web applications gets the value 'modified' for context parameter 'myParam'.
But jetty's logfile shows
```
java.lang.IllegalStateException: Unknown configuration type: web-app in org.eclipse.jetty.deploy.providers.WebAppProvider$1@69ea3742
        at org.eclipse.jetty.xml.XmlConfiguration.setConfig(XmlConfiguration.java:195)
        at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:135)
        at org.eclipse.jetty.deploy.providers.WebAppProvider$1.<init>(WebAppProvider.java:283)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.createContextHandler(WebAppProvider.java:282)
        at org.eclipse.jetty.deploy.App.getContextHandler(App.java:105)
        at org.eclipse.jetty.deploy.bindings.StandardDeployer.processBinding(StandardDeployer.java:36)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:458)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:452)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:419)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1511)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1438)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1437)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:222)
        at org.eclipse.jetty.start.Main.start(Main.java:486)
        at org.eclipse.jetty.start.Main.main(Main.java:79)
```

I could not find any hint how to write a correct overrideDescriptor. The few examples that I could find all lookd similar to mine.

I have tried a different approach and build my override-web.xml looks like
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.server.handler.ContextHandler">

         <Call name="setInitParameter">
            <Arg>myParam</Arg>
            <Arg>modified</Arg>
         </Call>
</Configure>
```

But this has no effect.

**Comment by janbartel** [comment]
You have put the override descriptor into the hot deploy directory, so jetty thinks it is a context xml file to deploy.  You can make a sub directory and put the override descriptor into it,  just make sure the sub directory name ends in ".d" as jetty knows to ignore those. This page has more info on deployment: https://eclipse.org/jetty/documentation/9.4.x/deployment-architecture.html#default-web-app-provider
