### ISSUE TITLE
Review GZIPContentDecoder buffer pooling

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#1509]
In `org.eclipse.jetty.fcgi.server.HttpClientTest.testGZIPContentEncoding()`:

```
2017-04-27 11:07:16.122:WARN:oeji.LeakTrackingByteBufferPool:: ByteBuffer java.nio.HeapByteBuffer[pos=0 lim=0 cap=2048] leaked at:
java.lang.Throwable
	at org.eclipse.jetty.util.LeakDetector$LeakInfo.<init>(LeakDetector.java:183)
	at org.eclipse.jetty.util.LeakDetector$LeakInfo.<init>(LeakDetector.java:172)
	at org.eclipse.jetty.util.LeakDetector.acquired(LeakDetector.java:79)
	at org.eclipse.jetty.io.LeakTrackingByteBufferPool.acquire(LeakTrackingByteBufferPool.java:66)
	at org.eclipse.jetty.http.GZIPContentDecoder.acquire(GZIPContentDecoder.java:408)
	at org.eclipse.jetty.http.GZIPContentDecoder.decodeChunks(GZIPContentDecoder.java:174)
	at org.eclipse.jetty.http.GZIPContentDecoder.decode(GZIPContentDecoder.java:71)
	at org.eclipse.jetty.client.HttpReceiver.responseContent(HttpReceiver.java:336)
	at org.eclipse.jetty.fcgi.client.http.HttpReceiverOverFCGI.responseContent(HttpReceiverOverFCGI.java:57)
	at org.eclipse.jetty.fcgi.client.http.HttpChannelOverFCGI.content(HttpChannelOverFCGI.java:121)
	at org.eclipse.jetty.fcgi.client.http.HttpConnectionOverFCGI$ResponseListener.onContent(HttpConnectionOverFCGI.java:408)
	at org.eclipse.jetty.fcgi.parser.ResponseContentParser$ResponseParser.notifyContent(ResponseContentParser.java:277)
	at org.eclipse.jetty.fcgi.parser.ResponseContentParser$ResponseParser.parse(ResponseContentParser.java:131)
	at org.eclipse.jetty.fcgi.parser.ResponseContentParser.onContent(ResponseContentParser.java:74)
	at org.eclipse.jetty.fcgi.parser.StreamContentParser.parse(StreamContentParser.java:69)
	at org.eclipse.jetty.fcgi.parser.Parser.parse(Parser.java:82)
	at org.eclipse.jetty.fcgi.client.http.HttpConnectionOverFCGI.parse(HttpConnectionOverFCGI.java:180)
	at org.eclipse.jetty.fcgi.client.http.HttpConnectionOverFCGI.process(HttpConnectionOverFCGI.java:150)
	at org.eclipse.jetty.fcgi.client.http.HttpConnectionOverFCGI.onFillable(HttpConnectionOverFCGI.java:114)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by paskos** [comment]
+1, at server startup we load lots of gzipped config files using jetty-client and since we moved to version 9.4.6 we see OutOfMemoryErrors. 
After analyzing heap dump we found that MappedByteBufferPool.heapBuffers took 90+ % of the heap.
We fixed the issue by creating our own instance of org.eclipse.jetty.client.GZIPContentDecoder with a null ByteBufferPool.
Hope it helps.

**Comment by gregw** [comment]
A temporary fix that uses a hueristic to limit the pool size.

Perhaps such a hueristic should be the default for the queue size of all ByteBufferPools, as infinite queue size is rarely going to be a good thing?

Also, I think all the pools need to have better javadoc, plus an upper/lower bound of the size of buffer that they will pool, as gzip will tend to ask for lots of random sized buffers to put the expanded data into, some could be very
large and unlikely to be reused.

**Comment by gregw** [comment]
Coming up with a perfect heuristic for an arbitrary buffer pool will be very difficult - more so if done with only  bucket factor and size.

A better limit would be to apply a total allocated size to the pool and a LRU algorithm used to discard buffers from the least recently used bucket when the size limit is exceeded.    Such an algorithm would better handle the difference between lots of small buffer vs a few huge buffers.

However, the problem is that the LinkedHashMap that provides easy LRU is not a concurrent class, and thus would require synchronisation.   Experience has shown that global locks on pool are not a good thing and we really should avoid if possible.

**Comment by gregw** [comment]
Hmmm perhaps it is time that rather than do all our own caching/pooling that we brought in a dependency like https://github.com/ben-manes/concurrentlinkedhashmap

We have many caches/pools in Jetty and they are mostly implemented in adhoc fashion.   It may be worthwhile to consider replacing them all with size limited `concurrentlinkedhashmap` ?

**Comment by sbordet** [comment]
The API for `ContentDecoder` does not allow for complete `ByteBuffer` pooling: the `ByteBuffer` that will be returned by `ByteBuffer ContentDecoder.decode(ByteBuffer)` is handed to the application, that has no knowledge whether the buffer was pooled and by what buffer pool.
As such it is normally "leaked", but that is fine since our `ByteBufferPool` implementations allow for such behavior.

**Comment by sbordet** [comment]
@gregw moved your thoughts to #1861.
