### ISSUE TITLE
RolloverFileOutputStream can't handle multiple instances

### ISSUE THREAD

**Issue by KentPeacock** [eclipse/jetty.project#1513]
I have a Jetty process that creates two Server instances, each of which has a separate request log. Somehow, they collide with each other over the single static Timer in the RolloverFileOutputStream class, and this happens during the midnight rollover:

Exception in thread "org.eclipse.jetty.util.RolloverFileOutputStream" java.lang.IllegalStateException: Task already scheduled or cancelled
        at java.util.Timer.sched(Timer.java:401)
        at java.util.Timer.schedule(Timer.java:193)
        at org.eclipse.jetty.util.RolloverFileOutputStream.scheduleNextRollover(RolloverFileOutputStream.java:216)
        at org.eclipse.jetty.util.RolloverFileOutputStream.access$200(RolloverFileOutputStream.java:48)
        at org.eclipse.jetty.util.RolloverFileOutputStream$RollTask.run(RolloverFileOutputStream.java:359)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

This is in 9.4.3. It's possible this one is fixed in 9.4.4, with the change in the RollTask handling. Is a Timer instance allowed more than one schedule operation on a Timer? One thing I notice is that the RollTask run routine doesn't have locking around the call to scheduleNextRollover.

**Comment by sbordet** [comment]
@gregw why `RolloverFileOutputStream` has a static field at all ? The `Timer` should not be static, as the `RolloverFileOutputStream` is typically instantiated only once (per `Server`).

**Comment by gregw** [comment]
@sbordet probably no great need, but some setups do have multiple instances and it can waste a lot of threads if each has it's own timer.

I've done a general cleanup of the class, but the fact that it still uses Timer rather than ScheduledExecutorService indicates that it still needs more of an update.

For now I have removed the duplication of zones and the assumption that nobody will ever change the system clock by more than 24hours
