### ISSUE TITLE
PreconfigureQuickStartWar not executable

### ISSUE THREAD

**Issue by SchulteMarkus** [eclipse/jetty.project#1543]
Hi,

I want my Jetty to use Quickstart, as described [here](https://www.eclipse.org/jetty/documentation/9.4.x/quickstart-webapp.html).

When trying to pre-generate quickstart-web.xml, I am running into following exception.

```
jetty-distribution-9.4.5.v20170502 $ java -cp "lib/*" org.eclipse.jetty.quickstart.PreconfigureQuickStartWar webapps/ROOT.war
2017-05-11 13:16:53.771:INFO::main: Logging initialized @118ms to org.eclipse.jetty.util.log.StdErrLog
2017-05-11 13:16:53.890:INFO:oejs.Server:main: jetty-9.4.5.v20170502
Exception in thread "main" java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider org.eclipse.jetty.cdi.websocket.WebSocketCdiInitializer not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.getNonExcludedInitializers(AnnotationConfiguration.java:788)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:361)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1458)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.quickstart.QuickStartWebApp.doStart(QuickStartWebApp.java:201)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.quickstart.PreconfigureQuickStartWar.preconfigure(PreconfigureQuickStartWar.java:114)
	at org.eclipse.jetty.quickstart.PreconfigureQuickStartWar.main(PreconfigureQuickStartWar.java:78)
```

In this case, ROOT.war is a war, which seems to be fine. Starting Jetty with this ROOT.war serves my application. But in fact, ROOT.war does not even have to exist for this error to occur.

**Steps to reproduce**

- Download latest Jetty 9.4.5 from https://www.eclipse.org/jetty/download.html
- From Quickstart-documentation, follow "Setting up Quickstart"
- From Quickstart-documentation, follow "Pre-generating the quickstart-web.xml file"
-- `java -cp "lib/*" org.eclipse.jetty.quickstart.PreconfigureQuickStartWar webapps/ROOT.war`
-- For the error to occur, ROOT.war does even not have to exist

**Comment by janbartel** [comment]
@SchulteMarkus what is in "lib/"? If it is $JETTY_HOME/lib, then you've probably included too many extraneous jars, including some for websocket-cdi integration.

**Comment by SchulteMarkus** [comment]
You are right, it is $JETTY_HOME/lib. Do you know a cp-pattern to use instead?

**Comment by janbartel** [comment]
@SchulteMarkus not really because it depends on what parts of jetty you have configured for your particular application. You can try going to your $JETTY_BASE dir and doing:

```java -jar $JETTY_HOME/start.jar --dry-run```

That will print out the classpath that your jetty base is configured to use, and so you should be able to use a similar one to pregenerate your quickstart.

By coincidence I opened issue #1542  today. Would something like that be of interest to you?

**Comment by SchulteMarkus** [comment]
#1542 nice idea, this would make my life easier. Using https://www.eclipse.org/jetty/documentation/9.4.x/jetty-maven-plugin.html#jetty-effective-web-xml is of course already possible, but no fun to include while building the war.

I will give your suggestion "You can try going..." a try, and reopen here, if it does not help. Thank you!
