### ISSUE TITLE
ServletContext is not reset/cleared between stop/start

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1566]
If a server with websockets is stopped, it cannot be restarted!   For example if you use the `demo-base` from the distribution and create an `etc/jetty-startstop.xml` file that contains:
```xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <Call name="start"/>
  <Call name="stop"/>
</Configure>
```
then if you run `java -jar ../start.jar etc/jetty-startstop.xml` you get the following exception on the second start (done by `XmlConfiguration`):
```
2017-05-22 19:33:16.380:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@370736d9{/,file:///home/gregw/src/jetty-9.3.x/jetty-distribution/target/distribution/demo-base/webapps/ROOT/,UNAVAILABLE}{/ROOT}
javax.servlet.ServletException: org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter is defined twice for the same context attribute key 'org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter'.  Make sure you have different init-param 'contextAttributeKey' values set
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.setToAttribute(WebSocketUpgradeFilter.java:392)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.init(WebSocketUpgradeFilter.java:366)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:139)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:873)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1516)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1441)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:215)
	at org.eclipse.jetty.start.Main.start(Main.java:458)
	at org.eclipse.jetty.start.Main.main(Main.java:76)
```

**Comment by gregw** [comment]
@joakime this is a moderate priority for me as it is blocking some work I'm doing on quickstart.

**Comment by joakime** [comment]
The attributes in the ServletContext are not cleaned out on undeploy?

**Comment by joakime** [comment]
I would have expected the WebAppContext.stop() to clear out the ServletContext, or at least have the WebAppContext.start() initialize a fresh/empty ServletContext before the Configurations are run.

**Comment by gregw** [comment]
Don't know sorry - just know that if I call start, stop, start on the demo base I get the exception above. 

Note that there are two maps of attributes for a context. Those added via the  programmatic API directly to our ContextHandler (or extension) and a second map for those added via the ServletContext API.  The former are not reset over stop/start but the later are.

**Comment by joakime** [comment]
The WebSocketUpgradeFilter.destroy() cannot remove the configuration from the ServletContext attributes itself, as there is no ServletContext at that point in time.   The expectation is that the ServletContext itself is cleaned out and reset between stop/start.

**Comment by joakime** [comment]
We do have a testcase for this scenario.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.5.v20170502/jetty-websocket/websocket-server/src/test/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeFilterTest.java#L324-L363

That sets up WebSocketUpgradeFilter using a bunch of different techniques, verifies that it works, and then performs stop/start on the handler (WebSocketContext or ServletContextHandler) and verifies that it works again.

**Comment by gregw** [comment]
Can you reproduce with `demo-base` and the XML ?

**Comment by joakime** [comment]
No error using the `jetty-distribution-9.4.5.v20170502` tarball.

```
[demo-base]$ java -jar ../start.jar etc/startstop.xml
2017-05-22 17:55:37.001:INFO::main: Logging initialized @1064ms to org.eclipse.jetty.util.log.StdErrLog
2017-05-22 17:55:37.284:WARN::main: demo test-realm is deployed. DO NOT USE IN PRODUCTION!
2017-05-22 17:55:37.291:INFO:oejs.Server:main: jetty-9.4.5.v20170502
2017-05-22 17:55:37.337:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///mnt/c/code/jetty/distros/jetty-distribution-9.4.5.v20170502/demo-base/webapps/] at interval 1
...(snip)...
2017-05-22 17:55:44.966:INFO:oejs.session:main: Scavenging every 660000ms
2017-05-22 17:55:44.968:INFO:oejs.AbstractConnector:main: Started ServerConnector@2dc9b0f5{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-05-22 17:55:44.970:INFO:oejus.SslContextFactory:main: x509=X509@6ca0256d(jetty,h=[jetty.eclipse.org],w=[]) for SslContextFactory@3eb91815(file:///mnt/c/code/jetty/distros/jetty-distribution-9.4.5.v20170502/demo-base/etc/keystore,file:///mnt/c/code/jetty/distros/jetty-distribution-9.4.5.v20170502/demo-base/etc/keystore)
2017-05-22 17:55:44.971:INFO:oejus.SslContextFactory:main: x509=X509@5ef0d29e(mykey,h=[],w=[]) for SslContextFactory@3eb91815(file:///mnt/c/code/jetty/distros/jetty-distribution-9.4.5.v20170502/demo-base/etc/keystore,file:///mnt/c/code/jetty/distros/jetty-distribution-9.4.5.v20170502/demo-base/etc/keystore)
2017-05-22 17:55:44.972:INFO:oejs.AbstractConnector:main: Started ServerConnector@43015c69{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2017-05-22 17:55:44.972:INFO:oejs.Server:main: Started @9036ms
```

**Comment by joakime** [comment]
BTW, I notice that this technique, using the `etc/startstop.xml` does start/stop each of the deployables 4 times (according to the output)

**Comment by joakime** [comment]
Interesting, there are 2 Server instances doing it this way. each one of those server instances with a start/stop of each of the deployables.

```
2017-05-22 17:59:10.368:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@648c94da{/test,null,UNAVAILABLE}{/test.war}
2017-05-22 17:59:10.372:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@5812f68b{/doc,null,UNAVAILABLE}{/doc}
2017-05-22 17:59:10.396:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@20f5281c{/proxy,null,UNAVAILABLE}{/xref-proxy.war}
2017-05-22 17:59:10.419:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@4816278d{/async-rest,null,UNAVAILABLE}{/async-rest.war}
2017-05-22 17:59:10.426:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@6a47b187{/,null,UNAVAILABLE}{/ROOT}
2017-05-22 17:59:10.427:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.s.h.MovedContextHandler@275bf9b3{/oldContextPath,null,UNAVAILABLE}
2017-05-22 17:59:10.451:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@544d57e{/test-jaas,null,UNAVAILABLE}{/test-jaas.war}
2017-05-22 17:59:10.475:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@4f4c4b1a{/test-jndi,null,UNAVAILABLE}{/test-jndi.war}
2017-05-22 17:59:10.512:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@d23e042{/test-spec,null,UNAVAILABLE}{/test-spec.war}
2017-05-22 17:59:10.514:INFO:oejsh.ManagedAttributeListener:Thread-0: update PushFilter org.eclipse.jetty.servlets.PushCacheFilter@5b7ea70d->null on o.e.j.w.WebAppContext@33065d67{/test,file:///tmp/jetty-0.0.0.0-8080-test.war-_test-any-6173122172720818602.dir/webapp/,UNAVAILABLE}{/test.war}
2017-05-22 17:59:10.515:INFO:oejsh.ManagedAttributeListener:Thread-0: update QoSFilter org.eclipse.jetty.servlets.QoSFilter@24d4d7c9->null on o.e.j.w.WebAppContext@33065d67{/test,file:///tmp/jetty-0.0.0.0-8080-test.war-_test-any-6173122172720818602.dir/webapp/,UNAVAILABLE}{/test.war}
2017-05-22 17:59:10.581:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@33065d67{/test,null,UNAVAILABLE}{/test.war}
2017-05-22 17:59:10.586:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@6574a52c{/doc,null,UNAVAILABLE}{/doc}
2017-05-22 17:59:10.605:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@a3d8174{/proxy,null,UNAVAILABLE}{/xref-proxy.war}
2017-05-22 17:59:10.622:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@68e965f5{/async-rest,null,UNAVAILABLE}{/async-rest.war}
2017-05-22 17:59:10.627:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@15ca7889{/,null,UNAVAILABLE}{/ROOT}
2017-05-22 17:59:10.627:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.s.h.MovedContextHandler@5f8edcc5{/oldContextPath,null,UNAVAILABLE}
2017-05-22 17:59:10.645:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@63475ace{/test-jaas,null,UNAVAILABLE}{/test-jaas.war}
2017-05-22 17:59:10.661:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@59e5ddf{/test-jndi,null,UNAVAILABLE}{/test-jndi.war}
```

One server has 2 connectors, the other has no connectors !?

**Comment by joakime** [comment]
@gregw i don't think your `etc/startstop.xml` is a valid test scenario.

**Comment by joakime** [comment]
On windows, this `etc/startstop.xml` scenario is also invalid as the temp directory contents cannot be deleted between the first stop/start.

```
2017-05-22 11:05:07.157:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@61d6015a{/test-jaas,file:///C:/Users/joakim/AppData/Local/Temp/jetty-0.0.0.0-8080-test-jaas.war-_test-jaas-any-1906976940619894765.dir/webapp/,AVAILABLE}{C:\code\jetty\distros\jetty-distribution-9.4.5.v20170502\demo-base\webapps/test-jaas.war}
2017-05-22 11:05:07.161:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5fd4f8f5{/proxy,null,UNAVAILABLE}{C:\code\jetty\distros\jetty-distribution-9.4.5.v20170502\demo-base\webapps\xref-proxy.war}
java.lang.IllegalStateException: Failed to delete temp dir C:\Users\joakim\AppData\Local\Temp\jetty-0.0.0.0-8080-xref-proxy.war-_xref-proxy-any-3214235503573190004.dir
        at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:376)
        at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:264)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:452)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:419)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1511)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1438)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1437)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
        at org.eclipse.jetty.start.Main.start(Main.java:499)
        at org.eclipse.jetty.start.Main.main(Main.java:78)
2017-05-22 11:05:07.200:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=21ms
```

**Comment by joakime** [comment]
If we allow the startup with the 2 Servers, but also enable jmx, then the JMX MBean tree does not report 2 servers, it only sees 1.

Thread dump only shows 1 Server too, along with 1 qtp pool.
However, the stop shows 2 thread ids during stop, with the same stop information repeated twice in the logs under two different thread ids (and with different webapp hashcode() values).

Hmmm.  Curiouser and curiouser ...

**Comment by gregw** [comment]
I have found a bug in XmlConfiguration where it does call start too many times on the server.
I agree the xml is a little contrived, but doing such things can be useful for testing configuration, generating start.jar.

Note that I'm in 9.3, so it may not be an issue in 9.4, so that is probably fine.

**Comment by joakime** [comment]
Closing, unable to replicate (though it did spark a different bug)
