### ISSUE TITLE
NPE in Quoted Quality CSV

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1579]
```stack
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:207)
at java.lang.StringBuffer.setLength(StringBuffer.java:192)
at org.eclipse.jetty.http.QuotedQualityCSV.parsedParam(QuotedQualityCSV.java:138)
at org.eclipse.jetty.http.QuotedCSV.addValue(QuotedCSV.java:156)
at org.eclipse.jetty.http.QuotedQualityCSV.addValue(QuotedQualityCSV.java:102)
at org.eclipse.jetty.http.HttpFields.getQualityCSV(HttpFields.java:441)
at org.eclipse.jetty.server.handler.ErrorHandler.getAcceptableWriter(ErrorHandler.java:199)
at org.eclipse.jetty.server.handler.ErrorHandler.generateAcceptableResponse(ErrorHandler.java:246)
at org.eclipse.jetty.server.handler.ErrorHandler.generateAcceptableResponse(ErrorHandler.java:170)
at org.eclipse.jetty.server.handler.ErrorHandler.doError(ErrorHandler.java:142)
at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:78)
at org.eclipse.jetty.server.Response.sendError(Response.java:655)
at org.eclipse.jetty.server.Response.sendError(Response.java:590)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:418)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
at java.lang.Thread.run(Thread.java:745)
Suppressed: java.lang.IllegalStateException: s=COMPLETING i=false a=NOT_ASYNC
at org.eclipse.jetty.server.HttpChannelState.onError(HttpChannelState.java:769)
at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:522)
at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:463)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:458)
```

**Comment by gregw** [comment]
There were several problems with bad partial values like `q=1` and `x;=1`.  
Also fixed handling of missing qualities
