### ISSUE TITLE
java.lang.IllegalArgumentException: setContentLength(0) when already written 1232

### ISSUE THREAD

**Issue by thomashunziker** [eclipse/jetty.project#1601]
I am using the version `9.4.4.v20170414` of Jetty. I see in the log the following error:

````
java.lang.IllegalArgumentException: setContentLength(0) when already written 1232
	at org.eclipse.jetty.server.Response.setContentLength(Response.java:1007)
	at javax.servlet.ServletResponseWrapper.setContentLength(ServletResponseWrapper.java:161)
	at javax.servlet.http.NoBodyResponse.setContentLength(HttpServlet.java:830)
	at javax.servlet.http.NoBodyResponse.setContentLength(HttpServlet.java:824)
	at javax.servlet.http.HttpServlet.doHead(HttpServlet.java:289)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:704)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at io.company.framework.core.api.util.main.filter.SessionFilter.doFilter(SessionFilter.java:36)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at io.company.framework.core.api.util.main.filter.LanguageHandlerFilter.doFilter(LanguageHandlerFilter.java:46)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at io.company.framework.core.api.util.main.filter.ErrorHandlerFilter.doFilter(ErrorHandlerFilter.java:56)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at io.company.framework.core.api.util.main.filter.CloseForwardedConnectionsFilter.doFilter(CloseForwardedConnectionsFilter.java:77)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at io.company.framework.core.api.util.main.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:79)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:454)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:278)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:148)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
````
It seems as this is a GET request. The headers of the request:
````
CF-IPCountry: US
CF-RAY: 3641b8327d8e7924-LAX
Connection: keep-alive
X-Forwarded-Proto: https
User-Agent: Mozilla/5.0 (compatible; Uptimebot/1.0; +http://www.uptime.com/uptimebot)
Referer: http://uptime.com/
X-Forwarded-For: 199.58.164.122
Host: xxxxxxxxxx.com
CF-Visitor: { \"scheme\":\"https\"}
Accept-Encoding: gzip
CF-Connecting-IP: 199.58.164.122
````

I have also posted the error here: https://github.com/eclipse/jetty.project/issues/1184
I do not believe it is exactly the same issue since I'm using a version which contains the fix.

I'm not able to reproduce this locally. I see the error only the production environment. When I send the request locally I do not get the above error. And as such I assume it has something to do with how the connection opened or closed. 

Has someone any idea how I can resolve this exception?

Regards,
Thomas

**Comment by joakime** [comment]
Closing this one, reopening #1184
