### ISSUE TITLE
Websocket JSR356 implementation doesn't call @OnClose method in case of a exception from @OnPongMessage and simply closes the conneciton.

### ISSUE THREAD

**Issue by anuraggupta** [eclipse/jetty.project#1626]
Sometimes the client doesn't send anything in the pong message and an exception is generated. 
After this exception the @OnError method is called and the websocket is closed, but the @OnClose method is skipped.

```
java.lang.UnsupportedOperationException 
at java.nio.ByteBuffer.array(ByteBuffer.java:994) ~[?:1.8.0_92] 
at com.adobe.ans.service.impl.WebsocketNotificationService.onPongMessage(WebsocketNotificationService.java:259) ~[classes/:?] 
at sun.reflect.GeneratedMethodAccessor1441.invoke(Unknown Source) ~[?:?] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92] 
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92] 
at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71) ~[websocket-common-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.jsr356.annotations.OnMessagePongCallable.call(OnMessagePongCallable.java:53) ~[javax-websocket-client-impl-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callPong(JsrEvents.java:180) ~[javax-websocket-client-impl-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onPing(JsrAnnotatedEventDriver.java:264) ~[javax-websocket-client-impl-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:142) [websocket-common-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:375) [websocket-common-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) [websocket-common-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [websocket-common-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256) [websocket-common-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679) [websocket-common-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511) [websocket-common-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.3.v20170317.jar:9.4.3.v20170317] 
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.3.v20170317.jar:9.4.3.v20170317] 
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by joakime** [comment]
onClose is for normal handshake close (one where the remote sent a response code)
onError is for closure based on error.

**Comment by lachlan-roberts** [comment]
I don't think there is anything to do here.

Looks like the 9.4.x code has been changed so this exception will now call `onError` and then `onClose` like the OP expected. Jetty-10 also has the correct behavior by notifying `onError` and then `onClose`.
