### ISSUE TITLE
Request with previous 100-continue and no content is going through

### ISSUE THREAD

**Issue by Sytten** [eclipse/jetty.project#1654]
Hi,
We decided to migrate our services from Jetty 9.3 to Jetty 9.4 (with Dropwizard) lately.
We have a SOAP Api that is crucial for the application. We receive that from a provider (we don't control the messages).
The way they work is they send first a TCP Segment (after the three way handshake) looking like that:
```
0000   06 68 e6 7e cc 04 06 75 0d 98 0e af 08 00 45 00  .h.~...u......E.
0010   01 35 19 5b 40 00 ff 06 48 e8 0a 00 00 1c 0a 00  .5.[@...H.......
0020   04 64 56 c5 00 50 0b dd ac 29 86 cb 36 64 80 18  .dV..P...)..6d..
0030   00 6a 03 ba 00 00 01 01 08 0a 0a 05 bd 67 09 f8  .j...........g..
0040   b9 d9 50 4f 53 54 20 2f 73 6f 61 70 2f 73 65 72  ..POST /soap/ser
0050   76 69 63 65 31 20 48 54 54 50 2f 31 2e 31 0d 0a  vice1 HTTP/1.1..
0060   68 6f 73 74 3a 20 31 30 2e 30 2e 32 30 2e 34 0d  host: 10.0.20.4.
0070   0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74  .Content-Type: t
0080   65 78 74 2f 78 6d 6c 3b 63 68 61 72 73 65 74 3d  ext/xml;charset=
0090   75 74 66 2d 38 0d 0a 53 4f 41 50 41 63 74 69 6f  utf-8..SOAPActio
00a0   6e 3a 20 22 68 74 74 70 3a 2f 2f 74 65 6d 70 75  n: "http://tempu
00b0   72 69 2e 6f 72 67 2f 47 65 74 54 72 61 6e 73 61  ri.org/GetTransa
00c0   63 74 69 6f 6e 22 0d 0a 58 2d 46 6f 72 77 61 72  ction"..X-Forwar
00d0   64 65 64 2d 46 6f 72 3a 20 31 30 2e 30 2e 34 2e  ded-For: 10.0.4.
00e0   32 36 0d 0a 58 2d 46 6f 72 77 61 72 64 65 64 2d  26..X-Forwarded-
00f0   50 6f 72 74 3a 20 38 30 0d 0a 58 2d 46 6f 72 77  Port: 80..X-Forw
0100   61 72 64 65 64 2d 50 72 6f 74 6f 3a 20 68 74 74  arded-Proto: htt
0110   70 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74  p..Content-Lengt
0120   68 3a 20 32 32 32 35 0d 0a 43 6f 6e 6e 65 63 74  h: 2225..Connect
0130   69 6f 6e 3a 20 6b 65 65 70 2d 61 6c 69 76 65 0d  ion: keep-alive.
0140   0a 0d 0a                                         ...
```
Then we receive the xml content in another segment after that.

It runs smooth most of the time, but we started to have weird connections problems 1 to 4 times a day.
I investigated and found out that Jetty is sometime sending a FIN between the first Segment (has shown above) and the segment containing the data. Totally ignoring the Keep-alive (even if it should not be needed since we use http 1.1). Our provider doesn't like that and sends us a RST which generates a bunch of errors. I should say that we never receive a close connection and it's always our service who kills it if it has not been used for a while.

I will continue to investigate (mostly enabling DEBUG logs) and I will post here more information when I have some, but if you have an idea why it might cause that it would be appreciated.
Thanks!

**Comment by joakime** [comment]
HTTP spec on persistent connections is rather clear here.

The client can only request a persistent connection (you call it Keep-Alive).

The server and any intermediary (proxies, load balancers, gateways, etc) are the ones in control of persistent connections and can close the connection at any time for their own reasons.

If you have a client that expects to be control, then that client is not following the HTTP spec.
It will have problems with many components on the public internet, not just Jetty.

**Comment by joakime** [comment]
`Connection: Keep-Alive` is meaningless on HTTP/1.1

The `Connection` header in HTTP/1.1 will see `Keep-Alive` as a value not present in the HTTP/1.1 spec and ignore it for its own HTTP handling. 

The value `Keep-Alive` is only present in the HTTP/1.0 spec.

Having non HTTP spec values in the `Connection` header is common when you think about the components after HTTP that can use the header for its own purposes: such as HTTP/2's 'h2c' upgrade, websocket upgrade, etc.

**Comment by joakime** [comment]
You seem to be using a proxy / load balancer in front of Jetty (the existence of the various older `X-Forwarded` headers).  Make sure you are using an up to date version of that proxy / load balancer (as it might not be behaving properly too)

> With Jetty 9.4+, consider using the `Forward` header outlined in https://tools.ietf.org/html/rfc7239

**Comment by Sytten** [comment]
Thanks for the comments. 
We are looking at our proxies too right now, we do have a complex architecture in front of jetty.
I can't reproduce on local and it rarely appears in production, that's why it's difficult to fix.
Still I'm not sure why Jetty sends a FIN milliseconds after the three way handshake and a TCP fragment.

**Comment by Sytten** [comment]
Ok I have more news.
I reverted to jetty 8 to see what is happening. 
After a tcpdump, I saw that the problem isn't new, it's just that jetty 9 handles it differently.
Before it used to return a 400 bad request before hitting my custom AbstractPhaseInterceptor<Message> (which reads the input stream to remove invalid strings from the received SOAP message).
I will see with my provider to fix the problem on their side, but is it possible to get the old behavior back too?

**Comment by Sytten** [comment]
More news today, I realized that the 400 comes from our Haproxy.
Still jetty 9.3 seems to silence the problem, but with 9.4 it goes through and fails later in the CXF filters.
Not sure it is a jetty, jersey or dropwizard problem.
@joakime if you have any hint for that I would be very glad.

**Comment by olamy** [comment]
Hi
Any sample project to help us reproduce your problem?

**Comment by Sytten** [comment]
![screen shot 2017-07-04 at 10 31 02 am](https://user-images.githubusercontent.com/2366731/27821835-f0140bf8-60a3-11e7-9f34-c8efb58dd3c5.png)
10.0.4.26 is the client
10.0.0.28 is my server

Hard for me to provide a sample project (enterprise project), but here is a stacktrace:
```
[2017-07-03 16:43:36.020] [qtp2009196049-47] WARN  i.p.t.servlets.InvalidStringHandler - Failed to read message's content. Resetting stream.
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:749)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:152)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2369)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2348)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2325)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2273)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1041)
	at io.pleo.titan.servlets.InvalidStringHandler.handleMessage(InvalidStringHandler.java:41)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:257)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:220)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1128)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1062)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
	at org.eclipse.jetty.server.Server.handle(Server.java:507)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:237)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:240)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:93)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceRun.produceAndRun(ExecuteProduceRun.java:191)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceRun.run(ExecuteProduceRun.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:641)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:559)
	at java.lang.Thread.run(Thread.java:748)
```

InvalidStringHandler is an AbstractPhaseInterceptor.
For now what I think I will do is read the InputStream inside a ContainerRequestFilter and if I get an EOF there, forbid the request from going through.

**Comment by sbordet** [comment]
You don't show what frame 188664 contains.

I expect that to be a HTTP request with an `Expect: 100-continue` and a `Content-Length` header.
The server replies correctly with a `100 Continue` response (because the application asked to read the content), but then the client sends a FIN at frame 188668.

It's a client problem.

**Comment by Sytten** [comment]
I updated the stacktrace, it wasn't the right one. 
It's certainly a client error, but it used to be silenced on the server side.
The behavior changed and that's why I'm trying to find solution to avoid having a EOF down the line.

**Comment by sbordet** [comment]
I don't understand what you mean by "silenced". If the client did not send the content, the server application would have seen the EOF, no matter the Jetty version.

**Comment by Sytten** [comment]
I totally agree, but we never experienced to error before with jersey 1 (based on jetty 9.3).
Meaning something "catch" it before it entered our pipeline.
I want this behavior back since I cannot fix the client in the short term (it's an external provider).
I will create a servlet filter and read the input stream, if I can catch the error there and silence it, I will be able to roll out my version without spamming the logs.

**Comment by Sytten** [comment]
Finally I decided to silence the error in my AbstractPhaseInterceptor until the client is fixed, I will still get a warning from apache CFX but thats not too bad.

I would say it's done on my part, but I find it strange that the behavior changed. Not sure which way is the best though.

Feel free to close the issue ;)
Thanks
