### ISSUE TITLE
Update ALPN support for Java 8u141

### ISSUE THREAD

**Issue by we3geeks** [eclipse/jetty.project#1685]
After updating to latest Java 8 JDK (released 2017-07-18), it looks like ALPN needs to be updated:

```
$ java -jar ~/opt/jetty/start.jar
java.lang.IllegalStateException: Cannot read file: modules/alpn-impl/alpn-1.8.0_141.mod
	at org.eclipse.jetty.start.Modules.registerModule(Modules.java:200)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:353)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:358)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:375)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:284)
	at org.eclipse.jetty.start.Main.processCommandLine(Main.java:324)
	at org.eclipse.jetty.start.Main.main(Main.java:76)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

**Comment by olamy** [comment]
see #1686.
@we3geeks   feel free to use the file in the pr.
