### ISSUE TITLE
StringIndexOutOfBoundsException when calling httpReq.getLocale() 

### ISSUE THREAD

**Issue by karussell** [eclipse/jetty.project#1697]
There is some problem in jetty for a certain locale:

```
2017-07-28 03:15:28,143 [qtp464064894-1142] WARN  org.eclipse.jetty.server.HttpChannel - /route
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.StringBuffer.charAt(StringBuffer.java:204)
        at org.eclipse.jetty.http.QuotedQualityCSV.parsedParam(QuotedQualityCSV.java:104)
        at org.eclipse.jetty.http.QuotedCSV.addValue(QuotedCSV.java:156)
        at org.eclipse.jetty.http.QuotedQualityCSV.addValue(QuotedQualityCSV.java:88)
        at org.eclipse.jetty.http.HttpFields.getQualityCSV(HttpFields.java:441)
        at org.eclipse.jetty.server.Request.getLocale(Request.java:857)
        at javax.servlet.ServletRequestWrapper.getLocale(ServletRequestWrapper.java:311)
        at javax.servlet.ServletRequestWrapper.getLocale(ServletRequestWrapper.java:311)
        at com.graphhopper.http.GraphHopperServlet.doGet(GraphHopperServlet.java:149)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
```

This might be [this code line](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedQualityCSV.java#L113) in jetty for an empty buffer:

```java
   protected void parsedParam(StringBuffer buffer, int valueLength, int paramName, int paramValue)
    {
        if (paramName<0)
        {
            if (buffer.charAt(buffer.length()-1)==';')
                buffer.setLength(buffer.length()-1);
}
```

See https://github.com/graphhopper/graphhopper/issues/1118 where we are using jetty 9.4.2.v20170220

**Comment by karussell** [comment]
Sorry for the hassle, seems like a duplicate of #1577
