### ISSUE TITLE
Accept "Kerberos v5" OID for SPNego handshake

### ISSUE THREAD

**Issue by joshelser** [eclipse/jetty.project#1708]
Another peculiar SPENGO related issue I've stumbled across.

Accessing a SPENGO-authenticated, Jetty endpoint behind an IIS-based reverse-proxy, I encountered an error stating that Jetty was unable to authenticate the client with an error similar to the following:

```
2017-08-03 19:09:29,440 WARN org.apache.phoenix.shaded.org.eclipse.jetty.security.SpnegoLoginService:
GSSException: No credential found for: 1.2.840.113554.1.2.2 usage: Accept
        at sun.security.jgss.GSSCredentialImpl.getElement(GSSCredentialImpl.java:600)
        at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:317)
        at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:285)
        at org.apache.phoenix.shaded.org.eclipse.jetty.security.SpnegoLoginService.login(SpnegoLoginService.java:137)
        at org.apache.phoenix.shaded.org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:61)
        at org.apache.phoenix.shaded.org.eclipse.jetty.security.authentication.SpnegoAuthenticator.validateRequest(SpnegoAuthenticator.java:99)
        at org.apache.calcite.avatica.server.AvaticaSpnegoAuthenticator.validateRequest(AvaticaSpnegoAuthenticator.java:43)
        at org.apache.phoenix.shaded.org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:512)
        at org.apache.phoenix.shaded.org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.apache.phoenix.shaded.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.apache.phoenix.shaded.org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.apache.phoenix.shaded.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.apache.phoenix.shaded.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.apache.phoenix.shaded.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.apache.phoenix.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.apache.phoenix.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
```

Reading https://msdn.microsoft.com/en-us/library/ms995330.aspx (as well as inspecting the raw HTTP requests via TCP), I can see that IIS is, indeed, sending the response to the WWW-Authenticate challenge (via `Authorization: Negotiate <token>`) that _only_ includes the Kerberos v2 OID and data. When I contrast this to what Apache Commons HttpClient does, I see that their implementation provides both the SPNEGO OID and the Kerberos v5 OID (and data for both).

At this point, I'm still not entirely sure what the SPNEGO OID actually means -- best as I can tell it just means to "negotiate" without being specific on the actual mechanism. However, for Jetty's SPENGO code to explicitly not list the Kerberos v5 OID in the SpnegoLoginService means that clients must *always* include the SPNEGO OID.

After doing some more searching, I did find some [other code](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/server/security/SpnegoFilter.java#L113-L114) which gives some credence to allowing both OIDs. Monkey-patching this myself and re-running the test with IIS allows the service to immediately connect successfully.

I'll put a pull-request shortly with the changes I'm suggesting.

**Comment by sbordet** [comment]
Done in #2868.
