### ISSUE TITLE
exception reported in SessionEvictionFailureTest

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1714]
An AIOOBE is reported during a successful run of SessionEvictionFailureTest

```
[INFO] Running org.eclipse.jetty.server.session.SessionEvictionFailureTest
2017-08-08 11:03:16.478:WARN:oejsh.ContextHandler:main: Empty contextPath
2017-08-08 11:03:16.480:INFO:oejs.Server:main: jetty-9.4.7-SNAPSHOT
2017-08-08 11:03:16.481:INFO:oejs.session:main: DefaultSessionIdManager workerName=w14
2017-08-08 11:03:16.481:INFO:oejs.session:main: Scavenging every 20000ms
2017-08-08 11:03:16.481:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@44fb6ebd{/,null,AVAILABLE}
2017-08-08 11:03:16.482:INFO:oejs.AbstractConnector:main: Started ServerConnector@7e27f603{HTTP/1.1,[http/1.1]}{0.0.0.0:41717}
2017-08-08 11:03:16.482:INFO:oejs.Server:main: Started @17512ms
2017-08-08 11:03:21.486:WARN:oejs.session:Scheduler-1571125860: Passivation of idle session w14p7f9yw2wepn0kd3a76m2r85q15 failed java.lang.IllegalStateException: Testing store
2017-08-08 11:03:28.490:WARN:oejs.session:Scheduler-1571125860: Passivation of idle session w14p7f9yw2wepn0kd3a76m2r85q15 failed java.lang.IllegalStateException: Testing store
2017-08-08 11:03:30.497:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@7e27f603{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2017-08-08 11:03:30.497:WARN:oejs.session:main: 
java.lang.ArrayIndexOutOfBoundsException: 5
	at org.eclipse.jetty.server.session.SessionEvictionFailureTest$MockSessionDataStore.doStore(SessionEvictionFailureTest.java:112)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.store(AbstractSessionDataStore.java:103)
	at org.eclipse.jetty.server.session.DefaultSessionCache.shutdown(DefaultSessionCache.java:162)
	at org.eclipse.jetty.server.session.SessionHandler.shutdownSessions(SessionHandler.java:994)
	at org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:514)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
	at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:863)
	at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:355)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:927)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:271)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:142)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:160)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
	at org.eclipse.jetty.server.Server.doStop(Server.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.server.session.TestServer.stop(TestServer.java:128)
	at org.eclipse.jetty.server.session.SessionEvictionFailureTest.testEvictFailure(SessionEvictionFailureTest.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
2017-08-08 11:03:30.498:INFO:oejsh.ContextHandler:main: Stopped o.e.j.s.ServletContextHandler@44fb6ebd{/,null,UNAVAILABLE}
2017-08-08 11:03:30.498:INFO:oejs.session:main: Stopped scavenging
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.022 s - in org.eclipse.jetty.server.session.SessionEvictionFailureTest
```

**Comment by janbartel** [comment]
Fixed for jetty-9.4.7 and beyond.
