### ISSUE TITLE
Document session setup in jetty-web.xml for jetty-9.4

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#1716]
In jetty-9.4, there is no need to configure anything in any jetty xml file - not jetty.xml nor context xml nor jetty-web.xml as all config can be done by enabling the desired session management module and editing the related start.d .ini file as desired.

However, we should document how you could go about putting explicit configuration into a context xml file or a  jetty-web.xml file if you wanted to. We documented that for jetty-9.3, so we should do the same for jetty-9.4.

Here's an example of how you would setup the FileSessionDataStore, but the same concept would apply to any of the *SessionDataStores:

```xml
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Call id="sh" name="getSessionHandler">
    <Set name="sessionCache">
      <New class="org.eclipse.jetty.server.session.DefaultSessionCache">
        <Arg><Ref id="sh"/></Arg>
        <Set name="sessionDataStore">
           <New class="org.eclipse.jetty.server.session.FileSessionDataStore">
             <Set name="storeDir">/tmp/sessions</Set>
           </New>
        </Set>
      </New>
    </Set>
  </Call>
</Configure>
```
Note that the above snipped works the same in either a context xml file or a jetty-web.xml file.

Note also that by explicitly setting the SessionCache and SessionDataStore for a SessionHandler, any session modules you already have enabled are ignored. So, for example, if you had enabled the session-store-gcloud module, you could force a particular webapp to use say the FileSessionDataStore by explicitly configuring it in either a context xml file or a jetty-web.xml file  as shown above.

**Comment by gregw** [comment]
Note also the update I just did in #1715 to make the server and more properties available in `jetty-web.xml`.

**Comment by neo-expert** [comment]
I am getting the following error with configuration mentioned above:

```
java.lang.IllegalStateException: No suitable constructor: <New class="org.eclipse.jetty.server.session.DefaultSessionCache"><Arg><Ref id="sh"/></Arg><Set name="sessionDataStore">|           <New class="org.eclipse.jetty.server.session.FileSessionDataStore"><Set name="storeDir">/tmp/sessions</Set></New>|        </Set></New> on org.eclipse.jetty.server.session.SessionHandler2094411587==dftMaxIdleSec=-1
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:864)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1305)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1210)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:517)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:462)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:801)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:351)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:296)
	at org.eclipse.jetty.webapp.JettyWebXmlConfiguration.lambda$configure$0(JettyWebXmlConfiguration.java:95)
	at org.eclipse.jetty.webapp.WebAppClassLoader.runWithServerClassAccess(WebAppClassLoader.java:160)
	at org.eclipse.jetty.webapp.JettyWebXmlConfiguration.configure(JettyWebXmlConfiguration.java:95)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1472)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:530)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:571)

```

**Comment by janbartel** [comment]
@neo-expert  I can't reproduce this problem on the info you've supplied.

I deduced that you are using the jetty-runner - next time please report the way that you're running jetty, plus the version of jetty and version of java, and include any  (sanitized) xml files that you have modified.

**Comment by neo-expert** [comment]
I created an repositority for this:
https://github.com/neo-expert/jetty-issue

**Comment by janbartel** [comment]
@neo-expert  the problem is that your webapp  puts a bunch of jetty jars into its WEB-INF/lib. They shouldn't be there, they are inside the jetty-runner jar. If you remove your dependency on jetty-server from the pom (and make your servlet-api dependency scope=provided as well) it will be fine.

**Comment by neo-expert** [comment]
Thank you very much, you made my day today. I was working the whole day on this issue :-D

**Comment by jrAtAustin** [comment]
I am getting the following error trying to use the Cloudbees jerry-reds session manager.

`2019-12-28 17:09:59.634:WARN:oejx.XmlConfiguration:main: Config error at <Call name="addBean"><Arg>|          <New id="sessionDataStoreFactory" class="com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory"><Set name="jedisPool">|                  <Ref refid="jedisPool"/>|              </Set></New>|      </Arg></Call> java.lang.ClassNotFoundException: com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory in file:/Users/user/bin/jetty.xml
java.lang.ClassNotFoundException: com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:65)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:834)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1309)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1214)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$500(XmlConfiguration.java:326)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$AttrOrElementNode.getList(XmlConfiguration.java:1442)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$AttrOrElementNode.getList(XmlConfiguration.java:1417)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:780)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:472)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:354)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:297)
	at org.eclipse.jetty.runner.Runner.configure(Runner.java:329)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:570)
Usage: java [-Djetty.home=dir] -jar jetty-runner.jar [--help|--version] [ server opts] [[ context opts] context ...] 
Server opts:
 --version                           - display version and exit
 --log file                          - request log filename (with optional 'yyyy_mm_dd' wildcard
 --out file                          - info/warn/debug log filename (with optional 'yyyy_mm_dd' wildcard
 --host name|ip                      - interface to listen on (default is all interfaces)
 --port n                            - port to listen on (default 8080)
 --stop-port n                       - port to listen for stop command (or -DSTOP.PORT=n)
 --stop-key n                        - security string for stop command (required if --stop-port is present) (or -DSTOP.KEY=n)
 [--jar file]*n                      - each tuple specifies an extra jar to be added to the classloader
 [--lib dir]*n                       - each tuple specifies an extra directory of jars to be added to the classloader
 [--classes dir]*n                   - each tuple specifies an extra directory of classes to be added to the classloader
 --stats [unsecure|realm.properties] - enable stats gathering servlet context
 [--config file]*n                   - each tuple specifies the name of a jetty xml config file to apply (in the order defined)
Context opts:
 [[--path /path] context]*n          - WAR file, web app dir or context xml file, optionally with a context path
`

The 'com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory' class is in a jar in my lib directory specified on the jetty-runner command line.

Here is my lib directory contents.
`-rw-rw-rw-@ 1  staff   25499 Dec 28 07:30 jetty-redis-sessions-9.4.2.jar
-rw-rw-rw-@ 1  staff  553762 Dec 28 07:30 jedis-2.9.0.jar
-rw-rw-rw-@ 1  staff  111969 Dec 28 07:30 commons-pool2-2.4.2.jar`

Jar  jetty-redis-sessions-9.4.2.jar contains the 'com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory' class. I am using Jetty Runner:

`java -jar jetty/jetty-runner.jar --version
2019-12-29 11:09:42.200:INFO::main: Logging initialized @222ms to org.eclipse.jetty.util.log.StdErrLog
org.eclipse.jetty.runner.Runner: 9.4.9.v20180320`

I would appreciate an example of running Jetty Runner 9.4 with Cloudbees jetty-redis session management or an explanation of why jetty-runner reports: 
`java.lang.ClassNotFoundException: com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory in file:/Users/user/bin/jetty.xml`
