### ISSUE TITLE
Jetty 9.3.20.v20170531 reported  ReadPendingException in class FillInterest.register

### ISSUE THREAD

**Issue by yangxingguo** [eclipse/jetty.project#1727]
When verifying the fixes on a recent Jetty 9.3.20.v20170531, I am seeing threads that are blocked forever on ArrayDeque objects from org.eclipse.jetty.server.HttpInput.blockForContent(HttpInput.java:398). An lsof shows no remaining server-side connections. the consumer of the request body reads slowly using the synchronous APIs. jetty server reported the following exception
why?
Can you help me ?
2017-08-10 03:05:57.243:WARN:oeji.FillInterest:qtp1983747920-34: Read pending for org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6 prevented org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6

**Comment by joakime** [comment]
There is not enough detail to help.
Please detail how you are using the servlet API.
If you have stacktraces, please include them in their entirety.

**Comment by yangxingguo** [comment]
thank you help me very much!!,following is stacktraces

[2017-08-07 08:23:52.740 UTC][][][WARN ][ [E6200000015DBBCB0C1FFA5770048C02][Attempt to return an invalid wrapperBuffer!] ][OSC][ChunkBufferTokenPool.java:destoryBuffer,185][qtp1983747920-43154]
java.nio.channels.ReadPendingException
        at org.eclipse.jetty.io.FillInterest.register(FillInterest.java:61)
        at org.eclipse.jetty.io.AbstractEndPoint.fillInterested(AbstractEndPoint.java:128)
        at org.eclipse.jetty.server.HttpConnection.blockingReadFillInterested(HttpConnection.java:555)
        at org.eclipse.jetty.server.HttpInputOverHTTP.blockForContent(HttpInputOverHTTP.java:39)
        at org.eclipse.jetty.server.HttpInput$1.blockForContent(HttpInput.java:846)
        at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:188)
        at uds.osc.io.DdosCountWithExInputStream.read(DdosCountWithExInputStream.java:79)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at uds.core.util.io.CountedInputStream.read(CountedInputStream.java:109)
        at uds.osp.multidc.ObjectDataTeeInputStream.read(ObjectDataTeeInputStream.java:198)
        at uds.osp.multidc.ObjectDataTeeInputStream.read(ObjectDataTeeInputStream.java:179)

**Comment by yangxingguo** [comment]
I Iadded extra logs in jetty, I found the HttpInput register  BlockingReadCallback  repeatedly and the other thread call FillInterest.fillable  to release BlockingReadCallback  
2017-08-10 03:05:57.240:WARN:oeji.FillInterest:qtp1983747920-1879: FillInterest@32e3bc77{true,org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6} fillable org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6
2017-08-10 03:05:57.240:WARN:oeji.FillInterest:qtp1983747920-34: register null  replace with org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6
2017-08-10 03:05:57.240:WARN:oeji.FillInterest:qtp1983747920-1879: FillInterest@32e3bc77{true,org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6} fillable org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6
2017-08-10 03:05:57.242:WARN:oeji.FillInterest:qtp1983747920-34: register null replace with org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6
2017-08-10 03:05:57.242:WARN:oeji.FillInterest:qtp1983747920-1879: FillInterest@32e3bc77{true,org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6} fillable org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6
2017-08-10 03:05:57.242:WARN:oeji.FillInterest:qtp1983747920-34: register null replace with org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6
2017-08-10 03:05:57.243:WARN:oeji.FillInterest:qtp1983747920-34: register org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6 for org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6 replace with org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6
2017-08-10 03:05:57.243:WARN:oeji.FillInterest:qtp1983747920-34: Read pending for org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6 prevented org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6
2017-08-10 03:05:57.243:WARN:oeji.FillInterest:qtp1983747920-1879: FillInterest@32e3bc77{true,org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6} fillable org.eclipse.jetty.server.HttpConnection$BlockingReadCallback@3a0064f6

**Comment by sbordet** [comment]
Please upgrade to latest 9.4.x, and if the problem persists, open a new issue.
