### ISSUE TITLE
MultiException | java.lang.RuntimeException: Error scanning UI and Servlet class | Vaadin

### ISSUE THREAD

**Issue by namannigam** [eclipse/jetty.project#1758]
Configured a vaadin project using this [getting started](https://vaadin.com/docs/-/part/framework/getting-started/getting-started-maven.html).

System configurations:
>     intelliJ-IDEA 2017.2.2
>     <vaadin.version>8.1.2</vaadin.version>
>     Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T01:09:06+05:30)
>     Maven home: /usr/local/Cellar/maven/3.5.0/libexec
>     Java version: 9, vendor: Oracle Corporation (jdk-9+181)

Basically these few steps:
1. Generate module using archetype
```
mvn archetype:generate \
   -DarchetypeGroupId=com.vaadin \
   -DarchetypeArtifactId=vaadin-archetype-application \
   -DarchetypeVersion=8.1.2 \
   -DgroupId=nullpointer \
   -DartifactId=vaadinjavanine \
   -Dversion=0.1 \
   -Dpackaging=war
```
2. Tried to migrate this to jdk9. Made changes in the pom for using 
```
<jetty.plugin.version>9.4.7.RC0</jetty.plugin.version>
<maven.compiler.source>1.9</maven.compiler.source>
<maven.compiler.target>1.9</maven.compiler.target> 
```
3. Created `module-info.java` corresponding to the project module.
4. Tried building the project and packaging it as war using `mvn clean package`. Works successfully.
3. Executing `mvn jettty:run`, results into the below stated stacktrace and I am unable to run the 

```
[INFO] jetty-9.4.7.RC0
[WARNING] THIS IS NOT A STABLE RELEASE! DO NOT USE IN PRODUCTION!
[WARNING] Download a stable release from http://download.eclipse.org/jetty/
[INFO] Scanning elapsed time=724ms
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@2b877a54{/,file:///../Jigsaw/vaadinjdk9/src/main/webapp/,UNAVAILABLE}{file:///../Jigsaw/vaadinjdk9/src/main/webapp/}
MultiException[java.lang.RuntimeException: Error scanning file MyUI$MyUIServlet.class, java.lang.RuntimeException: Error scanning file MyUI.class]
        at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:450)
        at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:363)
        at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1471)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:434)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:453)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:420)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:467)
        at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:333)
        at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:180)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: MultiException[java.lang.RuntimeException: Error scanning file MyUI$MyUIServlet.class, java.lang.RuntimeException: Error scanning file MyUI.class]
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:682)
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:689)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:830)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
        at java.base/java.lang.Thread.run(Thread.java:844)
        Suppressed: java.lang.RuntimeException: Error scanning file MyUI.class
                at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:712)
                ... 7 more
        Caused by: java.lang.IllegalArgumentException
                at org.objectweb.asm.ClassReader.<init>(Unknown Source)
                at org.objectweb.asm.ClassReader.<init>(Unknown Source)
                at org.objectweb.asm.ClassReader.<init>(Unknown Source)
                at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:959)
                at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:705)
                ... 7 more
Caused by: java.lang.RuntimeException: Error scanning file MyUI$MyUIServlet.class
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:712)
        ... 7 more
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:959)
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:705)
        ... 7 more
INFO] Started ServerConnector@38cfecf3{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] Started @14683ms
[INFO] Started Jetty Server
[INFO] Using Non-Native Java sun.nio.fs.PollingWatchService
[WARNING] Quiet Time is too low for non-native WatchService [sun.nio.fs.PollingWatchService]: 1000 < 5000 ms (defaulting to 5000 ms)

```

and I'm getting 503 response at http://localhost:8080

>  Problem accessing /. Reason:
>     Service Unavailable

Sample project to reproduce the above -- https://github.com/namannigam/Jigsaw/tree/master/vaadinjdk9/

_Note_: The same works fine for me if I create the project based on Java1.8.

**Comment by janbartel** [comment]
More than likely the version of asm in jetty 9.4 doesn't support jdk9. I think we already have an open issue to upgrade it.

**Comment by namannigam** [comment]
Is there a version of `asm` I can override to overcome in dependencies for this?

**Comment by janbartel** [comment]
@namannigam  I believe that asm has released 6.0-BETA which supports jdk-9. Not sure if its backwardly compatible with asm-5.x though.

**Comment by namannigam** [comment]
@janbartel Trying to build jetty with the BETA version gives me:
> 
The following artifacts could not be resolved: org.ow2.asm:asm:jar:6.0-BETA, org.ow2.asm:asm-commons:jar:6.0-BETA: Could not find artifact org.ow2.asm:asm:jar:6.0-BETA in jetty-snapshots (http://oss.sonatype.org/content/repositories/jetty-snapshots)

**Comment by joakime** [comment]
@namannigam the version is `6.0_BETA` not `6.0-BETA`

**Comment by namannigam** [comment]
@joakime Thanks, just went along with what was shared in the comments.

**Comment by namannigam** [comment]
@joakime @janbartel @sbordet Not sure what the process is. I was able to build Jetty using the `6.0_BETA` version of `asm` and `asm-commons`.
Using the `10.0.0-SNAPSHOT` built after that resolved the problem I was facing. Shall I raise a request to merge it into the master?

**Comment by joakime** [comment]
I'd be more interested to know if using `6.0_BETA` works on `jetty-9.4.x` branch and JDK9.

**Comment by namannigam** [comment]
@joakime *6.0_BETA works on jetty-9.4.x* what is the criteria for that? How do we test it out?
As far as I could test, [my application](https://github.com/namannigam/Jigsaw/tree/master/vaadinjdk9) works fine with both 10.0.0-SNAPSHOT(master) and 9.4.7-SNAPSHOT(jetty-9.4.x).

**Comment by janbartel** [comment]
@namannigam  we can't update jetty to use asm-6.0_BETA yet, because it fails in osgi, as 6.0_BETA is not a valid osgi version number:

Caused by: java.lang.IllegalArgumentException: invalid range "[6.0_BETA,6.0_BETA]": invalid version "6.0_BETA": non-numeric "0_BETA"

**Comment by janbartel** [comment]
Here's the link to the issue in their tracker:  http://forge.ow2.org/tracker/?func=detail&aid=317782&group_id=23&atid=100023

**Comment by namannigam** [comment]
@janbartel Understood (Y) We can wait for a valid release version in that case I guess.

**Comment by janbartel** [comment]
Upgraded to ASM-6.0 final in #1213
