### ISSUE TITLE
HTTP/2: producer can block in onReset

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#1759]
The following stack trace indicates that the HTTP/2 produce (which self declares as non blocking) has blocked within a call to `onReset` from the parser.  This can result in thread starvation as selector threads are consumed by such blocking producers.

```
"http-worker-1218" #1218 prio=5 os_prio=0 tid=0x00007f17a40014e0 nid=0xa68 waiting on condition [0x00007ef7fb645000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007f02aa003128> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:219)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:292)
	at org.eclipse.jetty.server.HttpWriter.close(HttpWriter.java:49)
	at org.eclipse.jetty.server.ResponseWriter.close(ResponseWriter.java:163)
	- locked <0x00007f156d01c760> (a org.eclipse.jetty.server.Iso88591HttpWriter)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1038)
	at org.eclipse.jetty.server.handler.ErrorHandler.generateAcceptableResponse(ErrorHandler.java:176)
	at org.eclipse.jetty.server.handler.ErrorHandler.doError(ErrorHandler.java:142)
	at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:78)
	at org.eclipse.jetty.server.Response.sendError(Response.java:655)
	at org.eclipse.jetty.server.handler.AbstractHandler.doError(AbstractHandler.java:100)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:565)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:281)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1339)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1110)
	at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:378)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:334)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:214)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:171)
	at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:425)
	at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:294)
	at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:230)
	at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:289)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyReset(BodyParser.java:139)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.onReset(ResetBodyParser.java:97)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.parse(ResetBodyParser.java:66)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:182)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:110)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:205)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:116)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:263)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:202)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:123)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:232)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gregw** [comment]
@sbordet two aspect of this issue:   Should handling of reset block?   If so then how can we handle it without thread starvation?

Taking the second part first.... if `onReset` handling can block then we are damned if we do and damned if we don't handle it with a dispatched thread.   If we dispatch, but the thread pool is exhausted, then any connection flow control window reserved by any data queued for the channel will not be freed until a thread becomes available... which it may not if threads are all blocked waiting on data that wont come because there is no flow control window.      If we don't dispatch, then we can block while producing and `HTTP/2` cannot self declare as non-blocking, so the selector will not be able to directly call it and will execute it - which can also lead to thread starvation if their are no available threads in the thread pool.

IF onReset must be able to block, then we are going to have to separate out the freeing on the data flow control from any handling of the reset.  Perhaps we should consume input first and then execute the handling of the reset.

However, the handling of this `onReset` does look a little strange and perhaps unnecessary.  The `onReset` handling has called asyncError, which has resulted in a and error page dispatch, which is trying to write an error page - which should fail in the write because the channel has been reset, but instead it blocks and waits for the write to complete, which never happens because no threads are selecting.  

Prior to the write that blocks, `getHttpTransport().onStreamFailure(failure);` has been called, so that should be sufficient to make any subsequent writes fail without blocking.

Note however, I'm still dubious we should be even trying to write an error page???

**Comment by gregw** [comment]
@sbordet I think the problem could be here: https://github.com/eclipse/jetty.project/blob/jetty-9.4.7.RC0/jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java#L328-L336

This is only changing the transport state to FAILED if there is a current write, in order to allow an error page to be written.    Either we need to differentiate between types of failures or all failures at this point should prevent an error page being written.

**Comment by sbordet** [comment]
Failures and timeouts now produce a task that will asynchronously call the application to produce the error page, avoid blocking.
