### ISSUE TITLE
SniX509ExtendedKeyManager.chooseServerAlias() throws NullPointerException when socket is null

### ISSUE THREAD

**Issue by derekla76** [eclipse/jetty.project#1770]
According to Java 8 documentation, https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/X509KeyManager.html#chooseServerAlias-java.lang.String-java.security.Principal:A-java.net.Socket-, the method, String chooseServerAlias(String keyType, Principal[] issuers, Socket socket) should be able to handle null socket as argument, but SniX509ExtendedKeyManager.chooseServerAlias()  throws NullPointerException when socket is null.
This is the stack trace we're getting when using Jetty 9.4.6 with bouncycastle:
java.lang.NullPointerException
	at org.eclipse.jetty.util.ssl.SniX509ExtendedKeyManager.chooseServerAlias(SniX509ExtendedKeyManager.java:115)
	at org.bouncycastle.jsse.provider.ProvTlsServer.selectCredentials(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsServer.selectCipherSuite(Unknown Source)
	at org.bouncycastle.tls.AbstractTlsServer.getSelectedCipherSuite(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsServer.getSelectedCipherSuite(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.sendServerHelloMessage(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.offerInput(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLEngine.unwrap(Unknown Source)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:653)
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:322)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:231)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rakRakevet** [comment]
I've stumbled upon this error itself. Jetty `9.4.7.v20170914` and BouncyCastle `bctls-jdk15on-158`.
Debugging shows that `org.bouncycastle.jsse.provider.ProvTlsServer#selectCredentials` calls `org.eclipse.jetty.util.ssl.SniX509ExtendedKeyManager#chooseServerAlias(java.lang.String, java.security.Principal[], java.net.Socket)` with null for socket.   
When jetty calls `getSSLParameters()` from socket we get the NullPointerException.  
So it seems that BCJSSE provider is not ready for use with Jetty just yet.

**Comment by gregw** [comment]
I've pushed a change that if a null socket or engine is passed, then we simply delegate the chooseServerAlias call to the delegate key manager, so it will handle the null value as per the standard JVM library.  Of course this means that SNI will not be available, but it cannot be selected anyway without a session.
