### ISSUE TITLE
NPE: StandardDescriptorProcessor.visitSecurityConstraint(StandardDescriptorProcessor.java:1505)

### ISSUE THREAD

**Issue by markkolich** [eclipse/jetty.project#1809]
Briefly grepped existing issues &mdash; didn't see anything similar.

Running `Jetty 9.4.6.v20170531`.

Configuring Jetty programmatically, I'm new'ing up a `WebAppContext` with the following configuration:

```java
final WebAppContext context =
  new WebAppContext(null, null, null, null, null, new ErrorPageErrorHandler(), 
    ServletContextHandler.NO_SESSIONS|ServletContextHandler.NO_SECURITY);
```

This fails miserably with an NPE:

```
2017-09-09 11:23:22.957:INFO::main: Logging initialized @693ms to org.eclipse.jetty.util.log.StdErrLog
2017-09-09 11:23:23.305:INFO:oejs.Server:main: jetty-9.4.6.v20170531
2017-09-09 11:23:23.732:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5a8806ef{/foo-apps,file:///Users/mark/workspace/foo/foo-apps/src/main/webapp/,UNAVAILABLE}{foo-apps/src/main/webapp}
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:83)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:70)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:407)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1461)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.foo.jetty.fooJettyRunner.main(fooJettyRunner.java:108)
Caused by: 
java.lang.NullPointerException
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitSecurityConstraint(StandardDescriptorProcessor.java:1505)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:83)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:70)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:407)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1461)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.foo.jetty.fooJettyRunner.main(fooJettyRunner.java:108)
2017-09-09 11:23:23.856:INFO:oejs.AbstractConnector:main: Started ServerConnector@26745168{HTTP/1.1,[http/1.1]}{0.0.0.0:9000}
2017-09-09 11:23:23.856:INFO:oejs.Server:main: Started @1594ms
```

I am explicitly setting `ServletContextHandler.NO_SESSIONS|ServletContextHandler.NO_SECURITY` because I have no need for Jetty to manage sessions (and/or security) in my stateless application context.

**Comment by markkolich** [comment]
Ok, ugh, upon closer inspection I'm passing a `null` `SecurityHandler` into this constructor.  Additionally, I'm passing in a `null` `SessionHandler`.

Am I required to pass a no-op like `SecurityHandler` and `SessionHandler` if I don't want Jetty to manage sessions?

**Comment by janbartel** [comment]
Jetty applies a webdefault.xml file to set up some defaults for every webapp. This file is baked into the jetty-webapp.jar. You can supply your own custom one with WebAppContext. SetDefaultsDescriptor method. Alternatively,  maybe you just want to use a ServletContextHandler instead of a full blown webapp?

**Comment by markkolich** [comment]
@janbartel thanks for the reply.

I did look at using `ServletContextHandler`, but I'm bootstrapping Jetty with an exploded `war` (unpacked under `src/main/webapp`), and need access to the `setWar` method provided by `WebAppContext`.  I didn't see any way to use a `ServletContextHandler` for my use case, but I might have missed it.

Edited for brevity, I'm effectively doing this:

```java
final Server server = new Server();

final WebAppContext context = new WebAppContext();

context.setWar("src/main/webapp");
context.setContextPath("/foo");

server.setHandler(context);
```

I went down this rabbit hole of mucking with `NO_SESSIONS|NO_SECURITY` on my `WebAppContext` because I'm trying to disable Jetty's `DefaultSessionIdManager`, as I have no need for Jetty to manage sessions (or security) in my stateless web-app.  I've been operating under the unconfirmed assumption that if I set `ServletContextHandler.NO_SESSIONS` on my `WebAppContext`, then Jetty won't instantiate its `DefaultSessionIdManager` and related resources &mdash; I should probably ask, is my assumption correct?

I'm not sure I totally understand the connection between `org/eclipse/jetty/webapp/webdefault.xml` and my issue.

Are you saying that instead of trying to set `NO_SESSIONS|NO_SECURITY` on my `WebAppContext` in code, there's something I can set in my own version of `webdefault.xml` to effectively force `NO_SESSIONS|NO_SECURITY` through configuration?

If so, is that the preferred mechanism to entirely disable the `DefaultSessionIdManager`, and its peer scavenger/housekeeper thread?

**Comment by janbartel** [comment]
If you use NO SESSIONS that should disable sessions because there will not be a SessionHandler. However I think the webdefault.xml contains some default security constraints,  so NO SECURITY might not work unless you customize webdefault.xml to remove them.

**Comment by markkolich** [comment]
> If you use NO SESSIONS that should disable sessions because there will not be a SessionHandler. 

Right &mdash; I think that's the bug though.

I want to instantiate a `WebAppContext` with the `NO_SESSIONS|NO_SECURITY` options, and not provide a session handler or security handler &mdash; because I don't have (or need) them.

It appears that I cannot do that.

If I pass a `null` `SessionHandler`, a `null` `SecurityHandler`, and the `NO_SESSIONS|NO_SECURITY` options to the `WebAppContext` constructor, Jetty NPEs with the exception captured here https://github.com/eclipse/jetty.project/issues/1809#issue-256457373.

**Comment by janbartel** [comment]
@markkolich I think we are in strenuous agreement.

What I am saying is that if you use NO_SESSIONS, and do not pass a SessionHandler, that should be fine. Indeed your stacktrace shows no problems with sessions.

However, if you pass NO_SECURITY and a null SecurityHandler, that I think is where you will see the problem, as the stacktrace shows that we are parsing the webdefault.xml file which contains some default security constraints. So, the short term solution for you is to edit the supplied webdefault.xml (from inside jetty-webapp.jar or from the distro in ${jetty.home}/etc/webdefault.xml) to remove those defaulted security constraints and apply your customized file to your WebAppContext with setDefaultsDescriptor().

I'll take a look at the code and see if there is anything we can do produce a warning instead of an error if we're parsing webdefault.xml and see a security constraint but there is no SecurityHandler present.

**Comment by markkolich** [comment]
Sounds good, thanks @janbartel

**Comment by janbartel** [comment]
Change to log null SecurityHandler checked in, not sure if it has squeaked into 9.4.7 or not yet.
