### ISSUE TITLE
9.4.7 - ResourceHandler throws NPE for welcome files (if calling handle manually)

### ISSUE THREAD

**Issue by tipsy** [eclipse/jetty.project#1856]
I realize I'm probably not using Jetty as intended, but in `9.4.6.v20170531` I was able create a `ResourceHandler` and call `handle()`, like this:

```java
ResourceHandler resourceHandler = new ResourceHandler(); 
...
resourceHandler.handle(target, baseRequest, httpRequest, httpResponse);
```

After updating to `9.4.7.v20170914` this works for everything except welcome-files, where I get a NPE in `ResourceService#sendWelcome` (which makes sense, since I don't have a `servletContext`).

Is this intended? Is there a simple workaround?

**Comment by joakime** [comment]
First, why are you calling `ResourceHandler.handle()` directly?

**Comment by gregw** [comment]
@tipsy Jetty is intended to be used flexibly and in ways which it's developers did not anticipate! 

As for #1833, we should not require a context for ResourceHandler, so please give us a full stack trace and we'll look at fixing.

**Comment by tipsy** [comment]
> @joakime First, why are you calling ResourceHandler.handle() directly?

It just seems simpler for my use case, but that might be because I'm not very familiar with servlets.
I spin up server with a single handler, like this (kotlin):

```kotlin
server.apply {
    handler = object : SessionHandler() {
        override fun doHandle(...) {
            ResourceHandler resourceHandler = ...
            // custom route matching + application logic here
            // try resourceHandler.handle(...) if custom route matching yielded 404
        }
    }
    ...
}.start()
```

> @gregw Jetty is intended to be used flexibly and in ways which it's developers did not anticipate! As for #1833, we should not require a context for ResourceHandler, so please give us a full stack trace and we'll look at fixing.

Happy to hear it. Luckily it's a pretty short stack-trace. The code above shows my application structure, which causes a NPE because I'm missing a `servletContext` in `sendWelcome`:

```java
java.lang.NullPointerException
	at org.eclipse.jetty.server.ResourceService.sendWelcome(ResourceService.java:419)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:251)
	at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:281)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
	at io.javalin.embeddedserver.jetty.JettyResourceHandler.handle(JettyResourceHandler.kt:66)
	at io.javalin.core.JavalinServlet.service(JavalinServlet.kt:63)
	at io.javalin.embeddedserver.jetty.EmbeddedJettyServer$start$httpHandler$1.doHandle(EmbeddedJettyServer.kt:34)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:561)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gregw** [comment]
@tipsy The issue is that the ResourceHandler has two mechanisms with which it can serve a welcome file: redirection; RequestDispatcher.    The RequestDispatcher requires a context, so it will not work without.   If you configure with `resourceHandler.setRedirectWelcome(true)` then you will avoid the NPE.

I will make a fix in the next release to do this by default if there is no context.

**Comment by tipsy** [comment]
@gregw, great, thanks!

**Comment by joakime** [comment]
@tipsy Handlers can be chained together in a list or by wrapping.

So you can, for example have ...

```
Server.setHandler( HandlerList )
  HandlerList
    FirstLogicHandler
    SecondLogicHandler
    ThirdLogicHandler
    ResourceHandler - configured for a resource base to serve as static content
    DefaultHandler - if nothing else above handles the request then this produces the error page
```

If one of your `*LogicHandler` implementations decides it doesn't want to send a response, it can just flow out and not set `baseRequest.setHandled(true)`, which means the next handler gets a shot.

If none of the `*LogicHandler` classes does `baseRequest.setHandled(true)` then `ResourceHandler` gets a shot to answer the request, if even it cannot handle the request, then it too doesn't call `baseRequest.setHandled(true)` and then `DefaultHandler` gets a go at it and will always respond.

**Comment by tipsy** [comment]
@joakime thanks for the suggestion. I tried that approach, but I didn't think it was a good fit. To expand on how my code works:

```
override fun doHandle() {
    run user-defined before-handlers
    if user-defined endpoint-handler
        run user-defined endpoint-handler
    else
        run jetty-resource-handler
    run user-defined after-handlers
}
```

I would like to use `DefaultServlet` properly, but it leads to a lot more complex code (at least I can't seem to make it simple).

**Comment by joakime** [comment]
You can have more than 1 DefaultServlet within your ServletContextHandler.

See example at https://stackoverflow.com/questions/20207477/serving-static-files-from-alternate-path-in-embedded-jetty/20223103#20223103

**Comment by philix** [comment]
If you don't want to redirect `/` to `index.html` as I do, you can wrap the `ResourceHandler` on a `ContextHandler`

```scala
   // Create server and set connectors
    val server = new Server()
    val connector = new ServerConnector(server)
    connector.setPort(8080)
    server.setConnectors(Array(connector))

    // Create a ResourceHandler to serve static files
    val rootResourceHandler = new ResourceHandler()
    rootResourceHandler.setDirectoriesListed(false)
    rootResourceHandler.setWelcomeFiles(Array("index.html"))

    // Wrap the ResourceHandler in a ContextHandler for the "/" path
    val basePath = Resource.newResource("/Users/felipe/.../public")
    val rootContextHandler = new ContextHandler()
    rootContextHandler.setContextPath("/")
    rootContextHandler.setBaseResource(basePath)
    rootContextHandler.setHandler(rootResourceHandler)

    // Create the FrontHandler for the API and wrap it in a ContextHandler
    val frontHandler = new FrontAPIHandler(storage)
    val apiContextHandler = new ContextHandler("/api")
    apiContextHandler.setHandler(frontHandler)

    // Add the ResourceHandler to the server.
    val handlers = new HandlerList()
    handlers.setHandlers(Array(rootContextHandler, apiContextHandler, new DefaultHandler()))
    server.setHandler(handlers)

    // Start server and wait
    server.start()
    server.join()
```

**Comment by AleksandarAleksandrov** [comment]
Thanks really helpful post
