### ISSUE TITLE
Unable to change thread pool configuration in jetty 9 [Reopening]

### ISSUE THREAD

**Issue by rajeevvs2007** [eclipse/jetty.project#1876]
In jetty.xml , i am trying to change the thread pool configuration from unbounded to bounded queue.I am getting an error during thr server startup.I am reopening the issue https://github.com/eclipse/jetty.project/issues/1872

**Exception**

```
java.lang.IllegalStateException: No suitable constructor: <New id="threadpool" class="org.eclipse.jetty.util.thread.QueuedThreadPool"><Arg name="maxThreads">10</Arg><Arg name="minThreads">500</Arg><Arg name="idleTimeout">10000</Arg><Arg name="queue">|        <New class="org.eclipse.jetty.util.BlockingArrayQueue"><Arg type="int">5</Arg></New>|      </Arg></New> on null
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:794)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1235)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1140)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:335)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:259)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1499)
```
**My configuration**

 ```
<Arg name="threadpool">
    <New id="threadpool" class="org.eclipse.jetty.util.thread.QueuedThreadPool">
      <Arg name="maxThreads">10</Arg>
      <Arg name="minThreads">500</Arg>
      <Arg name="idleTimeout">10000</Arg>
      <Arg name="queue">
        <New class="org.eclipse.jetty.util.BlockingArrayQueue">
	        <Arg type="int">5</Arg>
	 </New>
      </Arg>
    </New>
  </Arg>
```

**Comment by sbordet** [comment]
You must specify `type="int"` for the `Arg` elements `maxThreads`, `minThreads` and `idleTimeout`.
Note that you have swapped the values for `minThreads` (500) and `maxThreads` (10).

**Comment by sbordet** [comment]
Note also that it is normally not a good idea to specify a bounded queue for the thread pool.

**Comment by rajeevvs2007** [comment]
Thanks @sbordet, it worked!
