### ISSUE TITLE
Improve support of WebSocket over Unix Domain Socket

### ISSUE THREAD

**Issue by yueki1993** [eclipse/jetty.project#1881]
Hi,
Does not jetty support websocket over unix domain socket yet?
I'm trying to configure websocket connection over Unix domain socket, and I get the following error:

```
java.lang.NullPointerException
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.<init>(AbstractWebSocketConnection.java:231)
        at org.eclipse.jetty.websocket.server.WebSocketServerConnection.<init>(WebSocketServerConnection.java:36)
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.upgrade(WebSocketServerFactory.java:563)
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:230)
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:192)
        at org.eclipse.jetty.websocket.servlet.WebSocketServlet.service(WebSocketServlet.java:161)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:223)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:561)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
        at java.lang.Thread.run(Thread.java:748)
```

### version
Jetty 9.4.7.v20170914

### details
I use a sample app, and run it using jetty-distribution-9.4.7.v20170914.
https://github.com/jetty-project/jetty-websocket-example

start.ini:
```
--module=deploy
--module=websocket
--module=annotations
--module=unixsocket-http
```

etc/*: I use the default files (No modification)

jetty-websocket-example/pom.xml:
```
[...]
    <jetty.version>9.4.7.v20170914</jetty.version>
[...]
```

I can access the standard webpage (http://localhost/demo/time/servlet),
but when I try to access the websocket page using wscat (http://localhost/demo/time/websocket) the above exception raised.

**Comment by gregw** [comment]
Our unixsocket support is still very Beta quality.   We have mostly switched our efforts to using conscrypt to get fast TLS rather than use a local server over unixsockets.

However, it would be good to get this feature more robust and it is a bug that websockets does not work. So we hope to look at this, but it is not currently a high priority.

**Comment by yueki1993** [comment]
Hi gregw,
OK, I understand.
Thanks for your comment!

**Comment by joakime** [comment]
This NPE seems like its from the local/remote address lookups.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.7.v20170914/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java#L230-L234

That specific NPE is easy enough to fix, however confirming a future issue will be tricky (for me).

**Comment by joakime** [comment]
Having a null local and remote address is going to cause other bugs in websocket (both native jetty websockets and jsr356 websockets), perhaps we need to supplement the `UnixSocketEndPoint` to return something other then null?

https://github.com/eclipse/jetty.project/blob/jetty-9.4.7.v20170914/jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/UnixSocketEndPoint.java#L46-L56

**Comment by joakime** [comment]
I'd like to propose some new methods for EndPoint ...

`.getLocalAddressString()` - returns a textual representation of the local address
`.getRemoteAddressString()` - returns a textual representation of the remote address

(optional)
`.toConnectedString()` - returns textual representation of the connected endpoint (representing the local + remote address strings)

For network endpoints an "address string" would be `{address.host}:{address.port}`
For unix sockets it would be `{unixAddress.path}` (this is how the `jnr.unixsocket.UnixSocketAddress` represents the local/remote address fields found in the `jnr.unixsocket.UnixSocketChannel` class)

**Comment by gregw** [comment]
@joakime perhaps just
```java
interface EndPoint
{
    ...
    default String getRemote() { return getRemoteAddress().toString(); }
    default String getLocal() { return getLocalAddress().toString(); }
    ...
}
```
and then EndPoints that can have null addresses have to override with something else.
