### ISSUE TITLE
Jetty can deadlock when http thread is interrupted

### ISSUE THREAD

**Issue by oglueck** [eclipse/jetty.project#1889]
Calling Thread.interrupt() may end up with inverted locks taken as interrupt() calls down into the channel's interrupt() method. This stack is from 9.2.22.v20170606

```
"Timeout":
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:716)
        - waiting to lock <0x0000000714209228> (a org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.shutdownOutput(SslConnection.java:893)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.close(SslConnection.java:915)
        at org.eclipse.jetty.server.HttpConnection.abort(HttpConnection.java:489)
        at org.eclipse.jetty.server.HttpChannel.abort(HttpChannel.java:826)
        at org.eclipse.jetty.server.HttpConnection$HttpChannelOverHttp.abort(HttpConnection.java:627)
        at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:184)
        at java.nio.channels.Channels$WritableByteChannelImpl.implCloseChannel(Channels.java:469)
        at java.nio.channels.spi.AbstractInterruptibleChannel$1.interrupt(AbstractInterruptibleChannel.java:165)
        - locked <0x0000000714f342f0> (a java.lang.Object)
        at java.lang.Thread.interrupt(Thread.java:919)
        - locked <0x0000000716254b80> (a java.lang.Object)
        at test.TxTimeout.run(LoTx.java:607)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)


"http-9245":
        at java.lang.Thread.blockedOn(Thread.java:239)
        - waiting to lock <0x0000000716254b80> (a java.lang.Object)
        at java.lang.System$2.blockedOn(System.java:1252)
        at java.nio.channels.spi.AbstractInterruptibleChannel.blockedOn(AbstractInterruptibleChannel.java:211)
        at java.nio.channels.spi.AbstractInterruptibleChannel.begin(AbstractInterruptibleChannel.java:170)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:464)
        - locked <0x00000007145824c0> (a java.lang.Object)
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:809)
        - locked <0x0000000714209228> (a org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint)
        at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:735)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:481)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:765)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:798)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:155)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:148)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:363)
        at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458)
        - locked <0x0000000714f218a8> (a java.lang.Object)
        at sun.nio.ch.FileChannelImpl.transferToArbitraryChannel(FileChannelImpl.java:567)
        at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:616)
        at util.StreamUtils.copy(StreamUtils.java:162)
```

**Comment by joakime** [comment]
Short answer: 
Don't attempt to interrupt jetty, selector, acceptor, http, request, or dispatch threads in Jetty 8+

Long answer:
The assumption that there is 1 thread processing 1 request is no longer true with Servlet 3.0+.
For 1 HTTP/1.x connection, there can be many different threads throughout its lifetime serving different roles of the request.  There can even be multiple threads used throughout the lifetime of a single request.
This becomes especially true if you use AsyncContext or Async I/O.
This becomes doubly true if you use HTTP/2 or WebSocket.
This becomes even more troublesome if you use any modern web library (spring, jersey, rest, etc)

If you want to terminate the HTTP portion of the transaction, use HttpServletResponse.sendError(-1) and that will terminate the HTTP layer and unwind all of the jetty internals and cleanup appropriately.

Keep in mind that if you use Thread.interrupt on Java 8 (or older) with Jetty you will be subject to a JVM bug that will render the network Channels useless and require a JVM restart.
https://bugs.openjdk.java.net/browse/JDK-8084250

**Comment by oglueck** [comment]
This all happens within the boundaries of a servlet's doPost() method. So the thread does not and can not change here. The interrupt is a means of controlling our transaction timeouts (the transaction manager calls interrupt()) and we have been relying on that for the last 10 years very successfully. Do you see any chance that the lock inversion can be fixed within Jetty?

Thanks for the hint on JDK-8084250, but we have not observed any problems so far. This application runs fine for months without restart even when heavily loaded.

**Comment by joakime** [comment]
Thread.interrupt() was possible on Jetty and most servlet engines up to Servlet 2.5

Once Servlet 3.0 was introduced Thread.interrupt() no longer became viable, on any Servlet engine.
The servlet doPost() handling is not special in this regard.
Request and Response processing is separate, and easily handled in different threads without using servlet Async concepts.  You can even send a full response (even committed) before you have read the request.

I'll defer to @gregw or @sbordet on the lock request.

**Comment by joakime** [comment]
@oglueck also note that no work is being done on Jetty 9.2.x anymore.  

Current stable release is Jetty 9.4.7.
Current active branch is Jetty 10.x

**Comment by oglueck** [comment]
OK we can try and move the response streaming out of the transaction/timeout. So interrrupt calls won't hit Jetty in the middle of transferring. Seems there is no way around that. We actually do that everywhere except when streaming large blobs from the DB directly (that's why we need a transaction). This will introduce buffering though, which is a pitty. Jetty 9.2 is used because we need to support JDK-1.7 for now.

**Comment by joakime** [comment]
The public Oracle Release notes for Java 1.7 indicate that all versions of Java 1.7 are now expired.
This means that Java 1.7 is unsuitable for SSL/TLS (expired JVM's are considered vulnerable).
I mention this as your stacktrace includes `org.eclipse.jetty.io.ssl.SslConnection`.

**Comment by sbordet** [comment]
This is a JDK 7 (and early 8 beta releases) bug: https://bugs.openjdk.java.net/browse/JDK-8066764
The bug is fixed in JDK 8. Not much we can do in Jetty.

Best solution is for you to use another mechanism to cancel your transaction, or update to JDK 8.

**Comment by oglueck** [comment]
We know 1.7 is EOL. The corporate world is not always so simple and there are far more constraints that play here, including https://bugs.openjdk.java.net/browse/JDK-8164293 which keep certain customers from upgrading.

**Comment by gregw** [comment]
Not to diminish anything that @joakime or @sbordet have said about the deficiencies of interrupt, I'm still very amazed that interrupt can lead to such a dead lock we should at least have a look to see if there is anything that we (or the OP) can do to avoid it.

Well firstly, I note that the problem is being initiated by the WritableByteChannelImpl that is wrapping jetty's HttpOutput.   I do not believe that it is jetty that is doing that wrapping, so I assume it must be the application or framework?  So there is an opportunity there to intercept the close on interrupt semantics and avoid the deadlock.

One of the locks involved in the deadlock is 0x0000000714209228, which is in Jetty's DecryptedEndpoint class.  We grab that lock when flush is called and also when close/shutdownOutput is called.  It appears reasonable that an output stream should be able to mutually exclude calls to close and flush at the same time, so I don't think we are doing anything unreasonable there.  So let's look at what we are calling when we have that lock...

We are calling Channel.write with that lock, which again looks a reasonable thing to do, as we should be able to mutually exclude multiple threads from calling write.   Furthermore, there signature of write says that it will throw a ClosedByInterruptException if there is an interrupt.  

So that brings us to the other half of the deadlock 0x0000000716254b80, which is a Thread blockerLock with the comment:

>      /* The object in which this thread is blocked in an interruptible I/O
>      * operation, if any.  The blocker's interrupt method should be invoked
>      * after setting this thread's interrupt status.

There's your problem!

The JVM has strangely decided that a thread can only be involved in a single interruptible I/O operation and has just a single blockerLock object.   But in this case, there is a `WritableByteChannelImpl` IO operation on the wrapper of the HttpOutput stream and a `Channel.write` operation deep inside that as that HttpOutput stream is implement using a Channel within.    

There is very little that Jetty can do if an application wrapper decides to use the same lock object as one of our internal implementation classes.   This is a JVM bug pure and simple (and it was a stupid idea of them to attempt a close on interrupt in the first place - let alone the poor assumption of only a single interruptable IO operation per thread.).

If you can't update your JVM, then I would suggest wrapping the HttpOutput stream with something that intercepts close, an that if the thread calling close is interrupted, then do a noop and return.

**Comment by oglueck** [comment]
Good observation, @gregw! We actually do Channels.newChannel(out) and use channels to copy a file to the output stream. Can easily be replaced with a buffered stream copy. Thanks!
