### ISSUE TITLE
Sometimes jetty does not launche webapp if java configured is IBM java

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#190]
migrated from Bugzilla [#462840](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462840)
status ASSIGNED severity *minor* in component *server* for *9.2.x*
Reported in version *unspecified* on platform *All*
Assigned to: Greg Wilkins

Original attachment names and IDs:
- _[Jetty9CleanStartLogs](https://bugs.eclipse.org/bugs//attachment.cgi?id=251950)_ (ID 251950)
- _[Jetty9IBM javaStartError1.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=251951)_ (ID 251951)
- _[WebAppAndjettyConfiguration.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=251952)_ (ID 251952)

On 2015-03-23 08:05:46 -0400, Ravi Kini wrote:

> Sometimes jetty does not launche the webapp if java configured is IBM java.
> 
> Jetty Configuration: Deploy a test app in custom path which is only accessible on https. All http request is redirected to https.
> 
> After deploying an application with the above configuration, sometimes, the Jetty server starts gracefully and we are able to launch the application in the web-browser.  But sometimes, we see a error message when starting Jetty Server and the web-application does not get launched.  Also, sometimes there are no error messages seen at the Jetty server console, but still the web-app does not launch.  The solution is to restart the Jetty server and try to launch the application again.
> 
> Versions:
> Jetty Version: Jetty 8 or 9
> Java Version: IBM 7
> 
> Other Information:
> This issue is seen only when using IBM Java.  No issue is seen when using Open Java.

On 2015-03-23 09:48:24 -0400, Jesse McConnell wrote:

> You will need to track down some additional information for us to track this sort of intermittent start up issue, there is simply not enough to go on here.
> 
> I would enable debug logging for everything and see about restarting it over and over until you trigger the error.

On 2015-03-27 07:04:32 -0400, Ravi Kini wrote:

> We have enabled the debug log and captured the logs.  Attaching the logs and the sample web-app files.
> 
> 1. File "WebAppAndjettyConfiguration": This file has Web app details and jetty 9 configuration to deploy the web app.
> 2. File "Jetty9CleanStartLogs": This file has jetty 9 start logs. Till Line # 725 indicates that jetty start has no error. But when UI was accessed in browser, error was seen in logs, refer line # 1534. The UI did not launch.
> 3. File "Jetty9IBM javaStartError1": This file has jetty 9 logs. With same configuration, jetty start gave an error. Again, the UI did not launch.
> 4. Many time with clean start jetty logs, webapp was accessible using browser without an error.
> 
> Note that the problem is seen only when IBM Java is used.  Also, the issue is intermittent, so jetty restart has to be done multiple times to reproduce the issue and at every restart, the UI needs to be launched.

On 2015-03-27 07:07:27 -0400, Ravi Kini wrote:

> Created attachment 251950
> Jetty logs when the jetty server start did not show any error

On 2015-03-27 07:08:33 -0400, Ravi Kini wrote:

> Created attachment 251951
> Jetty server start gave an error message

On 2015-03-27 07:09:00 -0400, Ravi Kini wrote:

> Created attachment 251952
> Sample web-app files merged in one file

**Comment by meghasyam** [comment]
Hi Greg,

we are seeing the above issue consistently ,all time .
this causes the jetty not to start, so we are not able to run our web application.

as we are deadly blocked on this , can you please help us in solving this issue.

thanks,Ram

**Comment by sbordet** [comment]
The first error reports "no cipher suites in common", which is a configuration problem. You must make sure that you have configured the client and the server with a set of cipher suites so that they can talk to each other.

The second error is weird as Jetty does not reference the symbol `TYPE`, so I have no idea where that comes from. You should try to debug it and report back.

**Comment by meghasyam** [comment]
thanks for your reply. Can you please see the log below and suggest me some thing.

2016-06-06 12:09:37.103:DBUG:oejx.XmlConfiguration:WrapperSimpleAppMain: XML ServerConnector@2c532550{HTTP/1.1}{0.0.0.0:0}.setHost(null)
2016-06-06 12:09:37.104:WARN:oejx.XmlConfiguration:WrapperSimpleAppMain: Config error at <Set name="host"><Property name="jetty.host"/></Set> java.lang.NoSuchFieldExcep
tion: TYPE in file:<>/_jetty/etc/jetty-http.xml
2016-06-06 12:09:37.104:WARN:oejx.XmlConfiguration:WrapperSimpleAppMain: Config error at <Call name="addConnector"><Arg>|      <New class="org.eclipse.jetty.server.Serv
erConnector"><Arg name="server"><Ref refid="Server"/></Arg><Arg name="factories">|          <Array type="org.eclipse.jetty.server.ConnectionFactory"><Item>|
  <New class="org.eclipse.jetty.server.HttpConnectionFactory"><Arg name="config"><Ref refid="httpConfig"/></Arg></New>|            </Item></Array>|        </Arg><Set na
me="host"><Property name="jetty.host"/></Set><Set name="port"><Property name="jetty.port" default="80"/></Set><Set name="idleTimeout"><Property name="http.timeout" defa
ult="30000"/></Set><Set name="soLingerTime"><Property name="http.soLingerTime" default="-1"/></Set></New>|    </Arg></Call> java.lang.NoSuchFieldException: TYPE in file
:<>/_jetty/etc/jetty-http.xml
2016-06-06 12:09:37.104:DBUG:oejx.XmlConfiguration:WrapperSimpleAppMain: EXCEPTION
java.lang.NoSuchFieldException: TYPE
        at java.lang.Class.getFieldImpl(Native Method)
        at java.lang.Class.getField(Class.java:954)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:490)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:411)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:815)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1125)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1030)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:721)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:417)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:354)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:262)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1243)
        at java.security.AccessController.doPrivileged(AccessController.java:274)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:94)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:619)
		   at org.eclipse.jetty.start.Main.invokeMain(Main.java:306)
        at org.eclipse.jetty.start.Main.start(Main.java:754)
        at org.eclipse.jetty.start.Main.main(Main.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:94)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:619)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
        at java.lang.Thread.run(Thread.java:853)
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:94)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:619)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:306)
        at org.eclipse.jetty.start.Main.start(Main.java:754)
        at org.eclipse.jetty.start.Main.main(Main.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:94)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:619)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
        at java.lang.Thread.run(Thread.java:853)
Caused by: java.lang.NoSuchFieldException: TYPE
        at java.lang.Class.getFieldImpl(Native Method)
        at java.lang.Class.getField(Class.java:954)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:490)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:411)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:815)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1125)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1030)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:721)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:417)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:354)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:262)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1243)
        at java.security.AccessController.doPrivileged(AccessController.java:274)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
        ... 13 more

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information

**Comment by joakime** [comment]
Looks like your _jetty/etc/jetty-http.xml is corrupt.

Can you copy/paste it here?

Joakim Erdfelt / joakim@webtide.com

**Comment by meghasyam** [comment]
this is xml

<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">






<Configure id="Server" class="org.eclipse.jetty.server.Server">

  
  
  
  
  
  
  
  
  
  
  <Call name="addConnector">
    <Arg>
      <New class="org.eclipse.jetty.server.ServerConnector">
        <Arg name="server"><Ref refid="Server" /></Arg>
        <Arg name="factories">
          <Array type="org.eclipse.jetty.server.ConnectionFactory">
            <Item>
              <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                <Arg name="config"><Ref refid="httpConfig" /></Arg>
              </New>
            </Item>
          </Array>
        </Arg>
        <Set name="host"><Property name="jetty.host" /></Set>
        <Set name="port"><Property name="jetty.port" default="80" /></Set>
        <Set name="idleTimeout"><Property name="http.timeout" default="30000"/></Set>
        <Set name="soLingerTime"><Property name="http.soLingerTime" default="-1"/></Set>
      </New>
    </Arg>
  </Call>

</Configure>

**Comment by sbordet** [comment]
Exact Jetty version ?

**Comment by meghasyam** [comment]
the jetty version is org.eclipse.jetty.server.Server  - jetty-9.2.0.v20140526

**Comment by meghasyam** [comment]
and also i see  in the current code for private void set(Object obj, XmlParser.Node node) throws Exception 

the above method only throws   throw new NoSuchMethodException(oClass + "." + name + "(" + vClass[0] + ")"); but we are getting 

java.lang.NoSuchFieldException: TYPE
	at java.lang.Class.getFieldImpl(Native Method)
	at java.lang.Class.getField(Class.java:954)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:490)

**Comment by sbordet** [comment]
The line that throws that exception, [this one](https://github.com/eclipse/jetty.project/blob/jetty-9.2.0.v20140526/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L490), is wrapped into a `try/catch` block that catches `NoSuchFieldException` and ignores it.

If the exception is not caught and ignored, then it's a JVM bug, and there is nothing we can do.

**Comment by meghasyam** [comment]
Hi ,

Thanks for your help.
So , What is approach we have to follow , to solve this issue.

Thanks,Megha

**Comment by joakime** [comment]
To give a bit more detail to what @sbordet said.

Your JVM has a bug, one we cannot work around.

It happens like this (using your version of Jetty and the stacktrace you posted):

 1. in [`XmlConfiguration` L411](https://github.com/eclipse/jetty.project/blob/jetty-9.2.0.v20140526/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L411) the `set(obj, node)` call occurs.
 2. at [`XmlConfiguration` L490](https://github.com/eclipse/jetty.project/blob/jetty-9.2.0.v20140526/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L490) the test for `Field type = vClass[0].getField("TYPE")` occurs.  It throws a `NoSuchFieldException`
 3. The `NoSuchFieldException` is either never caught at [`XmlConfiguration` L496](https://github.com/eclipse/jetty.project/blob/jetty-9.2.0.v20140526/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L496), or is rethrown improperly (*JVM Bug*).
 4. The `LOG.ignore()` call at [`XmlConfiguration` L498](https://github.com/eclipse/jetty.project/blob/jetty-9.2.0.v20140526/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L498) does not produce output (as your logging output does not contain the [`IGNORED`](https://github.com/eclipse/jetty.project/blob/jetty-9.2.0.v20140526/jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java#L770-L778) severity level).
 5. The exception then somehow flows out of the `set(obj, node)` call (*This is where the JVM bug happens*).  When execution should have proceeded to [`XmlConfiguration` L504](https://github.com/eclipse/jetty.project/blob/jetty-9.2.0.v20140526/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L504).  Your JVM has popped out of the `set(obj, node)` call incorrectly.
 6. The improperly popped out `NoSuchFieldException` is now handled by [`XmlConfiguration` L438](https://github.com/eclipse/jetty.project/blob/jetty-9.2.0.v20140526/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L438) and reported to you.

There's really only 2 possibilities happening here.

 1. Working with the assumption that you haven't modified Jetty in any way, then this is a JVM bug.
 2. You could have modified the source for your `Logger.ignore(Throwable)` to rethrow exceptions. (If this is the case, this is not a Jetty bug, but a bug in your modifications to Jetty)

**Comment by meghasyam** [comment]
@joakime thanks  so much for your help.

I will look into the directions provide by you

**Comment by jmcc0nn3ll** [comment]
FWIW I have a hard time seeing the IBM JDK being that terrible so I would absolutely validate if it fails similarly for either oracle or openjdk.  If it does then you likely have something misconfigured.
