### ISSUE TITLE
Waiting for Server Shutdown

### ISSUE THREAD

**Issue by rkhmelichek** [eclipse/jetty.project#1913]
I'm using embedded Jetty in my integration tests and I have noticed a problem with what seems the server not being fully shut down even after the 'stopped' lifecycle event is triggered.
I have recreated the problem with the code below.
While playing around with the code, I also noticed that setting `server.setStopTimeout(0);` to something other than 0 causes things to behave normally.

The way it is, it will log the following Exception:

```
[WARN 10/19/2017 18:09:34 o.e.j.u.t.QueuedThreadPool] org.eclipse.jetty.util.thread.QueuedThreadPool@qtp1293226111{STOPPING,8<=8<=200,i=0,q=4} Couldn't stop Thread[qtp1293226111-28,5,main]
[WARN 10/19/2017 18:09:34 o.e.j.u.t.QueuedThreadPool] org.eclipse.jetty.util.thread.QueuedThreadPool@qtp1293226111{STOPPING,8<=8<=200,i=0,q=4} rejected org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread@3d71536c
[WARN 10/19/2017 18:09:34 o.e.j.u.t.QueuedThreadPool] org.eclipse.jetty.util.thread.QueuedThreadPool@qtp1293226111{STOPPED,8<=8<=200,i=0,q=4} rejected org.eclipse.jetty.io.ManagedSelector$EndPointCloser@6b2ddfe5
[WARN 10/19/2017 18:09:34 o.e.j.u.t.s.EatWhatYouKill] 
java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.io.ManagedSelector$EndPointCloser@6b2ddfe5
	at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:385) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:249) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

It seems the server is still up, but the ThreadPool is in a shutdown state, so it's rejecting any new requests.

```java
package jetty;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.eclipse.jetty.util.component.AbstractLifeCycle;
import org.eclipse.jetty.util.component.LifeCycle;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.concurrent.CountDownLatch;

public class JettyTest {
    private static final int PORT = 9191;

    public static ServerCountdown buildServer() throws Exception {
        CountDownLatch stopCountDownLatch = new CountDownLatch(1);

        ServletContextHandler contextHandler = new ServletContextHandler(null, "/", false, false);
        contextHandler.addServlet(new ServletHolder(new HttpServlet() {
            @Override
            protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
                resp.setContentType("text/plain;charset=UTF-8");
                PrintWriter out = resp.getWriter();
                out.print("hello world");
                out.close();
            }
        }), "/");

        Server server = new Server();
        ServerConnector connector = new ServerConnector(server);
        connector.setPort(PORT);
        server.addConnector(connector);
        server.setHandler(contextHandler);
        server.setStopAtShutdown(true);
        server.setStopTimeout(0);
        server.addLifeCycleListener(new AbstractLifeCycle.AbstractLifeCycleListener() {
            @Override
            public void lifeCycleStopped(LifeCycle event) {
                stopCountDownLatch.countDown();
            }
        });

        return new ServerCountdown(server, stopCountDownLatch);
    }

    public static CountDownLatch startServer(Server server) {
        final CountDownLatch startCountDownLatch = new CountDownLatch(1);

        new Thread(() -> {
            try {
                server.start();
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                startCountDownLatch.countDown();
            }

            try {
                server.join();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();

        return startCountDownLatch;
    }

    public static class ServerCountdown {
        private final Server server;
        private final CountDownLatch stopCountDownLatch;

        public ServerCountdown(Server server, CountDownLatch stopCountDownLatch) {
            this.server = server;
            this.stopCountDownLatch = stopCountDownLatch;
        }

        public Server getServer() {
            return server;
        }

        public CountDownLatch getStopCountDownLatch() {
            return stopCountDownLatch;
        }
    }

    public static void main(String[] args) throws Exception {
        for (int i = 0; i < 1024; i++) {
            ServerCountdown serverCountdown = buildServer();
            CountDownLatch startCountDownLatch = startServer(serverCountdown.getServer());

            startCountDownLatch.await();

            HttpURLConnection connection = (HttpURLConnection) new URL(String.format("http://localhost:%d/", PORT)).openConnection();
            connection.setReadTimeout(1000);
            connection.setConnectTimeout(1000);
            try (InputStream is = connection.getInputStream()) {
            } finally {
                connection.disconnect();
            }

            serverCountdown.getServer().stop();
            serverCountdown.getStopCountDownLatch().await();
        }
    }
}
```

**Comment by janbartel** [comment]
The stopTimeout allows some time for connections that are already active to finish, after telling the thread pool not to accept any more incoming inrequests.  If you set 0, then its a harsh termination.

**Comment by rkhmelichek** [comment]
I think there's still a problem here with stopTimeout = 0.
The test code serially creates a new Jetty server, waits until start() is finished, makes an http request, terminates it, stops the server, and waits until the `lifeCycleStopped ` event.
Somehow an http request makes it to the instance whose thread pool is shutting down (so it rejects it).
But supposedly a new server has already been created and listening for new connections (and the old server should have been shutdown).

**Comment by janbartel** [comment]
@rkhmelichek not sure your analysis is correct. Your client never reads any input after opening the stream, so as far as jetty is concerned it has a connection and could be trying to send you content. You then harshly terminate the server, so the jobs that need to queue up to properly close the connector/connection are not let to run.

You'd have to take a series of thread dumps during your test and turn on debug (although that might change the timing, so tricky) to see better what is happening.
