### ISSUE TITLE
Embedded CDI: SessionScoped gives a NPE

### ISSUE THREAD

**Issue by fcorneli** [eclipse/jetty.project#1940]
When trying to use a SessionScoped CDI bean within the embedded CDI example, you get a NPE.
```
java.lang.NullPointerException
	at org.jboss.weld.context.beanstore.http.AbstractSessionBeanStore.getLockStore(AbstractSessionBeanStore.java:113)
	at org.jboss.weld.context.beanstore.AttributeBeanStore.lock(AttributeBeanStore.java:210)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:90)
	at org.jboss.weld.context.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:76)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:98)
	at org.jboss.weld.bean.proxy.CachedBeanInstance.getInstance(CachedBeanInstance.java:66)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
	at org.eclipse.jetty.cdi.servlet.MySessionClass$Proxy$_$$_WeldClientProxy.invoke(Unknown Source)
	at org.eclipse.jetty.cdi.servlet.MySessionServlet.doGet(MySessionServlet.java:21)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
```

Patch (against 9.4.8-SNAPSHOT) for the example below:
```
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java
new file mode 100644
index 0000000000..c7ec7c8a10
--- /dev/null
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java
@@ -0,0 +1,15 @@
+package org.eclipse.jetty.cdi.servlet;
+
+import java.io.Serializable;
+
+import javax.enterprise.context.SessionScoped;
+
+@SessionScoped
+public class MySessionClass implements Serializable
+{
+
+	public void invoke()
+	{
+
+	}
+}
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java
new file mode 100644
index 0000000000..fed987d2b7
--- /dev/null
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java
@@ -0,0 +1,24 @@
+package org.eclipse.jetty.cdi.servlet;
+
+import java.io.IOException;
+
+import javax.inject.Inject;
+import javax.servlet.ServletException;
+import javax.servlet.annotation.WebServlet;
+import javax.servlet.http.HttpServlet;
+import javax.servlet.http.HttpServletRequest;
+import javax.servlet.http.HttpServletResponse;
+
+@WebServlet(urlPatterns = "/session")
+public class MySessionServlet extends HttpServlet
+{
+
+	@Inject
+	private MySessionClass mySessionObject;
+
+	@Override
+	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException
+	{
+		this.mySessionObject.invoke();
+	}
+}
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
index 1eff479d8c..6fdb779ba3 100644
--- a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
@@ -66,6 +66,7 @@ public class WeldInitializationTest
         // Add some servlets
         context.addServlet(TimeServlet.class,"/time");
         context.addServlet(RequestInfoServlet.class,"/req-info");
+        context.addServlet(MySessionServlet.class,"/session");
 
         server.start();
 
@@ -117,4 +118,11 @@ public class WeldInitializationTest
             assertThat("Response", resp, containsString(" param[abc] = [123]"));
         }
     }
+
+    @Test
+    public void testSessionScoped() throws Exception
+    {
+    		HttpURLConnection http = (HttpURLConnection) serverHttpURI.resolve("session").toURL().openConnection();
+    		assertThat("response code", http.getResponseCode(), is(200));
+    }
 }
```

Remove the `@SessionScoped`and it works again, add it, and you have the NPE.

**Comment by joakime** [comment]
This seems like a Weld / CDI specific bug.

**Comment by janbartel** [comment]
@joakime  In the WeldInitializationTest class, it uses the EmbeddedCdiHandler to set up weld. It seems that the WeldInitializationListener is missing, which would listen for new sessions and set them up correctly.

**Comment by fcorneli** [comment]
Simply adding
```
ctx.addListener(new WeldInitialListener());
```
to `EmbeddedCdiHandler` unfortunately does not do the trick. Anyone knows how to hook this up?

**Comment by janbartel** [comment]
@fcorneli  I've pushed a fix to the EmbeddedCdiHandler in jetty-9.4.x. It should fix it, so please try and let me know.

**Comment by fcorneli** [comment]
That indeed fixes the issue. As for the unit test, I had to use the `SESSIONS` parameter on `EmbeddedCdiHandler` to make it work. See full patch below for working unit test:
```
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java
new file mode 100644
index 0000000000..c7ec7c8a10
--- /dev/null
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java
@@ -0,0 +1,15 @@
+package org.eclipse.jetty.cdi.servlet;
+
+import java.io.Serializable;
+
+import javax.enterprise.context.SessionScoped;
+
+@SessionScoped
+public class MySessionClass implements Serializable
+{
+
+	public void invoke()
+	{
+
+	}
+}
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java
new file mode 100644
index 0000000000..fed987d2b7
--- /dev/null
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java
@@ -0,0 +1,24 @@
+package org.eclipse.jetty.cdi.servlet;
+
+import java.io.IOException;
+
+import javax.inject.Inject;
+import javax.servlet.ServletException;
+import javax.servlet.annotation.WebServlet;
+import javax.servlet.http.HttpServlet;
+import javax.servlet.http.HttpServletRequest;
+import javax.servlet.http.HttpServletResponse;
+
+@WebServlet(urlPatterns = "/session")
+public class MySessionServlet extends HttpServlet
+{
+
+	@Inject
+	private MySessionClass mySessionObject;
+
+	@Override
+	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException
+	{
+		this.mySessionObject.invoke();
+	}
+}
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
index 1eff479d8c..3dee55ad4b 100644
--- a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
@@ -55,7 +55,7 @@ public class WeldInitializationTest
         connector.setPort(0);
         server.addConnector(connector);
 
-        EmbeddedCdiHandler context = new EmbeddedCdiHandler();
+        EmbeddedCdiHandler context = new EmbeddedCdiHandler(EmbeddedCdiHandler.SESSIONS);
 
         File baseDir = MavenTestingUtils.getTestResourcesDir();
 
@@ -66,6 +66,7 @@ public class WeldInitializationTest
         // Add some servlets
         context.addServlet(TimeServlet.class,"/time");
         context.addServlet(RequestInfoServlet.class,"/req-info");
+        context.addServlet(MySessionServlet.class,"/session");
 
         server.start();
 
@@ -117,4 +118,11 @@ public class WeldInitializationTest
             assertThat("Response", resp, containsString(" param[abc] = [123]"));
         }
     }
+
+    @Test
+    public void testSessionScoped() throws Exception
+    {
+        HttpURLConnection http = (HttpURLConnection) serverHttpURI.resolve("session").toURL().openConnection();
+        assertThat("response code", http.getResponseCode(), is(200));
+    }
 }
```

Maybe also interesting to add such unit test to Jetty itself?
Anyway, @janbartel  thanks for the fix!

**Comment by fcorneli** [comment]
Had to add headers in order to keep `license-maven-plugin` happy. Patch below:
```
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java
new file mode 100644
index 0000000000..33ea4d72eb
--- /dev/null
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionClass.java
@@ -0,0 +1,33 @@
+//
+//  ========================================================================
+//  Copyright (c) 1995-2017 Mort Bay Consulting Pty. Ltd.
+//  ------------------------------------------------------------------------
+//  All rights reserved. This program and the accompanying materials
+//  are made available under the terms of the Eclipse Public License v1.0
+//  and Apache License v2.0 which accompanies this distribution.
+//
+//      The Eclipse Public License is available at
+//      http://www.eclipse.org/legal/epl-v10.html
+//
+//      The Apache License v2.0 is available at
+//      http://www.opensource.org/licenses/apache2.0.php
+//
+//  You may elect to redistribute this code under either of these licenses.
+//  ========================================================================
+//
+
+package org.eclipse.jetty.cdi.servlet;
+
+import java.io.Serializable;
+
+import javax.enterprise.context.SessionScoped;
+
+@SessionScoped
+public class MySessionClass implements Serializable
+{
+
+	public void invoke()
+	{
+
+	}
+}
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java
new file mode 100644
index 0000000000..2ef6c5d4fc
--- /dev/null
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/MySessionServlet.java
@@ -0,0 +1,42 @@
+//
+//  ========================================================================
+//  Copyright (c) 1995-2017 Mort Bay Consulting Pty. Ltd.
+//  ------------------------------------------------------------------------
+//  All rights reserved. This program and the accompanying materials
+//  are made available under the terms of the Eclipse Public License v1.0
+//  and Apache License v2.0 which accompanies this distribution.
+//
+//      The Eclipse Public License is available at
+//      http://www.eclipse.org/legal/epl-v10.html
+//
+//      The Apache License v2.0 is available at
+//      http://www.opensource.org/licenses/apache2.0.php
+//
+//  You may elect to redistribute this code under either of these licenses.
+//  ========================================================================
+//
+
+package org.eclipse.jetty.cdi.servlet;
+
+import java.io.IOException;
+
+import javax.inject.Inject;
+import javax.servlet.ServletException;
+import javax.servlet.annotation.WebServlet;
+import javax.servlet.http.HttpServlet;
+import javax.servlet.http.HttpServletRequest;
+import javax.servlet.http.HttpServletResponse;
+
+@WebServlet(urlPatterns = "/session")
+public class MySessionServlet extends HttpServlet
+{
+
+	@Inject
+	private MySessionClass mySessionObject;
+
+	@Override
+	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException
+	{
+		this.mySessionObject.invoke();
+	}
+}
diff --git a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
index 1eff479d8c..3dee55ad4b 100644
--- a/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
+++ b/jetty-cdi/cdi-servlet/src/test/java/org/eclipse/jetty/cdi/servlet/WeldInitializationTest.java
@@ -55,7 +55,7 @@ public class WeldInitializationTest
         connector.setPort(0);
         server.addConnector(connector);
 
-        EmbeddedCdiHandler context = new EmbeddedCdiHandler();
+        EmbeddedCdiHandler context = new EmbeddedCdiHandler(EmbeddedCdiHandler.SESSIONS);
 
         File baseDir = MavenTestingUtils.getTestResourcesDir();
 
@@ -66,6 +66,7 @@ public class WeldInitializationTest
         // Add some servlets
         context.addServlet(TimeServlet.class,"/time");
         context.addServlet(RequestInfoServlet.class,"/req-info");
+        context.addServlet(MySessionServlet.class,"/session");
 
         server.start();
 
@@ -117,4 +118,11 @@ public class WeldInitializationTest
             assertThat("Response", resp, containsString(" param[abc] = [123]"));
         }
     }
+
+    @Test
+    public void testSessionScoped() throws Exception
+    {
+        HttpURLConnection http = (HttpURLConnection) serverHttpURI.resolve("session").toURL().openConnection();
+        assertThat("response code", http.getResponseCode(), is(200));
+    }
 }
```

**Comment by janbartel** [comment]
@fcorneli  would you like to contribute a pull request for this?

**Comment by fcorneli** [comment]
@janbartel PR at https://github.com/eclipse/jetty.project/pull/1994

**Comment by gregw** [comment]
i will retest with latest CDI integrations.
