### ISSUE TITLE
Loading resource content failed

### ISSUE THREAD

**Issue by xmanaugs** [eclipse/jetty.project#1981]
Hallo,

I am trying to start an embedded jetty web server as an eclipse plugin. The web contents are also packaged in the plugin.
When I try to load the files in the browser I got the following error: File cannot be found.

```
java.lang.RuntimeException: java.io.FileNotFoundException: \WebContent\app\index.html 
	at org.eclipse.jetty.http.ResourceHttpContent.getDirectBuffer(ResourceHttpContent.java:149)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:864)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:747)
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:723)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:294)
	at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:281)
	at com.kuka.viper.webinterface.internal.ViperResourceHandler.handle(ViperResourceHandler.java:66)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at com.kuka.viper.webinterface.internal.ViperSessionHandler.doHandle(ViperSessionHandler.java:37)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.kuka.viper.webinterface.HandlerList.handle(HandlerList.java:40)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
```

The problem is in the org.eclipse.jetty.util.resource.URLResource class. The getFile method returns a File which doesn't exist. One Solution could be in the  org.eclipse.jetty.util.BufferUtil class in the 
toBuffer(Resource resource,boolean direct)  method :

``` java
	public static ByteBuffer toBuffer(Resource resource,boolean direct) throws IOException {
		int len=(int)resource.length();
		if (len<0)
			throw new IllegalArgumentException("invalid resource: "+
				String.valueOf(resource)+" len="+len);
		
		ByteBuffer buffer = direct?BufferUtil.allocateDirect(len):BufferUtil.allocate(len);

		int pos=BufferUtil.flipToFill(buffer);
		//check if the file exists
		File resFile = resource.getFile();
		if (resFile !=null && resFile.exists())
			BufferUtil.readFrom(resource.getFile(),buffer);
		else
		{
			try (InputStream is = resource.getInputStream();)
			{
				BufferUtil.readFrom(is,len,buffer);
			}
		}
		BufferUtil.flipToFlush(buffer,pos);
		
		return buffer;
	}
```

**Comment by joakime** [comment]
How did you define your context's resource base?

Also, what does `com.kuka.viper.webinterface.internal.ViperResourceHandler.handle` do?

**Comment by xmanaugs** [comment]
Hi Joakime:

Here is the ViperResourceHandler  class

``` java

public class ViperResourceHandler extends ResourceHanlder {

	public ViperResourceHandler(Resource base) {
		setBaseResource(base);
	}
	
	@Override
	public void handle(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException
	{

		//
		// here some checking code
		//
		super.handle(target, baseRequest, request, response);
	}


	@Override
	public Resource getResource(String path) {
		
		if ("/app/".equals(path)) {
			return super.getResource("/app/index.html");
		}
		else if ("/".equals(path)) {
			return super.getResource("/index.html");
		}
		
		return super.getResource(path);

	}
	
}
```

On Starting the server I am initiating an instance of the ViperResourceHandler like this:
```java
URL webContentURL = WebInterfacePlugin.getDefault().getBundle().getEntry("/WebContent");
Resource resource = Resource.newResource(webContentURL);

//passing the base resource 
ViperResourceHandler resourceHandler = new ViperResourceHandler(resource);
```

**Comment by joakime** [comment]
The URL you use for the base resource should be absolute.  

The error shows an attempt at using a relative resource.

Consider ...

``` java
URL webContentURL = WebInterfacePlugin.getDefault().getBundle().getEntry("/WebContent");
if (webContentURL == null || !webContentURL.isAbsolute())
{
    throw new RuntimeException("Not a valid web content URL : " + webContentURL);
}
Resource resource = Resource.newResource(webContentURL);
```

**Comment by janbartel** [comment]
@xmanaugs I've just checked in a fix to URLResource that should always return null for getFile() method. This should force the use of getInputStream() in BufferUtil.  However, I can't guarantee that this will entirely fix your problem: equinox uses a bundleentry:/ url which always returns a relative location, not a full location on disk which is what jetty is generally expecting.  Please test and let me know how you get on.

**Comment by joakime** [comment]
Closing due to lack of update
