### ISSUE TITLE
standalone pushfilter: jetty.server.request not found

### ISSUE THREAD

**Issue by BodoWissemann** [eclipse/jetty.project#1982]
I'm working on a standalone-filter to extend our webapp (BaseX) if it's used with jetty. 
The goal is, to push some additionial resources when the response is beeing sent. 
The webapp defines, which resources have to be pushed. 

With embedded jetty, all goes well. But when deploying BaxeX als servlet to jetty and starting with jettx:run-forked,  i get this:

```
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Request
	at org.basex.http2.BaseXJettyPushFilter.doFilter(BaseXJettyPushFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        ...
```

This is the filter's pom.xml:

```xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.basex</groupId>
  <artifactId>basex-jetty-push-filter</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>basex-jetty-push-filter</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <jetty.version>9.4.6.v20170531</jetty.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-annotations</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-servlet</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-servlets</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-server</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-alpn-server</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.http2</groupId>
      <artifactId>http2-common</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.http2</groupId>
      <artifactId>http2-server</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-webapp</artifactId>
      <version>${jetty.version}</version>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.7.0</version>
          <configuration>
            <!-- http://maven.apache.org/plugins/maven-compiler-plugin/ -->
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
...
```

and i'm loading it as dependency here:

```xml
  <parent>
    <groupId>org.basex</groupId>
    <artifactId>basex-parent</artifactId>
    <version>9.0-SNAPSHOT</version>
    <relativePath>..</relativePath>
  </parent>

  <name>BaseX API</name>

  <dependencies>
    <dependency>
      <groupId>org.basex</groupId>
      <artifactId>basex</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.basex</groupId>
      <artifactId>basex-jetty-push-filter</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>net.xqj</groupId>
      <artifactId>basex-xqj</artifactId>
    </dependency>
    <dependency>
      <groupId>org.xmldb</groupId>
      <artifactId>xmldb-api</artifactId>
    </dependency>
    ...
```
    
It's clear why i can't access server-classes from within the webapp! The webapp shouldn't have any dependencies to the surrounding servlet-container, because it may change..

That's why i implemented the filter standalone, but somehow it still can't access the server.Request-class. 
Jetty's PushCacheFilter also uses the jetty.request-class, it should be possible!

Here's the filter:
https://github.com/BodoWissemann/basex-jetty-push-filter

How can i solve this problem? I'm stuck :(

Thx a lot!

Bodo

**Comment by sbordet** [comment]
@BodoWissemann you have it right that Servlet Container classes must be hidden to deployed web applications, and that is why you get the `NoClassDefFoundError` when you _deploy_ your web application to Jetty and not when you run it embedded.

Jetty's `PushCacheFilter` works because we have a default system classes rule for it in the web application classloader, see https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L128.

You should do the same for your `BaseXJettyPushFilter`: put it in the server classpath and define a system classes rule for it in the web application classloader.
I recommend you read the documentation about [creating a custom Jetty module](http://www.eclipse.org/jetty/documentation/9.4.x/custom-modules.html) and how to define a server classes rule following [this documentation](http://www.eclipse.org/jetty/documentation/9.4.x/custom-modules.html#custom-module-properties) and [this example](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-webapp/src/main/config/modules/webapp.mod).

Note that in Servlet 4 you won't need any of this because the API to use, `PushBuilder`, has been standardized in the Servlet APIs.

**Comment by BodoWissemann** [comment]
Hey, thank you very much for the fast reply!

I somehow considered the servlet-filter to be part of the container.. my fault!


And i've read about servlet-api 4.0, but can i already use it with jetty 9.x?

Or do i have to wait for jetty 10? If yes, when will jetty 10 be released?


Thx again

B

**Comment by sbordet** [comment]
Servlet 4 will be implemented in Jetty 10, and will be released when it's ready :), hopefully beginning of 2018.

**Comment by BodoWissemann** [comment]
Is it possible to add the server class rule using jetty-maven-plugin? I can't use the start.jar mechanism.

i tried

```
<configuration>
	<webApp>
	    <extraClasspath>${basedir}/src/main/webapp/extraServerClasses/basex-jetty-push-filter-1.0-SNAPSHOT.jar</extraClasspath>
	</webApp>
        <jvmArgs>
                -Xbootclasspath/p:${basedir}/alpn-boot-8.1.11.v20170118.jar
        </jvmArgs>
        <jettyXml>
       		${basedir}/src/main/webapp/WEB-INF/jetty-http.xml,
		${basedir}/src/main/webapp/WEB-INF/jetty-ssl-context.xml,
       		${basedir}/src/main/webapp/WEB-INF/jetty-ssl.xml,
       		${basedir}/src/main/webapp/WEB-INF/jetty-alpn.xml,
       		${basedir}/src/main/webapp/WEB-INF/jetty-http2.xml,   
	</jettyXml>
        <stopKey>keyToStopJetty</stopKey>
        <stopPort>8985</stopPort>
</configuration>   
```

and tried to use an override-web.xml file containing this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" 
        "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
 	<Call name="setExtraClasspath" ><Arg>./basex-jetty-push-filter-1.0-SNAPSHOT.jar</Arg>
       </Call>
</Configure>
```

But i couldn't get it running like this. Do i need the .mod-file anyway or should the jetty-maven-plugin work like this?
