### ISSUE TITLE
jetty: org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF

### ISSUE THREAD

**Issue by lidong14** [eclipse/jetty.project#1996]
i send a request through jetty , when the network is not good,it is easyly to appear the exception of early EOF. i know that the exception show the server closes the connection. i want to know why the jetty client not reconnect the server and if the later version add the features to guarantee the reliablility.
the jetty version is 9.2.21
the exception is below:

java.io.EOFException: HttpConnectionOverHTTP@14da25ed(l:/192.168.190.133:39559 <-> r:/192.168.191.223:8080,closed=false)[HttpChannelOverHTTP@1a1dd906(exchange=HttpExchange@1e224e9d req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@5b20d33d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@1e1070f9(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:277)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1283)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:182)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:129)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:89)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:123)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sbordet** [comment]
Jetty `HttpClient` does not have any automatic reconnect feature, also because most of the times a request cannot be resent when it fails.
As such, there is nothing that we can do if your network is lossy.

Your application can detect the failure and retry, if it whishes to do so, but the request may fail again (at which point your application can try again).

**Comment by lidong14** [comment]
i think  that it is good if the httpclient can reconnect when failed connect not send. because if connect failed ,it show the request not send to the sever. it does not affect server. i know it is not goog for send failed, because  perhaps the server has processed the request.

**Comment by sbordet** [comment]
`HttpClient` does try to open a new connection if a previous attempt to open a connection failed.
The stack trace you show above shows a failure while receiving a response, which means that the request has been sent already, and at that point `HttpClient` cannot retry it.

**Comment by lidong14** [comment]
yes，because i use a keepalive connection.According to your description，even if i use short links , can not solve this problem. only try again in client. can you give others advises？3Q
