### ISSUE TITLE
PreEncodedHttpField.putTo(ByteBuffer, HttpVersion)  java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by ligzy** [eclipse/jetty.project#2048]
I got eht exception some time http2 server response to client.

I debuged it and got these parameters:
version:HTTP_2
index(version) is 1,
But _encodedField just has only one element : status:429

so how to fix?

 public void putTo(ByteBuffer bufferInFillMode, HttpVersion version)
    {
        bufferInFillMode.put(_encodedField[index(version)]);
    }

java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:228) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:392) ~[dispatchserver-443.jar:?]
        at com.lenovo.cui.util.VSIUtil.handleEvent(VSIUtil.java:136) ~[dispatchserver-443.jar:?]
        at com.lenovo.cui.util.VSIUtil.handlePost(VSIUtil.java:495) ~[dispatchserver-443.jar:?]
        at com.lenovo.cui.servlet.EventServlet.handleRequest(EventServlet.java:86) [dispatchserver-443.jar:?]
        at com.lenovo.cui.servlet.EventServlet$1.run(EventServlet.java:65) [dispatchserver-443.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.eclipse.jetty.http.PreEncodedHttpField.putTo(PreEncodedHttpField.java:119) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.hpack.HpackEncoder.encode(HpackEncoder.java:289) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.hpack.HpackEncoder.encode(HpackEncoder.java:174) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.generator.HeadersGenerator.generateHeaders(HeadersGenerator.java:72) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.generator.HeadersGenerator.generate(HeadersGenerator.java:56) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.generator.Generator.control(Generator.java:80) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.HTTP2Session$ControlEntry.generate(HTTP2Session.java:1144) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:168) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.HTTP2Session.frame(HTTP2Session.java:680) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.HTTP2Session.frames(HTTP2Session.java:652) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.HTTP2Stream.headers(HTTP2Stream.java:91) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.sendHeaders(HttpTransportOverHTTP2.java:200) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:128) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:730) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:786) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234) ~[dispatchserver-443.jar:?]
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:218) ~[dispatchserver-443.jar:?]

**Comment by gregw** [comment]
Jetty version?

**Comment by gregw** [comment]
The field pre-encoders are discovered by the ServiceLoader.  In this case, HTTP/2 requires the `HpackFieldPreEncoder` class to be discovered by the service loader, which should be in `http2-hpack-9.4???.jar`.

Can you check your classpath for this jar and the class within it?

Also running with
```
   java -Dorg.eclipse.jetty.http.PreEncodedHttpField.LEVEL=DEBUG ...
```
should give debugging about the pre encoder discovery.

**Comment by ligzy** [comment]
jetty version is: 9.4.7.v20170914.
You mean that i  should obviously put the dependency in my pom.xml?
let me try.


<dependency>
    <groupId>org.eclipse.jetty.http2</groupId>
    <artifactId>http2-hpack</artifactId>
    <version>9.4.7.v20170914</version>
</dependency>

**Comment by olamy** [comment]
@ligzy yes

**Comment by gregw** [comment]
@ligzy you should not have to explicitly declare that if you are dependent on http2-client, as http2-hpack is a transient dependency:
```
[INFO] org.eclipse.jetty.http2:http2-client:jar:9.4.9-SNAPSHOT
[INFO] +- org.eclipse.jetty.http2:http2-common:jar:9.4.9-SNAPSHOT:compile
[INFO] |  \- org.eclipse.jetty.http2:http2-hpack:jar:9.4.9-SNAPSHOT:compile
```

Besides, you must have the http2-hpack jar on your class path, as I can see classes from it in your stack trace.    So the question remains why doesn't your ServiceLoader see the `HpackFieldPreEncoder`?

More info is needed about how you are building your project and the logging asked for previously would be really handy.

**Comment by ligzy** [comment]
> //
> //  ========================================================================
> //  Copyright (c) 1995-2017 Mort Bay Consulting Pty. Ltd.
> //  ------------------------------------------------------------------------
> //  All rights reserved. This program and the accompanying materials
> //  are made available under the terms of the Eclipse Public License v1.0
> //  and Apache License v2.0 which accompanies this distribution.
> //
> //      The Eclipse Public License is available at
> //      http://www.eclipse.org/legal/epl-v10.html
> //
> //      The Apache License v2.0 is available at
> //      http://www.opensource.org/licenses/apache2.0.php
> //
> //  You may elect to redistribute this code under either of these licenses.
> //  ========================================================================
> //
> 
> 
> package org.eclipse.jetty.http;
> 
> import java.nio.ByteBuffer;
> import java.util.ArrayList;
> import java.util.Arrays;
> import java.util.Iterator;
> import java.util.List;
> import java.util.ServiceLoader;
> 
> import org.eclipse.jetty.util.log.Log;
> import org.eclipse.jetty.util.log.Logger;
> 
> 
> /* ------------------------------------------------------------ */
> /** Pre encoded HttpField.
>  * <p>A HttpField that will be cached and used many times can be created as 
>  * a {@link PreEncodedHttpField}, which will use the {@link HttpFieldPreEncoder}
>  * instances discovered by the {@link ServiceLoader} to pre-encode the header 
>  * for each version of HTTP in use.  This will save garbage 
>  * and CPU each time the field is encoded into a response.
>  * </p>
>  */
> public class PreEncodedHttpField extends HttpField
> {
>     private final static Logger LOG = Log.getLogger(PreEncodedHttpField.class);
>     private final static HttpFieldPreEncoder[] __encoders;
>     
>     static
>     { 
>         List<HttpFieldPreEncoder> encoders = new ArrayList<>();
>         Iterator<HttpFieldPreEncoder> iter = ServiceLoader.load(HttpFieldPreEncoder.class).iterator();
>         while (iter.hasNext())
>         {
>             try
>             {
>                 HttpFieldPreEncoder encoder = iter.next();
>                 if (index(encoder.getHttpVersion())>=0)
>                     encoders.add(encoder);
>             }
>             catch(Error|RuntimeException e)
>             {
>                 LOG.debug(e);
>             }
>         }
>         LOG.debug("HttpField encoders loaded: {}",encoders);
>         int size=encoders.size();
>         
>         __encoders = new HttpFieldPreEncoder[size==0?1:size];
>         for (HttpFieldPreEncoder e:encoders)
>         {
>             int i = index(e.getHttpVersion());
>             if (__encoders[i]==null)
>                 __encoders[i] = e;
>             else
>                 LOG.warn("multiple PreEncoders for "+e.getHttpVersion());
>         }
>         
>         // Always support HTTP1
>         if (__encoders[0]==null)
>             __encoders[0] = new Http1FieldPreEncoder();              
>     }
>     
>     private static int index(HttpVersion version)
>     {
>         switch (version)
>         {
>             case HTTP_1_0:
>             case HTTP_1_1:
>                 return 0;
> 
>             case HTTP_2:
>                 return 1;
> 
>             default:
>                 return -1;
>         }
>     }
>     
>     private final byte[][] _encodedField=new byte[__encoders.length][];
> 
>     public PreEncodedHttpField(HttpHeader header,String name,String value)
>     {
>         super(header,name, value);
>         for (int i=0;i<__encoders.length;i++)
>             _encodedField[i]=__encoders[i].getEncodedField(header,header.asString(),value);
>     }
>     
>     public PreEncodedHttpField(HttpHeader header,String value)
>     {
>         this(header,header.asString(),value);
>     }
>     
>     public PreEncodedHttpField(String name,String value)
>     {
>         this(null,name,value);
>     }
>     
>     public void putTo(ByteBuffer bufferInFillMode, HttpVersion version)
>     {
>         bufferInFillMode.put(_encodedField[index(version)]);
>     }
> }
> 

encoders i found it just contain only 1,but i use http2.

**Comment by ligzy** [comment]
when i 
		response.setStatus(HttpServletResponse.SC_NO_CONTENT);
		response.setContentType("application/json; charset=utf-8");

**Comment by ligzy** [comment]
i use the servlet in two thread.
how to fix? i have add the dependency.

**Comment by ligzy** [comment]
Http1FieldPreEncoder implements HttpFieldPreEncoder
 public class HpackFieldPreEncoder implements HttpFieldPreEncoder

i breakpoint and don't  seen the **HpackFieldPreEncoder** called.

**Comment by ligzy** [comment]
20:56:54.258 [main] DEBUG o.e.jetty.http.PreEncodedHttpField - HttpField encoders loaded: [org.eclipse.jetty.http.Http1FieldPreEncoder@f79a760]

**Comment by ligzy** [comment]
i have fixed.
fixed:

src/main/resources/META-INF/services/org.eclipse.jetty.http.HttpFieldPreEncoder
added:

org.eclipse.jetty.http.Http1FieldPreEncoder
org.eclipse.jetty.http2.hpack.HpackFieldPreEncoder

**Comment by joakime** [comment]
That's pointing at a much more fundamental flaw in your setup/environment.

The standard `ServiceLoader` mechanism will pull the `META-INF/services/org.eclipse.jetty.http.HttpFieldPreEncoder` from the http2-hpack artifact, if its present on your classpath.

See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.8.v20171121/jetty-http2/http2-hpack/src/main/resources/META-INF/services/org.eclipse.jetty.http.HttpFieldPreEncoder

If you are modifying/munging/merging/uberjar/shading/rebuilding the jetty artifacts, you have to also merge all `META-INF/services/*` found, **from all jars with similarly named service files** (this is important!).

Example: The maven shade plugin has this feature built-in as a Resource Transformer.
See: https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html

The specific transformer for `META-INF/services` files is called `ServicesResourceTransformer`.
See: https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer

**Comment by luduoduo** [comment]
You don't need to do anything following:
- manually add hpack dependency in pom
- manually add implments description in meta-inf/services
because the description is right there in hpack jar. The issue was just because maven did not merge meta-inf together, you need use maven plugin to do that like this.
```
assembly.xml
<containerDescriptorHandlers>
        <containerDescriptorHandler>
            <handlerName>metaInf-services</handlerName>
    </containerDescriptorHandlers>

```
