### ISSUE TITLE
Can't run Weld with jetty-maven-plugin 9.4.8, CDI version mismatch

### ISSUE THREAD

**Issue by havardw** [eclipse/jetty.project#2078]
With  jetty-maven-plugin 9.4.8 I get the following exception on startup when Weld is active:
org.jboss.weld.exceptions.IllegalStateException: WELD-000144: CDI API version mismatch. CDI 1.0 API detected on classpath. Weld requires version 1.1 or better.

I've attached [an example project](https://github.com/eclipse/jetty.project/files/1584461/jetty-weld-minimal.zip) that demonstrates the issue. This seems to be an regression from 9.4.7.

Running maven with "-X" shows the following dependency tree on startup, it seems like it's ":org.eclipse.sisu.plexus" that's bringing in CDI 1.0. I've tried to add cdi-api 1.2 to my project, that doesn't help.
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.5.0:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.5.0:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3:compile

**Comment by olamy** [comment]
can you try adding cdi-api 1.2 in the jetty maven plugin dependencies section.
```
      <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>${jetty.version}</version>
        <dependencies>
          <dependency>
            <groupId>javax.enterprise</groupId>
            <artifactId>cdi-api</artifactId>
            <version>1.2</version>
          </dependency>
        </dependencies>
      </plugin>
```

**Comment by havardw** [comment]
When I add cdi-api 1.2 I get  a ClassNotFoundException for com.sun.el.ExpressionFactoryImpl.

I tried to add a EL-implementation. I picked org.glassfish.web:javax.el:2.2.6:jar, not sure if this is the right one.

After I add that as well, I get the following stacktrace:
java.lang.IllegalStateException: Unable to access CDI
	at javax.enterprise.inject.spi.CDI.current(CDI.java:65)
	at org.jboss.weld.servlet.WeldInitialListener.contextInitialized(WeldInitialListener.java:94)
	at org.jboss.weld.servlet.api.helpers.ForwardingServletListener.contextInitialized(ForwardingServletListener.java:34)
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:66)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:329)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1515)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1477)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:428)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:461)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:327)

**Comment by olamy** [comment]
remove the empty beans.xml file and it will work see https://github.com/olamy/jetty-weld-minimal

**Comment by janbartel** [comment]
@havardw  the correct solution is **not** to add the cdi-1.2 jar to the plugin classpath. That will open you to a world of pain, because you will then have the cdi api **both** on the plugin classpath, and also inside your webapp from the weld-servlet jar.

You just need to exclude the older cdi api jar that the sisu jar transitively depends upon. Your pom should look like:

```xml
   <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>${jetty.version}</version>
                <configuration>
                    <!-- Set up configuration for Weld. -->
                    <contextXml>${basedir}/src/main/jetty/jetty-context.xml</contextXml>
                </configuration>
                <dependencies>
                  <dependency>
                    <groupId>org.eclipse.sisu</groupId>
                    <artifactId>org.eclipse.sisu.plexus</artifactId>
                    <version>0.3.3</version>
                    <exclusions>
                      <exclusion>
                        <groupId>javax.enterprise</groupId>
                        <artifactId>cdi-api</artifactId>
                      </exclusion>
                    </exclusions>
                  </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```

Ideally, it would not be necessary to exclude stuff that maven puts onto the classpath - I've opened a new issue to see if it is possible to exclude more of the maven machinery jars:  #2080.

**Comment by olamy** [comment]
definitely need a solution as any Maven upgrade (i.e sisu upgrade) can possibly break this fix.

**Comment by janbartel** [comment]
@olamy, strenuously agree :)  But it's hard to solve  - I've made some observations over on #2080, so lets continue the conversation on that issue over there.

**Comment by havardw** [comment]
Thanks @janbartel, I tried to find a way to exclude the CDI dependency, but didn't think of doing it by overriding the plugin dependency.

@olamy Maybe my example is a bit too minimalistic, the example does indeed work when you remove beans.xml, but that is because Weld is never properly started (check the log statements). An example that uses CDI for something would fail with "missing dependency", as Weld doesn't seem to consider the app directory as an archive without the beans.xml when running with an unassembled webapp.
