### ISSUE TITLE
Getting org.eclipse.jetty.io.EofException while using HttpClient with proxy (HttpProxy)

### ISSUE THREAD

**Issue by dpnkr** [eclipse/jetty.project#2122]
Here is my code :  

``` java                
SslContextFactory sslContextFactory = new SslContextFactory();
HttpClient httpClient = new HttpClient(sslContextFactory);

httpClient.start();

ProxyConfiguration proxyConfiguration = httpClient.getProxyConfiguration();

HttpProxy httpProxy = new HttpProxy("127.0.0.1",8082);
proxyConfiguration.getProxies().add(httpProxy);

Request request = httpClient.newRequest(new URI("https://google.com"));
request.method(HttpMethod.GET);

ContentResponse contentResponse = request.send();
System.out.println(contentResponse.getContentAsString());
```

Can anyone suggest me where I'm doing the mistake to set the proxy  to httpclient ??

Error stack from eclipse  :  
.....................................................................................................................................................................................................................
```
2018-01-16 10:16:49.168:INFO::main: Logging initialized @125ms
java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:653)
	at Get.main(Get.java:32)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:808)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:108)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:204)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:78)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:204)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:78)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:36)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:26)
	at org.eclipse.jetty.client.PoolingHttpDestination$2.run(PoolingHttpDestination.java:144)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:265)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:474)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 15 more
```

.....................................................................................................................................................................................................................

For the proxy server I'm using Burp . This is also noticeable  that the moment I change the endpoint address to "http:// google.com" from "https:// google.com" it starts working .

I'm using jetty version 9.2.13 .

**Comment by sbordet** [comment]
The code should work.

Would be great if you can report the DEBUG logs with the exception and stack trace you report in the issue subject.

**Comment by dpnkr** [comment]
Hi Simone,

Thanks for your response.
Error stack from eclipse  :  
.....................................................................................................................................................................................................................
```
2018-01-16 10:16:49.168:INFO::main: Logging initialized @125ms
java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:653)
	at Get.main(Get.java:32)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:808)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:108)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:204)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:78)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:204)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:78)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:36)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:26)
	at org.eclipse.jetty.client.PoolingHttpDestination$2.run(PoolingHttpDestination.java:144)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:265)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:474)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 15 more
```

.....................................................................................................................................................................................................................

For the proxy server I'm using Burp . This is also noticeable  that the moment I change the endpoint address to "http:// google.com" from "https:// google.com" it starts working .

For the debug log , I'm not sure how to generate that. Can you tell me the steps of generating debug logs for jetty ?

Fyi : I'm using jetty version 9.2.13

**Comment by dpnkr** [comment]
Hi Simon,

I got something after googling about the issue . Seems like long back someone has already reported about the issue to jetty-dev@eclipse.org. 
 Can you check this 
[https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02237.html](url)

He also faced the similar issue like me . 
Can you tell me what resolution has been provided to him ??

**Comment by dpnkr** [comment]
Some more information on this .

I have tried the same code with Jetty version 9.4.5 and it is working without any error.
Please note that I have limitation which is I have to build my application on jre 1.7 to work with one old application server.

I also tried by setting my eclipse environment to 1.7 and then adding the jetty version 9.4.5 but it shows major.minor error which is very usual thing.

Because of java version limitation I had to use jetty version  9.2.13.v20150730 which is causing the problem.

So does jetty has some fix/version where the issue is fixed and  it has not used any latest features of Java 8 ??

**Comment by sbordet** [comment]
The latest version of Jetty 9.2.x is 9.2.24. Have you tried that ?

**Comment by dpnkr** [comment]
Thanks for the info . With the version of 9.2.24 it is working as expected.
But I don't see org.eclipse.jetty.util.ajax in that zip file . 

Has it been removed from this version ??
If yes can I use the mentioned jar from the older version of jetty like 9.2.13 along with other jars from 9.2.24 ?

I was only using the JSON parser from that package , so this is not very critical one as I can manage those . But it would be good if I somehow get that feature from jetty itself . It will help me in not touching the code for json parser .

**Comment by sbordet** [comment]
Package `org.eclipse.jetty.util.ajax` is defined by module `jetty-util-ajax`, and it is present in 9.2.24.
Perhaps you just need to explicitly add it as a dependency.

**Comment by dpnkr** [comment]
Now everything is sorted out for me . Please close this issue.
Thanks again for all your help.
