### ISSUE TITLE
CometD and Jetty compatibility

### ISSUE THREAD

**Issue by Pratibha24** [eclipse/jetty.project#2143]
Hi,

While using jetty's older jars, we used to call cancel() function to cancel the exchange. but now how can we achieve it with the jetty 9?

In addition to that, I am using CometD 3.1.3 jar in a project with Jetty version 9.4.7 and but i get noClassDefFoundError for org/cometd/common/JettyJSONContext$FieldJSON. I have found that since class org.eclipse.jetty.util.ajax.JSON is missing in Jetty that's why i am getting this error. Could you please let me know which the compatible version of jetty to use with CometD 3.1.3 library ? 

Regards,
Pratibha

**Comment by Pratibha24** [comment]
Hi Simone,

One question here is, i have a code snippet like below in my project:
public class ChannelRequest implements Response.Listener{
public void invoke(HttpClient client) {
		try {
			//create a new Httprequest for this request
			createRequest(client);
			//add the authorization header as needed
			final Runnable runnable = new Runnable() {
				public void run() {
					try {
						request.send();
						RuntimeException err = getError();
						throw ex;
					}
				}
			}
			runnable.run();
		}
	}		
}

@Override
	public void onSuccess(Response res) {
 // Logging the events
}

I have found that when it executes the send() then it starts executing the next line of codes while i want as soon as send method is done its job then it should start calling the overridden callback methods.
How can i achieve that?

Regards,
Pratibha

**Comment by sbordet** [comment]
@Pratibha24, it's not clear what the problem is.
The snippet above wraps some code into a `Runnable`, just to call `run()` immediately after.
There is no sign of you registering a `Response.Listener`.
Have a read at the [HttpClient documentation](https://www.eclipse.org/jetty/documentation/current/http-client.html).

**Comment by Pratibha24** [comment]
I did not get this part "There is no sign of you registering a Response.Listener.", how do we register ?
In the documentation also, i did not find anything related to registering the listener.

Even i have tried like below as well: 
`public class ChannelRequest implements Response.Listener{
public void invoke(HttpClient client) {
		try {
			//create a new Httprequest for this request
			createRequest(client);
			//add the authorization header as needed
			final Runnable runnable = new Runnable() {
				public void run() {
					try {
						request.
                                                 onResponseSuccess((res) -> { 
                                                            // Some code   
       }
.send(new Response.Listener.Adapter() {
							@Override
							public void onFailure(Response res, Throwable failure){
								super.onFailure(res, failure);
							}
							@Override
							public void onComplete(Result result)
							{
								super.onComplete(result);
							}
						});
						RuntimeException err = getError();
						throw ex;
					}
				}
			}
			runnable.run();
		}
	}		
}

But still the same behavior.

**Comment by sbordet** [comment]
@Pratibha24 you are describing a (possibly wrong) solution.
What is the _problem_ ?
What do you want to do ?

**Comment by Pratibha24** [comment]
I have got to know the problem here, may be i am not correct.
The problem is, earlier we have exchange.waitForDone(), where it was doing the exchange and then used to fallback to the callback methods.
but now after calling the send(), immediately it does not wait and executes the next line. And after few seconds it falls back to callback method.
Even Though i have overridden the onComplete method using Response.Listener.Adapter(), my code executes it vary late. Could you please let me know how can i wait after calling the send() and when onComplete gets called.

Thanks,
Pratibha

**Comment by sbordet** [comment]
@Pratibha24 please read the [documentation about HttpClient](https://www.eclipse.org/jetty/documentation/current/http-client-api.html), it is all written there.

You want to use the blocking API to wait for `send()` to return with the response - that is the equivalent of calling the old `waitForDone()`.

**Comment by Pratibha24** [comment]
Okay. I got it.  As per the doc, i need to send the request in Sync way:
ContentResponse response = request.send();
Now my question is, if a send the request in synchronous way or  then is there any callback which happens or i need to handle it manually whether response is successful or failure?

**Comment by sbordet** [comment]
@Pratibha24 I don't understand ?
If the request is successful, you get the `ContentResponse` object back, otherwise you get an exception back.

**Comment by Pratibha24** [comment]
-> If request/response fails in that case it throws exception?
-> Then, How can we make out whether request has got failed or response.? Because in case if we use FutureResponseListener, then there is a way to override the onComplete() and using result object we can use getRequestFailure() or getResponseFailure().
But if i do not want to use this listener, and simply do ContentResponse res=request.send(); then how can i get to know whther request has failed or response?

**Comment by sbordet** [comment]
> If request/response fails in that case it throws exception?

Yes.

**Comment by Pratibha24** [comment]
-> Then, How can we make out whether request has got failed or response.? Because in case if we use FutureResponseListener, then there is a way to override the onComplete() and using result object we can use getRequestFailure() or getResponseFailure().
But if i do not want to use this listener, and simply do ContentResponse res=request.send(); then how can i get to know whther request has failed or response?

**Comment by Pratibha24** [comment]
Thanks a lot Simone.. You are really helpful! :1st_place_medal:

**Comment by Pratibha24** [comment]
Simone, i have one more question, if i send the request and its successful. So will it then start streaming the data from the backend to which i connect?

**Comment by sbordet** [comment]
Please. Read. The. [Documentation](https://www.eclipse.org/jetty/documentation/current/http-client-api.html).

All your questions here are already answered in that section.

**Comment by Pratibha24** [comment]
Hello,

I have tried below using jetty 9.4.8 and getting  Timeout Exception :
SslContextFactory sslContextFactory = new SslContextFactory();
		HttpClient httpClient = new HttpClient(sslContextFactory);
		httpClient.setConnectTimeout(30000);
		httpClient.start();

		
		Request request = httpClient.newRequest(new URI("https://stream.twitter.com/1.1/statuses/filter.json?track=cloudstreams,wmic"));
		request.method(HttpMethod.POST);
		request.header(HttpHeader.CONTENT_TYPE, "application/json");
		request.timeout(30000, TimeUnit.MILLISECONDS);
		String authzHdr = "XXXXXXXX";
		request.header(HttpHeader.AUTHORIZATION, authzHdr);
		ContentResponse contentResponse = request.send();
		System.out.println(">>>>>>>>>>>:"+contentResponse.toString());

As soon as i send the request, after 30 seconds it gives me timeout exception.
Exception in thread "main" java.util.concurrent.TimeoutException
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:109)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:684)
	at TwitterTest.main(TwitterTest.java:104)

Please advise.

**Comment by sbordet** [comment]
@Pratibha24 so you want to send a `POST` request to the server, but you don't specify the request content. The server is waiting for the request content until it times out.

**Comment by Pratibha24** [comment]
For given endpoint, body is not required but method is post only. I have tried with GET as well as POST with null request content , then also it din't work.

**Comment by sbordet** [comment]
@Pratibha24 sorry I have a hard time believing that a `POST` request with `Content-Type: application/json` does not require a content.
I doubt you are using the Twitter endpoints correctly.
