### ISSUE TITLE
Verify working directory permissions on startup

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2198]
We have reports that on badly configured systems, the working directory (jvm temp, jetty.base temp, or webapp temp) with insufficient filesystem permissions to create/write files will fail silently.

No error or warning is produced if Jetty cannot us the temp/work directory.

We should consider startup failure for the server startup cases, and webapp startup failure for the configured webapp specific cases.

**Comment by janbartel** [comment]
@joakime  I've tested back to jetty-9.1.6 using java -jar start.jar command line, and all fail with stacktrace exception if the given tmp dir does not have execute permission, eg:

For 9.1.6:
Starting Jetty: java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at java.io.File.createTempFile(File.java:1989)
	at java.io.File.createTempFile(File.java:2040)
	at org.eclipse.jetty.start.StartArgs.getMainArgs(StartArgs.java:494)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:287)
	at org.eclipse.jetty.start.Main.start(Main.java:737)
	at org.eclipse.jetty.start.Main.main(Main.java:103)


For 9.4.8:
java.nio.file.AccessDeniedException: /tmp/foo/start_54430668749414858.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
	at java.base/java.nio.file.Files.createFile(Files.java:640)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
	at java.base/java.nio.file.Files.createTempFile(Files.java:905)
	at org.eclipse.jetty.start.StartArgs.getMainArgs(StartArgs.java:627)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:211)
	at org.eclipse.jetty.start.Main.start(Main.java:504)
	at org.eclipse.jetty.start.Main.main(Main.java:78)


Additionally, WebInfConfiguration tests during the deployment of a webapp that the tmp directory is in fact a directory and is writeable and throws an error if it isn't.

Do you have more specific information?

**Comment by janbartel** [comment]
Closing as jetty start throws an error if the tmp dir isn't useable, and the WebInfConfiguration which unpacks the webapp to tmp dir already checks if the dir is useable or not.
