### ISSUE TITLE
NPE at org.eclipse.jetty.client.HttpDestination.newExchangeQueue

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#2210]
Version 9.4.8.v20171121

There seems to be some sort of race conditions when invoking `WebSocketClient.connect()` that is initialized with a custom `HttpClient`.

I am getting this exception:

```
java.lang.NullPointerException: null
	at org.eclipse.jetty.client.HttpDestination.newExchangeQueue(HttpDestination.java:125)
	at org.eclipse.jetty.client.HttpDestination.<init>(HttpDestination.java:70)
	at org.eclipse.jetty.client.PoolingHttpDestination.<init>(PoolingHttpDestination.java:25)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.<init>(HttpDestinationOverHTTP.java:32)
	at org.eclipse.jetty.client.http.HttpClientTransportOverHTTP.newHttpDestination(HttpClientTransportOverHTTP.java:50)
	at org.eclipse.jetty.client.HttpClient.destinationFor(HttpClient.java:535)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:568)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:723)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:707)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.send(WebSocketUpgradeRequest.java:540)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.sendAsync(WebSocketUpgradeRequest.java:545)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:389)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:324)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:306)
	at com.holdmyspot.pyramid.binance.BinanceOrderStream.connect(BinanceOrderStream.java:145)
	at com.holdmyspot.pyramid.binance.BinanceOrderStream.lambda$addOrderListener$1(BinanceOrderStream.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

which (as far as I can tell) can only occur if `HttpClient.send()` is invoked before `HttpClient.start()`. But I am not invoking `HttpClient.start()` directly so I think the bug is internal to Jetty. My code looks roughly like this:

```
		HttpClient httpClient = new HttpClient();
		httpClient.setRequestBufferSize(8192);
		WebSocketClient client = new WebSocketClient(httpClient);
		try
		{
			client.setMaxIdleTimeout(0);
			client.start();
		}
		catch (Exception e)
		{
			throw new AssertionError("We didn't register any lifecycle listeners that could fail", e);
		}
		URI uri = getVeryLongUri(); // URI with very long query parameter values  
		WebSocketListener websocketListener = getMyListener(); // instance of WebSocketListener
		Future<Session> sessionProvider = client.connect(websocketListener, uri); // Exception thrown here
```

Any ideas?

**Comment by joakime** [comment]
@sbordet do we need stronger "!running" or "!started" checks in HttpClient?

**Comment by cowwoc** [comment]
@joakime I actually tried starting the `HttpClient` before passing it into the `WebSocketClient`, or invoking `WebSocketClient.addBean(HttpClient)` and sure enough it got me over this initial hurdle but then I got a follow-up error. Something along the lines of `NPE at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.newConnection()`.

I gave up and instead used `new WebSocketClient().getHttpClient().setRequestBufferSize(...)` and that finally worked. I'm still not clear on why the `SslClientConnectionFactory` was giving me NPEs.

**Comment by joakime** [comment]
Why are you setting the RequestBufferSize on a websocket call?

**Comment by joakime** [comment]
As for your SSL issue.

It's likely because you didn't give the HttpClient a configured SslContextFactory.
That means there's no SSL support available.

http://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/client/HttpClient.html#HttpClient-org.eclipse.jetty.util.ssl.SslContextFactory-

**Comment by joakime** [comment]
In Jetty 9.4.x the WebSocketClient is the implementation for native jetty websockets along with the base class for JSR356 Client WebSocketContainer. 
The JSR356 spec says supporting `wss://` urls is mandated, so that means the default usage of WebSocketClient is also supporting `wss://`.

**Comment by joakime** [comment]
Reopening to add safety checks to WebSocketClient ...

* send()  / connectToServer() / connect() calls should check for HttpClient isStarted/isRunning
* if `wss://` is used in send()  / connectToServer() / connect() the existence of HttpClient.getSslContextFactory() should be validated.

**Comment by cowwoc** [comment]
> Why are you setting the RequestBufferSize on a websocket call?

See https://stackoverflow.com/q/48908234/14731

> As for your SSL issue.
> It's likely because you didn't give the HttpClient a configured SslContextFactory.
> That means there's no SSL support available.

Oh. That makes perfect sense. Thank you.
