### ISSUE TITLE
JDK9 Test failure: org.eclipse.jetty.hazelcast.session.client.ClientSessionExpiryTest.testSessionExpiresWithListener

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2214]
https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/1230/testReport/junit/org.eclipse.jetty.hazelcast.session.client/ClientSessionExpiryTest/linux_jdk9___Test___testSessionExpiresWithListener/

**Comment by joakime** [comment]
Log from test failure (for future search juice)

```
Stacktrace
java.lang.AssertionError

Standard Error
Feb 21, 2018 11:46:27 PM com.hazelcast.internal.cluster.impl.operations.MembersUpdateOp
SEVERE: [172.17.0.7]:5702 [dev] [3.9.3] targetUuid: d20a6f46-e17a-483f-a8e4-76db8859937f is different than this node's uuid: 24ce2981-d984-4dcd-81d0-386720d45374
java.lang.IllegalStateException: targetUuid: d20a6f46-e17a-483f-a8e4-76db8859937f is different than this node's uuid: 24ce2981-d984-4dcd-81d0-386720d45374
	at com.hazelcast.internal.cluster.impl.operations.MembersUpdateOp.checkLocalMemberUuid(MembersUpdateOp.java:103)
	at com.hazelcast.internal.cluster.impl.operations.MembersUpdateOp.run(MembersUpdateOp.java:66)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)

2018-02-21 23:46:39.159:INFO:oejs.Server:main: jetty-9.4.9-SNAPSHOT; built: 2018-02-21T23:06:33Z; git: f887bf340df4b3c482046fab008465a04b2a0fa7; jvm 9.0.1+11
2018-02-21 23:46:39.160:INFO:oejs.session:main: DefaultSessionIdManager workerName=w34
2018-02-21 23:46:39.160:WARN:oejs.session:main: Short interval of 1sec for session scavenging.
2018-02-21 23:46:39.160:INFO:oejs.session:main: Scavenging every 1100ms
2018-02-21 23:46:39.160:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@6d31bae5{/,null,AVAILABLE}
2018-02-21 23:46:39.160:INFO:oejs.AbstractConnector:main: Started ServerConnector@761e1290{HTTP/1.1,[http/1.1]}{0.0.0.0:33017}
2018-02-21 23:46:39.161:INFO:oejs.Server:main: Started @350771ms
2018-02-21 23:46:44.223:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@761e1290{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2018-02-21 23:46:44.362:INFO:oejsh.ContextHandler:main: Stopped o.e.j.s.ServletContextHandler@6d31bae5{/,null,UNAVAILABLE}
2018-02-21 23:46:44.363:INFO:oejs.session:main: Stopped scavenging
2018-02-21 23:46:44.363:WARN:oejs.session:Scheduler-732445761: 
com.hazelcast.core.HazelcastException: java.lang.InterruptedException
	at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:40)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:124)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:69)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:129)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:206)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:198)
	at com.hazelcast.client.proxy.ClientMapProxy.removeInternal(ClientMapProxy.java:325)
	at com.hazelcast.client.proxy.ClientMapProxy.remove(ClientMapProxy.java:318)
	at org.eclipse.jetty.hazelcast.session.HazelcastSessionDataStore.delete(HazelcastSessionDataStore.java:89)
	at org.eclipse.jetty.server.session.AbstractSessionCache.delete(AbstractSessionCache.java:628)
	at org.eclipse.jetty.server.session.SessionHandler.removeSession(SessionHandler.java:1049)
	at org.eclipse.jetty.server.session.SessionHandler.invalidate(SessionHandler.java:1234)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.expireAll(DefaultSessionIdManager.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.scavenge(SessionHandler.java:1276)
	at org.eclipse.jetty.server.session.HouseKeeper.scavenge(HouseKeeper.java:273)
	at org.eclipse.jetty.server.session.HouseKeeper$Runner.run(HouseKeeper.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: 
java.lang.InterruptedException
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.onInterruptDetected(ClientInvocationFuture.java:57)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:204)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:198)
	at com.hazelcast.client.proxy.ClientMapProxy.removeInternal(ClientMapProxy.java:325)
	at com.hazelcast.client.proxy.ClientMapProxy.remove(ClientMapProxy.java:318)
	at org.eclipse.jetty.hazelcast.session.HazelcastSessionDataStore.delete(HazelcastSessionDataStore.java:89)
	at org.eclipse.jetty.server.session.AbstractSessionCache.delete(AbstractSessionCache.java:628)
	at org.eclipse.jetty.server.session.SessionHandler.removeSession(SessionHandler.java:1049)
	at org.eclipse.jetty.server.session.SessionHandler.invalidate(SessionHandler.java:1234)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.expireAll(DefaultSessionIdManager.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.scavenge(SessionHandler.java:1276)
	at org.eclipse.jetty.server.session.HouseKeeper.scavenge(HouseKeeper.java:273)
	at org.eclipse.jetty.server.session.HouseKeeper$Runner.run(HouseKeeper.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:204)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:198)
	at com.hazelcast.client.proxy.ClientMapProxy.removeInternal(ClientMapProxy.java:325)
	at com.hazelcast.client.proxy.ClientMapProxy.remove(ClientMapProxy.java:318)
	at org.eclipse.jetty.hazelcast.session.HazelcastSessionDataStore.delete(HazelcastSessionDataStore.java:89)
	at org.eclipse.jetty.server.session.AbstractSessionCache.delete(AbstractSessionCache.java:628)
	at org.eclipse.jetty.server.session.SessionHandler.removeSession(SessionHandler.java:1049)
	at org.eclipse.jetty.server.session.SessionHandler.invalidate(SessionHandler.java:1234)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.expireAll(DefaultSessionIdManager.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.scavenge(SessionHandler.java:1276)
	at org.eclipse.jetty.server.session.HouseKeeper.scavenge(HouseKeeper.java:273)
	at org.eclipse.jetty.server.session.HouseKeeper$Runner.run(HouseKeeper.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by janbartel** [comment]
This test no longer exists.
