### ISSUE TITLE
JDK9 Test failure: org.eclipse.jetty.server.NotAcceptingTest.testLocalConnector

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2230]
`jetty-9.4.x` branch.
Linux build.

```
Error Details
/four

Stack Trace
java.lang.AssertionError: /four
	at org.eclipse.jetty.server.NotAcceptingTest.testLocalConnector(NotAcceptingTest.java:186)

Standard Error
[AdvancedRunner] Running org.eclipse.jetty.server.NotAcceptingTest.testLocalConnector()
2018-02-22 21:50:52.277:INFO:oejs.Server:main: jetty-9.4.9-SNAPSHOT; built: 2018-02-22T21:43:49Z; git: c751a8b1bbfdc73549bc9136f091b67270d9859e; jvm 1.8.0_152-b16
2018-02-22 21:50:52.278:INFO:oejs.AbstractConnector:main: Started LocalConnector@109fff4a{HTTP/1.1,[http/1.1]}
2018-02-22 21:50:52.279:INFO:oejs.Server:main: Started @172210ms
2018-02-22 21:50:52.281:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@109fff4a{HTTP/1.1,[http/1.1]}
```

**Comment by joakime** [comment]
This test is flaky on local machine too, but gives a different error.

```
2018-02-22 17:05:57.905:INFO:oejs.AbstractConnector:main: Started LocalConnector@12cdcf4{HTTP/1.1,[http/1.1]}
2018-02-22 17:05:57.905:INFO:oejs.Server:main: Started @30538ms
2018-02-22 17:06:08.410:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@12cdcf4{HTTP/1.1,[http/1.1]}

java.util.concurrent.TimeoutException
	at java.util.concurrent.Exchanger.exchange(Exchanger.java:626)
	at org.eclipse.jetty.server.NotAcceptingTest.testLocalConnector(NotAcceptingTest.java:192)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.eclipse.jetty.toolchain.test.AdvancedRunner.runChild(AdvancedRunner.java:133)
	at org.eclipse.jetty.toolchain.test.AdvancedRunner.runChild(AdvancedRunner.java:72)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:67)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

That is the exchanger triggering a `TimeoutException` where didn't expect it.

**Comment by joakime** [comment]
My experience with `LocalConnector` in the `jetty-10.0.x-websocket` branch is that its a super flaky object, do we need this test?

**Comment by joakime** [comment]
The original reported failure is because the `Exchanger.exchange()` did not timeout and worked for the "delayed connection" behavior/flow.

Not sure how this is supposed to timeout in the first place.
It seems to expect that the `LocalEndPoint.addInputAndExecute()` should take longer then 500ms to process.
When it fails, the processing is less then 500ms.

**Comment by gregw** [comment]
I improved part of these tests, but ignored the testLocalConnector for now as the not accepting capability is not needed in the local connector

**Comment by joakime** [comment]
Closing as fixed.
