### ISSUE TITLE
JDK8 Test failure: org.eclipse.jetty.server.LowResourcesMonitorTest.testMaxLowResourceTime

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2236]
`jetty-9.4.x` branch.
Linux build.
Bare metal build. (no container / docker)

```
Error Message
Broken pipe (Write failed)

Stacktrace
java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.LowResourcesMonitorTest.testMaxLowResourceTime(LowResourcesMonitorTest.java:240)

Standard Error
[AdvancedRunner] Running org.eclipse.jetty.server.LowResourcesMonitorTest.testMaxLowResourceTime()
2018-02-22 23:29:29.188:INFO:oejs.Server:main: jetty-9.4.9-SNAPSHOT; built: 2018-02-22T23:21:30Z; git: 4d2cbf76d7969df741032731f80d2e774a9e7587; jvm 1.8.0_152-b16
2018-02-22 23:29:29.257:INFO:oejs.AbstractConnector:main: Started ServerConnector@5c3f9618{HTTP/1.1,[http/1.1]}{0.0.0.0:40873}
2018-02-22 23:29:29.258:INFO:oejs.Server:main: Started @225645ms
2018-02-22 23:29:30.157:WARN:oejs.LowResourceMonitor:Timer-32: Low Resources: Max memory exceeded: 332720936>1
2018-02-22 23:29:34.189:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@5c3f9618{HTTP/1.1,[http/1.1]}{0.0.0.0:0}

```

**Comment by joakime** [comment]
This has also failed in docker / container builds on JDK9.

```
Error
Broken pipe (Write failed)

Stacktrace
java.net.SocketException: Broken pipe (Write failed)
at org.eclipse.jetty.server.LowResourcesMonitorTest.testMaxLowResourceTime(LowResourcesMonitorTest.java:240)

Standard Error
[AdvancedRunner] Running org.eclipse.jetty.server.LowResourcesMonitorTest.testMaxLowResourceTime()
2018-02-22 07:55:55.248:INFO:oejs.Server:main: jetty-9.4.9-SNAPSHOT; built: 2018-02-22T07:49:08Z; git: e46459e8a89a7086b8578f83ab8e9b11e6306433; jvm 9.0.1+11
2018-02-22 07:55:55.264:INFO:oejs.AbstractConnector:main: Started ServerConnector@20c4be8d{HTTP/1.1,[http/1.1]}{0.0.0.0:39301}
2018-02-22 07:55:55.264:INFO:oejs.Server:main: Started @221795ms
2018-02-22 07:55:56.164:WARN:oejs.LowResourceMonitor:Timer-32: Low Resources: Max memory exceeded: 240245248>1
2018-02-22 07:56:00.196:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@20c4be8d{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
```
