### ISSUE TITLE
Test failure: org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2237]
`jetty-9.4.x` branch.
Linux build.
Bare metal build. (no container / docker)

```
Error Message
java.net.SocketException: Broken pipe (Write failed)

Stacktrace
javax.net.ssl.SSLException: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI(SelectChannelServerSslTest.java:115)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI(SelectChannelServerSslTest.java:115)

Standard Error
[AdvancedRunner] Running org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI()
2018-02-22 22:17:56.948:INFO:oejs.Server:main: jetty-9.4.9-SNAPSHOT; built: 2018-02-22T22:08:21-06:00; git: 8bd27cd18a8cb2e31d47ed23cf85b16da49075b8; jvm 9.0.1+11
2018-02-22 22:17:57.047:INFO:oejus.SslContextFactory:main: x509=X509@14d513ca(jetty,h=[jetty.eclipse.org],w=[]) for SslContextFactory@be9cc86[provider=null,keyStore=file:///home/jenkins/jenkins_home/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q@2/jetty-server/src/test/resources/keystore,trustStore=file:///home/jenkins/jenkins_home/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q@2/jetty-server/src/test/resources/keystore]
2018-02-22 22:17:57.048:INFO:oejus.SslContextFactory:main: x509=X509@68af8288(mykey,h=[],w=[]) for SslContextFactory@be9cc86[provider=null,keyStore=file:///home/jenkins/jenkins_home/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q@2/jetty-server/src/test/resources/keystore,trustStore=file:///home/jenkins/jenkins_home/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q@2/jetty-server/src/test/resources/keystore]
2018-02-22 22:17:57.048:INFO:oejs.AbstractConnector:main: Started ServerConnector@8dc3019{SSL,[ssl, http/1.1]}{0.0.0.0:42755}
2018-02-22 22:17:57.049:INFO:oejs.Server:main: Started @283537ms
2018-02-22 22:17:57.049:INFO:oejs.HttpConnection:main: expect URI is too large, then ISE extra data ...
2018-02-22 22:17:57.100:WARN:oejh.HttpParser:qtp1977568029-723: URI is too large >8192
2018-02-22 22:17:57.115:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@8dc3019{SSL,[ssl, http/1.1]}{0.0.0.0:0}
```

**Comment by joakime** [comment]
This test has been overhauled and no longer failing.

**Comment by WalkerWatch** [comment]
This test is still intermittently failing. I've seen it both on JDK9 and JDK11 recently. Links and relevant information as follows.

JDK 9, Build [367](https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/367/testReport/junit/org.eclipse.jetty.server.ssl/SelectChannelServerSslTest/linux_jdk9___Test___jdk9___testFullURI/)

> **Error Message**
`java.net.SocketException: Broken pipe (Write failed)`
**Stacktrace**
`javax.net.ssl.SSLException: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI(SelectChannelServerSslTest.java:124)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI(SelectChannelServerSslTest.java:124)`
**Standard Error**
`[AdvancedRunner] Running org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI()
2018-05-30 16:17:42.858:INFO:oejs.Server:main: jetty-9.4.11-SNAPSHOT; built: 2018-05-30T16:13:14.293Z; git: b75a2df67935aec18b5896aca70502adf4a0a267; jvm 9.0.4+11
2018-05-30 16:17:42.869:INFO:oejus.SslContextFactory:main: x509=X509@5de15ce1(jetty,h=[jetty.eclipse.org],w=[]) for SslContextFactory@33544cc5[provider=null,keyStore=file:///home/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore,trustStore=file:///home/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore]
2018-05-30 16:17:42.870:INFO:oejus.SslContextFactory:main: x509=X509@2080ee70(mykey,h=[],w=[]) for SslContextFactory@33544cc5[provider=null,keyStore=file:///home/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore,trustStore=file:///home/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore]
2018-05-30 16:17:42.871:INFO:oejs.AbstractConnector:main: Started ServerConnector@1bce19db{SSL,[ssl, http/1.1]}{0.0.0.0:41747}
2018-05-30 16:17:42.871:INFO:oejs.Server:main: Started @106162ms
2018-05-30 16:17:42.872:INFO:oejs.HttpConnection:main: expect URI is too large, then ISE extra data ...
2018-05-30 16:17:42.886:WARN:oejh.HttpParser:qtp2061891477-4331: URI is too large >8192
2018-05-30 16:17:42.892:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@1bce19db{SSL,[ssl, http/1.1]}{0.0.0.0:0}`

JDK 11, Build [372](https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/372/testReport/junit/org.eclipse.jetty.server.ssl/SelectChannelServerSslTest/linux_jdk11___Test___jdk11___testFullURI/)

> **Error Message**
`java.net.SocketException: Broken pipe (Write failed)`
**Stacktrace**
`javax.net.ssl.SSLException: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI(SelectChannelServerSslTest.java:124)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI(SelectChannelServerSslTest.java:124)`
**Standard Error**
`[AdvancedRunner] Running org.eclipse.jetty.server.ssl.SelectChannelServerSslTest.testFullURI()
2018-05-31 17:33:06.898:INFO:oejs.Server:main: jetty-9.4.11-SNAPSHOT; built: 2018-05-31T17:28:16.094Z; git: 4acc4e798bf256502c081a9d7fbd240d4403793f; jvm 11-ea+15
2018-05-31 17:33:06.900:INFO:oejus.SslContextFactory:main: x509=X509@36f1046f(jetty,h=[jetty.eclipse.org],w=[]) for SslContextFactory@56d93692[provider=null,keyStore=file:///home/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore,trustStore=file:///home/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore]
2018-05-31 17:33:06.900:INFO:oejus.SslContextFactory:main: x509=X509@1686f0b4(mykey,h=[],w=[]) for SslContextFactory@56d93692[provider=null,keyStore=file:///home/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore,trustStore=file:///home/jenkins/workspace/jetty.project_jetty-9.4.x-INBQ7QOOOQAKBR7QXCZRBSZMK7E2XO45CPMMWPFUPSXZHYWIIW5Q/jetty-server/src/test/resources/keystore]
2018-05-31 17:33:06.901:INFO:oejs.AbstractConnector:main: Started ServerConnector@76c548f{SSL,[ssl, http/1.1]}{0.0.0.0:42543}
2018-05-31 17:33:06.901:INFO:oejs.Server:main: Started @114976ms
2018-05-31 17:33:06.902:INFO:oejs.HttpConnection:main: expect URI is too large, then ISE extra data ...
2018-05-31 17:33:06.918:WARN:oejh.HttpParser:qtp791499503-3106: URI is too large >8192
2018-05-31 17:33:06.920:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@76c548f{SSL,[ssl, http/1.1]}{0.0.0.0:0}`

**Comment by sbordet** [comment]
The test tries to send a too large HTTP/1.1 URI, expecting the server to reply with a `414`.

The request is written to a 64 KiB array that is then written to the server.

The server has a 8 KiB max request line + headers, so after it reads 8 KiB will send the 414 response and close the connection.

The test passes if the whole 64 KiB can be written to the server before the server replies and closes the connection.
If the 64 KiB write happens in 2 packets that are delayed by some time, the second packet is written to a closed connection, causing the broken pipe.

This is easily reproducible by splitting the write of the 64 KiB in 2 writes separated by 100 ms.

**Comment by joakime** [comment]
Out of curiosity, if this same server setup is used with our HttpClient, does our HttpClient response contain the 414?

**Comment by sbordet** [comment]
@joakime I would guess so, although the client will (like this test) occasionally fail on the request side - the response should always be successful with the `414`.

**Comment by gregw** [comment]
I'm trying with the URI reduced to just 10k, so it should better avoid being split.
If that doesn't work, we should reduce the configured max size and do an even smaller write.

**Comment by sbordet** [comment]
@gregw I fixed it already, I'm pushing the fix right now.
