### ISSUE TITLE
JDK8 Test failure: org.eclipse.jetty.util.thread.strategy.ExecutionStrategyTest.blockingProducerTest

### ISSUE THREAD

**Issue by phoe** [eclipse/jetty.project#2268]
Intermittent issue while building `jetty-9.4.x` branch on Linux barebone.

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ uname -a
Linux phoebox 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Jetty :: Utilities 9.4.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java) @ jetty-util ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-junit-dep.jar) @ jetty-util ---
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:parse-version (set-osgi-version) @ jetty-util ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.0:prepare-agent (jacoco-initialize) @ jetty-util ---
[INFO] argLine set to -javaagent:/home/emiherd/.m2/repository/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/home/emiherd/git/jetty.project/jetty-util/target/jacoco.exec,excludes=**/org/eclipse/jetty/ant/**:**/org/eclipse/jetty/maven/**:**/org/eclipse/jetty/jspc/**:**/org/eclipse/jetty/embedded/**:**/org/eclipse/jetty/asyncrest/**:**/org/eclipse/jetty/demo/**:**/org/eclipse/jetty/gcloud/**:**/org/eclipse/jetty/infinispan/**:**/org/eclipse/jetty/osgi/**:**/org/eclipse/jetty/spring/**:**/org/eclipse/jetty/http/spi/**:**/org/eclipse/jetty/tests/**:**/org/eclipse/jetty/test/**
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (create-buildnumber) @ jetty-util ---
[INFO] Executing: /bin/sh -c cd '/home/emiherd/git/jetty.project/jetty-util' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/emiherd/git/jetty.project/jetty-util
[INFO] Storing buildNumber: c684295f7e1676a65af8ac3bfc8156c1492ac908 at timestamp: 1519904054155
[INFO] Storing buildScmBranch: jetty-9.4.x
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ jetty-util ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ jetty-util ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 1 resource
[INFO] 
[INFO] --- jetty-version-maven-plugin:2.5:attach-version-text (attach-version) @ jetty-util ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.2:compile (default-compile) @ jetty-util ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 159 source files to /home/emiherd/git/jetty.project/jetty-util/target/classes
[INFO] /home/emiherd/git/jetty.project/jetty-util/src/main/java/org/eclipse/jetty/util/resource/EmptyResource.java: Some input files use or override a deprecated API.
[INFO] /home/emiherd/git/jetty.project/jetty-util/src/main/java/org/eclipse/jetty/util/resource/EmptyResource.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/emiherd/git/jetty.project/jetty-util/src/main/java/org/eclipse/jetty/util/Promise.java: Some input files use unchecked or unsafe operations.
[INFO] /home/emiherd/git/jetty.project/jetty-util/src/main/java/org/eclipse/jetty/util/Promise.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] >>> maven-pmd-plugin:3.8:check (named-logging-enforcement) > :pmd @ jetty-util >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:pmd (pmd) @ jetty-util ---
[INFO] 
[INFO] <<< maven-pmd-plugin:3.8:check (named-logging-enforcement) < :pmd @ jetty-util <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:check (named-logging-enforcement) @ jetty-util ---
[INFO] 
[INFO] 
[INFO] >>> maven-source-plugin:3.0.1:jar (attach-sources) > generate-sources @ jetty-util >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java) @ jetty-util ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-junit-dep.jar) @ jetty-util ---
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:parse-version (set-osgi-version) @ jetty-util ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.0:prepare-agent (jacoco-initialize) @ jetty-util ---
[INFO] argLine set to -javaagent:/home/emiherd/.m2/repository/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/home/emiherd/git/jetty.project/jetty-util/target/jacoco.exec,excludes=**/org/eclipse/jetty/ant/**:**/org/eclipse/jetty/maven/**:**/org/eclipse/jetty/jspc/**:**/org/eclipse/jetty/embedded/**:**/org/eclipse/jetty/asyncrest/**:**/org/eclipse/jetty/demo/**:**/org/eclipse/jetty/gcloud/**:**/org/eclipse/jetty/infinispan/**:**/org/eclipse/jetty/osgi/**:**/org/eclipse/jetty/spring/**:**/org/eclipse/jetty/http/spi/**:**/org/eclipse/jetty/tests/**:**/org/eclipse/jetty/test/**
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (create-buildnumber) @ jetty-util ---
[INFO] Executing: /bin/sh -c cd '/home/emiherd/git/jetty.project/jetty-util' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/emiherd/git/jetty.project/jetty-util
[INFO] Storing buildNumber: c684295f7e1676a65af8ac3bfc8156c1492ac908 at timestamp: 1519904068300
[INFO] Storing buildScmBranch: jetty-9.4.x
[INFO] 
[INFO] <<< maven-source-plugin:3.0.1:jar (attach-sources) < generate-sources @ jetty-util <<<
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar (attach-sources) @ jetty-util ---
[INFO] Building jar: /home/emiherd/git/jetty.project/jetty-util/target/jetty-util-9.4.9-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-bundle-plugin:3.3.0:manifest (default) @ jetty-util ---
[WARNING] Manifest org.eclipse.jetty:jetty-util:jar:9.4.9-SNAPSHOT : Unused Import-Package instructions: [javax.transaction*] 
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ jetty-util ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 30 resources
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.2:testCompile (default-testCompile) @ jetty-util ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ jetty-util ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eclipse.jetty.util.UptimeTest
Uptime = 4,837
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.43 s - in org.eclipse.jetty.util.UptimeTest
[INFO] Running org.eclipse.jetty.util.MultiExceptionTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.eclipse.jetty.util.MultiExceptionTest
[INFO] Running org.eclipse.jetty.util.Utf8LineParserTest
2018-03-01 12:34:40.980:INFO::main: Logging initialized @5104ms to org.eclipse.jetty.util.log.StdErrLog
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.231 s - in org.eclipse.jetty.util.Utf8LineParserTest
[INFO] Running org.eclipse.jetty.util.IPAddressMapTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 s - in org.eclipse.jetty.util.IPAddressMapTest
[INFO] Running org.eclipse.jetty.util.thread.ReservedThreadExecutorTest
[WARNING] Corrupted stdin stream in forked JVM 1. See the dump file /home/emiherd/git/jetty.project/jetty-util/target/surefire-reports/2018-03-01T12-34-34_911-jvmRun1.dumpstream
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 3.562 s - in org.eclipse.jetty.util.thread.ReservedThreadExecutorTest
[INFO] Running org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsumeTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsumeTest
[INFO] Running org.eclipse.jetty.util.thread.strategy.ExecutionStrategyTest
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at org.eclipse.jetty.util.thread.strategy.ExecutionStrategyTest$3.produce(ExecutionStrategyTest.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:342)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:189)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:139)
	at org.eclipse.jetty.util.thread.strategy.ExecutionStrategyTest$4.run(ExecutionStrategyTest.java:206)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:753)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:671)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.057 s <<< FAILURE! - in org.eclipse.jetty.util.thread.strategy.ExecutionStrategyTest
[ERROR] blockingProducerTest[class org.eclipse.jetty.util.thread.strategy.EatWhatYouKill](org.eclipse.jetty.util.thread.strategy.ExecutionStrategyTest)  Time elapsed: 33.479 s  <<< FAILURE!
java.lang.AssertionError
	at org.eclipse.jetty.util.thread.strategy.ExecutionStrategyTest.blockingProducerTest(ExecutionStrategyTest.java:216)
...
[ERROR] Failures: 
[ERROR]   ExecutionStrategyTest.blockingProducerTest:216
[INFO] 
[ERROR] Tests run: 1029, Failures: 1, Errors: 0, Skipped: 59
```

**Comment by joakime** [comment]
The ExecutionStrategyTest has undergone a review and overhaul since this was filed.
Closing as fixed.
