### ISSUE TITLE
NPE from start.jar during JVM version parsing

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2284]
During the `jetty-distribution` build, we encountered this NPE ...

```
[INFO] --- maven-pmd-plugin:3.8:check (named-logging-enforcement) @ jetty-distribution ---
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (setup home) @ jetty-distribution ---
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom (11 kB at 164 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom (58 kB at 656 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar (54 kB at 626 kB/s)
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.util.Formatter.parse(Formatter.java:2547)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.eclipse.jetty.start.UsageException.<init>(UsageException.java:38)
	at org.eclipse.jetty.start.StartArgs.setProperty(StartArgs.java:1278)
	at org.eclipse.jetty.start.Modules.<init>(Modules.java:65)
	at org.eclipse.jetty.start.Main.processCommandLine(Main.java:313)
	at org.eclipse.jetty.start.Main.main(Main.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE
```

**Comment by gregw** [comment]
the problem is going to be caused by a problem parsing a JVM version.
I have pushed a commit that will stop the NPE, but there will still be the JVM version parsing problem... but we should be able to see it.  Please run again against the commit

**Comment by olamy** [comment]
> java.lang.ExceptionInInitializerError
	at org.eclipse.jetty.start.StartArgs.setProperty(StartArgs.java:1268)
	at org.eclipse.jetty.start.Modules.<init>(Modules.java:65)
	at org.eclipse.jetty.start.Main.processCommandLine(Main.java:313)
	at org.eclipse.jetty.start.Main.main(Main.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid version string: '1.8.0_151-8u151-b12-1~deb9u1-b12'
	at org.eclipse.jetty.start.shaded.util.JavaVersion.parse(JavaVersion.java:53)
	at org.eclipse.jetty.start.shaded.util.JavaVersion.<clinit>(JavaVersion.java:47)
	... 10 more

**Comment by gregw** [comment]
@olamy thanks for that.  The problem was we were not handling ~ in the version string.  I have fixed with explicit adding of `~`, but wonder if we should be more flexible.

**Comment by joakime** [comment]
Perhaps instead of using the system property we could use something like this ...

``` java
String version = Runtime.class.getPackage().getImplementationVersion();
```

**Comment by joakime** [comment]
So, it seems "java.runtime.version" is the long form of the java version string from system properties.

@olamy on that system that had the "~" in the version string, what do the following system properties show?

```
  java.version
  java.runtime.version
  java.vm.version
  java.specification.version
  java.vm.specification.version
```

**Comment by olamy** [comment]
`
java.version :1.8.0_151
java.runtime.version :1.8.0_151-8u151-b12-1~deb9u1-b12
java.vm.version :25.151-b12
java.specification.version :1.8
java.vm.specification.version :1.8
`

**Comment by olamy** [comment]
by the way it's fixed :-)

**Comment by joakime** [comment]
yeah, i think the long form `java.runtime.version` is just asking for headaches.
(which lines up with [JEP 223 suggestions](http://openjdk.java.net/jeps/223) too)

Is the information in `java.version` sufficient for our purposes?

**Comment by gregw** [comment]
with all the volatility of version stuff, I'm not keen to change where we get the version... only to then discover a whole bunch more variability.
Let's sit with this now and review when the next JVM version breaks us.

**Comment by joakime** [comment]
We are currently using `java.runtime.version`, but that's a change from our history.

**Example from `jetty-9.4.x` HEAD**

https://github.com/eclipse/jetty.project/blob/ff341fb42060c3c337414a1fa8f04a132aa9d225/jetty-util/src/main/java/org/eclipse/jetty/util/JavaVersion.java#L47

We used to be using `java.version`.

**Example from `jetty-9.3.x` HEAD**

https://github.com/eclipse/jetty.project/blob/d41bcec681441b4123a16f6abb1f0356316cf736/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java#L1165-L1181

**Comment by joakime** [comment]
For those reading this issue (presumably because you've hit this problem), can you please run the following code (with your `jetty-util.jar` in the classpath) and report your results.

``` java
import org.eclipse.jetty.util.JavaVersion;

public class TestVersions
{
    public static String getObjectVersion()
    {
        return Object.class.getPackage().getImplementationVersion();
    }

    public static void main(String[] args)
    {
        System.out.println("java.version = " + System.getProperty("java.version"));
        System.out.println("java.runtime.version = " + System.getProperty("java.runtime.version"));
        System.out.println("java.vm.version = " + System.getProperty("java.vm.version"));
        System.out.println("java.specification.version = " + System.getProperty("java.specification.version"));
        System.out.println("java.vm.specification.version = " + System.getProperty("java.vm.specification.version"));
        System.out.println("Object.class.package.implementationVersion = " + getObjectVersion());
        System.out.println("JavaVersion.VERSION = " + JavaVersion.VERSION);
    }
}
```

**Comment by joakime** [comment]
Interesting, did you know that `java.runtime.version` is not considered a core java system property (It can even be null)?

* https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html
* (JDK8) https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#getProperties--
* (JDK9) https://docs.oracle.com/javase/9/docs/api/java/lang/System.html#getProperties--

**Comment by joakime** [comment]
Also, the following can be used to dump all of the JVM level properties.

``` shell
$ java -XshowSettings:all
```

You can even filter it 

``` shell
$ java -XshowSettings:all 2>&1 | grep -i version
```

**Comment by gregw** [comment]
I'm getting more and more convinced.... let me try something....

**Comment by joakime** [comment]
Closing as implemented.
