### ISSUE TITLE
BadMessageException with certain file when using multipart-upload

### ISSUE THREAD

**Issue by lglowania** [eclipse/jetty.project#2315]
I tried to replace Commons' FileUpload with the servlet multipart implementation but when experimenting that certain file could not be uploaded:
https://drive.google.com/open?id=1PM6HeyodeoQRyC6IzRGpq04m4gQ_3VYZ

org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content

jetty.version "9.4.8.v20171121", Ubuntu 16

**Comment by janbartel** [comment]
@lglowania  can you:

- describe if you're using the (deprecated)MultiPartFilter, or are you using @MultiPart annotation
- describe configuration of either the filter or annotation
- post more of the log, including any exception stack traces
- post a capture of the http dialog with something like ethereal/wireshark etc etc

**Comment by lglowania** [comment]
The problem has nothing to do with the certain file but with file size which was configured by using web.xml.
```xml
<multipart-config>
    <location>/tmp</location>
    <max-file-size>20848820</max-file-size>
    <max-request-size>1073741824</max-request-size>
    <file-size-threshold>1048576</file-size-threshold>
</multipart-config>
```

But i still wondered, why i got such a poor exception message because this is really all:
`2018-03-13 09:06:38.543:WARN:oejs.HttpChannel:qtp2015601401-15: /_nodes/files org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content`.
And the exception does not _bubble_ to the surrounding try-catch block.

I isolated the problem in a separate project. I still don't know, why in my orginal project the exception is swallowed but in the isolatetd project i get a stack trace and the problem roots from querying an url-paramater before using multipart. 

```
org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content
	at org.eclipse.jetty.server.Request.getParameters(Request.java:380)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:1021)
	at jettyproject_issue2315.UploadServlet.doPost(UploadServlet.java:20)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Multipart Mime part scribus_svn.tar.gz exceeds max filesize
	at org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart.write(MultiPartInputStreamParser.java:133)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:748)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:441)
	at org.eclipse.jetty.server.Request.getParts(Request.java:2335)
	at org.eclipse.jetty.server.Request.extractMultipartParameters(Request.java:543)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:467)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:376)
	... 35 more
```
Is it part of the specs, that you can't query url-params in a multi-part request or would it a good idea to make that possible in jetty?

**Comment by lglowania** [comment]
Here's the repo of my isolated project: https://github.com/lglowania/jettyproject-issue2315

**Comment by joakime** [comment]
The Servlet Spec makes all of the `HttpServletRequest.getParameter*()` methods behave like this ...

1) All query parameters are parsed.
2) If the request has `Content-Type: application/x-www-form-urlencoded` then parse the request body contents for more parameters.
3) If the request has `Content-Type: multipart/form-data` *and* a `<multipart-config>` or `@MultipartConfig` then parse the request body contents for more parameters.  The content parsed here is now available in the `HttpServletRequest.getPart*()` methods.

The point is, a "parameter" isn't exclusive to just the query, it applies to the request body contents as well.

This is why nearly all mature libraries that use the servlet spec avoid using the `HttpServletRequest.getParameter*()` methods if they are only interested in the query values (these libraries parse the query string directly and avoid the side effects that `.getParameter*()` entirely)

**Comment by janbartel** [comment]
Just to add to what @joakime  said, it is a requirement of the spec that the form contents can be put into the parameters:  thus, there is no choice but to thoroughly parse all parts of the request to gather all parameters.

I don't know why you didn't get more of the exception in your other project - probably something to do with your logging configuration maybe?

I don't think there's anything to fix in jetty so I'm closing this issue. If you find it that the exception wasn't logged properly due to a bug in jetty, please reopen.
