### ISSUE TITLE
OSX Testing Failures in jetty-io

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2341]
The recent changes in `jetty-9.4.x` HEAD have tickled something on the OSX builds.
We have many test failures now.

```
[INFO] Running org.eclipse.jetty.io.IdleTimeoutTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.295 s - in org.eclipse.jetty.io.IdleTimeoutTest
[INFO] Running org.eclipse.jetty.io.IOTest
[ERROR] Tests run: 9, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.254 s <<< FAILURE! - in org.eclipse.jetty.io.IOTest
[ERROR] testHalfCloseClientServer(org.eclipse.jetty.io.IOTest)  Time elapsed: 0.032 s  <<< ERROR!
java.net.ConnectException: Connection refused
	at org.eclipse.jetty.io.IOTest.testHalfCloseClientServer(IOTest.java:184)

[ERROR] testHalfCloseBadClient(org.eclipse.jetty.io.IOTest)  Time elapsed: 0.001 s  <<< ERROR!
java.net.ConnectException: Connection refused
	at org.eclipse.jetty.io.IOTest.testHalfCloseBadClient(IOTest.java:249)

[ERROR] testServerChannelInterrupt(org.eclipse.jetty.io.IOTest)  Time elapsed: 0.001 s  <<< ERROR!
java.net.ConnectException: Connection refused
	at org.eclipse.jetty.io.IOTest.testServerChannelInterrupt(IOTest.java:327)

[INFO] Running org.eclipse.jetty.io.MappedByteBufferPoolTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 s - in org.eclipse.jetty.io.MappedByteBufferPoolTest
[INFO] Running org.eclipse.jetty.io.NIOTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in org.eclipse.jetty.io.NIOTest
[ERROR] testSelector(org.eclipse.jetty.io.NIOTest)  Time elapsed: 0.001 s  <<< ERROR!
java.net.ConnectException: Connection refused
	at org.eclipse.jetty.io.NIOTest.testSelector(NIOTest.java:47)

[INFO] Running org.eclipse.jetty.io.SelectChannelEndPointInterestsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.618 s - in org.eclipse.jetty.io.SelectChannelEndPointInterestsTest
[INFO] Running org.eclipse.jetty.io.SelectChannelEndPointSslTest
2018-03-15 09:37:59.127:INFO:oejus.SslContextFactory:main: x509=X509@25a5c7db(mykey,h=[],w=[]) for SslContextFactory@4d27d9d[provider=null,keyStore=file:///Users/jenkins/workspace/nightlies/jetty-9.4.x-mac-nightly/jetty-io/src/test/resources/keystore,trustStore=null]
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /Users/jenkins/workspace/nightlies/jetty-9.4.x-mac-nightly/jetty-io/target/surefire-reports/2018-03-15T09-35-35_033-jvmRun1.dumpstream
[ERROR] Tests run: 9, Failures: 0, Errors: 6, Skipped: 1, Time elapsed: 0.581 s <<< FAILURE! - in org.eclipse.jetty.io.SelectChannelEndPointSslTest
[ERROR] testEcho(org.eclipse.jetty.io.SelectChannelEndPointSslTest)  Time elapsed: 0.059 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.newClient(SelectChannelEndPointSslTest.java:70)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.testEcho(SelectChannelEndPointSslTest.java:91)

[ERROR] testWriteBlocked(org.eclipse.jetty.io.SelectChannelEndPointSslTest)  Time elapsed: 0.039 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.newClient(SelectChannelEndPointSslTest.java:70)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.testWriteBlocked(SelectChannelEndPointSslTest.java:104)

[ERROR] testStress(org.eclipse.jetty.io.SelectChannelEndPointSslTest)  Time elapsed: 0.037 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.newClient(SelectChannelEndPointSslTest.java:70)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.testStress(SelectChannelEndPointSslTest.java:124)

[ERROR] testReadBlocked(org.eclipse.jetty.io.SelectChannelEndPointSslTest)  Time elapsed: 0.019 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.newClient(SelectChannelEndPointSslTest.java:70)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.testReadBlocked(SelectChannelEndPointSslTest.java:110)

[ERROR] testIdle(org.eclipse.jetty.io.SelectChannelEndPointSslTest)  Time elapsed: 0.019 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.newClient(SelectChannelEndPointSslTest.java:70)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.testIdle(SelectChannelEndPointSslTest.java:116)

[ERROR] testBlockedReadIdle(org.eclipse.jetty.io.SelectChannelEndPointSslTest)  Time elapsed: 0.02 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointSslTest.newClient(SelectChannelEndPointSslTest.java:70)

[INFO] Running org.eclipse.jetty.io.SelectChannelEndPointTest
[ERROR] Tests run: 8, Failures: 0, Errors: 7, Skipped: 1, Time elapsed: 0.17 s <<< FAILURE! - in org.eclipse.jetty.io.SelectChannelEndPointTest
[ERROR] testReadBlocked(org.eclipse.jetty.io.SelectChannelEndPointTest)  Time elapsed: 0.028 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.newClient(SelectChannelEndPointTest.java:121)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.testReadBlocked(SelectChannelEndPointTest.java:387)

[ERROR] testEcho(org.eclipse.jetty.io.SelectChannelEndPointTest)  Time elapsed: 0.019 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.newClient(SelectChannelEndPointTest.java:121)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.testEcho(SelectChannelEndPointTest.java:277)

[ERROR] testIdle(org.eclipse.jetty.io.SelectChannelEndPointTest)  Time elapsed: 0.03 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.newClient(SelectChannelEndPointTest.java:121)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.testIdle(SelectChannelEndPointTest.java:439)

[ERROR] testWriteBlocked(org.eclipse.jetty.io.SelectChannelEndPointTest)  Time elapsed: 0.03 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.newClient(SelectChannelEndPointTest.java:121)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.testWriteBlocked(SelectChannelEndPointTest.java:647)

[ERROR] testShutdown(org.eclipse.jetty.io.SelectChannelEndPointTest)  Time elapsed: 0.02 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.newClient(SelectChannelEndPointTest.java:121)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.testShutdown(SelectChannelEndPointTest.java:336)

[ERROR] testBlockedReadIdle(org.eclipse.jetty.io.SelectChannelEndPointTest)  Time elapsed: 0.021 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.newClient(SelectChannelEndPointTest.java:121)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.testBlockedReadIdle(SelectChannelEndPointTest.java:484)

[ERROR] testStress(org.eclipse.jetty.io.SelectChannelEndPointTest)  Time elapsed: 0.021 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.newClient(SelectChannelEndPointTest.java:121)
	at org.eclipse.jetty.io.SelectChannelEndPointTest.testStress(SelectChannelEndPointTest.java:544)

[INFO] Running org.eclipse.jetty.io.SelectorManagerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.02 s - in org.eclipse.jetty.io.SelectorManagerTest
[INFO] Running org.eclipse.jetty.io.SocketChannelEndPointTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in org.eclipse.jetty.io.SocketChannelEndPointTest
[ERROR] testClientClose(org.eclipse.jetty.io.SocketChannelEndPointTest)  Time elapsed: 0.001 s  <<< ERROR!
java.net.ConnectException: Connection refused
	at org.eclipse.jetty.io.SocketChannelEndPointTest.newConnection(SocketChannelEndPointTest.java:50)
	at org.eclipse.jetty.io.SocketChannelEndPointTest.testClientClose(SocketChannelEndPointTest.java:58)

[ERROR] testClientServerExchange(org.eclipse.jetty.io.SocketChannelEndPointTest)  Time elapsed: 0.001 s  <<< ERROR!
java.net.ConnectException: Connection refused
	at org.eclipse.jetty.io.SocketChannelEndPointTest.newConnection(SocketChannelEndPointTest.java:50)
	at org.eclipse.jetty.io.SocketChannelEndPointTest.testClientServerExchange(SocketChannelEndPointTest.java:64)

[INFO] Running org.eclipse.jetty.io.SslConnectionTest
2018-03-15 09:38:02.872:INFO:oejus.SslContextFactory:main: x509=X509@2d3ef181(mykey,h=[],w=[]) for SslContextFactory@a2341c6[provider=null,keyStore=file:///Users/jenkins/workspace/nightlies/jetty-9.4.x-mac-nightly/jetty-io/src/test/resources/keystore,trustStore=null]
[ERROR] Tests run: 14, Failures: 0, Errors: 14, Skipped: 0, Time elapsed: 0.033 s <<< FAILURE! - in org.eclipse.jetty.io.SslConnectionTest
[ERROR] testWriteOnConnect(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SslConnectionTest.newClient(SslConnectionTest.java:260)
	at org.eclipse.jetty.io.SslConnectionTest.testWriteOnConnect(SslConnectionTest.java:402)

[ERROR] testWriteOnConnect(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NullPointerException
	at org.eclipse.jetty.io.SslConnectionTest.stopManager(SslConnectionTest.java:164)

[ERROR] testRenegotiateLimit(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.003 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SslConnectionTest.newClient(SslConnectionTest.java:260)
	at org.eclipse.jetty.io.SslConnectionTest.testRenegotiateLimit(SslConnectionTest.java:353)

[ERROR] testRenegotiateLimit(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NullPointerException
	at org.eclipse.jetty.io.SslConnectionTest.stopManager(SslConnectionTest.java:164)

[ERROR] testRenegotiateNotAllowed(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SslConnectionTest.newClient(SslConnectionTest.java:260)
	at org.eclipse.jetty.io.SslConnectionTest.testRenegotiateNotAllowed(SslConnectionTest.java:320)

[ERROR] testRenegotiateNotAllowed(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NullPointerException
	at org.eclipse.jetty.io.SslConnectionTest.stopManager(SslConnectionTest.java:164)

[ERROR] testManyLines(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.002 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SslConnectionTest.newClient(SslConnectionTest.java:260)
	at org.eclipse.jetty.io.SslConnectionTest.testManyLines(SslConnectionTest.java:449)

[ERROR] testManyLines(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException
	at org.eclipse.jetty.io.SslConnectionTest.stopManager(SslConnectionTest.java:164)

[ERROR] testBlockedWrite(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.002 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SslConnectionTest.newClient(SslConnectionTest.java:260)
	at org.eclipse.jetty.io.SslConnectionTest.testBlockedWrite(SslConnectionTest.java:421)

[ERROR] testBlockedWrite(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException
	at org.eclipse.jetty.io.SslConnectionTest.stopManager(SslConnectionTest.java:164)

[ERROR] testRenegotiate(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.003 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SslConnectionTest.newClient(SslConnectionTest.java:260)
	at org.eclipse.jetty.io.SslConnectionTest.testRenegotiate(SslConnectionTest.java:292)

[ERROR] testRenegotiate(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NullPointerException
	at org.eclipse.jetty.io.SslConnectionTest.stopManager(SslConnectionTest.java:164)

[ERROR] testHelloWorld(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.jetty.io.SslConnectionTest.newClient(SslConnectionTest.java:260)
	at org.eclipse.jetty.io.SslConnectionTest.testHelloWorld(SslConnectionTest.java:267)

[ERROR] testHelloWorld(org.eclipse.jetty.io.SslConnectionTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NullPointerException
	at org.eclipse.jetty.io.SslConnectionTest.stopManager(SslConnectionTest.java:164)

[INFO] Running org.eclipse.jetty.io.WriteFlusherTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.915 s - in org.eclipse.jetty.io.WriteFlusherTest
[INFO] 
```

**Comment by lachlan-roberts** [comment]
@joakime this seems to be fixed now, I am not getting any test failures in jetty-io on osx

**Comment by joakime** [comment]
Closing as no longer relevant.
