### ISSUE TITLE
HttpWriter.write blocks indefinitely

### ISSUE THREAD

**Issue by tryge** [eclipse/jetty.project#2380]
We have seen jetty hang in our production environment several times the past week. These are systems that basically have an http interface to expose some raw data, but there is definitely not a lot of load on them. We've used jetty for much longer time but it seems our services now trigger this behaviour and I didn't find any suspicious changes that were integrated in recent weeks.

We're using jetty version 9.4.5.v20170502.

We took a thread dump and it looks like this:

```
"qtp1238080693-817" #817 prio=5 os_prio=0 tid=0x00007f71ac051800 nid=0x4914 waiting on condition [0x00007f718a4d2000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000088f10b00> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:219)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:509)
        at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
        - locked <0x00000000d9892c30> (a org.eclipse.jetty.util.ByteArrayOutputStream2)
        at org.eclipse.jetty.server.Utf8HttpWriter.write(Utf8HttpWriter.java:183)
        at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:71)
        at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:65)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:231)
        - locked <0x00000000d9892c08> (a org.eclipse.jetty.server.Utf8HttpWriter)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:248)
        at def.a (Unknown Source)
        at abc.doGet (Unknown Source)
        - locked <0x0000000087a25cb8> (a abc)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
```

Any hint on how to workaround or prevent this behaviour is highly appreciated :-)

**Comment by sbordet** [comment]
This is typically the result of a client not reading the content from the server.
Jetty's idle timeout mechanism should wake up and fail those requests.
What is your `idleTimeout` configuration ?
Can you update to 9.4.9 ?

**Comment by tryge** [comment]
Thank you for your response. We use jetty in an embedded way and basically just call the `Server(port)` constructor and therefore I guess the idleTimeout is `30000` ms by default (I looked it up in `AbstractConnector.java` of 9.4.5) unless it is overridden by something else.

Thank you for the hint about clients, we'll check if any of our automated clients get into a state where they don't read from the server. 

All other clients are browsers, do you know whether standard browsers sometimes don't read the content from the server?

Our development snapshot already has 9.4.9 integrated and it will be rolled out into production end of this week.

**Comment by sbordet** [comment]
Browsers typically close the connection if they don't want to read, so that would be reflected in an exception waking up the blocked write.

When the blocking happens, it would be good if you can take a server dump as explained [here](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-dump-tool.html) and report it here.

**Comment by tryge** [comment]
Great, I instructed the IT Team to do the server dump when we encounter the hang again.

**Comment by dreis2211** [comment]
On a (maybe) related note: This is the same error we see in #2061 for Websockets where this comes from the fact that no timeout can be configured for the SharedBlockingCallback. So I wonder if the timeout is properly configured @tryge . Otherwise the thread-dump would show TIMED_WAITING I suppose.

What do you think, @sbordet ?

**Comment by tryge** [comment]
As I stated above, we're using the default. If the default behaviour can result in blocked requests I suppose that should be changed as well.

**Comment by sbordet** [comment]
I would not bother for now to have a timeout for `SharedBlockingCallback` (which is a deprecated feature that would likely be removed), as the idle timeout mechanism should suffice.

The server dump will tell us if the connections are TCP congested. If they are, it's the clients that don't read and leave the connection hanging.
If then the idle timeout mechanism does not fire to wake up the blocked threads, that could be an issue, but we have had evidence that the idle timeout mechanism works fine, so I would look elsewhere first.

Does the server resume normal operation after the idle timeout elapses ?

**Comment by dreis2211** [comment]
Interesting to hear that this might be removed in the future. Can't wait...

I guess upgrading to 9.4.x should help @tryge anyhow on his problem, as 705a68dfc41d512c813b7e40076462f5e9caf26d changed the `block()` method to always call `await(long time, TimeUnit unit)` if the timeout is configured properly instead of calling `await()` that potentially leaves the SharedBlockingCallback in the hanging state. Am I wrong @sbordet?

**Comment by joakime** [comment]
@sbordet aren't the selector dumps (for tcp congested) only present in Jetty 9.4.9.v20180320?
OP says he's using 9.4.5.v20170502.

**Comment by sbordet** [comment]
They're available in 9.4.x, any version.

**Comment by tryge** [comment]
After the update we haven't had an incidence since, so I'm closing the issue.

**Comment by zjffdu** [comment]
@tryge Which version do you upgrade ? I meet the same issue in 9.4.27.v20200227

**Comment by xinguangduan** [comment]
i meet the same issue in 9.4.31.v20200723  too，

"qtp651235118-149433" #149433 prio=5 os_prio=0 tid=0x000000000261a800 nid=0x1e5c3d waiting on condition [0x00007fe03b6d5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000056eb56c68> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:217)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:298)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:507)

qtp651235118-149434" #149434 prio=5 os_prio=0 tid=0x000000000749c000 nid=0x1e5c3e waiting on condition [0x00007fe050421000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000004fb25c910> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:656)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$800(QueuedThreadPool.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:720)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tryge** [comment]
@zjffdu I can't remember anymore, but we ran into the issue again and then we switched to using netty...

**Comment by sbordet** [comment]
@xinguangduan can you please upgrade to Jetty 9.4.39? There has been some work on performing asynchronous closes.

**Comment by jllanes3** [comment]
This is still a problem. Thread gets stuck there waiting for a signal that never comes. Repro is as follows:
- Start a simple Dropwizard application with version 2.1.4, which brings in jetty 9.4.49.v20220914. 
- Using a Netty client, make a GET to a resource that returns a large amount of data from Jetty, but on Netty client side, do not read any more data after a certain point. This will get TCP buffer on client side to get full, and therefore not ACK anymore of server side new packets. 
- This puts the server Jetty handling thread in a situation where it could not flush all the bytes, and it lands here, forever:
```
"dw-27 - GET /test/sync/long@5233" prio=5 tid=0x1b nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:241)
	  at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:270)
	  at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:901)
	  at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:302)
	  at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:200)
	  at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:276)
	  at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171)
	  at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegments(UTF8JsonGenerator.java:1313)
	  at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:511)
	  at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
	  at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	  at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	  at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	  at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	  at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	  at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	  at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
	  at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1007)
	  at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:617)
	  at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
	  at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
	  at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	  at io.dropwizard.jersey.errors.EofExceptionWriterInterceptor.aroundWriteTo(EofExceptionWriterInterceptor.java:39)
	  at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	  at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85)
	  at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	  at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61)
	  at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	  at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
	  at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:642)
	  at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:373)
	  at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:363)
	  at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:258)
	  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	  at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	  at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
	  at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	  at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
	  at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
	  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	  at com.playground.filters.HelloWorldFilter.doFilter(HelloWorldFilter.java:33)
	  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	  at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:284)
	  at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	  at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
	  at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
	  at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	  at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	  at org.eclipse.jetty.server.Server.handle(Server.java:516)
	  at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	  at org.eclipse.jetty.server.HttpChannel$$Lambda$553.1875545387.dispatch(Unknown Source:-1)
	  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	  at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	  at java.lang.Thread.run(Thread.java:748)

```
- That thread is not useful anymore to serve any other calls. Say you only have that one, then all other calls have to wait. Here is a few thread dumps while the above is happening and the server is serving traffic to other calls as well.

First call that blocks the server:
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/43658655/202521652-5c6f9e73-2587-479c-86e9-adfeffaccc0e.png">

While the above call is happening (client is not reading data from TCP buffer and therefore server cannot flush), send more regular successful requests (i.e. not the the one that does not read the body like above), which get served by other threads. Notice the dw-27 is stuck. 
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/43658655/202521883-9a4a2632-b3d4-4216-8c21-658d8eac2723.png">

I was really hoping that Jetty would be truly NIO with the selector and non-blocking sockets mechanism is using, unfortunately it is not blocking on the sockets, it is blocking on signals. 

NOTE: This also happens if I use AsyncResponse suspended approach. In that case, my own executor thread gets blocked during writing back the response as above. Essentially my own thread becomes unusable in this case (i.e. not the dw-x thread, rather my own callback thread is the one that gets stuck waiting for the signal).

**Comment by joakime** [comment]
@jllanes3 lets take a look at your stacktrace ...

```
	  at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:241)
	  at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:270)
	  at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:901)
	  at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:302)
```

That's a Jersey 2.37 class.

Found here -> https://github.com/eclipse-ee4j/jersey/blob/2.37/containers/jersey-servlet-core/src/main/java/org/glassfish/jersey/servlet/internal/ResponseWriter.java

That class uses standard OutputStream behaviors, which is blocking.
It does not appear to be using Servlet Async I/O (which is non-blocking).

If your client doesn't read, this thread will block until one of the following occurs. (this is normal servlet spec behavior btw)

* Your client reads some data
* Your connection is closed
* Your Idle Timeout kicks in and closes the connection
