### ISSUE TITLE
JDK9 Build Failure - Artifact is not fully assembled: ... jetty-maven-plugin/target/classes

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2383]
In PR-2382 build.

> Caused by: java.lang.ClassNotFoundException: de.flapdoodle.embed.process.extract.ExtractedFileSets

Relevant section of log ...

```
[linux_jdk9] [INFO] Jetty :: Bom ....................................... SUCCESS [  0.108 s]
[linux_jdk9] [INFO] ------------------------------------------------------------------------
[linux_jdk9] [INFO] BUILD FAILURE
[linux_jdk9] [INFO] ------------------------------------------------------------------------
[linux_jdk9] [INFO] Total time: 15:08 min (Wall Clock)
[linux_jdk9] [INFO] Finished at: 2018-03-27T09:10:20+00:00
[linux_jdk9] 2018-03-27 09:10:20.935:INFO:oejs.AbstractConnector:main: Started ServerConnector@1feb76b9{SSL,[ssl, alpn, h2]}{0.0.0.0:42057}
[linux_jdk9] [INFO] Final Memory: 258M/1024M2018-03-27 09:10:20.935:INFO:oejs.Server:main: Started @3220ms
[linux_jdk9] 
[linux_jdk9] [INFO] ------------------------------------------------------------------------
[linux_jdk9] [INFO] [jenkins-event-spy] Generated /home/jenkins/workspace/jetty.project_PR-2382-HWCNIWGVZSRVODSJH3AUY5HPWZUJGQNGTPQNZA3KBWFWC7MYDXNQ@tmp/withMaven7db61b7e/maven-spy-20180327-085512-48510801699405196802699.log
[linux_jdk9] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.0.1:install (integration-test) on project jetty-jspc-maven-plugin: Failed to install project dependencies: MavenProject: org.eclipse.jetty:jetty-jspc-maven-plugin:9.4.10-SNAPSHOT @ /home/jenkins/workspace/jetty.project_PR-2382-HWCNIWGVZSRVODSJH3AUY5HPWZUJGQNGTPQNZA3KBWFWC7MYDXNQ/jetty-jspc-maven-plugin/pom.xml: Failed to install project artifacts: MavenProject: org.eclipse.jetty:jetty-maven-plugin:9.4.10-SNAPSHOT @ /home/jenkins/workspace/jetty.project_PR-2382-HWCNIWGVZSRVODSJH3AUY5HPWZUJGQNGTPQNZA3KBWFWC7MYDXNQ/jetty-maven-plugin/pom.xml: Failed to install artifact: org.eclipse.jetty:jetty-maven-plugin:maven-plugin:9.4.10-SNAPSHOT: Artifact is not fully assembled: /home/jenkins/workspace/jetty.project_PR-2382-HWCNIWGVZSRVODSJH3AUY5HPWZUJGQNGTPQNZA3KBWFWC7MYDXNQ/jetty-maven-plugin/target/classes -> [Help 1]
[linux_jdk9] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.0.1:install (integration-test) on project jetty-jspc-maven-plugin: Failed to install project dependencies: MavenProject: org.eclipse.jetty:jetty-jspc-maven-plugin:9.4.10-SNAPSHOT @ /home/jenkins/workspace/jetty.project_PR-2382-HWCNIWGVZSRVODSJH3AUY5HPWZUJGQNGTPQNZA3KBWFWC7MYDXNQ/jetty-jspc-maven-plugin/pom.xml
[linux_jdk9] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[linux_jdk9] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[linux_jdk9] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[linux_jdk9] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[linux_jdk9] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
[linux_jdk9] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
[linux_jdk9] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[linux_jdk9] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[linux_jdk9] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[linux_jdk9] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[linux_jdk9] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[linux_jdk9] 	at java.base/java.lang.Thread.run(Thread.java:844)
[linux_jdk9] Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to install project dependencies: MavenProject: org.eclipse.jetty:jetty-jspc-maven-plugin:9.4.10-SNAPSHOT @ /home/jenkins/workspace/jetty.project_PR-2382-HWCNIWGVZSRVODSJH3AUY5HPWZUJGQNGTPQNZA3KBWFWC7MYDXNQ/jetty-jspc-maven-plugin/pom.xml
[linux_jdk9] 	at org.apache.maven.plugins.invoker.InstallMojo.installProjectDependencies(InstallMojo.java:476)
[linux_jdk9] 	at org.apache.maven.plugins.invoker.InstallMojo.execute(InstallMojo.java:183)
[linux_jdk9] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[linux_jdk9] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[linux_jdk9] 	... 11 more
[linux_jdk9] Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to install project artifacts: MavenProject: org.eclipse.jetty:jetty-maven-plugin:9.4.10-SNAPSHOT @ /home/jenkins/workspace/jetty.project_PR-2382-HWCNIWGVZSRVODSJH3AUY5HPWZUJGQNGTPQNZA3KBWFWC7MYDXNQ/jetty-maven-plugin/pom.xml
[linux_jdk9] 	at org.apache.maven.plugins.invoker.InstallMojo.installProjectArtifacts(InstallMojo.java:342)
[linux_jdk9] 	at org.apache.maven.plugins.invoker.InstallMojo.installProjectDependencies(InstallMojo.java:470)
[linux_jdk9] 	... 14 more
[linux_jdk9] Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to install artifact: org.eclipse.jetty:jetty-maven-plugin:maven-plugin:9.4.10-SNAPSHOT
[linux_jdk9] 	at org.apache.maven.plugins.invoker.InstallMojo.installArtifact(InstallMojo.java:250)
[linux_jdk9] 	at org.apache.maven.plugins.invoker.InstallMojo.installProjectArtifacts(InstallMojo.java:330)
[linux_jdk9] 	... 15 more
[linux_jdk9] Caused by: java.lang.IllegalStateException: Artifact is not fully assembled: /home/jenkins/workspace/jetty.project_PR-2382-HWCNIWGVZSRVODSJH3AUY5HPWZUJGQNGTPQNZA3KBWFWC7MYDXNQ/jetty-maven-plugin/target/classes
[linux_jdk9] 	at org.apache.maven.plugins.invoker.InstallMojo.installArtifact(InstallMojo.java:234)
[linux_jdk9] 	... 16 more
[linux_jdk9] [ERROR] 
[linux_jdk9] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[linux_jdk9] [ERROR] 
[linux_jdk9] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[linux_jdk9] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[linux_jdk9] [ERROR] 
[linux_jdk9] [ERROR] After correcting the problems, you can resume the build with the command
[linux_jdk9] [ERROR]   mvn <goals> -rf :jetty-jspc-maven-plugin
[linux_jdk9] Exception in thread "Thread-189" java.lang.NoClassDefFoundError: de/flapdoodle/embed/process/extract/ExtractedFileSets
[linux_jdk9] 	at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:90)
[linux_jdk9] 	at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:176)
[linux_jdk9] 	at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:100)
[linux_jdk9] 	at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:196)
[linux_jdk9] 	at java.base/java.lang.Thread.run(Thread.java:844)
[linux_jdk9] Caused by: java.lang.ClassNotFoundException: de.flapdoodle.embed.process.extract.ExtractedFileSets
[linux_jdk9] 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
[linux_jdk9] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
[linux_jdk9] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
[linux_jdk9] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
[linux_jdk9] 	... 5 more
[Pipeline] [linux_jdk9] }
[Pipeline] [linux_jdk9] // withMaven
[Pipeline] [linux_jdk9] }
[Pipeline] [linux_jdk9] // timeout
[Pipeline] [linux_jdk9] }
[Pipeline] [linux_jdk9] // withEnv
[Pipeline] [linux_jdk9] }
[Pipeline] [linux_jdk9] // stage
[Pipeline] [linux_jdk9] }
[Pipeline] [linux_jdk9] // node
[Pipeline] [linux_jdk9] }
[linux_jdk9] Failed in branch linux_jdk9
[Pipeline] // parallel
[Pipeline] End of Pipeline
```

**Comment by joakime** [comment]
@olamy I have no clue what's going on here.

My gut says its a bad artifact download.
Are the PR builds using the data center local artifact repository?
Are there bad artifacts in that repository?
Should we enable strict artifact checksum checks for the builds?

**Comment by olamy** [comment]
Maven complains about a missing reactor module missing (i.e not installed yet) which should not happen as modules should be started in certain order and wait completion of dependant..
BTW definitely something weird here as if I read the logs correctly Maven complains saying jetty-jspc-maven-plugin need jetty-maven-plugin to be installed first which doesn't make sense as those modules are independant.
The worst is I can reproduce but not for every run.
Maybe some Maven multi thread build issue....

**Comment by olamy** [comment]
Maven issue here https://issues.apache.org/jira/browse/MINVOKER-191

**Comment by olamy** [comment]
fixed here https://github.com/apache/maven-invoker-plugin/commit/0136f8395ae9c98b6c1818fb516d13002ec6bc1f
