### ISSUE TITLE
StackOverflowError in Request.getAttribute

### ISSUE THREAD

**Issue by armandino** [eclipse/jetty.project#2399]
Apologies for the lack of details and a test case for this, but after upgrading our application to 9.4.6.v20170531 we are seeing occasional `StackOverflowError` errors:

```
java.lang.StackOverflowError: null
	at org.eclipse.jetty.server.Dispatcher$ForwardAttributes.getAttribute(Dispatcher.java:315) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Dispatcher$ForwardAttributes.getAttribute(Dispatcher.java:315) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        ... snip ...
	at org.eclipse.jetty.server.Dispatcher$ForwardAttributes.getAttribute(Dispatcher.java:315) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Request.getAttribute(Request.java:591) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
```

when calling `Request.getAttribute(...)`. Not sure what's causing this yet. I will follow up once i have more details...

**Comment by joakime** [comment]
I'm not finding any relevant commits or issues to `Request.java` or `Dispatcher.java` to address this.

**Comment by armandino** [comment]
Yes, that's what I thought as well.

From what I've seen so far, all the calls to `getAttribute` are originating from various filters.

**Comment by armandino** [comment]
Sure.. Here's a full stacktrace. I removed some repeating lines

```
java.lang.StackOverflowError: null
	at org.eclipse.jetty.server.Dispatcher$ForwardAttributes.getAttribute(Dispatcher.java:315) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Dispatcher$ForwardAttributes.getAttribute(Dispatcher.java:315) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	... snip ...
	at org.eclipse.jetty.server.Dispatcher$ForwardAttributes.getAttribute(Dispatcher.java:315) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Request.getAttribute(Request.java:591) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:377) ~[com.acme-1.0.jar:?]
	at com.acme.login.AuthorizationFilter.doFilter(AuthorizationFilter.java:148) ~[com.acme-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.redirect.RedirectFilter.doUnfiltered(RedirectFilter.java:60) ~[com.acme-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:59) ~[opensymphony.sitemesh-2.4.2.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64) ~[org.apache.logging.log4j.log4j-web-2.7.jar:2.7]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) ~[org.eclipse.jetty.jetty-security-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.jetty.CrossContextSessionHandler.doScope(CrossContextSessionHandler.java:37) ~[com.acme.jetty-1.0.jar:1.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:203) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.servlet.AbstractMDRequestDispatcher.forward(AbstractMDRequestDispatcher.java:54) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.handleError(SharedSitemapFilter.java:115) ~[com.acme-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.filter(SharedSitemapFilter.java:97) ~[com.acme-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.doFilter2(SharedSitemapFilter.java:53) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.login.CoreMDLoginFilter.doFilter2(CoreMDLoginFilter.java:207) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.login.MDLoginFilter.doFilter2(MDLoginFilter.java:41) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.login.AuthorizationFilter.doFilter(AuthorizationFilter.java:240) ~[com.acme-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.redirect.RedirectFilter.doUnfiltered(RedirectFilter.java:60) ~[com.acme-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:59) ~[opensymphony.sitemesh-2.4.2.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64) ~[org.apache.logging.log4j.log4j-web-2.7.jar:2.7]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) ~[org.eclipse.jetty.jetty-security-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        ... snip duplicate lines ...
	at com.acme.jetty.CrossContextSessionHandler.doScope(CrossContextSessionHandler.java:37) ~[com.acme.jetty-1.0.jar:1.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:203) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.servlet.AbstractMDRequestDispatcher.forward(AbstractMDRequestDispatcher.java:54) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.handleError(SharedSitemapFilter.java:115) ~[com.acme-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.filter(SharedSitemapFilter.java:97) ~[com.acme-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.doFilter2(SharedSitemapFilter.java:53) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.login.CoreMDLoginFilter.doFilter2(CoreMDLoginFilter.java:207) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.login.MDLoginFilter.doFilter2(MDLoginFilter.java:41) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.login.AuthorizationFilter.doFilter(AuthorizationFilter.java:240) ~[com.acme-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.redirect.RedirectFilter.doUnfiltered(RedirectFilter.java:60) ~[com.acme-1.0.jar:1.0]
```

**Comment by joakime** [comment]
In the `... snip duplicate lines ...` do you see multiple calls to 

    org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73)

?

I was only able to replicate this when the `Dispatcher.forward()` call is recursive.
Example ...

```
GET /content/simple/foo
   SimpleServlet - doGet() - forward("/alt/foo")
   FORWARD /alt/foo
   AltServlet - doGet() - forward("/content/simple/foo")
   FORWARD /content/simple/foo
   SimpleServlet - doGet() - forward("/alt/foo")
   FORWARD /alt/foo
   AltServlet - doGet() - forward("/content/simple/foo")
   FORWARD /content/simple/foo
   ... etc ...
```

You could easily test for this with some logging in a filter ...

``` java
public static class SimpleFilter implements Filter
    {
        @Override
        public void init(FilterConfig filterConfig) throws ServletException { }

        @Override
        public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException
        {
            HttpServletRequest  request;
            HttpServletResponse response;

            if (!(req instanceof HttpServletRequest &&
                    res instanceof HttpServletResponse)) {
                throw new ServletException("non-HTTP request or response");
            }

            request = (HttpServletRequest) req;
            response = (HttpServletResponse) res;

            System.out.printf("%s.doFilter() - dispatch:%s uri:%s filterchain:%s%n", this.getClass().getSimpleName(), request.getDispatcherType(), request.getRequestURI(), chain);
            chain.doFilter(request, response);
        }

        @Override
        public void destroy() { }
    }
```

**Comment by armandino** [comment]
Thanks a lot for your help! Much appreciated.

Yes, the stack pasted below is repeated multiple times, and it does have a call to `Dispatcher.forward()` in there. I guess somehow under certain conditions we are getting into an inifite loop of forwards.

I will try the filter first thing on Monday.

```
	at com.acme.jetty.CrossContextSessionHandler.doScope(CrossContextSessionHandler.java:37) ~[com.acme.jetty-1.0.jar:1.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:203) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.servlet.AbstractMDRequestDispatcher.forward(AbstractMDRequestDispatcher.java:54) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.handleError(SharedSitemapFilter.java:115) ~[com.acme-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.filter(SharedSitemapFilter.java:97) ~[com.acme-1.0.jar:1.0]
	at com.acme.login.SharedSitemapFilter.doFilter2(SharedSitemapFilter.java:53) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.login.CoreMDLoginFilter.doFilter2(CoreMDLoginFilter.java:207) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.login.MDLoginFilter.doFilter2(MDLoginFilter.java:41) ~[com.acme-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.login.AuthorizationFilter.doFilter(AuthorizationFilter.java:240) ~[com.acme-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.redirect.RedirectFilter.doUnfiltered(RedirectFilter.java:60) ~[com.acme-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:59) ~[opensymphony.sitemesh-2.4.2.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at com.acme.OneTimeFilter.doUnfiltered(OneTimeFilter.java:37) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.OneTimeFilter.doFilter2(OneTimeFilter.java:26) ~[com.acme.shared-1.0.jar:1.0]
	at com.acme.NonResourceFilter.doFilter(NonResourceFilter.java:58) ~[com.acme.shared-1.0.jar:1.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64) ~[org.apache.logging.log4j.log4j-web-2.7.jar:2.7]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) ~[org.eclipse.jetty.jetty-security-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) ~[org.eclipse.jetty.jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[org.eclipse.jetty.jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
```

**Comment by armandino** [comment]
I added the filter and it looks like there's something odd happening with our forwards. This only seems to happen in case of errors that get forwarded to a particular jsp error page. I'll close this ticket since it's not a Jetty 9 issue... Sorry for the false alarm and thanks again for your help!

**Comment by KouLouYiMaSi** [comment]
I used this version
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jetty</artifactId>
    <version>1.5.14.RELEASE</version>
</dependency>

And I add code like below in my project
```
public static class SimpleFilter implements Filter
    {
        @Override
        public void init(FilterConfig filterConfig) throws ServletException { }

        @Override
        public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException
        {
            HttpServletRequest  request;
            HttpServletResponse response;

            if (!(req instanceof HttpServletRequest &&
                    res instanceof HttpServletResponse)) {
                throw new ServletException("non-HTTP request or response");
            }

            request = (HttpServletRequest) req;
            response = (HttpServletResponse) res;

            System.out.printf("%s.doFilter() - dispatch:%s uri:%s filterchain:%s%n", this.getClass().getSimpleName(), request.getDispatcherType(), request.getRequestURI(), chain);
            chain.doFilter(request, response);
        }

        @Override
        public void destroy() { }
    }
```
when I download .mp4 use io stream or other operation about video.  this filter is called Infinitely，then stackoverflowerror happend. 
how can i fix this bug?

**Comment by lm0303** [comment]
Hello, I also encountered the same problem as you in the recent development. How did you solve it
