### ISSUE TITLE
jetty:stop java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback

### ISSUE THREAD

**Issue by gonzalezi** [eclipse/jetty.project#2406]
I`m using v9.3.16.20170120. Any idea if this is a known issue or how can be solved?

2018-03-28 16:02:06 DEBUG AbstractLifeCycle:194 - stopping org.eclipse.jetty.server.Server@2893de87
2018-03-28 16:02:06 DEBUG Server:433 - doStop org.eclipse.jetty.server.Server@2893de87
2018-03-28 16:02:06 WARN  AbstractLifeCycle:213 - FAILED org.eclipse.jetty.server.Server@2893de87: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
        at org.eclipse.jetty.server.AbstractConnector.shutdown(AbstractConnector.java:297)
        at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:108)
        at org.eclipse.jetty.server.ServerConnector.shutdown(ServerConnector.java:337)
        at org.eclipse.jetty.server.Server.doStop(Server.java:442)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:138)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.FutureCallback
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
        at org.eclipse.jetty.server.AbstractConnector.shutdown(AbstractConnector.java:297)
        at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:108)
        at org.eclipse.jetty.server.ServerConnector.shutdown(ServerConnector.java:337)
        at org.eclipse.jetty.server.Server.doStop(Server.java:442)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:138)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.FutureCallback
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more

**Comment by joakime** [comment]
During the stop, the classloader is attempting to load a new class, but cannot find it as the classloader is also undergoing stop.

How did you start your Jetty server?

**Comment by joakime** [comment]
This is similar to Issue #1409 and #537
