### ISSUE TITLE
jetty-osgi-boot-9.4.9.v20180320 - javax.naming.NameAlreadyBoundException: env for all web apps

### ISSUE THREAD

**Issue by n-kristev** [eclipse/jetty.project#2409]
Hello,

I am trying to run Jetty 9.4.9.v20180320 as described in https://www.eclipse.org/jetty/documentation/current/framework-jetty-osgi.html on an OSGi container. For all web applications (apart from the default Jetty one), I got errors similar to the following:

```
    Failed startup of context o.e.j.w.WebAppContext@11011cd{
    /XXXX,file:///var/volatile/tmp/jetty-0.0.0.0-80-XXXX-,UNAVAILABLE}{file:/YYYY.jar}

javax.naming.NameAlreadyBoundException: env
at org.eclipse.jetty.jndi.NamingContext.createSubcontext(NamingContext.java:355)
at org.eclipse.jetty.jndi.NamingContext.createSubcontext(NamingContext.java:420)
at org.eclipse.jetty.plus.webapp.EnvConfiguration.createEnvContext(EnvConfiguration.java:258)
at org.eclipse.jetty.plus.webapp.EnvConfiguration.preConfigure(EnvConfiguration.java:67)
at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
```
I have installed both JNDI and Annotation bundles. I tracked the cause to the following code in 
org.eclipse.jetty.osgi.boot.AbstractWebAppProvider:
```java
    public String[] getConfigurationClasses()
    {
        if (_configurationClasses != null)
            return _configurationClasses;

        Configuration.ClassList defaults = Configuration.ClassList.serverDefault(_serverWrapper.getServer());

        //add before JettyWebXmlConfiguration
        if (annotationsAvailable())
            defaults.addBefore("org.eclipse.jetty.webapp.JettyWebXmlConfiguration", 
                               "org.eclipse.jetty.osgi.annotations.AnnotationConfiguration");

        //add in EnvConfiguration and PlusConfiguration just after FragmentConfiguration
        if (jndiAvailable())
            defaults.addAfter("org.eclipse.jetty.webapp.FragmentConfiguration",
                              "org.eclipse.jetty.plus.webapp.EnvConfiguration",
                              "org.eclipse.jetty.plus.webapp.PlusConfiguration");
       String[] asArray = new String[defaults.size()];
       return defaults.toArray(asArray);
    }
```
Since  ```Configuration.ClassList.serverDefault(_serverWrapper.getServer()); ``` returns a list which already contains org.eclipse.jetty.plus.webapp.EnvConfiguration, later in ```org.eclipse.jetty.webapp.WebAppContext.preConfigure``` the call to ```EnvConfiguration.preconfigure``` is executed twice, which causes the error.

**Comment by janbartel** [comment]
@n-kristev so did you already set the default classes for that webapp in a context xml file or something? I'll change the code to only do the addition if they're not already there, but I would appreciate knowing the full circumstances please.

**Comment by janbartel** [comment]
@n-kristev, scratch that, I'm not mutating the Server defaults on each webapp. So can you please confirm if you've set up the server default configurations some other way? By default in OSGi they are just:
```
org.eclipse.jetty.osgi.boot.OSGiWebInfConfiguration
org.eclipse.jetty.webapp.WebXmlConfiguration
org.eclipse.jetty.webapp.MetaInfConfiguration
org.eclipse.jetty.webapp.FragmentConfiguration
org.eclipse.jetty.webapp.JettyWebXmlConfiguration
```

**Comment by n-kristev** [comment]
@janbartel OK, it is an ID 10 T error on my part. A bit of context - I am porting an OSGi/Jetty web app from Jetty 9.2 to 9.4, and this is my first time using Jetty. When I got the error I went into the source to figure it out, but did not check in detail the configuiration files, since I was told they are copied from the Jetty examples. I have rechecked jetty.xml now, and I found this:

```
    <Call class="org.eclipse.jetty.webapp.Configuration$ClassList" name="setServerDefault">
      <Arg><Ref refid="Server" /></Arg>
      <Call name="addAfter">
        <Arg name="afterClass">org.eclipse.jetty.webapp.FragmentConfiguration</Arg>
        <Arg>
          <Array type="String">
            <Item>org.eclipse.jetty.plus.webapp.EnvConfiguration</Item>
            <Item>org.eclipse.jetty.plus.webapp.PlusConfiguration</Item>
            <Item>org.eclipse.jetty.annotations.AnnotationConfiguration</Item>
          </Array>
        </Arg>
      </Call>
    </Call>
```
This file worked with Jetty 9.2, but I assume the behaviour of osgi-boot was changed before. For my part, yesterday I got it working by replacing the code in AbstractWebAppProvider.getConfigurationClasses with
```
//add before JettyWebXmlConfiguration
        if (annotationsAvailable() && !defaults.contains("org.eclipse.jetty.osgi.annotations.AnnotationConfiguration"))
            defaults.addBefore("org.eclipse.jetty.webapp.JettyWebXmlConfiguration", 
                               "org.eclipse.jetty.osgi.annotations.AnnotationConfiguration");

        //add in EnvConfiguration and PlusConfiguration just after FragmentConfiguration
        if (jndiAvailable()) {
        	if (!defaults.contains("org.eclipse.jetty.webapp.FragmentConfiguration")) {
        		defaults.addAfter("org.eclipse.jetty.webapp.FragmentConfiguration");
        	}
        	if (!defaults.contains("org.eclipse.jetty.plus.webapp.EnvConfiguration")) {
        		defaults.addAfter("org.eclipse.jetty.plus.webapp.EnvConfiguration");
        	}
        	if (!defaults.contains("org.eclipse.jetty.plus.webapp.PlusConfiguration")) {
        		defaults.addAfter("org.eclipse.jetty.plus.webapp.PlusConfiguration");
        	}
        }
```

I did not issue a pull request, exactly because I am very new to Jetty, and was not at all sure if this would be the correct way to go about this :)
