### ISSUE TITLE
Websocket intermittent test failure

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2415]
From jenkins build using jdk8 of the branch associated with https://github.com/eclipse/jetty.project/pull/2408

```
Error
Should only have 1 open session
Expected: a string containing "openSessions.size=1\n"
but: was "openSessions.size=2
[0] WebSocketSession[websocket=JettyListenerEventDriver[org.eclipse.jetty.websocket.server.WebSocketCloseTest$ContainerSocket],behavior=SERVER,connection=WebSocketServerConnection@e015dc6a[ios=IOState@7aa94026[OPEN,in,out],f=Flusher@7e96cbab[queueSize=0,aggregateSize=0,terminated=null],g=Generator[SERVER,validating],p=Parser@3b944a1d[ExtensionStack,s=START,c=0,len=0,f=null]]<-SocketChannelEndPoint@46332d41{/127.0.0.1:44470<->/127.0.0.1:44749,OPEN,fill=FI,flush=-,to=5/300000}{io=1/1,kio=1,kro=1}->WebSocketServerConnection@e015dc6a[ios=IOState@7aa94026[OPEN,in,out],f=Flusher@7e96cbab[queueSize=0,aggregateSize=0,terminated=null],g=Generator[SERVER,validating],p=Parser@3b944a1d[ExtensionStack,s=START,c=0,len=0,f=null]],remote=WebSocketRemoteEndpoint@3a7d5dcc[batching=true],incoming=JettyListenerEventDriver[org.eclipse.jetty.websocket.server.WebSocketCloseTest$ContainerSocket],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.common.WebSocketSession,outgoing=org.eclipse.jetty.websocket.server.WebSocketServerConnection]]
[1] WebSocketSession[websocket=JettyListenerEventDriver[org.eclipse.jetty.websocket.server.WebSocketCloseTest$ContainerSocket],behavior=SERVER,connection=WebSocketServerConnection@e015dc70[ios=IOState@ae592d5[OPEN,in,out],f=Flusher@42e6dbb1[queueSize=0,aggregateSize=0,terminated=null],g=Generator[SERVER,validating],p=Parser@5bbbb552[ExtensionStack,s=START,c=0,len=12,f=TEXT[len=0,fin=true,rsv=...,masked=true]]]<-SocketChannelEndPoint@316c5d7b{/127.0.0.1:44476<->/127.0.0.1:44749,OPEN,fill=-,flush=-,to=1/300000}{io=0/0,kio=0,kro=1}->WebSocketServerConnection@e015dc70[ios=IOState@ae592d5[OPEN,in,out],f=Flusher@42e6dbb1[queueSize=0,aggregateSize=0,terminated=null],g=Generator[SERVER,validating],p=Parser@5bbbb552[ExtensionStack,s=START,c=0,len=12,f=TEXT[len=0,fin=true,rsv=...,masked=true]]],remote=WebSocketRemoteEndpoint@b7800d4[batching=true],incoming=JettyListenerEventDriver[org.eclipse.jetty.websocket.server.WebSocketCloseTest$ContainerSocket],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.common.WebSocketSession,outgoing=org.eclipse.jetty.websocket.server.WebSocketServerConnection]]
"
Stacktrace
java.lang.AssertionError:
Should only have 1 open session
Expected: a string containing "openSessions.size=1\n"
but: was "openSessions.size=2
[0] WebSocketSession[websocket=JettyListenerEventDriver[org.eclipse.jetty.websocket.server.WebSocketCloseTest$ContainerSocket],behavior=SERVER,connection=WebSocketServerConnection@e015dc6a[ios=IOState@7aa94026[OPEN,in,out],f=Flusher@7e96cbab[queueSize=0,aggregateSize=0,terminated=null],g=Generator[SERVER,validating],p=Parser@3b944a1d[ExtensionStack,s=START,c=0,len=0,f=null]]<-SocketChannelEndPoint@46332d41{/127.0.0.1:44470<->/127.0.0.1:44749,OPEN,fill=FI,flush=-,to=5/300000}{io=1/1,kio=1,kro=1}->WebSocketServerConnection@e015dc6a[ios=IOState@7aa94026[OPEN,in,out],f=Flusher@7e96cbab[queueSize=0,aggregateSize=0,terminated=null],g=Generator[SERVER,validating],p=Parser@3b944a1d[ExtensionStack,s=START,c=0,len=0,f=null]],remote=WebSocketRemoteEndpoint@3a7d5dcc[batching=true],incoming=JettyListenerEventDriver[org.eclipse.jetty.websocket.server.WebSocketCloseTest$ContainerSocket],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.common.WebSocketSession,outgoing=org.eclipse.jetty.websocket.server.WebSocketServerConnection]]
[1] WebSocketSession[websocket=JettyListenerEventDriver[org.eclipse.jetty.websocket.server.WebSocketCloseTest$ContainerSocket],behavior=SERVER,connection=WebSocketServerConnection@e015dc70[ios=IOState@ae592d5[OPEN,in,out],f=Flusher@42e6dbb1[queueSize=0,aggregateSize=0,terminated=null],g=Generator[SERVER,validating],p=Parser@5bbbb552[ExtensionStack,s=START,c=0,len=12,f=TEXT[len=0,fin=true,rsv=...,masked=true]]]<-SocketChannelEndPoint@316c5d7b{/127.0.0.1:44476<->/127.0.0.1:44749,OPEN,fill=-,flush=-,to=1/300000}{io=0/0,kio=0,kro=1}->WebSocketServerConnection@e015dc70[ios=IOState@ae592d5[OPEN,in,out],f=Flusher@42e6dbb1[queueSize=0,aggregateSize=0,terminated=null],g=Generator[SERVER,validating],p=Parser@5bbbb552[ExtensionStack,s=START,c=0,len=12,f=TEXT[len=0,fin=true,rsv=...,masked=true]]],remote=WebSocketRemoteEndpoint@b7800d4[batching=true],incoming=JettyListenerEventDriver[org.eclipse.jetty.websocket.server.WebSocketCloseTest$ContainerSocket],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.common.WebSocketSession,outgoing=org.eclipse.jetty.websocket.server.WebSocketServerConnection]]
"
at org.eclipse.jetty.websocket.server.WebSocketCloseTest.testOpenSessionCleanup(WebSocketCloseTest.java:329)
Standard Error
2018-04-04 07:37:37.224:WARN:oejwc.WebSocketSession:qtp456577608-249:
java.lang.RuntimeException: Intentional FastFail
at org.eclipse.jetty.websocket.server.WebSocketCloseTest$FastFailSocket.onWebSocketConnect(WebSocketCloseTest.java:196)
at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onConnect(JettyListenerEventDriver.java:106)
at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:233)
at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:616)
at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:544)
at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:202)
at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:446)
at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:440)
at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:385)
at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:702)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:498)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by joakime** [comment]
Still haven't been able to reproduce this one. :-(

**Comment by joakime** [comment]
That test is seemingly racy with the LifeCycle stop, not worth fixing, we have this kind of test elsewhere already anyway.

Ignored in commit be3c5a08d0dc4875afcfac8948b73cba8b838dea
