### ISSUE TITLE
OSGi tests fail on Java 11

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2419]
CI reports the following failures for OSGi tests on Java 11.

org.eclipse.jetty.osgi.test.TestJettyOSGiBootContextAsService.testContextHandlerAsOSGiService
java.lang.AssertionError
	at org.eclipse.jetty.osgi.test.TestJettyOSGiBootContextAsService.testContextHandlerAsOSGiService(TestJettyOSGiBootContextAsService.java:103)

org.eclipse.jetty.osgi.test.TestJettyOSGiBootHTTP2Conscrypt.testHTTP2
java.lang.AssertionError
	at org.eclipse.jetty.osgi.test.TestJettyOSGiBootHTTP2Conscrypt.testHTTP2(TestJettyOSGiBootHTTP2Conscrypt.java:141)

org.eclipse.jetty.osgi.test.TestJettyOSGiBootHTTP2JDK9.testHTTP2
java.lang.AssertionError
	at org.eclipse.jetty.osgi.test.TestJettyOSGiBootHTTP2JDK9.testHTTP2(TestJettyOSGiBootHTTP2JDK9.java:135)

org.eclipse.jetty.osgi.test.TestJettyOSGiBootWebAppAsService.testBundle
java.lang.AssertionError
	at org.eclipse.jetty.osgi.test.TestJettyOSGiBootWebAppAsService.testBundle(TestJettyOSGiBootWebAppAsService.java:119)

org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithAnnotations.testIndex
java.lang.AssertionError
	at org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithAnnotations.testIndex(TestJettyOSGiBootWithAnnotations.java:115)

org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJavaxWebSocket.testWebsocket
java.lang.AssertionError
	at org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJavaxWebSocket.testWebsocket(TestJettyOSGiBootWithJavaxWebSocket.java:146)

org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJsp.testJspDump
java.lang.AssertionError
	at org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithJsp.testJspDump(TestJettyOSGiBootWithJsp.java:107)

org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithWebSocket.testWebsocket
java.lang.AssertionError
	at org.eclipse.jetty.osgi.test.TestJettyOSGiBootWithWebSocket.testWebsocket(TestJettyOSGiBootWithWebSocket.java:103)

**Comment by olamy** [comment]
same woth jdk10 see #2343

**Comment by janbartel** [comment]
The tests fail on jdk11 because they rely on asm and asm does not yet support jdk-11.

**Comment by olamy** [comment]
will be fixed with pr #2588  issue #2586
