### ISSUE TITLE
ServletOutputStream.write may block even though ServletOutputStream.isReady() returned true

### ISSUE THREAD

**Issue by jentfoo** [eclipse/jetty.project#2460]
I am trying to build a non-blocking application and have run into an unexpected behavior with `ServletOutputStream`.  As part of this I am trying to abstract away the complexities of `ServletOutputStream`.  In my current implementation I am not considering back pressure, and instead want to write out on the stream if we can, and if we can't queue the write to be sent later.

Here is what my current implementation looks like:
```
ServletInputStream in = request.getInputStream();
new NonBlockingOutputStream() {
      private Queue<ListenableRunnableFuture<?>> writeFutures = null;

      @Override
      public void close() throws IOException {
        out.close();
      }

      private void ensureAsyncSetup() {
        if (writeFutures == null) {
          writeFutures = new ConcurrentLinkedQueue<>();

          out.setWriteListener(new WriteListener() {
            @Override
            public void onError(Throwable t) {
              // TODO - handle error
              t.printStackTrace();
            }

            @Override
            public void onWritePossible() {
              ListenableRunnableFuture<?> lrf = writeFutures.poll();
              if (lrf != null) {
                lrf.run();
              }
            }
          });
        }
      }

      @Override
      public ListenableFuture<?> write(byte[] bytes, int position, int length) {
        if (out.isReady()) {
          try {
            out.write(bytes, position, length);
            return ImmediateResultListenableFuture.NULL_RESULT;
          } catch (IOException e) {
            return FutureUtils.immediateFailureFuture(e);
          }
        } else {
          ListenableRunnableFuture<?> result =
              new ListenableFutureTask<>(false, () -> { out.write(bytes, position, length); return null; });
          writeFutures.add(result);

          ensureAsyncSetup();

          return result;
        }
      }
    }
```
Some assumptions I am making right now:
* Write will only be invoked by one thread (thus no check then act race conditions should be possible)
* If `isReady()` returns `false`, and there is no write listener set, when one is set it will be invoked immediately (is this true?  even if it's not it does not relate to my issue)

The issue I am facing is that if I have a client not consuming any data, `isReady()` will never return `false`, but instead eventually the `write` will block.

I am unsure if it's because there is _some_ available space, but it can't fit the entire buffer.  If that is the case, how can I check if it's ready for a given size?

Thanks in advance!

**Comment by jentfoo** [comment]
Oh yes, and here is the stack for what it looks like when it blocks:

```
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000771ca0f80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:217)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:515)
```
