### ISSUE TITLE
WebSocket FragmentExtension can produce an invalid stream of frames

### ISSUE THREAD

**Issue by jeremystone** [eclipse/jetty.project#2491]
When a number of large fragmented messages interspersed with smaller non-fragmented messages are sent over a websocket to a slow client (or over a slow network), the client sometimes sees one of the smaller messages before the final fragment of the previously sent larger message.

The stack trace on the client is:

```
org.eclipse.jetty.websocket.api.ProtocolException: Unexpected TEXT frame, was expecting CONTINUATION
	at org.eclipse.jetty.websocket.common.Parser.parseFrame(Parser.java:329)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:241)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:560)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:391)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)
```

Note that we first noticed this with a jetty 9.4.9 server and a netty based client (and netty detects the same thing) so the problem is likely with the fragment creation (in this case on the server end) rather than with the fragment re-assembly on the client.

I have created [this gist](https://gist.github.com/jeremystone/70fd540cf559aec6148c8e9c333abc1c) which is a JUnit test case that shows that this seems to happen only with 'slow' readers. (Our original netty/jetty setup required a moderately slow internet link or something like NetLimiter to reliably reproduce it.)

Please let me know if you need any further information.

**Comment by joakime** [comment]
Bizarre.

The stacktrace shows that a parser Exception.
That's single threaded and reads/parses the stream.  Can't see how we could screw that up.
We've been (since 2009) constantly test our implementations against autobahn (the de facto websocket standard testing lib) and pywebsocket (the lib maintained by google/chrome).
This kind of bug would be surprising.

**Comment by jeremystone** [comment]
I added some logging to the test and grepped everything out except the just the 'nextOutgoingFrame' debug logging in FragmentExtension (see log for failing test [here](https://github.com/eclipse/jetty.project/files/1951147/jettytest_server.txt)). 

It appears as if everything happens initially on the 'server response' thread (which is what I called the single thread that does the send) neatly passing on 10 fragmented frames then a short full message frame. But after a while some stuff happens on a 'qtp523691575-17' thread. 

Not sure if this is relevant(?)

**Comment by joakime** [comment]
You can follow along at the test project at - https://github.com/joakime/websocket-issue-2491

**Comment by jeremystone** [comment]
OK. Thanks. Glad you're seeing it too.

**Comment by joakime** [comment]
The backpressure behaviors are not the cause.

Need to dig into WebSocketRemoteEndpoint and FrameFlusher to see if the fault lies there.

**Comment by joakime** [comment]
WebSocketRemoteEndpoint and FrameFlusher are not at fault.

Taking a closer look at the FragmentExtension now.

**Comment by joakime** [comment]
I've been able to narrow down the fault to the `FragmentExtension`.  I have a testcase that can now replicate the issue in isolation of all of the rest of the components.

**Comment by jeremystone** [comment]
Well done for getting to the bottom of that one!

Will there be a release soon do you know, or should we build from sources?

Many thanks.

**Comment by joakime** [comment]
9.4.10 final release should occur sometime within the next 2 weeks.
Once I get a CI verification of this fix, I'll push a SNAPSHOT at least (for you)

**Comment by joakime** [comment]
@jeremystone please try Jetty 9.4.10.RC1 (currently on maven central)

**Comment by jeremystone** [comment]
9.4.10.RC1 looks good. Not been able to reproduce with this. Thanks again.
