### ISSUE TITLE
NPE at SslClientConnectionFactory.newConnection()

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#2516]
Version 9.4.10.v20180503

I'm seeing the following error in my application but it's not clear what is triggering it in the first place because the stack trace does not mention who schedules the request in the first place.

```
java.lang.NullPointerException
		at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
		at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
		at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
		at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
		... 21 common frames omitted
Caused by: java.lang.NullPointerException: null
		at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.newConnection(SslClientConnectionFactory.java:70)
		at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.newConnection(AbstractConnectorHttpClientTransport.java:175)
		at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:227)
		at org.eclipse.jetty.io.ManagedSelector.access$1500(ManagedSelector.java:60)
		at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:840)
		... 3 common frames omitted
```

Is this enough for you to work on this? Perhaps you could add validation and improved error reporting for this case?

**Comment by cowwoc** [comment]
I just discovered this was caused by instantiating a `HttpClient` with the default constructor. Passing in a `SslContextFactory` fixed the problem.

I think improving the error message for this case would go a long way to reduce confusion. The error message could be something along the lines of "Attempted to request an HTTPS address using a HttpClient that was not configured to do so. Please pass a SslContextFactory into the HttpClient constructor." You might also want to through an `IllegalStateException` for this case instead of `NullPointerException`.
