### ISSUE TITLE
Seemingly random InputStreamResponseListener and TimeoutException failures

### ISSUE THREAD

**Issue by rgriffith** [eclipse/jetty.project#2527]
Jetty version: 9.4.6.v20170531

In our application, we use `InputStreamResponseListener` to perform a GET request (with timeout) to a URL so the response content can be parsed as XML:

**Code snippet with `InputStreamResponseListener`**

```
final DocumentBuilder builder = AssemblerDocumentBuilderFactory.getBuilder();
try
{
    LOG.debug("getFeed: fetching for url " + this.feedURLLocation + " using a timeout of ", this.timeout);

    InputStreamResponseListener listener = new InputStreamResponseListener();
    new URLTester().sendNonBlockingRequestToUrl(this.feedURLLocation, this.timeout, HttpMethod.GET, listener);
    org.w3c.dom.Document document = builder.parse(listener.getInputStream());

    LOG.debug("getFeed: fetched for url " + this.feedURLLocation + ":\n" + convertDocumentToString(document));

    return document;
}
catch (Exception e)
{
    throw new SAXException("Could not parse feed location " + this.feedURLLocation + ": " + e.getMessage(), e);
}
```

**Code snippet with `HttpClient` initialization and request handling**

```
/**
 * Performs a non-blocking request to given <code>url</code> with given <code>timeout</code> and
 * <code>requestMethod</code>. Once the server responds to the request, the request times out or cannot
 * connect at all, result is passed to waiting <code>completeListener</code>.
 * 
 * @param url A valid URL to connect to
 * @param timeout A valid timeout in milliseconds greater than 0; otherwise, no timeout will be used.
 * @param requestMethod The {@link HttpMethod} in which the request should be made
 * @param completeListener Listens for result of request: server response, timeout out or can't connect
 */
public void sendNonBlockingRequestToUrl(String url, int timeout, HttpMethod requestMethod, Response.CompleteListener completeListener)
{
    LOG.debug("Performing a non-blocking request to url: ", url, " with timeout: ", timeout," (ms) and method:", requestMethod);
    HttpClient client = getHttpClient();
    if (client == null)
    {
        LOG.debug("HttpClient is not available, unable to process links. It's likely that the container sent a shutdown request and is in the process of stopping");
        return;
    }

    Request request = client.newRequest(url).method(requestMethod).accept("*/*");

    if (timeout > 0)
        request.timeout(timeout, TimeUnit.MILLISECONDS);
    else
        LOG.debug("No timeout will be used when requesting the url: ", url);

    request.send(completeListener);
}

/**
 * Synchronized to avoid two threads initializing at once.
 * 
 * @return Returns an existing HttpClient or instantiates a new one with our custom threadpool or returns
 *         null if the system is being shutdown
 */
private static synchronized HttpClient getHttpClient()
{
    if (isShutdown)
        return null;

    if (httpClient == null || !httpClient.isRunning())
    {
        try
        {
            SslContextFactory sslFactory = new SslContextFactory(true);

            /*
             As of v9.3.0, Jetty excludes older protocols and ciphers by default. This clears those exclusions so connections to less
             secure servers are not blocked.
             TODO: based on Jetty documentation they may be planning to drop this functionality when TLSv1.3 comes out
            */
            sslFactory.setExcludeProtocols();
            sslFactory.setExcludeCipherSuites();

            httpClient = new HttpClient(sslFactory);
            httpClient.setFollowRedirects(true);

            // Disable cookie handling to prevent eventual request header size issues.
            httpClient.setCookieStore(new HttpCookieStore.Empty());

            // Supply our own ThreadPool with minimum 4 threads and max of (Runtime.getRuntime().availableProcessors() * 4)
            // or at least 8 threads.
            //
            // Note: a number of the threads in the pool will be allocated as ClientSelectorManagers that handle the
            // orchestration of NIO. The number of ClientSelectorManagers initialized depends on the number of
            // available processors on the server. So it's possible to actually starve the client's threadpool by
            // not providing enough threads to actually create connections after allocating:
            //
            // Math.max(1, Runtime.getRuntime().availableProcessors() / 2)
            //
            // as selector threads as Jetty does on init in HttpClientTransportOverHTTP. When this happens, connections
            // will consistently timeout with response code 0 because there are not enough available threads to connect.
            QueuedThreadPool jettyThreadPool = new QueuedThreadPool(Math.max(8,Runtime.getRuntime().availableProcessors() * 4), 4);
            jettyThreadPool.setDaemon(true);

            // To be consistent with the naming in the HttpClient constructor
            String name = HttpClient.class.getSimpleName() + "@" + httpClient.hashCode();
            jettyThreadPool.setName(name);
            httpClient.setExecutor(jettyThreadPool);

            httpClient.start();
        }
        catch (Exception e)
        {
            throw new RuntimeException("HTTP Client could not be started: " + e.getMessage(), e);
        }
    }

    return httpClient;
}
```

Firstly, we’re looking to see if our above code is correct usage of `InputStreamResponseListener`, or if we should change this to be closer to the example at the bottom of [this page](https://www.eclipse.org/jetty/documentation/9.4.x/http-client-api.html#http-client-content). Also, can anyone clarify if this is blocking or non-blocking? The example says “wait for response” so I’m a little unclear on that. If non-blocking, are there any blocking equivalents that do not impose the 2MB limit or require explicitly setting a limit?

Secondly, we’ve noticed that in some cases our application eventually starts running into frequent `TimeoutException` errors surrounding this code and once that occurs all future requests seem to fail with similar errors. This appears to be specific to a particular client environment where the application is running, because we have not been able to reproduce the behavior ourselves. This is making it difficult to gather more specifics on what the problem is. 

We have some debug logging from this client (see blow, [full logging here](https://s3.amazonaws.com/hannonhill-support/siu-cascade.log)) that shows requests with a timeout of 20 seconds failing to connect (and timeout) after about 15 seconds, retry connecting, and then fail/timeout again after another 15 seconds.

Additionally, in the associated `QueuedThreadPool` logging, it looks like some jobs start and run, but are never marked as ran. Specifically, we’re seeing 22 “queue”, 22 “run” and 20 “ran” throughout this debug logging. Similarly, in the associated `EatWhatYouKill` logging, there are 12 occurrences of “produce non-blocking” and only 11 “produce exit” entries.

At this point we’re speculating if perhaps this could be related to #2311 or #973, but since we can’t reproduce the behavior in our environment it’s difficult to pinpoint the cause of these seemingly random timeouts and failures. 

We would appreciate any pointers/suggestions we can get. Thank you in advance and please let me know if you require any additional information.

**Logging snippet ([full logging here](https://s3.amazonaws.com/hannonhill-support/siu-cascade.log))**

```
2018-05-04 13:27:57,949 DEBUG [FeedFetcher] {User: jessica, id: 331a3c977f0000010119105660c8e53b, type: not specified} getFeed: fetching for url https://news.siu.edu/index.xml using a timeout of 20000
2018-05-04 13:27:57,950 DEBUG [URLTester] {User: jessica, id: 331a3c977f0000010119105660c8e53b, type: not specified} Performing a non-blocking request to url: https://news.siu.edu/index.xml with timeout: 20000 (ms) and method:GET
2018-05-04 13:27:57,950 DEBUG [TimeoutCompleteListener] Scheduled timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@722393ef in 20000 ms for HttpRequest[GET /index.xml HTTP/1.1]@4bfaf8b
2018-05-04 13:27:57,950 DEBUG [HttpDestination] Queued HttpRequest[GET /index.xml HTTP/1.1]@4bfaf8b for HttpDestination[https://news.siu.edu]@2928b3d3,queue=1,pool=DuplexConnectionPool@139d82fe[c=0/64,a=0,i=0]
2018-05-04 13:27:57,950 DEBUG [AbstractConnectionPool] Connection 1/64 creation
2018-05-04 13:27:57,950 DEBUG [QueuedThreadPool] queue org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@15fe1e88
2018-05-04 13:27:57,951 DEBUG [QueuedThreadPool] run org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@15fe1e88
2018-05-04 13:27:57,954 DEBUG [QueuedThreadPool] ran org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@15fe1e88
2018-05-04 13:28:07,257 DEBUG [HttpClientTransport] Could not connect to HttpDestination[http://business.siu.edu]@4c3832fa,queue=0,pool=DuplexConnectionPool@100e68cc[c=1/64,a=0,i=0]
2018-05-04 13:28:07,257 DEBUG [AbstractConnectionPool] Connection 1/64 creation failed
java.net.SocketTimeoutException: Connect Timeout
	at org.eclipse.jetty.io.ManagedSelector$ConnectTimeout.run(ManagedSelector.java:681)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-04 13:28:12,954 DEBUG [HttpClientTransport] Could not connect to HttpDestination[https://news.siu.edu]@2928b3d3,queue=1,pool=DuplexConnectionPool@139d82fe[c=1/64,a=0,i=0]
2018-05-04 13:28:17,950 DEBUG [TimeoutCompleteListener] Executing timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@722393ef for HttpRequest[GET /index.xml HTTP/1.1]@4bfaf8b
2018-05-04 13:28:17,950 DEBUG [HttpExchange] Failed HttpExchange@3d14d95f req=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@2a2da3f4 res=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@2a2da3f4: req=true/rsp=true java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
2018-05-04 13:28:17,950 DEBUG [HttpExchange] Aborting while queued HttpExchange@3d14d95f req=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@2a2da3f4 res=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@2a2da3f4: java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
2018-05-04 13:28:17,950 DEBUG [InputStreamResponseListener] Content failure
java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-04 13:28:17,950 DEBUG [TimeoutCompleteListener] Cancelled (successfully: true) timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@722393ef
2018-05-04 13:28:17,950 DEBUG [InputStreamResponseListener] Result failure
java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-04 13:28:17,975 DEBUG [FeedFetcher] {User: jessica, id: 331a3c977f0000010119105660c8e53b, type: not specified} getFeed: fetching for url https://siu.edu/feed.xml using a timeout of 20000
2018-05-04 13:28:17,976 DEBUG [URLTester] {User: jessica, id: 331a3c977f0000010119105660c8e53b, type: not specified} Performing a non-blocking request to url: https://siu.edu/feed.xml with timeout: 20000 (ms) and method:GET
2018-05-04 13:28:17,976 DEBUG [TimeoutCompleteListener] Scheduled timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@28c94ff4 in 20000 ms for HttpRequest[GET /feed.xml HTTP/1.1]@607b1ffe
2018-05-04 13:28:17,978 DEBUG [HttpDestination] Queued HttpRequest[GET /feed.xml HTTP/1.1]@607b1ffe for HttpDestination[https://siu.edu]@2fe1d344,queue=1,pool=DuplexConnectionPool@f4b6c67[c=0/64,a=0,i=0]
2018-05-04 13:28:17,978 DEBUG [AbstractConnectionPool] Connection 1/64 creation
2018-05-04 13:28:17,978 DEBUG [QueuedThreadPool] queue org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@304aa721
2018-05-04 13:28:17,978 DEBUG [QueuedThreadPool] run org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@304aa721
2018-05-04 13:28:17,979 DEBUG [QueuedThreadPool] ran org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@304aa721
2018-05-04 13:28:27,954 DEBUG [HttpClientTransport] Could not connect to HttpDestination[https://news.siu.edu]@2928b3d3,queue=0,pool=DuplexConnectionPool@139d82fe[c=1/64,a=0,i=0]
2018-05-04 13:28:27,955 DEBUG [AbstractConnectionPool] Connection 1/64 creation failed
java.net.SocketTimeoutException: Connect Timeout
	at org.eclipse.jetty.io.ManagedSelector$ConnectTimeout.run(ManagedSelector.java:681)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-04 13:28:32,980 DEBUG [HttpClientTransport] Could not connect to HttpDestination[https://siu.edu]@2fe1d344,queue=1,pool=DuplexConnectionPool@f4b6c67[c=1/64,a=0,i=0]
2018-05-04 13:28:37,976 DEBUG [TimeoutCompleteListener] Executing timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@28c94ff4 for HttpRequest[GET /feed.xml HTTP/1.1]@607b1ffe
2018-05-04 13:28:37,976 DEBUG [HttpExchange] Failed HttpExchange@1fc5a6d7 req=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@4804a51 res=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@4804a51: req=true/rsp=true java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
2018-05-04 13:28:37,976 DEBUG [HttpExchange] Aborting while queued HttpExchange@1fc5a6d7 req=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@4804a51 res=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@4804a51: java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
2018-05-04 13:28:37,976 DEBUG [InputStreamResponseListener] Content failure
java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-04 13:28:37,976 DEBUG [TimeoutCompleteListener] Cancelled (successfully: true) timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@28c94ff4
2018-05-04 13:28:37,976 DEBUG [InputStreamResponseListener] Result failure
java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-04 13:28:38,004 DEBUG [FeedFetcher] {User: jessica, id: 331a3c977f0000010119105660c8e53b, type: not specified} getFeed: fetching for url http://business.siu.edu/news/index.xml using a timeout of 20000
2018-05-04 13:28:38,004 DEBUG [URLTester] {User: jessica, id: 331a3c977f0000010119105660c8e53b, type: not specified} Performing a non-blocking request to url: http://business.siu.edu/news/index.xml with timeout: 20000 (ms) and method:GET
2018-05-04 13:28:38,005 DEBUG [TimeoutCompleteListener] Scheduled timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@7bd61371 in 20000 ms for HttpRequest[GET /news/index.xml HTTP/1.1]@7f36d4e4
2018-05-04 13:28:38,005 DEBUG [HttpDestination] Queued HttpRequest[GET /news/index.xml HTTP/1.1]@7f36d4e4 for HttpDestination[http://business.siu.edu]@4c3832fa,queue=1,pool=DuplexConnectionPool@100e68cc[c=0/64,a=0,i=0]
2018-05-04 13:28:38,005 DEBUG [AbstractConnectionPool] Connection 1/64 creation
2018-05-04 13:28:38,005 DEBUG [QueuedThreadPool] queue org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@5d3f807f
2018-05-04 13:28:38,005 DEBUG [QueuedThreadPool] run org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@5d3f807f
2018-05-04 13:28:38,006 DEBUG [QueuedThreadPool] ran org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$63/113533606@5d3f807f
2018-05-04 13:28:47,980 DEBUG [HttpClientTransport] Could not connect to HttpDestination[https://siu.edu]@2fe1d344,queue=0,pool=DuplexConnectionPool@f4b6c67[c=1/64,a=0,i=0]
2018-05-04 13:28:47,980 DEBUG [AbstractConnectionPool] Connection 1/64 creation failed
java.net.SocketTimeoutException: Connect Timeout
	at org.eclipse.jetty.io.ManagedSelector$ConnectTimeout.run(ManagedSelector.java:681)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-04 13:28:53,006 DEBUG [HttpClientTransport] Could not connect to HttpDestination[http://business.siu.edu]@4c3832fa,queue=1,pool=DuplexConnectionPool@100e68cc[c=1/64,a=0,i=0]
2018-05-04 13:28:58,005 DEBUG [TimeoutCompleteListener] Executing timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@7bd61371 for HttpRequest[GET /news/index.xml HTTP/1.1]@7f36d4e4
2018-05-04 13:28:58,005 DEBUG [HttpExchange] Failed HttpExchange@37dfe38e req=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@59e18bc res=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@59e18bc: req=true/rsp=true java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
2018-05-04 13:28:58,005 DEBUG [HttpExchange] Aborting while queued HttpExchange@37dfe38e req=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@59e18bc res=COMPLETED/java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed@59e18bc: java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
2018-05-04 13:28:58,005 DEBUG [InputStreamResponseListener] Content failure
java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-04 13:28:58,005 DEBUG [TimeoutCompleteListener] Cancelled (successfully: true) timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@7bd61371
2018-05-04 13:28:58,005 DEBUG [InputStreamResponseListener] Result failure
java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sbordet** [comment]
Your `sendNonBlockingRequestToUrl()` blindly passes `InputStreamResponseListener` to `send(...)` but you don't appear to check the response code, so you may well be reading the content of a 500 response.

`InputStreamResponseListener` is blocking in both the `get(...)` call (that waits for the response headers to arrive), and in the normal `InputStream` semantic (i.e. blocking `read()` methods).

Your full log is probably wrong, as it reports Spring startup errors, but not `HttpClient` errors.

From what you pasted in the comment above, you have some serious network issue because you cannot even establish TCP connections (connect timeouts) .
Total timeout failures relate to the fact that the request/response cycle could not finish within 20 seconds.
It may mean that the network is really slow, or really broken.
If you set an idle timeout smaller than the total timeout, you can tell whether the network is active but slow, or whether nothing happens on the network at all.

I would not bother about "run", "ran", etc.: it is normal that some thread in the thread pool is waiting in some operation, so it will complete later.

**Comment by sbordet** [comment]
A connect timeout aborts the request. It will not be retried by Jetty.
The default `idleTimeout` is `0` which means that the client won't idle timeout.

I think your thread pool setting is way too small.
Leave it at default to start with, analyze the usage and load, and then configure it.

**Comment by rgriffith** [comment]
Thank you for following up, @sbordet.

> I think your thread pool setting is way too small. Leave it at default to start with, analyze the usage and load, and then configure it.

Definitely agreeing with you here. If we go with defaults, is it recommended to still provide a custom thread pool, or can we just let Jetty handle that when the HttpClient is started?

**Comment by sbordet** [comment]
@rgriffith Jetty's `QueuedThreadPool` hardcodes by default min and max at 8 and 200 respectively.
There is no automatic way of determining the optimal thread pool size, as it depends on how the application uses the threads, the load, the protocol, etc. It's a trial/error exercise.

`Request.timeout` imposes a total timeout on the exchange (request + response) and when it expires it aborts the request (or response).
`InputStreamResponseListener.get()` is decided by you on the spot, depending on how much you want to wait _for the response headers_ (see javadocs).
It has the same semantic of `Future.get()`, i.e. you can call it multiple times and has no side effects (in particular, it does not abort the request).
`InputStreamResponseListener.await()` waits for the request+response completion, and has the same semantic as `get()`, i.e. can be called multiple times and has no side effects.

**Comment by joakime** [comment]
This has been idle for a while.  Can it be closed?

**Comment by sbordet** [comment]
@rgriffith reopen if necessary.
