### ISSUE TITLE
Broken Test:  linux_jdk10 / Test - jdk10 / org.eclipse.jetty.websocket.client.ClientConnectTest.testConnectionTimeout_Concurrent

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#2536]
**Error Message**
Unexpected exception, expected<java.util.concurrent.TimeoutException> but was<java.lang.AssertionError>
**Stacktrace**
java.lang.Exception: Unexpected exception, expected<java.util.concurrent.TimeoutException> but was<java.lang.AssertionError>
	at org.eclipse.jetty.websocket.client.ClientConnectTest.assertExpectedError(ClientConnectTest.java:80)
	at org.eclipse.jetty.websocket.client.ClientConnectTest.testConnectionTimeout_Concurrent(ClientConnectTest.java:491)

**Comment by sbordet** [comment]
Got a better stack trace for the failure:

```
2018-05-16 13:54:31.292:INFO::main: Logging initialized @516ms to org.eclipse.jetty.util.log.StdErrLog

Disconnected from the target VM, address: '127.0.0.1:41881', transport: 'socket'

java.util.concurrent.ExecutionException: org.eclipse.jetty.websocket.api.UpgradeException: 0 null

	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.jetty.websocket.client.ClientConnectTest.testConnectionTimeout_Concurrent(ClientConnectTest.java:485)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:67)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.eclipse.jetty.websocket.api.UpgradeException: 0 null
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:515)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:216)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:208)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:470)
	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:552)
	at org.eclipse.jetty.client.HttpReceiver.responseFailure(HttpReceiver.java:442)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.failAndClose(HttpReceiverOverHTTP.java:369)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:338)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1476)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:209)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:147)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.EOFException: HttpConnectionOverHTTP@57ce0279(l:/127.0.0.1:35866 <-> r:/127.0.0.1:35219,closed=false)=>HttpChannelOverHTTP@36772f48(exchange=HttpExchange@3248bd5e req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@774a2573(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@49f59c12{s=START}],recv=HttpReceiverOverHTTP@46f7f70b(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]<-SocketChannelEndPoint@31a210c6{/127.0.0.1:35219<->/127.0.0.1:35866,ISHUT,fill=-,flush=-,to=5/0}{io=0/0,kio=0,kro=1}->HttpConnectionOverHTTP@57ce0279(l:/127.0.0.1:35866 <-> r:/127.0.0.1:35219,closed=false)=>HttpChannelOverHTTP@36772f48(exchange=HttpExchange@3248bd5e req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@774a2573(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@49f59c12{s=START}],recv=HttpReceiverOverHTTP@46f7f70b(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
	... 13 more


Process finished with exit code 255
```

**Comment by sbordet** [comment]
This is strange.

The server is written in a way that it accepts the socket, but does nothing with it, in particular does not close them.
The test code waits for a `TimeoutException`.
However, the client reads -1 from the server and aborts the upgrade before it times out.

The only explanation I have is that the accepted socket has been GCd, and `AbstractPlainSocketImpl.finalize()` is called, which closes the accepted socket, causing the stack trace above.

**Comment by sbordet** [comment]
Confirmed.

After adding multiple calls to `System.gc()` after the socket has been accepted, but before the test waits on `get(...)`, the stack trace above is reproducible 100% of the times at the first run.
