### ISSUE TITLE
Exception from passing test SslSelectChannelTimeoutTest.testMaxIdleDispatch()

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2541]
```
[AdvancedRunner] Running org.eclipse.jetty.server.ssl.SslSelectChannelTimeoutTest.testMaxIdleDispatch()
Running org.eclipse.jetty.server.ssl.SslSelectChannelTimeoutTest.testMaxIdleDispatch()
2018-05-16 14:46:07.932:INFO:oejs.Server:main: jetty-9.4.11-SNAPSHOT; built: 2018-05-16T04:43:12.635Z; git: 820b5752d7207fc0ed5294d13887780f7b28a48c; jvm 9.0.1+11
2018-05-16 14:46:07.935:INFO:oejus.SslContextFactory:main: x509=X509@3516f436(jetty,h=[jetty.eclipse.org],w=[]) for SslContextFactory@59c00010[provider=null,keyStore=file:///usr/local/home/gregw/src/jetty-9.4.x/jetty-server/src/test/resources/keystore,trustStore=file:///usr/local/home/gregw/src/jetty-9.4.x/jetty-server/src/test/resources/keystore]
2018-05-16 14:46:07.935:INFO:oejus.SslContextFactory:main: x509=X509@244268a8(mykey,h=[],w=[]) for SslContextFactory@59c00010[provider=null,keyStore=file:///usr/local/home/gregw/src/jetty-9.4.x/jetty-server/src/test/resources/keystore,trustStore=file:///usr/local/home/gregw/src/jetty-9.4.x/jetty-server/src/test/resources/keystore]
2018-05-16 14:46:07.936:INFO:oejs.AbstractConnector:main: Started ServerConnector@17485452{SSL,[ssl, http/1.1]}{0.0.0.0:34507}
2018-05-16 14:46:07.937:INFO:oejs.Server:main: Started @2418ms
2018-05-16 14:46:10.063:WARN:oejs.HttpChannel:qtp1981113966-97: /
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 2000/2000 ms
	at org.eclipse.jetty.server.HttpInput$ErrorState.noContent(HttpInput.java:1075)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:313)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at org.eclipse.jetty.server.HttpServerTestFixture$EchoHandler.handle(HttpServerTestFixture.java:137)
	at org.eclipse.jetty.server.handler.HotSwapHandler.handle(HotSwapHandler.java:123)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: 
java.util.concurrent.TimeoutException: Idle timeout expired: 2000/2000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Suppressed: 
	|java.lang.Throwable: HttpInput failure
	|	at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:821)
	|	at org.eclipse.jetty.server.HttpConnection$BlockingReadCallback.failed(HttpConnection.java:649)
	|	at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:134)
	|	at org.eclipse.jetty.io.ssl.SslConnection.onFillInterestedFailed(SslConnection.java:318)
	|	at org.eclipse.jetty.io.ssl.SslConnection$3.failed(SslConnection.java:157)
	|	at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:134)
	|	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:406)
	|	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	|	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	|	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	|	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	|	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	|	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	|	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	|	at java.base/java.lang.Thread.run(Thread.java:844)

```

**Comment by lachlan-roberts** [comment]
no longer getting this stack trace after the [revert stack logging](https://github.com/eclipse/jetty.project/commit/4cc8f4dcf6c64eade4d34b2456061a9b243f002b) commit so this issue can be closed
