### ISSUE TITLE
Error on delete SessionWeb after expire when java.io.EOFException present

### ISSUE THREAD

**Issue by quartex** [eclipse/jetty.project#2554]
Hi,
I'm using jdbc to store Session Web on Mysql 5.5 on Jetty 9.4.9-jre8-alpine on Docker

The table auto created use a Blob with max 64Kb (field map) for single session data.
If Session is more 64 Kb (and the deserialization is invalid) a warm appears on log and the records will not never delete after expire date 

2018-05-17 09:54:26.422:WARN:oejs.session:Scheduler-1840976765:
org.eclipse.jetty.server.session.UnreadableSessionDataException: Unreadable session node0183rdi6n5bbhc1rkxmtawl1jkb370 for node0__0.0.0.0
        at org.eclipse.jetty.server.session.JDBCSessionDataStore$1.run(JDBCSessionDataStore.java:665)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1339)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1359)
        at org.eclipse.jetty.server.session.SessionContext.run(SessionContext.java:96)
        at org.eclipse.jetty.server.session.JDBCSessionDataStore.load(JDBCSessionDataStore.java:685)
        at org.eclipse.jetty.server.session.AbstractSessionCache.loadSession(AbstractSessionCache.java:462)
        at org.eclipse.jetty.server.session.AbstractSessionCache.get(AbstractSessionCache.java:362)
        at org.eclipse.jetty.server.session.AbstractSessionCache.delete(AbstractSessionCache.java:628)
        at org.eclipse.jetty.server.session.SessionHandler.removeSession(SessionHandler.java:1049)
        at org.eclipse.jetty.server.session.SessionHandler.invalidate(SessionHandler.java:1234)
        at org.eclipse.jetty.server.session.DefaultSessionIdManager.expireAll(DefaultSessionIdManager.java:475)
        at org.eclipse.jetty.server.session.SessionHandler.scavenge(SessionHandler.java:1276)
        at org.eclipse.jetty.server.session.HouseKeeper.scavenge(HouseKeeper.java:273)
        at org.eclipse.jetty.server.session.HouseKeeper$Runner.run(HouseKeeper.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by:
java.io.EOFException

**Comment by janbartel** [comment]
If you explicitly enable the session-cache-hash  module, you will find the file start.d/session-cache-hash.ini in your base directory. In there, you will find the property jetty.session.removeUnloadableSessions=false. Set that property to true, and any session that cannot be loaded will be deleted.

If you need a different type with greater storage capacity than 'blob' then you should be able to edit the etc/sessions/jdbc/driver.xml or etc/sessions/jdbc/datasource.xml to customize the DatabaseAdaptor to use a different blob type.

I will look at adding some extra parameterization so you can do that by editing properties in session-store-jdbc.ini instead.

**Comment by quartex** [comment]
Ok , thank you very much, I'll try to use jetty.session.removeUnloadableSessions to delete records to mitigate the problem.
