### ISSUE TITLE
java.nio.channels.ClosedChannelException on https files resource

### ISSUE THREAD

**Issue by quartex** [eclipse/jetty.project#2555]
Hi,
I'm using Jetty 9.4.9-jre8-alpine on Docker and I give different warning like this 

2018-05-16 18:35:04.271:WARN:oejs.HttpChannel:qtp846947180-17047: /xxxxxx/xxxxx/xxxxx/xxxxxxxxx
java.nio.channels.ClosedChannelException
        at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427)
        at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:507)
        at org.eclipse.jetty.io.ssl.SslConnection.onClose(SslConnection.java:257)
        at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:341)
        at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:859)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)

for different type of files (gif, cvs,css, js)
In my configuration is present last version 1.59 for Bouncy Castle Crypto APIs and I tried to move the position on java.security but the warnings are always present.

Thanks you very much for any help

**Comment by joakime** [comment]
Do you have a `Dockerfile` that can replicate this?

**Comment by quartex** [comment]
Hi,
it's not easy for us give the Docker for db data dependency and I do not know yet how to recreate the problem with a know path. 

Could you suggest me any other logs or data that help you / me to understand better the problem ? 
  
Thank you very much

**Comment by quartex** [comment]
Hi,
there are a jsp errors too very similar :

2018-05-18 14:18:42,129 [qtp846947180-42016] ERROR org.apache.jsp.index_jsp - error: java.nio.channels.ClosedChannelException
org.eclipse.jetty.io.RuntimeIOException: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.server.ResponseWriter.isOpen(ResponseWriter.java:133)
	at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:202)
	at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:112)
	at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:329)
	at java.io.Writer.write(Writer.java:157)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:1674)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:856)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427)
	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:507)
	at org.eclipse.jetty.io.ssl.SslConnection.onClose(SslConnection.java:257)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:341)
	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:859)

**Comment by joakime** [comment]
Can you test without the Bouncy Castle Crypto APIs ?

**Comment by joakime** [comment]
Closing this as unable to replicate.

The jre8-alpine images that was claimed to be the source are not supported anyway.
See: https://github.com/appropriate/docker-jetty/pull/118
If a reproducer outside of jre8-alpine is discovered, then feel free to comment here, and we'll reopen.
