### ISSUE TITLE
NoHttpResponseException when using digest from client.

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#256]
migrated from Bugzilla [#482566](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482566)
status NEW severity *normal* in component *server* for *9.3.x*
Reported in version *9.3.0* on platform *PC*
Assigned to: Project Inbox

On 2015-11-19 04:30:29 -0500, Jan Tore Boee wrote:

> When posting and the server requires digest authentication the client ignores the 401 and does not resend the post with the credentials if the post request was not completed before the response came from the server. This results in a NoHttpResponseException on the client.
> 
> Tested with version 9.3.0.RC0 to 9.3.6.v20151106 on the server and client.
> 
> The client uses org.eclipse.jetty.security.MappedLoginService to handle the authentication.
> 
> httpclient is version 4.3.6
> 
> Stacktrace:
> 
> org.apache.http.NoHttpResponseException: xxxxxxxx:12345 failed to respond
> 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
> 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
> 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
> 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
> 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
> 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
> 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
> 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
> 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
> 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
> 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)

On 2015-11-19 06:49:45 -0500, Jan Tore Boee wrote:

> After some investigation, MappedLogonService is ofc used on the server, the client uses httpclient to connect and communicate.

**Comment by joakime** [comment]
Unable to replicate on Jetty 9.3.7 with Digest auth and MappedLoginService.
Tested with curl --digest (version 7.43.0)

Please reopen if you have a good testcase.

**Comment by lokkju** [comment]
I'm experiencing this exact issue with sbt-aether-plugin 0.21 and Nexus OSS 3.4.0-02.  aether uses httpclient to send a PUT request which requires authentication; Nexus, using jetty, returns a 401, but the client never sees it.

I'm not sure if this is more a jetty issue, or more a httpclient issue.

> Caused by: org.apache.http.NoHttpResponseException: nexus:80 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:207)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:684)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:164)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:318)
	at org.eclipse.aether.transport.http.HttpTransporter.implPut(HttpTransporter.java:296)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.put(AbstractTransporter.java:126)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask(BasicRepositoryConnector.java:510)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put(BasicRepositoryConnector.java:274)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:320)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:254)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:422)
	at aether.AetherPlugin$class.deployIt(Plugin.scala:127)
	at aether.AetherPlugin$.deployIt(Plugin.scala:26)
	at aether.AetherPlugin$$anonfun$deployTask$1$$anonfun$apply$2.apply(Plugin.scala:74)
	at aether.AetherPlugin$$anonfun$deployTask$1$$anonfun$apply$2.apply(Plugin.scala:73)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sbordet** [comment]
If you are sure that Jetty returns 401, and you can verify that with a network trace for example using wireshark, then it's an Apache HttpClient issue.
