### ISSUE TITLE
org.eclipse.jetty.io.EofException: Early EOF happened when aborted an upload

### ISSUE THREAD

**Issue by zhna123** [eclipse/jetty.project#2562]
Hi.
Recently we encountered an issue - when we canceled a multi-part file upload from UI before the request reached the back-end upload end-point, an EOFException: Early EOF happened. 
Afterwards jetty would delete the partial received/saved multi-part file.

Here is the exception:
```

WARN org.eclipse.jetty.server.HttpChannel - </upload_path>
javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is org.eclipse.jetty.io.EofException: Early EOF

... ...

Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is org.eclipse.jetty.io.EofException: Early EOF

... ...


Caused by: org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is org.eclipse.jetty.io.EofException: Early EOF
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:112)
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:86)
	at org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:79)
	at org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1104)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:936)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	... 50 more
Caused by: org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1111)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1100)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at org.eclipse.jetty.util.ReadLineInputStream.read(ReadLineInputStream.java:103)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:705)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:441)
	at org.eclipse.jetty.server.Request.getParts(Request.java:2319)
	at org.eclipse.jetty.server.Request.getParts(Request.java:2298)
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:93)
... 56 more
```
We use jetty docker image. (JETTY_VERSION 9.4.2.v20170220)
spring version 4.3.9.RELEASE
Before jetty, we have nginx to proxy request.

Here is the change that made us discover this exception:

Nginx has a configuration "proxy_request_buffering", which defaults the value to be "on", so it always saved a copy of the upload file. Lately we decided to turn it off so the file will NOT be buffered by nginx, but the request will be sent directly to jetty, then to reach our back-end upload end-point. However, this change caused the early EOF when we aborted the upload while jetty was in the process of receiving/processing the file and request.

My understanding is, without nginx buffering the upload file, the upload request that sent to jetty was not completed when we canceled the upload, so the early EOF happened. If nginx request buffer turned on, since it buffered the request, jetty would receive the complete request, not throwing exception when we canceled the upload.

This issue didn't have a big impact on our side, especially when the exception was thrown, jetty deleted the multi-part file it had received. But I'd like to get some ideas of how to best handle this error? We don't really want to see a long exception stack trace every time the client aborts an upload. Any thoughts would be appreciated. 
 
Thank you!

**Comment by joakime** [comment]
I think this overlaps with Issue #2346

**Comment by zhna123** [comment]
Ah Ok. The version we used(9.4.2.v20170220) doesn't have the new changes, but the EofException extends QuietException, according to the handleException method [1], this warn log failure stack trace shouldn't show up for an EofException, unless we enable debug. Is that right?
[1] https://github.com/eclipse/jetty.project/blob/4a674b9cc96de3e28d4fddf9abb8e7d1a456db96/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L493

**Comment by sbordet** [comment]
@zhna123 that is correct. I believe your issue is solved if you upgrade to the latest Jetty.
