### ISSUE TITLE
Exceptions from passing tests in MisbehavingClassTest

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#2567]
[org/eclipse/jetty/websocket/jsr356/misbehaving/MisbehavingClassTest.java](https://github.com/eclipse/jetty.project/blob/09d40dc66507042f1cf865a89e7cacf431d2d584/jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/misbehaving/MisbehavingClassTest.java)

in tests `testListenerRuntimeOnConnect()` and `testAnnotatedRuntimeOnConnect()` the StacklessLogging is only working some of the time and other times the full stack traces are getting logged.

```
2018-05-23 19:10:12.162:WARN:oejwc.WebSocketSession:qtp910091170-26: 
java.lang.RuntimeException: Intentional Exception from onWebSocketConnect
	at org.eclipse.jetty.websocket.server.misbehaving.ListenerRuntimeOnConnectSocket.onWebSocketConnect(ListenerRuntimeOnConnectSocket.java:39)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onConnect(JettyListenerEventDriver.java:106)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:233)
	at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:616)
	at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:544)
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:202)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:446)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:440)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:385)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:702)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:498)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by gregw** [comment]
Probably a race between the thread clearing the stackless logging and the one logging it.

@lachlan-roberts can you confirm if it is different threads and if so how can the clearing be made to always happen after the log?

**Comment by lachlan-roberts** [comment]
fixed a similar exception in 
[org/eclipse/jetty/websocket/server/misbehaving/MisbehavingClassTest.java](https://github.com/eclipse/jetty.project/blob/09d40dc66507042f1cf865a89e7cacf431d2d584/jetty-websocket/websocket-server/src/test/java/org/eclipse/jetty/websocket/server/misbehaving/MisbehavingClassTest.java)
where the only problem was the ordering of the StacklessLogging in the try-with-resources

**Comment by joakime** [comment]
@lachlan-roberts please submit this as a PR.  I have comments to make.  Some things are 100% spot on correct with good commits, others are irksome.
