### ISSUE TITLE
Exceptions from passing test EchoTest.testEcho()

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#2569]
Getting somewhere in the range of 10-20 exceptions every time i run this test. Doesn't seem to be the same set of test cases every time.

```
2018-05-24 12:46:18.145:WARN:oejwjs.TrackingSocket:Time-limited test: 
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.succeedEntries(FrameFlusher.java:246)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.succeeded(FrameFlusher.java:234)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:342)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.flush(FrameFlusher.java:218)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.process(FrameFlusher.java:157)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:90)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:495)
	at org.eclipse.jetty.websocket.client.io.WebSocketClientConnection.outgoingFrame(WebSocketClientConnection.java:72)
	at org.eclipse.jetty.websocket.common.WebSocketSession.close(WebSocketSession.java:223)
	at org.eclipse.jetty.websocket.common.WebSocketSession.close(WebSocketSession.java:202)
	at org.eclipse.jetty.websocket.jsr356.JsrSession.close(JsrSession.java:147)
	at org.eclipse.jetty.websocket.jsr356.server.EchoClientSocket.close(EchoClientSocket.java:46)
	at org.eclipse.jetty.websocket.jsr356.server.EchoTest.testEcho(EchoTest.java:299)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by joakime** [comment]
Exception in flusher, during websocket close.
I think the close frame (websocket close handshake) wasn't able to be sent due to the channel being closed.
