### ISSUE TITLE
Test failure: QoSFilterTest.testBlockingQosFilter

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2627]
https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/391/testReport/junit/org.eclipse.jetty.servlets/QoSFilterTest/linux_jdk9___Test___jdk9___testBlockingQosFilter/

**Comment by joakime** [comment]
Details of failure ...

```
Stacktrace
java.util.concurrent.CancellationException
	at org.eclipse.jetty.servlets.QoSFilterTest.rethrowExceptions(QoSFilterTest.java:161)
	at org.eclipse.jetty.servlets.QoSFilterTest.testBlockingQosFilter(QoSFilterTest.java:124)

Standard Error
2018-06-05 21:39:41.987:INFO:oejs.Server:main: jetty-9.4.11-SNAPSHOT; built: 2018-06-05T21:31:54.135Z; git: d846414c66d68607c6c688d2b108ccd1bb75d70b; jvm 9.0.4+11
2018-06-05 21:39:41.990:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2018-06-05 21:39:41.990:INFO:oejs.session:main: No SessionScavenger set, using defaults
2018-06-05 21:39:41.990:INFO:oejs.session:main: node0 Scavenging every 660000ms
2018-06-05 21:39:41.990:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@22bfd4b{/context,null,AVAILABLE}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@79e16dd9{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@5fa9247b{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@21ce3b22{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@7cd25bf5{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@e2f6e13{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@18b30951{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@48f4264e{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@2697c156{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.AbstractConnector:main: Started LocalConnector@533d7c61{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:41.990:INFO:oejs.Server:main: Started @43235ms
2018-06-05 21:39:51.993:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@79e16dd9{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.993:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@5fa9247b{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.993:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@21ce3b22{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.994:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@7cd25bf5{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.994:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@e2f6e13{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.994:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@18b30951{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.994:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@48f4264e{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.995:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@2697c156{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.995:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@533d7c61{HTTP/1.1,[http/1.1]}
2018-06-05 21:39:51.995:INFO:oejs.session:main: node0 Stopped scavenging
2018-06-05 21:39:51.995:INFO:oejsh.ContextHandler:main: Stopped o.e.j.s.ServletContextHandler@22bfd4b{/context,null,UNAVAILABLE}
```

**Comment by joakime** [comment]
Unable to cause this failure locally on Windows or Fedora Core 27 with repeated testing.

**Comment by joakime** [comment]
Closing as `org.eclipse.jetty.servlets.QoSFilterTest` has been stable for over a year now.

**Comment by gregw** [comment]
Test is still disabled
