### ISSUE TITLE
Test Failure: ResourceTest

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#2628]
This just started failing for me locally when built from top level:

```
[INFO] Running org.eclipse.jetty.util.resource.ResourceTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.01 s <<< FAILURE! - in org.eclipse.jetty.util.resource.ResourceTest
[ERROR] initializationError(org.eclipse.jetty.util.resource.ResourceTest)  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.AssertionError: Can only delete content within the /target/tests/ directory: /home/gregw/src/jetty-9.4.x/jetty-util/target/ResourceTest with spaces
	at org.eclipse.jetty.util.resource.ResourceTest.data(ResourceTest.java:200)

```

**Comment by gregw** [comment]
```
java.lang.AssertionError: Can only delete content within the /target/tests/ directory: /home/gregw/src/jetty-9.4.x/jetty-util/target/ResourceTest with spaces
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.eclipse.jetty.toolchain.test.FS.recursiveDeleteDir(FS.java:186)
	at org.eclipse.jetty.toolchain.test.FS.deleteDirectory(FS.java:110)
	at org.eclipse.jetty.toolchain.test.FS.cleanDirectory(FS.java:239)
	at org.eclipse.jetty.toolchain.test.FS.ensureEmpty(FS.java:264)
	at org.eclipse.jetty.toolchain.test.FS.ensureEmpty(FS.java:251)
	at org.eclipse.jetty.util.resource.ResourceTest.data(ResourceTest.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.runners.Parameterized.allParameters(Parameterized.java:280)
	at org.junit.runners.Parameterized.<init>(Parameterized.java:248)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:87)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:73)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by gregw** [comment]
```
[2059] ls -alR jetty-util/target/ResourceTest\ with\ spaces/
'jetty-util/target/ResourceTest with spaces/':
total 8
drwxrwsr-x  2 gregw gregw 4096 Jun  6 10:38 ./
drwxrwsr-x 15 gregw gregw 4096 Jun  6 10:42 ../
-rw-rw-r--  1 gregw gregw    0 Jun  6 10:38 test.tmp
```

**Comment by gregw** [comment]
The test only works from a clean build.

**Comment by joakime** [comment]
@gregw fixed.
