### ISSUE TITLE
occasional exception stack trace in UnixSocketTest

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#2634]
Getting exception stack trace printed out about 1 out of every 10 times I run the test, the test still passes when the stack trace is displayed

```
2018-06-07 08:31:23.735:INFO::main: Logging initialized @663ms to org.eclipse.jetty.util.log.StdErrLog
2018-06-07 08:31:24.723:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT; built: unknown; git: ; jvm 9.0.4+11
2018-06-07 08:31:24.846:INFO:oejs.AbstractConnector:main: Started UnixSocketConnector@5a7fe64f{HTTP/1.1,[http/1.1]}{/Users/Lachlan/webtide/jetty.project/jetty-unixsocket/target/tests/testUnixSocket/unix.sock}
2018-06-07 08:31:24.848:INFO:oejs.Server:main: Started @1776ms
2018-06-07 08:31:24.946:INFO:oeju.UnixSocketTest:qtp1428475041-23: UnixSocketTest: request received
2018-06-07 08:31:24.990:WARN:oeji.ChannelEndPoint:HttpClient@1b66c0fb-29: Ignoring key update for UnixSocketEndPoint@1cbe5747{null<->null,CLOSED,fill=FI,flush=-,to=2/0}{io=1/1,kio=-1,kro=-1}->HttpConnectionOverHTTP@52116146(l:null <-> r:null,closed=true)=>HttpChannelOverHTTP@1881d008(exchange=null)[send=HttpSenderOverHTTP@5d835d7c(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@27e8fcf{s=START}],recv=HttpReceiverOverHTTP@6c94e4a8(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]
java.lang.NullPointerException
	at jnr.enxio.channels.KQSelector$Descriptor.access$000(KQSelector.java:75)
	at jnr.enxio.channels.KQSelector.handleChangedKey(KQSelector.java:247)
	at jnr.enxio.channels.KQSelector.interestOps(KQSelector.java:301)
	at jnr.enxio.channels.KQSelectionKey.interestOps(KQSelectionKey.java:60)
	at org.eclipse.jetty.io.ChannelEndPoint.updateKey(ChannelEndPoint.java:381)
	at org.eclipse.jetty.io.ChannelEndPoint$1.update(ChannelEndPoint.java:103)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processUpdates(ManagedSelector.java:358)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:329)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-06-07 08:31:25.006:INFO:oejs.AbstractConnector:main: Stopped UnixSocketConnector@5a7fe64f{HTTP/1.1,[http/1.1]}{/Users/Lachlan/webtide/jetty.project/jetty-unixsocket/target/tests/testUnixSocket/unix.sock}

Process finished with exit code 0
```

**Comment by joakime** [comment]
On Linux eh?   what OS?

**Comment by lachlan-roberts** [comment]
on OSX 10.13.4
java 9.0.4

**Comment by joakime** [comment]
So on OSX it shows a stacktrace, but doesn't fail the testcase? huh?

**Comment by lachlan-roberts** [comment]
most of the time it doesn't show the stacktrace but if i keep running the test it eventually shows up, sometimes on the first time, sometimes i have to run it like 10 times before i see it, but it doesnt fail even when the stacktrace is printed

i tried to look into it the other day and couldn't work out what the problem was

**Comment by gregw** [comment]
Probably a bug in JNR as we only pass in an integer, so not much scope for us to be the cause.... unless we are stopping the connector while something is happening?   Actually the later is more likely as I can see the endpoint is CLOSED!   but still possibly JNR bug as it should not NPE even if the key is invalid/closed.

 I note there is now a 0.19 release, so try updating JNR and seeing if we can get the same exception.  We could then raise a bug on them for it.

Ultimately it could be an ignorable exception rather than a warning.

**Comment by olamy** [comment]
looks to be fixed here https://github.com/jnr/jnr-enxio/pull/31
upgrading jnr library is the fix
