### ISSUE TITLE
java.util.concurrent.TimeoutException: Idle timeout expired: 300001/300000 ms

### ISSUE THREAD

**Issue by Fxztam** [eclipse/jetty.project#2637]
I am on jetty-all-9.4.10.v20180503-uber.jar an getting from the WebSocket Server side :
**java.util.concurrent.TimeoutException: Idle timeout expired: 300001/300000 ms
Socket Closed: CloseReason[1001,Idle Timeout]**
Socket Closed: CloseReason[1001,Idle Timeout]
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

That comes only once, everything else works very well.

**Comment by joakime** [comment]
That's normal for an idle websocket connection.
