### ISSUE TITLE
Jetty Unexpected thread death and then no request can be processed

### ISSUE THREAD

**Issue by hzy38324** [eclipse/jetty.project#2688]
We have a online machine using Jetty, and we found jetty warned '**Locker is not reentrant**' and '**Unexpected thread death**', after that no request can be processed because there is no more log.  

**Why jetty can not handle any request when one of its thread died, since there are others thread in QueuedThreadPool?**  

We think it is a bug.

Here is our log:  
```
2018-06-24 09:15:59.698 [qtp1137078855-25] WARN  [] [] [] o.e.j.util.thread.QueuedThreadPool - 
java.lang.IllegalStateException: 
	at org.eclipse.jetty.util.thread.Locker.lock(Locker.java:47)Locker is not reentrant
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:202)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
2018-06-24 09:15:59.698 [qtp1137078855-25] WARN  [] [] [] o.e.j.util.thread.QueuedThreadPool - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@43f9f0ff in org.eclipse.jetty.util.thread.QueuedThreadPool@qtp1137078855{STARTED,8<=8<=200,i=2,q=0}
```

**Comment by gregw** [comment]
Version? Operating System? Load? repeatable?

**Comment by hzy38324** [comment]
Version: 9.4.7  
Operation System: Linux

**Comment by joakime** [comment]
Jetty 9.4.7 is vulnerable, and shouldn't be run in a production capacity.

See: [Jetty CVE Announcements - June 2018](https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00123.html)

There's also been a few improvements with QueuedThreadPool and the thread execution behaviors in 9.4.8, and 9.4.10 that you would get benefit from.

**Comment by hzy38324** [comment]
Yeah, maybe upgrade jetty will solve the problem.  
But as long as we don't figure out the root cause, there is no guarantee that it won't happen again. It may be a potential bug that will also affects the other jetty users.  
 
We still want to know what may cause jetty to fail to respond after one of its worker thread died.  
Can you give us some possible reasons?

**Comment by firebiird** [comment]
I found a time where this can happen : If your filtering a collection stream and you get a null pointer inside the stream filter it will cause this unexpected thread death.

**Comment by sbordet** [comment]
@firebiird can you please detail where the collection stream is being processed?
In a Servlet? Inside the Jetty implementation?

**Comment by dikkedimi** [comment]
I have this issue when using the RRD4J graphing feature in openHAB. I just did a reinstall and it was running okay until I moved my old graphis into /var/lib/openhab/persistence/rrd4j

now it is crashing every couple of hours or days, rendering openHAB unusable.

See log from openhab's console
```
2019-10-11 03:50:14.138 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Unexpected thread death: [FAILED toString()] in [FAILED toString()]
2019-10-11 03:50:11.296 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@130d4ee in [FAILED toString()]
2019-10-11 03:50:14.142 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@fc9892 in [FAILED toString()]
2019-10-11 03:50:14.141 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@1e065a6 in [FAILED toString()]
2019-10-11 03:50:14.143 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@e7633a in [FAILED toString()]
2019-10-11 03:50:14.145 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@10e9540 in [FAILED toString()]
```

**Comment by sbordet** [comment]
`java.lang.OutOfMemoryError: Java heap space` means you have a too small heap.

Jetty does not "spawn unlimited amounts of threads" - it constrain them to the max number configured in the Jetty thread pools.

**Comment by dikkedimi** [comment]
while i do appreciate your feedback, it in no way adds to the solution to my issue. As I have previously run this install for a long period of time without any problems, and without modification to the number of threads allowed by jetty. I would appreciate help in determining the true cause of this symptom. Me saying "It seems to be spawning an unlimited amount of threads" is what I can deduce from the logs, as I am in no way a jetty,java, or openhab developer.

So please, what could cause this shortage of heap space? it's been happening since august/september if I remember correctly.

**Comment by joakime** [comment]
@dikkedimi to know where your memory is going, I'd suggest you start digging into java heap dumps and the various tooling around investigating it.
Things like `jhat` (in the JDK) and [Eclipse Memory Analysis Tool](https://www.eclipse.org/mat/)

That is the only way to know where your memory is going.

**Comment by sbordet** [comment]
> As I have previously run this install for a long period of time without any problems, and without modification to the number of threads allowed by jetty

But you did not say that in your first comment.
You have not even said what Jetty version you were using before, and what you are using now, or even if there was a version change.

So please: open a new issue and don't hijack this one that is closed.
In the new issue detail exactly your configuration, versions, etc. 
Detail what is the problem, and what you expect instead with as much details as possible.

**Comment by dikkedimi** [comment]
> > As I have previously run this install for a long period of time without any problems, and without modification to the number of threads allowed by jetty
> 
> But you did not say that in your first comment.
> You have not even said what Jetty version you were using before, and what you are using now, or even if there was a version change.
> 
> So please: open a new issue and don't hijack this one that is closed.
> In the new issue detail exactly your configuration, versions, etc.
> Detail what is the problem, and what you expect instead with as much details as possible.

I am sorry, but I'm not a java buff. I'm a simple dumb end-user that does not know how to diagnose all those things. I just follow where google queries take me and add to the discussion if I think my issue is related.

Turns out Jetty did not like me casting a string to a number type variable, or something like that. Issue is now resolved.

**Comment by dikkedimi** [comment]
> @dikkedimi to know where your memory is going, I'd suggest you start digging into java heap dumps and the various tooling around investigating it.
> Things like `jhat` (in the JDK) and [Eclipse Memory Analysis Tool](https://www.eclipse.org/mat/)
> 
> That is the only way to know where your memory is going.

Thanks, this is very helpful information.
