### ISSUE TITLE
ClosedChannelException / earlyEOF

### ISSUE THREAD

**Issue by aton-elvisb** [eclipse/jetty.project#2699]
Hi,

I am using Jetty  9.4.11.v20180605. In log files there are tons of exception stacktraces, identical to the below one. Maybe it is a symptom of server wrong configuration? Or a client bug?

Thank you in advance.

Elvis

DEBUG | 2018-07-05 14:46:09.319 | ..clipse.jetty.io.WriteFlusher | ignored: WriteFlusher@5c8892a9{IDLE}->null
java.nio.channels.ClosedChannelException
        at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:532)
        at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353)
        at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:216)
        at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225)
        at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
        at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175)
        at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:224)
        at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:234)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1557)
        at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:360)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:745)

**Comment by joakime** [comment]
https://github.com/eclipse/jetty.project/blob/c45ca9e38bf7f8beaba1dd45e361fae6d8e2962a/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java#L468-L471

That's the log event location (the `ignored` is the key word there).

Looks like your connection was closed either due to connection failure, or connection idle timeout.
There is likely another error/exception earlier on that connection indicating the cause.

Are you using Servlet 3.1 Async I/O perhaps? (if so, make sure you have [`WriteListener.onError(Throwable)`](https://docs.oracle.com/javaee/7/api/javax/servlet/WriteListener.html#onError-java.lang.Throwable-) implemented and at least logging your errors.)

**Comment by aton-elvisb** [comment]
In our log this is the first exception that appears: non previous errors detected. We are using traditional Servlet, not Async I/O.

**Comment by sbordet** [comment]
This exception is logged at DEBUG level and should not be regarded as relevant for applications.

Are you running your application with DEBUG logs enabled?

**Comment by aton-elvisb** [comment]
Yes, the log level is DEBUG. Ok, I will consider this exception not relevant for the "server" application. Maybe it is a clue to a client bug?

**Comment by sbordet** [comment]
No, it's not a clue for a client bug. Clients close connections at any time all the times.
Unless you explicitly control the client, there is typically nothing to worry about.

**Comment by aton-elvisb** [comment]
That's clear. I close this issue since it is all ok. Thank you very VERY much!
