### ISSUE TITLE
Using resource war file with jar file results in FileNotFoundException during scanForTlds

### ISSUE THREAD

**Issue by mpashka** [eclipse/jetty.project#2710]
Start jetty instance and add war file with some WEB-INF/lib/lib.jar inside as a resource:
```
WebAppContext webappcontext = new WebAppContext();
webappcontext.setBaseResource(new ResourceCollection(new String[]{"jar:file:///my_payj/war_with_lib.war!/"}));
HandlerCollection handlers = new HandlerCollection();
handlers.addHandler(webappcontext);
handlers.addHandler(new DefaultHandler());
Server server = new Server();
server.setHandler(handlers);
server.start();
```

That results in the following exception:
```
55:41,991 WARN  [     JUNIT] pse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@596afb2f{/,[jar:file:///my_path/war_with_lib.war!/],UNAVAILABLE}
java.io.FileNotFoundException: JAR entry WEB-INF/lib/_my_lib_.jar!/ not found in /my_path/war_with_lib.war
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:142) ~[?:1.8.0_151]
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89) ~[?:1.8.0_151]
	at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:438) ~[jetty-webapp-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:355) ~[jetty-webapp-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:173) ~[jetty-webapp-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:107) ~[jetty-webapp-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506) ~[jetty-webapp-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544) ~[jetty-webapp-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Server.start(Server.java:449) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Server.doStart(Server.java:416) ~[jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
```

This is simplified example and that was tested with jetty 9.4.7. I can create real snippet and check it with latest jetty if required though.

**Comment by joakime** [comment]
Why are you using a ResourceCollection for a single reference?

Just a note, we do support this concept, we even have an example project for this ...

https://github.com/jetty-project/embedded-jetty-live-war

**Comment by mpashka** [comment]
In our code we use set of resources that's why we use ResourceCollection.
So we have web overlay module in our project which contains our common JSP pages and other web resources.
We have modules which also have JSP pages and web resources. If we use maven to build war then everything is fine - maven does everything and we don't have to worry. But in order to run functional tests we start jetty, and at that point we don't have resulting war - so we have to combine module web resources and overlay web resources. If overlay war doesn't contain jars it works. Including jars into overlay war breaks jetty.

**Comment by janbartel** [comment]
I will close this issue for now, if needed it can be reopened.
