### ISSUE TITLE
IDleTimeoutException but still response is sent

### ISSUE THREAD

**Issue by noviceamateur** [eclipse/jetty.project#2734]
Jetty version -  9.4.8.v20171121

I am making a request to jetty server and it takes a long time before it sends a response. That is okay for us.

I made the idle timeout as 9 seconds for jetty.

Jetty is continuously giving these exceptions ->
[s3proxy] DEBUG 07-19 11:33:55.362 Scheduler-1321115948 org.eclipse.jetty.io.IdleTimeout:156 |:: ] SocketChannelEndPoint@1bccc548{/127.0.0.1:63602<->/127.0.0.1:8090,OPEN,fill=-,flush=-,to=9001/9000}{io=0/0,kio=0,kro=1}->HttpConnection@2b389aa6[p=HttpParser{s=END,0 of 0},g=HttpGenerator@562a5b2a{s=START}]=>HttpChannelOverHttp@2b312222{r=1,c=false,a=ASYNC_WAIT,uri=//127.0.0.1:8090/holani/testfilec2e0d109-0dc8-4b72-aaa0-b3b7c7bf57e9} idle timeout check, elapsed: 9001 ms, remaining: -1 ms
[s3proxy] DEBUG 07-19 11:33:55.362 Scheduler-1321115948 org.eclipse.jetty.io.IdleTimeout:163 |:: ] SocketChannelEndPoint@1bccc548{/127.0.0.1:63602<->/127.0.0.1:8090,OPEN,fill=-,flush=-,to=9001/9000}{io=0/0,kio=0,kro=1}->HttpConnection@2b389aa6[p=HttpParser{s=END,0 of 0},g=HttpGenerator@562a5b2a{s=START}]=>HttpChannelOverHttp@2b312222{r=1,c=false,a=ASYNC_WAIT,uri=//127.0.0.1:8090/holani/testfilec2e0d109-0dc8-4b72-aaa0-b3b7c7bf57e9} idle timeout expired
[s3proxy] DEBUG 07-19 11:33:55.362 Scheduler-1321115948 org.eclipse.jetty.io.FillInterest:130 |:: ] onFail FillInterest@6b7ab09f{null}
java.util.concurrent.TimeoutException: Idle timeout expired: 9001/9000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166) [s3-1.5.1.jar:1.5.1]
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50) [s3-1.5.1.jar:1.5.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

But once my server has the response ready, it sends it correctly and my client also gets the correct response.

How is this working ?

If the connection has been timed out, it should not be able to send the response back right ?

**Comment by noviceamateur** [comment]
So configuring the idle timeout does not actually change anything ?

**Comment by sbordet** [comment]
Configuring the idle timeout change the *idle* timeout.
You are not idle, you are processing a request.
