### ISSUE TITLE
DefaultServlet async-supported is ignored for ranged requests

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#275]
migrated from Bugzilla [#485226](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485226)
status NEW severity _normal_ in component _servlet-3.1_ for _9.3.x_
Reported in version _9.2.14_ on platform _PC_
Assigned to: Jan Bartel

On 2016-01-05 12:10:57 -0500, Rich DiCroce wrote:

> DefaultServlet always uses blocking I/O for ranged requests, even if async is enabled. This can lead to thread starvation in environments with small thread pools. See the stack trace below.
> 
> I have marked this issue as affecting 9.2.14 because that's what we're currently using, but after looking at the code in 9.3.x and master branches, both of those also appear to be affected (although master has had some refactoring that moved the problematic code from DefaultServlet to ResourceService).
> 
> 06:57:40,965 WARN  [org.eclipse.jetty.server.HttpChannel](qtp164974746-7598) Could not send response error 500: java.io.IOException: org.eclipse.jetty.util.SharedBlockingCallback$BlockerTimeoutException
> 06:57:40,965 WARN  [org.eclipse.jetty.util.thread.QueuedThreadPool](qtp164974746-7598) java.lang.IllegalStateException: org.eclipse.jetty.util.SharedBlockingCallback$BlockerTimeoutException
>   at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.failed(SharedBlockingCallback.java:184) ~[jetty-util-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:103) ~[jetty-io-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) ~[jetty-util-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
> Caused by: org.eclipse.jetty.util.SharedBlockingCallback$BlockerTimeoutException
>   at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:216) ~[jetty-util-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:141) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:378) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.util.IO.copy(IO.java:152) ~[jetty-util-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.util.resource.Resource.writeTo(Resource.java:634) ~[jetty-util-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.servlet.DefaultServlet.sendData(DefaultServlet.java:992) ~[jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:534) ~[jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar:3.1.0]
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
>   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812) ~[jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) ~[jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:224) ~[websocket-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) ~[jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) ~[jetty-security-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) ~[jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.Server.handle(Server.java:499) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
>   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) ~[jetty-io-9.2.14.v20151106.jar:9.2.14.v20151106]
>   ... 3 more

**Comment by joakime** [comment]
This is no longer reproducible in Jetty 9.4.2

**Comment by knabbers** [comment]
Looking at the code for ResourceService, it still looks like ranged requests are not handled asynchronously.

https://github.com/eclipse/jetty.project/blame/jetty-11.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java

(see writeContent and usages)

**Comment by gregw** [comment]
Currently we do write range parts using the blocking IO API.

I have reopened this as a feature request rather than as a bug.  @knabbers can you give a bit more detail about your use-case to motivate if we need to write an async multipart generator?

**Comment by gregw** [comment]
Note that we also don't use async if the response is wrapped.  I think we could still fall back to the async IO APIs in that situation, even if that is not as good as directly writing a memory mapped content buffer

**Comment by knabbers** [comment]
We considered using ranged requests to allow clients to pause/resume large downloads (but perhaps Jetty isn’t the best choice for that?). Another way could be setting a big timeout and expecting the client to go slow - would that be more canonical?

**Comment by knabbers** [comment]
Note that the clients in our case are never saving to disk - they are processing the download as a stream (which in general might be slower then the network).

**Comment by gregw** [comment]
@knabbers OK that is a good use case. Range requests are often used to access large content and often in large chunks that can block.   So it would be good to be able to serve that asynchronously.

I don't see why Jetty shouldn't be a good choice for pause/resume large downloads, so we will look at this feature.... but no promises exactly when it might be implemented.
