### ISSUE TITLE
Missing alpn-1.8.0_181.mod  for openjdk-1.8.0_181

### ISSUE THREAD

**Issue by YangChihLin** [eclipse/jetty.project#2774]
I face the issue when executing `java -jar ./start.jar --add-to-startd=https,http2`

```
WARN  : --add-to-startd is deprecated! Instead use: --create-startd --add-to-start=https,http2
java.lang.IllegalStateException: Cannot read file: modules/alpn-impl/alpn-1.8.0_181.mod
	at org.eclipse.jetty.start.Modules.registerModule(Modules.java:202)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:355)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:360)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:286)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:129)
	at org.eclipse.jetty.start.Main.start(Main.java:435)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
```
I'm using `jetty-distribution-9.4.10.v20180503`

Any suggestion will be greatly appreciated, thanks.
Eric

**Comment by draeath** [comment]
@YangChihLin if you are unable to use a non-release version, do check out that issue for a workaround you can borrow from.

**Comment by YangChihLin** [comment]
Yeah, @draeath, I use the exactly same way as you mentioned that copy `alpn-1.8.0_172.mod` to `alpn-1.8.0_181.mod`, and it works, thank you!

@sbordet  I see your new commit [eceaff7](https://github.com/eclipse/jetty.project/commit/eceaff7bed3a596a05bf5e9dfaf2e61054fc5366).

Thank you guys for following up the issue.
