### ISSUE TITLE
org.eclipse.jetty.client.HttpCookieTest:SetCookieWithLongerPath CI test failure

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2805]
(https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-2804/1/test
```txt
Error
java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException
Stacktrace
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException
at org.eclipse.jetty.client.HttpCookieTest.send(HttpCookieTest.java:669)
at org.eclipse.jetty.client.HttpCookieTest.lambda$test_SetCookieWithLongerPath$2(HttpCookieTest.java:325)
at org.eclipse.jetty.client.HttpCookieTest.test_SetCookieWithLongerPath(HttpCookieTest.java:323)
Caused by: java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException
at org.eclipse.jetty.client.HttpCookieTest.send(HttpCookieTest.java:661)
at org.eclipse.jetty.client.HttpCookieTest.lambda$test_SetCookieWithLongerPath$2(HttpCookieTest.java:325)
at org.eclipse.jetty.client.HttpCookieTest.test_SetCookieWithLongerPath(HttpCookieTest.java:323)
Caused by: java.nio.channels.AsynchronousCloseException
Standard Error
Running org.eclipse.jetty.client.HttpCookieTest.test_SetCookieWithLongerPath[ssl=SslContextFactory@1d01dfa5[provider=null,keyStore=null,trustStore=null]]()
2018-08-15 03:04:02.993:INFO:oejs.Server:main: jetty-9.4.12-SNAPSHOT; built: 2018-08-15T02:55:48.528Z; git: f42505e25920cdd505ebd2d9f5f4c68e5ffc7c4e; jvm 11-ea+18
2018-08-15 03:04:03.027:INFO:oejus.SslContextFactory:main: x509=X509@5226e402(mykey,h=[],w=[]) for SslContextFactory@1d01dfa5[provider=null,keyStore=file:///home/jenkins/workspace/jetty.project_PR-2804-GH57V2DVDEO7B6JTUVK3IGQ7M34QMOC656BEYC6CGDGS76RETTJQ/jetty-client/src/test/resources/keystore.jks,trustStore=null]
2018-08-15 03:04:03.028:INFO:oejs.AbstractConnector:main: Started ServerConnector@1440c311{SSL,[ssl, http/1.1]}{0.0.0.0:43785}
2018-08-15 03:04:03.028:INFO:oejs.Server:main: Started @79479ms
2018-08-15 03:04:03.123:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@1440c311{SSL,[ssl, http/1.1]}{0.0.0.0:0}

```

**Comment by joakime** [comment]
Closing as `org.eclipse.jetty.client.HttpCookieTest.testSetCookieWithLongerPath` has been stable for the past year.
