### ISSUE TITLE
SslContextFactory should validate certificate viability on start

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#2854]
If you use a certificate that has say `DSA` (as a subject public key), or perhaps `SHA1withDSA` (as a signature algorithm) then its possible to have a server where people cannot connect to you.
This manifests in different ways.

Perhaps the cipher suite is artificially limited due to your Certificate.
Perhaps the TLS level prevents proper usage of your Certificate (such as the above examples and TLS/1.3)

This is primarily a Server setup concern, not so much a client concern.

This just proposes that we iterate the certificates on startup, perhaps if the existing `SslContextFactory.setValidateCerts(true)` is set to true.
The validation just checks for known "insufficient security" concerns and warns with clear logging messages.
It shouldn't fail startup, as its possible to have a security setup that is intentionally insecure, or you have a keystore with many certificates, of which only some are used for ServerConnector, and others are invalid.

The goal is to help with troubleshooting.

Note: the error isn't always that obvious on the server side (no errors / warnings are produced on the server side when a client attempts to connect).
Sometimes (but not always) the only way to detect a bad setup is at the client side.
Example of this, when attempting to connect to server with a certificate that is bad.

## Java 9.0.4 Client side Error
```
Exception in thread "main" java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:684)
	at tls.HttpClientExample.main(HttpClientExample.java:30)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at java.base/sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1596)
	at java.base/sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:497)
	at java.base/sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1282)
	at java.base/sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1256)
	at java.base/javax.net.ssl.SSLEngine.wrap(SSLEngine.java:511)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:853)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:349)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:651)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1830)
	at java.base/sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1735)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:347)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:339)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1968)
	at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1777)
	at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:264)
	at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1092)
	at java.base/sun.security.ssl.Handshaker$1.run(Handshaker.java:1031)
	at java.base/sun.security.ssl.Handshaker$1.run(Handshaker.java:1028)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1534)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:512)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:421)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:306)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:160)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	... 3 more
Caused by: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1516)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1482)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1396)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1952)
	... 16 more
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: MD5withRSA
	at java.base/sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:278)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1512)
	... 19 more
```

**Comment by joakime** [comment]
@gregw now that we have the features introduced in issue #3049, would it be wise to attempt to validate the certificates in the same "config issues" section of SslContextFactory?

**Comment by gregw** [comment]
Yes indeed!   As the check is just producing warnings, I think it would be a great idea to warn for non-valid certificates!!!

**Comment by joakime** [comment]
Removing Stale label to give myself another year to implement this.
