### ISSUE TITLE
100% CPU at ReservedThreadExecutor$ReservedThread.reservedWait after OOM

### ISSUE THREAD

**Issue by fluidsonic** [eclipse/jetty.project#2873]
## Situation
I've had multiple OOM errors (possibly caused by a memory leak problem with Ktor coroutines). All the OOM errors led to Jetty at some point getting stuck in one thread with 100% CPU usage.

## Issue
OOM errors shouldn't cause Jetty to get stuck :)

## Info
This is the problematic thread:

```
"qtp239465106-648" #648 prio=5 os_prio=0 tid=0x00007fdf280b8800 nid=0xc198 runnable [0x00007fdef5c98000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Thread.yield(Native Method)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.transferAfterCancelledWait(AbstractQueuedSynchronizer.java:1709)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2159)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.reservedWait(ReservedThreadExecutor.java:292)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:357)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
```

More information about the issue which in turn triggered this issue can be found [in the respective Kotlin issue](https://youtrack.jetbrains.com/issue/KT-26507).

## Versions

JDK openjdk-8-jre-headless 151 on Ubuntu
Ktor 0.9.3
Jetty 9.4.11.v20180605
Jetty ALPN 1.1.3.v20160715

**Comment by sbordet** [comment]
@gregw I'm against having `System.exit()` in Jetty code, no matter the reason.

**Comment by joakime** [comment]
Adding `OutOfMemoryError` handling options link for others that come into this issue - https://stackoverflow.com/a/12096648/775715
