### ISSUE TITLE
Jetty 9.4.12 embedded is throwing an exception with "No config path set" when server starts

### ISSUE THREAD

**Issue by joemokos** [eclipse/jetty.project#2890]
I just upgraded from 9.4.11 to 9.4.12 and now when I start the embedded webserver I get a message "Exception ocurred in run method: No config path set".  The exception occurs in jetty/security/PropertyUserStore method loadUsers.

It appears this is caused by a change made in commit 0fb90223059.  loadUsers used exit if _configPath was null.  Now it throws an exception.  Are we now required to supply a config file.  I noticed that the setConfig method allows a null config rather than throwing an exception.

Here's the stack trace:

start webserver failed with an exception Exception in thread "Thread-4" java.lang.IllegalStateException: No config path set
        at org.eclipse.jetty.security.PropertyUserStore.loadUsers(PropertyUserStore.java:246)
        at org.eclipse.jetty.security.PropertyUserStore.doStart(PropertyUserStore.java:329)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.security.HashLoginService.doStart(HashLoginService.java:192)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:416)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:383)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.altaworks.dsa.http.AwHttpServer.startServer(AwHttpServer.java:788)
        at com.altaworks.dsa.http.AwHttpServer.startWebServer(AwHttpServer.java:888)

**Comment by janbartel** [comment]
The question has been answered. If there is a further issue, the OP is welcome to reopen this issue.

**Comment by JuDev3** [comment]
How can we remove the usage of PropertyUserStore entirely ?

**Comment by joakime** [comment]
This is question on Jetty version 9.x.
That version is now at End of Community Support.

See:  
* #7958

As for the general question that applies to Jetty 10+, `PropertyUserStore` is an implementation of `UserStore`, which is something that the `HashLoginService` needs to operate. (You would only see this warning/error if you are using the `HashLoginService` _and_ haven't configured the `PropertyUserStore` it uses by default)
If you don't want `PropertyUserStore`, but want `HashLoginService`, then you have to provide your own implementation of `UserStore` to the `HashLoginService` you are using.
