### ISSUE TITLE
Performance regression in WriteListener#onWritePossible() implementation after upgrade Jetty from 9.3 to 9.4

### ISSUE THREAD

**Issue by davido** [eclipse/jetty.project#2911]
After upgrading Jetty from 9.3.18.v20170406 to 9.4.9.v20180320 and later (e.g.: 9.4.12.v20180830) we are seeing severe performance degradation after git LFS clone operation: CPU jumped to 100% consumption. Gerrit server must be rebooted to recover. We reverted the upgrade and investigating the root cause.

From the quick debug session, it seems that the problem is endless loop in the `WriteListener#onWritePossible()` implementation in JGit code:

```java
/**
	 * {@inheritDoc}
	 *
	 * Write file content
	 */
	@Override
	public void onWritePossible() throws IOException {
		while (out.isReady()) {
			if (in.read(buffer) != -1) {
				buffer.flip();
				outChannel.write(buffer);
				buffer.compact();
			} else {
				in.close();
				buffer.flip();
				while (out.isReady()) {
					if (buffer.hasRemaining()) {
						outChannel.write(buffer);
					} else {
						context.complete();
					}
				}
			}
		}
	}
```

Specifically this loop is never ending:

```java
				while (out.isReady()) {
					if (buffer.hasRemaining()) {
						outChannel.write(buffer);
					} else {
						context.complete();
					}
				}
```

`buffer.hasRemaining()` is returning false and context.complete() is called, that seems to be a no-op in 9.4.x line. It seems that the implementations of `HttpChannelState#complete()` changed between 9.3.x and 9.4.x lines:

- 9.3.x branch: http://paste.openstack.org/show/730139
- 9.4.x branch: http://paste.openstack.org/show/730140

Can it be that the code needs to be adapted to be compatible with Jetty's 9.4.x line? Note that all is fine with the code with Jetty 9.3.18.v20170406 release.

**Comment by davido** [comment]
It seem that diff in JGit code fixed the problem:

```diff
diff --git a/org.eclipse.jgit.lfs.server/src/org/eclipse/jgit/lfs/server/fs/ObjectDownloadListener.java b/org.eclipse.jgit.lfs.server/src/org/eclipse/jgit/lfs/server/fs/ObjectDownloadListener.java
index ec1d3cd5d..ba237bfe1 100644
--- a/org.eclipse.jgit.lfs.server/src/org/eclipse/jgit/lfs/server/fs/ObjectDownloadListener.java
+++ b/org.eclipse.jgit.lfs.server/src/org/eclipse/jgit/lfs/server/fs/ObjectDownloadListener.java
@@ -129,6 +129,7 @@ public void onWritePossible() throws IOException {
 						outChannel.write(buffer);
 					} else {
 						context.complete();
+						return;
 					}
 				}
 			}
```

I also see that return statement is used in [this Jetty example](https://webtide.com/servlet-3-1-async-io-and-jetty/).

**Comment by joakime** [comment]
This seems strange to me.

What happens in this scenario ...

1. onWritePossible is called.
2. out.isReady() is true
3. in.read(buffer) is EOF (-1)

You wind up with a ServletOutputStream call order of ...

1. out.isReady()
2. out.isReady()
3. out.write(buffer)

That's a violation of the ServletOutputStream contract.
For every out.isReady() == true you must either write or close that ServletOutputStream.

I also question if the second `while(out.isReady())` loop is even needed.

If you are in the else block for `in.read(buffer)` there's no buffer, its empty.
You will always `context.complete()`

Perhaps your code should be ...

``` java
    private boolean inEof = false;

    @Override
    public void onWritePossible() throws IOException
    {
        while (out.isReady())
        {
            if (buffer.hasRemaining())
            {
                if (in.read(buffer) != -1)
                {
                    inEof = true;
                    in.close();
                }
                buffer.flip();
                outChannel.write(buffer);
                buffer.compact();
            }
            else if(inEof) // no buffer remaining, and input is EOF
            {
                out.close(); // you have the out.isReady() == true state at this point
                context.complete();
            }
        }
    }
```

**Comment by davido** [comment]
Thanks for the suggestion, I flipped the logic of the `if (in.read(buffer) != -1)` to be:

```
if (in.read(buffer) == -1)
                {
                    inEof = true;
                    in.close();
                }
```

With that code the git clone with LFS objects works as expected. However, on Jetty 9.4.12 I'm seeing this stack trace:

```
[2018-09-16 00:37:50,146] [HTTP-75] WARN  org.eclipse.jetty.server.HttpChannel : /plugins/lfs/content/default/bdef5499ea21baa69e707391b463105b32c4a2fbf1ab045da53f4023c1a033be
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.eclipse.jgit.lfs.server.fs.FileLfsServlet.sendError(FileLfsServlet.java:181)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onError(ObjectDownloadListener.java:151)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1048)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
[2018-09-16 00:37:50,282] [HTTP-102] WARN  org.eclipse.jetty.server.HttpChannel : /plugins/lfs/content/default/34488cd55f95668cfad45874d9d58a220ea8233beede60ade1b036ebc661c1d0
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.eclipse.jgit.lfs.server.fs.FileLfsServlet.sendError(FileLfsServlet.java:181)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onError(ObjectDownloadListener.java:151)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1048)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
[2018-09-16 00:37:50,322] [HTTP-74] WARN  org.eclipse.jetty.server.HttpChannel : /plugins/lfs/content/default/7f6748b48a7ea6bdf00b0e1967909ce2181ebe6f377638aa454a7d09a0e3ea7b
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.eclipse.jgit.lfs.server.fs.FileLfsServlet.sendError(FileLfsServlet.java:181)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onError(ObjectDownloadListener.java:151)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1048)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

The code `FileLfsServlet.sendError` is here:

```
/**
	 * {@inheritDoc}
	 *
	 * Handle errors
	 */
	@Override
	public void onError(Throwable e) {
		try {
			FileLfsServlet.sendError(response,
					HttpStatus.SC_INTERNAL_SERVER_ERROR, e.getMessage());
			context.complete();
			in.close();
		} catch (IOException ex) {
			LOG.log(Level.SEVERE, ex.getMessage(), ex);
		}
	}
```

And the code of FileLfsServlet.sendError() is here:

```
/**
	 * Send an error response.
	 *
	 * @param rsp
	 *            the servlet response
	 * @param status
	 *            HTTP status code
	 * @param message
	 *            error message
	 * @throws java.io.IOException
	 *             on failure to send the response
	 * @since 4.6
	 */
	protected static void sendError(HttpServletResponse rsp, int status, String message)
			throws IOException {
		rsp.setStatus(status);
		try (PrintWriter writer = rsp.getWriter()) {
			LfsGson.toJson(message, writer);
			writer.flush();
		}
		rsp.flushBuffer();
	}
```

**Comment by davido** [comment]
I added more diagnostic output and see the root cause: we are reading already closed channel:

```
[2018-09-16 06:08:56,131] [main] INFO  com.google.gerrit.pgm.Daemon : Gerrit Code Review (dev) ready
java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:147)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onWritePossible(ObjectDownloadListener.java:126)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1079)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
[2018-09-16 06:09:53,796] [HTTP-77] WARN  org.eclipse.jetty.server.HttpChannel : /plugins/lfs/content/default/bdef5499ea21baa69e707391b463105b32c4a2fbf1ab045da53f4023c1a033be
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.eclipse.jgit.lfs.server.fs.FileLfsServlet.sendError(FileLfsServlet.java:181)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onError(ObjectDownloadListener.java:152)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1048)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:147)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onWritePossible(ObjectDownloadListener.java:126)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1079)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
[2018-09-16 06:09:54,037] [HTTP-78] WARN  org.eclipse.jetty.server.HttpChannel : /plugins/lfs/content/default/34488cd55f95668cfad45874d9d58a220ea8233beede60ade1b036ebc661c1d0
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.eclipse.jgit.lfs.server.fs.FileLfsServlet.sendError(FileLfsServlet.java:181)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onError(ObjectDownloadListener.java:152)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1048)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:147)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onWritePossible(ObjectDownloadListener.java:126)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1079)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
[2018-09-16 06:09:54,050] [HTTP-77] WARN  org.eclipse.jetty.server.HttpChannel : /plugins/lfs/content/default/7f6748b48a7ea6bdf00b0e1967909ce2181ebe6f377638aa454a7d09a0e3ea7b
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.eclipse.jgit.lfs.server.fs.FileLfsServlet.sendError(FileLfsServlet.java:181)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onError(ObjectDownloadListener.java:152)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1048)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by davido** [comment]
Looking into HttpOutput#isReady() implementation on Jetty 9.4.12 it is:

```java
@Override
    public boolean isReady()
    {
        while (true)
        {
            switch (_state.get())
            {
                case OPEN:
                    return true;

                case ASYNC:
                    if (!_state.compareAndSet(OutputState.ASYNC, OutputState.READY))
                        continue;
                    return true;

                case READY:
                    return true;

                case PENDING:
                    if (!_state.compareAndSet(OutputState.PENDING, OutputState.UNREADY))
                        continue;
                    return false;

                case UNREADY:
                    return false;

                case ERROR:
                    return true;

                case CLOSED:
                    return true;

                default:
                    throw new IllegalStateException();
            }
        }
    }
```

I'm, confused about that part:

```
case CLOSED:
                    return true;
```

Shouldn't this rather be:

```
case CLOSED:
                    return false;
```

so that `out.close()` in the code from previous comment would lead to the exit of the outer `while(out.isReady())` loop? Was it the root cause for performance degradation compared to Jetty 9.3.x line?

I adapted the code again to account for the fact, that calling `out.isReady()` after `out.close()` would still return true:

```java
/**
	 * {@inheritDoc}
	 *
	 * Write file content
	 */
	@Override
	public void onWritePossible() throws IOException {
		while (out.isReady()) {
			if (!in.isOpen()) {
				out.close();
				context.complete();
				// Avoid endless loop as out.isReady() would
				// still return true even though the stream
				// was previously closed, see:
				// https://github.com/eclipse/jetty.project/issues/2911
				return;
			} else {
				if (in.read(buffer) == -1) {
					in.close();
				}
				buffer.flip();
				outChannel.write(buffer);
				buffer.compact();
			}
		}
	}
```

That seems to work without exception trying to read already closed stream and without entering the endless loop on Jetty 9.4.12 release.

**Comment by davido** [comment]
The question is why the original code from [that comment](https://github.com/eclipse/jetty.project/issues/2911#issuecomment-421639391) has not lead to the endless loop. And the answer is because ISE exception was thrown:

```
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.eclipse.jgit.lfs.server.fs.FileLfsServlet.sendError(FileLfsServlet.java:181)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onError(ObjectDownloadListener.java:152)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1048)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

the loop was exited. After my attempt to avoid the reading already closed channel the code exposing again endless loop. Something seems to be changed from 9.3.x to 9.4.x Jetty release lines.

**Comment by msohn** [comment]
> You wind up with a ServletOutputStream call order of ...
> 
> out.isReady()
> out.isReady()
> out.write(buffer)
> That's a violation of the ServletOutputStream contract.
> For every out.isReady() == true you MUST either write or close that ServletOutputStream.

Where is this rule specified ? I couldn't find it neither in the servlet 3.1 spec [1] nor in ServletOutputStream's javadoc [2].

[1] says on page 5-48:

> ■ ServletOutputStream
> ■ boolean isReady(). This method returns true if a write to the
> ServletOutputStream will succeed, otherwise it will return false. If this
> method returns true, a write operation can be performed on the
> ServletOutputStream. If no further data can be written to the
> ServletOutputStream. then this method will return false till the underlying
> data is flushed at which point the container will invoke the onWritePossible
> method of the WriteListener. A subsequent call to this method will return
> true.

[1] https://javaee.github.io/servlet-spec/downloads/servlet-3.1/Final/servlet-3_1-final.pdf
[2] https://docs.oracle.com/javaee/7/api/javax/servlet/ServletOutputStream.html

**Comment by joakime** [comment]
```
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.eclipse.jgit.lfs.server.fs.FileLfsServlet.sendError(FileLfsServlet.java:181)
	at org.eclipse.jgit.lfs.server.fs.ObjectDownloadListener.onError(ObjectDownloadListener.java:152)
```

That says your `HttpServletResponse` output mode is currently STREAM (something has used `HttpServletResponse.getOutputStream()`), but your `sendError()` attempted to use `HttpServletResponse.getWriter()` which is a violation of the Servlet contract, you can be either STREAM or WRITE but not swap between them.  You can can use `HttpServletResponse.reset()` to reset the STREAM vs WRITER mode if you want (but be sure you understand all of the implications of `reset()` see javadoc)

Your `FileLfsServlet.sendError()` should also check for `HttpServletResponse.isCommitted()` before attempting to send an error (you can't do anything useful if the response is committed)

**Comment by joakime** [comment]
Regarding the nuances and gotchas of ServletOutputStream and ServletInputStream.

Please watch these 2 videos

## Scale your Web Applications with Servlet 3.1 Async I/O, Speaker: Simone Bordet

* Part 1 - (47m) - https://www.youtube.com/watch?v=j1VjAHTxCBo
* Part 2 - (18m) - https://www.youtube.com/watch?v=TUPSMRVT6VI

**Comment by msohn** [comment]
thanks, watching these videos helped

I pushed another patch to fix `FileLfsServlet.sendError()`: https://git.eclipse.org/r/#/c/129502/

**Comment by msohn** [comment]
@joakime, @gregw thanks for your help and my education :-)
