### ISSUE TITLE
Unmarshalling authenticated Session object in Infinispan error

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#2919]
Caused by: 
java.lang.ClassNotFoundException: org.eclipse.jetty.security.authentication.SessionAuthentication
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:578)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:131)
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:112)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1025)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1354)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:275)
	at org.jboss.marshalling.river.BlockUnmarshaller.readObject(BlockUnmarshaller.java:149)
	at org.jboss.marshalling.river.BlockUnmarshaller.readObject(BlockUnmarshaller.java:135)
	at org.jboss.marshalling.MarshallerObjectInputStream.readObjectOverride(MarshallerObjectInputStream.java:53)
	at org.jboss.marshalling.river.RiverObjectInputStream.readObjectOverride(RiverObjectInputStream.java:307)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:416)
	at java.base/java.util.concurrent.ConcurrentHashMap.readObject(ConcurrentHashMap.java:1465)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jboss.marshalling.reflect.SerializableClass.callReadObject(SerializableClass.java:321)
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1741)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1390)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:275)
	at org.jboss.marshalling.river.BlockUnmarshaller.readObject(BlockUnmarshaller.java:149)
	at org.jboss.marshalling.river.BlockUnmarshaller.readObject(BlockUnmarshaller.java:135)
	at org.jboss.marshalling.MarshallerObjectInputStream.readObjectOverride(MarshallerObjectInputStream.java:53)
	at org.jboss.marshalling.river.RiverObjectInputStream.readObjectOverride(RiverObjectInputStream.java:307)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:416)
	at org.eclipse.jetty.server.session.SessionData.readObject(SessionData.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jboss.marshalling.reflect.SerializableClass.callReadObject(SerializableClass.java:321)
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1741)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1390)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:275)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:208)
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
	at org.infinispan.commons.marshall.jboss.AbstractJBossMarshaller.objectFromObjectStream(AbstractJBossMarshaller.java:134)
	at org.infinispan.commons.marshall.jboss.AbstractJBossMarshaller.objectFromByteBuffer(AbstractJBossMarshaller.java:112)
	at org.infinispan.commons.marshall.AbstractMarshaller.objectFromByteBuffer(AbstractMarshaller.java:82)
	at org.infinispan.client.hotrod.marshall.MarshallerUtil.bytes2obj(MarshallerUtil.java:36)
	at org.infinispan.client.hotrod.impl.protocol.CodecUtils.readUnmarshallByteArray(CodecUtils.java:38)
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readUnmarshallByteArray(Codec20.java:54)
	at org.infinispan.client.hotrod.impl.operations.GetOperation.executeOperation(GetOperation.java:38)
	at org.infinispan.client.hotrod.impl.operations.RetryOnFailureOperation.execute(RetryOnFailureOperation.java:57)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.get(RemoteCacheImpl.java:369)
	at org.eclipse.jetty.session.infinispan.InfinispanSessionDataStore$1.run(InfinispanSessionDataStore.java:102)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1413)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1451)
	at org.eclipse.jetty.server.session.SessionContext.run(SessionContext.java:96)
	at org.eclipse.jetty.session.infinispan.InfinispanSessionDataStore.load(InfinispanSessionDataStore.java:113)

**Comment by janbartel** [comment]
The o.e.j.s.a.SessionAuthentication is a server class, and as such it cannot normally be seen by the webapp. Jetty's security mechanism puts an instance of this class into the session, and thus it will be serialized when the session is passivated. Re-loading the session is causing the exception.

**Comment by janbartel** [comment]
Fixed for 9.4.13 by PR #2932
