### ISSUE TITLE
Jetty 9 leaks threads and connections and stops responding

### ISSUE THREAD

**Issue by dvdewet** [eclipse/jetty.project#2935]
We use Jetty 9 as embedded web server in a Java 8 VM. On occasion, the following happens:

The thread count of the (Windows) process starts to increase at a steady rate
Some time after this, Jetty stops responding to HTTP (TLS) requests.
After this, threads increase still for a while, then stops increasing at around 300 (around 100 non-jetty threads in the process).
At the same time the responses stops, message sequences like the following are starting to be logged repeatedly exactly every 2 minutes, and never stops:

```
2018-09-22 00:00:47 DEBUG [Scheduler-7519289] org.eclipse.jetty.io.IdleTimeout:156 - SelectChannelEndPoint@be1c72{/192.168.37.61:12421<->444,Open,in,out,-,-,120001/120000,SslConnection@16ad018}{io=0/0,kio=0,kro=1} idle timeout check, elapsed: 120001 ms, remaining: -1 ms

2018-09-22 00:00:47 DEBUG [Scheduler-7519289] org.eclipse.jetty.io.IdleTimeout:163 - SelectChannelEndPoint@be1c72{/192.168.37.61:12421<->444,Open,in,out,-,-,120002/120000,SslConnection@16ad018}{io=0/0,kio=0,kro=1} idle timeout expired

2018-09-22 00:00:47 DEBUG [Scheduler-7519289] org.eclipse.jetty.io.WriteFlusher:473 - ignored: WriteFlusher@2527cb{IDLE} {}

2018-09-22 00:00:47 DEBUG [Scheduler-7519289] org.eclipse.jetty.io.AbstractEndPoint:186 - Ignored idle endpoint SelectChannelEndPoint@be1c72{/192.168.37.61:12421<->444,Open,in,out,-,-,120004/120000,SslConnection@16ad018}{io=0/0,kio=0,kro=1}

...

2018-09-22 00:02:47 DEBUG [Scheduler-7519289] org.eclipse.jetty.io.IdleTimeout:156 - SelectChannelEndPoint@be1c72{/192.168.37.61:12421<->444,Open,in,out,-,-,120002/120000,SslConnection@16ad018}{io=0/0,kio=0,kro=1} idle timeout check, elapsed: 120002 ms, remaining: -2 ms

2018-09-22 00:02:47 DEBUG [Scheduler-7519289] org.eclipse.jetty.io.IdleTimeout:163 - SelectChannelEndPoint@be1c72{/192.168.37.61:12421<->444,Open,in,out,-,-,120002/120000,SslConnection@16ad018}{io=0/0,kio=0,kro=1} idle timeout expired

2018-09-22 00:02:47 DEBUG [Scheduler-7519289] org.eclipse.jetty.io.WriteFlusher:473 - ignored: WriteFlusher@2527cb{IDLE} {}

2018-09-22 00:02:47 DEBUG [Scheduler-7519289] org.eclipse.jetty.io.AbstractEndPoint:186 - Ignored idle endpoint SelectChannelEndPoint@be1c72{/192.168.37.61:12421<->444,Open,in,out,-,-,120003/120000,SslConnection@16ad018}{io=0/0,kio=0,kro=1}
```

Sequence like the above are logged for about 200 unique SelectChannelEndPoint objects (also around 200 unique client IP:port combos).

Versions: 9.3.22 and 9.3.25. These are TLS connections.

We do not change the default thread pool size.

It appears as if the scavenging of idle connections has a bug that on occasion kicks in - not from the start - there are many once-off clearing of idle connections before the problem sequence described above starts.

Please help! Is this a known bug (I could not find anything on the internet)?

What other diagnostic info could help pinpoint the issue?

(I also logged this at stackoverflow ...)

**Comment by sbordet** [comment]
Can you upgrade to 9.4.x?

One of the reasons idle timeouts are ignored is because a thread is waiting in application code. 
Please post a thread dump and a [server dump](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-dump-tool.html).

**Comment by dvdewet** [comment]
Thank you, very much. Our next aim is to gather thread dump and server dumps.

**Comment by dvdewet** [comment]
Eventually succeeded in capturing a Java thread dump, and found that 186 of about 228 threads of which the name starts with "qtp", got 'stuck' in a native method java.lang.Class.getDeclaredConstructors0.   Most, but not all of these threads were making another outbound SSL connection at the time, while others look like they were handling the SSL handshake on an incoming HTTPS request.

Example of most common case:
"qtp14711304-10228" Id=10228 in RUNNABLE
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:403)
        at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
        at sun.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.security.Provider$Service.newInstance(Provider.java:1595)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:183)
        at sun.security.ssl.HandshakeMessage$CertificateMsg.<init>(HandshakeMessage.java:451)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
          - locked <dda626> (sun.security.ssl.SSLSocketImpl)
          - locked <bab4b1> (java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
          - locked <14d4e18> (java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
[part of trace deleted going via own code]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:539)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:259)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)


Internet articles indicate that this COULD be caused by having the debugger enabled, which we do,  as follows: 
-agentlib:jdwp=transport=dt_shmem,server=y,suspend=n,address=Webserver 

As well as this option:  -Djavax.net.debug=ssl,handshake 

Although, we don't have any debugger connecting to the VM.

**Comment by sbordet** [comment]
You either have a problem running with the debugger enabled (why are you doing that?) or with the other remote endpoint that does not answer you and you are using blocking APIs to connect to.

In either case it's not Jetty related.
