### ISSUE TITLE
Jetty web socket client Issue

### ISSUE THREAD

**Issue by vaseemahmed01** [eclipse/jetty.project#2946]
[Websocketclient.txt](https://github.com/eclipse/jetty.project/files/2436948/Websocketclient.txt)

I have implemented jetty JSR356 client implementation only, Web socket Server is implemented by third party they have used tomcat websocket.

We have implemented the client code as per jetty jsr356 , we are able to send handshaking request to the web socket server.
Third party team has confirmed that they are receiving web socket url and and connection is established then they are returning the handshaking response, but in our side we are not able to receive response getting error.

Check attached file has two class file....

```
[2018-10-01 15:59:00,779] [DEBUG] [ClientUpgradeResponse]: Saving remaining header: HeapByteBuffer@49af89d8[p=0,l=0,c=0,r=0]={<<<>>>}
[2018-10-01 15:59:00,779] [INFO] [WebSocketClient]: ######requestUr333----->wss://131.5.15.13/CBWSO/wso/svc?entityDetails=%7B%03d%22%7D&eid=029
[2018-10-01 15:59:00,780] [DEBUG] [UpgradeConnection]: Shutting down output DecryptedEndPoint@398cd970{131.5.15.13/131.5.15.13:443<->/192.168.5.5:43279,OPEN,-|-,382/300000,UpgradeConnection@204238ef}->SocketChannelEndPoint@2a6d2e95{131.5.15.13/131.5.15.13:443<->/192.168.5.5:43279,OPEN,-|-,4/300000,SslConnection@11f54221}{io=0/0,kio=0,kro=1}
[2018-10-01 15:59:00,780] [ERROR] [WebSocketClient]: *******ERROR!!!! setupHandshakeConnection ******
#########ERROR------>Connect failure
[2018-10-01 15:59:00,780] [DEBUG] [SslConnection]: SslConnection@11f54221{NOT_HANDSHAKING,eio=218/-1,di=-1} -> UpgradeConnection@204238ef[DecryptedEndPoint@398cd970{131.5.15.13/131.5.15.13:443<->/192.168.5.5:43279,OSHUTTING,-|-,383/300000,UpgradeConnection@204238ef}->SocketChannelEndPoint@2a6d2e95{131.5.15.13/131.5.15.13:443<->/192.168.5.5:43279,OPEN,-|-,5/300000,SslConnection@11f54221}{io=0/0,kio=0,kro=1}] shutdownOutput: oshut=false, ishut=false
java.io.IOException: Connect failure
        at org.eclipse.jetty.websocket.jsr356.ClientContainer.connect(ClientContainer.java:161)
        at org.eclipse.jetty.websocket.jsr356.ClientContainer.connectToServer(ClientContainer.java:184)
        at com.bilogicsys.hplus.cbwsi.ipi.client.controler.WebSocketClient.setupHandshakeConnection(WebSocketClient.java:105)
        at com.bilogicsys.hplus.cbwsi.ipi.client.controler.WebSocketClient.main(WebSocketClient.java:40)
Caused by: org.eclipse.jetty.websocket.api.UpgradeException: Connection is upgrade, close (expected upgrade)
        at org.eclipse.jetty.websocket.client.io.UpgradeConnection.validateResponse(UpgradeConnection.java:359)
        at org.eclipse.jetty.websocket.client.io.UpgradeConnection.read(UpgradeConnection.java:280)
        at org.eclipse.jetty.websocket.client.io.UpgradeConnection.onFillable(UpgradeConnection.java:196)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:269)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:269)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
```

this error also i m getting - 

```
java.lang.RuntimeException: java.io.IOException: Connect failure
        at com.bilogicsys.hplus.cbwsi.ipi.client.wso.WebSocketClientEndpoint.<init>(WebSocketClientEndpoint.java:63)
        at com.bilogicsys.hplus.cbwsi.ipi.client.controler.WebSocketClient.setupHandshakeConnection(WebSocketClient.java:110)
        at com.bilogicsys.hplus.cbwsi.ipi.client.controler.WebSocketClient.main(WebSocketClient.java:40)
Caused by: java.io.IOException: Connect failure
        at org.eclipse.jetty.websocket.jsr356.ClientContainer.connect(ClientContainer.java:161)
        at org.eclipse.jetty.websocket.jsr356.ClientContainer.connectToServer(ClientContainer.java:184)
        at com.bilogicsys.hplus.cbwsi.ipi.client.wso.WebSocketClientEndpoint.<init>(WebSocketClientEndpoint.java:60)
        ... 2 more
Caused by: org.eclipse.jetty.websocket.api.UpgradeException: Didn't switch protocols, expected status <101>, but got <200>
[2018-10-01 17:14:50,305] [DEBUG] [SslConnection]: SslConnection@643f8072{NEED_UNWRAP,eio=-1/85,di=-1} -> UpgradeConnection@43218bb0[DecryptedEndPoint@e7fa929{131.5.15.13/131.5.15.13:443<->/192.168.5.5:44056,OSHUTTING,-|-,303/300000,UpgradeConnection@43218bb0}->SocketChannelEndPoint@4c7fdc2c{131.5.15.13/131.5.15.13:443<->/192.168.5.5:44056,OPEN,-|-,6/300000,SslConnection@643f8072}{io=0/0,kio=0,kro=1}] wrap Status = CLOSED HandshakeStatus = NEED_UNWRAP bytesConsumed = 0 bytesProduced = 85
        at org.eclipse.jetty.websocket.client.io.UpgradeConnection.validateResponse(UpgradeConnection.java:352)
        at org.eclipse.jetty.websocket.client.io.UpgradeConnection.read(UpgradeConnection.java:280)
        at org.eclipse.jetty.websocket.client.io.UpgradeConnection.onFillable(UpgradeConnection.java:196)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:269)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)[2018-10-01 17:14:50,305] [DEBUG] [ChannelEndPoint]: flushed 85 SocketChannelEndPoint@4c7fdc2c{131.5.15.13/131.5.15.13:443<->/192.168.5.5:44056,OPEN,-|-,6/300000,SslConnection@643f8072}{io=0/0,kio=0,kro=1}

        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:269)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sbordet** [comment]
This is the relevant information in the logs:

```
Caused by: org.eclipse.jetty.websocket.api.UpgradeException: Didn't switch protocols, expected status <101>, but got <200>
```

This is a server problem, they should upgrade to WebSocket and respond with a 101 response.
If they don't, possibly they did not like the upgrade request sent by the client, and they should have the reason why in their server logs.

**Comment by lachlan-roberts** [comment]
Closing, jetty is correctly handling the 200 response for the attempted websocket upgrade.
