### ISSUE TITLE
Socket Closed: CloseReason[1011,Not valid for write: id=node01n2ydgkklxhsk1eec63k9k95lh0 not resident]

### ISSUE THREAD

**Issue by Xearoxde** [eclipse/jetty.project#2969]
Hello there,

I am getting this error here:

```
Created: node01n2ydgkklxhsk1eec63k9k95lh0
java.lang.IllegalStateException: Not valid for write: id=node01n2ydgkklxhsk1eec63k9k95lh0 not resident
Socket Closed: CloseReason[1011,Not valid for write: id=node01n2ydgkklxhsk1eec63k9k95lh0 not resident]
	at org.eclipse.jetty.server.session.Session.checkValidForWrite(Session.java:616)
	at org.eclipse.jetty.server.session.Session.setAttribute(Session.java:756)
	at main.EventSocket.onWebSocketConnect(EventSocket.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
	at org.eclipse.jetty.websocket.jsr356.annotations.OnOpenCallable.call(OnOpenCallable.java:54)
	at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callOpen(JsrEvents.java:170)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onConnect(JsrAnnotatedEventDriver.java:195)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:233)
	at org.eclipse.jetty.websocket.jsr356.endpoints.AbstractJsrEventDriver.openSession(AbstractJsrEventDriver.java:104)
	at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:616)
	at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:544)
	at org.eclipse.jetty.io.AbstractConnection.onOpened(AbstractConnection.java:209)
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:202)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:446)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:440)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:385)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:743)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:510)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

This is line 29: `this.httpSession.setAttribute("websocketSession", sess);`

In my Main Class I have this:

```java
		this.jettyServer = new Server();

		ServerConnector connector = new ServerConnector(jettyServer);

		connector.setPort(config.getJettyPort());

		connector.setIdleTimeout(config.getJettyIdleTimeout() == 0 ? -1 : config.getJettyIdleTimeout());
		this.jettyServer.addConnector(connector);

		ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);

		context.setContextPath(config.getJettyContextPath());

		context.addEventListener(new MySessionListener());

		SessionHandler sessionHandler = context.getSessionHandler();

		SessionCache cache = new NullSessionCache(sessionHandler);

		JDBCSessionDataStore sessionDataStore = new JDBCSessionDataStore();

		DatabaseAdaptor ada = new DatabaseAdaptor();

		ada.setDatasource(ConnectionManager.getMainConnection());

		sessionDataStore.setDatabaseAdaptor(ada);

		cache.setSessionDataStore(sessionDataStore);

		sessionHandler.setSessionCache(cache);
```

So I don't know where the problem is!

I am using Jetty: 9.4.12.v20180830

**Comment by joakime** [comment]
The key lines ...

```
Socket Closed: CloseReason[1011,Not valid for write: id=node01n2ydgkklxhsk1eec63k9k95lh0 not resident]
	at org.eclipse.jetty.server.session.Session.checkValidForWrite(Session.java:616)
	at org.eclipse.jetty.server.session.Session.setAttribute(Session.java:756)
	at main.EventSocket.onWebSocketConnect(EventSocket.java:29)
```

You are attempting to modify an `HttpSession` from within your WebSocket codebase.

This is not possible, once in WebSocket, all of the HTTP features become static and immutable as you are no longer within HTTP. 

Grab the information you need from the `HttpSession` during WebSocket Upgrade Handshake, pass whatever information you need into your `WebSocket` and use it.

**Comment by sbordet** [comment]
@joakime I'm not convinced. Even if one connection is upgraded to WebSocket, the server can still serve HTTP for the same browser and therefore for the same HTTP session, which must available for modifications.

**Comment by joakime** [comment]
All concepts from HTTP are static/immutable once WebSocket is upgraded.
Always has been.
There's no lifecycle during WebSocket for the HTTP components. (no save point for HttpSessions, no update point for updates from other Sessions, etc)

JSR356 specifically points out that it's invalid.
CDI also does the same thing.
Spring has the same rules for WebSocket.
Browser JavaScript WebSocket also has the same rules for the connection that is WebSocket (cannot access/read/modify HTTP details of that connection).

**Comment by sbordet** [comment]
@joakime thanks for explanations, I'm convinced now that it is a user error to try to access the `HttpSession` after the `WebSocket` upgrade because the behavior will be non-deterministic over the long haul.

@Xearoxde do as @joakime said: extract the information during the upgrade and use only the information extracted, not the `HttpSession` object.
