### ISSUE TITLE
Embedded Jetty doesn't shut down gracefully if port is already bound

### ISSUE THREAD

**Issue by pmwmedia** [eclipse/jetty.project#3004]
In my application, I use Jetty as embedded server. If I try to start Jetty and the port is already bound, Jetty will throw an exception as expected. However Jetty does not stop the created threads (named qtp*). This means that an application cannot terminate gracefully.

```java
public class Application {

	public static void main(String[] args) throws Exception {
		new Server(8080).start();
	}

}
```

```
2018-10-19 10:38:20.946:INFO::main: Logging initialized @506ms to org.eclipse.jetty.util.log.StdErrLog
2018-10-19 10:38:21.023:INFO:oejs.Server:main: jetty-9.4.7.v20170914
Exception in thread "main" java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:334)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:302)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:238)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:428)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at Application.main(Application.java:8)
```

```
Thread [qtp174573182-14] (Running)	
Thread [qtp174573182-15] (Running)	
Thread [qtp174573182-16] (Running)	
Thread [qtp174573182-17] (Running)	
Thread [qtp174573182-18] (Running)	
Thread [qtp174573182-19] (Running)	
Thread [qtp174573182-20] (Running)	
Thread [qtp174573182-21] (Running)	
Thread [DestroyJavaVM] (Running)	
```

It is even impossible to destroy Jetty manually:

```java
public class Application {

	public static void main(String[] args) throws Exception {
		Server server = new Server(8080);
		try {
			server.start();
		} catch (Exception ex) {
			server.destroy();
			throw ex;
		}
	}

}
```

```
2018-10-19 10:40:44.610:INFO::main: Logging initialized @490ms to org.eclipse.jetty.util.log.StdErrLog
2018-10-19 10:40:44.678:INFO:oejs.Server:main: jetty-9.4.7.v20170914
Exception in thread "main" java.lang.IllegalStateException: !STOPPED
	at org.eclipse.jetty.server.handler.HandlerWrapper.destroy(HandlerWrapper.java:147)
	at Application.main(Application.java:12)
```

This bug is reproduziere with Jetty 9.4.7.v20170914 and 9.4.12.v20180830.

**Comment by joakime** [comment]
Using `server.stop();` instead of `server.destroy();` seems to work for me.

``` java
public class Application {
	public static void main(String[] args) throws Exception {
		Server server = new Server(8080);
		try {
			server.start();
		} catch (Exception ex) {
			server.stop();
			throw ex;
		}
	}
}
```

**Comment by pmwmedia** [comment]
Thank you! That works for me too :-)
