### ISSUE TITLE
Bogus Content-Length header causes timeouts

### ISSUE THREAD

**Issue by tabtwentyfivesec** [eclipse/jetty.project#3034]
If I set a Content-Length header with a value > than the actual content length then Jetty times out.  This behavior was observed in jetty-distribution-9.4.12.v20180830.

```
2018-10-29 10:31:35.318:DBUG:oejut.QueuedThreadPool:Scheduler-679890578: queue HttpChannelOverHttp@6ba827d3{r=1,c=false,a=IDLE,uri=//localhost:8080/doesnotexist,age=30008}
2018-10-29 10:31:35.319:DBUG:oejut.QueuedThreadPool:qtp1451043227-24: run HttpChannelOverHttp@6ba827d3{r=1,c=false,a=IDLE,uri=//localhost:8080/doesnotexist,age=30009}
2018-10-29 10:31:35.319:DBUG:oejs.HttpChannel:qtp1451043227-24: HttpChannelOverHttp@6ba827d3{r=1,c=false,a=IDLE,uri=//localhost:8080/doesnotexist,age=30009} handle //localhost:8080/doesnotexist 
2018-10-29 10:31:35.319:DBUG:oejs.HttpChannelState:qtp1451043227-24: handling HttpChannelState@7ee6ff0b{s=IDLE a=NOT_ASYNC i=true r=IDLE w=false}
2018-10-29 10:31:35.319:DBUG:oeji.WriteFlusher:Scheduler-679890578: ignored: WriteFlusher@48b73069{IDLE}->null
java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
    at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
    at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Suppressed: 
    |java.lang.Throwable: HttpInput idle timeout
    |   at org.eclipse.jetty.server.HttpInput.onIdleTimeout(HttpInput.java:797)
    |   at org.eclipse.jetty.server.HttpChannelOverHttp.onIdleTimeout(HttpChannelOverHttp.java:407)
    |   at org.eclipse.jetty.server.HttpConnection.onReadTimeout(HttpConnection.java:487)
    |   at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:170)
    |   at org.eclipse.jetty.server.HttpConnection.onFillInterestedFailed(HttpConnection.java:494)
    |   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:311)
    |   at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:138)
    |   at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:406)
    |   at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
    |   at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
    |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    |   at java.lang.Thread.run(Thread.java:748)
2018-10-29 10:31:35.321:DBUG:oejs.HttpChannel:qtp1451043227-24: HttpChannelOverHttp@6ba827d3{r=1,c=false,a=DISPATCHED,uri=//localhost:8080/doesnotexist,age=30011} action DISPATCH
```

**Comment by sbordet** [comment]
That is expected behavior.

You told the server, "hey, I'm sending 10 bytes" but then you only send 6. The server is waiting for the remaining 4 bytes until it times out.
