### ISSUE TITLE
Multiple HTTP/2 HttpInput suppressed failures

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3112]
Noticed during a Performance testing, if there's multiple HttpInput failures, the failures are not communicated properly, and seem to be overly supressed.

**Comment by sbordet** [comment]
```
ava.io.IOException: 1/unexpected_data_frame
	at org.eclipse.jetty.http2.HTTP2Session.onConnectionFailure(HTTP2Session.java:539) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.HTTP2Session.onData(HTTP2Session.java:260) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.HTTP2Connection$ParserListener.onData(HTTP2Connection.java:367) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.parser.BodyParser.notifyData(BodyParser.java:103) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.parser.DataBodyParser.onData(DataBodyParser.java:138) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.parser.DataBodyParser.parse(DataBodyParser.java:103) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:194) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:123) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:252) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:826) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323) ~[http2-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:219) ~[http2-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onSessionFailure(HTTP2ServerConnection.java:258) ~[http2-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:127) ~[http2-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Session.notifyFailure(HTTP2Session.java:1179) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Session.onConnectionFailure(HTTP2Session.java:539) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Session.onData(HTTP2Session.java:260) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Connection$ParserListener.onData(HTTP2Connection.java:367) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.BodyParser.notifyData(BodyParser.java:103) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.DataBodyParser.onData(DataBodyParser.java:138) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.DataBodyParser.parse(DataBodyParser.java:103) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:194) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:123) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:252) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:826) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323) ~[http2-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:219) ~[http2-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onSessionFailure(HTTP2ServerConnection.java:258) ~[http2-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:127) ~[http2-server-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Session.notifyFailure(HTTP2Session.java:1179) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Session.onConnectionFailure(HTTP2Session.java:539) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Session.onData(HTTP2Session.java:260) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Connection$ParserListener.onData(HTTP2Connection.java:367) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.BodyParser.notifyData(BodyParser.java:103) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.DataBodyParser.onData(DataBodyParser.java:138) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.DataBodyParser.parse(DataBodyParser.java:103) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:194) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:123) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:252) ~[http2-common-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
		at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: java.lang.Throwable: HttpInput failure
                ... // and many many others
```

**Comment by sbordet** [comment]
The stack trace is really strange, as `HttpInput.failed(Throwable)` is protected by a lock, and inside it does a state change, so it should never be possible that the same exception is added as suppressed multiple times.
