### ISSUE TITLE
Using proxy server with websocketclient

### ISSUE THREAD

**Issue by rajanigk** [eclipse/jetty.project#3119]
I am able to get my websocket client connect to the websocket server when i connect trough the  private IP adress without using proxy.  Same websocketclient code when tries to  connect to the websocket server using public ip address of the websocket server through proxy server, upgrade to websocket fails with UpgradeException. 

I am not sure whether i am using the right APIs to connect to the websocket server through proxy. I am not able to get any sample code in the internet doing this.

Following is the code snippet used in my project. I have used jetty-version 9.4.13.v20181111
....
....

``` java

        HttpClient httpClient = new HttpClient();

        ProxyConfiguration proxyConfig = httpClient.getProxyConfiguration();
        HttpProxy proxy = new HttpProxy("proxyhost",proxyport);
        proxyConfig.getProxies().add(proxy);

        try {
                httpClient.start();
        } catch (Exception e) {
                e.printStackTrace();
        }
        WebSocketClient client= new WebSocketClient(httpClient);


        client.setConnectTimeout(4000);
        client.setMaxIdleTimeout(4000);
        client.setMaxBinaryMessageBufferSize(1000000);
        try {
                client.start();

        } catch (Exception e) {
                e.printStackTrace();
        }

        try {

            String dest = "ws://"+public_ip_address_of_websocket_server+":80"/toUpper
            MyclientSocketListener socket = new MyclientSocketListener(wmain,noConnections);
            URI echoUri = new URI(dest);

            ClientUpgradeRequest request = new ClientUpgradeRequest();

            String encodedstring = Base64.getEncoder().encodeToString(("somestring").getBytes());
            String headerString = new String(encodedstring.getBytes(), "UTF-8");
            request.setHeader("Authorization","Basic "+headerString);

            Future<Session> fut =client.connect(socket, echoUri, request);
            fut.get(60000, TimeUnit.MILLISECONDS);

        } catch (Throwable t) {
                t.printStackTrace();
        }
```

With the  same code if i remove the httpclient parameter to WebsocketClient constructor and use the private IP address of the websocket server in the URI string i am able to connect to the websocket server when i run the application in the private subnet.

I want to develop a jmeter sampler to load test jetty,So i need to first do the testing outside the private subnet. So i need the websocketclient to connect to the websocket server using public ip address and through the proxy server and port. I used the samplers given in the following links.

1. https://bitbucket.org/pjtr/jmeter-websocket-samplers

Above sampler does not use jetty, i could set the command line parms for jmeter with -H <proxyhost> -P <proxy port> and could connect to my websocket server.

2. https://github.com/maciejzaleski/JMeter-WebSocketSampler
Above sampler uses jetty,  and the proxy setting using commandlin earguments of jmeter does not work, then i looked at the code, the websocketclient is not coded to take the proxy. But even if change the code to take the proxy through htpclient it does not connect and fails with UpgradeException.

I have also written an autobahn client which is able to connect to the websocket server through the proxy. Only with jetty client i am seeing this issue. 

The stack trace of the UpgradeException is:

````
java.util.concurrent.ExecutionException: org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 400 Bad Request
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.javacodegeeks.snippets.enterprise.jettywebsocket.jetty.client1.WebSocketClientMain.main(WebSocketClientMain.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 400 Bad Request
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:524)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:202)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:194)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:470)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:416)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:316)
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:599)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1669)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1517)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:172)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:135)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by joakime** [comment]
Sounds like you need to find a JMeter plugin that honors the JMeter provided proxy settings and forwards them to the WebSocketClient from jetty.

Note you can optionally use ... 


``` java
WebSocketClient wsclient = new WebSocketClient();
ProxyConfiguration proxyConfig = wsclient.getHttpClient().getProxyConfiguration();
HttpProxy proxy = new HttpProxy("proxyhost",proxyport);
proxyConfig.getProxies().add(proxy);
```

as well, in the codebase that you are working with.

The "400 Bad request" is a message from the server you connected to, indicating a bad request was sent.
If you are, for example, sending a proxy request to non-proxy server then that could happen.

**Comment by rajanigk** [comment]
I tried the code snippet you have given, but I see the same error. But with the same proxy and port setting I am able to connect to the  websocket server through other Websocket clients except jetty client

Regards
Rajani

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rajanigk** [comment]
Do you have any jetty sample websocket  server and client using proxy ? If you have can you share that code with me?

**Comment by joakime** [comment]
The code I shared with you works for HTTP based proxies.
If you have a different type of proxy (eg: SOCKS4) then you need to use a different proxy configuration in HttpClient, eg ...

``` java
WebSocketClient wsclient = new WebSocketClient();
ProxyConfiguration proxyConfig = wsclient.getHttpClient().getProxyConfiguration();
Socks4Proxy proxy = new Socks4Proxy("proxyhost",proxyport);
proxyConfig.getProxies().add(proxy);
```

If you are using a a different websocket client that uses the native JVM based proxy support then you should know you cannot use those JVM properties and techniques within the Jetty HttpClient.
Why?  well, the JVM based proxy support impacts 100% of connections JVM wide, which is undesirable (all connections should not go through proxy) and harmful (memory, performance, threading, etc) in too many situations, so we intentionally do not support it.

Right know all we know is `400 Bad Request` as a response, but you haven't identified what machine is returning that response (the proxy? the ultimate destination?)
We don't know if you have authentication requirements for the proxy machine. (this is supported in Jetty HttpClient)
We've even seen proxies that require the client to execute javascript in order to know how to communicate with the proxy. (this is totally unsupported in Jetty HttpClient)

https://www.eclipse.org/jetty/documentation/current/http-client-proxy.html

Once you know what kind of proxy you are dealing with, and what kind of requirements it has, we can help with more details on your setup.

**Comment by joakime** [comment]
This points to a JMeter specific issue.
Closing due to lack of updates.
