### ISSUE TITLE
Server can't accept new connection when many http2 connection close same time

### ISSUE THREAD

**Issue by ligzy** [eclipse/jetty.project#3231]
Hi,
I am make a performance test for a http2 server.
it can accept about 500,000 connection at a 64g ,16cpu server.
now i meet a situation.
if some connection disconnect ,i found it will can't accept new connection.
I use jstack,it show this:

"qtp45822040-493" #493 prio=5 os_prio=0 tid=0x0000000004818800 nid=0x1d1a71 waiting on condition [0x00007fbeb87fe000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00007fc35eab62b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

"qtp45822040-492" #492 prio=5 os_prio=0 tid=0x0000000004752800 nid=0x1d1a70 waiting on condition [0x00007fbeb883f000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00007fc425339068> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

"qtp45822040-491" #491 prio=5 os_prio=0 tid=0x0000000006813000 nid=0x1d1a6f waiting on condition [0x00007fbeb8880000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00007fc3a8580048> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

"qtp45822040-490" #490 prio=5 os_prio=0 tid=0x000000000698d800 nid=0x1d1a6e waiting on condition [0x00007fbeb88c1000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00007fc369dce9e0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

"qtp45822040-489" #489 prio=5 os_prio=0 tid=0x00000000062be800 nid=0x1d1a6d waiting on condition [0x00007fbeb8902000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00007fc4bda20658> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

"qtp45822040-488" #488 prio=5 os_prio=0 tid=0x000000000680e000 nid=0x1d1a6c waiting on condition [0x00007fbeb8943000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00007fcc76da8c00> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.reservedWait(ReservedThreadExecutor.java:292)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:357)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

"qtp45822040-487" #487 prio=5 os_prio=0 tid=0x0000000007221000 nid=0x1d1a6b waiting on condition [0x00007fbeb8984000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00007fc47d1601a0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

"qtp45822040-486" #486 prio=5 os_prio=0 tid=0x0000000005d67800 nid=0x1d1a6a waiting on condition [0x00007fbeb89c5000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00007fc41cf40e08> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)

But , after a while,it can accept up to 500,000 connections again.
May you help me ?
Thanks.

**Comment by ligzy** [comment]
Hi,
I am make a performance test for a http2 server.
it can accept about 500,000 connection at a 64g ,16cpu server.
now i meet a situation.
if some connection disconnect ,i found it will can't accept new connection.
I use jstack,it show this:

"qtp45822040-493" #493 prio=5 os_prio=0 tid=0x0000000004818800 nid=0x1d1a71 waiting on condition [0x00007fbeb87fe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fc35eab62b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
	at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp45822040-492" #492 prio=5 os_prio=0 tid=0x0000000004752800 nid=0x1d1a70 waiting on condition [0x00007fbeb883f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fc425339068> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
	at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp45822040-491" #491 prio=5 os_prio=0 tid=0x0000000006813000 nid=0x1d1a6f waiting on condition [0x00007fbeb8880000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fc3a8580048> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
	at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp45822040-490" #490 prio=5 os_prio=0 tid=0x000000000698d800 nid=0x1d1a6e waiting on condition [0x00007fbeb88c1000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fc369dce9e0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
	at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp45822040-489" #489 prio=5 os_prio=0 tid=0x00000000062be800 nid=0x1d1a6d waiting on condition [0x00007fbeb8902000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fc4bda20658> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
	at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp45822040-488" #488 prio=5 os_prio=0 tid=0x000000000680e000 nid=0x1d1a6c waiting on condition [0x00007fbeb8943000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fcc76da8c00> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.reservedWait(ReservedThreadExecutor.java:292)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:357)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp45822040-487" #487 prio=5 os_prio=0 tid=0x0000000007221000 nid=0x1d1a6b waiting on condition [0x00007fbeb8984000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fc47d1601a0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
	at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp45822040-486" #486 prio=5 os_prio=0 tid=0x0000000005d67800 nid=0x1d1a6a waiting on condition [0x00007fbeb89c5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007fc41cf40e08> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:210)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:297)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:1044)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1431)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1116)
	at org.eclipse.jetty.server.HttpChannelState.asyncError(HttpChannelState.java:381)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2$FailureTask.run(HttpChannelOverHTTP2.java:406)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

May you help me ?
Thanks.

**Comment by ligzy** [comment]
@sbordet I was doing a pressure test, and i am make 500,000 connection to a jvm.
When i kill one client with about 180,000 connections through 3 ips, i got the case above.

**Comment by joakime** [comment]
The only way to reproduce this is to have a load testing client that doesn't read the response (headers and/or body content).
Causing TCP congestion.
That's the sign of a bad load testing client.
