### ISSUE TITLE
HttpClientLoadTest fails on Java 11.0.1

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3239]
```
org.eclipse.jetty.http.client.HttpClientLoadTest
[ERROR] testConcurrent{Transport}[2]  Time elapsed: 0.443 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: [Result failed Result[HttpRequest[POST /177 HTTP/1.1]@14308123 > HttpResponse[null 0 null]@413ddb2d] javax.net.ssl.SSLException: Received fatal alert: internal_error] ==> expected: <true> but was: <false>
	at org.eclipse.jetty.http.client.HttpClientLoadTest.run(HttpClientLoadTest.java:181)
	at org.eclipse.jetty.http.client.HttpClientLoadTest.lambda$testConcurrent$2(HttpClientLoadTest.java:146)
	at org.eclipse.jetty.http.client.HttpClientLoadTest.lambda$testConcurrent$3(HttpClientLoadTest.java:145)
```

Attached surefire-report: 
[TEST-org.eclipse.jetty.http.client.HttpClientLoadTest.xml.gz](https://github.com/eclipse/jetty.project/files/2728054/TEST-org.eclipse.jetty.http.client.HttpClientLoadTest.xml.gz)

**Comment by sbordet** [comment]
This appears to be a Java 11 bug, see #3368.
