### ISSUE TITLE
CyclicException on startup

### ISSUE THREAD

**Issue by GMillerVarian** [eclipse/jetty.project#3243]
After upgrading Java 8 to Java 11 and Jetty 9.2 to 9.4, we are getting the following errors in jetty-distribution when running "java -jar start.jar". In build.gradle we have runtime dependencies on jetty-jaas and jetty-webapp. Based on [Issue 2407](https://github.com/eclipse/jetty.project/issues/2407) I have tried adding compile time dependency jetty-start:shaded but it did not help and I'm not sure if that was the right thing to do.

> org.eclipse.jetty.start.shaded.util.TopologicalSort$CyclicException: cyclic at annotations{enabled,transitive}
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:135)
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.sort(TopologicalSort.java:99)
        at org.eclipse.jetty.start.Modules.getEnabled(Modules.java:274)
        at org.eclipse.jetty.start.Main.processCommandLine(Main.java:328)
        at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: org.eclipse.jetty.start.shaded.util.TopologicalSort$CyclicException: cyclic at plus{enabled}
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:135)
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:131)
        ... 4 more
Caused by: org.eclipse.jetty.start.shaded.util.TopologicalSort$CyclicException: cyclic at jndi{enabled}
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:135)
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:131)
        ... 5 more
Caused by: org.eclipse.jetty.start.shaded.util.TopologicalSort$CyclicException: cyclic at server{enabled}
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:135)
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:131)
        ... 6 more
Caused by: org.eclipse.jetty.start.shaded.util.TopologicalSort$CyclicException: cyclic at logging{enabled}
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:135)
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:131)
        ... 7 more
Caused by: org.eclipse.jetty.start.shaded.util.TopologicalSort$CyclicException: cyclic at jmx{enabled}
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:135)
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:131)
        ... 8 more
Caused by: org.eclipse.jetty.start.shaded.util.TopologicalSort$CyclicException: cyclic at server{enabled}
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:147)
        at org.eclipse.jetty.start.shaded.util.TopologicalSort.visit(TopologicalSort.java:131)
        ... 9 more

**Comment by GMillerVarian** [comment]
I noticed that start.jar in jetty-distribution matches the -shaded version of the jar in jetty-start. If I replace start.jar in jetty-distribution with the normal one from jetty-start then I get the following error instead. I do see jetty-util in the lib folder in jetty-distribution.

> java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ManifestUtils
        at org.eclipse.jetty.start.StartArgs.<clinit>(StartArgs.java:69)
        at org.eclipse.jetty.start.Main.processCommandLine(Main.java:293)
        at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.ManifestUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more

**Comment by gregw** [comment]
@GMillerVarian The shaded version of start.jar contains a shaded copy of the util classes that it needs.  It is the job of start.jar to build a class path of the required libraries in lib, so it doesn't actually use anything in lib.

So the exceptions you are seeing are more likely to do with something in your modules or ini files. Are you using the same mod/ini files from 9.2?    Do you have any custom modules?    Any chance you can attach(or send me) start.ini, start.d/* and modules/*

**Comment by GMillerVarian** [comment]
Yes, the files are the same, and yes there are custom modules. I have sent you the files as requested. Thanks!

**Comment by GMillerVarian** [comment]
One of our custom modules is called "logging". If I rename this module to anything else, Jetty starts up fine.
