### ISSUE TITLE
earlyEOF exception with AsyncProxyServlet

### ISSUE THREAD

**Issue by darrachequesne** [eclipse/jetty.project#3263]
Hi everyone,

We are using the `org.eclipse.jetty.proxy.AsyncProxyServlet` as a gateway, in front of our APIs. Our architecture:

```
gateway -> F5 loadbalancer -> apache httpd -> tomcat
```

Our issue is that some of the requests get an HTTP 502 response from the gateway. It happens for a few random requests (something like 1 out of 100 000 successful requests), is sparse across the day and does not seem related to a given path / resource.

We get the following exceptions in the logs:

```
java.io.EOFException: HttpConnectionOverHTTP@6f5b4e8e(l:/xxx:42186 <-> r:xxx:443,closed=false)=>HttpChannelOverHTTP@46ffdb2c(exchange=HttpExchange@597ec84d req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@12c8e284(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@49611bf1{s=START}],recv=HttpReceiverOverHTTP@717f9f4a(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]<-DecryptedEndPoint@5eec1d88{xxx:443<->/xxx:42186,OPEN,fill=-,flush=-,to=5000/0}->HttpConnectionOverHTTP@6f5b4e8e(l:/xxx:42186 <-> r:xxx:443,closed=false)=>HttpChannelOverHTTP@46ffdb2c(exchange=HttpExchange@597ec84d req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@12c8e284(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@49611bf1{s=START}],recv=HttpReceiverOverHTTP@717f9f4a(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]->SocketChannelEndPoint@be50813{xxx:443<->/xxx:42186,ISHUT,fill=-,flush=-,to=3/0}{io=1/0,kio=1,kro=1}->SslConnection@4a9a340d{NEED_WRAP,eio=-1/-1,di=-1}=>HttpConnectionOverHTTP@6f5b4e8e(l:/xxx:42186 <-> r:xxx:443,closed=false)=>HttpChannelOverHTTP@46ffdb2c(exchange=HttpExchange@597ec84d req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@12c8e284(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@49611bf1{s=START}],recv=HttpReceiverOverHTTP@717f9f4a(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:338)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1557)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:209)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:147)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:748)
```

What is strange is that the requests do not seem to reach the Apache httpd server, as they do not appear in the access logs (and nothing gets printed in the error log).

Our `org.eclipse.jetty.proxy.AbstractProxyServlet` configuration:

```
maxThreads: 600
maxConnections: 512
idleTimeout: 30_000
timeout: 60_000
requestBufferSize: 32_768
responseBufferSize: 262_144
```

We are not sure those errors are related to Jetty itself, would you have any idea? Do you know what could cause those `earlyEOF` exceptions?

Thanks!

Jetty version: `9.4.11.v20180605`

**Comment by joakime** [comment]
Early EOF Exception is common on the modern web.

Some examples of things that trigger it ...

* A user navigates away from a web page that is actively doing something on the network.
* A user on a mobile device has their network switch (mobile tower to mobile tower, mobile to wifi, wifi to mobile, etc)

**Comment by arulrajnet** [comment]
I too facing the same issue in server to server communication

In this the header is not fully written by proxy servlet. 

```
org.eclipse.jetty.client.HttpSender - Generated headers (-1 bytes), chunk (-1 bytes), content (0 bytes) - NEED_HEADER/HttpGenerator@5a9f841f{s=START}
org.eclipse.jetty.client.HttpSender - Generated headers (1077 bytes), chunk (-1 bytes), content (0 bytes) - FLUSH/HttpGenerator@5a9f841f{s=COMPLETING}
org.eclipse.jetty.client.HttpSender - Request shutdown output HttpRequest[GET /api/user/543 HTTP/1.1]@4687213d
org.eclipse.jetty.client.HttpSender - Request failure HttpRequest[GET /api/user/543 HTTP/1.1]@4687213d HttpExchange@715dec48 req=COMPLETED/org.eclipse.jetty.io.EofException@4e932f2e res=PENDING/null@null on HttpChannelOverHTTP@40176676(exchange=HttpExchange@715dec48 req=COMPLETED/org.eclipse.jetty.io.EofException@4e932f2e res=PENDING/null@null)[send=HttpSenderOverHTTP@243ab7f9(req=FAILURE,snd=FAILED,failure=org.eclipse.jetty.io.EofException)[HttpGenerator@5a9f841f{s=END}],recv=HttpReceiverOverHTTP@767e4c56(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]: {}
```


Here is the success log. Here the header written to END

```
org.eclipse.jetty.client.HttpContent - Advanced content to last chunk
org.eclipse.jetty.client.HttpSender - Generated headers (-1 bytes), chunk (-1 bytes), content (0 bytes) - NEED_HEADER/HttpGenerator@2bcb87b5{s=START}
org.eclipse.jetty.client.HttpSender - Generated headers (1128 bytes), chunk (-1 bytes), content (0 bytes) - FLUSH/HttpGenerator@2bcb87b5{s=COMPLETING}
org.eclipse.jetty.client.HttpSender - Generated headers (-1 bytes), chunk (-1 bytes), content (-1 bytes) - DONE/HttpGenerator@2bcb87b5{s=END}
org.eclipse.jetty.client.HttpSender - Request committed HttpRequest[GET /api/user HTTP/1.1]@577b1a04
```

Jetty Version : 9.4.10.v20180503

**Comment by arulrajnet** [comment]
I solved it. 

The `idleTimeout` of client and server should not be the same. The client timeout should lesser than server.

**Comment by darrachequesne** [comment]
I think we found the culprit. The value of the `KeepAliveTimeout` on the httpd server was set too low (2 seconds, the default being 5 seconds), which resulted in HTTP connections being randomly closed. When increasing it to 15 seconds, the HTTP 502 responses disappeared.

@joakime thanks for the support!
