### ISSUE TITLE
Jetty acceptor threads are in BLOCKED state for very long time

### ISSUE THREAD

**Issue by ashimcompsc** [eclipse/jetty.project#3266]
We are using jetty 9.4.5 in our product on linux and jdk version is 1.8.0_131-b11. We have performed stress test and observed few of the acceptor threads are in BLOCKED state for the entire duration of stress test run (~2 hrs).
The issue https://github.com/eclipse/jetty.project/issues/760 is suggesting that it is not an issue but i have following questions
1. Why a thread is blocked for so long?
2. What are these objects on which acceptor threads takes lock?
3. Are all acceptors threads looking to take lock on the same object?

Please find the excerpts of thread dump below. It shows Handler-133-acceptor is in RUNNABLE state while the Handler-132-acceptor thread is in WAITING state for the entire duration of stress test run.

"HTTP Connection Handler-133-acceptor-1@7624d7e1-Jetty Connector 0.0.0.0 port 8080@4571f11a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}" #133 prio=3 os_prio=0 tid=0x00007fc8a0019000 nid=0x2e76 runnable [0x00007fc8fc3cc000] 
   java.lang.Thread.State: RUNNABLE 
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) 
        at 
sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) 
        at 
sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) 
        - locked <0x00000005082c68c8> (a java.lang.Object) 
        at 
org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378) 
        at 
org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java 
:639) 
        at 
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:76 
0) 
        at 
org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678 
) 
        at java.lang.Thread.run(Thread.java:748) 

"HTTP Connection Handler-132-acceptor-0@72b93e10-Jetty Connector 0.0.0.0 port 
8080@4571f11a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}" #132 prio=3 os_prio=0 
tid=0x00007fc8a0011800 nid=0x2e75 waiting for monitor entry 
[0x00007fc8fc4cd000] 
   java.lang.Thread.State: BLOCKED (on object monitor) 
        at 
sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:233) 
        - waiting to lock <0x00000005082c68c8> (a java.lang.Object) 
        at 
org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378) 
        at 
org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java 
:639) 
        at 
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:76 
0) 
        at 
org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678 
) 
        at java.lang.Thread.run(Thread.java:748)

**Comment by ashimcompsc** [comment]
Thanks Simone for quick response.

However i have few more questions on the object lock taken by acceptor threads.
In the below excerpt of the thread dump "Handler-132-acceptor" is blocked on the object with ID - 0x00000004e0baacd0 and "Handler-142-acceptor" is blocked on the object with ID 0x00000004e06d9fc8.

1. Shouldn't the ID of the lock object be same as all the acceptor threads are supposed to share the same object lock?
2. I observed that a pair of acceptor threads are in RUNNABLE state and another pair in the BLOCKED state. Shouldn't only one acceptor thread be running while others be waiting at a particula point of time?

"HTTP Connection Handler-132-acceptor-0@390ad399-Jetty Connector 0.0.0.0 port 8080@787bb1c7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}" #132 prio=3 os_prio=0 tid=0x00007ff034010800 nid=0x7792 waiting for monitor entry [0x00007feffe9f2000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:233)
	- waiting to lock <0x00000004e0baacd0> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:639)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)
	
	"HTTP Connection Handler-133-acceptor-1@7de90720-Jetty Connector 0.0.0.0 port 8080@787bb1c7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}" #133 prio=3 os_prio=0 tid=0x00007ff034012800 nid=0x7793 runnable [0x00007feffe8f1000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	- locked <0x00000004e0baacd0> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:639)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)


	"HTTP Connection Handler-141-acceptor-0@4e1e410a-Jetty Connector 0.0.0.0 port 10443@40d9b6b9{SSL,[ssl, http/1.1]}{0.0.0.0:10443}" #141 prio=3 os_prio=0 tid=0x00007ff05c003000 nid=0x779e runnable [0x00007feffdfe8000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	- locked <0x00000004e06d9fc8> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:639)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)
	
	
	"HTTP Connection Handler-142-acceptor-1@4eb9e62c-Jetty Connector 0.0.0.0 port 10443@40d9b6b9{SSL,[ssl, http/1.1]}{0.0.0.0:10443}" #142 prio=3 os_prio=0 tid=0x00007ff05c005000 nid=0x779f waiting for monitor entry [0x00007feffdee7000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:234)
	- waiting to lock <0x00000004e06d9fc8> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:378)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:639)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sbordet** [comment]
You have 2 `ServerConnector`s, so you have 1 RUNNABLE thread each, 1 lock each, and N-1 BLOCKED threads each (where N is the number of acceptors you have configured).

**Comment by ashimcompsc** [comment]
Thanks Simone.
I understood the concept.

**Comment by yyconstantine** [comment]
> You have 2 `ServerConnector`s, so you have 1 RUNNABLE thread each, 1 lock each, and N-1 BLOCKED threads each (where N is the number of acceptors you have configured).

I have many servers(different application, but all provide HTTP API) run in jetty, some of these have no blocked threads, but some servers do, that bothers me a lot

**Comment by sbordet** [comment]
If they are acceptor threads, that is normal.

**Comment by yyconstantine** [comment]
> If they are acceptor threads, that is normal.

They are acceptor threads, but some of my application run in same version of jetty don't have blocked acceptor threads
In my opinion, they shuold show same status

**Comment by sbordet** [comment]
You probably have a different configuration, then.

**Comment by gregw** [comment]
You can configure jetty connectors to have 0 acceptor threads and then the accepting is done asynchronously by the selector.   If you have persistent connections with few accepting events, then async accepting is probably best.   But if you have many CPU cores and frequent new connections, then acceptor threads are better.
