### ISSUE TITLE
when write response to the channel occur exception

### ISSUE THREAD

**Issue by chenchencc** [eclipse/jetty.project#3270]
```
org.eclipse.jetty.io.EofException: null 
 at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:286) ~[jetty-io-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429) ~[jetty-io-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:384) ~[jetty-io-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:133) ~[jetty-io-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:295) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [jetty-util-9.4.10.v20180503.jar!/:9.4.10.v20180503]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45] 
Caused by: java.io.IOException: Broken pipe
 at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_45]
 at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_45]
 at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_45]
 at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_45]
 at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[?:1.8.0_45]
 at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264) ~[jetty-io-9.4.10.v20180503.jar!/:9.4.10.v20180503] 
 ... 11 more
```

**Comment by sbordet** [comment]
@chenchencc can you at least properly report stack traces? See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code.
Also, add a description of the problem, otherwise we're going to close the issue right away as there is not enough information for us to know what your problem is.
Your Jetty version is outdated, please use the most recent one.

**Comment by joakime** [comment]
@chenchencc you are using a long ago expired JVM `1.8.0_45` and not the most recent version of Jetty.

According to [the Java 1.8.0_45 release notes](https://www.oracle.com/technetwork/java/javase/8u45-relnotes-2494160.html), that version of Java expired on July 14, 2015.

Can you at least update/upgrade both the JVM (critical!) and the version of Jetty you are using?

**Comment by joakime** [comment]
Closing as there has been no followup from OP.
We will happily reopen once more details are provided.
