### ISSUE TITLE
HttpChannel.onRequestBegin not called

### ISSUE THREAD

**Issue by jebeaudet** [eclipse/jetty.project#3314]
Hi
I'm using Jetty 9.4.14.v20181114 with Spring Boot 1.5.19.RELEASE and I have a need for auditing on my application for all requests that come in. I do this by generating a GUID as the request id at the beginning of the request and inject it in the MDC for tracing purposes. At the end of the request, I log a line including this request id along with the request path + authentication.

I had implemented this using servlet filters although the implementation was cumbersome to keep the same request id in case of error dispatch notably. I then decided to move the implementation to `HttpChannel.Listener` to simplify all of this (and it did!) but now I have a case where my listener generating the request id GUID doesn't get called in some cases (haven't been able to reproduce, it looks random). The result is a log with "audit for request with id 'null'" since my listener on `onComplete` seems to always run. It looks like ~0.1% of the requests (very approximate) are not getting their onRequestBegin listener called.

I enabled the debug logging on HttpChannel to see if my listeners were throwing an exception but it's not the case. For the faulty requests, I cannot see this log `LOG.debug("REQUEST for {} on {}{}{} {} {}{}{}",[...])` isn't it supposed to be called systematically?

Here is an excerpt of the code : 
```java
public class MDCInitializerHttpChannelListener implements HttpChannel.Listener
{
    @Override
    public void onRequestBegin(Request request)
    {
        String requestId = UUID.randomUUID().toString();
        request.getResponse().setHeader(LoggingTags.X_REQUEST_ID, requestId);
        MDC.put(LoggingTags.X_REQUEST_ID, requestId);
    }
}
```

```java
public class AuditLogger implements HttpChannel.Listener
{
    private static final Logger logger = LoggerFactory.getLogger(AuditLogger.class);

    @Override
    public void onComplete(Request request)
    {
        try {
            logAuditMessage();
        } catch (Exception e) {
            logger.error("Something went wrong while logging the audit.", e);
        }
    }

    private void logAuditMessage()
    {
        String logMessage = String.format("Audit for request id '%s'.", 
        MDC.get(LoggingTags.X_REQUEST_ID));

        [...]

        logger.info(markers, logMessage);
    }
}
```

I initially though about async dispatch however, AFAICT, I'm not using any here. Did I miss something obvious or there might be a problem in Jetty? I've tried in vain to find a way to reproduce, it can happen on succesful/unsucessful requests, GET/POST/etc...

Thanks a lot

**Comment by joakime** [comment]
How did add your listeners to Jetty?

**Comment by joakime** [comment]
Also, are you testing HTTP/1.1 or HTTP/2 ?

**Comment by jebeaudet** [comment]
HTTP/1.1

I'm injecting the listeners on the Connector instances with `Connector::addBean`.

**Comment by joakime** [comment]
> HTTP/1.1

Looking at the code, the HTTP/1 path will call those listeners for all non-upgrade requests (including Bad Requests that result in a 400 response).

The 2 types of upgrades I see in the codebase ...

* Upgrade to WebSocket
* Upgrade to HTTP/2

> I'm injecting the listeners on the Connector instances with Connector::addBean.

Cool, as long as you do this very early it should be fine.
Consider adding those Listeners when the `ServerConnector`'s are created, and before they are started or added to the server connector list.

**Comment by joakime** [comment]
For those `onComplete(Request request)` (that don't have a corresponding `onRequestBegin()`) can you dump the request object?
Perhaps that will help you figure out what kind of requests these are occurring on.

**Comment by jebeaudet** [comment]
The listeners are added to `Connector` before they are started at the bootstrap of the application. 

Am I understanding correctly that the listeners won't get called on websocket or http2 upgrades? AFAIK I'm not using them but I'll have to check further. If that's the case, what should I use for upgraded requests?

Also, am I being correct saying that this `HttpChannel.Listener` setup should work as intended?

I could add the `request.toString()` easily although I'll have to get back to you with the result since I can't do it tonight. Thanks again!

**Comment by joakime** [comment]
> I could add the `request.toString()` easily although I'll have to get back to you with the result since I can't do it tonight.

The things that are useful to know from the `Request` object ...

* `Request.isHandled()` - if this is true, something on the server handled the request.  false means nothing processed that request.
* `Request.getMetadata().toString()` - this will dump the request line (Method, URI, and Http Version)
* `Request.toString()` - this will dump the request header fields (will tell you lots about possible upgrade request, etc)
* `Request.getDispatcherType()` - this will tell you what kind of dispatch this request is (REQUEST, ASYNC, ERROR, etc) - can be useful to determine if this is a physical request or a synthetic one (from async, error, `RequestDispatcher.include()`, etc)
* `Request.getResponse().toString()` - this will tell you what kind of response was already produced for this request.

**Comment by jebeaudet** [comment]
Alright so we checked it out yesterday night and this morning and realized that when the issue occurs, the calling thread for the `onRequestBegin` and `onComplete` is not the same. Since we're using the MDC which is a thread local in the logback implementation, this breaks the feature.

I've tried going through the code and I can't find a code path where the thread would be different for both listeners, unless we're in async which we're not (confirmed by enabled the debug logging on HttpChannelState). 

From looking at the stack traces when the `onRequestBegin` is called, I can see that it's in the `HttpParser`, could that be a "side effect" of the `ReservedThreadExecutor` used in `QueuedThreadPool` as discussed [here](https://webtide.com/thread-starvation-with-eat-what-you-kill-2/)?

I also logged the request/response when the issued occured and not much information can be deducted, the dispatcherType is `null` in the `onComplete` invocation, I guess due to the request being recycled. The request is always handled == true.

Here is the stacktrace when `onRequestBegin` is invoked : 
```
java.lang.Exception: null
	at com.coveo.cloud.baseservice.configuration.jetty.audit.TestHttpChannel.onRequestBegin(TestHttpChannel.java:28)
	at org.eclipse.jetty.server.HttpChannel.notifyEvent1(HttpChannel.java:1020)
	at org.eclipse.jetty.server.HttpChannel.notifyRequestBegin(HttpChannel.java:941)
	at org.eclipse.jetty.server.HttpChannel.onRequest(HttpChannel.java:693)
	at org.eclipse.jetty.server.HttpChannelOverHttp.headerComplete(HttpChannelOverHttp.java:389)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1218)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1502)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:360)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

And when `onComplete` is invoked : 
```
java.lang.Exception: null
	at com.coveo.cloud.baseservice.configuration.jetty.audit.TestHttpChannel.onComplete(TestHttpChannel.java:42)
	at org.eclipse.jetty.server.HttpChannel.notifyEvent1(HttpChannel.java:1020)
	at org.eclipse.jetty.server.HttpChannel.notifyComplete(HttpChannel.java:1011)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:746)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:514)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

We're reproducing quite easily in our dev environment, although I've yet to reproduce it locally. Let me know if you need more information of some sorts. Thanks again.

**Comment by joakime** [comment]
There is no expectation of a single request being handled by a single thread.
In Jetty 9+ a single request can be handled by 1...n threads. (even non-async requests)

**Comment by jebeaudet** [comment]
Well that explains my behavior then. I use the MDC so that my request id gets appended automatically as a custom field for all the logs in the request with the logstash encoder I use. I was thrown off by the javadoc of the listener saying :

> Listener methods are invoked synchronously from the thread that is performing the request processing, and they should not call blocking code (otherwise the request processing will be blocked as well).

I'm not a native english speaker but the way I read it was that there was a single thread processing the request throughout its whole lifecycle.

One last question then, is there any warranty that the `onBeforeDispatch` method will execute in the same thread as `onComplete` (it seems like it's the case right now)? Or should I just stick my implementation to servlet filters?

**Comment by joakime** [comment]
You are working with the `Request`, which has a much larger scope then the `HttpServletRequest` and its dispatch within the servlet spec (which has strong rules on threading).

The `Request` is parsed, populated, customized, dispatched (now in servlet spec rules), finished, completed, recycled. (to name some of the more common steps you'll see).
The thread that created / populated / customized the request can be different from the thread that dispatched, and even from the thread that finished up the writing of the bytes to the network.
(I'm simplifying it quite a bit here, so be aware of other cases not mentioned)

**Comment by jebeaudet** [comment]
Alright then, wrong assumptions on my part ended up in that issue then. Thanks for clearing it up and hopefully it'll turn up in search engines for a future user.

Cheers!

**Comment by Falmarri** [comment]
I know this is old, but what's the solution for logging the request IDs then if not a channel listener?

**Comment by jebeaudet** [comment]
@Falmarri I've been using channel listeners for the past couple of years for our audits and it works great. We're just not using thread locals but instead relying on `request.setAttribute()` and `request.getAttribute()` to pass stuff around the lifecycle of the request like suggested here.
