### ISSUE TITLE
Websphere  8.5.5.14 - java.lang.VerifyError: JVMVRFY007  - class=org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection

### ISSUE THREAD

**Issue by lasreeram** [eclipse/jetty.project#3424]
Trying to deploy a Javaspark application in websphere and get the below error. We are running Websphere version - 8.5.5.14 

Get the below error. We are deploying this for the first time. Not sure how to resolve this. Please help!

Caused by: com.ibm.ws.exception.RuntimeWarning: com.ibm.ws.webcontainer.exception.WebAppNotLoadedException: Failed to load webapp: Failed to load webapp: JVMVRFY007 final method overridden&amp;#59&#59; class=org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection, method=toString&amp;#40&#59;&amp;#41&#59;Ljava/lang/String&amp;#59&#59;
        at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:433)
        at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:719)
        at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1211)
        at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1450)
        at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:639)
        at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:1032)
        at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:795)
        at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplicationDynamically(ApplicationMgrImpl.java:1413)
        at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2273)
        at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:436)
        at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)
        at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:379)
        at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:127)
        at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$1.run(CompositionUnitMgrImpl.java:654)
        at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5572)
        at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5698)
        at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255)
        at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCompositionUnit(CompositionUnitMgrImpl.java:668)
        at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCompositionUnit(CompositionUnitMgrImpl.java:612)
        at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:1303)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:83)
        at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:287)
        at javax.management.modelmbean.RequiredModelMBean$4.run(RequiredModelMBean.java:1263)
        at java.security.AccessController.doPrivileged(AccessController.java:666)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:91)
        at javax.management.modelmbean.RequiredModelMBean.invokeMethod(RequiredModelMBean.java:1257)
        ... 19 more

**Comment by lasreeram** [comment]
Not sure if this is even jetty issue or it is related to Websphere.

**Comment by joakime** [comment]
The heart of the issue seems to be ...

> JVMVRFY007 final method overridden&#59; class=org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection, method=toString&#40;&#41;Ljava/lang/String&#59;

That seems to point out that Websphere doesn't like the `String AbstractWebSocektConnection.toString()` declaration.
(Which is actually part of the `AbstractConnection` base object).

https://github.com/eclipse/jetty.project/blob/438042e28bd22382acc4f22cbb63f36e013f52a2/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java#L287-L291

Why Websphere is complaining about this is unknown.
Also, why is Websphere even attempting to load a jetty class?
Do you have websocket-client present perhaps?

**Comment by joakime** [comment]
Can you list the jetty JARs in your webapp's `WEB-INF/lib` for us?

**Comment by lasreeram** [comment]
[vlltcmpsguisws01]/home/wasroot/hostapi_v1> jar tvf mps-1.0-SNAPSHOT.war | grep jetty
121362 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-webapp-9.4.6.v20170531.jar
110502 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-servlet-9.4.6.v20170531.jar
 93085 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-security-9.4.6.v20170531.jar
579819 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-server-9.4.6.v20170531.jar
268784 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-client-9.4.6.v20170531.jar
163922 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-http-9.4.6.v20170531.jar
128844 Wed Feb 06 04:50:10 CST 2019 WEB-INF/lib/jetty-io-9.4.6.v20170531.jar
 50392 Wed Feb 06 04:50:10 CST 2019 WEB-INF/lib/jetty-xml-9.4.6.v20170531.jar
457682 Wed Feb 06 04:50:10 CST 2019 WEB-INF/lib/jetty-util-9.4.6.v20170531.jar
[vlltcmpsguisws01]/home/wasroot/hostapi_v1>


The WAR file works correctly in the Jetty Web Server

**Comment by lasreeram** [comment]
On your question 'Also, why is Websphere even attempting to load a jetty class?
Do you have Jetty's websocket-client present perhaps?' - Not sure. This is a java spark application. java spark internally uses the jetty websocket client?

**Comment by joakime** [comment]
Can you search for "websocket" too in `WEB-INF/lib`?

**Comment by lasreeram** [comment]
[vlltcmpsguisws01]/home/wasroot/hostapi_v1> jar tvf mps-1.0-SNAPSHOT.war | grep -i websocket
 34891 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/websocket-server-9.4.6.v20170531.jar
 21303 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/websocket-servlet-9.4.6.v20170531.jar
 35362 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/websocket-client-9.4.6.v20170531.jar
199656 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/websocket-common-9.4.6.v20170531.jar
 41996 Wed Feb 06 04:50:10 CST 2019 WEB-INF/lib/websocket-api-9.4.6.v20170531.jar
[vlltcmpsguisws01]/home/wasroot/hostapi_v1>

**Comment by joakime** [comment]
There's nothing glaring there. 
No duplicate classes, no combination of jars with different versions of releases, or hybrid jars, etc.

However, there are a few jars that have no place even being in a WEB-INF/lib (as they are server jars).

The following are strictly server jars ...

```
121362 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-webapp-9.4.6.v20170531.jar
110502 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-servlet-9.4.6.v20170531.jar
93085 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-security-9.4.6.v20170531.jar
579819 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/jetty-server-9.4.6.v20170531.jar
34891 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/websocket-server-9.4.6.v20170531.jar
21303 Wed Feb 06 04:50:08 CST 2019 WEB-INF/lib/websocket-servlet-9.4.6.v20170531.jar
```

Mark that as a task to remove in the future.
It doesn't impact the issue you are having, but it's worth taking care of.

I don't know why Websphere is having an issue with that, sorry.
Have you reached out to the websphere community to understand this error?
Perhaps they can explain why this is an issue on websphere, and from there we can see about adjustments on jetty to support this usage.

**Comment by lasreeram** [comment]
Thank you!, for your time. Will post this issue in websphere forum. By any stretch would the below be related to what we are seeing. 

https://www.ibm.com/developerworks/community/forums/html/topic?id=77777777-0000-0000-0000-000014870618

**Comment by lasreeram** [comment]
Was able to solve this. This turned out to be a Websphere 8.5 issue (not certain). Moved the websocket-client JAR out of the WAR file and referenced it as a shared lib in Websphere.
