### ISSUE TITLE
java.lang.IllegalStateException: HttpClient has no SslContextFactory, wss:// URI's are not supported in this configuration

### ISSUE THREAD

**Issue by davidkarlsen** [eclipse/jetty.project#3447]
I'm getting
```
2019-03-10 18:09:13.361 ERROR 21 --- [cTaskExecutor-1] o.s.w.s.c.WebSocketConnectionManager     : Failed to connect
web    | 
web    | java.lang.IllegalStateException: HttpClient has no SslContextFactory, wss:// URI's are not supported in this configuration
web    |        at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:362) ~[websocket-client-9.4.15.v20190215.jar:9.4.15.v20190215]
web    |        at org.eclipse.jetty.websocket.jsr356.ClientContainer.connect(ClientContainer.java:215) ~[javax-websocket-client-impl-9.4.15.v20190215.jar:9.4.15.v20190215]
web    |        at org.eclipse.jetty.websocket.jsr356.ClientContainer.connectToServer(ClientContainer.java:259) ~[javax-websocket-client-impl-9.4.15.v20190215.jar:9.4.15.v20190215]
web    |        at org.springframework.web.socket.client.standard.StandardWebSocketClient.lambda$doHandshakeInternal$0(StandardWebSocketClient.java:150) ~[spring-websocket-5.1.5.RELEASE.jar:5.1.5.RELEASE]
web    |        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
web    |        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```
with 9.4.15 - work with 9.4.14

**Comment by joakime** [comment]
javax.websocket client issue?
That has SSL enabled by default.

Are you using a custom Jetty `HttpClient` configuration per chance?
Or do you have a custom `jetty-websocket-httpclient.xml` in your project?

**Comment by davidkarlsen** [comment]
Yes - I have a jetty-websocket-httpclient.xml on the classpath:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">

<Configure class="org.eclipse.jetty.client.HttpClient">
  <Get name="proxyConfiguration">
    <Get name="proxies">
      <Call name="add">
        <Arg>
          <New class="org.eclipse.jetty.client.HttpProxy">
            <Arg type="String">myproxyhost</Arg>
            <Arg type="Integer">8080</Arg>
          </New>
        </Arg>
      </Call>
    </Get>
  </Get>
</Configure>
```

**Comment by sbordet** [comment]
@davidkarlsen you need to explicitly set the `SslContextFactory` on the `HttpClient` you create with the XML file.

This could be as simple as:

```xml
<Configure class="org.eclipse.jetty.client.HttpClient">
  <Arg>
    <New class="org.eclipse.jetty.util.ssl.SslContextFactory" />
  </Arg>
  <Get name="proxyConfiguration">
  ...
</Configure>
```

Of course you can configure it at your liking.
