### ISSUE TITLE
NPE in MappedLoginService after upgrade to 9.3.7.v20160115

### ISSUE THREAD

**Issue by abes-dabir** [eclipse/jetty.project#345]
Hi,

I just tried upgrading the version of Jetty I use from 9.3.6.v20151106 to 9.3.7.v20160115.  After launching my application, I get NPEs when I try to do Basic auth:

`java.lang.NullPointerException
        at org.eclipse.jetty.security.MappedLoginService.login(MappedLoginService.java:244)
        at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:61)
        at org.eclipse.jetty.security.authentication.BasicAuthenticator.validateRequest(BasicAuthenticator.java:92)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)`

The previous versions of Jetty work fine for me.  My app is using an embedded Jetty, and sets up Basic auth programmatically, and it looks like there is something there that the new version doesn't like. I used a debugger to inspect MappedLoginService._users and it is an empty list, whereas I would expect it to have the information for the one user I have configured.  Anyway, regardless of any configuration errors, Jetty shouldn't NPE.  I'll double check the programmatic Basic Auth configuraiton.  I don't see anything in the release notes about changes to basic auth...

**Comment by boxymoron** [comment]
I'm seeing the same error. In my case it only happens when I try to authenticate (BASIC) with an invalid password.

**Comment by gregw** [comment]
I just did a quick test with https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/SecuredHelloHandler.java and I could not replicate.    If you could write a little embedded main program that demonstrates the regression that would be handy.

**Comment by boxymoron** [comment]
Hi Greg,

I modified your test class slightly to replicate my config (static context via a ResourceHandler). The code is attached. I ran the class and opened http://localhost:8080 and got the HTTP BASIC auth prompt in my browser. I then entered a random username/password and got this stacktrace:

`2016-03-21 17:56:48,215 [qtp963522361-15] WARN  org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:468) - //localhost:8080/favicon.ico
java.lang.NullPointerException
	at org.eclipse.jetty.security.MappedLoginService.login(MappedLoginService.java:244) ~[jetty-security-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:61) ~[jetty-security-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.security.authentication.BasicAuthenticator.validateRequest(BasicAuthenticator.java:92) ~[jetty-security-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483) ~[jetty-security-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) ~[jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.Server.handle(Server.java:517) ~[jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
`
[SecuredHelloHandler.txt](https://github.com/eclipse/jetty.project/files/183162/SecuredHelloHandler.txt)

**Comment by boxymoron** [comment]
Looking at the commit history it looks like there was some refactoring done during the jetty-9.3.x branch. HashLoginService used to extend MappedLoginService. The latest version (master branch) extends AbstractLoginService which handles missing credentials correctly.

**Comment by janbartel** [comment]
This is a duplicated of this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=486497

That was fixed for 9.3.8.

Jan
