### ISSUE TITLE
ClassCastException when using websocket-core classes in websocket-servlet

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#3484]
running the following code in a webapp gives a ClassCastException for `ExtensionConfig` which is a websocket-core class

```java
public void configure(WebSocketServletFactory factory)
{
    try
    {
        WebSocketCreator creator = (req, resp) ->
        {
            List<ExtensionConfig> configs = req.getExtensions();
            resp.setExtensions(configs);
            return new ForwardingSocket(client, serverUri);
        };

        factory.setCreator(creator);
    }
    catch (Throwable t)
    {
        t.printStackTrace();
    }
}
```

<hr>

**Stacktrace:**
```
2019-03-25 10:49:40.049:INFO::main: Logging initialized @438ms to org.eclipse.jetty.util.log.StdErrLog
2019-03-25 10:49:40.272:INFO:oejs.Server:main: jetty-10.0.0-SNAPSHOT; built: 2019-03-24T23:32:40.445Z; git: f8f6e21a2d1470bda8ef5f4d083ce99174756468; jvm 11.0.2+9-LTS
2019-03-25 10:49:40.321:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/lachlan/jetty/test-base/webapps/] at interval 1
2019-03-25 10:49:40.603:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=89ms
2019-03-25 10:49:40.611:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /test, did not find org.eclipse.jetty.jsp.JettyJspServlet
2019-03-25 10:49:40.660:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2019-03-25 10:49:40.660:INFO:oejs.session:main: No SessionScavenger set, using defaults
2019-03-25 10:49:40.661:INFO:oejs.session:main: node0 Scavenging every 600000ms
2019-03-25 10:49:40.928:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@dc7df28{Test WebApp,/test,file:///tmp/jetty-0.0.0.0-8080-test.war-_test-any-16646103782115877334.dir/webapp/,AVAILABLE}{/test.war}
2019-03-25 10:49:40.938:INFO:oejs.AbstractConnector:main: Started ServerConnector@2453f95d{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-03-25 10:49:40.939:INFO:oejs.Server:main: Started @1329ms
2019-03-25 10:49:46.844:WARN:oejws.WebSocketMapping:qtp521081105-12: Error during upgrade: 
java.lang.ClassCastException: class org.eclipse.jetty.websocket.core.ExtensionConfig cannot be cast to class org.eclipse.jetty.websocket.core.ExtensionConfig (org.eclipse.jetty.websocket.core.ExtensionConfig is in unnamed module of loader org.eclipse.jetty.start.Classpath$Loader @4e7dc304; org.eclipse.jetty.websocket.core.ExtensionConfig is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @79defdc)
    at com.acme.WebSocketForwardingServlet.lambda$configure$0(WebSocketForwardingServlet.java:39)
    at org.eclipse.jetty.websocket.servlet.WebSocketMapping$Negotiator.negotiate(WebSocketMapping.java:289)
    at org.eclipse.jetty.websocket.core.server.internal.RFC6455Handshaker.upgradeRequest(RFC6455Handshaker.java:128)
    at org.eclipse.jetty.websocket.servlet.WebSocketMapping.upgrade(WebSocketMapping.java:245)
    at org.eclipse.jetty.websocket.servlet.WebSocketServlet.service(WebSocketServlet.java:162)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:859)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1590)
    at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:135)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1577)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:525)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1683)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:464)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1650)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:534)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:264)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:309)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
    at java.base/java.lang.Thread.run(Thread.java:834)
^C2019-03-25 10:50:16.139:INFO:oejs.AbstractConnector:Thread-0: Stopped ServerConnector@2453f95d{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-03-25 10:50:16.140:INFO:oejs.session:Thread-0: node0 Stopped scavenging
2019-03-25 10:50:16.155:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@dc7df28{Test WebApp,/test,null,UNAVAILABLE}{/test.war}
```

**Comment by sbordet** [comment]
@lachlan-roberts this is akin to the `ClassCastException` that I was trying to reproduce with CometD.
You have core classes in the webapp, which is wrong as they should be provided by the server.

**Comment by lachlan-roberts** [comment]
`WebSocketServlet` has been made generic and implemented by the jetty-websocket-api so now you can use jetty-websockets without any class cast exceptions

however if you try to use `WebSocketServlet` directly there are some problems
specifically when trying to use the `WebSocketProxy` (uses core api) in a servlet
```java
public class WebSocketProxyServlet extends WebSocketServlet
{
    private WebSocketCoreClient client;
    private URI uri;

    @Override
    public void configure(WebSocketServletFactory factory)
    {
        WebSocketCreator creator = (req, resp) -> new WebSocketProxy(client, uri).client2Proxy;
        factory.setCreator(creator);
    }

    @Override
    public FrameHandlerFactory getFactory()
    {
        return (pojo, req, resp) -> (FrameHandler)pojo;
    }

```

Looks like there might be a conflicting `FrameHandler` type in the `FrameHandlerFactory` lambda, between the provided one and the webapps version.

```
java.lang.LinkageError: loader constraint violation in interface itable initialization for class com.acme.WebSocketProxyServlet$$Lambda$169/0x000000010027dc40: when selecting method org.eclipse.jetty.websocket.servlet.FrameHandlerFactory.newFrameHandler(Ljava/lang/Object;Lorg/eclipse/jetty/websocket/servlet/ServletUpgradeRequest;Lorg/eclipse/jetty/websocket/servlet/ServletUpgradeResponse;)Lorg/eclipse/jetty/websocket/core/FrameHandler; the class loader org.eclipse.jetty.start.Classpath$Loader @4e7dc304 (instance of org.eclipse.jetty.start.Classpath$Loader, child of 'app' jdk.internal.loader.ClassLoaders$AppClassLoader) for super interface org.eclipse.jetty.websocket.servlet.FrameHandlerFactory, and the class loader org.eclipse.jetty.webapp.WebAppClassLoader @13df2a8c (instance of org.eclipse.jetty.webapp.WebAppClassLoader, child of org.eclipse.jetty.start.Classpath$Loader @4e7dc304 org.eclipse.jetty.start.Classpath$Loader) of the selected method's type, com.acme.WebSocketProxyServlet$$Lambda$169/0x000000010027dc40 have different Class objects for the type org.eclipse.jetty.websocket.core.FrameHandler used in the signature
	at java.base/jdk.internal.misc.Unsafe.defineAnonymousClass0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.defineAnonymousClass(Unsafe.java:1223)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:320)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:188)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:307)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:258)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:248)
	at com.acme.WebSocketProxyServlet.getFactory(WebSocketProxyServlet.java:32)
	at org.eclipse.jetty.websocket.servlet.WebSocketServlet$CustomizedWebSocketServletFactory.addMapping(WebSocketServlet.java:195)
	at org.eclipse.jetty.websocket.servlet.WebSocketServlet$CustomizedWebSocketServletFactory.addMapping(WebSocketServlet.java:189)
	at org.eclipse.jetty.websocket.servlet.WebSocketServlet$CustomizedWebSocketServletFactory.setCreator(WebSocketServlet.java:230)
	at com.acme.WebSocketProxyServlet.configure(WebSocketProxyServlet.java:26)
	at org.eclipse.jetty.websocket.servlet.WebSocketServlet.init(WebSocketServlet.java:152)
	at javax.servlet.GenericServlet.init(GenericServlet.java:203)
	at com.acme.WebSocketProxyServlet.init(WebSocketProxyServlet.java:64)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:429)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:735)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:729)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:388)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1339)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:297)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:563)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:172)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:430)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:65)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:145)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:576)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:238)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:447)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:398)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1592)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1532)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1531)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:490)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
```

**Comment by lachlan-roberts** [comment]
@sbordet if the core classes were provided by the server then everything in websocket would need to be provided including the client

**Comment by sbordet** [comment]
@lachlan-roberts not sure I understand.

I definitely want to be able to provide the WebSocket client classes in the war.
This is because I want to be able to deploy the same war to another Servlet Container without any change, and it should work out of the box.

So I'm not sure why it was working before but now it's not?

**Comment by lachlan-roberts** [comment]
there are no more class cast issues with jetty-websockets or javax-websockets as they do not require websocket core classes to use
