### ISSUE TITLE
Two SslContextFactory with Conscrypt, Client & Server TLSv1.3

### ISSUE THREAD

**Issue by readonlynetwork** [eclipse/jetty.project#3500]
Exception is thrown when I use Conscrypt provider with TLSv1.3 at different SslContextFactory object at the same time.

Client threw Error:
```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: TLSv1.3
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at com.readonlynetwork.prepare.SelfSignedCert.main(SelfSignedCert.java:270)
Caused by: javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: TLSv1.3
	at org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:361)
	at org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1158)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1113)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:861)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:733)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:698)
	at org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:236)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:578)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:128)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.cert.CertificateException: java.lang.IllegalArgumentException: TLSv1.3
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1661)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:531)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1119)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1103)
	... 23 more
Caused by: java.lang.IllegalArgumentException: TLSv1.3
	at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:258)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at org.conscrypt.Java7PlatformUtil.checkServerTrusted(Java7PlatformUtil.java:78)
	at org.conscrypt.Platform.checkServerTrusted(Platform.java:303)
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1653)
	... 27 more
```

**Comment by readonlynetwork** [comment]
2019-03-28 13:22:11.409:INFO::Thread-1: Logging initialized @1452ms to org.eclipse.jetty.util.log.StdErrLog
2019-03-28 13:22:11.638:INFO:oejs.Server:Thread-1: jetty-9.4.15.v20190215; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12
2019-03-28 13:22:11.678:INFO:oejsh.ContextHandler:Thread-1: Started o.e.j.s.h.ContextHandler@34f886fb{/stop,null,AVAILABLE,127.0.0.1}
2019-03-28 13:22:11.679:INFO:oejsh.ContextHandler:Thread-1: Started o.e.j.s.h.ContextHandler@4cc02011{/other,null,AVAILABLE}
2019-03-28 13:22:11.695:INFO:oejus.SslContextFactory:Thread-1: x509=X509@3ee11e05(server1,h=[server.name, testname2],w=[]) for SslContextFactory@61c6a19e[provider=Conscrypt,keyStore=null,trustStore=null]
2019-03-28 13:22:11.758:WARN:oejusS.config:Thread-1: No Client EndPointIdentificationAlgorithm configured for SslContextFactory@61c6a19e[provider=Conscrypt,keyStore=null,trustStore=null]
2019-03-28 13:22:11.779:INFO:oejs.AbstractConnector:Thread-1: Started ServerConnector@5be6ee6f{SSL,[ssl, http/1.1]}{0.0.0.0:50443}
2019-03-28 13:22:11.780:INFO:oejs.Server:Thread-1: Started @1822ms
2019-03-28 13:22:13.451:INFO:oejus.SslContextFactory:main: x509=X509@37374a5e(client,h=[testname],w=[]) for SslContextFactory@4671e53b[provider=Conscrypt,keyStore=null,trustStore=null]

**Comment by readonlynetwork** [comment]
No error if I not use Conscrypt at Client or at Server OR I disable TLSv1.3 at client or at server.

**Comment by readonlynetwork** [comment]
Is it a Conscrypt bug?

**Comment by joakime** [comment]
`jvm 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12` <-- Java 8 does not support TLSv1.3 (Support in the JVM and Java APIs for TLSv1.3 was introduced in Java 11)
The fact that conscrypt uses `org.conscrypt.Java7PlatformUtil` is also telling that conscrypt is running in the older JVM and APIs (that was added in Java 11)

Try your experiments with conscrypt again, but use Java 12
But keep in mind ... https://webtide.com/openjdk-11-and-tls-1-3-issues/

**Comment by readonlynetwork** [comment]
But server still Work with 1.3, and I am able to connect to server with a chrome browser:
```
Certificate - missing
This site is missing a valid, trusted certificate (net::ERR_CERT_AUTHORITY_INVALID).
Connection - secure connection settings
The connection to this site is encrypted and authenticated using TLS 1.3, X25519, and AES_128_GCM.
```

**Comment by readonlynetwork** [comment]
Is it possible to get programmatically the SSL information from Jetty Client? (Server cert, Cipher Suit etc.)

**Comment by readonlynetwork** [comment]
>  If you want to use TLS 1.3 with Conscrypt on one of those versions, you need to use Conscrypt's trust manager... - Conscrypt

**Comment by readonlynetwork** [comment]
I got randomly 3 error when I set this at main first line: `Security.insertProviderAt(Conscrypt.newProvider(), 1);//first position`

```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: SSL_write
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at com.readonlynetwork.prepare.SelfSignedCert.main(SelfSignedCert.java:274)
Caused by: javax.net.ssl.SSLException: SSL_write
	at org.conscrypt.ConscryptEngine.newSslExceptionWithMessage(ConscryptEngine.java:1376)
	at org.conscrypt.ConscryptEngine.wrap(ConscryptEngine.java:1551)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509)
	at org.conscrypt.Java8EngineWrapper.wrap(Java8EngineWrapper.java:56)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:884)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:349)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:670)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

OR

```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: No subjectAltNames on the certificate match
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at com.readonlynetwork.prepare.SelfSignedCert.main(SelfSignedCert.java:272)
Caused by: javax.net.ssl.SSLHandshakeException: No subjectAltNames on the certificate match
	at org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:361)
	at org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1158)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1113)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:861)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:733)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:698)
	at org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:236)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:578)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:128)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.cert.CertificateException: No subjectAltNames on the certificate match
	at org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:406)
	at org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
	at org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:367)
	at org.conscrypt.Java7PlatformUtil.checkServerTrusted(Java7PlatformUtil.java:78)
	at org.conscrypt.Platform.checkServerTrusted(Platform.java:303)
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1653)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:531)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1119)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1103)
	... 23 more
```

OR

```
Fail: java.io.IOException: Broken pipe
java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at com.readonlynetwork.prepare.SelfSignedCert.main(SelfSignedCert.java:272)
Caused by: java.io.IOException: Broken pipe
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:924)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:349)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:670)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by joakime** [comment]
@readonlynetwork can you try branch `jetty-9.4.x-issue-3540-ssl-provider-consistency` and see if it improves things for you?

**Comment by joakime** [comment]
@readonlynetwork note, the work on Issue #3540 has now been merged into `jetty-9.4.x` branch. (branch `jetty-9.4.x-issue-3540-ssl-provider-consistency` no longer exists)

**Comment by readonlynetwork** [comment]
So is it released as 9.4.16? Will it apear in maven as jetty-all (uber)? Then I will try it asap.

**Comment by joakime** [comment]
@readonlynetwork please use the jetty dependencies properly.  `jetty-all` is meant for the tutorial section of the documentation, that's all it exists for.

https://www.eclipse.org/lists/jetty-users/msg06030.html

**Comment by readonlynetwork** [comment]
Conscrypt does not support scf.setEndpointIdentificationAlgorithm("https");
The default setting of SslContextFactory.Client with Conscrypt cause a error

**Comment by readonlynetwork** [comment]
It work well with TLSv1.3! Nice!
Is it possible to get the ssl session info from response at Jetty client? 
Example from Java 11 api: https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpResponse.html#sslSession()

**Comment by sbordet** [comment]
@readonlynetwork please open an new issue for the `Response.sslSession()` enhancement.

**Comment by readonlynetwork** [comment]
https://github.com/eclipse/jetty.project/issues/3553

**Comment by joakime** [comment]
Closing this issue, as followup issue #3553 has been opened
