### ISSUE TITLE
If conscrypt at first position, HttpClient error

### ISSUE THREAD

**Issue by readonlynetwork** [eclipse/jetty.project#3501]
I got randomly 3 error when I set this at main first line: `Security.insertProviderAt(Conscrypt.newProvider(), 1);//first position`

```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: SSL_write
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at com.readonlynetwork.prepare.SelfSignedCert.main(SelfSignedCert.java:274)
Caused by: javax.net.ssl.SSLException: SSL_write
	at org.conscrypt.ConscryptEngine.newSslExceptionWithMessage(ConscryptEngine.java:1376)
	at org.conscrypt.ConscryptEngine.wrap(ConscryptEngine.java:1551)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509)
	at org.conscrypt.Java8EngineWrapper.wrap(Java8EngineWrapper.java:56)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:884)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:349)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:670)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

OR

```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: No subjectAltNames on the certificate match
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at com.readonlynetwork.prepare.SelfSignedCert.main(SelfSignedCert.java:272)
Caused by: javax.net.ssl.SSLHandshakeException: No subjectAltNames on the certificate match
	at org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:361)
	at org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1158)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1113)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:861)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:733)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:698)
	at org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:236)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:578)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:128)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.cert.CertificateException: No subjectAltNames on the certificate match
	at org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:406)
	at org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
	at org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:367)
	at org.conscrypt.Java7PlatformUtil.checkServerTrusted(Java7PlatformUtil.java:78)
	at org.conscrypt.Platform.checkServerTrusted(Platform.java:303)
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1653)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:531)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1119)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1103)
	... 23 more
```

OR

```
Fail: java.io.IOException: Broken pipe
java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at com.readonlynetwork.prepare.SelfSignedCert.main(SelfSignedCert.java:272)
Caused by: java.io.IOException: Broken pipe
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:924)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:349)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:670)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by readonlynetwork** [comment]
If Conscrypt is not in the first position, it work fine.

```
SslContextFactory scf = new SslContextFactory(false);
scf.setProvider("Conscrypt");//enable chacha20, x25519 and others BUT still disable SNI
scf.setKeyStorePassword(new String(keyPassword));
scf.setKeyStore(clientKeyStore);
scf.setTrustStore(clientTrustStore);
scf.setTrustStorePassword(null);
scf.setEndpointIdentificationAlgorithm("https");// check end point
//exclude
scf.addExcludeCipherSuites(".*NULL.*");
scf.addExcludeCipherSuites(".*RC4.*");
scf.addExcludeCipherSuites(".*MD5.*");
scf.addExcludeCipherSuites(".*SHA1.*");
scf.addExcludeCipherSuites(".*DES.*");
scf.addExcludeCipherSuites(".*DSS.*");
scf.addExcludeCipherSuites(".*ECDH_.*");
scf.addExcludeProtocols("SSL");
scf.addExcludeProtocols("SSLv2");
scf.addExcludeProtocols("SSLv2Hello");
scf.addExcludeProtocols("SSLv3");
scf.addExcludeProtocols("TLSv1");
scf.addExcludeProtocols("TLSv1.0");
scf.addExcludeProtocols("TLSv1.1");
//enabled
scf.setIncludeProtocols(new String[] {"TLSv1.2"});//No TLS 1.3 yet
//TLS renegotiation could be disabled too to prevent an attack based on this feature.
scf.setRenegotiationAllowed(false);

//response
HttpClient client = null;
try {
	client = new HttpClient(scf);
	client.setFollowRedirects(false);
	client.start();
	ContentResponse response = client.newRequest("https://www.google.com/")
	        .method(HttpMethod.GET)
	        .timeout(10, TimeUnit.SECONDS)
	        .send();
	System.out.print("Status: ");
	System.out.println(response.getStatus());
	System.out.print("Version: ");
	System.out.println(response.getVersion());
	System.out.print("Body: ");
	System.out.println(response.getContentAsString());
	System.out.print("MediaType: ");
	System.out.println(response.getMediaType());
}catch (Exception e) {
	System.out.println("Fail: " + e.getMessage());
	e.printStackTrace();
}
```

**Comment by joakime** [comment]
Sounds like something the Conscrypt guys can get you an answer about.
What position they recommend. (Hint: it's not always the first one, see BouncyCastle as an example)

**Comment by joakime** [comment]
Closing issue as it's been moved to google/conscrypt#656
