### ISSUE TITLE
java.nio.channels.ClosedByInterruptException causes EofException on WebSocket

### ISSUE THREAD

**Issue by janikgithub** [eclipse/jetty.project#3519]
I am using Jetty 9.4.12.v20180830 and see intermittent EofException. coming from server 
The stack trace I see in the log is different from: #3386 

My stack trace is:

```
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:286)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.flush(FrameFlusher.java:218)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.process(FrameFlusher.java:152)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:90)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:495)
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextOutgoingFrame(AbstractExtension.java:191)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextOutgoingFrame(PerMessageDeflateExtension.java:116)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.access$1000(CompressExtension.java:42)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.compress(CompressExtension.java:554)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.deflate(CompressExtension.java:451)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.process(CompressExtension.java:431)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.outgoingFrame(CompressExtension.java:218)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:419)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:296)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:311)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendAsyncFrame(WebSocketRemoteEndpoint.java:241)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendStringByFuture(WebSocketRemoteEndpoint.java:413)
	at org.apache.zeppelin.socket.NotebookSocket.send(NotebookSocket.java:145)
	at org.apache.zeppelin.socket.NotebookServer.broadcast(NotebookServer.java:899)
	at org.apache.zeppelin.socket.NotebookServer.access$300(NotebookServer.java:101)
	at org.apache.zeppelin.socket.NotebookServer$ParagraphListenerImpl.onProgressUpdate(NotebookServer.java:2808)
	at org.apache.zeppelin.scheduler.JobProgressPoller.run(JobProgressPoller.java:57)
Caused by: java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:478)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
	... 30 common frames omitted

```

Method `onWebsocketClose() ` shows: 
closeCode: 1006, message: WebSocket Write EOF

Additionally in the log file I see:

`org.eclipse.jetty.util.component.AbstractLifeCycle - stopping WebSocketSession[websocket=JettyListenerEventDriver[org.apache.zeppelin.socket.NotebookSocket],behavior=SERVER,connection=WebSocketServerConnection@e03b760b::SocketChannelEndPoint@1e62cf22{/10.39.204.83:54089<->/172.17.0.2:8080,OPEN,fill=-,flush=F,to=639/300000}{io=0/0,kio=-1,kro=-1}->WebSocketServerConnection@e03b760b[ios=IOState@62a6490f[CLOSED,!in,!out,finalClose=CloseInfo[code=1006,reason=WebSocket Write EOF],clean=false,closeSource=ABNORMAL],f=Flusher@d234159[queueSize=0,aggregateSize=0,terminated=org.eclipse.jetty.io.EofException],g=Generator[SERVER,validating,+rsv1],p=Parser@5a216045[ExtensionStack,s=START,c=0,len=1206,f=TEXT[len=0,fin=true,rsv=1..,masked=true]]],remote=WebSocketRemoteEndpoint@664c50a7[batching=true],incoming=JettyListenerEventDriver[org.apache.zeppelin.socket.NotebookSocket],outgoing=ExtensionStack[queueSize=0,extensions=[permessage-deflate],incoming=org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension,outgoing=org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension]]`

I use` sendStringByFuture()` for communication to client.

Any suggestions/help to avoid the issue is appreciated.
Thanks

**Comment by joakime** [comment]
Lots of close behavior changes in WebSocket since 9.4.12, please upgrade to 9.4.15.v20190215 and try again.

**Comment by janikgithub** [comment]
Switched to 9.4.15.v20190215.
Still see the EofException:

`org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.flush(FrameFlusher.java:247)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.process(FrameFlusher.java:181)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:505)
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextOutgoingFrame(AbstractExtension.java:155)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextOutgoingFrame(PerMessageDeflateExtension.java:116)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.access$1000(CompressExtension.java:42)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.compress(CompressExtension.java:554)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.deflate(CompressExtension.java:451)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.process(CompressExtension.java:431)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.outgoingFrame(CompressExtension.java:218)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:400)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:277)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:307)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendAsyncFrame(WebSocketRemoteEndpoint.java:241)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendStringByFuture(WebSocketRemoteEndpoint.java:404)
	at org.apache.zeppelin.socket.NotebookSocket.send(NotebookSocket.java:146)
	at org.apache.zeppelin.socket.NotebookServer.broadcast(NotebookServer.java:899)
	at org.apache.zeppelin.socket.NotebookServer.access$300(NotebookServer.java:101)
	at org.apache.zeppelin.socket.NotebookServer$ParagraphListenerImpl.onProgressUpdate(NotebookServer.java:2808)
	at org.apache.zeppelin.scheduler.JobProgressPoller.run(JobProgressPoller.java:57)
Caused by: java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:478)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:262)
	... 29 common frames omitted
`
Method` onWebSocketClose() `shows **another error code` closeCode: 1011**, message: EofException`

Thanks

**Comment by sbordet** [comment]
`ClosedByInterruptException` is thrown when the writing thread is interrupted via `Thread.interrupt()`.
Jetty does not do that, unless when shutting down.
So perhaps you have some other code or library that interrupts threads?

**Comment by janikgithub** [comment]
I am not aware of any designed interruptions, nut the server code updates client (via web-socket) every 500 ms. I tried to increase the polling to 2000 ms, but that didn't help.
However if I disable the polling completely the EofException doesn't show up.
Not sure whether relevant or not but the `WebSocketPolicy ` values are:
idle timeout = 300,000
input buffer size=4096
max text message size = 1,024,000

**Comment by joakime** [comment]
What @sbordet is saying is that the only way you can get a `ClosedByInterruptException` is that something in your runtime is calling `Thread.interrupt()`.
Jetty calls `Thread.interrupt()` only 2 very specific cases (as its generally a dangerous API to use and can easily cause resources to not be cleaned up properly)

1. The `Server` object is being stopped/shutdown.
2. The `DoSFilter` is being used (and this only applies to normal HTTP requests, not WebSocket)

You might need to setup a breakpoint on `Thread.interrupt()` and see who is using it.
Once you discover who is using `Thread.interrupt()`, you'll have your answer on where to fix this.

**Comment by janikgithub** [comment]
Thank you for your suggestions, unfortunately I am not able to use debugger in my environment - it is a docker. I have to find some other way of tracing the issue.
Thanks

**Comment by janikgithub** [comment]
I think I found the problem. You were right there was a `Thread.interrupt() `call.
Thank you very much!
