### ISSUE TITLE
java.nio.channels.CancelledKeyException

### ISSUE THREAD

**Issue by janikgithub** [eclipse/jetty.project#3529]
I am using 9.4.15.v20190215.
 
Looked at the #2555, #1997, #3519 #3133
They all have different stack trace.

My stack trace is below. Do you have any suggestions why the exception is thrown?
Thanks

```
2019-04-06 15:57:36 {qtp1948863195-356} DEBUG [Server] [HQYWXX4OSUDJYVT] org.eclipse.jetty.io.ManagedSelector - 
java.nio.channels.CancelledKeyException: null
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at org.eclipse.jetty.io.ManagedSelector.safeReadyOps(ManagedSelector.java:294)
	at org.eclipse.jetty.io.ChannelEndPoint.toEndPointString(ChannelEndPoint.java:433)
	at org.eclipse.jetty.io.AbstractEndPoint.toString(AbstractEndPoint.java:447)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.eclipse.jetty.io.AbstractConnection.toString(AbstractConnection.java:290)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:299)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:271)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:233)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:173)
	at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:680)
	at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:224)
	at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:97)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:300)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by joakime** [comment]
Not an issue, not a bug.

You have DEBUG logging turned on.
This is a side effect of DEBUG logging on closed connections.

```
2019-04-06 15:57:36 {qtp1948863195-356} DEBUG [Server] [HQYWXX4OSUDJYVT] org.eclipse.jetty.io.ManagedSelector - 
java.nio.channels.CancelledKeyException: null
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73) 
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)  
	at org.eclipse.jetty.io.ManagedSelector.safeReadyOps(ManagedSelector.java:294)  <-- generic safe ReadOps get that will log at DEBUG level when it has an issue
	at org.eclipse.jetty.io.ChannelEndPoint.toEndPointString(ChannelEndPoint.java:433)
	at org.eclipse.jetty.io.AbstractEndPoint.toString(AbstractEndPoint.java:447)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.eclipse.jetty.io.AbstractConnection.toString(AbstractConnection.java:290)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:299)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:271)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:233)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:173)
	at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:680)
	at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:224)
	at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:97)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:300)  <-- LOGGING of connection at debug level
```

**Comment by sbordet** [comment]
I have recently changed the logging of this from DEBUG to IGNORE.

**Comment by joakime** [comment]
Original implementation (also what's present in Jetty 9.4.15)

https://github.com/eclipse/jetty.project/blob/ebd676df5df4d96fc0b4c40b0a409a7c5c6441ba/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L290-L302

Simone's update ...

https://github.com/eclipse/jetty.project/commit/b6b7d2e730a584f837fd06f80965bc8b1231dc89

Current implementation ...

https://github.com/eclipse/jetty.project/blob/bd0f5ba313be5f6d14b65e2cf4ebf148db2d5564/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L290-L301
