### ISSUE TITLE
Strange HeapByteBuffer changes during parse. 

### ISSUE THREAD

**Issue by santihong** [eclipse/jetty.project#3570]
`Version: 9.4.14.v20181114`

Why the HeapByteBuffer seems changed unexpected, Just during invoke before all reading. 
And why the buffer remain `r=8192` but nothing inside buffer, actually I didn't send any body that long. 
Thank u for any advice.

Associate with issue [HttpInput Early EOF](https://github.com/eclipse/jetty.project/issues/3538)

  ![image](https://user-images.githubusercontent.com/7974622/56341775-afb9b100-61e8-11e9-9a8b-54785ff6bf74.png)

Jetty Source Code:
![image](https://user-images.githubusercontent.com/7974622/56342490-bc3f0900-61ea-11e9-9fc4-b8aa25baf812.png)

![image](https://user-images.githubusercontent.com/7974622/56342527-d678e700-61ea-11e9-95ad-73bccb0f6ea7.png)

**Comment by joakime** [comment]
Please modify your logging output to include the thread name.
The two logging events (54 and 55) could easily be from 2 different threads.
The ByteBuffer's you show are likely the same buffer, but with different position/limit values (was it flipped? or in the middle of a flip?)

**Comment by santihong** [comment]
Okay, I will add thread-id to log.  Can you check this issue for me [HttpInput Early EOF](https://github.com/eclipse/jetty.project/issues/3538).
Invoke `response 400` or 'Early EOF`.  I have post the stack trace, Thanks.

**Comment by santihong** [comment]
@joakime Hi, I dump two successive request, first success, last fail with exception. 
I think the problem is nio HeapByteBuffer state not correct.
[error.txt](https://github.com/eclipse/jetty.project/files/3095811/error.txt)

[2019-04-19 01:43:33]10.25.1.240
content: 2019-04-18 17:43:33.299 [DEBUG][thread-qtp664457955-16] jetty.server.HttpConnection - HttpConnection@29e6397a::SocketChannelEndPoint@661cd1f2{/21.0.8.254:49958<->/21.0.8.8:9000,OPEN,fill=-,flush=-,to=1/3600000}{io=0/0,kio=0,kro=1}->HttpConnection@29e6397a[p=HttpParser{s=START,0 of -1},g=HttpGenerator@2975eef5{s=START}]=>HttpChannelOverHttp@68db3341{r=824,c=false,a=IDLE,uri=null,age=0} parse HeapByteBuffer@5bea6788[p=27,l=1876,c=8192,r=1849]={POST /invoke HTTP/1.1\r\nHost<<<: 162733438250787...\x96\x87', age: '28'}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} {}

-2
[2019-04-19 01:43:33]10.25.1.240
content: 2019-04-18 17:43:33.304 [DEBUG][thread-qtp664457955-16] jetty.http.HttpParser - parseNext s=START HeapByteBuffer@5bea6788[p=27,l=1876,c=8192,r=1849]={POST /invoke HTTP/1.1\r\nHost<<<: 162733438250787...\x96\x87', age: '28'}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}

-1
[2019-04-19 01:43:33]10.25.1.240
content: 2019-04-18 17:43:33.311 [DEBUG][thread-qtp664457955-16] jetty.http.HttpParser - Illegal character SPACE=' ' in state=START for buffer HeapByteBuffer@5bea6788[p=29,l=1876,c=8192,r=1847]={POST /invoke HTTP/1.1\r\nHost: <<<1627334382507875....\x96\x87', age: '28'}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}

0
[2019-04-19 01:43:33]10.25.1.240
content: 2019-04-18 17:43:33.311 [DEBUG][thread-qtp664457955-16] jetty.http.HttpParser - Parse exception: HttpParser{s=START,0 of -1} for HttpChannelOverHttp@68db3341{r=824,c=false,a=IDLE,uri=null,age=0}
org.eclipse.jetty.http.HttpParser$IllegalCharacterException: 400: Illegal character SPACE=' '
at org.eclipse.jetty.http.HttpParser.quickStart(HttpParser.java:551) [XXX.jar:?]
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1488) [XXX.jar:?]
at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:360) [XXX.jar:?]
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250) [XXX.jar:?]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [XXX.jar:?]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [XXX.jar:?]
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [XXX

**Comment by joakime** [comment]
A few observations from your `error.txt` ...

A HTTP Response seen ...

```
200 null HTTP/1.1
Date: Thu, 18 Apr 2019 17:43:33 GMT
Content-Length: 27
Content-Type: application/octet-stream
Connection: keep-alive
```

The `Connection: keep-alive` has no meaning for HTTP/1.1.   The value `keep-alive` only works for HTTP/1.0.

Don't send that particular value on HTTP/1.1, either don't send the `Connection` header at all for a persistent connection, or send `Connection: close` to close the connection.
Those are your only two options in this HTTP/1.1 scenario.

Your chosen client, `okhttp/2.7.5` will not use the `keep-alive` value on an HTTP/1.1 exchange, it too will only use `keep-alive` on HTTP/1.0 exchanges. (okhttp removed support to use HTTP/1.0 back in 2014)

The request at line 641 ...

```
[2019-04-19 01:43:33]10.25.1.240
content: 2019-04-18 17:43:33.276 [DEBUG][thread-qtp664457955-16] jetty.server.HttpChannel - REQUEST for //XXX/invoke on HttpChannelOverHttp@68db3341{r=824,c=false,a=IDLE,uri=//XXX/invoke,age=0}
POST //XXX/invoke HTTP/1.1
Host: XXX
Accept-Encoding: gzip
User-Agent: okhttp/2.7.5
Content-Length: 27
Content-Type: application/json;charset=UTF-8
```

is the request before your failure.
That request never receives it's 27 bytes of body content. 

The next buffer of network bytes it receives is on line 883

```
[2019-04-19 01:43:33]10.25.1.240
content: 2019-04-18 17:43:33.289 [DEBUG][thread-qtp664457955-16] jetty.io.ChannelEndPoint - filled 1876 HeapByteBuffer@5bea6788[p=0,l=1876,c=8192,r=1876]=
{<<<POST /invoke HTTP...\x96\x87', age: '28'}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
```

The parser is still in CONTENT mode, looking for body content on the prior request.

It reads 27 bytes, as seen by line 913

```
[2019-04-19 01:43:33]10.25.1.240
content: 2019-04-18 17:43:33.291 [DEBUG][thread-qtp664457955-16] jetty.server.HttpInput - HttpInputOverHTTP@6dce1a25[c=0,q=0,[0]=null,s=STREAM] addContent Content@75775484{HeapByteBufferR@14494f65[p=0,l=27,c=8192,r=27]=
{<<<POST /invoke HTTP/1.1\r\nHost>>>: 162733438250787...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}}
```

The text `"POST /invoke HTTP/1.1\r\nHost"` is your 27 bytes of body content on the POST request at line 641.

Then the Parser switches state to read the next request. (line 1110)
At which point the "request" is seen as ...

```
[2019-04-19 01:43:33]10.25.1.240
content: 2019-04-18 17:43:33.304 [DEBUG][thread-qtp664457955-16] jetty.http.HttpParser - parseNext s=START HeapByteBuffer@5bea6788[p=27,l=1876,c=8192,r=1849]=
{POST /invoke HTTP/1.1\r\nHost<<<: 162733438250787...\x96\x87', age: '28'}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
```

Which is seen as `": 162733438250787...\x96\x87', age: '28'}"`, which is an invalid request.

The parser was attempting to find the HTTP method.
But it encountered on the second character is a SPACE which is invalid / illegal at that point.

You have a bad client that didn't send its POST body content.
Have you considered upgrading your okhttp to something more current / stable / supported?
okhttp 2.7.5 is over 2 years old, and the entire okhttp 2.x codebase is pretty much abandoned at this point.

**Comment by joakime** [comment]
on your server side, you can validate / verify this by reading your POST body content. (use `HttpServletRequest.getInputStream()`)
It likely had the `POST /invoke HTTP/1.1` content if you attempted to read it.

**Comment by santihong** [comment]
@joakime  Acctually, I use golang1.8 net/http as the middle proxy, that's the request process: `okhttp->golang1.8->jetty`.

Is that any possible the jetty onContent read 27 bytes rightly, but position set error:
    
    -39
    [2019-04-19 01:43:33]10.25.1.240 content: 2019-04-18 17:43:33.291 [DEBUG][thread-qtp664457955-16] jetty.server.HttpChannel -HttpChannelOverHttp@68db3341{r=824,c=false,a=DISPATCHED,uri=//XXX/invoke,age=15} onContent Content@75775484{HeapByteBufferR@14494f65[p=0,l=27,c=8192,r=27]={<<<POST /invoke HTTP/1.1\r\nHost>>>: 162733438250787...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}}

This should be something like `[p=1876, l=1876+27, c=8192, r=27]`,there 1876 was the already existed buffer.
Just like the correct one:
    
    -214
    [2019-04-19 01:43:33]10.25.1.240 content: 2019-04-18 17:43:33.215 [DEBUG][thread-qtp664457955-16] jetty.server.HttpChannel - HttpChannelOverHttp@68db3341{r=823,c=false,a=DISPATCHED,uri=//XXX/invoke,age=6} onContent Content@357c1cac{HeapByteBufferR@8efbefa[p=1849,l=1876,c=8192,r=27]={POST /invoke HTTP...oding: gzip\r\n\r\n<<<{name: '\xE4\xB8\xAd\xE6\x96\x87', age: '28'}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}}

**Comment by santihong** [comment]
@joakime I am sure the error read `p=0` was not right compare with all success invoke before.

![image](https://user-images.githubusercontent.com/7974622/56402294-42149000-628f-11e9-85a7-3adbdacf4071.png)

Is this jetty read content error? I don't think the golang1.8 didn't send body.  As it is so simple only two lines code

        if param.Event != nil {
            req.Body = ioutil.NopCloser(bytes.NewReader(param.Event))
        }
        req.ContentLength = int64(len(param.Event))

**Comment by santihong** [comment]
Another situation `Early EOF`.

Unknownable parseNext:

    -18
    [2019-04-19 11:29:19]10.24.238.107 content: 2019-04-19 03:29:19.273 [DEBUG][thread-qtp664457955-10] jetty.http.HttpParser - parseNext s=CONTENT HeapByteBuffer@6ce4ba82[p=1849,l=8192,c=8192,r=6343]={POST /invoke HTTP...oding: gzip\r\n\r\n<<<{name: '\xE4\xB8\xAd\xE6\x96\x87', ...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>}

Received a content correctly 27 bytes:

    -16
    [2019-04-19 11:29:19]10.24.238.107 content: 2019-04-19 03:29:19.273 [DEBUG][thread-qtp664457955-10] jetty.server.HttpChannel - HttpChannelOverHttp@6d5d2c97{r=4990,c=false,a=DISPATCHED,uri=/XXX/invoke,age=2} onContent Content@6f3676e7{HeapByteBufferR@4ded7649[p=1849,l=1876,c=8192,r=27]={POST /invoke HTTP...oding: gzip\r\n\r\n<<<{name: '\xE4\xB8\xAd\xE6\x96\x87', age: '28'}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}}

parseNext End but with a remaining=6316:

    -10
    [2019-04-19 11:29:19]10.24.238.107 content: 2019-04-19 03:29:19.273 [DEBUG][thread-qtp664457955-10] jetty.http.HttpParser - End============= s=END HeapByteBuffer@6ce4ba82[p=1876,l=8192,c=8192,r=6316]={POST /invoke HTTP...\x96\x87', age: '28'}<<<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>}

Finally exception in parseNext:

    Caused by: java.lang.IndexOutOfBoundsException at java.nio.Buffer.checkIndex(Buffer.java:540) ~[?:1.8.0_131] 
    at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139) ~[?:1.8.0_131] 
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1538) [ .jar:?] ... 44 more

Why seems parse 27 bytes okay , but got remain 6316 then cause exception. 
Even puzzle is why `HttpChanel onContent` happen between a `parseNext` invocation.

[EarlyEOF.txt](https://github.com/eclipse/jetty.project/files/3097051/EarlyEOF.txt)
