### ISSUE TITLE
Websocket Client test failure in 9.3.x

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#358]
Running org.eclipse.jetty.websocket.client.SessionTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.076 sec <<< FAILURE! - in org.eclipse.jetty.websocket.client.SessionTest
testBasicEcho_FromClient(org.eclipse.jetty.websocket.client.SessionTest)  Time elapsed: 0.075 sec  <<< FAILURE!
java.lang.AssertionError: (After Close) Open Sessions.size
Expected: is <0>
     but: was <1>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.eclipse.jetty.websocket.client.SessionTest.testBasicEcho_FromClient(SessionTest.java:107)

**Comment by joakime** [comment]
Not happening anymore
