### ISSUE TITLE
NPE in DumpableCollection

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#3587]
If the collection passed to DumpableCollection is null, an NPE results. Eg:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.jetty.util.component.DumpableCollection.dump(DumpableCollection.java:56)
	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:225)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dumpObjects(ContainerLifeCycle.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.dump(WebAppContext.java:1070)
	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:162)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dumpObjects(ContainerLifeCycle.java:717)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dump(ContainerLifeCycle.java:672)
	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:154)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dumpObjects(ContainerLifeCycle.java:717)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dump(ContainerLifeCycle.java:672)
	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:154)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dumpObjects(ContainerLifeCycle.java:717)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dump(ContainerLifeCycle.java:672)
	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:154)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dumpObjects(ContainerLifeCycle.java:717)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dump(ContainerLifeCycle.java:672)
	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:154)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dumpObjects(ContainerLifeCycle.java:717)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dump(ContainerLifeCycle.java:672)
	at org.eclipse.jetty.util.component.Dumpable.dumpObjects(Dumpable.java:154)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dumpObjects(ContainerLifeCycle.java:717)
	at org.eclipse.jetty.server.Server.dump(Server.java:693)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.dumpStdErr(ContainerLifeCycle.java:642)
	at org.eclipse.jetty.server.Server.doStart(Server.java:403)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
```

**Comment by janbartel** [comment]
For jetty-9.4.17 and beyond.
