### ISSUE TITLE
Very slow page load and missing resources when using HTTP/2 with Jetty 9.3.7

### ISSUE THREAD

**Issue by ofrias** [eclipse/jetty.project#362]
We have found an issue when remotely loading pages using HTTP/2 in Jetty.  The page takes tens of seconds to load, and when it finishes it usually is missing resources (CSS and/or images).

The issue is quite frequent, you can reproduce it by opening a new window to the test page which is just plain HTML with several img tags.  It happens after just a few tries, usually less than 10.  It looks like it is more frequent in pages with many images.

You can reproduce the issue with 2 remote computers with this setup:

Server running:
- Jetty 9.3.7
- JDK 1.8.0_66

Remote client:
- Firefox 44.0.2 for example (also happens with Chrome)

It is very important to run the client remotely, not from the same computer.  The issue is not present when the client is local.  We have reproduced it through different networks and with different computers, but not locally.

We assume that Jetty is installed in /usr/local/jetty/ and Java in /usr/local/java8/

Steps to reproduce:

1) Prepare the server computer:

```
mkdir ~/jettytest/
cd ~/jettytest/
mkdir webapps
cp -a /usr/local/jetty/demo-base/webapps/ROOT webapps/mytest
emacs webapps/mytest/index.html
```

Edit the file adding these lines after `<h1>Welcome to Jetty 9</h1>`  :

  ```
    <img src="images/jetty-header2.jpg"/>
    <img src="images/jetty-header3.jpg"/>
    <img src="images/jetty-header4.jpg"/>
    <img src="images/jetty-header5.jpg"/>
    <img src="images/jetty-header6.jpg"/>
    <img src="images/jetty-header7.jpg"/>
    <img src="images/jetty-header8.jpg"/>
    <img src="images/jetty-header9.jpg"/>
    <img src="images/jetty-header10.jpg"/>
    <img src="images/jetty-header11.jpg"/>
    <img src="images/jetty-header12.jpg"/>
```
    
Copy all the new images:

```
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header2.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header3.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header4.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header5.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header6.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header7.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header8.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header9.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header10.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header11.jpg
cp webapps/mytest/images/jetty-header.jpg webapps/mytest/images/jetty-header12.jpg

```

Prepare Jetty:

`/usr/local/java8/bin/java -jar /usr/local/jetty/start.jar --module=server --module=deploy --module=http2 --create-files`

Execute Jetty:

`/usr/local/java8/bin/java -jar /usr/local/jetty/start.jar --module=server --module=deploy --module=http2`

2) Now, from the client computer:

2.1) Open Firefox.

2.2) Open a "Private Window" pointing to: `https://<SERVER_IP>:8443/mytest/`

2.3) If page loads normally, close the Private Window and go to 2.2.  It is very important to close the previous Private Window to force the HTTP/2 connection close.

You should be able to reproduce the issue in just a few tries.

In the server this Exception is logged several times (pointing to the CSS and/or to the images):

```
2016-02-24 19:21:24.133:WARN:oejs.HttpChannel:qtp1896277646-16: https://<SERVER_IP>:8443/mytest/images/jetty-header6.jpg
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427)
	at org.eclipse.jetty.http2.HTTP2Session.terminate(HTTP2Session.java:910)
	at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:929)
	at org.eclipse.jetty.http2.HTTP2Session.onIdleTimeout(HTTP2Session.java:874)
	at org.eclipse.jetty.http2.HTTP2Connection.onIdleExpired(HTTP2Connection.java:118)
	at org.eclipse.jetty.io.ssl.SslConnection.onIdleExpired(SslConnection.java:176)
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:162)
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-02-24 19:21:24.134:WARN:oejs.HttpChannel:qtp1896277646-29: https://<SERVER_IP>:8443/mytest/jetty.css
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:427)
	at org.eclipse.jetty.http2.HTTP2Session.terminate(HTTP2Session.java:910)
	at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:929)
	at org.eclipse.jetty.http2.HTTP2Session.onIdleTimeout(HTTP2Session.java:874)
	at org.eclipse.jetty.http2.HTTP2Connection.onIdleExpired(HTTP2Connection.java:118)
	at org.eclipse.jetty.io.ssl.SslConnection.onIdleExpired(SslConnection.java:176)
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:162)
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

I add more information in case it could help to find the route cause of the issue...  We initially detected the issue in a [Jetty setup with HAProxy](http://www.eclipse.org/jetty/documentation/current/http2-configuring-haproxy.html).  In our setup we have 2 servers, one with HAProxy + Jetty, and the other one just with Jetty.  The ping between them is just about 0.2 ms.  We detected the issue in the HTTP/2 requests sent by HAProxy to the other server.  The requests that were served in the same server did not experience the issue.  We tried moving HAProxy to the other server and then the Jetty with the issue was the other one.  So the issue only arises when there is a network involved.  Although in this setup the only network causing the problem was the one between HAProxy and Jetty.  If the connection between HAProxy and Jetty was local there was no problem, even if the browser was remote.

**Comment by sbordet** [comment]
Thanks for this report.

I understand correctly that HAProxy is out of the picture for this issue, and that you were able to reproduce it with a browser and Jetty alone, albeit on 2 different machines ?

The stack trace reported only shows that the connection went idle and timed out.

Can you please enable DEBUG logging for `org.eclipse.jetty.http2`, re-run the test case, get the failure and attach the server logs ?

Thanks !

**Comment by ofrias** [comment]
Yes, that's right, we initially discovered the issue in a setup with HAProxy, but we are able to reproduce it easily with just a standalone Jetty serving a static page and a remote browser (Chrome or Firefox).  For example accessing Jetty from a smartphone connected to the local WiFi.

As I explained in the mailing list, we can reproduce it also with JDK 1.8.0_72 and ALPN 8.1.7.v20160121.

I attach a log running Jetty with `--module=logging -Dorg.eclipse.jetty.http2.LEVEL=DEBUG`

The page load that fails (the second in the log I think) starts at 2016-02-29 19:20:13.985

In this case the visible symptoms were that page load halted while loading an image, and after many seconds page load finished leaving one of the images with the broken image icon in the display.

[2016_02_29.stderrout.log.gz](https://github.com/eclipse/jetty.project/files/151522/2016_02_29.stderrout.log.gz)

**Comment by sbordet** [comment]
@ofrias I was able to reproduce the issue, stay tuned for news.

**Comment by sbordet** [comment]
The issue was related to the selector notifying both read ready and write ready
We were first calling `fillable()` and then `completeWrite()`. Calling `fillable()` may have resulted in read from network, parse and call the application which could have performed a blocking write, so that the thread never returned from `fillable()` to then call `completeWrite()`.

This is now fixed; we first call `completeWrite()`, which never calls into application code, and then `fillable()`.

Thanks for the detailed report and logs !

**Comment by ofrias** [comment]
Are you including the fix into 9.3.8 ?

**Comment by sbordet** [comment]
Yes, it's going to be in the final 9.3.8.

**Comment by ofrias** [comment]
OK, thanks a lot for your support!
