### ISSUE TITLE
Broken pipe exceptions connecting to Jetty with SSL client auth

### ISSUE THREAD

**Issue by andymc12** [eclipse/jetty.project#3656]
In testing the MicroProfile Rest Client, we ran into an issue with certain versions of Jetty where we were not able to connect when the Jetty server was configured to use SSL client auth.

You can see the test cases in use here:
https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/ssl/SslMutualTest.java

These tests use the MP Rest Client to connect to the Jetty server (to test whether it can connect to a remote server with client auth), but I wrote a standalone Java app that also attempts to connect - this also fails:
https://gist.github.com/andymc12/25e7a4e445a1bc7e284717b3c1bf6f9a

My colleague determined that this worked with Jetty version `9.4.14.v20181114`, but failed with version `9.4.18.v20190429` - so possibly it was broken somewhere in between?

Here is the stack trace from the client side:
```
Exception in thread "main" javax.net.ssl.SSLException: readHandshakeRecord
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1072)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
	at TestSSLwithStores.main(TestSSLwithStores.java:38)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
	at java.base/sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:89)
	at java.base/sun.security.ssl.Finished$T13FinishedProducer.onProduceFinished(Finished.java:664)
	at java.base/sun.security.ssl.Finished$T13FinishedProducer.produce(Finished.java:643)
	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
	at java.base/sun.security.ssl.Finished$T13FinishedConsumer.onConsumeFinished(Finished.java:969)
	at java.base/sun.security.ssl.Finished$T13FinishedConsumer.consume(Finished.java:848)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	... 5 more
```

This was run using Java 11, but also failed when we tested with Java 8.

**Comment by joakime** [comment]
This may be related to issue #3648  is there any way I can convince you to test the branch that PR #3651 is sitting on (branch `jetty-9.4.x-3648-websocket-policy-based-ssl`)?

**Comment by sbordet** [comment]
You are probably hitting #3454, and here's the explanation why we chose to do that: https://github.com/eclipse/jetty.project/issues/3454#issuecomment-472007812.

Should be enough that you either use Jetty 9.4.18's `SslContextFactory.Server` to configure the server side, or you can still use `SslContextFactory` but you have to explicitly call `sslContextFactory.setEndpointIdentificationAlgorithm(null)`.

Please report back if that fixed your problem. Thanks!

**Comment by andymc12** [comment]
@sbordet Thanks for the quick response!
When I add `sslContextFactory.setEndpointIdentificationAlgorithm(null)`, that resolves the problem.

Thanks again!

**Comment by sbordet** [comment]
@andymc12 thanks for the feedback!
