### ISSUE TITLE
Jetty 9.2 AbstractSessionManager removeSession method calls getCreationTime on invalid sessions

### ISSUE THREAD

**Issue by hoomanv** [eclipse/jetty.project#3674]
There is a bug in jetty 9.2 AbstractSessionManager removeSession method.

The scavenger thread in HashSessionManager periodically scans sessions to evict stale sessions out of memory. Once it finds one, timeout() will be invoked on it. Eventually the removeSession method of AbstractSessionManager will be invoked and at line 763 an IllegalStateException occurs.

Line 763:
`_sessionTimeStats.set(round((System.currentTimeMillis() - session.getCreationTime())/1000.0));`

`session.getCreationTime()` is the reason. It shouldn't be called on an invalid session.

Exception logs:
<pre>19:48:59.355 [org.eclipse.jetty.server.session.HashSessionManager@1d6944d8Timer] WARN  org.eclipse.jetty.server.session.HashedSession - Problem de-idling session 1mmkyko7ua015rvc4out721f7
java.io.FileNotFoundException: 1mmkyko7ua015rvc4out721f7
	at org.eclipse.jetty.server.session.HashedSession.deIdle(HashedSession.java:218)
	at org.eclipse.jetty.server.session.HashedSession.checkValid(HashedSession.java:78)
	at org.eclipse.jetty.server.session.AbstractSession.getCreationTime(AbstractSession.java:162)
	at org.eclipse.jetty.server.session.AbstractSessionManager.removeSession(AbstractSessionManager.java:763)
	at org.eclipse.jetty.server.session.AbstractSession.timeout(AbstractSession.java:302)
	at org.eclipse.jetty.server.session.HashSessionManager.scavenge(HashSessionManager.java:358)
	at org.eclipse.jetty.server.session.HashSessionManager$Scavenger.run(HashSessionManager.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19:48:59.355 [org.eclipse.jetty.server.session.HashSessionManager@1d6944d8Timer] WARN  org.eclipse.jetty.server.session - Problem scavenging sessions
java.lang.IllegalStateException: null
	at org.eclipse.jetty.server.session.AbstractSession.checkValid(AbstractSession.java:104)
	at org.eclipse.jetty.server.session.HashedSession.checkValid(HashedSession.java:79)
	at org.eclipse.jetty.server.session.AbstractSession.invalidate(AbstractSession.java:324)
	at org.eclipse.jetty.server.session.HashedSession.deIdle(HashedSession.java:236)
	at org.eclipse.jetty.server.session.HashedSession.checkValid(HashedSession.java:78)
	at org.eclipse.jetty.server.session.AbstractSession.getCreationTime(AbstractSession.java:162)
	at org.eclipse.jetty.server.session.AbstractSessionManager.removeSession(AbstractSessionManager.java:763)
	at org.eclipse.jetty.server.session.AbstractSession.timeout(AbstractSession.java:302)
	at org.eclipse.jetty.server.session.HashSessionManager.scavenge(HashSessionManager.java:358)
	at org.eclipse.jetty.server.session.HashSessionManager$Scavenger.run(HashSessionManager.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)</pre>

**Comment by janbartel** [comment]
It looks to me what has happened is that the session has been idled - ie saved to a file, and then subsequently its maxInactiveInterval has passed, so the scavenger finds it and attempts to remove it. Before it can be removed, the idled session needs to be fully restored, but the file to which it was persisted no longer exists.   Note that jetty does not mark the session as invalid until AFTER getCreationTime is called, so it is not the case that getCreationTime is being called on an invalid session

So one explanation is that you have some job that is deleting old session files?

In any case, jetty-9.2 is end-of-life, so I encourage you to update to jetty-9.4.  Alternatively, if you can debug this further and come up with a patch, then we would be happy to evaluate the patch.

**Comment by hoomanv** [comment]
It is the scavenger thread that is deleting the old session files.
This stack trace shows the course of actions taken after the scavenger thread finds a stale session.

<pre>at org.eclipse.jetty.server.session.AbstractSession.access(AbstractSession.java:281)
at org.eclipse.jetty.server.session.HashedSession.deIdle(HashedSession.java:207)
at org.eclipse.jetty.server.session.HashedSession.checkValid(HashedSession.java:78)
at org.eclipse.jetty.server.session.AbstractSession.invalidate(AbstractSession.java:324)
at org.eclipse.jetty.server.session.AbstractSession.access(AbstractSession.java:278)
at org.eclipse.jetty.server.session.HashedSession.deIdle(HashedSession.java:207)
at org.eclipse.jetty.server.session.HashedSession.checkValid(HashedSession.java:78)
at org.eclipse.jetty.server.session.AbstractSession.invalidate(AbstractSession.java:324)
at org.eclipse.jetty.server.session.AbstractSession.access(AbstractSession.java:278)
at org.eclipse.jetty.server.session.HashedSession.deIdle(HashedSession.java:207)
at org.eclipse.jetty.server.session.HashedSession.checkValid(HashedSession.java:78)
at org.eclipse.jetty.server.session.AbstractSession.getCreationTime(AbstractSession.java:162)
at org.eclipse.jetty.server.session.AbstractSessionManager.removeSession(AbstractSessionManager.java:763)
at org.eclipse.jetty.server.session.AbstractSession.timeout(AbstractSession.java:302)
at org.eclipse.jetty.server.session.HashSessionManager.scavenge(HashSessionManager.java:358)
at org.eclipse.jetty.server.session.HashSessionManager$Scavenger.run(HashSessionManager.java:84)
at java.util.concurrent.Executors$RunnableAdapter.call
at java.util.concurrent.FutureTask.run
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run
at java.util.concurrent.ThreadPoolExecutor.runWorker
at java.util.concurrent.ThreadPoolExecutor$Worker.run
at java.lang.Thread.run</pre>

Look how many times `deIdle` and `access` methods are called. Something bizarre is happening there.
Session file is deleted in the 2nd call to `deIdle`.

I have no clue how to patch it the right way, but just to get around this I have extended the HashSessionManager and overridden the `removeSession` and switched the call to `session.getCreationTime()` with a reflective call to read `AbstractSession._created` without incurring a `checkValid` invocation.
