### ISSUE TITLE
SharedBlockingCallback$BlockerTimeoutException

### ISSUE THREAD

**Issue by SandKing123** [eclipse/jetty.project#3695]
The version I use is 9.2.10.v20150310.This exception sometimes occurs when returned data is written.
Here is stack trace in the exception object.

java.lang.IllegalStateException: org.eclipse.jetty.util.SharedBlockingCallback$BlockerTimeoutException
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.failed(SharedBlockingCallback.java:184)
        at org.eclipse.jetty.server.HttpChannel$CommitCallback.failed(HttpChannel.java:853)
        at org.eclipse.jetty.io.AbstractConnection.failedCallback(AbstractConnection.java:115)
        at org.eclipse.jetty.server.HttpConnection.access$1000(HttpConnection.java:48)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.onCompleteFailure(HttpConnection.java:740)
        at org.eclipse.jetty.util.IteratingCallback.failed(IteratingCallback.java:422)
        at org.eclipse.jetty.io.WriteFlusher$PendingState.fail(WriteFlusher.java:261)
        at org.eclipse.jetty.io.WriteFlusher.onFail(WriteFlusher.java:464)
        at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:482)
        at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:109)
        at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:116)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.close(SslConnection.java:897)
        at org.eclipse.jetty.server.HttpConnection.abort(HttpConnection.java:758)
        at org.eclipse.jetty.server.HttpChannel.abort(HttpChannel.java:829)
        at org.eclipse.jetty.server.HttpConnection$HttpChannelOverHttp.abort(HttpConnection.java:582)
        at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:171)
        at org.eclipse.jetty.server.HttpWriter.close(HttpWriter.java:49)
        at java.io.PrintWriter.close(PrintWriter.java:339)
        at org.eclipse.jetty.server.Response.closeOutput(Response.java:1012)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:421)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.util.SharedBlockingCallback$BlockerTimeoutException
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:216)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:136)
        at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:166)
        ... 9 more

**Comment by sbordet** [comment]
@SandKing123 Jetty 9.2.10 is very outdated.
Please upgrade to latest 9.2.x version, or better yet, upgrade to latest 9.4.x.

**Comment by SandKing123** [comment]
@sbordet  thanks. I've upgraded latest 9.4.x.
