### ISSUE TITLE
NPE from WebAppClassLoader during CDI

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3736]
The stack seen in logging ...

```
2019-06-05 07:29:28.053:WARN:oejw.ClasspathPattern:weld-worker-4: 
java.lang.NullPointerException
	at org.eclipse.jetty.webapp.ClasspathPattern.match(ClasspathPattern.java:690)
	at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:829)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:557)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.lang.Package.getPackageInfo(Package.java:375)
	at java.lang.Package.getAnnotation(Package.java:390)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Package.isAnnotationPresent(Package.java:400)
	at org.jboss.weld.util.Beans.isPackageVetoed(Beans.java:561)
	at org.jboss.weld.util.Beans.isVetoed(Beans.java:550)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:75)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:94)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:61)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:58)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The class being loaded when this occurs is `org.eclipse.jetty.test.package-info`
When the `WebAppContext` / `WebAppClassLoader` is trying to get the annotated package info, it interrogates the webapp classloader first, finds it, and then the parent and it returns null.

The `parent_class` below is null. (an obvious classloader violation, as it should have thrown a `ClassNotFoundException`)

https://github.com/eclipse/jetty.project/blob/b96b4bfffe7a444481fc9a239084ef2c3d2c7f66/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppClassLoader.java#L552-L567

The stack captured in the IDE
```
match:690, ClasspathPattern (org.eclipse.jetty.webapp)
isServerClass:829, WebAppContext (org.eclipse.jetty.webapp)
loadClass:557, WebAppClassLoader (org.eclipse.jetty.webapp)
loadClass:357, ClassLoader (java.lang)
forName0:-1, Class (java.lang)
forName:348, Class (java.lang)
getPackageInfo:375, Package (java.lang)
getAnnotation:390, Package (java.lang)
isAnnotationPresent:258, AnnotatedElement (java.lang.reflect)
isAnnotationPresent:400, Package (java.lang)
isPackageVetoed:561, Beans (org.jboss.weld.util)
isVetoed:550, Beans (org.jboss.weld.util)
loadAnnotatedType:75, AnnotatedTypeLoader (org.jboss.weld.bootstrap)
loadAnnotatedType:60, AnnotatedTypeLoader (org.jboss.weld.bootstrap)
addClass:94, BeanDeployer (org.jboss.weld.bootstrap)
doWork:61, ConcurrentBeanDeployer$1 (org.jboss.weld.bootstrap)
doWork:58, ConcurrentBeanDeployer$1 (org.jboss.weld.bootstrap)
call:62, IterativeWorkerTaskFactory$1 (org.jboss.weld.executor)
call:55, IterativeWorkerTaskFactory$1 (org.jboss.weld.executor)
run$$$capture:266, FutureTask (java.util.concurrent)
run:-1, FutureTask (java.util.concurrent)
 - Async stack trace
<init>:132, FutureTask (java.util.concurrent)
newTaskFor:102, AbstractExecutorService (java.util.concurrent)
invokeAll:236, AbstractExecutorService (java.util.concurrent)
invokeAllAndCheckForExceptions:43, AbstractExecutorServices (org.jboss.weld.executor)
invokeAllAndCheckForExceptions:51, AbstractExecutorServices (org.jboss.weld.executor)
addClasses:58, ConcurrentBeanDeployer (org.jboss.weld.bootstrap)
createClasses:224, BeanDeployment (org.jboss.weld.bootstrap)
startInitialization:398, WeldStartup (org.jboss.weld.bootstrap)
startInitialization:76, WeldBootstrap (org.jboss.weld.bootstrap)
initialize:191, WeldServletLifecycle (org.jboss.weld.environment.servlet)
onStartup:62, EnhancedListener (org.jboss.weld.environment.servlet)
callStartup:140, ContainerInitializer (org.eclipse.jetty.plus.annotation)
doStart:64, ServletContainerInitializersStarter (org.eclipse.jetty.annotations)
start:68, AbstractLifeCycle (org.eclipse.jetty.util.component)
startContext:347, ServletContextHandler (org.eclipse.jetty.servlet)
startWebapp:1497, WebAppContext (org.eclipse.jetty.webapp)
startContext:1459, WebAppContext (org.eclipse.jetty.webapp)
doStart:854, ContextHandler (org.eclipse.jetty.server.handler)
doStart:278, ServletContextHandler (org.eclipse.jetty.servlet)
doStart:545, WebAppContext (org.eclipse.jetty.webapp)
start:68, AbstractLifeCycle (org.eclipse.jetty.util.component)
start:167, ContainerLifeCycle (org.eclipse.jetty.util.component)
start:418, Server (org.eclipse.jetty.server)
doStart:110, ContainerLifeCycle (org.eclipse.jetty.util.component)
doStart:113, AbstractHandler (org.eclipse.jetty.server.handler)
doStart:382, Server (org.eclipse.jetty.server)
start:68, AbstractLifeCycle (org.eclipse.jetty.util.component)
startServer:110, CDIWebAppTest (org.eclipse.jetty.test)
invoke0:-2, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
invokeMethod:628, ReflectionUtils (org.junit.platform.commons.util)
invoke:117, ExecutableInvoker (org.junit.jupiter.engine.execution)
```

**Comment by joakime** [comment]
Opened PR #3775

**Comment by amir-khassaia** [comment]
Hi @joakime 
I see another similar variant of this which doesnt look like will be addressed by the commit

In my case (9.4.19) the parent class is not null so we proceed to call `isServerClass`,
eventually getting to 
`org.eclipse.jetty.webapp.ClasspathPattern#match(java.lang.Class<?>)`

This then calls `TypeUtil.getLocationOfClass(clazz)` via lazy supplier evaluation. 
The class in question is actually a synthetic JDK proxy (eg "com.sun.proxy.$Proxy150") which of course shouldnt load but it doesnt get short circuited and ends up as NPE in `org.eclipse.jetty.webapp.ClasspathPattern.ByLocation#test` as URI is null because location returned by getLocation call was null.

Any chance to have this included too as its causing undue alarm in logs?

**Comment by amir-khassaia** [comment]
Sample stack trace just in case
```
          at org.eclipse.jetty.webapp.ClasspathPattern$ByLocation.test(ClasspathPattern.java:355)
	  at org.eclipse.jetty.webapp.ClasspathPattern$ByLocationOrModule.test(ClasspathPattern.java:445)
	  at org.eclipse.jetty.webapp.ClasspathPattern$ByLocationOrModule.test(ClasspathPattern.java:437)
	  at org.eclipse.jetty.util.IncludeExcludeSet.isIncludedAndNotExcluded(IncludeExcludeSet.java:176)
	  at org.eclipse.jetty.webapp.ClasspathPattern.combine(ClasspathPattern.java:728)
	  at org.eclipse.jetty.webapp.ClasspathPattern.match(ClasspathPattern.java:690)
	  at org.eclipse.jetty.webapp.WebAppContext.isServerClass(WebAppContext.java:829)
	  at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:557)
	  at java.lang.ClassLoader.loadClass(Unknown Source:-1)
	  at java.lang.Class.forName0(Unknown Source:-1)
	  at java.lang.Class.forName(Unknown Source:-1)
	  at org.aspectj.weaver.reflect.ReflectionBasedReferenceTypeDelegateFactory.createDelegate(ReflectionBasedReferenceTypeDelegateFactory.java:38)
	  at org.aspectj.weaver.reflect.ReflectionWorld.resolveDelegate(ReflectionWorld.java:195)
	  at org.aspectj.weaver.World.resolveToReferenceType(World.java:486)
	  at org.aspectj.weaver.World.resolve(World.java:321)
	  at org.aspectj.weaver.World.resolve(World.java:231)
	  at org.aspectj.weaver.World.resolve(World.java:436)
	  at org.aspectj.weaver.internal.tools.PointcutExpressionImpl.couldMatchJoinPointsInType(PointcutExpressionImpl.java:83)
	  at org.springframework.aop.aspectj.AspectJExpressionPointcut.matches(AspectJExpressionPointcut.java:260)
	  at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:220)
	  at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:279)
	  at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:311)
	  at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:119)
	  at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:89)
	  at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:70)
	  at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:343)
	  at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:295)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:421)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1634)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	  at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	  at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1197)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	  at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	  at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1197)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	  at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	  at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1197)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
	  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	  at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	  at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	  at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	  at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:959)
	  at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	  at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:924)
	  at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
	  at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	  at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	  at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854)
	  at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	  at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	  at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:406)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	  at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:256)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	  at org.eclipse.jetty.server.Server.start(Server.java:418)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	  at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
```

**Comment by gregw** [comment]
@amir-khassaia I believe we already have fixes on their way that will address this 8d59302978d8107bfce40754ead29986940b5f94:
 + [This change](https://github.com/eclipse/jetty.project/commit/8d59302978d8107bfce40754ead29986940b5f94#diff-e1218e49f50adb871a5b213577ddeb36R602) improves the way we work out a classes location, so the chances of it being null are less.
+ [This change](https://github.com/eclipse/jetty.project/commit/8d59302978d8107bfce40754ead29986940b5f94#diff-3891c2e25e89242677a891510b476101R729) protects against a null URI

This will be in the next release, but it would be great if you could test against your use-case before then

**Comment by amir-khassaia** [comment]
@gregw Thanks for the update.
Had a look at the changes and perhaps I'm tempting fate but I can see that the change to not call
`Boolean byLocation = locations.isIncludedAndNotExcluded(location.get());`
if the URI is null out of location.get will fix the issue (ie. we dont do any work and short circuit on such location).
That is the last change in your reply.
What are the timelines for next 9.4.x release?

**Comment by gregw** [comment]
@amir-khassaia currently undecided on our next release date... so that makes it a minimum of 2 weeks away.  I would not expect it to be more than 4 weeks.

**Comment by amir-khassaia** [comment]
Thanks @gregw

**Comment by amir-khassaia** [comment]
Feel free to close this.
