### ISSUE TITLE
WebSocketConnectionStatsTest test uses port 8080

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#3762]
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.419 s <<< FAILURE! - in org.eclipse.jetty.websocket.tests.WebSocketConnectionStatsTest
[ERROR] echoStatsTest  Time elapsed: 0.414 s  <<< ERROR!
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
	at org.eclipse.jetty.websocket.tests.WebSocketConnectionStatsTest.start(WebSocketConnectionStatsTest.java:152)
Caused by: java.net.BindException: Address already in use
	at org.eclipse.jetty.websocket.tests.WebSocketConnectionStatsTest.start(WebSocketConnectionStatsTest.java:152)
```

**Comment by lachlan-roberts** [comment]
some of the tests I have written the port is being set explicitly to 8080, so it will fail if something else is using the port, I will make a PR to fix this
