### ISSUE TITLE
Failed startup of context o.e.j.w.WebAppContext@7c29daf3

### ISSUE THREAD

**Issue by sarabsing** [eclipse/jetty.project#3781]

**Comment by sarabsing** [comment]
I have created Docker Image and run that image

My docker file look like below :

FROM gcr.io/google-appengine/jetty
ADD target/Tim-Carry-legacy.war $JETTY_BASE/webapps/root.war
WORKDIR $JETTY_BASE

RUN java -jar $JETTY_HOME/start.jar --approve-all-licenses --add-to-startd=jmx,stats && chown -R jetty:jetty $JETTY_BASE

EXPOSE 8080

**Comment by joakime** [comment]
Do you have any logs or other details on how it failed?
All your jetty Docker image does is setup the $JETTY_BASE directory to work with jmx and stats module then exit.

**Comment by sarabsing** [comment]
Failed startup of context o.e.j.w.WebAppContext@7c29daf3{Tim-Carry,/,file:///tmp/jetty-0.0.0.0-8080-root.war-_-any-6174782283207811127.dir/webapp/,UNAVAILABLE}{/root.war}
java.lang.NullPointerException: Operation not allowed in a thread that is neither the original request thread nor a thread created by ThreadManager
	at com.google.appengine.api.LifecycleManager.currentAppVersionId(LifecycleManager.java:92)
	at com.google.appengine.api.LifecycleManager.setShutdownHook(LifecycleManager.java:40)
	at co.ritual.shutdownmanager.appengine.AppEngineShutdownManager.addShutdownHook(AppEngineShutdownManager.java:24)
	at co.ritual.starhopper.listeners.TimCarryContextListener.initialized(StarhopperContextListener.java:24)
	at co.ritual.starhopper.listeners.ConsumerAwareContextListener.contextInitialized(ConsumerAwareContextListener.java:25)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:957)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:922)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:256)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)

**Comment by sarabsing** [comment]
Hi,

Do you know what can be reason

**Comment by sarabsing** [comment]
Hi @joakime , i am still struggling with the above error. Did you have anything to specify

**Comment by joakime** [comment]
Looks like you are trying to use Google App Engine.
That requires you run that docker image on their infrastructure.
You will not be able to run that image anywhere else.
If you want to run Google App Engine locally, then you have to stick with the various Development App Server options.

**Comment by joakime** [comment]
The error you are getting is Google App Engine's way of saying that you are attempting to run Google App Engine stuff outside of the Google Infrastructure.
This is not a Jetty error.

**Comment by sarabsing** [comment]
Thanks @joakime . It means even if i used jetty latest version(and not Google App Engine) and run locally still it will not work

**Comment by joakime** [comment]
If you want to run locally, you can use straight Jetty.  Even the docker image - https://hub.docker.com/_/jetty

If you want to run GAE locally, you can use the GAE Development App Server.

If you want to run GAE in a docker container, you need to run that docker container on google infrastructure.

**Comment by gregw** [comment]
The base image you are using is primarily intended for running in the GAE flex environment.  However it typically can be run locally so long as any google APIs used are correctly configured for remote access.
You can startup the base image locally with something like:
```
docker run -it --rm -e HEAP_SIZE_MB=4096 gcr.io/google-appengine/jetty
```

However, I think your error is something else! As  you can see in this part of your stack:
```
at com.google.appengine.api.LifecycleManager.setShutdownHook(LifecycleManager.java:40)
at co.ritual.shutdownmanager.appengine.AppEngineShutdownManager.addShutdownHook(AppEngineShutdownManager.java:24)
at co.ritual.starhopper.listeners.TimCarryContextListener.initialized(StarhopperContextListener.java:24)
at co.ritual.starhopper.listeners.ConsumerAwareContextListener.contextInitialized(ConsumerAwareContextListener.java:25)
at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:957)
```
you have  context listener trying to register an AppEngine shutdown hook.   Contexts have no need to do that as they are given pre shutdown warning events via context listeners.

Moreover, I think the google LifecycleManager API is for the standard GAE runtime and not the flex.

So I suggest you have a look at TimCarryContextListener and see what it is doing and why!

**Comment by janbartel** [comment]
Looks like this question has been addressed, so I am closing this issue. If you feel there is something that jetty needs to investigate, please reopen supplying all information.
