### ISSUE TITLE
Jetty client sometimes returns EOFException instead of SSLHandshakeException on certificate errors.

### ISSUE THREAD

**Issue by YutaHiguchi-bsn** [eclipse/jetty.project#3787]
When jetty client connect to a HTTPS server running with self-signed certificate, 
it sometime returns `EOFException` instead of `SSLHandshakeException` from `Result#getFailure()`, which makes it challenging to diagnose the root cause of the failure.  

Following gist has reproducer code and debug log trace on failing schenario returning EOFException:
 https://gist.github.com/YutaHiguchi-bsn/dd33be6d6ed6dc3932eb9b6800535f2e

Internally `SSLHandshakeException` is observed and logged by Jetty,
```
12:30:12.353 DEBUG [o.e.j.i.s.SslConnection:HttpClient@3043fe0e-20] SslConnection@29e268b1::SocketChannelEndPoint@34b7c29b{/10.2.0.117:8443<->/10.100.12.56:56288,OPEN,fill=-,flush=-,to=27/0}{io=0/0,kio=0,kro=1}->SslConnection@29e268b1{NEED_WRAP,eio=475/-1,di=-1,fill=IDLE,flush=IDLE}~>DecryptedEndPoint@27cf4226{/10.2.0.117:8443<->/10.100.12.56:56288,OPEN,fill=FI,flush=C,to=2/0}=>HttpConnectionOverHTTP@7f8bd3f4(l:/10.100.12.56:56288 <-> r:/10.2.0.117:8443,closed=false)=>HttpChannelOverHTTP@75a27584(exchange=HttpExchange@5d6af988 req=PENDING/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@4fbf3c61(req=HEADERS,snd=SENDING,failure=null)[HttpGenerator@123c89c2{s=COMPLETING}],recv=HttpReceiverOverHTTP@3389fc02(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]
javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1165)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:890)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:349)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:670)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:527)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:128)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	... 3 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)
	... 21 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 27 common frames omitted
```

But in the user code, as log entry at `12:30:12.358` shows `Result` object only returns `EOFException`, which hides the detail from the user code, how establishing connection failed.

```
12:30:12.358 ERROR [o.p.d.r.c.j.Minimum:HttpClient@3043fe0e-21] send: 
java.io.EOFException: HttpConnectionOverHTTP@7f8bd3f4::DecryptedEndPoint@27cf4226{/10.2.0.117:8443<->/10.100.12.56:56288,CLOSED,fill=-,flush=C,to=9/0}
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:338)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:209)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:147)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:144)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

Note that there seems to be some kind of race condition, which is causing this issue.
So you may need to run the reproducer multiple times.

I mainly use JDK 8 with latest macOS when I first encountered this issue. Switched between AdoptOpenJDK binary, Corretto, Oracle including JDK11 and getting similar behavior.

Original [thread](https://www.eclipse.org/lists/jetty-users/msg08925.html) at jetty-users mailing list

**Comment by gaoxingliang** [comment]
We encounter similar case is: the remote connection is broken before sent back the certificates.
I tried multiple times, it’s not reproduced.

**Comment by sbordet** [comment]
@YutaHiguchi-bsn would you be able to build and test #4126, which has a fix for this issue?

**Comment by YutaHiguchi-bsn** [comment]
@sbordet Thanks, I can confirm that fixed the issue!
I had the reproducer running in tight loop for couple minutes, it passed 20,000 rounds without receiving single EOFException.

Thanks for the fix!
