### ISSUE TITLE
Submit PR for weld to use non-deprecated Decorator

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3803]
Starting in Jetty 10.0.x the old (long ago deprecated) `org.eclipse.jetty.servlet.ServletContextHandler$Decorator` interface has been removed.

This results in the following error when attempting to start Weld (version 2.4.5.Final)

```
java.lang.NoClassDefFoundError: org/eclipse/jetty/servlet/ServletContextHandler$Decorator
 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
 	at java.base/java.security.AccessController.doPrivileged(Native Method)
 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
 	at org.eclipse.jetty.webapp.WebAppClassLoader.foundClass(WebAppClassLoader.java:649)
 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadAsResource(WebAppClassLoader.java:618)
 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:547)
 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
 	at org.jboss.weld.environment.jetty.JettyContainer.initialize(JettyContainer.java:74)
 	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:220)
 	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:62)
 	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
 	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:64)
 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1357)
 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:849)
 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:296)
```

We should prepare a PR for the weld project to use the replacement at `org.eclipse.jetty.util.Decorator`.
(A class that is also available in Jetty 9.4.x)

**Comment by joakime** [comment]
Closing, as @gregw submitted https://issues.jboss.org/browse/WELD-2587
