### ISSUE TITLE
XmlConfiguration odd behavior for numbers

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3805]
To demonstrate this odd behavior in `jetty-9.4.x` ...

Lets assume you have the following class ...

``` java
public class Pear {
    public static int price = 0;
}
```

If you have an XML that says ...

``` xml
<Configure class="demo.Pear">
    <Set name="price" type="int">42</Set>
</Configure>
```

Then the `price` value gets set to `42`.

But if you have an XML like any of the following ...

``` xml
<Configure class="demo.Pear">
    <Set name="price" type="int">42
    </Set>
</Configure>
```

``` xml
<Configure class="demo.Pear">
    <Set name="price" type="int">
    42</Set>
</Configure>
```

``` xml
<Configure class="demo.Pear">
    <Set name="price" type="int">
        42
    </Set>
</Configure>
```

... then the attempt to set the price fails with ...

```
2019-06-23 10:25:34.302:WARN:oejx.XmlConfiguration:main: Config error at <Set name="price" type="int">42|  </Set> java.lang.IllegalArgumentException: Can not set static int field demo.Pear.price to null value in file:///home/joakim/code/../pear.xml

java.lang.IllegalArgumentException: Can not set static int field demo.Pear.price to null value

	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeStaticIntegerFieldAccessorImpl.set(UnsafeStaticIntegerFieldAccessorImpl.java:78)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.setField(XmlConfiguration.java:742)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:620)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:506)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:400)
```

I would have expected that setting a number should trim and not care about whitespace around it.

**Comment by sbordet** [comment]
Missing call to `trim()`?

**Comment by gregw** [comment]
I'm fixing this in the reformat branches

**Comment by gregw** [comment]
I think these changes confuse the reformatting branches too much, so I have backed them out and they can be the subject of a PR once the reformatting is over.
