### ISSUE TITLE
Increase of CPU utilization after few days

### ISSUE THREAD

**Issue by michal-niklas** [eclipse/jetty.project#3852]
I have strange problems with service with embedded Jetty. Service works for 7 days, but after 6 days it started tu use more CPU than usually. I can see it on Zabbix monitoring charts. All tasks of my application are completed, so the only threads are system Java threads (garbage collector, compiler, logger), and Jetty thread pool. I saved some jstack traces and compare them, and I see one thing that may be the problem:

I have dumped Java thread infor and Jetty info in 2019-07-03. It is important, because when I finish serving any resource I rename this thread adding "ht_finished_[YYMMDDhhmmss]". In jstack dump I see thread working for some days:

```
time: 6 days, 3 hrs
"qtp792232038-1037-ht_finished-190627060547_/komunal-partner-as/isof/__sZeeiB0knnF9XcCceY9e__/lib/view/bootstrap/4.0/js/popper.min.js" #1037 prio=5 os_prio=0 cpu=787.64ms elapsed=528511.44s tid=0x00007f164004a800 nid=0x1346 waiting on condition  [0x00007f181fffd000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x...> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.3/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.3/AbstractQueuedSynchronizer.java:2081)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:219)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:754)
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:733)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:296)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:459)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:120)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:305)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:171)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:126)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:338)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)
   Locked ownable synchronizers:
	- None

```
I think this thread has some problem with sending response. I have three threads in this state.

Other threads that I marked as finished looks different:

```
time: 1:54 [hh:mm]   cpu: 8:23 [mm:ss]
"qtp792232038-55708-ht_finished-190703081730_/skb/isof/__sRSgjp671tacnZFNVD2s__/lib/view/photoswipe/default-skin/default-skin.css" #55708 prio=5 os_prio=0 cpu=502724.59ms elapsed=6886.88s tid=0x00007f1520127000 nid=0x6bcd waiting on condition  [0x00007f1683ffe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x...> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.3/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.3/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:656)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$800(QueuedThreadPool.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:720)
	at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)
   Locked ownable synchronizers:
	- None

```
Why this first thread serving popper.min.js is still working? How to stop it?

The same thread I can see on Jetty dump as:
`   +>1037 qtp792232038-1037-ht_finished-190627060547_/komunal-partner-as/isof/__sZeeiB0knnF9XcCceY9e__/lib/view/bootstrap/4.0/js/popper.min.js WAITING @ java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
`

You can see Jetty dump and jstack dump in attached zip file
[logs.zip](https://github.com/eclipse/jetty.project/files/3359226/logs.zip)

My server is running on dockerized Linux with:
Jetty: 9.4.14.v20181114
Java: 11.0.3 OpenJDK 64-Bit Server VM

**Comment by gregw** [comment]
I'm not familiar with Zabbix so can you please give a bit more information about what your dumbs are saying.  Specifically:
```
time: 6 days, 3 hrs
"qtp792232038-1037-ht_finished-190627060547_/komunal-partner-as/isof/__sZeeiB0knnF9XcCceY9e__/lib/view/bootstrap/4.0/js/popper.min.js" #1037 prio=5 os_prio=0 cpu=787.64ms elapsed=528511.44s tid=0x00007f164004a800 nid=0x1346 waiting on condition  [0x00007f181fffd000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x...> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.3/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.3/AbstractQueuedSynchronizer.java:2081)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:219)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:754)
        ...
```
Is that saying that thread `qtp792232038-1037-ht_finished-190627060547_` has been blocked `WAITING` for 6 days 3 hrs or that it has been running for 6 days 3 hrs?
If it has been blocked there, then it is unlikely to be the cause of CPU consumption (but still bad that it is blocked there for so long).

When and how do you do the rename to add the "ht_finished_[YYMMDDhhmmss]" suffix to the thread name?   How does this thread have that suffix when it is obviously not finished (it is still in `DefaultServlet.doGet` )?  What is the YYMMDDhhmmss that the dump was taken?

With regards to thread:
```
"qtp792232038-55708-ht_finished-190703081730_/skb/isof/__sRSgjp671tacnZFNVD2s__/lib/view/photoswipe/default-skin/default-skin.css" #55708 prio=5 os_prio=0 cpu=502724.59ms elapsed=6886.88s tid=0x00007f1520127000 nid=0x6bcd waiting on condition  [0x00007f1683ffe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x...> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.3/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.3/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:656)
        ...
```
That is our idle job poll, so you should see many threads there.   I note that the thread still has a "ht_finished-190703081730_" suffix, so that would be from the last time it was out of the pool.   To avoid confusion, you probably want to wrap the QTP so that when a thread leaves the pool it's suffix is removed and thus you don't see finished for a working thread.

What is your operating system?  We have had some problems lately with JVM select bugs on windows that have consumed CPU.

**Comment by michal-niklas** [comment]
1. Zabix is an OS/Network/application monitoring system that plots charts with various data like CPU utilization, load time, memory usage etc. I use it to monitor whole system and I saw strange increase of CPU utilization.

2. Info "_time: 6 days, 3 hrs_" is from jstack output "_elapsed=528511.44s_" translated to a more readable format:

`"qtp792232038-1037-ht_finished-190627060547_/.../js/popper.min.js" #1037 prio=5 os_prio=0 cpu=787.64ms elapsed=528511.44s tid=0x00007f164004a800 nid=0x1346 waiting on condition  [0x00007f181fffd000]
`
It is running for 6 days. I think it is also blocked for 6 days.

In jstack trace you can see 3 threads blocked in the same way for a long time:

```
time: 6 days, 8 hrs   cpu: 1 [s]
"qtp792232038-1037-ht_finished-190627060547_/komunal-partner-as/isof/__sZeeiB0knnF9XcCceY9e__/lib/view/bootstrap/4.0/js/popper.min.js" #1037 prio=5 os_prio=0 cpu=787.64ms elapsed=546914.93s tid=0x00007f164004a800 nid=0x1346 waiting on condition  [0x00007f181fffd000]

time: 4 days, 2 hrs   cpu: 0 [s]
"qtp792232038-22883-ht_finished-190629112545_/futuro/isof/__scNKtGB9dxaXb92qL58Z__/lib/view/bootstrap/4.0/js/popper.min.js" #22883 prio=5 os_prio=0 cpu=183.34ms elapsed=352831.49s tid=0x00007f152c446800 nid=0x6eb7 waiting on condition  [0x00007f1813ffe000]

time: 4 days, 2 hrs   cpu: 0 [s]
"qtp792232038-22885-ht_finished-190629112545_/futuro/isof/__scNKtGB9dxaXb92qL58Z__/lib/view/photoswipe/photoswipe.css" #22885 prio=5 os_prio=0 cpu=4.78ms elapsed=352831.49s tid=0x00007f14e4003800 nid=0x6eb9 waiting on condition  [0x00007f17d7ffd000]


```
Stacktraces of other threads that I think works normally (idle in the pool) looks like:

```
time: 4:01 [hh:mm]   cpu: 15:12 [mm:ss]
"qtp792232038-56770-ht_finished-190703132423_/emu-spk/isof/__swbaJrdYMLdHYDf814rM__/gif_schm/kopiuj_nieaktywny.png" #56770 prio=5 os_prio=0 cpu=911505.64ms elapsed=14492.85s tid=0x00007f17000a7800 nid=0x739a waiting on condition  [0x00007f16cdbfd000]
```



3. I rename thread in the _handle()_ method of my handler which extends _ResourceHandler_:

```
		...
		finally
			{
			String finished_thread_name = _thrdName + HT_FINISHED_POSTFIX + TimeFuns.CurDateTimeToStrPacked() + '_' + target;
			curr_thread.setName(finished_thread_name);
			}
		} // handle


```
4. I use dockerized Linux with OpenJDK 11.0.3. System info:

CentOS Linux release 7.4.1708 (Core)

Docker:

Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64

Docker build
FROM openjdk:11.0.3

**Comment by gregw** [comment]
Thanks for the extra info.... but still not enough sorry.

I don't see how those threads can be responsible for extra CPU usage - cpu=787.64ms elapsed=528511.44s  is less than a second of CPU over 6 days, so that thread is not causing it.   
I also still don't understand if that thread has been blocked there for 6 days or has been idle for 6 days and just recently been allocated to a blocking request.
If you think it has been blocked long term because of the finished suffix, that is probably because it is from a previous usage of that thread and it has been sitting in the thread pool idle for a long time,

Can you modify your handler to something like:
```java
		try
                {			
                        String started_thread_name = _thrdName + HT_FINISHED_POSTFIX + TimeFuns.CurDateTimeToStrPacked() + '_' + target;
			curr_thread.setName(started_thread_name);

                        // handle here
                        ...
                }
		finally
		{
			String finished_thread_name = _thrdName + HT_FINISHED_POSTFIX + TimeFuns.CurDateTimeToStrPacked() + '_' + target;
			curr_thread.setName(finished_thread_name);
		}
	} // handle
```


Then when the problem occurs, can you take multiple jstacks  a few seconds apart, so we can see the differences and help identify which threads really are active and which really are blocked long term.

I don't doubt you have a problem, but at the moment I don't really understand exactly your debug info, plus I can't line up your proposed diagnosis of threads stuck long term with high CPU usage.

**Comment by michal-niklas** [comment]
I will use your idea with renaming thread at start. Thank you.

I have jstack dump from 2019-07-03 08:17 and 2019-07-03 13:24. Thread `"qtp792232038-1037-ht_finished-190627060547_/komunal-partner-as/isof/__sZeeiB0knnF9XcCceY9e__/lib/view/bootstrap/4.0/js/popper.min.js"` is in both.

I can see they differs in 2 places:

1. elapsed time:
 ```
#1037 prio=5 os_prio=0 cpu=787.64ms elapsed=528511.44s tid=0x00007f164004a800 nid=0x1346 waiting on condition  [0x00007f181fffd000]
 #1037 prio=5 os_prio=0 cpu=787.64ms elapsed=546914.93s tid=0x00007f164004a800 nid=0x1346 waiting on condition  [0x00007f181fffd000]

```
2. line with parking info (identifier):
```
- parking to wait for  <0x000000030a69c410> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
- parking to wait for  <0x0000000307db96c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
[logs.zip]

```

In attachment there is zip with Jetty info, jstack traces from the morning and from the afternoon, and both jstack traces sorted by elapsed time (for me it is easier to compare), and extracted trace for qtp792232038-1037-ht_finished-190627060547... thread. (https://github.com/eclipse/jetty.project/files/3362286/logs.zip)

I do not know why OS shows that my application uses so much CPU. Maybe it is problem with docker or other part of the environment. But I see those three threads in jstack trace I got in the morning and in jstack trace I got in the afternoon. To me those threads wants to write output, but for some reason they cannot. Maybe I can use some write timeout to prevent such situations?

**Comment by gregw** [comment]
@michal-niklas unless you have disabled the idle timeout, then jetty should timeout any stalled requests.  Thus if it is the same request, it is probably a jetty bug.
However, the different identifier for the lock may suggest that it is the same thread, acting on a different request for the same resource.    How large is popper.min.js and how frequently is it served?

I will have a more detailed look at your jstacks early next week.

**Comment by michal-niklas** [comment]
I have 3 long running threads. 2 of them serve `popper.min.js` which is about 22 KiB, and one serve `photoswipe.css` which is about 4 KiB. Both are served many times a day:

```
[mn:~/tmp/jstack] $ grep popper.min.js jetty_access_2019_07_01.log_entry | wc -l
2572
[mn:~/tmp/jstack] $ grep photoswipe.css jetty_access_2019_07_01.log_entry | wc -l
5644

```

Have a look at jstack and waiting condition info:

```
"qtp792232038-1037-ht_finished-190627060547_/komunal-partner-as/isof/__sZeeiB0knnF9XcCceY9e__/lib/view/bootstrap/4.0/js/popper.min.js" #1037 prio=5 os_prio=0 cpu=787.64ms elapsed=528475.79s tid=0x00007f164004a800 nid=0x1346
waiting on condition  [0x00007f181fffd000]
time: 6 days, 3 hrs   cpu: 1 [s]

"qtp792232038-22883-ht_finished-190629112545_/futuro/isof/__scNKtGB9dxaXb92qL58Z__/lib/view/bootstrap/4.0/js/popper.min.js" #22883 prio=5 os_prio=0 cpu=183.34ms elapsed=334392.35s tid=0x00007f152c446800 nid=0x6eb7
waiting on condition  [0x00007f1813ffe000]
time: 3 days, 21 hrs   cpu: 0 [s]

"qtp792232038-22885-ht_finished-190629112545_/futuro/isof/__scNKtGB9dxaXb92qL58Z__/lib/view/photoswipe/photoswipe.css" #22885 prio=5 os_prio=0 cpu=4.78ms elapsed=334392.35s tid=0x00007f14e4003800 nid=0x6eb9
waiting on condition  [0x00007f17d7ffd000]
time: 3 days, 21 hrs   cpu: 0 [s]

```
Few hour later they look waiting on the same condition:

```
"qtp792232038-1037-ht_finished-190627060547_/komunal-partner-as/isof/__sZeeiB0knnF9XcCceY9e__/lib/view/bootstrap/4.0/js/popper.min.js" #1037 prio=5 os_prio=0 cpu=787.64ms elapsed=546900.36s tid=0x00007f164004a800 nid=0x1346
waiting on condition  [0x00007f181fffd000]
time: 6 days, 8 hrs   cpu: 1 [s]

"qtp792232038-22883-ht_finished-190629112545_/futuro/isof/__scNKtGB9dxaXb92qL58Z__/lib/view/bootstrap/4.0/js/popper.min.js" #22883 prio=5 os_prio=0 cpu=183.34ms elapsed=352816.93s tid=0x00007f152c446800 nid=0x6eb7
waiting on condition  [0x00007f1813ffe000]
time: 4 days, 2 hrs   cpu: 0 [s]

"qtp792232038-22885-ht_finished-190629112545_/futuro/isof/__scNKtGB9dxaXb92qL58Z__/lib/view/photoswipe/photoswipe.css" #22885 prio=5 os_prio=0 cpu=4.78ms elapsed=352816.93s tid=0x00007f14e4003800 nid=0x6eb9
waiting on condition  [0x00007f17d7ffd000]
time: 4 days, 2 hrs   cpu: 0 [s]

```
I'm not sure what means '`<0x000000030a69c410>`' in:

`- parking to wait for  <0x000000030a69c410> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
`

Is this some identifier? Maybe it is elapsed time?

**Comment by janbartel** [comment]
@michal-niklas  can you be sure that you rename your threads *differently* for start vs finally? The snippet that @gregw  posted has the same naming scheme for both, but should be more like:

```java
		try
                {			
                        String started_thread_name = _thrdName + HT_STARTED_POSTFIX + TimeFuns.CurDateTimeToStrPacked() + '_' + target;
			curr_thread.setName(started_thread_name);

                        // handle here
                        ...
                }
		finally
		{
			String finished_thread_name = _thrdName + HT_FINISHED_POSTFIX + TimeFuns.CurDateTimeToStrPacked() + '_' + target;
			curr_thread.setName(finished_thread_name);
		}
	} // handle
```

**Comment by michal-niklas** [comment]
@janbartel Thank you. New version of application will use "started" and "finished" in thread name.

**Comment by DarDoro** [comment]
The same server. CPU utilization raises without apparent reason, OS memory also (20GB). Java reports only 4GB Heap. Jetty has ~800 http2 sessions in state as described bellow. Is there something to worry about? Are sendWindow ~12MB permamnenty allocated for each session?
```

HTTP2ServerSession@6dc11dc3{l:/192.168.1.124:8443 <-> r:/5.173.128.149:34477,sendWindow=12582912,recvWindow=1048576,streams=0,LOCALLY_CLOSED,GoAwayFrame@43963554,-1/protocol_error/invalid_hpack_block/LOCALLY_CLOSED} - STARTED
| | |   | +-BufferingFlowControlStrategy@25dcc1ee[ratio=0.50,sessionLevel=0,sessionStallTime=0ms,streamsStallTime=0ms]
| | |   | +-org.eclipse.jetty.http2.HTTP2Flusher@3659f14d[IDLE][window_queue=0,frame_queue=0,processed/pending=0/0]
| | |   | +>streams size=0 

```

**Comment by DarDoro** [comment]
Still the same problem, the sam server.
Top output show 50% CPU utilization for idle Jetty threads 
```
top - 12:58:56 up 13:13,  0 users,  load average: 3.83, 3.93, 3.91
Threads: 103 total,   6 running,  97 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.7 us,  3.1 sy,  0.0 ni, 91.8 id,  0.2 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 13184270+total,  1365672 free, 24572628 used, 10590440+buff/cache
KiB Swap: 16777212 total, 16673532 free,   103680 used. 97914496 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 7329 hdb       20   0 36.668g 0.020t  15344 R 56.2 16.5   0:02.06 qtp23390770+
 6874 hdb       20   0 36.668g 0.020t  15344 R 50.0 16.5   2:27.02 qtp23390770+
 6990 hdb       20   0 36.668g 0.020t  15344 S 50.0 16.5   2:06.49 qtp23390770+
 7203 hdb       20   0 36.668g 0.020t  15344 S 50.0 16.5   0:38.36 qtp23390770+ 

```
Full thread names
qtp233907704-3726-ht_finished-190827125855
qtp233907704-3389-ht_finished-190827125857
qtp233907704-3466-ht_finished-190827125857
qtp233907704-3630-ht_finished-190827125856

Typical thread state
```
qtp233907704-3726-ht_finished-190827125855/name/_sgIVgFhjUH5wZRrqmL7n__/crm/analizy/naglowek.css" #3726 prio=5 os_prio=0 cpu=2307.77ms elapsed=46.18s tid=0x00007fc478010000 nid=0x1ca1 waiting on condition  [0x00007fc373ffe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x00000003079c7b80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.3/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.3/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:656)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$800(QueuedThreadPool.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:720)
	at java.lang.Thread.run(java.base@11.0.3/Thread.java:834) 

```
Somtimes also observed
```
java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.3/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.3/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.3/SelectorImpl.java:124)
	- locked <0x000000030792c6b0> (a sun.nio.ch.Util$2)
	- locked <0x000000030792c658> (a sun.nio.ch.EPollSelectorImpl) 
```

Is there a way/test/measure to show it's not a Jetty problem?
Does high CPU means that aforementioned thread repeatedly go to sleep then wake up or just stay in JVM internal procedure?

[jetty_dump.txt](https://github.com/eclipse/jetty.project/files/3545986/jetty_dump.txt)
[jstack.txt](https://github.com/eclipse/jetty.project/files/3545988/jstack.txt)

**Comment by cy6erGn0m** [comment]
I wonder why it gets closed because noone tried to investiage it?

**Comment by gregw** [comment]
@DarDoro Sorry we failed to investigate your latest stacks etc.
Is this still an issue for you?  
What is the current version of jetty you are using?  If it is old, can you update?

**Comment by DarDoro** [comment]
Not a problem anymore. Newer version and client-side changes get rid of the problem.

**Comment by gregw** [comment]
Thanks!
