### ISSUE TITLE
No Client ALPN Processors error while trying to connect to AVS endpoint using Java Jetty library and http2clinet 

### ISSUE THREAD

**Issue by abhigithub911** [eclipse/jetty.project#3874]
[AVSClient.docx](https://github.com/eclipse/jetty.project/files/3390654/AVSClient.docx)
Hi All,

So I am trying to establish a downchannel stream connection with AVS. I am using HTTP/2 protocol to send a GET request to AVS endpoint. In the message header I am sending the access token which is required to establish a connection with AVS. 
Endpoint : https://alexa.na.gateway.devices.a2z.com/v20160207/directives 
I am using jetty library of Java to do this. I am also using ALPN library which is a protocol negotiator. HTTP/2 typically use TLS, because browsers only support HTTP/2 over TLS. And AVS communicates over SSL which is to be added in the code.   
SO In order to achieve this I have tried 2 approaches 
1. Create a http2client and sent a GET request directly with http2 format along with headers to AVS endpoint 
2. Create a htt2client and Set up an HttpClient that sends HTTP/1.1 requests over an HTTP/2 transport and hence sent GET request and headers in http format which are sent over HTTP2 using the predefined class HttpClientTransportOverHTTP2(http2Client) from http2client library.

Now I am getting the following error stack trace:

Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: No Client ALPNProcessors! at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:221) at AVSClient.doRequest(AVSClient.java:93) at AVSClient.main(AVSClient.java:55) Caused by: java.lang.IllegalStateException: No Client ALPNProcessors! at org.eclipse.jetty.alpn.client.ALPNClientConnectionFactory.<init>(ALPNClientConnectionFactory.java:55) at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2.newConnection(HttpClientTransportOverHTTP2.java:159) at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.newConnection(SslClientConnectionFactory.java:101) at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2.lambda$doStart$1(HttpClientTransportOverHTTP2.java:109) at org.eclipse.jetty.http2.client.HTTP2Client$ClientSelectorManager.newConnection(HTTP2Client.java:476) at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:248) at org.eclipse.jetty.io.ManagedSelector.access$1800(ManagedSelector.java:60) at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:889) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) at java.lang.Thread.run(Thread.java:748)

Which basically says there is No client ALPN Processors. When I searched for this error online , people have suggested me to add the following jar “alpn-boot-8.1.7.v20160121.jar” in my xbootclasspath which I did in the edit configurations of my IDE.

“Note that ALPN is not supported by Java 8. ALPN support will be coming in Java 9. To use ALPN today you would have to use ALPN libraries that are external to the JDK. The Jetty project provides an ALPN boot JAR file that can be added into your application's bootclasspath. ”

But adding it to Xbootclasspath dint work as well.  I even tried adding JDK 10 to my config file with the thought that ALPN doesn’t work with JDK 8 so probably it will work with JDK10. But that didn’t work either.  Has anyone ever faced a similar error and could help me with finding a workaround ?

I've attached my code for reference.

**Comment by olamy** [comment]
you should create a reproducible project on github. Reading docx file is not possible.
How do you build your application? what is the content of the jar you're using or what is the classpath?etc....

**Comment by sbordet** [comment]
Read [here](https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html).
