### ISSUE TITLE
@WebSocket without @OnWebSocketMessage handler fails when receiving a continuation frame

### ISSUE THREAD

**Issue by marcphilipp** [eclipse/jetty.project#3884]
Receiving a continuation frame for a binary or text frame with the following `@WebSocket` listener fails with the exception below.

```java
@WebSocket
public class MyWebSocketListener {
    @OnWebSocketFrame
    public void onWebSocketFrame(Frame frame) {
        System.out.println(frame);
    }
}
```

Exception:

```
java.io.IOException: Out of order Continuation frame encountered
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.onContinuationFrame(AbstractEventDriver.java:180)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:155)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:319)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:201)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:226)
	at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame(Parser.java:260)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:583)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:441)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:428)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
```

As a workaround, adding two dummy methods to handle text and binary frames makes it work:

```java
@WebSocket
public class MyWebSocketListener {
    @OnWebSocketFrame
    public void onWebSocketFrame(Frame frame) {
        System.out.println(frame);
    }
    @OnWebSocketMessage
    public void onBinaryMessage(byte buf[], int offset, int length) {
        //do nothing
    }
    @OnWebSocketMessage
    public void onTextMessage(String text) {
        //do nothing
    }
}
```

It is really non-obvious that these two methods should be necessary. Moreover, all frame payloads will be collected behind the scenes so they can be passed to the `@OnWebSocketMessage` methods when the last frame is received even though they are not consumed.

This seems to happen because `JettyAnnotatedEventDriver` only sets `activeMessage` when a handler method for text/binary frames is present in the `@WebSocket` class.

From a quick look at the code, it seems the same happens in `JettyListenerEventDriver` if the listener does not implement `WebSocketListener`.

**Comment by joakime** [comment]
Legit bug. working it now.

**Comment by joakime** [comment]
Opened PR #3885

**Comment by joakime** [comment]
PR #3885 Merged.
