### ISSUE TITLE
BufferUtil.toBuffer(Resource resource,boolean direct) does not like large (4G+) Resources

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3888]
When troubleshooting issue #3878 the following exception occurred ...

```
2019-07-18 11:02:08.317:WARN:oejs.CachedContentFactory:qtp1144748369-45: Could not load CachedContent@55a4cf39{r=file:///tmp/jetty-huge-work/file4G.txt,e=true,lm=Last-Modified: Tue, 16 Jul 2019 15:35:47 GMT,ct=Content-Type: text/plain,c=0}
2019-07-18 11:02:08.317:WARN:oejs.CachedContentFactory:qtp1144748369-45: 
java.lang.IllegalArgumentException: invalid resource: file:///tmp/jetty-huge-work/file4G.txt len=-100663296
	at org.eclipse.jetty.util.BufferUtil.toBuffer(BufferUtil.java:970)
	at org.eclipse.jetty.server.CachedContentFactory.getIndirectBuffer(CachedContentFactory.java:338)
	at org.eclipse.jetty.server.CachedContentFactory$CachedHttpContent.getIndirectBuffer(CachedContentFactory.java:558)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:988)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:869)
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:731)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:294)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:457)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

But it didn't prevent the file from being downloaded.

The length value is truncated in the beginning of the method ...

https://github.com/eclipse/jetty.project/blob/4ebf4b7477acb42c73a069a37e29b5fd0738bfec/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java#L972-L993

But that seems like it only exists to protect the eventual call to `BufferUtil.readFrom(is, len, buffer);` as that doesn't like `long len`.

**Comment by joakime** [comment]
The new testcase introduced in commit aef58168d06f3e1edd95e2a007be9df5f1f4ccb2
Performs a 1GB, 4GB, 10GB download of static resources via a default configured WebAppContext.

So far the results are confusing.

1GB - downloads fine.
4GB - produces a bad HTTP Response with `Content-Length: 0`, and the download is not even performed (via the java `java.net.HttpURLConnection` class).
10GB - produces 2 stack traces. (once for `CachedContentFactory$CachedHttpContent.getDirectBuffer` and once for `CachedContentFactory$CachedHttpContent.getIndirectBuffer`), but the download completes successfully.

```
2019-07-18 11:44:15.935:WARN:oejs.CachedContentFactory:qtp615634843-87: 
java.lang.IllegalArgumentException: invalid resource: file:///home/joakim/code/jetty/jetty.project-9.4.x/jetty-webapp/target/tests/test-HugeResourceTest-huge-static-base/test-10g.dat len=-2147483648
	at org.eclipse.jetty.util.BufferUtil.toBuffer(BufferUtil.java:976)
	at org.eclipse.jetty.server.CachedContentFactory.getDirectBuffer(CachedContentFactory.java:367)
	at org.eclipse.jetty.server.CachedContentFactory$CachedHttpContent.getDirectBuffer(CachedContentFactory.java:594)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:987)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:870)
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:725)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:294)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:454)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:844)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1304)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1201)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
2019-07-18 11:44:15.936:WARN:oejs.CachedContentFactory:qtp615634843-87: Could not load CachedContent@43f001e9{r=file:///home/joakim/code/jetty/jetty.project-9.4.x/jetty-webapp/target/tests/test-HugeResourceTest-huge-static-base/test-10g.dat,e=true,lm=Last-Modified: Thu, 18 Jul 2019 16:44:14 GMT,ct=null,c=0}
2019-07-18 11:44:15.939:WARN:oejs.CachedContentFactory:qtp615634843-87: 
java.lang.IllegalArgumentException: invalid resource: file:///home/joakim/code/jetty/jetty.project-9.4.x/jetty-webapp/target/tests/test-HugeResourceTest-huge-static-base/test-10g.dat len=-2147483648
	at org.eclipse.jetty.util.BufferUtil.toBuffer(BufferUtil.java:976)
	at org.eclipse.jetty.server.CachedContentFactory.getIndirectBuffer(CachedContentFactory.java:338)
	at org.eclipse.jetty.server.CachedContentFactory$CachedHttpContent.getIndirectBuffer(CachedContentFactory.java:558)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:989)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:870)
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:725)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:294)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:454)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:844)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1304)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1201)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
2019-07-18 11:44:15.940:WARN:oejs.CachedContentFactory:qtp615634843-87: Could not load CachedContent@43f001e9{r=file:///home/joakim/code/jetty/jetty.project-9.4.x/jetty-webapp/target/tests/test-HugeResourceTest-huge-static-base/test-10g.dat,e=true,lm=Last-Modified: Thu, 18 Jul 2019 16:44:14 GMT,ct=null,c=0}
```

**Comment by joakime** [comment]
Ah. the response headers for each are ...

For the 1GB test ...
```
  HTTP/1.1 200 OK
  Date: Thu, 18 Jul 2019 16:56:05 GMT
  Last-Modified: Thu, 18 Jul 2019 16:55:58 GMT
  Accept-Ranges: bytes
  Content-Length: 1073741824
  Server: Jetty(9.4.z-SNAPSHOT)
```

For the 4G test ...
```
  HTTP/1.1 200 OK
  Date: Thu, 18 Jul 2019 16:56:05 GMT
  Last-Modified: Thu, 18 Jul 2019 16:55:59 GMT
  Accept-Ranges: bytes
  Content-Length: 0
  Server: Jetty(9.4.z-SNAPSHOT)
```

For the 10G test ...
```
  HTTP/1.1 200 OK
  Date: Thu, 18 Jul 2019 16:56:05 GMT
  Last-Modified: Thu, 18 Jul 2019 16:56:04 GMT
  Accept-Ranges: bytes
  Transfer-Encoding: chunked
  Server: Jetty(9.4.z-SNAPSHOT)
```

The chunked `Transfer-Encoding: chunked` (on the 10G test) makes sense for the successful download, 
and the `Content-Length: 0` (on the 4G test) makes sense for the failed download.

**Comment by joakime** [comment]
Opened PR #3889

**Comment by joakime** [comment]
Test results of new `HugeResourceTest` found in PR #3889 

![HugeResourceTest-results](https://user-images.githubusercontent.com/191721/61745141-71d7a600-ad5e-11e9-87a7-1c42a9384ea6.png)

Multipart upload is slower then straight / plain POST upload.
I'll file another issue to investigate that performance issue.

**Comment by joakime** [comment]
For Default file system Whole Resource requests the results are:

Http Request | Linux / Jetty 9.2.28 | Linux / Jetty 9.4.19 | Linux / Jetty 9.4.x HEAD
-- | -- | -- | --
Whole / Traditional / 1 GB | 435.70 ms | 306.76 ms | 307.85 ms
Whole / Traditional / 10 GB | 5,251.54 ms | FAILED - Content-Length: 0 | 5,276.40 ms
Whole / Traditional / 2 MB | 17.14 ms | 16.81 ms | 15.87 ms
Whole / Traditional / 20 KB | 94.68 ms | 89.39 ms | 87.60 ms
Whole / Traditional / 4 GB | 2,189.00 ms | FAILED - Content-Length: 0 | 2,103.90 ms

For JarUrlConnection and Non-Default FileSystem Whole Resource requests the results are:

Http Request | Linux / Jetty 9.2.28 | Linux / Jetty 9.4.19 | Linux / Jetty 9.4.x HEAD
-- | -- | -- | --
Whole / JarUrl / Large | 6,670.05 ms | 6,691.31 ms | 6,719.11 ms
Whole / JarUrl / Medium | 6.16 ms | 12.55 ms | 6.44 ms
Whole / JarUrl / Small | 5.79 ms | 3.65 ms | 5.00 ms
Whole / ZipFs / Large | 7,655.60 ms | FAILED - EOF | 6,831.18 ms
Whole / ZipFs / Medium | FAILED - Got status code [500] | FAILED - EOF | 6.27 ms
Whole / ZipFs / Small | FAILED - Got status code [500] | FAILED - EOF | 15.71 ms

It works, whole files, regardless of origin and size(*) now work.

_* only if the static `Resource` length doesn't exceed `Long.MAX_VALUE`_
