### ISSUE TITLE
Http2 stream internal_error reset due to TimeoutException

### ISSUE THREAD

**Issue by Qnzvna** [eclipse/jetty.project#3907]
Hi,
I have a question about the idleTimeout option in the jetty server configuration. As I understand the idle timeout exceptions are suppressed during the request execution so the stream reset or connection close won't happen. Is that right?

However I've managed to found a case when the request is processed longer than the defined idleTimeout sometimes the stream is reset by the jetty. What's even more unusual about this case is that the RST_STREAM frame is send with the INTERNAL_ERROR type. The second thing which I don't understand is that 1ms before stream reset header frame is fully transformed to the client (only the data frame is not send properly).

I'm attaching the screenshot from wireshark for such stream.

That behavior happened on 9.4.11.v20180605 but I could easily reproduce this also on 9.4.19.v20190610.

```
2019-07-25 20:23:50.991:DBUG:oejs.HttpOutput:qtp245672235-48: 
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30002/30000 ms
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:235)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:226)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:307)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:842)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:513)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: 
java.util.concurrent.TimeoutException: Idle timeout expired: 30002/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-25 20:23:50.991:DBUG:oejhs.HttpTransportOverHTTP2:qtp245672235-48: HTTP2 Response #23/274a3c4a aborted
2019-07-25 20:23:50.991:DBUG:oejh.HTTP2Session:qtp632249781-21: Received ResetFrame@208b1362#23{internal_error}
```

![Screen Shot 2019-07-25 at 8 24 31 PM](https://user-images.githubusercontent.com/9974356/61898936-ad1ed400-af1a-11e9-9b71-2cfcfc7221c7.jpg)

Here is the link to the small jetty server with tests made on two clients (okhttp, jetty-client) that can reproduce this stream reset.
https://github.com/Qnzvna/jettyhttp2timeout

Please advice if this is a bug or I'm missing something and have a bad understanding of the idle timeout.

**Comment by joakime** [comment]
In your code ...

``` java
Thread.sleep(60_000); // long processing
```

That's longer then your connector idle timeout (of 30,000 ms).
That means no traffic (read or write) for 60,000ms, so the connection / channel / stream idle times out, causing the result.
Is that what you intended?

**Comment by Qnzvna** [comment]
Yes that is intended, that's longer and ofc that means that there is no traffic during that processing but why that doesn't happens for all of the requests and normally it is suppressed and the body is properly sent.

The idle timeout shouldn't happen on cases when the client is sending or receiving the data slowly? E.g.

I'm also confused by comment in: #2734 . 

> When a request is being processed, the idle timeout is disabled as per Servlet specification.

**Comment by sbordet** [comment]
> As I understand the idle timeout exceptions are suppressed during the request execution so the stream reset or connection close won't happen. Is that right?

That is true if the request is being processed asynchronously, i.e. `request.startAsync()` has been called.
Your code does that.

However, `AsyncContext` has a default timeout of 30 seconds after which it is resumed.
You want to call `asyncContext.setTimeout(0)` to disable that, otherwise the server will try to send a response back to the client when resumed.

Furthermore:
```
2019-07-25 20:23:50.991:DBUG:oejh.HTTP2Session:qtp632249781-21: Received ResetFrame@208b1362#23{internal_error}
```
shows that the server received a `RST_STREAM` from the client, which probably also has an idle timeout.

There are many things going on that you don't seem aware of, so I recommend that you take control :wink:

**Comment by Qnzvna** [comment]
I've set the context timeout to 0 and that doesn't change anything.

Both client and server are in the process and are logging to the console so the receive frame message is from the client side.
The idle timeout on client is set to 120s.
`http2Client.setIdleTimeout(120_000);`

Attaching the rst_frame from wireshark. It clearly stands that the packet was sent from 8443 port.

![Screen Shot 2019-07-25 at 9 51 58 PM](https://user-images.githubusercontent.com/9974356/61904182-95e5e380-af26-11e9-81e2-832fade00c4d.jpg)

And a little bit more of logs when reproducing using okhttp.
`2019-07-25 21:55:37.894:DBUG:oeji.WriteFlusher:Connector-Scheduler-7ac7a4e4: Flushed=true written=13 remaining=0 WriteFlusher@17a01c95{WRITING}->null
2019-07-25 21:55:37.894:DBUG:oejh.HTTP2Session:Connector-Scheduler-7ac7a4e4: Flushed 13/13 frame bytes for ResetFrame@46b98241#19{internal_error}
2019-07-25 21:55:37.894:DBUG:oeji.WriteFlusher:Connector-Scheduler-7ac7a4e4: update WriteFlusher@17a01c95{IDLE}->null:WRITING-->IDLE
2019-07-25 21:55:37.894:DBUG:oejh.HTTP2Flusher:Connector-Scheduler-7ac7a4e4: Written 1 buffers - entries processed/pending 1/0: [ResetFrame@46b98241#19{internal_error}]/[]
2019-07-25 21:55:37.894:DBUG:oejh.HTTP2Session:Connector-Scheduler-7ac7a4e4: Removed remote HTTP2Stream@78c17316#19{sendWindow=16777216,recvWindow=524288,reset=true/false,CLOSED,age=60007,attachment=ServerHttpChannelOverHTTP2@7bcadfb0{r=1,c=true,c=false/false,a=COMPLETING,uri=https://localhost:8443/,age=60007}#19}
2019-07-25 21:55:37.894:DBUG:oejh.HTTP2Flusher:Connector-Scheduler-7ac7a4e4: Flushing HTTP2ServerSession@4e77d539{l:/127.0.0.1:8443 <-> r:/127.0.0.1:64657,sendWindow=16777200,recvWindow=1048576,streams=29,NOT_CLOSED,null}
2019-07-25 21:55:37.894:DBUG:oejh.HTTP2Flusher:Connector-Scheduler-7ac7a4e4: Flushed HTTP2ServerSession@4e77d539{l:/127.0.0.1:8443 <-> r:/127.0.0.1:64657,sendWindow=16777200,recvWindow=1048576,streams=29,NOT_CLOSED,null}
Stream reset exception caught.
2019-07-25 21:55:37.894:DBUG:oejh.HTTP2Connection:Connector-Scheduler-7ac7a4e4: Ignored idle timeout on HTTP2Stream@78c17316#19{sendWindow=16777216,recvWindow=524288,reset=true/false,CLOSED,age=60007,attachment=ServerHttpChannelOverHTTP2@7bcadfb0{r=1,c=true,c=false/false,a=COMPLETING,uri=https://localhost:8443/,age=60007}#19}: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
2019-07-25 21:55:37.894:DBUG:oejs.HttpOutput:qtp896681694-91: 
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:235)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:226)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:307)
	at org.eclipse.jetty.server.Response.closeOutput(Response.java:842)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:513)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: 
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-25 21:55:37.895:DBUG:oejhs.HttpTransportOverHTTP2:qtp896681694-91: HTTP2 Response #19/4e77d539 aborted
2019-07-25 21:55:37.895:DBUG:oejs.HttpChannelState:qtp896681694-91: onComplete HttpChannelState@6b9d7769{s=COMPLETING a=NOT_ASYNC i=false r=IDLE w=false}
2019-07-25 21:55:37.895:DBUG:oejs.HttpChannel:qtp896681694-91: COMPLETE for / written=0
2019-07-25 21:55:37.895:DBUG:oejs.HttpChannel:qtp896681694-91: ServerHttpChannelOverHTTP2@7bcadfb0{r=1,c=true,c=true/false,a=COMPLETED,uri=https://localhost:8443/,age=60008}#19 handle exit, result COMPLETE
2019-07-25 21:55:37.895:DBUG:oejut.QueuedThreadPool:qtp896681694-91: ran ServerHttpChannelOverHTTP2@7bcadfb0{r=1,c=true,c=true/false,a=COMPLETED,uri=https://localhost:8443/,age=60008}#19 in QueuedThreadPool[qtp896681694]@357246de{STARTED,8<=11<=200,i=0,r=12,q=0}[ReservedThreadExecutor@e25b2fe{s=3/12,p=0}]
okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:419)
	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:217)
	at okio.RealBufferedSource.select(RealBufferedSource.java:100)
	at okhttp3.internal.Util.bomAwareCharset(Util.java:467)
	at okhttp3.ResponseBody.string(ResponseBody.java:181)
	at TimeoutOkTest$2.onResponse(TimeoutOkTest.java:132)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:216)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by sbordet** [comment]
Please attach the full logs and if you can the full wireshark (in clear).

**Comment by Qnzvna** [comment]
Sure, I've pushed the logs and packets in the text form into the repository.
https://github.com/Qnzvna/jettyhttp2timeout/tree/master/logs

**Comment by sbordet** [comment]
@Qnzvna setting `asyncContext.setTimeout(0)` gets rid of a race condition where the container would wake up and try to write a response back to the client.

What you have now is a different race between the 30 seconds idle timeout and your 60 seconds sleep.

The idle timeout works in a way that every 30 seconds it wakes up and checks if it has to idle timeout. Because your request is async, most of the times the idle timeout is ignored (you can see this from the logs).

However, some times the 60 seconds sleep elapses, your code is trying to write a small response then yields the control back to Jetty.
At that point, the idle timeout also fires (the second time after the first ignored 30 seconds) and wins the race causing the response to be aborted.

@gregw what is the spec saying about this? If an application stays idle for 29.9 seconds and then resumes, it is correct to only give it 0.1 seconds to finish its job?
For the HTTP/2 side we reset the stream idle timeout as soon as something is read/written to the stream, but we could still lose the race.
The OP code does this:

```java
executor.submit(() ->
{
    Thread.sleep(60_000);
    response.setStatus(200);
    outputStream.setWriteListener(...);
});
```

We move from `ASYNC_WAIT` to `ASYNC_WOKEN` etc. and we are in a race.
I think this is happening also for HTTP/1.1.

**Comment by Qnzvna** [comment]
> @Qnzvna setting asyncContext.setTimeout(0) gets rid of a race condition where the container would wake up and try to write a response back to the client.
Yes, I understand the mechanism, I just forgot to add this to the snippet for reproducing the error. This statement is surely needed. We are setting it on our production environment (using dropwizard actually).

> For the HTTP/2 side we reset the stream idle timeout as soon as something is read/written to the stream, but we could still lose the race.

That was my assumption also. The idleTimeout on the whole HTTP2 connection can be singly mitigated by sending pings from the client (which we are doing in the production). However, the ping frame doesn't bumps the idle timeout for the stream (as it is stream 0 always).

Thanks a lot for looking into this! 
If you need anything from my site to debug this further feel free to ask.

**Comment by sbordet** [comment]
@Qnzvna we discussed this case, and we think it's an unfortunate, but possible, case, so TLDR is that you don't want to race with idle timeouts.
Your 60 seconds sleep is racing with the 30 seconds idle timeout and yes, things can go wrong.

Even in the case of not sleeping, but doing some activity that lasts exactly the idle timeout, you may end up in this race and there is not much that can be done.

This is exacerbated by the Servlet definition of idle timeout and how to handle it while being in async processing: it's not clear what a Servlet Container or an application have to do in corner cases - let alone that it may have not been a good idea to "extend" the idle timeout while async processing.

If you imagine having a proxy with a 30 seconds idle timeout in front of Jetty, your request would have idle timed out after 30 seconds.
If you know your application processing can last 60 seconds, then what you would do is to arrange the proxy idle timeout so that it could cover the processing plus some safety margin.

This case would be the same: relying on "Servlets will ignore idle timeout until my processing is over" is risky and you don't want to do that. If you know your processing lasts 60 seconds, you set an idle timeout of e.g. 75 seconds.

Also, if you have clients (e.g. a HTTP client that calls an external service from within your application), then you always want to have the client idle timeout shorter than the server idle timeout, so that the client always know first that something went wrong.

We are inclined to close this issue because it's a corner case of an uncovered case of the Servlet specification, and we think it can be worked around by not relying on idle timeouts (or be prepared that things can be racy).
So either you arrange for idle timeouts to not expire (and so for example have a shorter application timeout), or you let them expire but then be prepared that things may race in case application and idle timeout wake up at exactly the same time.
This race will happen even if you decide to setup and handle an application timeout, but it's going to be much easier for you to handle your own races than trying to coordinate the race between the application and the Servlet Container.

If you have further insights, please reopen/comment.

**Comment by gregw** [comment]
Note also that if you really do have requests that take 60+ seconds, then you might want to look at a comet style long polling approach or even sending 102 PROCESSING responses to avoid the connection timing out.  >30s idle connections do not live long on the wider web.
