### ISSUE TITLE
Inform custom ManagedSelector of dead selector via optional onFailedSelect()

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#3989]
Well, not quite quietly, but it does close it with a Log.warn() message.

https://github.com/eclipse/jetty.project/blob/6a0a2883ad354f2987cf6ff6f09519bf23425906/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L234-L271

If the `int selected = selector.select();` has an exception ... 

Example exception:

```
java.io.IOException: Interrupted function call
 at sun.nio.ch.FileDispatcherImpl.close0(Native Method)
 at sun.nio.ch.SocketDispatcher.close(SocketDispatcher.java:55)
 at sun.nio.ch.SocketChannelImpl.kill(SocketChannelImpl.java:879)
 at sun.nio.ch.AbstractPollSelectorImpl.implDereg(AbstractPollSelectorImpl.java:194)
 at sun.nio.ch.SelectorImpl.processDeregisterQueue(SelectorImpl.java:149)
 at sun.nio.ch.PollSelectorImpl.doSelect(PollSelectorImpl.java:91)
 at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
 at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
 at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
 at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:243)
 at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:191)
 at org.eclipse.jetty.util.thread.strategy.ProduceExecuteConsume.execute(ProduceExecuteConsume.java:69)
 at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:147)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
 at java.lang.Thread.run(Thread.java:748)
```

... then the selector is `closeNoExceptions(_selector);` and `select()` returns `false`

Which returns a `produce()` of `null`
Which the PEC.execute() interprets as no task and waits on its lock.
We now have no Selector running, and no way to detect this. (as the selector close produces no events, and the selector itself is not an exposed field to interrogate).

This results in a dead ServerConnector that can no longer process network events or even handle new incoming requests/connections.

**Comment by joakime** [comment]
Working on a possible solution along the lines of ...

**Main Code**
``` java
Server server = new Server(threadPool);
CustomServerConnector connector = new CustomServerConnector(server, 1, 1);
connector.setPort(9999);
server.addConnector(connector);
```

**CustomServerConnector.java**
``` java
public class CustomServerConnector extends ServerConnector
{
    public CustomServerConnector(Server server, int acceptors, int selectors)
    {
        super(server, acceptors, selectors);
    }

    @Override
    protected SelectorManager newSelectorManager(Executor executor, Scheduler scheduler, int selectors)
    {
        return new ServerConnectorManager(executor, scheduler, selectors)
        {
            @Override
            protected ManagedSelector newSelector(int id)
            {
                return new CustomManagedSelector(this, id, getExecutionStrategyFactory());
            }
        };
    }
}
```

**CustomManagedSelector.java**
``` java
public class CustomManagedSelector extends ManagedSelector
{
    public CustomManagedSelector(SelectorManager selectorManager, int id, ExecutionStrategy.Factory executionFactory)
    {
        super(selectorManager, id, executionFactory);
    }

    /**
     * New method in ManagedSelector.
     * Is called when selector.select() throws an exception.
     */
    @Override
    protected void onSelectFailed(Selector selector, Throwable cause)
    {
        try
        {
            this.startSelector();   // new method in ManagedSelector
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }
}
```

Ideally, this would allow the restarting of the selector.
But I can't get it to work reliably on both PEC (works here) and EPC (fails here).

**Comment by gregw** [comment]
How about a System.exit when the selector fails - allow for a full restart of the server.... I'm only partly joiking!

**Comment by sbordet** [comment]
@joakime ping me and let's see if we can make it work.
@gregw nah :grin:
