### ISSUE TITLE
[9.4.20] Incompatible type change in patch version

### ISSUE THREAD

**Issue by gbrehmer** [eclipse/jetty.project#4020]
changing ExtensionFactory from abstract class to interface with 9.4.20 seems to be an incompatible change for third party libraries like spring (Spring Boot 2.1.7) which make some use of this class:

```
2019-08-23 15:22:35.929 ERROR 321 --- [tp1413871034-27,i=127.0.0.1] d.i.r.w.config.logging.HttpErrorFilter   : RETURN 500, url: GET /websocket/731/2y1k2l1j/websocket
2019-08-23 15:22:35.931  WARN 321 --- [tp1413871034-27,] org.eclipse.jetty.server.HttpChannel     : /websocket/731/2y1k2l1j/websocket

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.socket.sockjs.SockJsException: Uncaught failure in SockJS request, uri=http://127.0.0.1/websocket/731/2y1k2l1j/websocket?access_token
....
Caused by: org.springframework.web.socket.sockjs.SockJsException: Uncaught failure in SockJS request, uri=http://127.0.0.1/websocket/731/2y1k2l1j/websocket?access_token=<token>
nested exception is org.springframework.web.socket.sockjs.SockJsTransportFailureException: WebSocket handshake failure; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:136)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:53)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	... 103 common frames omitted
Caused by: org.springframework.web.socket.sockjs.SockJsTransportFailureException: WebSocket handshake failure; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.socket.sockjs.transport.handler.WebSocketTransportHandler.handleRequest(WebSocketTransportHandler.java:128)
	at org.springframework.web.socket.sockjs.transport.TransportHandlingSockJsService.handleTransportRequest(TransportHandlingSockJsService.java:312)
	at org.springframework.web.socket.sockjs.support.AbstractSockJsService.handleRequest(AbstractSockJsService.java:438)
	at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:133)
	... 107 common frames omitted
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.buildWebSocketExtensions(JettyRequestUpgradeStrategy.java:170)
	at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.getSupportedExtensions(JettyRequestUpgradeStrategy.java:164)
	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.doHandshake(AbstractHandshakeHandler.java:283)
	at org.springframework.web.socket.sockjs.transport.handler.WebSocketTransportHandler.handleRequest(WebSocketTransportHandler.java:124)
	... 110 common frames omitted
```

it is possible to get a patched 9.4.x version w/o backward incompatible changes?

**Comment by joakime** [comment]
What version of Spring is your `org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy` from?
I ask, as this problem has existed for a while, and I thought we addressed this at Spring already.
Your line numbers don't match up with any of the versions we test against too.

**Comment by joakime** [comment]
I am unable to replicate with Spring Boot 2.1.7 with Spring WebSocket 5.1.9.RELEASE upgraded to use Jetty 9.4.20.
Regarding the IncompatibleClassChangeError, have you verified that you don't have mixed versions of Jetty jars present?

**Comment by gbrehmer** [comment]
the change is part of 9.4.20 (https://github.com/eclipse/jetty.project/commit/30dc103a129d08304e1f1a99a84c045049de305d#diff-4af9666bc4755ce4bae7e7bacb9761ce). We use latest version like you mentioned: 
2.1.7 with Spring 5.1.9
Line 170: 
```
Set<String> names = this.factory.getExtensionFactory().getExtensionNames()
```
Probably the first time during request, that a method from extensionfactory abstract class/interface is called

**Comment by gbrehmer** [comment]
Report from japi-compliance-checker (https://github.com/lvc/japi-compliance-checker) or see comments regarding binary backward compatibility: https://stackoverflow.com/a/4690885/218449
![image](https://user-images.githubusercontent.com/1201680/63625866-42d47e80-c601-11e9-9c4d-841c7dc771ca.png)

**Comment by joakime** [comment]
I did a full build of spring-boot 2.1.7 (with tests) using Jetty 9.4.20 with no issues as well.
I did not recompile spring-websocket 5.1.9 in this attempt.

The call in spring-websocket that uses ...

```
Set<String> names = this.factory.getExtensionFactory().getExtensionNames()
```

Does not fail for me when simply switching out Jetty 9.4.19 (which spring-websocket 5.1.9 was built against) to Jetty 9.4.20.
That line of code is also not incompatible with the change from abstract to interface. (what your API checker points out with "dependent on the usage of this class").
If spring-websocket had created their own ExtensionFactory then we'd have something that could trigger that IncompatibleClassChangeError, but we don't.

The only way I can trigger the IncompatibleClassChangeError is if I have mixed versions of Jetty present in my ClassLoader.
A different version of jetty-websocket on the webapp classloader vs the server classloader.

**Comment by gbrehmer** [comment]
my understanding about the api checker result differs quite a bit. the sentence "dependent on the usage of this class" means from my perspective, that If we make an own implementation/subclass, we already get an exception during instantiation (InstantiationError). Previously, the implementation was part of the abstract class. now its moved to the only public implementation of the interface. What you probably mean is source code compatibility. We will make some more tests, but we also have a clean e2e test setup and embedded jetty and excluded jetty dependencies from other 3rd party libs like liquibase. And we have real world test cases, where a browser starts a websocket connection to our backend service (protractor with chrome). Unit tests from spring probably does not cover such a request in the same way.
When you make a new build of spring with updated resources, the binary compatibility is assured. The problem only occurs if you use spring jars which are "linked" to another jetty version during build/packaging time from the spring jar. So probably the problem goes away if we wait for spring boot 2.1.8 with updates 3rd party libs. but then it is not more possible to use jetty <= 9.4.19 with such a version. For sure our spring boot setup is not the default one, most people will use jetty in the same version it was used from the spring guys during release time.

**Comment by joakime** [comment]
The build of spring-boot 2.1.7 leaves the spring-websocket 5.1.9 artifact alone, it doesn't rebuild it.
That's where the IncompatibleClassChangeError you reported is triggered from.
I'm not done with this issue, I have a few more things to try after the weekend.
But I want to understand this before reverting an important change to fix a websocket permessage-deflate bug.

**Comment by gbrehmer** [comment]
I've looked not very deep into the implementation, but currently (I did not checked the tests) there is only one implementation, which implements the interface. so then it should be possible to still use a abstract class for 9.4.x. it seems that this was more like a refactoring for code styling.
i will make tests with a spring boot websocket example app and will post the results later.

**Comment by gbrehmer** [comment]
@joakime thanks for such a fast bugfix/feedback! 
ah I started the spring boot app directly from STS and didn't executed the tests. sorry for any inconvenience. and thanks for pointing to the tests, I didn't know the spring java sockjs client lib yet.
