### ISSUE TITLE
Multiple values in X-Forwarded-Port throw NumberFormatException

### ISSUE THREAD

**Issue by xamino** [eclipse/jetty.project#4048]
This issue arose in our development environment, using webpack-dev-server with **two** proxies. Request looks like thus:
```
X-Forwarded-For: 127.0.0.1,127.0.0.1
X-Forwarded-Port: 8080,8080
```
The multiple port values however cause Jetty to throw:
```
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "8080,8080"
	at org.eclipse.jetty.server.ForwardedRequestCustomizer.customize(ForwardedRequestCustomizer.java:375) ~[jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:363) ~[jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) ~[jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) ~[jetty-io-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) ~[jetty-io-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) ~[jetty-util-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) ~[jetty-util-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[jetty-util-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132) ~[jetty-util-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781) ~[jetty-util-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917) ~[jetty-util-9.4.19.v20190610.jar:9.4.19.v20190610]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.NumberFormatException: For input string: "8080,8080"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:na]
	at java.base/java.lang.Integer.parseInt(Integer.java:652) ~[na:na]
	at java.base/java.lang.Integer.parseInt(Integer.java:770) ~[na:na]
	at org.eclipse.jetty.http.HttpField.getIntValue(HttpField.java:75) ~[jetty-http-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.server.ForwardedRequestCustomizer$Forwarded.handlePort(ForwardedRequestCustomizer.java:577) ~[jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
	at org.eclipse.jetty.server.ForwardedRequestCustomizer.customize(ForwardedRequestCustomizer.java:370) ~[jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
	... 12 common frames omitted
```

Jetty 9.4.19, but relevant file is still unchanged for 9.4.x – https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L628 calls https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java#L74 so it will still throw (since it is not just one port number).

I'm aware that `X-Forwarded-*` is a mess, and we've fixed it by not adding the headers twice (webpack-dev-server: set `xfwd` only in a single proxy), but the error could well happen in the wild, so reporting for anyone else (independent of whether this should be fixed or not).

**Comment by joakime** [comment]
This kind of request most definitely needs to return a failure status code. 
Now which one seems the most appropriate is up for discussion.

**Comment by gregw** [comment]
@joakime I don't think so.  We handle multiple `X-Forwarded-Port` headers OK and we handle multiple `X-Forwarded-For` values both as separate headers and and comma separated values.  So I think we should support this case.

PR coming...

**Comment by joakime** [comment]
Opened PR #4063
