### ISSUE TITLE
Restarting quickstarted webapp throws IllegalStateException: ServletContainerInitializersStarter already exists

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#4076]
If a webapp that is started via quickstart is stopped and restarted, it throws:

```
java.lang.IllegalStateException: ServletContainerInitializersStarter already exists
	at org.eclipse.jetty.quickstart.QuickStartConfiguration.configure(QuickStartConfiguration.java:186)
	at org.eclipse.jetty.webapp.Configurations.configure(Configurations.java:484)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:522)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1287)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:817)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:309)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:542)
```

The problem is that the ServletContainerInitializersStarter is added by the QuickStartConfiguration.configure() method, but never cleared in the QuickStartConfiguration.postconfigure or deconfigure() method.

**Comment by janbartel** [comment]
Fixed for 10.0.0.
