### ISSUE TITLE
Http client does not work on https with proxy

### ISSUE THREAD

**Issue by smatei** [eclipse/jetty.project#408]
Hi,

I try to connect to a https page ("https://www.google.com" in my example), using a squid proxy. 

    
      SslContextFactory sslContextFactory = new SslContextFactory();
      HttpClient client = new HttpClient(sslContextFactory);

      ProxyConfiguration proxyConfig = client.getProxyConfiguration();
      
      HttpProxy proxy = new HttpProxy(new Origin.Address(proxyHost, proxyPort), true);

      client.getAuthenticationStore().addAuthentication(new BasicAuthentication(new URI("https://" + proxyHost), "Proxy", user, password));
      
      proxyConfig.getProxies().add(proxy);
      
      client.start();

      ContentResponse res = client.GET("https://www.google.com");
      
      System.out.println(res.getStatus());
      
      System.out.println(res.getContentAsString());
      
      client.stop(); `      

I get the following exception:

`2016-03-09` 11:35:54.980:INFO:oejc.ResponseNotifier:HttpClient@1555009629-11: Exception while notifying listener org.eclipse.jetty.client.AuthenticationProtocolHandler$AuthenticationListener@340e1cca
java.lang.IllegalArgumentException: Invalid protocol www.google.com
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:536)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:704)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:688)
	at org.eclipse.jetty.client.AuthenticationProtocolHandler$AuthenticationListener.onComplete(AuthenticationProtocolHandler.java:158)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:447)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:394)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:264)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1199)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:158)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:119)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:112)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$1.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)`

It seems that in HttpRequest.BuildURI, an URI is created from "www.google.com:443", that has no protocol.

**Comment by smatei** [comment]
The proxy does not have NTLM authentication. 
On non https pages, it works fine.

**Comment by khalidhuseynov** [comment]
I wonder if this kind of fixes are backported into `9.2.x` branch for projects using JVM `1.7`?

**Comment by sbordet** [comment]
@khalidhuseynov Jetty 9.2.x is in maintenance mode only, so this issue won't be backported unless sponsored through Webtide support.

**Comment by joakime** [comment]
@khalidhuseynov or done by the community in a PR

**Comment by khalidhuseynov** [comment]
@sbordet @joakime i see, thanks for info
