### ISSUE TITLE
Resolution of relative path leads to BadMessageException

### ISSUE THREAD

**Issue by ko-mueller** [eclipse/jetty.project#4088]
In one of our projects we're are using Jetty together with RESTEasy to serve our REST API. One endpoint is available under a URL which looks like `GET /path/to/endpoint/{value}` where `{value}` can basically be an arbitrary string. When I execute `curl 'http://localhost/path/to/endpoint/%2F..%2F..%2F..%2F..%2F..'` the request is rejected with `<h1>Bad Message 400</h1><pre>reason: Bad URI</pre>`.

Stacktrace:
```
org.eclipse.jetty.http.BadMessageException: 400: Bad URI
	at org.eclipse.jetty.server.Request.setMetaData(Request.java:1717) ~[jetty-server-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.HttpChannel.onRequest(HttpChannel.java:705) ~[jetty-server-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.HttpChannelOverHttp.headerComplete(HttpChannelOverHttp.java:388) ~[jetty-server-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.http.HttpParser.handleHeaderContentMessage(HttpParser.java:564) ~[jetty-http-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1187) ~[jetty-http-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1475) ~[jetty-http-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:369) ~[jetty-server-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258) ~[jetty-server-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135) ~[jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) ~[jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) ~[jetty-util-9.4.20.v20190813.jar:9.4.20.v20190813]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

The problem is that the path gets decoded to `/path/to/endpoint//../../../../..` and afterwards `URIUtil.canonicalPath()` returns null because it traverses the path above root. This leads to a BadMessageException. When I call the endpoint with one less `/..` everything works fine. The `{value}` variable in my REST endpoint is substituted with the correct value, however, the resolved path in `Request.setMetaData()` is different.

Is this expected behaviour? Can I turn the resolution of relative paths off?

I know that I can put the same information into the request body or a query parameter to avoid this problem, but this would make the API more cumbersome to use and I'd like to avoid that.

Thank you in advance!

**Comment by ko-mueller** [comment]
Thank you for the explanation! The point is that we're using Jetty to serve the REST API and all requests are just forwarded to RESTEasy and evaluated by the REST framework. We're not serving static files, etc. with Jetty. That said, breaking the specification is probably not a good idea as it could lead to more problems down the road.
