### ISSUE TITLE
WebSocket Client sometimes receives EOFException in onError, instead of SSLHandshakeException

### ISSUE THREAD

**Issue by steffyP** [eclipse/jetty.project#4091]
I have a simple test case, that should verify a SSLHandshakeException is received in the client's WebSocket _onError_ callback in case the server uses a certificate that is unknown to the client.

Most of the time the test works fine, but **sometimes, instead of a SSLHandshakeException, a EOFException is received**:
```
java.io.EOFException: HttpConnectionOverHTTP@157a0f67::DecryptedEndPoint@20c1e4de{localhost/127.0.0.1:10005<->/127.0.0.1:64987,CLOSED,fill=-,flush=C,to=8/0}
2019-09-16 14:10:08.632:DBUG:oeji.FillInterest:qtp209813603-13: onFail FillInterest@27d3f334{null}
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.io.FillInterest.onClose(FillInterest.java:150)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:355)
	at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:214)
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doClose(SslConnection.java:1180)
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:220)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:681)
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:341)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:426)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:320)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:158)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
```

I already tested with the version 9.4.20.v20190813.

Could you please give me a hint whether this is a bug, or maybe there is something misconfigured in my test example.

I have attached a debug-log output of the test case. I could also provide you the sources of the test if required. 
[jetty_test_failed.log](https://github.com/eclipse/jetty.project/files/3616156/jetty_test_failed.log)

Thank you!

Edit: I could already verify in the logs, that the SSLHandshakeException was also thrown, but nevertheless, the client's web socket callback only received EOFException in onError.

**Comment by sbordet** [comment]
I believe this is the same as #3787.

I think it's a race between receiving the TLS error, but still trying to write after that.

**Comment by gregw** [comment]
closing in favour of #3787
