### ISSUE TITLE
Problems with migration to Jetty 10.0.0-alpha0

### ISSUE THREAD

**Issue by davido** [eclipse/jetty.project#4112]
I'm trying to migrate Gerrit project to Jetty 10.0.0-alpha0 and facing some problems.

For one jetty-continuation sub-project was discontinued (related: #1444). It's not quite clear to me how to migrate of from using `org.eclipse.jetty.continuation.Continuation` and friends.

For another some acceptance tests are failing, e.g.:

```
19) changeEditRest(com.google.gerrit.acceptance.edit.ChangeEditIT)
org.apache.http.NoHttpResponseException: localhost:44515 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.apache.http.client.fluent.Executor.execute(Executor.java:229)
	at com.google.gerrit.acceptance.HttpSession.execute(HttpSession.java:49)
	at com.google.gerrit.acceptance.RestSession.putRaw(RestSession.java:90)
	at com.google.gerrit.acceptance.edit.ChangeEditIT.changeEditRest(ChangeEditIT.java:530)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.google.gerrit.acceptance.AbstractDaemonTest$1$1.evaluate(AbstractDaemonTest.java:213)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:153)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)
```

The migration change is here: [1]. To reproduce, fetch this CL and run:

```
  $ bazel test --host_javabase=@bazel_tools//tools/jdk:remote_jdk11 \
    --javabase=@bazel_tools//tools/jdk:remote_jdk11 \
    --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 \
    --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 \
    javatests/...
```

[1] https://gerrit-review.googlesource.com/c/gerrit/+/238383

**Comment by joakime** [comment]
> For one jetty-continuation sub-project was discontinued (related: #1444). It's not quite clear to me how to migrate of from using {{org.eclipse.jetty.continuation.Continuation}} and friends.

Continuations were replaced by `javax.servlet.AsyncContext` back in Jetty 8.0

See https://docs.oracle.com/javaee/7/api/javax/servlet/AsyncContext.html

The events / methods signatures should look familiar.

**Comment by joakime** [comment]
Also, glancing quickly at your gerrit review page, you mention QoSFilter, which still exists on Jetty 10.

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/QoSFilter.java

**Comment by davido** [comment]
@joakime Thanks for the pointer. It was migrated from Jetty's ` Continuation` to `javax.servlet.AsyncContext` in this CL: [1].

Any clue, though, why the REST tests are failing with Jetty 10.0.0-alpha0? 

https://github.com/eclipse/jetty.project/commit/5956b9e013eeacac3e2d320c4bb271f1036dff5e

**Comment by sbordet** [comment]
> Any clue, though, why the REST tests are failing with Jetty 10.0.0-alpha0?

DEBUG logs?

**Comment by davido** [comment]
> DEBUG logs?

WARN  org.eclipse.jetty.io.ManagedSelector : java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletMapping

Sorry for the noise. I missed that servlet API was bumped in Jetty 10.x from 3.x to 4.x, so that this transitive dependency change was still missing here:

```
diff --git a/WORKSPACE b/WORKSPACE
index 753b276ed5..d8b8435efa 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -195,10 +195,11 @@ maven_jar(
     sha1 = "6975da39a7040257bd51d21a231b76c915872d38",
 )
 
+# TODO(davido): Rename servlet-api-3_1 to just servlet-api to make it upgrade friendly
 maven_jar(
     name = "servlet-api-3_1",
-    artifact = "org.apache.tomcat:tomcat-servlet-api:8.5.23",
-    sha1 = "021a212688ec94fe77aff74ab34cc74f6f940e60",
+    artifact = "org.apache.tomcat:tomcat-servlet-api:9.0.26",
+    sha1 = "027e44dff2e3b04c46c258761e45e30701fd35cd",
 )
 
```

After bump of `org.apache.tomcat:tomcat-servlet-api:9.0.26` the tests are passing again:

```
  $ bazel test //javatests/com/google/gerrit/acceptance/edit:edit
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/command.profile.gz'
INFO: Invocation ID: 634b213c-5ac7-414c-a505-0a495b42e3e9
INFO: Analyzed target //javatests/com/google/gerrit/acceptance/edit:edit (262 packages loaded, 4195 targets configured).
INFO: Found 1 test target...
Target //javatests/com/google/gerrit/acceptance/edit:edit up-to-date:
  bazel-bin/javatests/com/google/gerrit/acceptance/edit/edit.jar
  bazel-bin/javatests/com/google/gerrit/acceptance/edit/edit
INFO: Elapsed time: 134.161s, Critical Path: 110.66s
INFO: 454 processes: 401 remote cache hit, 15 linux-sandbox, 38 worker.
INFO: Build completed successfully, 476 total actions
//javatests/com/google/gerrit/acceptance/edit:edit                       PASSED in 37.0s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 476 total actions
```

**Comment by joakime** [comment]
The tomcat-servlet-api is missing schemas that Jetty 10 needs.

Please use jetty-servlet-api
 https://search.maven.org/artifact/org.eclipse.jetty.toolchain/jetty-servlet-api/4.0.2/jar

**Comment by joakime** [comment]
Also of note, tomcat is not the reference implementation for the servlet api.
The official servlet-api jar is found at ...
https://search.maven.org/artifact/javax.servlet/javax.servlet-api/4.0.1/jar

With updates found at ...
https://search.maven.org/artifact/jakarta.servlet/jakarta.servlet-api/4.0.3/jar

**Comment by davido** [comment]
@joakime @sbordet Thanks for your help. We are in process to migrate from Jetty continuation to AsyncContext in this CL: [1]. I also uploaded this diff here if this is easier to review: [2].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/245132
[2] http://paste.openstack.org/show/786038
