### ISSUE TITLE
Server fails to start if OIDC module added without jetty.openid.scopes defined

### ISSUE THREAD

**Issue by travisspencer** [eclipse/jetty.project#4130]
If the new OpenID module is added to a server, and the `jetty.openid.scopes` which is said (in the INI template at least) to be "extra" scopes beyond `openid`, then the server will not start with this exception:

```
2019-09-28T14:12:18:064+0200 WARN  {main} org.eclipse.jetty.xml.XmlConfiguration:544 Config error at <Call name="addScopes"><Arg>
        <Call class="org.eclipse.jetty.util.StringUtil" name="csvSplit"><Arg><Property name="jetty.openid.scopes"/></Arg></Call>
      </Arg></Call>
2019-09-28T14:12:18:065+0200 WARN  {main} org.eclipse.jetty.xml.XmlConfiguration:544 Config error at <New id="OpenIdConfiguration" class="org.eclipse.jetty.security.openid.OpenIdConfiguration"><Arg><Property name="jetty.openid.openIdProvider"/></Arg><Arg><Property name="jetty.openid.clientId"/></Arg><Arg><Property name="jetty.openid.clientSecret"/></Arg><Call name="addScopes"><Arg>
        <Call class="org.eclipse.jetty.util.StringUtil" name="csvSplit"><Arg><Property name="jetty.openid.scopes"/></Arg></Call>
      </Arg></Call></New>
2019-09-28T14:12:18:065+0200 WARN  {main} org.eclipse.jetty.xml.XmlConfiguration:1897
 java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837) [jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:762) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:757) ~Exception in thread "main" [jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:973) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:940) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:512) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1060) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:518) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:454) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:354) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1874) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	... 2 more
Caused by: java.lang.NullPointerException
	at java.util.Collections.addAll(Collections.java:5400) ~[?:1.8.0_181]
	at org.eclipse.jetty.security.openid.OpenIdConfiguration.addScopes(OpenIdConfiguration.java:134) ~[jetty-openid-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:762) ~[jetty-xml-9.4.21-SNAPSHOT.jar:9.4.21-SNAPSHOT]
```

**Comment by lachlan-roberts** [comment]
fixed with PR #4131
