### ISSUE TITLE
9.4.21 is incompatible with dropwizard metrics-jetty9 4.x

### ISSUE THREAD

**Issue by cstamas** [eclipse/jetty.project#4169]
This is not a jetty bug per-se, just a FYI for others using the two libraries...

Jetty 9.4.21 and metrics-jetty9 4.x throws this:

```
2019-10-08 13:45:20,078+0000 WARN  [qtp1-864] *SYSTEM org.eclipse.jetty.server.HttpChannel - /some/path
java.lang.NoSuchFieldError: DISPATCHED
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:233)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handleAsync(Server.java:543)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$2(HttpChannel.java:397)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:560)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:397)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:336)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
        at java.lang.Thread.run(Thread.java:748)
```

Even current (as of creating this issue) metrics-jetty9 has this line:
https://github.com/dropwizard/metrics/blob/af8bc7b193bb53b8b90a2df254cff4d7c35caae7/metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedHandler.java#L233

There is a PR but failed, as bumping Jetty is not enough:
https://github.com/dropwizard/metrics/pull/1487

**Comment by joakime** [comment]
`HttpChannelState.State` is very internal and wasn't meant as a public API.  It was split up, it's now `State`, `RequestState`, `InputState`, `OutputState`.

The commit that made this change - https://github.com/eclipse/jetty.project/commit/bde86467f4e5df595773ab11ed5e80c615b741f3#diff-68e74a60841dd5ec1f7edc4bd736ce18

@cstamas what do you need from `Handler` and/or `HandlerWrapper` to make your instrumentation easier and more reliable?

Would a listener interface for your various events be acceptable?
Would the existing `HttpChannel.Listener` be a good starting point?
https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/server/HttpChannel.Listener.html

**Comment by cstamas** [comment]
@joakime sry for late response.... just to clear up, am merely a "user" of metrics-jetty9 and just spotted this problem. I did not write any code the is in that library.

That said, I might create a patch for them using the hint you provided, as I see, the listener should be good starting point.... (or this could be a hint to anyone out there as well :smile: )

**Comment by joakime** [comment]
Closing as https://github.com/dropwizard/metrics/pull/1490 was merged.
