### ISSUE TITLE
Classcast Exception when adding SessionHandler to Handler Chain

### ISSUE THREAD

**Issue by xresch** [eclipse/jetty.project#4185]
I'm currently a bit in trouble and I wasn't able to figure our the root cause of this issue by myself.
When I add the SessionHandler to the handler chain, server.start() throws a class cast exception.

Without the SessionHandler sthe startup works fine:
```
new HandlerChainBuilder(mainHandler)
.chain(servletGzipHandler)
.chain(requestHandler)
.chainLast(handlerCollection);
```

But as soon as I add the Handler to the session handler to the handler chain...
```
new HandlerChainBuilder(mainHandler)
.chain(servletGzipHandler)
.chain(sessionHandler)
.chain(requestHandler)
.chainLast(handlerCollection);
```

I get the following exception:
```
java.lang.ClassCastException: org.eclipse.jetty.server.handler.ContextHandler cannot be cast to org.eclipse.jetty.servlet.ServletContextHandler
	at org.eclipse.jetty.servlet.ServletHandler.doStart(ServletHandler.java:155)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:123)
	at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:568)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:406)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:123)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:913)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:415)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.pengtoolbox.cfw._main.CFWApplication.start(CFWApplication.java:516)
	at com.pengtoolbox.pageanalyzer._main.Main.startApp(Main.java:121)
	at com.pengtoolbox.cfw._main.CFW.initializeApp(CFW.java:139)
	at com.pengtoolbox.pageanalyzer._main.Main.main(Main.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
```

What I find really interesting, is that the output of Handler.dump() changes
This is without SessionHandler:
```
o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} - STOPPED
+= GzipHandler@4b5a5ed1{STOPPED} - STOPPED
|  += RequestHandler@59d016c9{STOPPED} - STOPPED
|     += HandlerCollection@3cc2931c{STOPPED} - STOPPED
|        +? o.e.j.s.ServletContextHandler@20d28811{/pub,null,UNAVAILABLE} - STOPPED
|        |  += ServletHandler@3967e60c{STOPPED} - STOPPED
|        |  |  +> listeners ServletHandler@3967e60c{STOPPED} size=0
|        |  |  +> filters ServletHandler@3967e60c{STOPPED} size=0
|        |  |  +> filterMappings ServletHandler@3967e60c{STOPPED} size=0
|        |  |  +> servlets ServletHandler@3967e60c{STOPPED} size=5
|        |  |  |  +> com.pengtoolbox.pageanalyzer.servlets.RestAPIServlet-5a955565@cb99d298==com.pengtoolbox.pageanalyzer.servlets.RestAPIServlet,jsp=null,order=-1,inst=true,async=true - STOPPED
|        |  |  |  |  +> com.pengtoolbox.pageanalyzer.servlets.RestAPIServlet@60d8c9b7
|        |  |  |  +> com.pengtoolbox.cfw.login.APILoginServlet-1f0f1111@a3223b77==com.pengtoolbox.cfw.login.APILoginServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|        |  |  |  |  +> class com.pengtoolbox.cfw.login.APILoginServlet
|        |  |  |  +> com.pengtoolbox.cfw.servlets.FormServlet-49c386c8@191b7b04==com.pengtoolbox.cfw.servlets.FormServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|        |  |  |  |  +> class com.pengtoolbox.cfw.servlets.FormServlet
|        |  |  |  +> com.pengtoolbox.cfw.servlets.AssemblyServlet-56528192@63148f4e==com.pengtoolbox.cfw.servlets.AssemblyServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|        |  |  |  |  +> class com.pengtoolbox.cfw.servlets.AssemblyServlet
|        |  |  |  +> com.pengtoolbox.cfw.servlets.JARResourceServlet-6e0dec4a@b66c58af==com.pengtoolbox.cfw.servlets.JARResourceServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|        |  |  |     +> class com.pengtoolbox.cfw.servlets.JARResourceServlet
|        |  |  +> servletMappings ServletHandler@3967e60c{STOPPED} size=5
|        |  |     +> [/api/analyzehar]=>com.pengtoolbox.pageanalyzer.servlets.RestAPIServlet-5a955565
|        |  |     +> [/cfw/apilogin]=>com.pengtoolbox.cfw.login.APILoginServlet-1f0f1111
|        |  |     +> [/cfw/formhandler]=>com.pengtoolbox.cfw.servlets.FormServlet-49c386c8
|        |  |     +> [/cfw/assembly]=>com.pengtoolbox.cfw.servlets.AssemblyServlet-56528192
|        |  |     +> [/cfw/jarresource]=>com.pengtoolbox.cfw.servlets.JARResourceServlet-6e0dec4a
|        |  +> No ClassLoader
|        |  +> eventListeners o.e.j.s.ServletContextHandler@20d28811{/pub,null,UNAVAILABLE} size=0
|        |  +> handler attributes o.e.j.s.ServletContextHandler@20d28811{/pub,null,UNAVAILABLE} size=0
|        |  +> context attributes o.e.j.s.ServletContextHandler@20d28811{/pub,null,UNAVAILABLE} size=0
|        |  +> initparams o.e.j.s.ServletContextHandler@20d28811{/pub,null,UNAVAILABLE} size=0
|        +? RewriteHandler@48aaecc3{STOPPED} - STOPPED
|        +? o.e.j.s.h.ContextHandler@7c0c77c7{/auth,null,UNAVAILABLE} - STOPPED
|           += AuthenticationHandler@7adda9cc{STOPPED} - STOPPED
|           |  += o.e.j.s.ServletContextHandler@5cee5251{/,null,UNAVAILABLE} - STOPPED
|           |     += ServletHandler@433d61fb{STOPPED} - STOPPED
|           |     |  +> listeners ServletHandler@433d61fb{STOPPED} size=0
|           |     |  +> filters ServletHandler@433d61fb{STOPPED} size=0
|           |     |  +> filterMappings ServletHandler@433d61fb{STOPPED} size=0
|           |     |  +> servlets ServletHandler@433d61fb{STOPPED} size=19
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.HARUploadServlet-23f7d05d@b54be792==com.pengtoolbox.pageanalyzer.servlets.HARUploadServlet,jsp=null,order=-1,inst=true,async=true - STOPPED
|           |     |  |  |  +> com.pengtoolbox.pageanalyzer.servlets.HARUploadServlet@5c909414
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.DataServlet-1e730495@74f7037f==com.pengtoolbox.pageanalyzer.servlets.DataServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.DataServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.AnalyzeURLServlet-7d3a22a9@299e4f5b==com.pengtoolbox.pageanalyzer.servlets.AnalyzeURLServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.AnalyzeURLServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.ResultViewServlet-1d082e88@25dd8f5==com.pengtoolbox.pageanalyzer.servlets.ResultViewServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.ResultViewServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.CompareServlet-60704c@67cf4c92==com.pengtoolbox.pageanalyzer.servlets.CompareServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.CompareServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.DeleteResultServlet-6b19b79@39942663==com.pengtoolbox.pageanalyzer.servlets.DeleteResultServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.DeleteResultServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.ResultListServlet-2a32de6c@92176f5c==com.pengtoolbox.pageanalyzer.servlets.ResultListServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.ResultListServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.GanttChartServlet-7692d9cc@5471ff5c==com.pengtoolbox.pageanalyzer.servlets.GanttChartServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.GanttChartServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.ManageResultsServlet-75f32542@ae5829a8==com.pengtoolbox.pageanalyzer.servlets.ManageResultsServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.ManageResultsServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.DocuServlet-7f1302d6@8dcde287==com.pengtoolbox.pageanalyzer.servlets.DocuServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.DocuServlet
|           |     |  |  +> com.pengtoolbox.pageanalyzer.servlets.CustomContentServlet-43ee72e6@5bb9c29e==com.pengtoolbox.pageanalyzer.servlets.CustomContentServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.pageanalyzer.servlets.CustomContentServlet
|           |     |  |  +> com.pengtoolbox.cfw.login.LoginServlet-23529fee@3da22327==com.pengtoolbox.cfw.login.LoginServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.cfw.login.LoginServlet
|           |     |  |  +> com.pengtoolbox.cfw.servlets.LogoutServlet-4fe767f3@f59550d4==com.pengtoolbox.cfw.servlets.LogoutServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.cfw.servlets.LogoutServlet
|           |     |  |  +> com.pengtoolbox.cfw.api.CFWAPIServlet-2805c96b@349b255f==com.pengtoolbox.cfw.api.CFWAPIServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.cfw.api.CFWAPIServlet
|           |     |  |  +> com.pengtoolbox.cfw.servlets.userprofile.ChangePasswordServlet-184cf7cf@304a53d==com.pengtoolbox.cfw.servlets.userprofile.ChangePasswordServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.cfw.servlets.userprofile.ChangePasswordServlet
|           |     |  |  +> com.pengtoolbox.cfw.servlets.ConfigurationServlet-2fd6b6c7@fbcfaabc==com.pengtoolbox.cfw.servlets.ConfigurationServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.cfw.servlets.ConfigurationServlet
|           |     |  |  +> com.pengtoolbox.cfw.servlets.admin.UserManagementServlet-5bfa9431@e628f386==com.pengtoolbox.cfw.servlets.admin.UserManagementServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.cfw.servlets.admin.UserManagementServlet
|           |     |  |  +> com.pengtoolbox.cfw.servlets.PermissionsServlet-5db250b4@12edc7c8==com.pengtoolbox.cfw.servlets.PermissionsServlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |  |  +> class com.pengtoolbox.cfw.servlets.PermissionsServlet
|           |     |  |  +> com.pengtoolbox.cfw.servlets.admin.APIUserMgmtSevlet-223f3642@d5ac7bf3==com.pengtoolbox.cfw.servlets.admin.APIUserMgmtSevlet,jsp=null,order=-1,inst=false,async=true - STOPPED
|           |     |  |     +> class com.pengtoolbox.cfw.servlets.admin.APIUserMgmtSevlet
|           |     |  +> servletMappings ServletHandler@433d61fb{STOPPED} size=20
|           |     |     +> [/]=>com.pengtoolbox.pageanalyzer.servlets.HARUploadServlet-23f7d05d
|           |     |     +> [/harupload]=>com.pengtoolbox.pageanalyzer.servlets.HARUploadServlet-23f7d05d
|           |     |     +> [/data]=>com.pengtoolbox.pageanalyzer.servlets.DataServlet-1e730495
|           |     |     +> [/analyzeurl]=>com.pengtoolbox.pageanalyzer.servlets.AnalyzeURLServlet-7d3a22a9
|           |     |     +> [/resultview]=>com.pengtoolbox.pageanalyzer.servlets.ResultViewServlet-1d082e88
|           |     |     +> [/compare]=>com.pengtoolbox.pageanalyzer.servlets.CompareServlet-60704c
|           |     |     +> [/delete]=>com.pengtoolbox.pageanalyzer.servlets.DeleteResultServlet-6b19b79
|           |     |     +> [/resultlist]=>com.pengtoolbox.pageanalyzer.servlets.ResultListServlet-2a32de6c
|           |     |     +> [/ganttchart]=>com.pengtoolbox.pageanalyzer.servlets.GanttChartServlet-7692d9cc
|           |     |     +> [/manageresults]=>com.pengtoolbox.pageanalyzer.servlets.ManageResultsServlet-75f32542
|           |     |     +> [/docu]=>com.pengtoolbox.pageanalyzer.servlets.DocuServlet-7f1302d6
|           |     |     +> [/custom]=>com.pengtoolbox.pageanalyzer.servlets.CustomContentServlet-43ee72e6
|           |     |     +> [/login]=>com.pengtoolbox.cfw.login.LoginServlet-23529fee
|           |     |     +> [/logout]=>com.pengtoolbox.cfw.servlets.LogoutServlet-4fe767f3
|           |     |     +> [/api]=>com.pengtoolbox.cfw.api.CFWAPIServlet-2805c96b
|           |     |     +> [/changepassword]=>com.pengtoolbox.cfw.servlets.userprofile.ChangePasswordServlet-184cf7cf
|           |     |     +> [/configuration]=>com.pengtoolbox.cfw.servlets.ConfigurationServlet-2fd6b6c7
|           |     |     +> [/usermanagement]=>com.pengtoolbox.cfw.servlets.admin.UserManagementServlet-5bfa9431
|           |     |     +> [/usermanagement/permissions]=>com.pengtoolbox.cfw.servlets.PermissionsServlet-5db250b4
|           |     |     +> [/usermanagement/data]=>com.pengtoolbox.cfw.servlets.admin.APIUserMgmtSevlet-223f3642
|           |     +> No ClassLoader
|           |     +> eventListeners o.e.j.s.ServletContextHandler@5cee5251{/,null,UNAVAILABLE} size=0
|           |     +> handler attributes o.e.j.s.ServletContextHandler@5cee5251{/,null,UNAVAILABLE} size=0
|           |     +> context attributes o.e.j.s.ServletContextHandler@5cee5251{/,null,UNAVAILABLE} size=0
|           |     +> initparams o.e.j.s.ServletContextHandler@5cee5251{/,null,UNAVAILABLE} size=0
|           +> No ClassLoader
|           +> eventListeners o.e.j.s.h.ContextHandler@7c0c77c7{/auth,null,UNAVAILABLE} size=0
|           +> handler attributes o.e.j.s.h.ContextHandler@7c0c77c7{/auth,null,UNAVAILABLE} size=0
|           +> context attributes o.e.j.s.h.ContextHandler@7c0c77c7{/auth,null,UNAVAILABLE} size=0
|           +> initparams o.e.j.s.h.ContextHandler@7c0c77c7{/auth,null,UNAVAILABLE} size=0
+> No ClassLoader
+> eventListeners o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} size=0
+> handler attributes o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} size=0
+> context attributes o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} size=0
+> initparams o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} size=0
key: +- bean, += managed, +~ unmanaged, +? auto, +: iterable, +] array, +@ map, +> undefined
```

And below with the SessionHandler(this is not truncated, it is the actuall output).:
```
+= GzipHandler@4b5a5ed1{STOPPED} - STOPPED
|  += org.eclipse.jetty.server.session.SessionHandler1506809545==dftMaxIdleSec=3600 - STOPPED
|     +? org.eclipse.jetty.server.session.DefaultSessionCache@3cc2931c[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STOPPED
|     |  +? org.eclipse.jetty.server.session.NullSessionDataStore@20d28811[passivating=false,graceSec=3600] - STOPPED
|     += RequestHandler@3967e60c{STOPPED} - STOPPED
|        += ServletHandler@60d8c9b7{STOPPED} - STOPPED
|           +> listeners ServletHandler@60d8c9b7{STOPPED} size=0
|           +> filters ServletHandler@60d8c9b7{STOPPED} size=0
|           +> filterMappings ServletHandler@60d8c9b7{STOPPED} size=0
|           +> servlets ServletHandler@60d8c9b7{STOPPED} size=0
|           +> servletMappings ServletHandler@60d8c9b7{STOPPED} size=0
+> No ClassLoader
+> eventListeners o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} size=0
+> handler attributes o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} size=0
+> context attributes o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} size=0
+> initparams o.e.j.s.h.ContextHandler@794cb805{/pageanalyzer,null,UNAVAILABLE} size=0
key: +- bean, += managed, +~ unmanaged, +? auto, +: iterable, +] array, +@ map, +> undefined
```

After my custom RequestHandler there was a HandlerCollection in the first dump. In the dump with the issue there is a ServletHandler.
It would be really helpful if you could support me on this issue. as I really don't have any further ideas where I could look.

I'm currently using jetty 9.4.15 as an embedded server.

**Comment by janbartel** [comment]
I'm confused by your server dump. You seem to have a ContextHandler with an embedded GzipHandler, a RequestHandler and embedded HandlerCollection, which has ServletContextHandlers, ContextHandlers and RewriteHandlers in it.  That's not the kind of ordering I was expecting to see - it should be more like a top level handler like Gzip or RewriteHandler, with a child handler of a ContextHandlerCollection with a number of either ContextHandlers or ServletContextHandlers as children. The ServletContextHandler can automatically chain a ServletHandler, GzipHandler, SessionHandler and SecurityHandler in the right order for you. Here's an example of a Server that has a GzipHandler, RewriteHandler and a couple of ServletContextHandlers so you can see how to use these classes:
```java

import java.nio.file.Path;
import java.nio.file.Paths;

import org.eclipse.jetty.rewrite.handler.RewriteHandler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.ContextHandlerCollection;
import org.eclipse.jetty.server.handler.gzip.GzipHandler;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.util.resource.PathResource;
import org.eclipse.jetty.util.resource.Resource;

public class OneServletContextWithSession
{
    public static Server createServer(int port, Resource baseResource)
    {
        Server server = new Server(port);

        GzipHandler gzipHandler = new GzipHandler();
        gzipHandler.setMinGzipSize(10);
        gzipHandler.addIncludedMimeTypes("text/plain");
        gzipHandler.addIncludedMimeTypes("text/html");

        RewriteHandler rewriteHandler = new RewriteHandler();
        gzipHandler.setHandler(rewriteHandler);
        
        ContextHandlerCollection contexts = new ContextHandlerCollection();
        rewriteHandler.setHandler(contexts);

        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/bar");
        context.addServlet(HelloServlet.class, "/");
        context.setBaseResource(baseResource);
        contexts.addHandler(context);
        
        ServletContextHandler contextB = new ServletContextHandler(ServletContextHandler.SECURITY|ServletContextHandler.SESSIONS);
        contextB.setContextPath("/foo");
        contextB.addServlet("org.eclipse.jetty.embedded.HelloSessionServlet", "/");
        contexts.addHandler(contextB);

        server.setHandler(gzipHandler);
        
        return server;
    }

    public static void main(String[] args) throws Exception
    {
        int port = ExampleUtil.getPort(args, "jetty.http.port", 8080);
        Path dir = Paths.get(System.getProperty("user.dir"));
        PathResource baseResource = new PathResource(dir);
        Server server = createServer(port, baseResource);

        server.start();
        server.dumpStdErr();
        server.join();
    }
}
```

**Comment by xresch** [comment]
Hi janbartel,
thank you for your fast answer.
What you send me above is kind of what I currently have and try to re-eingineer to share the same SessionIDs between two ServletContextHandlers. Thats the root cause of my problem.

Here is more or less what I try to achieve:
[JettyIssue.pptx](https://github.com/eclipse/jetty.project/files/3723461/JettyIssue.pptx)

From your answer it's not really the proper way I try to solve the problem. I currently working more on my knowledge about Session and Context Handling to get better with it.

If you know a better approach to solve my problem I would be glad to get your professional advice.

Thanks and Regards
Reto

**Comment by xresch** [comment]
I found a workaround that works for my case.
Not sure if this is something that sould be done, but it is working as SessionHandler.newHttpSession(request) alsways creates the a Session with the same sessionID. Most probably because the JSESSIONID Cookie is already set on the request.

```
/**************************************************************************************************
 * Propagates session data to all available session context handlers.
 **************************************************************************************************/
public static String propagateSessionDataToOtherContexts(HttpServletRequest request, SessionData data) {
	
	String sessionID = "";
	for(ServletContextHandler handler : servletContextArray) {
		HttpSession session = handler.getSessionHandler().getSession(request.getSession().getId());
		if(session == null) {
			session = handler.getSessionHandler().newHttpSession(request);
		}
		session.setAttribute(CFW.SESSION_DATA, data);
		sessionID = session.getId();
	}
	
	return sessionID;
}
```

Would it make sense to have a feature like a "shared session cache"? For example like this:
` ServletContextHandler servletContext = new ServletContextHandler(ServletContextHandler.SHARED_SESSIONS);`

This could simplify things a lot if you need to create multiple ServletContextHandlers that have to share the same session data.

**Comment by janbartel** [comment]
@xresch the Servlet Specification does not permit session data to be shared between multiple contexts: the session id may be shared, but the session data cannot.  So perhaps you could store your information in a cookie that is visible to all contexts rather than use the session mechanism.
