### ISSUE TITLE
Spin in HttpOutput.close

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4188]
A spin has been reported at:
```
  org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor$GzipBufferCB.process() GzipHttpOutputInterceptor.java:394
  org.eclipse.jetty.util.IteratingCallback.processing() IteratingCallback.java:241
  org.eclipse.jetty.util.IteratingCallback.iterate() IteratingCallback.java:223
  org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.gzip(ByteBuffer, boolean, Callback) GzipHttpOutputInterceptor.java:150
  org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.commit(ByteBuffer, boolean, Callback) GzipHttpOutputInterceptor.java:246
  org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.write(ByteBuffer, boolean, Callback) GzipHttpOutputInterceptor.java:108
  org.eclipse.jetty.server.HttpOutput.write(ByteBuffer, boolean, Callback) HttpOutput.java:259
  org.eclipse.jetty.server.HttpOutput.write(ByteBuffer, boolean) HttpOutput.java:235
  org.eclipse.jetty.server.HttpOutput.close() HttpOutput.java:373
...
  xxx.Xxxxx$1.onWritePossible() ServletOutputStreamWriter.java:276
  org.eclipse.jetty.server.HttpOutput.run() HttpOutput.java:1279
  org.eclipse.jetty.server.handler.ContextHandler.handle(Request, Runnable) ContextHandler.java:1381
  org.eclipse.jetty.server.HttpChannel.handle() HttpChannel.java:495
  org.eclipse.jetty.server.HttpChannel.run() HttpChannel.java:336
  org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(Runnable) QueuedThreadPool.java:782
  org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run() QueuedThreadPool.java:914
  java.lang.Thread.run() Thread.java:834
```

**Comment by gregw** [comment]
Things we know from that stack trace are:

- The close call goes via `write(ByteBuffer content, boolean complete)`, so it is a not an new async close.
 - In order to get to where it does, the execution must have passed a `_state.compareAndSet(state, State.CLOSING)`, which would prevent a spin outside of close which called close over and over and over.
 - There is a `while(true)` in close method itself, but the branch taken in this loop does the change state in the point above, thus also making it unlikely the spin is here.
 - The Gzip interceptor calls `commit(content, complete, callback);`, so this is the first write.. potentially the only write???
 - There is an `IteratingCallback` within the gzip handler - implemented as `org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.GzipBufferCB` - this is the candidate for the spin.

**Comment by gregw** [comment]
Another stack from a spinning thread is:
```
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:733)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:539)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:842)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:914)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor$GzipBufferCB.process(GzipHttpOutputInterceptor.java:402)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.gzip(GzipHttpOutputInterceptor.java:150)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.commit(GzipHttpOutputInterceptor.java:246)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.write(GzipHttpOutputInterceptor.java:108)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:259)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235)
        at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:373)
...
        at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1279)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1381)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:495)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:336)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
        at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)
```

**Comment by gregw** [comment]
From the two stack traces, we know the spin is at least over the following range:
https://github.com/eclipse/jetty.project/blob/jetty-9.4.21.v20190926/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java#L394-L402

This suggests spin could be writing something that always immediately succeeds and then we try writing the same thing again and again?

**Comment by joakime** [comment]
@gregw we had another issue (#4190) mentioning `HttpOutput.close` filed today.

**Comment by gregw** [comment]
@joakime yes that is definitely a new hard bug we introduced with the asynchronous close code.  Simone and I think we have a simple fix for #4190, but it will need a bit more review.
For this spin, we still can't really see how it spins, but we have some suspicions (or suppositions) about some of the code in GzipHandler.... however that hasn't changed and plausible spin mechanism seams unrelated to the actual close changes we made... but perhaps they were just enough to trigger an existing but rare bug in GzipHander.

Proposed approach is to write two branches: 1) with some instrumentation of the current code so we can see more what is happening if a spin can be reproduced; 2) rewrite the code in anycase as it can be written better an more defensively in anycase.   If we can't get any results with 1), then we will probably go with 2) anyway as a hopeful fix.

**Comment by gregw** [comment]
I have built https://github.com/eclipse/jetty.project/tree/jetty-9.4.x-4188-GzipHandler-instrumentations with some instrumentation to help diagnose any spin.

**Comment by gregw** [comment]
#4198 has been merged as a speculative fix.  The code reads better anyway and should be more defensive against spins.   But we should not stop efforts to reproduce on  https://github.com/eclipse/jetty.project/tree/jetty-9.4.x-4188-GzipHandler-instrumentations
