### ISSUE TITLE
Jetty 9.4.18 - Basic auth not working without pre-emptively 

### ISSUE THREAD

**Issue by senthilrajanvs** [eclipse/jetty.project#4223]
Basic auth not working without pre-emptively for large payloads (SOAP / XML), for small payloads it is working. Also large payloads are working if I enable pre-emptive auth  May I know why ?

Jetty version:  9.4.18.v20190429

401 Unauthorized HTTP/1.1
WWW-Authenticate: basic realm="web"
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1

2019-10-19 16:03:53.058:DBUG:oeji.WriteFlusher:qtp733943822-30: ignored: WriteFlusher@43e29d8b{IDLE}->null
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:492)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353)
	at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:215)
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175)
	at org.eclipse.jetty.server.HttpConnection.abort(HttpConnection.java:567)
	at org.eclipse.jetty.server.HttpChannel.abort(HttpChannel.java:966)
	at org.eclipse.jetty.server.HttpChannelOverHttp.abort(HttpChannelOverHttp.java:495)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:432)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:757)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:520)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by senthilrajanvs** [comment]
401 Unauthorized HTTP/1.1
WWW-Authenticate: basic realm="web"
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1

**Comment by sbordet** [comment]
It is an attack to the server to try to send large (or incomplete) payloads that are replied with a 401.

The server will get the request headers and figure out the request is not authenticated.
What should it do now with the request content?
If it is all arrived, the server can discard it.
If it is not all arrived, the server should not bother reading it, for many reasons.
What if the content is GiB of data? What if it is never sent? What if it is sent very slowly? 
And in any case this content will never be presented to the application, so Jetty will just respond with a 401 and close the connection.

You should either preempt the authentication, or you should perform a small pre-request (perhaps a GET rather than a POST) that will guarantee you are authenticated when sending the large request content.

**Comment by senthilrajanvs** [comment]
Thanks Simone for the info. Is the introduced newly in latest Jetty version. I'm not seeing this behavior in Jetty 9.2.24.v2018010
