### ISSUE TITLE
Jetty 9.4.21.v20190926 ResponseWriter#close blocks indefinitely

### ISSUE THREAD

**Issue by jspechts** [eclipse/jetty.project#4279]
We recently tried upgrading from 9.4.8.v20180619 to 9.4.22.v20191022 but we started noticing that our jetty server slowed to a crawl when running an internal automation test suite.

We started downgrading jetty server versions and determined that the issue happens on version 9.4.21.v20190926 and greater.

Attached below is a thread dump and jetty server dump captured after replicating the issue. Any guidance as to how we can further troubleshoot this issue would be appreciated.

[thread-dump-11-6-19.txt](https://github.com/eclipse/jetty.project/files/3817350/thread-dump-11-6-19.txt)
[jetty-server-dump-11-6-19.txt](https://github.com/eclipse/jetty.project/files/3817351/jetty-server-dump-11-6-19.txt)

**Comment by gregw** [comment]
@jspechts Can you tell us what kind of traffic your automated test suite is generating?    Is it some particular tests or all tests?  Can you share the code of the client and server parts of your test?   Can you also define precisely how much it slows down? eg how many ms does the test usually take and how many does it take with 9.4.22?

**Comment by gregw** [comment]
Also is it consuming CPU during the slow tests or just pausing?

**Comment by gregw** [comment]
Looking at your thread dumps:
+ webserver-32 is blocked in `HttpOutput.closed` waiting for webserver-182 to release lock 0x4cd1
+ webserver-182 is blocked in `HttpOutput.write` I'm assuming because the client is not reading data.

webserver-32 looks to be the thread that is trying to complete the write that 182 is doing... so I'm not sure why it has called closed???   @sbordet ?

**Comment by gregw** [comment]
Opened PR #4288

**Comment by jspechts** [comment]
Hi @gregw -

Thanks for the reply.

Unfortunately I cannot share source code but I will try to add more detail.

We have a javascript-based web app which instructs the browser to send dozens of HTTP requests and WebSocket messages to our Jetty server. We use selenium to simulate a web browser which downloads the JS-based web app from our jetty server and runs it. The tests exercise various user-triggered actions on the web app which then triggers the various HTTP requests and WebSocket messages. The tests wait for the web app state / DOM to mutate in an expected way before it passes or fails. Finally, the tests will close the HTTP / WebSocket connections when they are finished.

FWIW - we were also able to replicate the issue manually in a web browser by navigating to the same web app that the automated tests run.

We were not able to replicate the issue when Jetty is run on macOS but we are able to replicate when Jetty is run on Windows 7/10 or Ubuntu 16.

When we replicate the issue, Jetty seems to completely pause indefinitely. Seems like I am able to open connections to the http server port (using telnet) but I am not getting an HTTP response after firing a request. Refreshing browser web pages just sit there spinning and waiting for a response that never seems to come.

On the server end, CPU seems low / normal when the issue is happening.

The only change which seems to cause this problem is the jetty server version bump to 9.4.21 or 9.4.22. No other configuration or code changes were made in our app.

**Comment by jsonyu** [comment]
Hi, 

am also trying to figure out a similar issue when we began using 9.4.21.v20190926.  We'd see 1k++ of "TIME_WAIT" (via netstat) in one server this eventually stops responding to request but resolves itself after 10-15 minutes and then after about an hour it happens again.. this cycles (hanging and resolving) for 3-5 hours until it eventually stops for good. The server is behind an AWS ALB, httptimeout is 30 sec. and MonitoredQueuedThreadPool idle timeout set to 120 sec, selector and acceptor count is not set (ie default).

Doing a server dump shows 1k+ ManagedSelector but with a lot of idle threads.

Attached is a log file with 2 dumps taken a few seconds apart.  Thanks in advance!

[www1a.201911081732.stack.hang.log](https://github.com/eclipse/jetty.project/files/3824088/www1a.201911081732.stack.hang.log)

**Comment by sbordet** [comment]
@jsonyu can you try the code in #4288 and see if it solves the problem for you?

**Comment by jsonyu** [comment]
hi @sbordet thanks for the reco.. we did have old code using GzipOutputStream which does a close() after writing.. we replaced this with GzipHandler.

We pushed out the update to a couple of servers running 9.4.21 and 9.4.22 and seems to be better.. however we occasionally see "org.eclipse.jetty.io.EofException: request lifecycle violation" on both servers.. similar to issue [#4161](https://github.com/eclipse/jetty.project/issues/4161) in our logs:


org.eclipse.jetty.io.EofException: request lifecycle violation
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:746)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:539)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:842)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:914)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:259)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:616)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1263)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1236)
        at com.intigrix.front.utils.ContentTransmitter.showDocument(ContentTransmitter.java:310)
        at com.intigrix.httpserver.ContentLoaderHandler.handle(ContentLoaderHandler.java:626)
        at com.intigrix.httpserver.ContentLoaderHandler.handle(ContentLoaderHandler.java:75)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:737)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386)
        at org.eclipse.jetty.server.HttpChannel$$Lambda$36.0000000000000000.dispatch(Unknown Source)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:560)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.MonitoredQueuedThreadPool$1.run(MonitoredQueuedThreadPool.java:70)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
        at java.lang.Thread.run(Thread.java:819)

Server are running "OpenJDK Runtime Environment (build 1.8.0_232-b09)".  Many thanks!

**Comment by jsonyu** [comment]
hmm.. adding back the final block stopped the "request lifecycle violation" issue:

> 
            OutputStream os = response.getOutputStream();
            try
            {
                IOUtils.copy(is,os);
            }
            finally
            {
                IOUtils.closeQuietly(is);
                IOUtils.closeQuietly(os);
            }

**Comment by jspechts** [comment]
We checked out and built #4288 and ran our automation test suite against it. We are not seeing the deadlock issue anymore. Thanks for the quick fix!

**Comment by joakime** [comment]
Thanks for the followup @jspechts
