### ISSUE TITLE
RequestTest stacktrace

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#434]
This test when run from the command line has multiple port in use exceptions logged:

```
Running org.eclipse.jetty.server.RequestTest
java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.bind(ServerSocket.java:329)
        at org.eclipse.jetty.server.ShutdownMonitor.listen(ShutdownMonitor.java:270)
        at org.eclipse.jetty.server.ShutdownMonitor.start(ShutdownMonitor.java:214)
        at org.eclipse.jetty.server.Server.doStart(Server.java:343)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.RequestTest.init(RequestTest.java:91)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Error binding ShutdownMonitor to port 46408: java.net.BindException: Address already in use
[ShutdownMonitor] STOP.PORT=46408
[ShutdownMonitor] STOP.KEY=foo
2016-03-16 18:25:16.233:INFO:oejs.Server:main: jetty-9.3.8-SNAPSHOT
2016-03-16 18:25:16.235:INFO:oejs.AbstractConnector:main: Started LocalConnector@37091312{HTTP/1.1,[http/1.1]}
2016-03-16 18:25:16.235:INFO:oejs.Server:main: Started @133195ms
2016-03-16 18:25:17.245:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@37091312{HTTP/1.1,[http/1.1]}
java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
...

```

**Comment by gregw** [comment]
marked as high priority as I want zero tolerance of stack traces during a build!

**Comment by sbordet** [comment]
It's not `ShutdownMonitorTest` that fails, but `RequestTest`.

I don't see the stack trace when I run `RequestTest`, and the test does not appear to explicitly set a port, nor does `Server` when starting a `ShutdownMonitor` instance, so it looks like there is a clash on an ephemeral port, which I don't see how it can happen (the OS should have picked a free port).

**Comment by gregw** [comment]
@sbordet yep I'm with you... I can't see how this can be happening and it only happens sometimes for me....  so definitely is a mystery that needs to be investigated.

**Comment by gregw** [comment]
Ah actually it appears the exceptions only happen when running the RequestTest AFTER the ShutdownMonitorTest, which must be leaving something running?

Can reproduce with: 
````bash
cd jetty-server
mvn -Dtest=org.eclipse.jetty.server.ShutdownMonitorTest,org.eclipse.jetty.server.RequestTest
````

**Comment by gregw** [comment]
Added a reset to the ShutdownMonitorTest, but leaving open as the class probably needs some review.

**Comment by sbordet** [comment]
`ShutdownMonitor` is a static singleton created the first time a `Server` is started.
However, creating multiple `Server` instances in the same JVM (as it may happen with tests) seems to be troublesome.

I am actually questioning that `ShutdownMonitor` is a static singleton. We have a clearly defined lifecycle, so I think `ShutdownMonitor` can just become a normal non-static class that is added as a bean to `Server`.

**Comment by gregw** [comment]
I tend to agree.   Statics are rarely the best way to go.

But we have had use cases were multiple servers are started in a JVM that need to all be stopped by a single ShutdownMonitor - so we have to make sure it is simple/trivial/automatic that such a use-case is supported.

**Comment by sbordet** [comment]
Opening a new issue for `ShutdownMonitor`.
