### ISSUE TITLE
Stopping Jetty 9.4.24.x causes java.lang.NoClassDefFoundError exceptions with openjdk11, jetty-maven plugin

### ISSUE THREAD

**Issue by yadvr** [eclipse/jetty.project#4410]
**Jetty version**
Version 9.4.24.v20191120

**Java version**

> java -version
openjdk version "11.0.5-ea" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1, mixed mode, sharing)

**OS type/version**

Ubuntu 19.10
Linux spectre 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description**

We're using jetty-maven-plugin 9.4.24.x with CloudStack (see PR https://github.com/apache/cloudstack/pull/3601) where on stopping the server either using Ctrl+c or jetty:stop, throws `java.lang.NoClassDefFoundError` exceptions which was not seen with previous version of the plugin (for example in CloudStack 4.11, 4.13, master branches):

```
[INFO] Stopped ServerConnector@cabb9c6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] node0 Stopped scavenging
[INFO] Closing Spring root WebApplicationContext
[INFO] Stopped o.e.j.m.p.JettyWebAppContext@f9919a2{/client,[file:///home/rohit/lab/apache/cloudstack/client/target/classes/META-INF/webapp/, file:///home/rohit/lab/apache/cloudstack/client/target/jetty_overlays/release-documentation-2_3_2-docbook_zip/, file:///home/rohit/lab/apache/cloudstack/client/target/jetty_overlays/samples-2_3_2_zip/],UNAVAILABLE}{file:///home/rohit/lab/apache/cloudstack/client/target/classes/META-INF/webapp/}
[INFO] Jetty server exiting.
[..snipped..]
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean PremiumSecondaryStorageManagerImpl
Exception in thread "Thread-20" java.lang.NoClassDefFoundError: org/apache/log4j/spi/ThrowableInformationINFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean APIAuthenticationManagerImpl

INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean com.cloud.network.security.SecurityGroupManagerImpl2
	at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:165)
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean AccountManagerImpl
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.error(Category.java:322)INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean HighAvailabilityManagerExt
Impl
	at com.cloud.cluster.ClusterServiceServletContainer$ListenerThread.run(ClusterServiceServletContainer.java:168)
INFO  [c.c.h.HighAvailabilityManagerImpl] (HA-Worker-2:null) (logid:) Time to go home!
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.spi.ThrowableInformation
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean SimulatorManagerImpl
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean ExternalNetworkDeviceManag
erImpl
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:543)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean LoadBalancingRulesManagerI
mpl
	... 4 more
INFO  [c.c.h.HighAvailabilityManagerImpl] (HA-Worker-4:null) (logid:) Time to go home!
INFO  [c.c.h.HighAvailabilityManagerImpl] (HA-Worker-1:null) (logid:) Time to go home!
INFO  [c.c.h.HighAvailabilityManagerImpl] (HA-Worker-0:null) (logid:) Time to go home!
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean VpcVirtualNetworkApplianceManagerImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean Baremetal Vlan Manager
INFO  [c.c.h.HighAvailabilityManagerImpl] (HA-Worker-3:null) (logid:) Time to go home!
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean RoleManagerImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean NetworkModelImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean ConsoleProxyManagerImpl
INFO  [c.c.c.ConsoleProxyManagerImpl] (SpringContextShutdownHook:null) (logid:) Stop console proxy manager
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean DiagnosticsServiceImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean CapacityManagerImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean MockStorageManagerImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean Volume Manager
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean ProjectManagerImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean DeploymentPlanningManagerImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean StatsCollector
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean CAManagerImpl
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean null
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (SpringContextShutdownHook:null) (logid:) stopping bean null
Exception in thread "SpringContextShutdownHook" java.lang.NoClassDefFoundError: org/apache/log4j/spi/ThrowableInformation
	at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:165)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.log(Log4jLoggerAdapter.java:581)
	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.warn(LogAdapter.java:442)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1024)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
```

**Comment by joakime** [comment]
It looks like you are in the shutdown process and then you have a ClassNotFoundException on a logger.

This is not a new issue, and the fact that you haven't seen it before doesn't mean much.

See Issues: #1356 and #1409

In short, on Jetty stop/shutdown the maven process yanks the classloader out from underneath the Jetty threads (and Spring threads) leaving random errors in its wake.
This can happen with any version of Jetty and the Jetty Maven Plugin.
It's random, and can happen at any time, with no work around that we are aware of.

Some people have reported better behavior with newer version of Maven.

**Comment by yadvr** [comment]
Thanks for replying @joakime - is there any workaround/solution for this? I'll also consult maven developers.

**Comment by joakime** [comment]
@olamy (a maven developer), do you know of a work around for this?

**Comment by yadvr** [comment]
Hey @olamy (also one of CloudStack's PMC members) - ^^ what @joakime said :)

**Comment by olamy** [comment]
@rhtyd What Maven version are you using? I vaguely remember similar issues (but cannot find references) which should be fixed in last version of Maven.
I guess it's annoying but not blocker?

**Comment by yadvr** [comment]
@olamy I'm using mvn 3.6.2 with openjdk11.0.5. Yes, it's annoying and certainly not a blocker.
