### ISSUE TITLE
EofException when reloading any JSP in Jetty 9.3.8

### ISSUE THREAD

**Issue by ofrias** [eclipse/jetty.project#443]
When reloading any JSP several times very quickly the exception below is fired.  Since reloading a page is normal behavior this exception should not be fired (or should be catched).

```
org.apache.jasper.JasperException: org.eclipse.jetty.io.RuntimeIOException: org.eclipse.jetty.io.EofException: reset
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:478)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
        at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:108)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1162)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
        ...
        ...
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1162)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
        ...
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        ...
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        ....
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1162)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:462)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:518)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:262)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:102)
        at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:97)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jetty.io.RuntimeIOException: org.eclipse.jetty.io.EofException: reset
        at org.eclipse.jetty.server.ResponseWriter.isOpen(ResponseWriter.java:133)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:202)
        at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:109)
        at org.apache.jasper.runtime.PageContextImpl.release(PageContextImpl.java:184)
        at org.apache.jasper.runtime.JspFactoryImpl.internalReleasePageContext(JspFactoryImpl.java:120)
        at org.apache.jasper.runtime.JspFactoryImpl.releasePageContext(JspFactoryImpl.java:75)
        at org.apache.jsp.WEB_002dINF.jsp.hotel_005fdetail_jsp._jspService(hotel_005fdetail_jsp.java:1612)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
        ... 71 more
Caused by: org.eclipse.jetty.io.EofException: reset
        at org.eclipse.jetty.http2.HTTP2Flusher$Entry.reset(HTTP2Flusher.java:340)
        at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:221)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
        at org.eclipse.jetty.http2.HTTP2Session.frame(HTTP2Session.java:622)
        at org.eclipse.jetty.http2.HTTP2Session.data(HTTP2Session.java:612)
        at org.eclipse.jetty.http2.HTTP2Stream.data(HTTP2Stream.java:101)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:187)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:105)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:668)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:722)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor$GzipBufferCB.process(GzipHttpOutputInterceptor.java:369)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.gzip(GzipHttpOutputInterceptor.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.commit(GzipHttpOutputInterceptor.java:228)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.write(GzipHttpOutputInterceptor.java:103)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:179)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:415)
        at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
        at org.eclipse.jetty.server.Utf8HttpWriter.write(Utf8HttpWriter.java:183)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:203)
        at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:109)
        at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:326)
        at java.io.Writer.write(Writer.java:157)
        at org.apache.jasper.runtime.JspWriterImpl.print(JspWriterImpl.java:461)
        at org.apache.taglibs.standard.tag.common.fmt.BundleSupport.doEndTag(BundleSupport.java:102)
        at org.apache.jsp.WEB_002dINF.jsp.hotel_005fdetail_jsp._jspService(hotel_005fdetail_jsp.java:1592)
        ... 74 more
```

We are using Jetty 9.3.8.

**Comment by joakime** [comment]
Looks like you had an active HTTP/2 connection when you reloaded the webapp and/or JSP.
That would be a normal and expected exception in that scenario.

**Comment by ofrias** [comment]
We have a public site using Jetty + HTTP/2 and we see these exceptions very frequently.  I understand that they happen when a user reloads a page while it is still loading.  But this is a normal behavior for users.  Why do we have to log this as an exception?  This fills the logs with exceptions that should be ignored.

**Comment by joakime** [comment]
EofException is a controversial one.  We've had it this way, to log occurrences with stacktraces for a while.  Then briefly squelched it for a single line for a few releases in the Jetty 7 days.  We received far far more feedback that the squelching was hurting troubleshooting and returned it to its current state.  Log it, with a stacktrace.

If you setup an advanced logging framework (slf4j + logback), you can filter that event from being logged with a stacktrace in your logs.

**Comment by ofrias** [comment]
Currently Jetty implementation of this call:

getServletConfig().getServletContext().getRequestDispatcher("mypage.jsp").forward(request, response);

is indeed firing a exception (not only logging something) in a scenario that cannot be considered an exception in normal web application behavior.  It is quite standard to try-catch this call to detect problems in JSP execution:

```
try {
    getServletConfig().getServletContext().getRequestDispatcher("mypage.jsp").forward(request, response);
} catch (Throwable th) {
    // report the problem
}
```

So the problem is that currently Jetty users are forced to workaround this issue by ignoring this kind of exceptions.  Otherwise we get spurious error reports.


A similar exception is fired when forwarding the request to a static file (an image in this case) and reloading the page:

```
java.nio.channels.ClosedChannelException
        at org.eclipse.jetty.http2.HTTP2Flusher.append(HTTP2Flusher.java:105)
        at org.eclipse.jetty.http2.HTTP2Session.frame(HTTP2Session.java:620)
        at org.eclipse.jetty.http2.HTTP2Session.data(HTTP2Session.java:612)
        at org.eclipse.jetty.http2.HTTP2Stream.data(HTTP2Stream.java:101)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:187)
        at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.send(HttpTransportOverHTTP2.java:105)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:668)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:722)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.commit(GzipHttpOutputInterceptor.java:173)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.write(GzipHttpOutputInterceptor.java:103)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:179)
        at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:676)
        at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:776)
        at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:654)
        at org.eclipse.jetty.servlet.DefaultServlet.sendData(DefaultServlet.java:971)
        at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:527)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1162)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
        ...
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1162)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
        ...
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        ...
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        ...
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        ...
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1162)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:462)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:518)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:262)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:102)
        at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:97)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
```


From my point of view these exceptions should never reach web application developers code because they are fired in situations that happen during normal web application usage (and very frequently indeed).

**Comment by janbartel** [comment]
Hi Oscar,

Regarding the EOF exception with the jsp page:  if you look at the signature of JspWriter, all the output methods allow for the throwing of an IO exception. So its perfectly normal that when an IO exception occurs, it is thrown back to the application. If the application doesn't handle it, then the container will. Now, jetty has code in place to detect the EOF exception and do less verbose logging of it. However, it seems that the jsp page is catching the EOF exception and wrapping it as a JspException, which would seem to evade our detection code.  So we can look at improving the detection for this case. In the meanwhile, as @joakime suggests you might like to configure your logging system to reduce the log output for these. 

Regarding the ClosedChannelException, we can also expand the detection and less verbose logging for HTTP2 exceptions.

I note that in master it appears that the special detection code is in fact missing, so I'm making note if it here so that it gets fixed at the same time the extra detection is added to the jetty-9.3.x branch.

**Comment by ofrias** [comment]
From my point of view it is important to distinguish between logs and exceptions:

1) with regard to logs, I agree that Jetty should log everything that could be relevant in any scenario (using the appropriate severity).  So nothing to be changed with respect to logs.

2) with regard to exceptions, my point is that Jetty should never throw an exception in a situation which is not exceptional at all.  In fact it is as common as reloading a webpage.  This is what I understand that should be fixed.  User code should not have to deal with events that belong to a lower level of abstraction.  Do you agree with this?  Are the planned changes going to remove these exceptions?

**Comment by gregw** [comment]
In terms of writing a response, a closed connection is exceptional.  If we do not throw then an application may waste resources generating and writing more content that cannot be sent

**Comment by Samaa-Fayed** [comment]
Is it possible to know in which jetty version is this bug solved?

**Comment by sbordet** [comment]
@Samaa-Fayed this issue is quite old. Please use the latest version of Jetty and report if you still have problems in a new issue, with the exact stack trace.

**Comment by Samaa-Fayed** [comment]
@sbordet Thank you for your fast response, the application I am working on is built on top of eclipse, so the version of jetty is dependent on the eclipse used, for now it is neon which uses jetty 9.3.9 (which has the problem); I need to know what version is the fix in because it would matter for plugin dependencies when upgrading to a newer version.

**Comment by sbordet** [comment]
@Samaa-Fayed there is no "fix" for this issue because it's not an issue. If a client is reloading a page while the server is writing, the server application will see an I/O exception. 
Jetty wraps the `RST_STREAM` sent by the client with a `EofException` which is an exception that is logged at DEBUG level only in Jetty, and reported to the application.
There is not much else we can do.

**Comment by Samaa-Fayed** [comment]
@sbordet Is it possible to know the code change?

**Comment by joakime** [comment]
@Samaa-Fayed there's been no code change surrounding EofException specifically, but there has been tons of other code changes that could have likely impacted your results.
