### ISSUE TITLE
Jetty-runner can't find or load class

### ISSUE THREAD

**Issue by jrAtAustin** [eclipse/jetty.project#4449]
9.4.9.v20180320

openjdk version "1.8.0_232"

Mac OS Catalina 10.15.2 

I am getting the following exception running jetty-runner with Cloudbees jetty-redis session management.

`2019-12-28 17:09:59.634:WARN:oejx.XmlConfiguration:main: Config error at <Call name="addBean"><Arg>|          <New id="sessionDataStoreFactory" class="com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory"><Set name="jedisPool">|                  <Ref refid="jedisPool"/>|              </Set></New>|      </Arg></Call> java.lang.ClassNotFoundException: com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory in file:/Users/user/bin/jetty.xml
java.lang.ClassNotFoundException: com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:65)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:834)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1309)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1214)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$500(XmlConfiguration.java:326)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$AttrOrElementNode.getList(XmlConfiguration.java:1442)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$AttrOrElementNode.getList(XmlConfiguration.java:1417)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:780)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:472)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:354)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:297)
	at org.eclipse.jetty.runner.Runner.configure(Runner.java:329)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:570)
Usage: java [-Djetty.home=dir] -jar jetty-runner.jar [--help|--version] [ server opts] [[ context opts] context ...] 
Server opts:
 --version                           - display version and exit
 --log file                          - request log filename (with optional 'yyyy_mm_dd' wildcard
 --out file                          - info/warn/debug log filename (with optional 'yyyy_mm_dd' wildcard
 --host name|ip                      - interface to listen on (default is all interfaces)
 --port n                            - port to listen on (default 8080)
 --stop-port n                       - port to listen for stop command (or -DSTOP.PORT=n)
 --stop-key n                        - security string for stop command (required if --stop-port is present) (or -DSTOP.KEY=n)
 [--jar file]*n                      - each tuple specifies an extra jar to be added to the classloader
 [--lib dir]*n                       - each tuple specifies an extra directory of jars to be added to the classloader
 [--classes dir]*n                   - each tuple specifies an extra directory of classes to be added to the classloader
 --stats [unsecure|realm.properties] - enable stats gathering servlet context
 [--config file]*n                   - each tuple specifies the name of a jetty xml config file to apply (in the order defined)
Context opts:
 [[--path /path] context]*n          - WAR file, web app dir or context xml file, optionally with a context path
`

Here is the command line I used to invoke jetty-runner:
`/Users/me/.sdkman/candidates/java/current/bin/java -Dgrails.env=development -Dorg.eclipse.jetty.server.Request.maxFormKeys=2000 -Djetty.base=jetty/homebase -Djetty.home=jetty/homebase -Djava.io.tmpdir=/Users/johnruggentaler/jetty/tmpdir -Dorg.eclipse.jetty.server.session.LEVEL=DEBUG -Xmx4096m -Xms4096m -jar jetty/jetty-runner.jar --config bin/jetty.xml --port 8080 --stop-port 8081 --stop-key killit --lib jetty/lib --log logs/yyyy_mm_dd-requests.log --out logs/yyyy_mm_dd-output.log context.xml`

Here is my lib directory contents:
`-rw-rw-rw-@ 1  staff   25499 Dec 28 07:30 jetty-redis-sessions-9.4.2.jar`
`-rw-rw-rw-@ 1  staff  553762 Dec 28 07:30 jedis-2.9.0.jar`
`-rw-rw-rw-@ 1  staff  111969 Dec 28 07:30 commons-pool2-2.4.2.jar`

Here is the list of the contents of the Cloudbees jar

`jar -tvf jetty/lib/jetty-redis-sessions-9.4.2.jar`
`  1812 Fri May 10 16:32:52 CDT 2019 META-INF/MANIFEST.MF`
`     0 Fri May 10 16:32:52 CDT 2019 META-INF/`
`     0 Fri May 10 16:32:52 CDT 2019 org/`
`     0 Fri May 10 16:32:52 CDT 2019 org/eclipse/`
`     0 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/`
`     0 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/`
`     0 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/`
`     0 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/transcoders/`
`     0 Fri May 10 16:32:52 CDT 2019 META-INF/maven/`
`     0 Fri May 10 16:32:52 CDT 2019 META-INF/maven/com.cloudbees.jetty.redis/`
`     0 Fri May 10 16:32:52 CDT 2019 META-INF/maven/com.cloudbees.jetty.redis/jetty-redis-sessions/`
`  2052 Fri May 10 16:32:50 CDT 2019 about.html`
` 10594 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/RedisSessionDataMap.class`
`  2937 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/transcoders/TranscoderUtils.class`
`  6275 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/RedisSessionDataMapFactory.class`
`  3185 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/transcoders/CachedData.class`
`  9228 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/transcoders/BaseSerializingTranscoder.class`
`  1174 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/transcoders/CompressionMode.class`
`  6336 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/transcoders/SerializingTranscoder.class`
`   915 Fri May 10 16:32:52 CDT 2019 org/eclipse/jetty/redis/session/transcoders/BaseSerializingTranscoder$1.class`
`  5436 Fri May 10 16:32:26 CDT 2019 META-INF/maven/com.cloudbees.jetty.redis/jetty-redis-sessions/pom.xml`
`   137 Fri May 10 16:32:52 CDT 2019 META-INF/maven/com.cloudbees.jetty.redis/jetty-redis-sessions/pom.properties`

Here is my context.xml contents:

`<?xml version="1.0"  encoding="ISO-8859-1"?>`
`<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">`
` `
`<Configure class="org.eclipse.jetty.webapp.WebAppContext">`
` `
`  <Set name="contextPath">/</Set>`
`  <Set name="war">current.war</Set>`
` `
`  <Set name="securityHandler">`
`    <New class="org.eclipse.jetty.security.ConstraintSecurityHandler">`
`      <Set name="sessionRenewedOnAuthentication">false</Set>`
`    </New>`
`  </Set>`
` `
`    <New id="jedisPoolConfig" class="redis.clients.jedis.JedisPoolConfig"/>`
`    <New id="jedisPool" class="redis.clients.jedis.JedisPool">`
`        <Arg>`
`            <Ref refid="jedisPoolConfig"/>`
`        </Arg>`
`        <Arg>`
`            <Property name="com.cloudbees.analytics.sse.session.redis.host" default="localhost"/>`
`        </Arg>`
`        <Arg type="int">`
`            <Property name="com.cloudbees.analytics.sse.session.redis.port" default="6379"/>`
`        </Arg>`
`        <Arg type="boolean">`
`            <Property name="com.cloudbees.analytics.sse.session.redis.use.ssl" default="false"/>`
`        </Arg>`
`    </New>`
` `
`    <Call name="addBean">`
`        <Arg>`
`            <New id="sessionDataStoreFactory" class="com.cloudbees.jetty.session.redis.RedisSessionDataStoreFactory">`
`                <Set name="jedisPool">`
`                    <Ref refid="jedisPool"/>`
`                </Set>`
`            </New>`
`        </Arg>`
`    </Call>`
`</Configure>`

Thanks in advance!

**Comment by jrAtAustin** [comment]
Closing this issue. My configuration is incorrect. There are two similarly named Redis session store projects jetty-redis and jetty-redis-sessions.
