### ISSUE TITLE
High CPU Usage in accept0 from thread qtp526833889-24-acceptor-0@367d34c0-ServerConnector@1c628f6a{SSL,[ssl, http/1.1]}{0.0.0.0:8443}

### ISSUE THREAD

**Issue by git-jamie-s** [eclipse/jetty.project#4474]
Hi,

I have a server running Jetty 9.4.21, and occasionally, I will have to restart the process to get it back to normal CPU usage.
It does not appear to be doing anything useful at the time, really.

Using JMX, I am able to see the CPU usage.
This thread has been pegged at 100% CPU for 60 minutes and counting.

![Screenshot_2020-01-13_10-11-45](https://user-images.githubusercontent.com/44268363/72267328-e1cc3800-35ed-11ea-91e9-6c03bc108085.png)

Here is the stack trace of that thread:

> qtp526833889-24-acceptor-0@367d34c0-ServerConnector@1c628f6a{SSL,[ssl, http/1.1]}{0.0.0.0:8889}" - Thread t@24
>   java.lang.Thread.State: RUNNABLE
>	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
>	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
>	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
>	- locked <3f358da5> (a java.lang.Object)
>	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:385)
>	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:701)
>	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
>	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
>	at java.lang.Thread.run(Thread.java:748)
>
>   Locked ownable synchronizers:
>	- None

[threads.txt](https://github.com/eclipse/jetty.project/files/4054293/threads.txt)

I will be upgrading to the latest, 9.4.25, to see if that does anything.

There is the possibility, I suppose, that a client is connected and going crazy, I am looking at that as well.

Any help on this would be greatly appreciated!

**Comment by git-jamie-s** [comment]
Upon further investigation, the accept() thread is always busy, even in quiet environments.
