### ISSUE TITLE
Jetty Httpclient EOfexception during loadtest

### ISSUE THREAD

**Issue by s0j0urn** [eclipse/jetty.project#452]
I am doing small load tests using jetty Httpclient on Raspberry Pi. The server being used is h2o and is deployed on another pi on the network. 

Let's say I invoke 6 clients in parallel: 

`seq 10 | parallel -j6 -n0 --joblog /tmp/joblog java -jar httpasynchronousclient.jar all_urls.txt >> error_logs.txt 2>&1`

`all_urls.txt`just contain a set of urls supplied as argument to client

However, I am getting Eofexceptions in case I run more than 4 clients in parallel:

```
2016-03-22 16:11:07.095:INFO::main: Logging initialized @27911ms
org.eclipse.jetty.io.EofException
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:197)
    at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:419)
    at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
    at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:141)
    at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.process(HttpSenderOverHTTP.java:230)
    at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
    at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
    at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:58)
    at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:204)
    at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:79)
    at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:202)
    at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:201)
    at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:82)
    at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:37)
    at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:27)
    at org.eclipse.jetty.client.PoolingHttpDestination.process(PoolingHttpDestination.java:162)
    at org.eclipse.jetty.client.PoolingHttpDestination.process(PoolingHttpDestination.java:113)
    at org.eclipse.jetty.client.PoolingHttpDestination.send(PoolingHttpDestination.java:97)
    at org.eclipse.jetty.client.PoolingHttpDestination.succeeded(PoolingHttpDestination.java:84)
    at org.eclipse.jetty.client.DuplexConnectionPool.proceed(DuplexConnectionPool.java:171)
    at org.eclipse.jetty.client.DuplexConnectionPool$1.succeeded(DuplexConnectionPool.java:148)
    at org.eclipse.jetty.client.DuplexConnectionPool$1.succeeded(DuplexConnectionPool.java:139)
    at org.eclipse.jetty.client.HttpClient$1$1.succeeded(HttpClient.java:567)
    at org.eclipse.jetty.client.HttpClient$1$1.succeeded(HttpClient.java:563)
    at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:90)
    at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:307)
    at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:414)
    at org.eclipse.jetty.io.ManagedSelector.access$1600(ManagedSelector.java:56)
    at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:587)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
    at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:494)
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177)
    ... 33 more
```

Complete error_logs.txt: 
[error_logs.txt](https://github.com/eclipse/jetty.project/files/184508/error_logs.txt)

Httpclient code: [HTTPClient.java](https://github.com/s0j0urn/Http.client/blob/master/src/main/java/http/client/HttpClientBenchMark.java)

**Comment by joakime** [comment]
When you get these EOF exceptions, how are your file handles at that point in time?
Are you consuming all of them?  Have any free?
What's the status of the various connections? (netstat?)

**Comment by joakime** [comment]
What version of Jetty's HttpClient?

**Comment by s0j0urn** [comment]
Client Version is `9.3.7.v20160115`.

I'll just let you know netstat status as well. 
Not sure how to check if any file handles are free. Will you please point me to a reference how can I check it ?

**Comment by sbordet** [comment]
@s0j0urn I recommend that you run with very large timeouts, as I suspect that those exceptions are due to idle timeouts, in turn due to the fact that Raspberry Pi does not have a powerful CPU.
Large timeouts in both client and server.

I also suggest to update to latest 9.3.8.

The exceptions reported show that the client is trying to write bytes on the network, but the connection has been closed asynchronously. This can be caused by idle timeouts, as said above, or by the server closing the connection.

Only a network trace can tell what party is closing the connection. Alternatively, run with `org.eclipse.jetty.client` DEBUG logging, you should see what happens just before those exceptions and understand if it's something happening on the client or on the server.

**Comment by s0j0urn** [comment]
@sbordet I increased the timeout limit of the client to 50 seconds and updated the client version to 9.3.8.
However, the error still occurs. I am able to load the server with equal or more load using h2load than what I am doing with jetty client. So, I assume the server is not closing the connection.

@joakime From what I read/googled, by file handler you meant file descriptors. Following, [Find Out How Many File Descriptors Are Being Used](http://www.cyberciti.biz/tips/linux-procfs-file-descriptors.html), `sysctl fs.file-nr` gives me about 700 (at maximum) in use when the client processes are running.

Netstat logs on client end: [client_end_netstat_status.txt](https://github.com/eclipse/jetty.project/files/185195/client_end_netstat_status.txt)
Netstat logs on server end: [server_end_netstat_status.txt](https://github.com/eclipse/jetty.project/files/185196/server_end_netstat_status.txt)

**Comment by sbordet** [comment]
@s0j0urn, 

`h2load` performs HTTP/2 load on the server, while the stack trace you report shows that you are using `HttpClient` with HTTP/1.1. 

Is that what you meant to do, to use `HttpClient` in HTTP/1.1 mode ?

**Comment by s0j0urn** [comment]
Hello Simone ,

H2load can be used to do http/1.1 benchmark as well. At present, I have
tested both h2load and jetty http client for http/1.1 only.

**Comment by sbordet** [comment]
@s0j0urn any chance you can get a network dump of the traffic ?

Alternatively, can you turn on DEBUG logging for the client and attach the log here ?

Can you detail when it happens ?
If you use just one client and one connection, does it happen ?
If you use multiple clients and one connection, does it happen ?
If you use one client and multiple connections, does it happen ?

Thanks !

**Comment by s0j0urn** [comment]
@sbordet 

> any chance you can get a network dump of the traffic ?

Will do that. May take time as the server is currently being used by others.

> Alternatively, can you turn on DEBUG logging for the client and attach the log here ?

You asked me for this in a previous comment as well. I googled how I can do that for the client but did not find something that can help me out. It will be great if you can point me to a reference and I'll quickly do that.

> Can you detail when it happens ?
If you use just one client and one connection, does it happen ?
If you use multiple clients and one connection, does it happen ?
If you use one client and multiple connections, does it happen ?

From what I have observed till now, It happens if I launch more than 4 clients in parallel. Each client makes 6 TCP connections to the server and can queue at max 1024 * 1024 requests to server.

**Comment by sbordet** [comment]
To turn on DEBUG logging for the client, put into the client classpath a file called `jetty-logging.properties` with the following content:

```
org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog
org.eclipse.jetty.client.LEVEL=DEBUG
```

From my limited experience with h2load (with HTTP/2), what it does was to pipeline requests on a single connection. This is normal for HTTP/2, but I wonder how does it work for HTTP/1.1 ? How many connection would it open ?

**Comment by s0j0urn** [comment]
>  I wonder how does it work for HTTP/1.1 ? How many connection would it open ?

Yes, for HTTP/1.1 as well it opens only one connection by default. But, it allows controlling the number of connection being. So, you can make 6 connections to simulate a single HTTP/1.1 client that fetches the same load.

**Comment by s0j0urn** [comment]
@sbordet 

Sorry for such a long delay in following up on this issue.

I enabled the client logging as suggested by you. Meanwhile, I also made a few modifications to the client. Instead of running it through `parallel` command, I am now using `ExecutorService` to launch multiple threads (each thread acting as one client) concurrently which then executes the requests. Each thread processes 219 requests and listens to their response. 

I was able to reproduce the issue with 10 threads/clients running concurrently. You can see in `requests_successful.txt` that for each of the client some of the requests have failed. Detailed clients logs are in the other file. 

Please find the logs attached:
[requests_successful.txt](https://github.com/eclipse/jetty.project/files/209863/requests_succesful.txt)
[10_clients_logs.txt](https://github.com/eclipse/jetty.project/files/209862/10_clients_logs.txt)

**Comment by sbordet** [comment]
Lowering priority due to Raspberry Pi environment.
