### ISSUE TITLE
HTTP2Flusher: Failure generating frame HeadersFrame

### ISSUE THREAD

**Issue by RamyaNaik847** [eclipse/jetty.project#4531]
**Jetty version**
9.4.9.v20180320
**Java version**
java version "1.8.0_162"
**OS type/version**
windows
**Description**
Hi 

I am using Jmeter4.x to send HTTP2 requests over tlsv1.2.

My usecase is to send one first Post request followed by PUT request.

I am trying to send PUT request over TLSv1.2 but i get the below NPE. I could successfully send POST request over TLSv1.2. What could be the issue.

```
2020-01-30 11:20:57,857 DEBUG o.e.j.i.IdleTimeout: HTTP2Stream@6e0ad605#1{sendWindow=0,recvWindow=0,reset=false,NOT_CLOSED,age=0,attachment=null} idle timeout check, elapsed: 0 ms, remaining: 30000 ms
2020-01-30 11:20:57,857 DEBUG o.e.j.h.HTTP2Session: Created local HTTP2Stream@6e0ad605#1{sendWindow=65535,recvWindow=65535,reset=false,NOT_CLOSED,age=0,attachment=null}
2020-01-30 11:20:57,857 DEBUG o.e.j.h.HTTP2Flusher: Appended HeadersFrame@6a00f19f#1{end=true}, frames=1
2020-01-30 11:20:57,857 DEBUG o.e.j.h.HTTP2Flusher: Flushing HTTP2ClientSession@1bd5fb2f{l:/10.136.181.113:58759 <-> r:/100.69.67.244:8445,sendWindow=65535,recvWindow=16777216,streams=1,NOT_CLOSED,null}
2020-01-30 11:20:57,857 DEBUG o.e.j.h.HTTP2Flusher: Processing HeadersFrame@6a00f19f#1{end=true}
2020-01-30 11:20:57,857 DEBUG o.e.j.h.h.HpackEncoder: CtxTbl[151217fd] encoding
2020-01-30 11:20:57,858 DEBUG o.e.j.h.HTTP2Flusher: Failure generating frame HeadersFrame@6a00f19f#1{end=true}
java.lang.NullPointerException: null
	at org.eclipse.jetty.http2.hpack.HpackEncoder.encode(HpackEncoder.java:156) ~[http2-hpack-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.http2.generator.HeadersGenerator.generateHeaders(HeadersGenerator.java:72) ~[http2-common-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.http2.generator.HeadersGenerator.generate(HeadersGenerator.java:56) ~[http2-common-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.http2.generator.Generator.control(Generator.java:80) ~[http2-common-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.http2.HTTP2Session$ControlEntry.generate(HTTP2Session.java:1167) ~[http2-common-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:177) [http2-common-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:365) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:244) [http2-common-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.io.WriteFlusher$PendingState.complete(WriteFlusher.java:272) [jetty-io-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:403) [jetty-io-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:121) [jetty-io-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
2020-01-30 11:20:57,859 DEBUG o.e.j.h.HTTP2Flusher: Failing, active/queued=1/0
2020-01-30 11:20:57,859 DEBUG o.e.j.h.HTTP2Session: Removed local HTTP2Stream@6e0ad605#1{sendWindow=65535,recvWindow=65535,reset=false,CLOSED,age=2,attachment=null}
2020-01-30 11:20:57,860 DEBUG o.e.j.h.HTTP2Flusher: Terminated
2020-01-30 11:20:57,860 DEBUG o.e.j.h.HTTP2Session: Disconnecting HTTP2ClientSession@1bd5fb2f{l:/10.136.181.113:58759 <-> r:/100.69.67.244:8445,sendWindow=65535,recvWindow=16777216,streams=0,CLOSED,null}
2020-01-30 11:20:57,860 DEBUG o.e.j.i.AbstractEndPoint: close DecryptedEndPoint@4972aa57{/100.69.67.244:8445<->/10.136.181.113:58759,OPEN,fill=FI,flush=-,to=5/30000}->HTTP2ClientConnection@3ac70e5b->SocketChannelEndPoint@95bf27a{/100.69.67.244:8445<-
```

**Comment by sbordet** [comment]
Do you get the same error with Jetty 9.4.26?

**Comment by RamyaNaik847** [comment]
Yes, i have tried with 9.4.26 jars as well. Same issue is observed. Attached the log where it works for POST request but not for PUT request.
[jmeter.log](https://github.com/eclipse/jetty.project/files/4137540/jmeter.log)

**Comment by sbordet** [comment]
The NPE happens because some code is calling `HpackEncoder.encode(ByteBuffer buffer, MetaData metadata)` with `metadata=null`.

It is unlikely we do this in the Jetty high-level `HttpClient`.

If JMeter is using directly the low-level `HTTP2Client`, which is what they seem to do from the stack trace, this is likely a JMeter issue.

**Comment by RamyaNaik847** [comment]
Okay thanks for the clarification.
