### ISSUE TITLE
After upgrading the Java 1.8.0_242, Jetty server is failing to start 

### ISSUE THREAD

**Issue by vinayakbmalagatti** [eclipse/jetty.project#4569]
Below is the exception with Java version 1.8.0_242, but same code works with 1.8.0_201.
Tried with the Jetty version 9.4.26.v20200117
```
Defaulting Uptime to NOIMPL due to (java.lang.UnsupportedOperationException) Implementation not available in this environment
09:02:46.265 [main] org.eclipse.jetty.util.log INFO  - Logging initialized @-1ms to org.eclipse.jetty.util.log.Slf4jLog
09:02:46.353 [main] org.eclipse.jetty.server.Server INFO  - jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_242-b08
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.net.ServerSocket.setImpl(ServerSocket.java:303)
        at java.net.ServerSocket.<init>(ServerSocket.java:102)
        at sun.nio.ch.ServerSocketAdaptor.<init>(ServerSocketAdaptor.java:72)
        at sun.nio.ch.ServerSocketAdaptor.create(ServerSocketAdaptor.java:63)
        at sun.nio.ch.ServerSocketChannelImpl.socket(ServerSocketChannelImpl.java:106)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.apache.cxf.transport.http_jetty.JettyHTTPServerEngine.addServant(JettyHTTPServerEngine.java:473)
        at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.activate(JettyHTTPDestination.java:187)
        at org.apache.cxf.transport.AbstractObservable.setMessageObserver(AbstractObservable.java:53)
        at org.apache.cxf.binding.AbstractBindingFactory.addListener(AbstractBindingFactory.java:95)
        at org.apache.cxf.jaxrs.JAXRSBindingFactory.addListener(JAXRSBindingFactory.java:88)
        at org.apache.cxf.endpoint.ServerImpl.start(ServerImpl.java:132)
        at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:212)
        at com.netapp.smcore.loader.helper.RestEndpointHelper.startEndpoint(RestEndpointHelper.java:98)
        at com.netapp.smcore.loader.helper.RestEndpointHelper.startRestEndpoint(RestEndpointHelper.java:85)
        at com.netapp.smcore.loader.startup.SmCorePluginLoaderLauncher.main(SmCorePluginLoaderLauncher.java:272)
Caused by: java.lang.NullPointerException
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        at java.net.AbstractPlainSocketImpl$1.run(AbstractPlainSocketImpl.java:84)
        at java.net.AbstractPlainSocketImpl$1.run(AbstractPlainSocketImpl.java:82)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.AbstractPlainSocketImpl.<clinit>(AbstractPlainSocketImpl.java:81)
        ... 22 more
```

**Comment by sbordet** [comment]
The stack trace reports a NPE trying to load the `net` library, so it's impossible for the JVM to create sockets.

This has nothing to do with Jetty.

You probably have a bad JDK installation, or a bad environment or some other system misconfiguration.

**Comment by vinayakbmalagatti** [comment]
Found the solution here https://github.com/MinecraftForge/ForgeGradle/issues/652
