### ISSUE TITLE
Jetty QuickStart 

### ISSUE THREAD

**Issue by gopikrishnayaramothu** [eclipse/jetty.project#4589]
we are trying to move from WebAppContext to QuickStartWebApp on standalone jetty server , we will deploy the individual war file inside webapps folder. we are facing below issue when we ran with quickstart 

2020-02-19 14:31:28.878:INFO:oejs.Server:main: Started @3728ms
2020-02-19 14:31:29.486:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.q.QuickStartWebApp@587c290d{/XXXXXXXX,file:///C:/Oracle/SimphonyHome/jetty//XXXXXXXX/,UNAVAILABLE}
java.lang.NullPointerException
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:142)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:101)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
        at org.eclipse.jetty.quickstart.QuickStartWebApp.doStart(QuickStartWebApp.java:200)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1888)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
        at org.eclipse.jetty.start.Main.start(Main.java:491)
        at org.eclipse.jetty.start.Main.main(Main.java:77)

Note*** : we didn't have anything related to WebAppContext initialization in Application (Project).

could you please help us on this issue ?

**Comment by janbartel** [comment]
Please provide:

- the version of jetty you are using.
- are you running in the distro or embedded.
- how you have enabled quickstart (depends on if running in distro or embedded).
- are you deploying as a .war or an unpacked war.
- does your webapp contain a WEB-INF/lib
- what configuration have you put in your context xml file

**Comment by gopikrishnayaramothu** [comment]
1. jetty version - jetty-distribution-9.4.12.v20180830
2. distributed jetty environment (standalone)
3. java -jar $JETTY_HOME/start.jar --add-to-start=quickstart
4. we are deploying a war file
5. not in project post deployment libs will be copied into WEB-INF/lib
6.  class="org.eclipse.jetty.quickstart.QuickStartWebApp"

please let me know if any additional details are required .
Thanks in advance

**Comment by gopikrishnayaramothu** [comment]
After pre-genrating quickstart-web.xml ($ java -cp [jetty classpath] org.eclipse.jetty.quickstart.PreconfigureQuickStartWar myapp.war)  .
we have seen below exception when we ran **java -jar start.jar**
2020-02-19 15:50:54.690:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.q.QuickStartWebApp@7dc222ae{/ConfigurationService,file:///C:/Oracle/SimphonyHome/jetty/ra/apps/ConfigurationService/,STARTING}{file:///C:/Oracle/SimphonyHome/jetty/ra/apps/ConfigurationService/}
java.lang.NullPointerException
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:802)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:276)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.quickstart.QuickStartWebApp.doStart(QuickStartWebApp.java:200)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1888)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
        at org.eclipse.jetty.start.Main.start(Main.java:491)
        at org.eclipse.jetty.start.Main.main(Main.java:77)

**Comment by janbartel** [comment]
Those line numbers don't line up with jetty-distribution-9.4.12.v20180830.

Also, the exception is different to the one you posted earlier. That makes it very difficult to understand what is going on.

9.4.12 is many versions old. Can you upgrade to the latest 9.4.26 version?

I would try configuring your jetty distro with the quickstart module, and follow the documentation for how to set up your context xml to make your webapp quickstartable, and make it lazily generate the quickstart version: that is, the first time you run the webapp, jetty will make the quickstart version of it, and then use that on subsequent runs. I think the param you should configure in your xml is autoPreconfigure=true, but check the documentation for the exact name.  After running the first time, check that your webapp has the WEB-INF/quickstart-web.xml file, and that the contents of it look good. Then stop and restart and check that the quickstart version is used - startup should be faster.

**Comment by gopikrishnayaramothu** [comment]
autoPreconfigure is correct if we use this quickstart-web.xml was not generated so we have pre-generated quickstart-web.xml using below line 
$ java -cp [jetty classpath] org.eclipse.jetty.quickstart.PreconfigureQuickStartWar myapp.war
post executing above command quickstart-web.xml was generated under web-inf folder, then we have tried java -jar start.jar here we got latest exception i have posted .

**Comment by gopikrishnayaramothu** [comment]
one small update we are using 9.4.21.v20190926 version

**Comment by janbartel** [comment]
If you remove the WEB-INF/quickstart-web.xml from your webapp, then change your context xml file so that autoPreconfigure=true, then when you start jetty, the quickstart-web.xml should be regenerated. If this is not happening, that is a problem.  Please try that. If that does not work, attach your (sanitized where necessary) context xml file, and listing from java -jar start.jar --list-modules and also java -jar start.jar --list-config, and any log output from jetty.

**Comment by gopikrishnayaramothu** [comment]
we have tried above approach quickstart-web.xml was not generated. following is the context file content 
xml version="1.0" encoding="UTF-8"
DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd"
Configure class="org.eclipse.jetty.quickstart.QuickStartWebApp"
  Set name="autoPreconfigure">true</Set
  Set name="contextPath">/xxxxx</Set
  Set name="war"><Property name="jetty.base" default="."/>/apps/xxxxx.war</Set 
Configure
following are the details 


java -jar ../start.jar

Picked up _JAVA_OPTIONS: -Xms128m -Xmx512m
2020-02-19 19:19:59.926:INFO::main: Logging initialized @3591ms to org.eclipse.jetty.util.log.StdErrLog
2020-02-19 19:20:00.034:INFO:oeju.TypeUtil:main: JVM Runtime does not support Modules
2020-02-19 19:20:00.621:INFO:oejs.Server:main: jetty-9.4.21.v20190926; built: 2019-09-26T16:41:09.154Z; git: 72970db61a2904371e1218a95a3bef5d79788c33; jvm 1.8.0_211-b12
2020-02-19 19:20:00.644:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///xxxxx/ra/webapps/] at interval 1
2020-02-19 19:20:00.674:INFO:oejs.AbstractConnector:main: Started httpConn@3043fe0e{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2020-02-19 19:20:00.701:INFO:oejus.SslContextFactory:main: x509=X509@80503(localhost,h=[],w=[]) for Server@4b553d26[provider=null,keyStore=file:///xxxxx\jetty/ra/etc/identity.jks,trustStore=file:///xxxxx\jetty/ra/etc/identity.jks]
2020-02-19 19:20:01.291:INFO:oejs.AbstractConnector:main: Started httpsConn@706a04ae{SSL,[ssl, http/1.1]}{0.0.0.0:7002}
2020-02-19 19:20:01.293:INFO:oejs.Server:main: Started @4959ms
2020-02-19 19:20:01.300:INFO:oejq.QuickStartWebApp:main: Quickstart Extract file:///xxxxx\jetty/ra/apps/yyyyy.war to file:///xxxxx\jetty/ra/apps/yyyyy
2020-02-19 19:20:03.147:INFO:oejq.QuickStartWebApp:main: Quickstart preconfigure: o.e.j.q.QuickStartWebApp@6eceb130{/yyyyy,file:///xxxxx\jetty/ra/apps/yyyyy,UNAVAILABLE}(war=file:///xxxxx\jetty/ra/apps/yyyyy.war,dir=file:///xxxxx\jetty/ra/apps/yyyyy)
2020-02-19 19:20:03.877:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.q.QuickStartWebApp@6eceb130{/yyyyy,file:///xxxxx\jetty/ra/apps/yyyyy,UNAVAILABLE}
java.lang.NullPointerException
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:142)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:101)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
        at org.eclipse.jetty.quickstart.QuickStartWebApp.doStart(QuickStartWebApp.java:200)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1888)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
        at org.eclipse.jetty.start.Main.start(Main.java:491)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
2020-02-19 19:23:43.438:INFO:oejs.AbstractConnector:Thread-0: Stopped httpConn@3043fe0e{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2020-02-19 19:23:43.441:INFO:oejs.AbstractConnector:Thread-0: Stopped httpsConn@706a04ae{SSL,[ssl, http/1.1]}{0.0.0.0:7002}


```
java -jar ../start.jar --list-config
Picked up _JAVA_OPTIONS: -Xms128m -Xmx512m

Java Environment:
-----------------
 java.home = C:\Program Files\Java\jre1.8.0_211 (null)
 java.vm.vendor = Oracle Corporation (null)
 java.vm.version = 25.211-b12 (null)
 java.vm.name = Java HotSpot(TM) 64-Bit Server VM (null)
 java.vm.info = mixed mode (null)
 java.runtime.name = Java(TM) SE Runtime Environment (null)
 java.runtime.version = 1.8.0_211-b12 (null)
 java.io.tmpdir = C:\Users\gyaramot\AppData\Local\Temp\ (null)
 user.dir = xxxxx\jetty\ra (null)
 user.language = en (null)
 user.country = US (null)

Jetty Environment:
-----------------
 jetty.version = 9.4.21.v20190926
 jetty.tag.version = master
 jetty.home = xxxxx\jetty
 jetty.base = xxxxx\jetty\ra

Config Search Order:
--------------------
 <command-line>
 ${jetty.base} -> xxxx\jetty\ra
 ${jetty.home} -> xxxx\jetty


JVM Arguments:
--------------
 (no jvm args specified)

System Properties:
------------------
 (no system properties specified)

Properties:
-----------
 java.version = 1.8.0_211
 java.version.major = 1
 java.version.micro = 0
 java.version.minor = 8
 java.version.platform = 8
 jetty.base = xxxxx\jetty\ra
 jetty.base.uri = file:///xxxxx\jetty/ra
 jetty.home = xxxxx\jetty
 jetty.home.uri = file:///xxxxx\jetty

Jetty Server Classpath:
-----------------------
Version Information on 33 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:      1.4.1.v201005082020 | ${jetty.home}\lib\mail\javax.mail.glassfish-1.4.1.v201005082020.jar
 1:         (none specified) | ${jetty.base}\lib\ext\commons-jwt-19.1.0-SNAPSHOT.jar
 2:      2.7.1.v201005080400 | ${jetty.base}\lib\ext\org.apache.xalan_2.7.1.v201005080400.jar
 3:      2.7.1.v201005080400 | ${jetty.base}\lib\ext\org.apache.xml.serializer_2.7.1.v201005080400.jar
 4:                    (dir) | ${jetty.base}\resources
 5:                    3.1.0 | ${jetty.home}\lib\servlet-api-3.1.jar
 6:                 3.1.0.M0 | ${jetty.home}\lib\jetty-schemas-3.1.jar
 7:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-http-9.4.21.v20190926.jar
 8:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-server-9.4.21.v20190926.jar
 9:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-xml-9.4.21.v20190926.jar
10:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-util-9.4.21.v20190926.jar
11:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-io-9.4.21.v20190926.jar
12:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-jndi-9.4.21.v20190926.jar
13:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-security-9.4.21.v20190926.jar
14:                      1.3 | ${jetty.home}\lib\transactions\javax.transaction-api-1.3.jar
15:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-servlet-9.4.21.v20190926.jar
16:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-webapp-9.4.21.v20190926.jar
17:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-plus-9.4.21.v20190926.jar
18:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-annotations-9.4.21.v20190926.jar
19:                      7.1 | ${jetty.home}\lib\annotations\asm-7.1.jar
20:                      7.1 | ${jetty.home}\lib\annotations\asm-analysis-7.1.jar
21:                      7.1 | ${jetty.home}\lib\annotations\asm-commons-7.1.jar
22:                      7.1 | ${jetty.home}\lib\annotations\asm-tree-7.1.jar
23:                      1.3 | ${jetty.home}\lib\annotations\javax.annotation-api-1.3.jar
24:    3.17.0.v20190306-2240 | ${jetty.home}\lib\apache-jsp\org.eclipse.jdt.ecj-3.17.0.jar
25:         9.4.21.v20190926 | ${jetty.home}\lib\apache-jsp\org.eclipse.jetty.apache-jsp-9.4.21.v20190926.jar
26:                   8.5.40 | ${jetty.home}\lib\apache-jsp\org.mortbay.jasper.apache-el-8.5.40.jar
27:                   8.5.40 | ${jetty.home}\lib\apache-jsp\org.mortbay.jasper.apache-jsp-8.5.40.jar
28:                    1.2.5 | ${jetty.home}\lib\apache-jstl\org.apache.taglibs.taglibs-standard-impl-1.2.5.jar
29:                    1.2.5 | ${jetty.home}\lib\apache-jstl\org.apache.taglibs.taglibs-standard-spec-1.2.5.jar
30:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-deploy-9.4.21.v20190926.jar
31:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-quickstart-9.4.21.v20190926.jar
32:         9.4.21.v20190926 | ${jetty.home}\lib\jetty-servlets-9.4.21.v20190926.jar

Jetty Active XMLs:
------------------
 ${jetty.home}\etc\jetty-bytebufferpool.xml
 ${jetty.home}\etc\jetty-threadpool.xml
 ${jetty.home}\etc\jetty.xml
 ${jetty.home}\etc\jetty-webapp.xml
 ${jetty.home}\etc\jetty-plus.xml
 ${jetty.home}\etc\jetty-annotations.xml
 ${jetty.home}\etc\jetty-deploy.xml
 ${jetty.home}\etc\jetty-http.xml
 ${jetty.home}\etc\jetty-ssl.xml
 ${jetty.home}\etc\jetty-ssl-context.xml
 ${jetty.home}\etc\jetty-https.xml
 ${jetty.base}\etc\vh-ssl.xml
 ${jetty.base}\etc\vh-http.xml
 ${jetty.base}\etc\ssl-context.xml
 ${jetty.base}\etc\yyyyy.xml
```

**Comment by janbartel** [comment]
There's something wrong with the way you have configured your jetty base.  You have configured the Deployer to look in ra/webapps/, but yet the webapp you're trying to deploy is in ra/apps.  So it can't be the Deployer that is finding your webapp to quickstart, it must be via some other means? Is the context xml file for your quickstart webapp in ${jetty.base}\etc\yyyyy.xml ???? If so, that is not the recommended way to do it.

You should put a context xml file that configures a QuickStartWebapp into the directory that is being watched by the Deployer. The context xml file should be the same name as the war file to quickstart:  so for example if your war file is foo-bar.war, then the context xml file that configures it must be called foo-bar.xml, and both the .war file and the .xml file must be in the same directory, and that directory should be the one that is being watched by the Deployer.

The Deployer will find your context xml file that specifies it is a QuickStartWebapp - if you have autoPreConfigure=true, then it will check if the quickstart has already been generated and use it if it has; if it has not generated the quickstart, it will do so first, and then start normally.

**Comment by janbartel** [comment]
@gopikrishnayaramothu progress?

**Comment by gopikrishnayaramothu** [comment]
I forgot to close this issue.thanks for the follow up
