### ISSUE TITLE
jetty-jaspi in jetty-all uber aggregate artifact requires javax.security.auth.message.AuthException which cannot be included

### ISSUE THREAD

**Issue by jbonofre** [eclipse/jetty.project#4621]
**Jetty version**

Any version equal or greater than Jetty 9.4.23.

**Java version**

Any

**OS type/version**

Any

**Description**

Several projects (for instance Apache ActiveMQ) use jetty-all uber artifact (`org.eclipse.jetty.aggregate:jetty-all:uber`) doesn't include `org.eclipse.jetty.orbit:javax.security.auth.message`.
This missing artifact cause issue when using the `ConstraintSecurityHandler`:

```
Caused by: java.util.ServiceConfigurationError: org.eclipse.jetty.security.Authenticator$Factory: Provider org.eclipse.jetty.security.jaspi.JaspiAuthenticatorFactory could not be instantiated
  at java.util.ServiceLoader.fail(ServiceLoader.java:232)
  at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
  at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
  at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
  at org.eclipse.jetty.security.SecurityHandler.<clinit>(SecurityHandler.java:79)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.eclipse.jetty.servlet.ServletContextHandler.newSecurityHandler(ServletContextHandler.java:318)
  at org.eclipse.jetty.servlet.ServletContextHandler.getSecurityHandler(ServletContextHandler.java:377)
  at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(ServletContextHandler.java:227)
  at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:160)
  at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:129)
  at org.apache.activemq.transport.ws.WSTransportServer.doStart(WSTransportServer.java:69)
  at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
  at org.apache.activemq.broker.TransportConnector.start(TransportConnector.java:250)
  at org.apache.activemq.broker.BrokerService.startTransportConnector(BrokerService.java:2761)
  at org.apache.activemq.broker.BrokerService.startAllConnectors(BrokerService.java:2654)
  at org.apache.activemq.broker.BrokerService.doStartBroker(BrokerService.java:777)
  at org.apache.activemq.broker.BrokerService.startBroker(BrokerService.java:739)
  at org.apache.activemq.broker.BrokerService.start(BrokerService.java:642)
  at org.apache.activemq.xbean.XBeanBrokerService.afterPropertiesSet(XBeanBrokerService.java:73)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1748)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1685)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1615)
  ... 27 more
Caused by: java.lang.NoClassDefFoundError: javax/security/auth/message/AuthException
  at java.lang.Class.getDeclaredConstructors0(Native Method)
  at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
  at java.lang.Class.getConstructor0(Class.java:3075)
  at java.lang.Class.newInstance(Class.java:412)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
  ... 55 more
Caused by: java.lang.ClassNotFoundException: javax.security.auth.message.AuthException
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 60 more
```

I see this exclude: https://github.com/eclipse/jetty.project/blob/f4fc78ac66a5811a68e264055114d879d74ae477/aggregates/jetty-all/pom.xml#L85

But it doesn't make sense to me, `jetty-all` should include `javax.security.auth.message.AuthException`. I'm creating a PR.

**Comment by olamy** [comment]
I'm not sure we can legally include those classes `javax.security.auth.message.*`
@janbartel @joakime WDYT?

**Comment by joakime** [comment]
If the origin is from Jakarta with the EPL license then I think we would be ok.

But this Uber artifact is not for direct consumption, never was.
It only exists to teach about jetty basics from the documentation point of view.

**Comment by olamy** [comment]
@joakime yup but It looks some projects such Apache ActiveMQ use it as a normal artifact... :( 
@jbonofre you guys lazy to include more artifacts? (come on it's only a matter of editing some osgi MANIFEST.MF :P )

**Comment by jbonofre** [comment]
I fixed the issue (in ActiveMQ) but including jetty.orbit:javax.security.auth.message artifact.
My concern is the fact it works with Jetty 9.4.22 (without adding the artifact) and it doesn't work out of the box since 9.4.23. That's why I consider this issue as a regression.
The problem is not related to OSGi, but to the uber shade.
I can refactore to use atomic Jetty artifacts instead of the uber one (it's what I did already in pax-web and karaf).
If the uber artifact is not supposed to be used at all, then it should be removed.

**Comment by olamy** [comment]
@jbonofre sorry for the trouble :( 
 @joakime maybe we should keep backward compat for 9.4.x and to avoid such issue we should simply stop building/deploy it with 10 wdyt?

**Comment by jbonofre** [comment]
It makes sense to remove for Jetty 10.
No problem for the change, it was just "surprising".

**Comment by olamy** [comment]
ok as you don't need it anymore we can just close it.

**Comment by joakime** [comment]
> I fixed the issue (in ActiveMQ) but including jetty.orbit:javax.security.auth.message artifact.

If you are using the Eclipse RT (RunTime) and OSGi, then use the version from orbit.

If you are NOT using the Eclipse RT and OSGi then use the official artifacts from the jakarta effort. (they even have good quality OSGi manifest information!)
https://search.maven.org/artifact/jakarta.security.auth.message/jakarta.security.auth.message-api/1.1.3/jar

`javax.security.auth.message` is only used by the `jetty-jaspi` components.
And that requirement has existed since the beginning of our effort at Eclipse.
https://github.com/eclipse/jetty.project/blob/da627b843fe81fa0fe52a046c1be8595630e9ae7/jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/JaspiAuthenticator.java

As far as I can tell, those classes have not been part of jetty-all before.

```
[joakim@hyperion tmp]$ curl -O https://repo1.maven.org/maven2/org/eclipse/jetty/aggregate/jetty-all/7.0.0.v20091005/jetty-all-7.0.0.v20091005.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1185k  100 1185k    0     0  1637k      0 --:--:-- --:--:-- --:--:-- 1634k
[joakim@hyperion tmp]$ jar -tvf jetty-all-7.0.0.v20091005.jar | grep javax/security
[joakim@hyperion tmp]$ curl -O https://repo1.maven.org/maven2/org/eclipse/jetty/aggregate/jetty-all/9.4.22.v20191022/jetty-all-9.4.22.v20191022-uber.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3616k  100 3616k    0     0  4595k      0 --:--:-- --:--:-- --:--:-- 4589k
[joakim@hyperion tmp]$ jar -tvf jetty-all-9.4.22.v20191022-uber.jar | grep javax/security
[joakim@hyperion tmp]$ 
```

Which makes sense, as those classes ship with the JVM itself.

* https://docs.oracle.com/javase/8/docs/api/javax/security/auth/package-summary.html
* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/security/auth/package-summary.html

> This missing artifact cause issue when using the `ConstraintSecurityHandler`:

The `ConstraintSecurityHandler` does not have a requirement for `javax.security.auth.message`.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.27.v20200227/jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java

Have you just recently started to use JASPI perhaps?

**Comment by jbonofre** [comment]
No directly use of JASPI, the code didn't change: it was working with Jetty 9.4.22, and after upgrading to any version equal or great to Jetty 9.4.23, it failed.

I proposed the PR at least of 9.4.x branch to be backward compatible. If you want I can do a `git bisect` to identify the change between 9.4.22 and 9.4.23 causing the issue.

**Comment by uschindler** [comment]
I have the same problem. I have a simple standalone app just setting up a webapp context and it fails asap with this error. No code change anywhere, just update of jetty-uber.jar.

**Comment by uschindler** [comment]
I tried to follow this issue: Will it be fixed in next point release, or is it won't fix?

**Comment by joakime** [comment]
@uschindler what happens if you don't use the uber classified artifact? but use the normal artifacts instead?

**Comment by joakime** [comment]
If you are using the combination of spring / spring-boot and activemq, you need to exclude `jetty-all` from activemq in your build.
It conflicts with the proper usage of jetty artifacts that spring/spring-boot uses.

Bug filed at ActiveMQ about this a while ago - https://issues.apache.org/jira/browse/AMQ-7364

**Comment by uschindler** [comment]
The problem here is that it has nothing to do with ActiveMQ. Here it's really a project not using Maven and just having the uber.jar in classpath.

I have another version working here that just uses a ServletContextHandler, this works without any problems. But As soon as you use a WebappContextHandler it breaks.

I will report back when I found out what's causing this. It looks like the uber JAR is not useable anymore with newer bugfix releases (after 9.4.22) if you use a WebappContext.

**Comment by joakime** [comment]
Since you are using a WAR, do you have jetty jars in your `WEB-INF/lib` or jetty classes in your `WEB-INF/classes` perhaps?

**Comment by joakime** [comment]
Are you changing the `WebAppContext` classloader or parentyLoaderPriority?

**Comment by uschindler** [comment]
Hi,
there is nothing in the single webapp deployed in the jetty. It's just a stupid AXIS 1.4 instance (for legacy reasons). The problem occurs on booting up.

But I figured out the problem: If you don't use the uber.jar file, all works fine (it has nothing to do with a WebappContext). With the Uber.JAR, I can also make the ServletContextHandler fail in same way.

It's plain simple: In Jetty 9.4.22, there is no "META-INF/services/org.eclipse.jetty.security.Authenticator$Factory", so the ServiceLoader just gets nothing. In latest version there is the service lookup file, so when starting the ServletContext it tries to load the the SPI.

If I remove the "META-INF/services/org.eclipse.jetty.security.Authenticator$Factory" file from the uber.jar using 7zip, it works and starts up.

It looks like the issue is that somehow the SPI listing in META-INF made it into the uber JAR, but the class there does not exist.

**Comment by uschindler** [comment]
So the fix is to remove the faulty META-INF/services/org.eclipse.jetty.security.Authenticator$Factory file which should not belong there. It's a bug as it lists a class which does not exist.

**Comment by joakime** [comment]
Opened PR #4679
