### ISSUE TITLE
CustomRequestLog throws NullPointerException when no request cookie is present

### ISSUE THREAD

**Issue by hengah** [eclipse/jetty.project#4671]
This happens when the custom log format is configured to log an optional cookie.
For example: %{cookieName}C

The expectation is an '-' in the request log if the cookie is missing.
Instead we get a NullPointerException and nothing is logged to the request-log if no cookies exists on the request.

Stacktrace(sorry for the formatting):
```
2020-03-13 17:57:44.388  WARN 14464 --- [tp1756726852-29] o.e.j.s.CustomRequestLog                 : 
java.lang.NullPointerException: null
	at org.eclipse.jetty.server.CustomRequestLog.logRequestCookie(CustomRequestLog.java:1037) ~[jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.CustomRequestLog.log(CustomRequestLog.java:339) ~[jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:741) ~[jetty-server-9.4.22.v20191022.jar:9.4.22.v20191022]
```

It appears that there is missing a null-check in CustomRequestLog.logRequestCookie.
The corresponding method for logging all the cookies(CustomRequestLog.logRequestCookies) has a valid null-check.
It could also be possible to make sure Request.getCookies returns an empty array instead of null. But that depends more on your coding guidelines and the issues such a change could result in.

**Comment by lachlan-roberts** [comment]
Yep you're right, we need a null check similar to what is being done in the method below `logRequestCookies`. But I don't think we can allow Request.getCookies to return an empty array instead, as it implements `HttpServletRequest.getCookies` and the javadoc says we must return null.
