### ISSUE TITLE
use HttpClientTransportOverHTTP2 to send patch

### ISSUE THREAD

**Issue by leosun620** [eclipse/jetty.project#4677]
**Jetty version**
9.4.19.v20190610
**Java version**
12.0.2
**OS type/version**
windows10
**Description**
my code is:

```java
// Use the HTTP/2 transport.
HttpClient client = new HttpClient(new HttpClientTransportOverHTTP2(new HTTP2Client()), new SslContextFactory.Client());
client.start();

// Add fields.
Fields fields = new Fields();
fields.put("name", "Jobs");
Request request = client.newRequest("nghttp2.org",443).method("PATCH").path("/httpbin/patch").content(new FormContentProvider(fields)).agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36");
		
request.param("name", "sunbin");
request.header("Sec-Fetch-Dest", "style");
ContentResponse response = request.send();
System.out.println(request.getVersion());
System.out.println(response.getStatus());
System.out.println(response.getContentAsString());
```

the error logs is:
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683)
	at com.bot.jettyHttp2ClientSnkrs.main.test.main(test.java:38)
Caused by: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.http2.HTTP2Session.onShutdown(HTTP2Session.java:950)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:283)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:170)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:125)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:348)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.Invocable.invokeNonBlocking(Invocable.java:68)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.invokeTask(EatWhatYouKill.java:345)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:300)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by sbordet** [comment]
You are missing `.scheme("https")` when you build the request.

**Comment by leosun620** [comment]
it's useful ,thanks a lot.
