### ISSUE TITLE
Reset trailers on recycled response

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4711]
+ https://jenkins.webtide.net/job/nightlies/job/servlettck-run-jetty-10.0.x/361/testReport/com_sun_ts_tests_servlet_api_javax_servlet_http_httpservletresponse40_Client/java/TrailerTest/
 + https://jenkins.webtide.net/job/nightlies/job/servlettck-run-jetty-10.0.x/361/testReport/com_sun_ts_tests_servlet_api_javax_servlet_http_httpservletresponse40_Client/java/TrailerTestResponseCommitted/
 + https://jenkins.webtide.net/job/nightlies/job/servlettck-run-jetty-10.0.x/361/testReport/com_sun_ts_tests_servlet_api_javax_servlet_http_httpservletresponse40_Client/java/TrailerTestWithHTTP10/

**Comment by gregw** [comment]
```
[javatest.batch] <title>Error 500 java.lang.NullPointerException</title>
[javatest.batch] </head>
[javatest.batch] <body><h2>HTTP ERROR 500 java.lang.NullPointerException</h2>
[javatest.batch] <table>
[javatest.batch] <tr><th>URI:</th><td>/servlet_jsh_httpservletresponse40_web/TrailerTestServlet</td></tr>
[javatest.batch] <tr><th>STATUS:</th><td>500</td></tr>
[javatest.batch] <tr><th>MESSAGE:</th><td>java.lang.NullPointerException</td></tr>
[javatest.batch] <tr><th>SERVLET:</th><td>TrailerTestServlet</td></tr>
[javatest.batch] <tr><th>CAUSED BY:</th><td>java.lang.NullPointerException</td></tr>
[javatest.batch] </table>
[javatest.batch] <h3>Caused by:</h3><pre>java.lang.NullPointerException
[javatest.batch] 	at com.sun.ts.tests.servlet.api.javax_servlet_http.httpservletresponse40.TrailerTestServlet.doPost(TrailerTestServlet.java:44)
[javatest.batch] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
[javatest.batch] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
[javatest.batch] 	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1338)
[javatest.batch] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:716)
[javatest.batch] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:538)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
[javatest.batch] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:561)
[javatest.batch] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:228)
[javatest.batch] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1575)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:226)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1237)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:181)
[javatest.batch] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:475)
[javatest.batch] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1548)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:179)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1156)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:134)
[javatest.batch] 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:218)
[javatest.batch] 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
[javatest.batch] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
[javatest.batch] 	at org.eclipse.jetty.server.Server.handle(Server.java:545)
[javatest.batch] 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:375)
[javatest.batch] 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:559)
[javatest.batch] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:367)
[javatest.batch] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:290)
[javatest.batch] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:321)
[javatest.batch] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
[javatest.batch] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
[javatest.batch] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
[javatest.batch] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
[javatest.batch] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
[javatest.batch] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
[javatest.batch] 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
[javatest.batch] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:823)
[javatest.batch] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:945)
[javatest.batch] 	at java.base/java.lang.Thread.run(Thread.java:834)
[javatest.batch] </pre>
```

**Comment by gregw** [comment]
I've also noted that sending and error has not reset either the transfer-encoding nor the trailers themselves!

**Comment by sbordet** [comment]
@gregw trailers done, but `Transfer-Encoding` (or anything else) not done, so I'm leaving this issue open.

**Comment by gregw** [comment]
@sbordet  See #5643... is that sufficient to close this issue?

**Comment by gregw** [comment]
passing asssociated TCK test so closing this one
