### ISSUE TITLE
CDI Tests failing

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#4755]
Test is failing with

```
2020-04-07 15:04:33.851:INFO :oejtd.DistributionTester:main: Executing: [/opt/jdk-13.0.2/bin/java, -Djava.io.tmpdir=/home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/work, -jar, /home/gregw/src/jetty-10.0.x/tests/test-distribution/target/jetty_home_16075767936657539467/jetty-distribution-10.0.0-SNAPSHOT/start.jar, --create-startd, --approve-all-licenses, --add-to-start=http,deploy,annotations,jsp,cdi-spi, maven.local.repo=/home/gregw/.m2/repository]
2020-04-07 15:04:33.851:INFO :oejtd.DistributionTester:main: Working Dir: /home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959
2020-04-07 15:04:34.134:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: MKDIR : ${jetty.base}/start.d
2020-04-07 15:04:34.136:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : webapp          transitively enabled, ini template available with --add-to-start=webapp
2020-04-07 15:04:34.136:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : server          transitively enabled, ini template available with --add-to-start=server
2020-04-07 15:04:34.136:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : servlet         transitively enabled
2020-04-07 15:04:34.138:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : jsp             initialized in ${jetty.base}/start.d/jsp.ini
2020-04-07 15:04:34.139:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : resources       transitively enabled
2020-04-07 15:04:34.140:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : annotations     initialized in ${jetty.base}/start.d/annotations.ini
2020-04-07 15:04:34.140:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : cdi             transitively enabled
2020-04-07 15:04:34.140:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : cdi-spi         initialized in ${jetty.base}/start.d/cdi-spi.ini
2020-04-07 15:04:34.140:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : threadpool      transitively enabled, ini template available with --add-to-start=threadpool
2020-04-07 15:04:34.141:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : plus            transitively enabled
2020-04-07 15:04:34.142:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : deploy          initialized in ${jetty.base}/start.d/deploy.ini
2020-04-07 15:04:34.142:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : logging-jetty   transitively enabled
2020-04-07 15:04:34.142:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : security        transitively enabled
2020-04-07 15:04:34.142:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : apache-jsp      transitively enabled
2020-04-07 15:04:34.142:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : jndi            transitively enabled
2020-04-07 15:04:34.143:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : http            initialized in ${jetty.base}/start.d/http.ini
2020-04-07 15:04:34.143:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : logging/slf4j   transitive provider of logging/slf4j for logging-jetty
2020-04-07 15:04:34.144:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : logging/slf4j   dynamic dependency of logging-jetty
2020-04-07 15:04:34.144:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : bytebufferpool  transitively enabled, ini template available with --add-to-start=bytebufferpool
2020-04-07 15:04:34.144:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: MKDIR : ${jetty.base}/resources
2020-04-07 15:04:34.145:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: MKDIR : ${jetty.base}/webapps
2020-04-07 15:04:34.146:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: COPY  : ${jetty.home}/modules/logging/jetty/resources/jetty-logging.properties to ${jetty.base}/resources/jetty-logging.properties
2020-04-07 15:04:34.146:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: INFO  : Base directory was modified
2020-04-07 15:04:34.183:INFO :oejtd.DistributionTester:main: Executing: [/opt/jdk-13.0.2/bin/java, -Djava.io.tmpdir=/home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/work, -jar, /home/gregw/src/jetty-10.0.x/tests/test-distribution/target/jetty_home_16075767936657539467/jetty-distribution-10.0.0-SNAPSHOT/start.jar, jetty.http.port=34299, maven.local.repo=/home/gregw/.m2/repository]
2020-04-07 15:04:34.184:INFO :oejtd.DistributionTester:main: Working Dir: /home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959
2020-04-07 15:04:34.776:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:34.774:INFO :oejs.Server:main: jetty-10.0.0-SNAPSHOT; built: 2020-04-07T12:22:29.533Z; git: a189d13fd548b2acb626c501148d5364a2a085a7; jvm 13.0.2+8
2020-04-07 15:04:34.807:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:34.807:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/webapps/] at interval 1
2020-04-07 15:04:34.954:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:34.953:INFO :oeja.AnnotationConfiguration:main: Error:  for o.e.j.w.WebAppContext@d35dea7{demo,/demo,file:///home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/webapps/demo/,STARTING}{/home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/webapps/demo}
2020-04-07 15:04:35.057:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.057:INFO :oeja.AnnotationConfiguration:main: Annotation scanning elapsed time=83ms
2020-04-07 15:04:35.112:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.112:INFO :oejc.CdiServletContainerInitializer:main: CdiSpiDecorator enabled in ServletContext@o.e.j.w.WebAppContext@d35dea7{OWB CDI Integration Test WebApp,/demo,file:///home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/webapps/demo/,STARTING}{/home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/webapps/demo}
2020-04-07 15:04:35.193:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: WARNING: An illegal reflective access operation has occurred
2020-04-07 15:04:35.193:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: WARNING: Illegal reflective access by org.apache.webbeans.proxy.Unsafe (file:/home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/webapps/demo/WEB-INF/lib/openwebbeans-impl-2.0.15.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
2020-04-07 15:04:35.193:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: WARNING: Please consider reporting this to the maintainers of org.apache.webbeans.proxy.Unsafe
2020-04-07 15:04:35.193:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2020-04-07 15:04:35.193:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: WARNING: All illegal access operations will be denied in a future release
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.238:WARN :oejc.CdiServletContainerInitializer:main: Unable to decorate org.eclipse.jetty.test.MyContextListener@492691d7
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: javax.enterprise.inject.UnsatisfiedResolutionException: Api type [org.eclipse.jetty.test.ServerID] is not found with the qualifiers |Qualifiers: [@javax.enterprise.inject.Default()]|for injection into Field Injection Point, field name :  serverId, Bean Owner : [null]
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.apache.webbeans.util.InjectionExceptionUtil.throwUnsatisfiedResolutionException(InjectionExceptionUtil.java:60)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.apache.webbeans.container.InjectionResolver.getInjectionPointBean(InjectionResolver.java:293)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.apache.webbeans.inject.AbstractInjectable.inject(AbstractInjectable.java:79)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.apache.webbeans.inject.InjectableField.doInjection(InjectableField.java:65)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.apache.webbeans.portable.InjectionTargetImpl.injectFields(InjectionTargetImpl.java:227)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:213)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:203)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.cdi.CdiSpiDecorator$Decorated.<init>(CdiSpiDecorator.java:157)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.cdi.CdiSpiDecorator.decorate(CdiSpiDecorator.java:111)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.DecoratedObjectFactory.decorate(DecoratedObjectFactory.java:102)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ServletContextHandler$Context.createInstance(ServletContextHandler.java:1261)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ServletContextHandler$Context.createInstance(ServletContextHandler.java:1270)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.BaseHolder.createInstance(BaseHolder.java:188)
2020-04-07 15:04:35.240:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ListenerHolder.createInstance(ListenerHolder.java:111)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ListenerHolder.doStart(ListenerHolder.java:91)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:389)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1288)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:797)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:317)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:536)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:45)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:518)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:154)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:179)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:435)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:789)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:756)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:174)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:124)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:151)
2020-04-07 15:04:35.241:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:249)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:174)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.Server.start(Server.java:454)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:124)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:94)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.Server.doStart(Server.java:399)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$2(XmlConfiguration.java:1848)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1790)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/java.lang.reflect.Method.invoke(Method.java:567)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.start.Main.start(Main.java:483)
2020-04-07 15:04:35.242:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.start.Main.main(Main.java:77)
2020-04-07 15:04:35.266:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.266:INFO :oejss.DefaultSessionIdManager:main: DefaultSessionIdManager workerName=node0
2020-04-07 15:04:35.266:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.266:INFO :oejss.DefaultSessionIdManager:main: No SessionScavenger set, using defaults
2020-04-07 15:04:35.267:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.267:INFO :oejss.HouseKeeper:main: node0 Scavenging every 600000ms
2020-04-07 15:04:35.276:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.275:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@d35dea7{OWB CDI Integration Test WebApp,/demo,file:///home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/webapps/demo/,UNAVAILABLE}{/home/gregw/src/jetty-10.0.x/tests/test-distribution/target/tests/test-bases/jetty_base_7250099805369474959/webapps/demo}
2020-04-07 15:04:35.276:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: java.lang.IllegalStateException: CDI did not inject!
2020-04-07 15:04:35.276:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.test.MyContextListener.contextInitialized(MyContextListener.java:36)
2020-04-07 15:04:35.276:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:955)
2020-04-07 15:04:35.276:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:592)
2020-04-07 15:04:35.278:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:884)
2020-04-07 15:04:35.278:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
2020-04-07 15:04:35.278:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:399)
2020-04-07 15:04:35.278:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1288)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:797)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:317)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:536)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:45)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:518)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:154)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:179)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:435)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:789)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:756)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:174)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:124)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:151)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.279:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:249)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:174)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.Server.start(Server.java:454)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:124)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:94)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.server.Server.doStart(Server.java:399)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:96)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$2(XmlConfiguration.java:1848)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1790)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at java.base/java.lang.reflect.Method.invoke(Method.java:567)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.start.Main.start(Main.java:483)
2020-04-07 15:04:35.280:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: ?at org.eclipse.jetty.start.Main.main(Main.java:77)
2020-04-07 15:04:35.287:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.286:INFO :oejs.AbstractConnector:main: Started ServerConnector@7913be0{HTTP/1.1, (http/1.1)}{0.0.0.0:34299}
2020-04-07 15:04:35.299:INFO :oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-04-07 15:04:35.299:INFO :oejs.Server:main: Started Server@6a192cfe{STARTING}[10.0.0-SNAPSHOT,sto=5000] @1111ms
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.226 s <<< FAILURE! - in org.eclipse.jetty.tests.distribution.CDITests
[ERROR] org.eclipse.jetty.tests.distribution.CDITests.testCDIIncludedInWebapp(String,String,Consumer)  Time elapsed: 2.205 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <200> but was: <503>
	at org.eclipse.jetty.tests.distribution.CDITests.testCDIIncludedInWebapp(CDITests.java:108)

```

**Comment by joakime** [comment]
This is already being worked in PR #4706
