### ISSUE TITLE
Upon enabling the --https module, startup fails with " No constructor class org.eclipse.jetty.server.ServerConnector([],{}) in file:/opt/software/etc/jetty-https.xml"

### ISSUE THREAD

**Issue by Azifor** [eclipse/jetty.project#4774]
jetty.version = 9.4.18.v20190429

java.version = 1.8.0_161

RHEL 7.4

Upon startup on geoserver utilizing jetty, I get the following error:

/usr/lib/jvm/jre-1.8.0/bin/java -server -Xms16G -Xmx16G -Xmn2G -XX:+UseG1GC  -DSTOP.PORT=8079 -DSTOP.KEY=geoserver -jar start.jar
2020-04-14 22:12:01.817:INFO::main: Logging initialized @294ms to org.eclipse.jetty.util.log.StdErrLog
2020-04-14 22:12:01.945:WARN:oejx.XmlConfiguration:main: Property 'jetty.port' is deprecated, use 'jetty.http.port' instead
2020-04-14 22:12:01.945:WARN:oejx.XmlConfiguration:main: Property 'http.timeout' is deprecated, use 'jetty.http.idleTimeout' instead
2020-04-14 22:12:01.961:WARN:oejx.XmlConfiguration:main:
java.lang.IllegalStateException: No constructor class org.eclipse.jetty.server.ServerConnector([],{}) in file:/opt/software/etc/jetty-https.xml
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:406)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:311)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1558)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
        at org.eclipse.jetty.start.Main.start(Main.java:490)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
        at org.eclipse.jetty.start.Main.start(Main.java:490)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.lang.IllegalStateException: No constructor class org.eclipse.jetty.server.ServerConnector([],{}) in file:/opt/software/etc/jetty-https.xml
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:406)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:311)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1558)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
        ... 7 more
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
        at org.eclipse.jetty.start.Main.start(Main.java:490)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.lang.IllegalStateException: No constructor class org.eclipse.jetty.server.ServerConnector([],{}) in file:/opt/software/etc/jetty-https.xml
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:406)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:311)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1558)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
        ... 7 more

When I startup with the --list-config option I see:
Jetty Active XMLs:
------------------
 ${jetty.base}/etc/jetty.xml
 ${jetty.base}/etc/jetty-deploy.xml
 ${jetty.base}/etc/jetty-http.xml
 ${jetty.base}/etc/jetty-ssl.xml
 ${jetty.base}/etc/jetty-ssl-context.xml
 ${jetty.base}/etc/jetty-https.xml

With jetty.base:
jetty.base = /opt/software
 jetty.base.uri = file:///opt/software
jetty.ssl.port = 8443
 jetty.sslContext.keyManagerPassword = MyPassword
 jetty.sslContext.keyStorePassword = MyPassword
 jetty.sslContext.keyStorePath = etc/keystore
 jetty.sslContext.trustStorePassword = MyPassword
 jetty.sslContext.trustStorePath = etc/keystore

Everything starts up successful when I disable the --https module but working on getting https working with jetty.

Here is the excerpt form the classPath if that is needed as well.

Jetty Server Classpath:
-----------------------
Version Information on 13 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    (dir) | ${jetty.base}/resources
 1:                    3.1.0 | ${jetty.base}/lib/javax.servlet-api-3.1.0.jar
 2:                 3.1.0.M0 | ${jetty.base}/lib/jetty-schemas-3.1.M0.jar
 3:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-http-9.4.18.v20190429.jar
 4:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-server-9.4.18.v20190429.jar
 5:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-xml-9.4.18.v20190429.jar
 6:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-util-9.4.18.v20190429.jar
 7:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-io-9.4.18.v20190429.jar
 8:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-security-9.4.18.v20190429.jar
 9:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-servlet-9.4.18.v20190429.jar
10:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-webapp-9.4.18.v20190429.jar
11:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-deploy-9.4.18.v20190429.jar
12:         9.4.18.v20190429 | ${jetty.base}/lib/jetty-servlets-9.4.18.v20190429.jar

It appears it is finding all of the configuration files correctly...yet can't quite see why it is failing when loading that module.

**Comment by Azifor** [comment]
The etc/jetty-https.xml file looks like:
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">






<Configure id="sslConnector" class="org.eclipse.jetty.server.ServerConnector">

  <Call name="addIfAbsentConnectionFactory">
    <Arg>
      <New class="org.eclipse.jetty.server.SslConnectionFactory">
        <Arg name="next">http/1.1</Arg>
        <Arg name="sslContextFactory"><Ref refid="sslContextFactory"/></Arg>
      </New>
    </Arg>
  </Call>

  <Call name="addConnectionFactory">
    <Arg>
      <New class="org.eclipse.jetty.server.HttpConnectionFactory">
        <Arg name="config"><Ref refid="sslHttpConfig" /></Arg>
        <Arg name="compliance"><Call class="org.eclipse.jetty.http.HttpCompliance" name="valueOf"><Arg><Property name="jetty.http.compliance" default="RFC7230"/></Arg></Call></Arg>
      </New>
    </Arg>
  </Call>

**Comment by sbordet** [comment]
@Azifor seems like you have copied to `${jetty.base}/etc/` a number of XML files that are probably from older versions of Jetty and now they don't work.

Please update to jetty 9.4.28.

I would start without any modified XML file - leave them all in `${jetty.home}`.

If you really need to modify them, use properties instead.

Only if also properties are not enough, then you can use custom XML files.

**Comment by Azifor** [comment]
That was it. I was using the embedded jetty that geoserver provides out of the box and that part wasn't updated from I think 2.15 onwards. 

Thanks!
