### ISSUE TITLE
aused by: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@8ddf008

### ISSUE THREAD

**Issue by SambaDamerla** [eclipse/jetty.project#4793]
**Jetty version**
9.2.14.v20151106 (compile group: 'org.restlet.jse', name: 'org.restlet.ext.jetty', version: '2.3+')
**Java version**
1.8.0_242
**OS type/version**
Ubuntu 16.04.6 LTS
**Description**
We are using Restlet 2.3+  Server and Client. When we get a request to my server we are doing a dependent API call to my third party vendors (Responsys, Bingmap etc) using Restlet ClientResrouce (where the Client object was created when the server started). 

Server Start Calls will initiate Server and Client attached with file SenderRootServerComponent.txt

When  we want to do any dependent API calls we do as in attached  ResourceClient.txt. We are not using separate client timeout settings as Client  was already setup with those settings as a part of startup call.

Below is the restlet version 2.3+ we were using past 1year. see restletDepenencyVersions.txt

From past 1 year when ever we got Restlet 1001 communication error due to EOF error from jetty as below, if it continue from 3 to 4min, from then VM going into Bad state and continuously seeing Communication Error 1001 (with timeout) 

Caused by: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@8ddf008
[SenderRootServerComponent.txt](https://github.com/eclipse/jetty.project/files/4506241/SenderRootServerComponent.txt)
[ResourceClient.txt](https://github.com/eclipse/jetty.project/files/4506243/ResourceClient.txt)
[restletDepenencyVersions.txt](https://github.com/eclipse/jetty.project/files/4506245/restletDepenencyVersions.txt)

(l:/10.XXX.XX.28:56460 <-> r:ws2-XXX.extns.XXXX.net/12.XXX.XXX.XXX:443,closed=false)[HttpChannelOverHTTP@59f7fe92(exchange=HttpExchange@568e48cf req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@5a0c7af(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@621a3aa3(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of 0}]]]
	at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:228)
	at org.restlet.ext.jetty.internal.JettyClientCall.sendRequest(JettyClientCall.java:287)
	at org.restlet.engine.adapter.ClientAdapter.commit(ClientAdapter.java:105)
	at org.restlet.engine.adapter.HttpClientHelper.handle(HttpClientHelper.java:119)
	at org.restlet.Client.handle(Client.java:153)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.engine.component.ComponentClientDispatcher.doHandle(ComponentClientDispatcher.java:129)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.util.ChildClientDispatcher.parentHandle(ChildClientDispatcher.java:139)
	at org.restlet.engine.util.ChildClientDispatcher.doHandle(ChildClientDispatcher.java:112)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.util.ChildClientDispatcher.parentHandle(ChildClientDispatcher.java:139)
	at org.restlet.engine.util.ChildClientDispatcher.doHandle(ChildClientDispatcher.java:112)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1093)
	at org.restlet.resource.ClientResource.handleOutbound(ClientResource.java:1179)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1008)
	... 65 common frames omitted
Caused by: java.io.EOFException: HttpConnectionOverHTTP@8ddf008(l:/10.XXX.XXX.28:56460 <-> r:ws2-XXXX.extns.XXXX.net/12.XXX.XXX.212:443,closed=false)[HttpChannelOverHTTP@59f7fe92(exchange=HttpExchange@568e48cf req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@5a0c7af(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@621a3aa3(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of 0}]]]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:277)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1309)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:182)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:129)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:89)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:122)

Thanks 
Samba

**Comment by sbordet** [comment]
Jetty 9.2.14 almost 5 years old and Jetty 9.2.x is End-Of-Life so you must really upgrade. 
Latest Jetty is 9.4.28, and latest Restlet is also based on Jetty 9.4.x.

The stack trace you posted shows that the client sent the request, but the server never replied and it just closed the connection.
Seems to be a server problem.

**Comment by SambaDamerla** [comment]
Thanks @sbordet I will upgrade it to latest 9.4.x version. I will also inform my depended API provider to look into this.

**Comment by SambaDamerla** [comment]
@sbordet  could you also help me when we get this exception
Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:228)
	at org.restlet.ext.jetty.internal.JettyClientCall.sendRequest(JettyClientCall.java:287)
	at org.restlet.engine.adapter.ClientAdapter.commit(ClientAdapter.java:105)
	at org.restlet.engine.adapter.HttpClientHelper.handle(HttpClientHelper.java:119)
	at org.restlet.Client.handle(Client.java:153)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.engine.component.ComponentClientDispatcher.doHandle(ComponentClientDispatcher.java:129)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.util.ChildClientDispatcher.parentHandle(ChildClientDispatcher.java:139)
	at org.restlet.engine.util.ChildClientDispatcher.doHandle(ChildClientDispatcher.java:112)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.util.ChildClientDispatcher.parentHandle(ChildClientDispatcher.java:139)
	at org.restlet.engine.util.ChildClientDispatcher.doHandle(ChildClientDispatcher.java:112)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1093)
	at org.restlet.resource.ClientResource.handleOutbound(ClientResource.java:1179)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1008)
	... 65 common frames omitted
Caused by: java.util.NoSuchElementException: null
	at org.eclipse.jetty.client.util.InputStreamContentProvider$InputStreamContentProviderIterator.next(InputStreamContentProvider.java:231)
	at org.eclipse.jetty.client.util.InputStreamContentProvider$InputStreamContentProviderIterator.next(InputStreamContentProvider.java:166)
	at org.eclipse.jetty.client.HttpContent.advance(HttpContent.java:142)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:73)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:204)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:78)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:218)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:91)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:36)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:26)
	at org.eclipse.jetty.client.PoolingHttpDestination$2.run(PoolingHttpDestination.java:144)
	... 3 common frames omitted
Caused by: java.io.IOException: Timeout while reading from the queue-based input stream
	at org.restlet.engine.io.PipeStream$1.read(PipeStream.java:74)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.InputStream.read(InputStream.java:101)
	at org.eclipse.jetty.client.util.InputStreamContentProvider$InputStreamContentProviderIterator.hasNext(InputStreamContentProvider.java:181)
	at org.eclipse.jetty.client.HttpContent.advance(HttpContent.java:141)
	... 11 common frames omitted

**Comment by sbordet** [comment]
@SambaDamerla I don't know, since the origin exception is:

```
Caused by: java.io.IOException: Timeout while reading from the queue-based input stream
at org.restlet.engine.io.PipeStream$1.read(PipeStream.java:74)
```

The `InputStream` you provide to the `HttpClient` is not providing the content it should.

**Comment by SambaDamerla** [comment]
Thanks @sbordet

**Comment by sbordet** [comment]
@SambaDamerla what was exactly the problem? 
As more information in case someone stumbles on this issue.

**Comment by SambaDamerla** [comment]
@sbordet Thanks for check the problem.
Here is my problem, from past one year we were seeing communication error with Resetlet (version 2.3.12). It is happening when there is sudden spike of repose time of my third party dependency services or some network problem for couple of minutes. And my VM is not recovering fast until I bounce the VMs. Even though I set the socket time out settings as 5Sec, I have observed that either the dependency API response time or my main API response time is more than 60Sec. 
I suspect when I receive a request to my server since I do one or two HTTP API call to my dependent third party servers like BingMap or  some other server. And if one of those services respond slow, the main request thread is waiting to respond to the customer. So due to this during the load time the request are waiting in queue more than 55Sec until it got a connection/thread to execute with response time of 55sec waiting for connection + time taken by dependent calls. 

To this ticket I have attached below defined files that helps you to know how I have configured Restlet, connection settings and timeout settings. Can you take a look and help me whether my connection settings were correct or not?
SenderRootServerComponent.txt
ResourceClient.txt
restletDepenencyVersions.txt

I closed this ticket as you already advised to upgrade to latest version of Restlet 2.4.3 which uses Jetty 9.4.X. So I closed this ticket. 
It will be great if you can suggest or correct my connection settings

Thanks
Samba

**Comment by sbordet** [comment]
@SambaDamerla the files are not attached.

For your scenario, you want to use `request.startAsync()` and process requests asynchronously.

Also, the client must be prepared to wait for a long time if you have these problems, or timeout early (don't wait a full minute for a HTTP request!) and try again.

Your application should be prepared to these kind of failures, so I would set the timeouts to third party services really short, and if they fail, either you have some cached content to use, or you just give up and send an error to the client, without having the client to wait too much.

**Comment by SambaDamerla** [comment]
Hi @sbordet , 
Sorry for the late reply
We already implemented, server's to wait for dependency call to respond with the SocketTimeout setting (which 2000ms). We throw HTTP status 503 to my clients if dependency API didn't respond with the SocketTimeout. My clients will either do one or two retires or show proper error messages to customers. 
Also if my sever has to do multiple third party dependency calls we use Java ForkJoin to do it parallel. 
The only problem we have is for some reason, if we have Restlet Communication errors (due to Socket time out or EOF) more than 300 or 400 events in 5mins window, my VM is continue to throw those errors until we restart the service running on that VM. We run only one Java service per VM. Also the observation I did so far is, even though my timeout setting is 2Sec, I am seeing each request with the communication error happens after 50Sec. 
I did sometime wrong with my Sockettimeout settings, Ideal timeout settings, totalConnections etc. 
Here I have attached my Restlet config related code. Please correct me if my config is wrong. 
[restletDepenencyVersions.txt](https://github.com/eclipse/jetty.project/files/4556115/restletDepenencyVersions.txt)
[ResourceClient.txt](https://github.com/eclipse/jetty.project/files/4556116/ResourceClient.txt)
[SenderRootServerComponent.txt](https://github.com/eclipse/jetty.project/files/4556117/SenderRootServerComponent.txt)

NOTE: my production VM is ubuntu 18.04, 4Core CPU, 4GB Memory.

Thanks
Samba

**Comment by sbordet** [comment]
@SambaDamerla I cannot really help you, as all your attachments show some application code.

I don't see how this is a Jetty issue.
