### ISSUE TITLE
org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper refers to non-existent config file

### ISSUE THREAD

**Issue by sdybiec** [eclipse/jetty.project#4820]
**Jetty version** 9.4.28

**Java version** 8

**OS type/version** Windows 7

**Description**
Jetty 9.4.28 will not boot using OSGi and dies with this exception. 'jetty-deployer.xml' is no longer part of the 9.4.x distribution.

Caused by: java.nio.file.NoSuchFileException: S:\jetty-osgi-9.4-workspace\jetty.osgi\jettyhome\etc\jetty-deployer.xml
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.eclipse.jetty.util.resource.PathResource.getInputStream(PathResource.java:421)
	at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:241)
	at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:260)
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper.configure(ServerInstanceWrapper.java:140)
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper.startJettyAtJettyHome(DefaultJettyAtJettyHomeHelper.java:175)
	at org.eclipse.jetty.osgi.boot.JettyBootstrapActivator.start(JettyBootstrapActivator.java:86)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)

**Comment by janbartel** [comment]
@sdybiec  can you provide more description about your deployment environment? Again, osgi works for jetty-9.4.28 as evidenced by the REPO/jetty-osgi/test-jetty-osgi tests. We need to work out how your environment differs from the test environment.

**Comment by joakime** [comment]
@janbartel the `jetty-deployer.xml` on the `DefaultJettyAtJettyHomeHelper.DEFAULT_JETTY_ETC_FILES` will work in testing, as our testing has that file.

The file (in src/test/config) ...

https://github.com/eclipse/jetty.project/blob/jetty-9.4.28.v20200408/jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty-deployer.xml

The reference to it ...

https://github.com/eclipse/jetty.project/blob/ab228fde9e55e9164c738d7fa121f8ac5acd51c9/jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/serverfactory/DefaultJettyAtJettyHomeHelper.java#L65

**Comment by joakime** [comment]
PR #4821 opened

**Comment by janbartel** [comment]
Fixed.

**Comment by sdybiec** [comment]
You're awesome. Thanks for fixing this. 

To your question about my setup, I'm using the instructions on this web page to build and test my Jetty-on-Equinox environments. 

https://www.eclipse.org/jetty/documentation/current/framework-jetty-osgi.html

They mostly work for the 9.3.x series, but now struggling to get 9.4.x to work. I'll keep you posted.
