### ISSUE TITLE
Some JSP page compilation broken when running on OSGi

### ISSUE THREAD

**Issue by sdybiec** [eclipse/jetty.project#4834]
**Jetty version** 9.4.28

**Java version** 8

**OS type/version** Windows 7

**Description** Using the instructions on the Jetty OSGi page to build my Jetty-on-Equinox environment, then testing using the standard JSP examples, I found that several JSPs are broken and result in the same exception included below. Here's the source code for a few of the broken pages:

https://github.com/hash2100/progr-dist/blob/master/cap9/apache-tomcat-9.0.13/webapps/examples/jsp/jsp2/el/composite.jsp

https://github.com/hash2100/progr-dist/blob/master/cap9/apache-tomcat-9.0.13/webapps/examples/jsp/jsp2/jspx/basic.jspx

https://github.com/hash2100/progr-dist/blob/master/cap9/apache-tomcat-9.0.13/webapps/examples/jsp/jsp2/jspattribute/jspattribute.jsp

https://github.com/hash2100/progr-dist/blob/master/cap9/apache-tomcat-9.0.13/webapps/examples/jsp/num/numguess.jsp

and others.

I imported the org.mortbay.jasper.apache-jsp and org.mortbay.jasper.apache-el bundles into my workspace, added a javax.el package import to the org.mortbay.jasper.apache-jsp MANIFEST and everything now works.

javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:106)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1402)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: org/apache/el/util/JreCompat
	at org.apache.jasper.compiler.Generator$GenerateVisitor.visit(Generator.java:1364)
	at org.apache.jasper.compiler.Node$UseBean.accept(Node.java:1186)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441)
	at org.apache.jasper.compiler.Generator$GenerateVisitor.visit(Generator.java:1998)
	at org.apache.jasper.compiler.Node$UninterpretedTag.accept(Node.java:1256)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441)
	at org.apache.jasper.compiler.Generator$GenerateVisitor.generateJspFragment(Generator.java:3382)
	at org.apache.jasper.compiler.Generator$GenerateVisitor.generateCustomDoTag(Generator.java:2667)
	at org.apache.jasper.compiler.Generator$GenerateVisitor.visit(Generator.java:1897)
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441)
	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2447)
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:470)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.Generator.generate(Generator.java:3667)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:254)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:375)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:597)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	... 35 more
Caused by: java.lang.ClassNotFoundException: org.apache.el.util.JreCompat cannot be found by org.mortbay.jasper.apache-jsp_8.5.49
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:514)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:425)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 61 more

**Comment by janbartel** [comment]
Hmm, well you are using apache jasper from 9.x series with jetty-9.4 that is targetted against the 8.5.x series of jasper.

Also, the org.mortbay.jasper.apache-jsp manifest already contains an Import-Package statement for javax.el.

Can you make a small example webapp?

I have seen this error before, but only when I tested upgrading to apache jasper 8.5.50, and it was in a different place, so it would be good to have a reproduction test case to work against.

**Comment by joakime** [comment]
Details from `org.mortbay.jasper:apache-jsp:8.5.49` (the version the OP is using).

List of packages (with class files):

```
$ jar -tvf apache-jsp-8.5.49.jar | grep -E "\\.class$" | sed -e "s@^.*2019 \(.*\)/[A-Za-z0-9$\-]*\\.class@\1@" | sort -u
javax/servlet/jsp
javax/servlet/jsp/el
javax/servlet/jsp/tagext
org/apache/jasper
org/apache/jasper/compiler
org/apache/jasper/compiler/tagplugin
org/apache/jasper/el
org/apache/jasper/runtime
org/apache/jasper/security
org/apache/jasper/servlet
org/apache/jasper/tagplugins/jstl
org/apache/jasper/tagplugins/jstl/core
org/apache/jasper/util
org/apache/jasper/xmlparser
org/apache/juli/logging
org/apache/tomcat
org/apache/tomcat/util
org/apache/tomcat/util/buf
org/apache/tomcat/util/compat
org/apache/tomcat/util/descriptor
org/apache/tomcat/util/descriptor/tagplugin
org/apache/tomcat/util/descriptor/tld
org/apache/tomcat/util/descriptor/web
org/apache/tomcat/util/digester
org/apache/tomcat/util/file
org/apache/tomcat/util/res
org/apache/tomcat/util/scan
org/apache/tomcat/util/security
```

The `META-INF/MANIFEST.MF`

```
Manifest-Version: 1.0
Automatic-Module-Name: org.mortbay.apache.jasper
Bnd-LastModified: 1574746332811
Build-Jdk: 1.8.0_172
Built-By: janb
Bundle-Classpath: .
Bundle-Description: A rebundling of Apache Tomcat Jasper to remove the t
 omcat server dependencies,    so that the JSP engine can be used by the
  Eclipse Jetty project.
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0
Bundle-ManifestVersion: 2
Bundle-Name: Mortbay Jasper
Bundle-RequiredExecutionEnvironment: JavaSE-1.7
Bundle-SymbolicName: org.mortbay.jasper.apache-jsp
Bundle-Version: 8.5.49
Created-By: Apache Maven Bundle Plugin
Export-Package: org.apache.juli.logging;version="8.5.49",org.apache.tomc
 at;version="8.5.49",org.apache.tomcat.util.compat;version="8.5.49",org.
 apache.tomcat.util.scan;version="8.5.49",org.apache.tomcat.util.file;ve
 rsion="8.5.49",org.apache.tomcat.util.digester;version="8.5.49",org.apa
 che.tomcat.util.descriptor.tagplugin;version="8.5.49",org.apache.tomcat
 .util.descriptor.tld;version="8.5.49",org.apache.tomcat.util.descriptor
 .web;version="8.5.49",org.apache.tomcat.util;version="8.5.49",org.apach
 e.tomcat.util.buf;version="8.5.49",org.apache.tomcat.util.res;version="
 8.5.49",org.apache.tomcat.util.security;version="8.5.49",javax.servlet.
 jsp;version="2.3",javax.servlet.jsp.el;version="2.3",javax.servlet.jsp.
 tagext;version="2.3",javax.servlet.jsp.resources;version="2.3",org.apac
 he.jasper;version="8.5.49",org.apache.jasper.compiler;version="8.5.49",
 org.apache.jasper.compiler.tagplugin;version="8.5.49",org.apache.jasper
 .el;version="8.5.49",org.apache.jasper.resources;version="8.5.49",org.a
 pache.jasper.runtime;version="8.5.49",org.apache.jasper.security;versio
 n="8.5.49",org.apache.jasper.servlet;version="8.5.49",org.apache.jasper
 .tagplugins.jstl;version="8.5.49",org.apache.jasper.tagplugins.jstl.cor
 e;version="8.5.49",org.apache.jasper.util;version="8.5.49",org.apache.j
 asper.xmlparser;version="8.5.49"
Implementation-Version: 8.5.49
Import-Package: javax.el;version="3.0",javax.naming,javax.net.ssl,javax.
 servlet;version="3.0.1",javax.servlet.annotation;version="3.0.1",javax.
 servlet.descriptor;version="3.0.1",javax.servlet.http;version="3.0.1",j
 avax.servlet.resources;version="3.0.1",javax.xml.parsers,org.apache.tom
 cat.util.descriptor;version="8.5.4";resolution:=optional,org.apache.tom
 cat.util.descriptor.tagplugin;version="8.5.4";resolution:=optional,org.
 eclipse.jdt.core.compiler,org.eclipse.jdt.internal.compiler,org.eclipse
 .jdt.internal.compiler.classfmt,org.eclipse.jdt.internal.compiler.env,o
 rg.eclipse.jdt.internal.compiler.impl,org.eclipse.jdt.internal.compiler
 .problem,org.xml.sax,org.xml.sax.ext,org.xml.sax.helpers
Require-Capability: osgi.serviceloader;filter:="(osgi.serviceloader=org.
 apache.juli.logging.Log)";resolution:=optional;cardinality:=multiple,os
 gi.extender;filter:="(osgi.extender=osgi.serviceloader.processor)"
Specification-Version: 2.3
Tool: Bnd-4.0.0.201805111645
```

The Exports / Imports reformatted to be easier to read.

```
Export-Package: 
    org.apache.juli.logging;version="8.5.49"
    org.apache.tomcat;version="8.5.49"
    org.apache.tomcat.util.compat;version="8.5.49"
    org.apache.tomcat.util.scan;version="8.5.49"
    org.apache.tomcat.util.file;version="8.5.49"
    org.apache.tomcat.util.digester;version="8.5.49"
    org.apache.tomcat.util.descriptor.tagplugin;version="8.5.49"
    org.apache.tomcat.util.descriptor.tld;version="8.5.49"
    org.apache.tomcat.util.descriptor.web;version="8.5.49"
    org.apache.tomcat.util;version="8.5.49"
    org.apache.tomcat.util.buf;version="8.5.49"
    org.apache.tomcat.util.res;version="8.5.49"
    org.apache.tomcat.util.security;version="8.5.49"
    javax.servlet.jsp;version="2.3"
    javax.servlet.jsp.el;version="2.3"
    javax.servlet.jsp.tagext;version="2.3"
    javax.servlet.jsp.resources;version="2.3"
    org.apache.jasper;version="8.5.49"
    org.apache.jasper.compiler;version="8.5.49"
    org.apache.jasper.compiler.tagplugin;version="8.5.49"
    org.apache.jasper.el;version="8.5.49"
    org.apache.jasper.resources;version="8.5.49"
    org.apache.jasper.runtime;version="8.5.49"
    org.apache.jasper.security;version="8.5.49"
    org.apache.jasper.servlet;version="8.5.49"
    org.apache.jasper.tagplugins.jstl;version="8.5.49"
    org.apache.jasper.tagplugins.jstl.core;version="8.5.49"
    org.apache.jasper.util;version="8.5.49"
    org.apache.jasper.xmlparser;version="8.5.49"

Import-Package: 
    javax.el;version="3.0"
    javax.naming
    javax.net.ssl
    javax.servlet;version="3.0.1"
    javax.servlet.annotation;version="3.0.1"
    javax.servlet.descriptor;version="3.0.1"
    javax.servlet.http;version="3.0.1"
    javax.servlet.resources;version="3.0.1"
    javax.xml.parsers
    org.apache.tomcat.util.descriptor;version="8.5.4";resolution:=optional
    org.apache.tomcat.util.descriptor.tagplugin;version="8.5.4";resolution:=optional
    org.eclipse.jdt.core.compiler
    org.eclipse.jdt.internal.compiler
    org.eclipse.jdt.internal.compiler.classfmt
    org.eclipse.jdt.internal.compiler.env
    org.eclipse.jdt.internal.compiler.impl
    org.eclipse.jdt.internal.compiler.problem
    org.xml.sax
    org.xml.sax.ext
    org.xml.sax.helpers
```

I noticed that the only package from this jar that is also _not_ present in `Export-Packages` is `org.apache.tomcat.util.descriptor`

Which has the following classes.

```
$ jar -tvf apache-jsp-8.5.49.jar | grep -E "org/apache/tomcat/util/descriptor/[A-Za-z0-9$]*.class"
   744 Tue Nov 26 16:32:24 CST 2019 org/apache/tomcat/util/descriptor/Constants.class
  6654 Tue Nov 26 16:32:24 CST 2019 org/apache/tomcat/util/descriptor/DigesterFactory.class
   913 Tue Nov 26 16:32:24 CST 2019 org/apache/tomcat/util/descriptor/InputSourceUtil.class
  3939 Tue Nov 26 16:32:24 CST 2019 org/apache/tomcat/util/descriptor/LocalResolver.class
  2566 Tue Nov 26 16:32:24 CST 2019 org/apache/tomcat/util/descriptor/XmlErrorHandler.class
  2630 Tue Nov 26 16:32:24 CST 2019 org/apache/tomcat/util/descriptor/XmlIdentifiers.class
```

**Comment by janbartel** [comment]
@sdybiec any progress with making a small repro webapp for me to test?

**Comment by sdybiec** [comment]
Not yet. Had to work on another project, so it'll be a couple weeks.

**Comment by janbartel** [comment]
@sdybiec any progress?

**Comment by saturna** [comment]
I have ran into identical issue with Jetty 9.4.37 in our OSGi project. The fix was to append "org.apache.el.util" to MANIFEST's Import-Package for org.mortbay.apache-jsp bundle. As per error, this bundle makes use of org.apache.el.util.JreCompat, but it doesn't import it. I think there is some confusion around which packages org.mortbay.apache-jsp contains, the source bundle includes org.apache.el.util but the compiled bundle doesn't. The package is normally found in org.mortbay.apache-el.

**Comment by janbartel** [comment]
I raised and fixed this issue over at the jetty-jasper project:  https://github.com/jetty-project/jasper-jsp/issues/93. Next time we do releases this fix will be present.
