### ISSUE TITLE
HTTP/2 Client catch java.nio.channels.AsynchronousCloseException

### ISSUE THREAD

**Issue by xrkCode** [eclipse/jetty.project#4883]
**Jetty version**
  9.4.19.v20190610
**Java version**
  jdk-1.8.0_242
**OS type/version**
  linux-suse
**Description**
Client use HTTP2Client send a request but catch an Exception, it only happened once
```
| ERROR | defaultHttp2Client-3232        | HTTP2ClientWrapperImpl           |onFailure() 278 | http2client |  |  |  
java.nio.channels.AsynchronousCloseException: null
	at org.eclipse.jetty.http2.client.http.HttpConnectionOverHTTP2.close(HttpConnectionOverHTTP2.java:144)
	at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2.onClose(HttpClientTransportOverHTTP2.java:170)
	at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2$SessionListenerPromise.onClose(HttpClientTransportOverHTTP2.java:232)
	at org.eclipse.jetty.http2.api.Session$Listener.onClose(Session.java:206)
	at org.eclipse.jetty.http2.HTTP2Session.notifyClose(HTTP2Session.java:1153)
	at org.eclipse.jetty.http2.HTTP2Session.onGoAway(HTTP2Session.java:438)
	at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onGoAway(Parser.java:392)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyGoAway(BodyParser.java:187)
	at org.eclipse.jetty.http2.parser.GoAwayBodyParser.onGoAway(GoAwayBodyParser.java:169)
	at org.eclipse.jetty.http2.parser.GoAwayBodyParser.parse(GoAwayBodyParser.java:139)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:194)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:123)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:248)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:170)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:125)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:348)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:808)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:944)
	at java.lang.Thread.run(Thread.java:748)
| ERROR | adPool_platform#futureEcs-2121 | InnerServiceProxy                |handleExcepion() 550 | com.huawei.ncecommon.bp.servicecommunication.proxy |  |  | call async execption 
com.huawei.enterprise.naas.servicecommunication.proxy.api.RestfulClientException: java.nio.channels.AsynchronousCloseException
	at com.huawei.controller.bp.http2.client.internal.impl.HTTP2ClientWrapperImpl$2$1.run(HTTP2ClientWrapperImpl.java:284)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.huawei.enterprise.platform.concurrent.api.TtlRunnable.run(TtlRunnable.java:34)
	at com.huawei.enterprise.platform.concurrent.impl.WrapperRunnable.run(WrapperRunnable.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.AsynchronousCloseException: null
	at org.eclipse.jetty.http2.client.http.HttpConnectionOverHTTP2.close(HttpConnectionOverHTTP2.java:144)
	at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2.onClose(HttpClientTransportOverHTTP2.java:170)
	at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2$SessionListenerPromise.onClose(HttpClientTransportOverHTTP2.java:232)
	at org.eclipse.jetty.http2.api.Session$Listener.onClose(Session.java:206)
	at org.eclipse.jetty.http2.HTTP2Session.notifyClose(HTTP2Session.java:1153)
	at org.eclipse.jetty.http2.HTTP2Session.onGoAway(HTTP2Session.java:438)
	at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onGoAway(Parser.java:392)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyGoAway(BodyParser.java:187)
	at org.eclipse.jetty.http2.parser.GoAwayBodyParser.onGoAway(GoAwayBodyParser.java:169)
	at org.eclipse.jetty.http2.parser.GoAwayBodyParser.parse(GoAwayBodyParser.java:139)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:194)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:123)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:248)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:170)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:125)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:348)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:808)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:944)
	... 1 common frames omitted
```
But the server get the request and handler it success.
So why the client get the AsynchronousCloseException?
How to solve the problem?

**Comment by sbordet** [comment]
The stack trace shows that the client received a GOAWAY frame from the server, so it's the server that closed the connection.

You should look into the server to understand why it closed the connection.

**Comment by xrkCode** [comment]
Hi，@sbordet，thank you for the reply.
The server is also jetty-9.4.19.v20190610, I found some Exception in the server log:

| ERROR | ol_platform#RpcBroker-thread-3 | ServerRuntime$Responder          |writeResponse() 736 | org.glassfish.jersey.core.jersey-server |  |  | Error while closing the output stream in order to commit response. 
java.lang.IllegalStateException: WRITER
	at org.eclipse.jetty.server.Response.getOutputStream(Response.java:715)
	at com.huawei.controller.platform.operlog.filter.CachingHttpServletResponse.getOutputStream(CachingHttpServletResponse.java:33)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.writeResponseStatusAndHeaders(ResponseWriter.java:180)
	at org.glassfish.jersey.server.ServerRuntime$Responder$1.getOutputStream(ServerRuntime.java:652)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:195)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:300)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:256)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:271)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:848)
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:413)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:734)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at com.huawei.ncecommon.netconf.service.messagemgr.rest.AsyncRpcRestResponse.setResult(AsyncRpcRestResponse.java:40)
	at com.huawei.ncecommon.netconf.service.messagemgr.ReplyResponseTask.responseCall(ReplyResponseTask.java:85)
	at com.huawei.ncecommon.netconf.service.messagemgr.ReplyResponseMatcher.match(ReplyResponseMatcher.java:69)
	at com.huawei.ncecommon.netconf.service.messagemgr.ReplyCenter.executeReplyRequest(ReplyCenter.java:42)
	at com.huawei.ncecommon.netconf.service.communication.msgconsume.RpcReplyMessageConsumer.onNotifyMessage(RpcReplyMessageConsumer.java:32)
	at com.huawei.ncecommon.netconf.cluster.comm.impl.NetconfCommReceiveServiceImpl.receivePackage(NetconfCommReceiveServiceImpl.java:91)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.huawei.enterprise.component.manager.proxy.ProxyRpcObject.actorCall(ProxyRpcObject.java:76)
	at com.huawei.enterprise.component.manager.proxy.ProxyRpcObject.invoke(ProxyRpcObject.java:60)
	at com.sun.proxy.$Proxy116.receivePackage(Unknown Source)
	at org.opendaylight.yangtools.yang.binding.util.RpcMethodInvokerWithInput.invokeOn(RpcMethodInvokerWithInput.java:32)
	at org.opendaylight.yangtools.yang.binding.util.AbstractMappedRpcInvoker.invokeRpc(AbstractMappedRpcInvoker.java:53)
	at org.opendaylight.controller.md.sal.binding.impl.BindingDOMRpcImplementationAdapter.invoke(BindingDOMRpcImplementationAdapter.java:437)
	at org.opendaylight.controller.md.sal.binding.impl.BindingDOMRpcImplementationAdapter.invokeRpc(BindingDOMRpcImplementationAdapter.java:199)
	at org.opendaylight.controller.md.sal.dom.broker.impl.RoutedDOMRpcRoutingTableEntry.invokeRpc(RoutedDOMRpcRoutingTableEntry.java:64)
	at org.opendaylight.controller.md.sal.dom.broker.impl.DOMRpcRoutingTable.invokeRpc(DOMRpcRoutingTable.java:186)
	at org.opendaylight.controller.md.sal.dom.broker.impl.DOMRpcRouter.invokeRpc(DOMRpcRouter.java:123)
	at Proxy081e648f_fa85_4b4e_800d_292f086de0fb.invokeRpc(Unknown Source)
	at Proxy0c23eb2a_77f4_45a9_bd54_a442c5a740b5.invokeRpc(Unknown Source)
	at org.opendaylight.controller.remote.rpc.RpcInvoker.executeRpc(RpcInvoker.java:402)
	at org.opendaylight.controller.remote.rpc.RpcInvoker.access$900(RpcInvoker.java:89)
	at org.opendaylight.controller.remote.rpc.RpcInvoker$DeserializationTask.run(RpcInvoker.java:338)
	at com.huawei.enterprise.platform.concurrent.api.TtlRunnable.run(TtlRunnable.java:34)
	at com.huawei.enterprise.platform.concurrent.impl.WrapperRunnable.run(WrapperRunnable.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Is it the client AsynchronousCloseExceptioncaused caused by this server exception?
Why it happend and how to solve?

**Comment by xrkCode** [comment]
Hi，@sbordet，thank you for the reply.
The server is also jetty-9.4.19.v20190610, I found some Exception in the server log:

| ERROR | ol_platform#RpcBroker-thread-3 | ServerRuntime$Responder          |writeResponse() 736 | org.glassfish.jersey.core.jersey-server |  |  | Error while closing the output stream in order to commit response. 
java.lang.IllegalStateException: WRITER
	at org.eclipse.jetty.server.Response.getOutputStream(Response.java:715)
	at com.huawei.controller.platform.operlog.filter.CachingHttpServletResponse.getOutputStream(CachingHttpServletResponse.java:33)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.writeResponseStatusAndHeaders(ResponseWriter.java:180)
	at org.glassfish.jersey.server.ServerRuntime$Responder$1.getOutputStream(ServerRuntime.java:652)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:195)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:300)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:256)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:271)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:848)
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:413)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:734)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at com.huawei.ncecommon.netconf.service.messagemgr.rest.AsyncRpcRestResponse.setResult(AsyncRpcRestResponse.java:40)
	at com.huawei.ncecommon.netconf.service.messagemgr.ReplyResponseTask.responseCall(ReplyResponseTask.java:85)
	at com.huawei.ncecommon.netconf.service.messagemgr.ReplyResponseMatcher.match(ReplyResponseMatcher.java:69)
	at com.huawei.ncecommon.netconf.service.messagemgr.ReplyCenter.executeReplyRequest(ReplyCenter.java:42)
	at com.huawei.ncecommon.netconf.service.communication.msgconsume.RpcReplyMessageConsumer.onNotifyMessage(RpcReplyMessageConsumer.java:32)
	at com.huawei.ncecommon.netconf.cluster.comm.impl.NetconfCommReceiveServiceImpl.receivePackage(NetconfCommReceiveServiceImpl.java:91)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.huawei.enterprise.component.manager.proxy.ProxyRpcObject.actorCall(ProxyRpcObject.java:76)
	at com.huawei.enterprise.component.manager.proxy.ProxyRpcObject.invoke(ProxyRpcObject.java:60)
	at com.sun.proxy.$Proxy116.receivePackage(Unknown Source)
	at org.opendaylight.yangtools.yang.binding.util.RpcMethodInvokerWithInput.invokeOn(RpcMethodInvokerWithInput.java:32)
	at org.opendaylight.yangtools.yang.binding.util.AbstractMappedRpcInvoker.invokeRpc(AbstractMappedRpcInvoker.java:53)
	at org.opendaylight.controller.md.sal.binding.impl.BindingDOMRpcImplementationAdapter.invoke(BindingDOMRpcImplementationAdapter.java:437)
	at org.opendaylight.controller.md.sal.binding.impl.BindingDOMRpcImplementationAdapter.invokeRpc(BindingDOMRpcImplementationAdapter.java:199)
	at org.opendaylight.controller.md.sal.dom.broker.impl.RoutedDOMRpcRoutingTableEntry.invokeRpc(RoutedDOMRpcRoutingTableEntry.java:64)
	at org.opendaylight.controller.md.sal.dom.broker.impl.DOMRpcRoutingTable.invokeRpc(DOMRpcRoutingTable.java:186)
	at org.opendaylight.controller.md.sal.dom.broker.impl.DOMRpcRouter.invokeRpc(DOMRpcRouter.java:123)
	at Proxy081e648f_fa85_4b4e_800d_292f086de0fb.invokeRpc(Unknown Source)
	at Proxy0c23eb2a_77f4_45a9_bd54_a442c5a740b5.invokeRpc(Unknown Source)
	at org.opendaylight.controller.remote.rpc.RpcInvoker.executeRpc(RpcInvoker.java:402)
	at org.opendaylight.controller.remote.rpc.RpcInvoker.access$900(RpcInvoker.java:89)
	at org.opendaylight.controller.remote.rpc.RpcInvoker$DeserializationTask.run(RpcInvoker.java:338)
	at com.huawei.enterprise.platform.concurrent.api.TtlRunnable.run(TtlRunnable.java:34)
	at com.huawei.enterprise.platform.concurrent.impl.WrapperRunnable.run(WrapperRunnable.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Is it the client AsynchronousCloseExceptioncaused caused by this server exception?
Why it happend and how to solve?

**Comment by sbordet** [comment]
>  java.lang.IllegalStateException: WRITER

This is likely an application mistake.
You are not allowed to call `response.getWriter()` and then `response.getOutputStream()`.

**Comment by joakime** [comment]
> > java.lang.IllegalStateException: WRITER
> 
> This is likely an application mistake.
> You are not allowed to call `response.getWriter()` and then `response.getOutputStream()`.

Link to relevant javadoc for this ...

https://docs.oracle.com/javaee/7/api/javax/servlet/ServletResponse.html#getOutputStream--

**Comment by janbartel** [comment]
@xrkCode it seems your question has been answered by sbordet, so I'm closing this issue as you haven't indicated that there is still a problem.
