### ISSUE TITLE
JDBCSessionDataStore fails to create multiple JettySessions for server with multiple databases

### ISSUE THREAD

**Issue by sergiuhlihor** [eclipse/jetty.project#4894]
Jetty version:  9.4.x (confirmed from 9.4.5 to 9.4.28) ,  Java 11
OS: Ubuntu 18.04
Database: MySQL 8.0.19
MySQL connector 8.0.19

Jetty 9.4.x branch fails to create properly the JettySessions table at startup when database instances hosts more than one sessions schemas and at least one already has the table created. 
To reproduce:
  - create two independent sessions schemas, called schemaA and schemaB.
  - setup two applications with **same database user** having access to both schemaA and schemaB
  - start first application with sessions connection locked to schemaA. This will create JettySessions table correctly.
  - start second application with sessions connection locked to schemaB. The second application detects that exists at least JettySessions table, which would be correct if user is shared, but fails to check if it exists relative to existing schema defined in JDBC url. However later when querying for sessions, all queries are relative to existing schema. 

JDBCSessionDataStore, line 487 (String schemaName = _dbAdaptor.convertIdentifier(getSchemaName()); ) builds a null schemaName. Suggested fix would be to have it build based on existing used schema if null. 

JDBC connection:
jdbc:mysql://localhost:3306/schemaB?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useCompression=true

Stacktrace
java.sql.SQLSyntaxErrorException: Table 'schemaB.JettySessions' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.eclipse.jetty.server.session.JDBCSessionDataStore.doInsert(JDBCSessionDataStore.java:721)
	at org.eclipse.jetty.server.session.JDBCSessionDataStore.doStore(JDBCSessionDataStore.java:676)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore$1.run(AbstractSessionDataStore.java:142)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1448)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1467)
	at org.eclipse.jetty.server.session.SessionContext.run(SessionContext.java:92)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.store(AbstractSessionDataStore.java:155)
	at org.eclipse.jetty.server.session.AbstractSessionCache.release(AbstractSessionCache.java:572)
	at org.eclipse.jetty.server.session.SessionHandler.complete(SessionHandler.java:368)
	at org.eclipse.jetty.server.Request.leaveSession(Request.java:399)
	at org.eclipse.jetty.server.Request.onCompleted(Request.java:1531)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:363)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by janbartel** [comment]
You know you can change the table names to be different, right?

If you're using the standard distro, you can edit the session-store-jdbc.ini file and set all of the relevant jdbc artfact names: name of the table and names of all the columns. These are the properties (don't forget to remove the comment character at the beginning of the line):

\#\# Session table schema
#jetty.session.jdbc.schema.accessTimeColumn=accessTime
#jetty.session.jdbc.schema.contextPathColumn=contextPath
#jetty.session.jdbc.schema.cookieTimeColumn=cookieTime
#jetty.session.jdbc.schema.createTimeColumn=createTime
#jetty.session.jdbc.schema.expiryTimeColumn=expiryTime
#jetty.session.jdbc.schema.lastAccessTimeColumn=lastAccessTime
#jetty.session.jdbc.schema.lastSavedTimeColumn=lastSavedTime
#jetty.session.jdbc.schema.idColumn=sessionId
#jetty.session.jdbc.schema.lastNodeColumn=lastNode
#jetty.session.jdbc.schema.virtualHostColumn=virtualHost
#jetty.session.jdbc.schema.maxIntervalColumn=maxInterval
#jetty.session.jdbc.schema.mapColumn=map
**#jetty.session.jdbc.schema.table=JettySessions**

**Comment by janbartel** [comment]
@sergiuhlihor see this line in the code where we determine if we need to create the table or not:

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/JDBCSessionDataStore.java#L488

If `_schemaName` is non-null, will that work in your environment to differentiate the 2 different instances?  It seems we forgot to create a property in session-store-jdbc.ini file to allow schemaName to be set. I can add one in if you can confirm that will fix it.

**Comment by sergiuhlihor** [comment]
@janbartel I was aware of _tableName however in my setup we customize databases to run multiple copies of same environments. I think customizing _schemaName as an option would be welcome independent of this ticket. However, I just looked at the code. A few lines above (481) you have a Connection which has a method getSchema() which returns exactly the current one. I think the fix would be to take Connection.getSchema() if _schemaName is null at that point.

**Comment by janbartel** [comment]
@sergiuhlihor actually I'm getting confused here:  are you sure that "schema" is the right thing here? To get the terminology right, according to the mysql documentation, you have 1 host at localhost listening on port 3306, and 2 _databases_ one called "databaseA" and the other "databaseB". How does this relate to "schema"?

**Comment by sergiuhlihor** [comment]
@janbartel My bad for confusion. In MySQL sometimes we refer to schemas as "databases". By databaseA or databaseB I was referring to schemas. I have edited my comments to better reflect the ticket.

In my case, I use a single MySQL instance to host 10+ identical environments, where inside the instance there are different schemas (example sessions1, sessions2... sessions10) . Then templating for whole environments is done based on JDBC connection where application1 gets sessions1, applications2 gets sessions2, etc. Since the schema used is defined in connection url, this is why I believe the correct treatment may be just using the connection.getSchema() if _schemaName is null. From what I see, Jetty is appears to be using the schema specified in connection when persisting the sessions, thus resulting the the stacktrace I posted.

**Comment by janbartel** [comment]
So after some good detective work from @lorban, it seems that there is no consistency between various database vendors on what is a schema and what is a catalog. So the safest thing for us to do is to 1) expose the schemaName as a property in the session-store-jdbc.mod file so it can easily be set, and also provide a setter for the catalogName too  2) fallback to the values provided by the connection.

**Comment by lorban** [comment]
The reason why a `catalogName` property should be added is because in this particular case (i.e.: MySQL) calling `metaData.getTables(null, connection.getSchema(), tableName, null)` does not help, but `metaData.getTables(connection.getCatalog(), schemaName, tableName, null)` does solve the problem at hand.

This is because MySQL maps what they call the database name to the JDBC schema: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html#idm45580377677216

**Comment by sergiuhlihor** [comment]
@lorban Could we have then the catalogName and a fallback to connection.getCatalog() when not set?

**Comment by lorban** [comment]
This is exactly what @janbartel 's proposition is about.

**Comment by sergiuhlihor** [comment]
Perfect, waiting eagerly for a fix :+1:

**Comment by janbartel** [comment]
@sergiuhlihor any comment on the PR https://github.com/eclipse/jetty.project/pull/4908 before I commit it?

**Comment by sergiuhlihor** [comment]
Looks good! Thank you!

**Comment by janbartel** [comment]
Fix checked in to jetty-9.4.x, will go out with 9.4.30.

**Comment by sergiuhlihor** [comment]
Forgot to ask... is there any way to set the new settings at code level? I'm running Jetty as embedded and I have a bit of struggle in finding a way to override the existing defaults.

**Comment by janbartel** [comment]
@sergiuhlihor  so there are 2 new setters on the org.eclipse.jetty.server.session.SessionTableSchema class for the catalog and schema. If you want to see an example (albeit not one that sets the catalog and schema, but does set other column names etc) then have a look at a test case here: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/tests/test-sessions/test-jdbc-sessions/src/test/java/org/eclipse/jetty/server/session/JdbcTestHelper.java#L135

**Comment by sergiuhlihor** [comment]
@janbartel Was too obvious. Worked! Thanks!
