### ISSUE TITLE
UnsupportedOperationException at javax.net.ssl.SSLEngine.getHandshakeSession when using RSA SSLJ

### ISSUE THREAD

**Issue by vanand123** [eclipse/jetty.project#4961]
**Jetty version**
jetty-distribution-9.4.25.v20191220

**Java version**
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK Server VM (build 25.191-b12, mixed mode)

**OS type/version**
CentOS Linux release 7.6.1810 (Core)

**Description**
Upgrading Jetty from "9.2.18.v20160721" to "9.4.25.v20191220".

When trying to setup tunnel.html on Jetty version "9.4.25.v20191220" with endpoint which is running on secure port.
After setting the TLS context, when it is going to getBufferSize then it is getting redirected to SSLEngine.getHandshakeSession.
And then it is throwing java.lang.UnsupportedOperationException as below:

2020-06-10 21:46:41 DEBUG ManagedSelector:764 -
java.lang.UnsupportedOperationException
        at javax.net.ssl.SSLEngine.getHandshakeSession(SSLEngine.java:1007)
        at org.eclipse.jetty.io.ssl.SslConnection.getBufferSize(SslConnection.java:325)
        at org.eclipse.jetty.io.ssl.SslConnection.getApplicationBufferSize(SslConnection.java:315)
        at org.eclipse.jetty.io.ssl.SslConnection.access$500(SslConnection.java:80)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.setConnection(SslConnection.java:597)
        at org.eclipse.jetty.server.SslConnectionFactory.newConnection(SslConnectionFactory.java:116)
        at org.eclipse.jetty.server.ServerConnector$ServerConnectorManager.newConnection(ServerConnector.java:549)
        at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:271)
        at org.eclipse.jetty.io.ManagedSelector.access$1800(ManagedSelector.java:62)
        at org.eclipse.jetty.io.ManagedSelector$Accept.run(ManagedSelector.java:759)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:748)

We are not seeing any Exception with old jetty version "9.2.18.v20160721" and able to setup tunnel.html with endpoint running on secure port.
Attached the logs for both success(jetty_9.2.18.v20160721.txt) and failure scenario(jetty_9.4.25.v20191220.txt)

[jetty_9.4.25.v20191220.txt](https://github.com/eclipse/jetty.project/files/4763559/jetty_9.4.25.v20191220.txt)
[jetty_9.2.18.v20160721.txt](https://github.com/eclipse/jetty.project/files/4763561/jetty_9.2.18.v20160721.txt)

**Comment by sbordet** [comment]
This is likely a JDK issue you are having.
I recommend that you update to OpenJDK 8u252.

**Comment by joakime** [comment]
The UnsupportedOperationException is correctly thrown if the SSL provider you are using doesn't implement that method.

https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLEngine.html#getHandshakeSession--

Looking at your logs you seem to be using CiscoJCE(NativeCrypto) and RSA BSAFE_SSL_J as your SSL/TLS providers.
Seen as ...
```
security.provider.3=com.rsa.jsse.JsseProvider
2020-06-10 21:45:34 INFO  CiscoJCEProvider:1656 - run - CiscoJCEProvider version 5.3.3.2019-12-05-19-17-48 loading...
2020-06-10 21:45:34 INFO  CiscoJCEProvider:1657 - run - CiscoJCEProvider - CiscoJCEProvider version 5.003003 loading...
2020-06-10 21:45:34 INFO  CiscoJCEProvider:1660 - run - Library: CiscoSSL 1.0.2u.6.2.374-fips loading...
```

Remove both CiscoJCE and BSAFE_SSL and try again.
If it runs, then you know you have a valid configuration and proper Java support for SSL/TLS.
Then you'll have to contact your CiscoJCE and BSAFE_SSL experts to upgrade those products to one that supports your version of Java.

**Comment by vanand123** [comment]
By using CiscoJCE(NativeCrypto) and RSA BSAFE_SSL_J as SSL/TLS providers in Jetty version "9.2.18.v20160721" and there i'm not seeing any issue.
Please check "jetty_9.2.18.v20160721.txt"

**Comment by sbordet** [comment]
@vanand123 in Jetty 9.2.x we are not calling `SSLEngine.getHandshakeSesssion()`, but we do in Jetty 9.4.x.

The JCE provider is at fault by not implementing that method.
Remove those providers are you will see that everything works, or contact them to get the providers fixed.

**Comment by vanand123** [comment]
After removing JCE provider, getting another Exception as below:

java.io.IOException: parseAlgParameters failed: PBES2 AlgorithmParameters not available
        at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:816)
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2018)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1188)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:323)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:92)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:320)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1888)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837)
Caused by: java.security.NoSuchAlgorithmException: PBES2 AlgorithmParameters not available
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.security.Security.getImpl(Security.java:695)
        at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:146)
        at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:808)
        ... 22 more

![PBES2_algo_na](https://user-images.githubusercontent.com/66744134/85283162-8b232e00-b4aa-11ea-9e8e-22a9123645d4.JPG)

**Comment by sbordet** [comment]
@vanand123 so the problem is detailed in the exception:

```
 Caused by: java.security.NoSuchAlgorithmException: PBES2 AlgorithmParameters not available
```

Double check your `SslContextFactory` configuration.

**Comment by vanand123** [comment]
@sbordet Support for getHandshakeSession() was added in CiscoJ 6.0.9 and CiscoJ 7.0.1.
So, upgrading to latest CiscoJ 6.0.10 resolved this issue.

**Comment by sbordet** [comment]
Thanks for the feedback.
