### ISSUE TITLE
Prevent parsing of module-info.class in OSGi bundles

### ISSUE THREAD

**Issue by hieplq** [eclipse/jetty.project#4989]
**Jetty version**
9.4.28
**Java version**
jdk-13
**OS type/version**
linux mint debian
**Description**
i get bellow error on console when run webapp
```
15:10:39.990-----------> ClassInheritanceHandler.warn:  [33]
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:75)
	at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:62)
	at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:507)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:542)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:952)
	at org.eclipse.jetty.osgi.annotations.AnnotationParser.parse(AnnotationParser.java:220)
	at org.eclipse.jetty.osgi.annotations.AnnotationConfiguration$BundleParserTask.call(AnnotationConfiguration.java:64)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:455)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

reason:
annotation scan library jakarta.xml.ws-api_2.3.2.jar
inside this bundle has module-info.class but it's not class so classInfo.getSuperName() on bellow code get null value

org.eclipse.jetty.annotations.ClassInheritanceHandler

```java
@Override
    public void handle(ClassInfo classInfo)
    {
        try
        {
            //Don't scan Object
            if ("java.lang.Object".equals(classInfo.getClassName()))
                return;

            for (int i = 0; classInfo.getInterfaces() != null && i < classInfo.getInterfaces().length; i++)
            {
                addToInheritanceMap(classInfo.getInterfaces()[i], classInfo.getClassName());
            }
            //To save memory, we don't record classes that only extend Object, as that can be assumed
            if (!"java.lang.Object".equals(classInfo.getSuperName()))
            {
                addToInheritanceMap(classInfo.getSuperName(), classInfo.getClassName());
            }
        }
        catch (Exception e)
        {
            LOG.warn(e);
        }
    }
```

**Comment by janbartel** [comment]
@hieplq how is the jakarta.xml.ws-api_2.3.2.jar declared to be related to the webapp that is being deployed? Is  it deployed into the container, and you've set the org.eclipse.jetty.server.webapp.containerIncludeBundlePattern context attribute to include it?? Or is it inside the WEB-INF/lib of the war file that you're deploying into osgi?? Or some other way?

**Comment by hieplq** [comment]
it's on Require-Bundle
on my application, we use equinox as Osgi container and jetty is deploy as Osgi bundle 
webapp is other Osgi bundle in equinox with Web-ContextPath
jakarta.xml.ws-api declare as Require-Bundle on webapp bundle

**Comment by janbartel** [comment]
Thanks @hieplq, I've raised PR #4991.
