### ISSUE TITLE
Async timeout / dispatch causing IllegalStateException

### ISSUE THREAD

**Issue by ztravis** [eclipse/jetty.project#5009]
**Jetty version**
9.4.28.v20200408, 9.4.30.v20200611

**Java version**
1.8.0_201-b09

**OS type/version**
Ubuntu (18.04)

**Description**
I'm seeing occasional IllegalStateExceptions being thrown in HttpChannelState when attempting to write an async result.
Our use case (which seems pretty typical) is to be able to write an async result when one becomes available or a default empty result on timeout. However, it seems like when the async result is available very close to the timeout, sometimes an exception is thrown when trying to write it. This has only started happening after moving from 9.4.20 to 9.4.28 (presumably as as result of https://github.com/eclipse/jetty.project/pull/3912).

Here is an example (truncated) stack trace:

```
SEVERE: Exception during POST request for XXXXXX:
java.lang.IllegalStateException: s=WOKEN rs=EXPIRE os=OPEN is=IDLE awp=false se=false i=false al=1
        at org.eclipse.jetty.server.HttpChannelState.dispatch(HttpChannelState.java:588)
        at org.eclipse.jetty.server.AsyncContextState.dispatch(AsyncContextState.java:94)
        at org.springframework.security.web.servletapi.HttpServlet3RequestFactory$SecurityContextAsyncContext.dispatch(HttpServlet3Request
Factory.java:290)
        at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
        at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
        at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
        at org.springframework.web.context.request.async.DeferredResult.setResult(DeferredResult.java:238)
        ....
```

From my reading of the PR and the 9.4.28 source, it seems like now that the actual `HttpChannelState#onTimeout()` call is async to the `HttpChannelState#timeout()` trigger, there's a window in which the channel is in an un-dispatchable/unwriteable state (`EXPIRE`) but no timeout callbacks have been fired. Is this expected? Is there some other way we should be interacting with the channel (or our spring `DeferredResult`) to avoid this? 

**EDIT: I also apologize for not having tried this on the latest version! I didn't see anything in the release notes about it but I will see if I can test now.

**Comment by ztravis** [comment]
I am able to reproduce this on 9.4.30.

**Comment by joakime** [comment]
@ztravis do you have an example project that you can share which will produce this?

**Comment by ztravis** [comment]
Not at the moment, but I can probably put together a small example. For testing I set a breakpoint at the end of `HttpChannelState#timeout()` and once that was hit, called `DeferredResult#setResult` in a separate thread.
