### ISSUE TITLE
java.lang.IllegalStateException: isReady() not called

### ISSUE THREAD

**Issue by cstamas** [eclipse/jetty.project#5016]
**Jetty version**: 
9.4.30.v20200611

**Java version**:
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**OS type/version**
Linux 3.10.0-1062.12.1.el7.x86_64 / CentOS 7.7

**Description**
Sporadic errors when response buffer is flushed.

A template (Velocity) is being rendered, and writes to (wrapped with BufferedWriter) response.OutputStream. 
The request is NOT invoking `javax.servlet.ServletRequest#startAsync(javax.servlet.ServletRequest, javax.servlet.ServletResponse)` so the request processing did not start any async work (but see below for "speculation" part).

But, under load, from time to time, we see strange errors like this:

```
2020-07-02 08:09:25,180+0000 WARN  [qtp1-235] *SYSTEM org.sonatype.nexus.web.internal.ErrorPageFilter - Unexpected exception
java.lang.IllegalStateException: isReady() not called: s=OPEN,api=ASYNC,sc=false,e=null
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:686)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at org.sonatype.nexus.web.internal.VelocityTemplateRenderer.render(VelocityTemplateRenderer.java:144)
        at org.sonatype.nexus.web.internal.VelocityTemplateRenderer.render(VelocityTemplateRenderer.java:121)
        at org.sonatype.nexus.web.internal.VelocityTemplateRenderer.renderErrorPage(VelocityTemplateRenderer.java:96)
        at org.sonatype.nexus.web.internal.ErrorPageServlet.service(ErrorPageServlet.java:72)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:300)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:284)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:188)
        at com.google.inject.servlet.AbstractServletPipeline.service(AbstractServletPipeline.java:63)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
        at com.walmart.warm.webapp.qos.QosFilter.doFilter(QosFilter.java:211)
        at com.walmart.warm.webapp.qos.BLFilter.doFilter(BLFilter.java:225)
        at org.sonatype.nexus.web.internal.CommonHeadersFilter.doFilter(CommonHeadersFilter.java:69)
        at org.sonatype.nexus.web.internal.ErrorPageFilter.doFilter(ErrorPageFilter.java:93)
        at org.sonatype.nexus.web.internal.BaseUrlHolderFilter.doFilter(BaseUrlHolderFilter.java:66)
        at org.sonatype.nexus.web.internal.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:92)
        at com.google.inject.servlet.AbstractFilterPipeline.dispatch(AbstractFilterPipeline.java:102)
        at com.google.inject.servlet.NexusGuiceFilter$MultiFilterChain.doFilter(NexusGuiceFilter.java:82)
        at com.google.inject.servlet.NexusGuiceFilter$MultiFilterPipeline.dispatch(NexusGuiceFilter.java:56)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:620)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:219)
        at org.eclipse.jetty.server.Dispatcher.error(Dispatcher.java:83)
        at org.eclipse.jetty.server.handler.ErrorHandler.doError(ErrorHandler.java:118)
        at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:94)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$3(HttpChannel.java:423)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:421)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:748)
```

Still trying to collect more information, am just curious is this maybe something you saw or know about.

The thing is that I have no clue WHY is errorPageServlet dispatched at all (nothing in log, still looking), but it is ErrorPageServlet that tries to render the page, but flush fails, and finally ErrorPageFilter (that wraps everything) logs this.

Note: it IS possible, that response got to the point where we started Servlet 3.1 async IO to send back the response content with `WriteListener`, and then THERE got something wrong (but listener had no invocation for onError as we would log it), and then Jetty redispatches to ErrorPage, that fails to flush the error page..... (this is just speculation, am still investigating).

**Comment by joakime** [comment]
The `com.walmart.warm.webapp.qos.QosFilter.doFilter` probably forced that request into Async mode to delay it's processing based on whatever logic it is doing.
That's where the ASYNC likely came from.

**Comment by cstamas** [comment]
Negative, is disabled (and QosFilter.java:211 is actually the "else" branch of it, it just passed on.

![image](https://user-images.githubusercontent.com/45165/86365632-0c807a80-bc7a-11ea-934c-3e500e71f778.png)

**Comment by joakime** [comment]
If the api says ASYNC, something set it.  check your other Filters? (and wrappers of the HttpServletRequest/HttpServletResponse, and any overridden Servlet Streams)

**Comment by cstamas** [comment]
Agreed, but then am leaning toward my "speculation": we processed the request, got the content, and started async IO to deliver it to client, BUT, something happened -- and as I said, WriteListener got no notification about it (onError was not invoked). 

I currently have no other place to pintpoint where we would start async... (but am still looking)

**Comment by cstamas** [comment]
I think we got a lead: there was a corruption in out storage, so briefly what happens:
- we get content metadata, set up headers for content delivery response (say `Content-Length: 100`)
- we start Async IO to deliver content
- but alas, the actual content is not 100 bytes but 80
- and here it (I believe) Jetty triggers `500 - insufficient content written`
- our error page assumes we are SYNC and not ASYNC, so this error issue is about is actually just the symptom of the original error
