### ISSUE TITLE
HTTP2Session ClosedChannelException on http1 request

### ISSUE THREAD

**Issue by mattnelson** [eclipse/jetty.project#5052]
**Jetty version**
9.4.30.v20200611
Enabled http/2 support via these instructions > https://webtide.com/jetty-alpn-java-8u252/

**Java version**

```
java.vm.vendor AdoptOpenJDK
java.vm.version 11.0.7+10

and

java.vm.specification.version 1.8
java.vm.vendor AdoptOpenJDK
java.vm.version 25.252-b09 
```

**OS type/version**

container deployment with these two images:
`adoptopenjdk/openjdk8:jdk8u252-b09-alpine-slim`
`adoptopenjdk/openjdk11:jdk-11.0.7_10-alpine-slim`

**Description**

Warn message is being logged infrequently about a closed channel exception. This started happening after deploying with http2 enabled. It happens maybe every 5-20 minutes, haven't tracked down if there is a specific frequency yet.

```
2020-07-15T18:32:50,140Z WARN  [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] java.nio.channels.ClosedChannelException
```

The exception toString is being logged at warn level. Turned on debug to get the stack trace.
https://github.com/eclipse/jetty.project/blob/271836e4c1f4612f12b7bb13ef5a92a927634b0d/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java#L738-L741

The logs show http2 session operations being performed on a http1 request. This does not appear to impact functionality as the request was able to be served without error (200). This is just noise in the logs at warn level that I'm not sure what to do with and doesn't appear to be need intervention. Could this warn log event be skipped if there is no action required?

```
2020-07-15T18:32:50,140Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] asyncError HttpChannelState@398bc373{s=HANDLING rs=BLOCKING os=ABORTED is=IDLE awp=false se=false i=true al=1}
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.http2.HTTP2Session.onShutdown(HTTP2Session.java:927)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:283)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:170)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:125)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:348)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:830)
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:221)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onSessionFailure(HTTP2ServerConnection.java:261)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:128)
		at org.eclipse.jetty.http2.HTTP2Session.notifyFailure(HTTP2Session.java:1157)
		at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:1061)
		... 23 common frames omitted
2020-07-15T18:32:50,140Z WARN  [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] java.nio.channels.ClosedChannelException
2020-07-15T18:32:50,140Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] 
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.http2.HTTP2Session.onShutdown(HTTP2Session.java:927)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:283)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:170)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:125)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:348)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:830)
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:221)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onSessionFailure(HTTP2ServerConnection.java:261)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:128)
		at org.eclipse.jetty.http2.HTTP2Session.notifyFailure(HTTP2Session.java:1157)
		at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:1061)
		... 23 common frames omitted
2020-07-15T18:33:00,235Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] handling HttpChannelState@1a66d50a{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0}
2020-07-15T18:33:00,244Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:my-unique-request-id] onEof HttpChannelState@1a66d50a{s=HANDLING rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=1}
2020-07-15T18:33:00,270Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] unhandle HttpChannelState@1a66d50a{s=HANDLING rs=BLOCKING os=COMPLETED is=READY awp=false se=false i=true al=1}
2020-07-15T18:33:00,270Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] nextAction(false) COMPLETE HttpChannelState@1a66d50a{s=HANDLING rs=COMPLETING os=COMPLETED is=READY awp=false se=false i=false al=1}
2020-07-15T18:33:00,270Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] completed HttpChannelState@1a66d50a{s=HANDLING rs=COMPLETING os=COMPLETED is=READY awp=false se=false i=false al=1}
2020-07-15T18:33:00,270Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] unhandle HttpChannelState@1a66d50a{s=HANDLING rs=COMPLETED os=COMPLETED is=READY awp=false se=false i=false al=1}
2020-07-15T18:33:00,270Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] nextAction(false) TERMINATED HttpChannelState@1a66d50a{s=IDLE rs=COMPLETED os=COMPLETED is=READY awp=false se=false i=false al=1}
172.16.31.36 - - [2020-07-15T18:33:00,270Z] "POST /my-service/my-path HTTP/1.1" 200 568 "-" "User-Agent" "host:port" "-" 0/35 0 0 "my-unique-request-id"
2020-07-15T18:33:00,271Z DEBUG [dw-73] org.eclipse.jetty.server.HttpChannelState [cid:] recycle HttpChannelState@1a66d50a{s=IDLE rs=COMPLETED os=COMPLETED is=READY awp=false se=false i=false al=1}

```

**Comment by sbordet** [comment]
> The logs show http2 session operations being performed on a http1 request. 

I don't see that in the logs, can you post the DEBUG logs in full?

What I see from what you posted is that a request is being dispatched to the application and it is still there when the client closes the HTTP/2 connection, so the request is aborted.

I would recommend that you take a thread dump to know if your threads are blocked while processing a request.

**Comment by mattnelson** [comment]
> What I see from what you posted is that a request is being dispatched to the application and it is still there when the client closes the HTTP/2 connection, so the request is aborted.

I have confirmed this to be the case.

> Could this warn log event be skipped if there is no action required?

Gonna close this out, but I think it would still be worthwhile to change the log level if no action is required.
