### ISSUE TITLE
getPlatformMBeanServer(); is not supported in android for jetty 9.4.28

### ISSUE THREAD

**Issue by visgans** [eclipse/jetty.project#5055]
I tried to embed jetty server as a android application via IJetty but i got error like "class file for javax.management.MBeanServer not found". Is that possible to run jetty server in android?

**Comment by joakime** [comment]
What Android API version are you using?

You MUST be using Android API level 26 or better.
And you'll need the `sugar` build tooling that the various Android SDKs provide.

Don't use the `i-jetty` code, at all.
`i-jetty` is EOL. the version of Android API level it uses is EOL, and even the version of Jetty it uses is EOL.

As for `javax.management.MBeanServer` you'll likely need to exclude or alter some Jetty classes to avoid that dependency.

You might want to look at the `compact-3` build of Jetty, IIRC that one doesn't include `javax.management`.
But you'll need to build Jetty yourself for that.
https://github.com/eclipse/jetty.project/tree/jetty-9.4.30.v20200611/aggregates/jetty-all-compact3

**Comment by visgans** [comment]
Hi I trying to run on API 29 and i tried to run previously 9.4.30, 9.4.28 Stable and i got getcontainer error there

**Comment by joakime** [comment]
Please include full stacktraces.

**Comment by visgans** [comment]
Process: org.mortbay.ijetty, PID: 29925
    java.lang.NoSuchMethodError: No virtual method getContainer()Lorg/eclipse/jetty/util/component/Container; in class Lorg/eclipse/jetty/server/Server; or its super classes (declaration of 'org.eclipse.jetty.server.Server' appears in /data/app/org.mortbay.ijetty-czWWaIpjJPrTPP1QVxQELw==/base.apk)
        at org.mortbay.ijetty.deployer.AndroidContextDeployer.doStart(AndroidContextDeployer.java:170)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.mortbay.ijetty.IJettyService.startJetty(IJettyService.java:646)
        at org.mortbay.ijetty.IJettyService$JettyStarterThread.run(IJettyService.java:153)

**Comment by janbartel** [comment]
ijetty is build on a version of jetty that was EOL long ago. Please follow @joakime's suggestion in his post about doing your own embedded jetty server.
