### ISSUE TITLE
Jetty stops responding to ServerConnector on secure ports but respond on non ssl port after some time of server start

### ISSUE THREAD

**Issue by mohanrao** [eclipse/jetty.project#5074]
**Jetty version**
9.4.14

**Java version**

Oracle JDK 8 and AdoptOpenJdk 11

**OS type/version**
Linux , RHEL happening in 6 and 7 also
**Description**

Jetty randomly stops respond to ssl ports created with ServerConnector instance. We are running an embedded jetty server. 

Strang part is non ssl port respond on the same server created with NetworkTrafficServerConnector. 

Basically we create one server instance and add two connectors one create with NetworkTrafficServerConnector and another with ServerConnector with custom SSL socket factory.

Below is the error
`
2020-07-22 09:44:27,132 [Jetty Thread Pool-306] DEBUG org.eclipse.jetty.http.HttpParser.setState() 1870 : HEADER: --> IN_NAME
2020-07-22 09:44:27,132 [Jetty Thread Pool-501] DEBUG org.eclipse.jetty.io.ssl.SslConnection.flush() 950 : SslConnection@36fbef::SocketChannelEndPoint@2f9b5a{/10.254.249.151:64944<->/10.254.249.24:58443,OPEN,fill=-,flush=-,to=42/30000}{io=0/0,kio=0,kro=1}->SslConnection@36fbef{NEED_UNWRAP,eio=0/1193,di=-1,fill=IDLE,flush=IDLE}~>DecryptedEndPoint@b502dd{/10.254.249.151:64944<->/10.254.249.24:58443,OPEN,fill=-,flush=-,to=56/30000}=>HttpConnection@1b7eb8f[p=HttpParser{s=START,0 of -1},g=HttpGenerator@3a7de{s=START}]=>HttpChannelOverHttp@48218f{r=0,c=false,a=IDLE,uri=null,age=0}
org.eclipse.jetty.io.EofException
                at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:285) ~[jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:882) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:515) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:331) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:243) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.io.IOException: Connection reset by peer
                at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_172]
                at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_172]
                at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_172]
                at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_172]
                at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[?:1.8.0_172]
                at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:263) ~[jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                ... 19 more

`

**Any pointers**

**Comment by joakime** [comment]
9.4.14 is a bit old, and subject to several security reports at this point in time.
https://www.eclipse.org/jetty/security-reports.html

You should really upgrade.

The "Connection reset by peer" is when a remote endpoint has terminated the connection, a common enough scenario and is not the root of your issue.

> Basically we create one server instance and add two connectors one create with NetworkTrafficServerConnector and another with ServerConnector with custom SSL socket factory

Now that has a few red flags.

Why do you use and/or need a custom SSL socket factory??  
And are you taking into account all of the various changes that Java 8 and Java 11 have made to SSL Sockets?

**Comment by mohanrao** [comment]
Thanks @joakime for the reply

we tested the socket connection by issuing a simple openssl command too. it fails to connect. 

Sorry it's not really a custom SSL socket factory. it is a ssl socket factory instance with our own keystore and trust store i mean like below 

`
SslContextFactory sslContextFactory = new SslContextFactory();
`

We see also the below errors 


`
sun.nio.ch.EPollSelectorImpl@17e6e45 waiting with 18 keys
2020-07-22 09:44:27,145 [Jetty Thread Pool-501] DEBUG org.eclipse.jetty.io.WriteFlusher.onFail() 471 : ignored: WriteFlusher@c00afd{IDLE}->null
java.nio.channels.ClosedChannelException
                at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:502) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:216) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doShutdownOutput(SslConnection.java:1085) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doClose(SslConnection.java:1131) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:220) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:951) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:515) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:331) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:243) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
`

and 

`
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_172]
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_172]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_172]
    at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_172]
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[?:1.8.0_172]
    at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:263) ~[jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
    ... 24 more
`

**Comment by joakime** [comment]
9.4.14 is a bit old, and subject to several security reports at this point in time.
https://www.eclipse.org/jetty/security-reports.html

You should really upgrade.

The `SslContextFactory` itself has undergone many changes since 9.4.14

**Comment by mohanrao** [comment]
Thanks @joakime . We will upgrade and hoping it should fix the issues.
