### ISSUE TITLE
Can't use keyStores with multiple certificates for SSL ServerConnector

### ISSUE THREAD

**Issue by vn7n24fzkq** [eclipse/jetty.project#5076]
**Jetty version**
9.4.30.v20200611
**Java version**
java 11
**OS type/version**
Windows 10
**Description**
Here are part of my code and output message
```kotlin
    fun createServer(plainPort: Int, securePort: Int): Server {
        val server = Server()

        val httpConfig = HttpConfiguration()
        httpConfig.secureScheme = "https"
        httpConfig.securePort = securePort
        httpConfig.outputBufferSize = 32768

        val http = ServerConnector(server,
                HttpConnectionFactory(httpConfig))
        http.port = plainPort
        http.idleTimeout = 30000

        val sslContextFactory = SslContextFactory.Server()
        sslContextFactory.keyStorePath = "config/keystore.jks"
        sslContextFactory.setKeyStorePassword(ServerConfig.JKS_PASSWORD)
        sslContextFactory.setTrustStorePassword(ServerConfig.JKS_PASSWORD)
        sslContextFactory.setKeyManagerPassword(ServerConfig.JKS_PASSWORD)

        val httpsConfig = HttpConfiguration(httpConfig)
        val src = SecureRequestCustomizer()
        src.stsMaxAge = 2000
        src.isStsIncludeSubDomains = true
        httpsConfig.addCustomizer(src)

        val https = ServerConnector(server,
                SslConnectionFactory(sslContextFactory, HttpVersion.HTTP_1_1.asString()),
                HttpConnectionFactory(httpsConfig))
        https.port = securePort
        https.idleTimeout = 500000

        server.connectors = arrayOf<Connector>(http, https)
        return server
    }
```
```
Caused by: java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
        at org.eclipse.jetty.util.ssl.SslContextFactory.newSniX509ExtendedKeyManager(SslContextFactory.java:1274)
        at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1256)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:374)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:386)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at io.javalin.core.JavalinServer.start(JavalinServer.kt:63)
        at io.javalin.Javalin.start(Javalin.java:175)
        ... 3 more
```

**Comment by vn7n24fzkq** [comment]
I solve it. 
Change SslContextFactory to SslContextFactory.Server() can fix this.
But I forget recompile code.😅
