### ISSUE TITLE
Module [depend] property expansion should support eg foo/${bar}/${bar}-xxx

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#510]
If a [depend] clause like the following is used in a .mod file:

[depend]
foo/${bar}/${bar}-xxx

Then the following exception is thrown:

org.eclipse.jetty.start.PropsException: Property expansion loop detected: session-type -> session-type
	at org.eclipse.jetty.start.Props.expand(Props.java:227)
	at org.eclipse.jetty.start.Props.expand(Props.java:189)
	at org.eclipse.jetty.start.Module.lambda$expandProperties$3(Module.java:151)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.jetty.start.Module.expandProperties(Module.java:152)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:226)
	at org.eclipse.jetty.start.Modules.select(Modules.java:215)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:120)
	at org.eclipse.jetty.start.Main.start(Main.java:407)
	at org.eclipse.jetty.start.Main.main(Main.java:73)

Seems like this should be supported.

**Comment by joakime** [comment]
Fixed this in jetty-9.2.x and merged up to jetty-9.3.x and master
