### ISSUE TITLE
JNDI With Embedded Jetty Example Doesn't work. 

### ISSUE THREAD

**Issue by mitchdennett** [eclipse/jetty.project#5138]
**Jetty version**
9.4.31.v20200723

**Java version**
14 OpenJDK

**OS type/version**
MacOS

**Description**
I'm trying to follow this example. https://www.eclipse.org/jetty/documentation/current/jndi-embedded.html

But I cannot get it to work. 

```
    public static void main(String[] args) throws Exception
    {

        //Create the server
        Server server = new Server(8080);

        //Enable parsing of jndi-related parts of web.xml and jetty-env.xml
        org.eclipse.jetty.webapp.Configuration.ClassList classlist = org.eclipse.jetty.webapp.Configuration.ClassList.setServerDefault(server);
        classlist.addAfter("org.eclipse.jetty.webapp.FragmentConfiguration", "org.eclipse.jetty.plus.webapp.EnvConfiguration", "org.eclipse.jetty.plus.webapp.PlusConfiguration");

        //Create a WebApp
        WebAppContext webapp = new WebAppContext();
        webapp.setContextPath("/");
        webapp.setWar("./my-foo-webapp.war");
        server.setHandler(webapp);

        //Define an env entry with Server scope.
        //At runtime, the webapp accesses this as java:comp/env/woggle
        //This is equivalent to putting an env-entry in web.xml:
        //<env-entry>
        //  <env-entry-name>woggle</env-entry-name>
        //  <env-entry-type>java.lang.Integer</env-entry-type>
        //  <env-entry-value>4000</env-entry-value>
        //</env-entry>
        org.eclipse.jetty.plus.jndi.EnvEntry woggle = new org.eclipse.jetty.plus.jndi.EnvEntry(server, "woggle", new Integer(4000), false);


        //Define an env entry with webapp scope.
        //At runtime, the webapp accesses this as java:comp/env/wiggle
        //This is equivalent to putting a web.xml entry in web.xml:
        //<env-entry>
        //  <env-entry-name>wiggle</env-entry-name>
        //  <env-entry-value>100</env-entry-value>
        //  <env-entry-type>java.lang.Double</env-entry-type>
        //</env-entry>
        //Note that the last arg of "true" means that this definition for "wiggle" would override an entry of the
        //same name in web.xml
        org.eclipse.jetty.plus.jndi.EnvEntry wiggle = new org.eclipse.jetty.plus.jndi.EnvEntry(webapp, "wiggle", new Double(100), true);

        //Register a reference to a mail service scoped to the webapp.
        //This must be linked to the webapp by an entry in web.xml:
        // <resource-ref>
        //  <res-ref-name>mail/Session</res-ref-name>
        //  <res-type>javax.mail.Session</res-type>
        //  <res-auth>Container</res-auth>
        // </resource-ref>
        //At runtime the webapp accesses this as java:comp/env/mail/Session
        org.eclipse.jetty.jndi.factories.MailSessionReference mailref = new org.eclipse.jetty.jndi.factories.MailSessionReference();
        mailref.setUser("CHANGE-ME");
        mailref.setPassword("CHANGE-ME");
        Properties props = new Properties();
        props.put("mail.smtp.auth", "false");
        props.put("mail.smtp.host","CHANGE-ME");
        props.put("mail.from","CHANGE-ME");
        props.put("mail.debug", "false");
        mailref.setProperties(props);
        org.eclipse.jetty.plus.jndi.Resource xxxmail = new org.eclipse.jetty.plus.jndi.Resource(webapp, "mail/Session", mailref);


        // Register a  mock DataSource scoped to the webapp
        //This must be linked to the webapp via an entry in web.xml:
        //<resource-ref>
        //  <res-ref-name>jdbc/mydatasource</res-ref-name>
        //  <res-type>javax.sql.DataSource</res-type>
        //  <res-auth>Container</res-auth>
        //</resource-ref>
        //At runtime the webapp accesses this as java:comp/env/jdbc/mydatasource
        org.eclipse.jetty.plus.jndi.Resource mydatasource = new org.eclipse.jetty.plus.jndi.Resource(webapp, "jdbc/mydatasource",
                                                                                                     new com.acme.MockDataSource());

        server.start();
        server.join();
    }

```

First thing is it complains about not being able to find `org.eclipse.jetty.jndi.factories.MailSessionReference` 
I have the following dependencies in my pom.xml
```
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>9.4.31.v20200723</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>9.4.31.v20200723</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-jndi</artifactId>
            <version>9.4.31.v20200723</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-plus</artifactId>
            <version>9.4.31.v20200723</version>
        </dependency>
```

When I remove that mail code and can get everything to compile I get the following error.

```
Exception in thread "main" javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:685)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342)
	at java.naming/javax.naming.InitialContext.getNameParser(InitialContext.java:497)
	at org.eclipse.jetty.plus.jndi.NamingEntry.save(NamingEntry.java:191)
	at org.eclipse.jetty.plus.jndi.EnvEntry.<init>(EnvEntry.java:34)
	at com.mitchdennett.main.Main.main(Main.java:47)
```

**Comment by joakime** [comment]
The example is from ....

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ServerWithJNDI.java

Which is actually tested with each build ...

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/examples/embedded/src/test/java/org/eclipse/jetty/embedded/ServerWithJNDITest.java

So we know it works.

So, lets narrow down what's going on in your specific example.

You've changed your WAR file, so we'll need to know what that WAR file is doing, what it's `WEB-INF/web.xml` looks like, if it has any `WEB-INF/jetty-env.xml` files, etc ...

Also, in your code, line 47 is what? (trying to line up the stacktrace to your code)

Could you perhaps make this test project a new personal github repository that you can share with us?

Finally, some details about your environment might reveal something about your issue as well. (OS, JVM in use, etc...)  Judging from the stacktrace it seems you are using at least Java 9.

**Comment by mitchdennett** [comment]
Let me create a git repo real quick

**Comment by mitchdennett** [comment]
Hmm so its working now. My apologies for opening this issue. When I created my new Maven project to reproduce this it worked there after pulling down the maven dependancies. Now my original one works too. Something was screwed up with my maven repo.

**Comment by joakime** [comment]
No worries.  Good luck.
