### ISSUE TITLE
Jetty not throwing EOF exception on browser tab close

### ISSUE THREAD

**Issue by hypervisorfdi** [eclipse/jetty.project#5149]
**9.4.25.v20191220**

**JavaSE-1.8 / jdk1.8.0_231**

What are the criteria for EOF exception to be thrown?
My code is doing response.getOutputStream().write(byte)

but when the user is closing the browser tab, Im not getting any exceptions, currently the code is proxying, so on Exception, I would like to stop the requests to backend.

UPDATE:
exception is seen, I wonder why the exception is not propagating and my thread is hanging, wonder if I need a callback configured to get notified on such exception, since its been swallowed by Jetty.

**Comment by joakime** [comment]
On HTTP/1.1, you are subject to normal TCP/IP behaviors.

Exceptions will be thrown by Java once the OS + network and all of the network buffers notice, or idle timeout kicks in.

If the client is totally gone, but the client didn't close the TCP/IP connection (common in a browser tab closure scenario), then
you would have to write enough to trigger network backpressure (halting further activity on the connection), at which point you are subject to the network idle timeout behaviors, the last blocked write will fail with IdleException/TimeoutException.

If the client did close the TCP/IP connection, the writes will still succeed up until there is an attempt to write to the network. (such as with the various aggregation buffers present).
Then it will fail the next write with a EarlyEofException, EOFException, etc..

If you are using HTTP/2, then the behavior is generally better, as the the client sessions have the ability to notify the server that it's "going away", even in mid-stream.
These "going away" events immediately trigger a failure on the connection, the status of the various buffers in Jetty, in Java, on the Network have no influence on the immediacy of the failure.
But, this HTTP/2 scenario relies on the browser using HTTP/2 to send that "going away" message.  (which not all browsers do)

Now, back to proxying.
In a proxy, you should not be using response.getOutputStream().write(...) anything, that's old school blocking code and is subject to many many many scenarios like you have just hit.

You should be using the Async I/O features of the servlet API (and the Async I/O features of your choice of Http Client in your proxy) to manage the connections in a threadless way, allowing normal TCP/IP cleanup to operate without a blocked thread waiting for it.

Have you considered using Jetty's AsyncProxy for this purpose?
If you need to modify content during the proxy activities, then consider using AsyncMiddleManServlet instead.

**Comment by hypervisorfdi** [comment]
- Exceptions will be thrown by Java once the OS + network and all of the network buffers notice, or idle timeout kicks in.
yes I can see the exception, but its not propagating up to my code.

- If the client did close the TCP/IP connection, the writes will still succeed up until there is an attempt to write to the network.
yes, the client is closing the connection, and a flush is being called, thus there is an actual exception.

-Have you considered using Jetty's AsyncProxy for this purpose?
no, not yet, will google regarding AsyncMiddleManServlet , thanks for the suggestion.

here is the stack trace that never propagate to my code:

```javascript
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:283) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) [jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) [jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:815) [jetty-server-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) [jetty-util-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:546) [jetty-server-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:829) [jetty-server-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:901) [jetty-server-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:283) [jetty-server-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:267) [jetty-server-9.4.25.v20191220.jar:9.4.25.v20191220]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:828) [jetty-server-9.4.25.v20191220.jar:9.4.25.v20191220]
	at com.v2.proxy.code.ProxyCall.writeResponse(ProxyCall.java:140) [classes/:?]
	at com.v2.proxy.code.GenericServiceCommand.run(GenericServiceCommand.java:47) [classes/:?]
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302) [hystrix-core-1.5.18.jar:1.5.18]
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298) [hystrix-core-1.5.18.jar:1.5.18]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) [rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) [rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) [rxjava-1.2.0.jar:1.2.0]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) [hystrix-core-1.5.18.jar:1.5.18]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) [hystrix-core-1.5.18.jar:1.5.18]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) [hystrix-core-1.5.18.jar:1.5.18]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) [rxjava-1.2.0.jar:1.2.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_241]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:55) ~[?:1.8.0_241]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_241]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:1.8.0_241]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:263) ~[jetty-io-9.4.25.v20191220.jar:9.4.25.v20191220]
	... 46 more
```

**Comment by sbordet** [comment]
The code at `HttpOutput.java:828` and related show that the exception is rethrown to user code, as it should.
This hits `com.v2.proxy.code.ProxyCall.writeResponse()` and if that is your code, you should see the exception.

Note also that "closing a tab in a browser" does not mean that the connection is closed.
Browsers keep a connection pool, and the connection may be used for something else.

**Comment by hypervisorfdi** [comment]
no, it shows a stack trace that was printed by Jetty and the exception was swallowed up, my code is freezing/blocked at response.getOutputStream().write(...)

No, the browser connection is closed, see the exception is from flushing operation that goes bad.
java.io.IOException: An established connection was aborted by the software in your host machine

so wont blame browsers here.

**Comment by hypervisorfdi** [comment]
thanks

**Comment by sbordet** [comment]
@hypervisorfdi you closed this issue because it was solved for you? Can you detail how?

**Comment by MoralCode** [comment]
I am seeing similar behavior to that reported.
Known affected version: 9.4.22 and below (also tested 9.4.18, 9.4.12, and 9.4.6)
Known unaffected version: 9.4.28 + (also tested: 9.4.30, 9.4.32)

This issue happens in a grails app (running via jetty using an exported WAR file instead of the default tomcat server) when rapidly double-tapping F5 in browser (tested on MS edge which is basically chrome) to cause two rapid refreshes.

When this happens, the stack trace has the same `Caused by: java.io.IOException: An established connection was aborted by the software in your host machine` at the lowest level, yet nowhere in the stack trace references any code that's specific to the (in my case grails) application.

Im having a hard time narrowing this down to a specific code change in jetty that made this no longer an issue

#544 seems to describe the issue nearly perfectly but didnt seem to result in any code changes

**Comment by joakime** [comment]
Chromium works with it's own connection pool, and response caches, rapidly refreshing with F5 might not do anything with any physical connection as well.

If I do the same thing with Chrome 102, and I have wireshark open watching the network traffic, I see no network traffic to the web server.
