### ISSUE TITLE
Jetty 9.4.31 WebSocketClient.stop() hang on stop

### ISSUE THREAD

**Issue by zhugf** [eclipse/jetty.project#5155]
**Jetty version**
9.4.29.20200521
9.4.31.20200723

**Java version**
jdk 11/jdk 14

**OS type/version**
Ubuntu 20.04.1 LTS
Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description**
Jetty websocket client hang while stopping. From the stacktrace, it seems that the selector thread is not wakeup by stop thread, then the stop thread waits for signal forever.

ManageSelector.select() thread:
"qtp1602167682-197" #197 prio=5 os_prio=0 cpu=1.76ms elapsed=29362.39s tid=0x00007f47ddf98800 nid=0x1f42f runnable  [0x00007f474aa03000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@14.0.2/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@14.0.2/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@14.0.2/SelectorImpl.java:129)
	- locked <0x00000004198adf50> (a sun.nio.ch.Util$2)
	- locked <0x00000004198adef0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@14.0.2/SelectorImpl.java:146)
	at org.eclipse.jetty.io.ManagedSelector.nioSelect(ManagedSelector.java:149)
	at org.eclipse.jetty.io.ManagedSelector.select(ManagedSelector.java:156)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:572)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:509)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$748/0x00000008013ed840.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

The stop thread:

"HttpClient@72f954cc-416" #416 prio=5 os_prio=0 cpu=36.31ms elapsed=29057.87s tid=0x00007f46b0045800 nid=0x1f5b5 waiting on condition  [0x00007f46dabf4000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@14.0.2/Native Method)
	- parking to wait for  <0x0000000420514b38> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@14.0.2/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@14.0.2/AbstractQueuedSynchronizer.java:714)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@14.0.2/AbstractQueuedSynchronizer.java:1046)
	at java.util.concurrent.CountDownLatch.await(java.base@14.0.2/CountDownLatch.java:232)
	at org.eclipse.jetty.io.ManagedSelector.doStop(ManagedSelector.java:136)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	- locked <0x0000000420514bf0> (a java.lang.Object)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.io.SelectorManager.doStop(SelectorManager.java:281)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	- locked <0x0000000420514cd0> (a java.lang.Object)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.doStop(AbstractConnectorHttpClientTransport.java:70)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	- locked <0x0000000420514d98> (a java.lang.Object)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:280)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	- locked <0x0000000420514f08> (a java.lang.Object)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.websocket.client.WebSocketClient.doStop(WebSocketClient.java:413)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	- locked <0x0000000420514fe0> (a java.lang.Object)
	at org.springframework.web.socket.client.jetty.JettyWebSocketClient.stop(JettyWebSocketClient.java:118)
	at org.springframework.web.socket.client.WebSocketConnectionManager.stopInternal(WebSocketConnectionManager.java:128)
	at org.springframework.web.socket.client.ConnectionManagerSupport.stop(ConnectionManagerSupport.java:132)
	- locked <0x000000041ff96400> (a java.lang.Object)
	at trader.service.node.NodeClientChannelImpl.clearWsSession(NodeClientChannelImpl.java:396)
	at trader.service.node.NodeClientChannelImpl.closeWsSession(NodeClientChannelImpl.java:389)
	at trader.service.node.NodeClientChannelImpl.handleTransportError(NodeClientChannelImpl.java:205)
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleTransportError(WebSocketHandlerDecorator.java:80)
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleTransportError(LoggingWebSocketHandlerDecorator.java:64)
	at org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketError(JettyWebSocketHandlerAdapter.java:131)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@14.0.2/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@14.0.2/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@14.0.2/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@14.0.2/Method.java:564)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onError(JettyAnnotatedEventDriver.java:164)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.handleException(WebSocketUpgradeRequest.java:540)
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:519)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:269)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:240)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:149)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:812)
	at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:501)
	at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:253)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.failed(AbstractConnectionPool.java:194)
	at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:136)
	at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:627)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.connectFailed(AbstractConnectorHttpClientTransport.java:138)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.connectionFailed(AbstractConnectorHttpClientTransport.java:188)
	at org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:924)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:335)
	at org.eclipse.jetty.io.ManagedSelector.access$1600(ManagedSelector.java:62)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:639)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:501)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$748/0x00000008013ed840.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

**Comment by zhugf** [comment]
Just found the root cause: the code try to destroy websocket client from handleTransportError() thread.

Destroy the websocket client from a new thread, it works!

**Comment by joakime** [comment]
Yeah, that makes sense.

The WebSocketClient.stop() is supposed to attempt a graceful shutdown of all open sessions and then finally stop.
If you are attempting to stop WebSocketClient from a thread that is part of the graceful shutdown, then you are essentially in a deadlock.
