### ISSUE TITLE
Strange "java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms" when using Continuations

### ISSUE THREAD

**Issue by laeubi** [eclipse/jetty.project#517]
We see this exception in the Log:

```
WARN  (HttpChannel.java:468) (and one from ServletHandler.java:631):
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
    at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:226) ~[org.eclipse.jetty.util_9.3.8.v20160314.jar:9.3.8.v20160314]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:164) ~[org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:415) ~[org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1026) ~[org.apache.commons.io_1.4.0.v20081110-1000.jar:na]
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:999) ~[org.apache.commons.io_1.4.0.v20081110-1000.jar:na]

...

Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
    at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166) ~[org.eclipse.jetty.io_9.3.8.v20160314.jar:9.3.8.v20160314]
    at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50) ~[org.eclipse.jetty.io_9.3.8.v20160314.jar:9.3.8.v20160314]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_73]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_73]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_73]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_73]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_73]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_73]
    ... 1 common frames omitted
```

The strange thing is the following:
1. The client receives the response without any problem in under a second
2. It does not happen on every request but seems to need n-request to happen
3. The exception occurs very much earlier than espected, if you log requests you see the request and the exception occur within a few milli-seconds.

This happens at the Upgrade from Jetty8->Jetty9, the code has worked before without any problem, the continuation itself is also not timing out.

**Comment by laeubi** [comment]
Is it possible that the Continuation Object (or any other object related to this) is recycled but the timeouthandling is not reset for an reason?

**Comment by gregw** [comment]
Not sure how continuations and the write are related?      Can you produce logging to show that this write itself did not take 30s?     If you run with full jetty debugging, you should be able to trace the actions of the thread that calls this blocking write and see how long the write actually takes.

**Comment by laeubi** [comment]
I'll try this, any specific logger for what I should enable debug level? From the client-perspective I can tell that the full request-cycle (from starting the request to reading the data and writing it to disk) it finish under a second.

**Comment by gregw** [comment]
On 17 April 2016 at 04:14, laeubi <notifications@github.com> wrote:

> I'll try this, any specific logger for what I should enable debug level?
> From the client-perspective I can tell that the full request-cycle (from
> starting the request to reading the data and writing it to disk) it finish
> under a second.
>
I would just try to reproduce with fill debugging turned on.  If that
doesn't work, then turn it on for io, http, server packages at least.

Also you need to use a better log reporter.  The standard jetty log will
log the thread that generated the log, the ms it occurred and if an
exception is listed, the stack trace of any cause or suppressed exception
is also logged.    The stack trace in your original report is only partial
and lacks a lot of information.

regards




-- 
Greg Wilkins <gregw@webtide.com> CTO http://webtide.com

**Comment by laeubi** [comment]
I'm currently facing an issue with "to-many-open-files" and have seen the exception again but now with a very very large timeout value:

```
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 215984795/30000 ms

       at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:226)

       at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:164)

       at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:436)

       at java.io.OutputStream.write(OutputStream.java:75)

       at de.JSONProvider.writeData(OfflineJSONProvider.java:91)

       at de.BackgroundTask$1.run(BackgroundTask.java:97)

       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

       at java.util.concurrent.FutureTask.run(FutureTask.java:266)

       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

       at java.lang.Thread.run(Thread.java:745)

 Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 215984795/30000 ms

       at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)

       at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)

       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

       at java.util.concurrent.FutureTask.run(FutureTask.java:266)

       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

       ... 3 common frames omitted
```

The Thread where this happens is the background-worker thread and I have used the Async API now.

**Comment by sbordet** [comment]
Not sure what you mean by "I have used the Async API now", but the stack trace shows that you were into a blocking write, and the client did not read, until you eventually timed out.

The large timeout value could be due to the fact that the request has been suspended for a long time before starting to write.

**Comment by laeubi** [comment]
Thanks for the feedback, I first have used Continuations (as mentioned in the headline) but now switched over to Async API (as recommended by gregw).
I must check what the exact timeout value is but it is far lesser than 60 hours as it seems from the exception trace. I'm not even sure if the server has really run such a long time...

**Comment by sbordet** [comment]
Well, if you can make your case reproducible, we will take a look. 

By the descriptions so far, this issue is explainable with a client that does not read and a congested connection. 

If you have more information like a full DEBUG log, then attach it here and we'll have a look.

**Comment by laeubi** [comment]
I think this is a sideeffect of timeouts all executed in one thread see https://github.com/eclipse/jetty.project/issues/1037 when timeout events stack-up I'll try to create a test-case for this.

**Comment by laeubi** [comment]
It seems to be related to persistent http connections: If the client caches a connection and reuses it some time later I see 

```
[Scheduler-96639997] DEBUG org.eclipse.jetty.io.IdleTimeout - SelectChannelEndPoint@6eca1c45{/127.0.0.1:55501<->9090,Open,in,out,FI,-,27902/30000,HttpConnection}{io=1/1,kio=1,kro=1} idle timeout check, elapsed: 27902 ms, remaining: 2098 ms
[Scheduler-96639997] DEBUG org.eclipse.jetty.io.IdleTimeout - SelectChannelEndPoint@6eca1c45{/127.0.0.1:55501<->9090,Open,in,out,FI,-,30001/30000,HttpConnection}{io=1/1,kio=1,kro=1} idle timeout check, elapsed: 30001 ms, remaining: -1 ms
[Scheduler-96639997] DEBUG org.eclipse.jetty.io.IdleTimeout - SelectChannelEndPoint@6eca1c45{/127.0.0.1:55501<->9090,Open,in,out,FI,-,30001/30000,HttpConnection}{io=1/1,kio=1,kro=1} idle timeout expired
```

and the connection gets closed without any exception. But in this case it seems the call does not reach my servlet-code at all so it seems a different case.

In the "real-world" the client-(java)-application uses a mix of different calls that either use long-polling or async-data generation. So maybe it is a combination of cached-connections (java seems to use 5 by default) and long-polling but I can't reliable reproduce this :(

**Comment by laeubi** [comment]
I have seen while debugging that the SharedBlockingCallback created in HttpOutput always returns -1 for the IdleTimeout. This value is aquired from the HttpConfig. The code seems to only if this configured timeout is == 0 (no timeout?) using the idle timeout of the channel wich fetches the timeout from the Endpoint that has an idletimeout if 30000 in what I have debugged.

This sounds a little bit strange I why it uses a different IdleTimeout here? As -1 as an value also leads to block() beening waiting for the complete "forever".

Is it possible that the succeed call is blocked for some reason and can't enter the lock, then the Timout occurs, and failed(..) is called, both waiting on the lock. Now the lock is freed and since there is no guarantee for order the timout can first complete? Because as mentioned before all request seem to finish Ok for the *Client* but on the server side I see alot of EOF errors and some of the IdleTimeout-Errors.

**Comment by laeubi** [comment]
I'll close this issue since I can't find any evidence that something is wrong in jetty but finally was able to debug a problem in the application code: Under some circumstances the client opens an URLConnection to the server but never reading any of the Streams (and not closing them) thus the HTTP-Connection was terminated at arbitrary times (GarbageCollection happens?). Depending on the time this happens jetty encounters an EOFException (what was suppressed on the server side) so this fails was unnoticed most of the time, or in some rare cases it runs into the IdleTimeout.
It seems that Jetty8 has handled this different so we have not seen this before.
