### ISSUE TITLE
Getting SSLHandshakeException: Received fatal alert: certificate_unknown error

### ISSUE THREAD

**Issue by shwetaCummins** [eclipse/jetty.project#5197]
**Jetty version**
9.4.18.v20190429
**Java version**
1.8.0_261
**OS type/version**

**Description**
I am using Spark web server in one of our IOT device. I have Self Signed certificate. When I try to open the UI on any browser like chrome, I get below errors.
```
javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at org.openjsse.sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at org.openjsse.sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at org.openjsse.sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
	at org.openjsse.sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
	at org.openjsse.sun.security.ssl.TransportContext.dispatch(TransportContext.java:180)
	at org.openjsse.sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at org.openjsse.sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:673)
	at org.openjsse.sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:628)
	at org.openjsse.sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:443)
	at org.openjsse.sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:422)
	at org.openjsse.sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:55)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:578)
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:340)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```
Thank you in advance,

Regards,
Shweta

**Comment by sbordet** [comment]
Browsers don't typically send certificates to servers, so your report is unlikely.
If you do send certificates from the browser, you have to detail _exactly_ what is your setup, what is the server configuration, etc.
This seems to be just a TLS configuration issue, not a Jetty issue.

**Comment by shwetaCummins** [comment]
My server implemented at device is sending the certificate while handshaking with browser as a client. I am getting errors on device side.
Here is my configuration for device at server side
         secure(keyStore, keyStorePwd, null, null);
        SslContextFactory sslContextFactory = new SslContextFactory();
        sslContextFactory.setIncludeProtocols("TLSv1.2");

**Comment by sbordet** [comment]
Sorry but the information you give is not enough. If you are getting error on the server-side, and the error is that the certificate is unknown, then the server is complaining about certificates, which is unlikely.

`secure(...)` is not a Jetty method, so no idea what it does.

Please double and triple check on your side that you are doing things correctly - it's most likely an issue on your side than a Jetty issue.

**Comment by shwetaCummins** [comment]
secure( .. ) is method of spark web server. I know I am missing something at server side. Can you guide me to identify this.
In spite of having the certificate_unknown exception, I am able to access the UI. Also I observed that I am not getting such exception when I use Firefox as a browser. 
I am not sure where I am missing anything while configuring the embedded jetty server

**Comment by shwetaCummins** [comment]
Hello

I run the same example give at https://github.com/tipsy/spark-ssl on my system. still I get the same error of Certificate Unknown issue.

Please guide.

**Comment by sbordet** [comment]
@shwetaCummins the issue you are having is not a Jetty issue.

I have just tried the example you linked, and it works perfectly fine for me.

**Comment by shwetaCummins** [comment]
Yes it does not look like a jetty issue. But something wrong with spark web server. Do you have any idea about it. I used the same code in my existing environment. As long as example code is  concern, I think we have to add the spark-web server dependency in pom file. I don't see anything else. n spite of having the same setting in my pom I am getting same error.
Can you guide me is there anything that crashes the spark. Also can you share which browser you have used for testing. Because I am getting exception on Google Chrome Microsoft Edge browsers only. Not for firefox.

**Comment by joakime** [comment]
@shwetaCummins check the date/time on the IoT system running Jetty/Spark.  It could be as simple as a bad date that is invalidating the certificates before you get a chance to use them. (they have a start/end date, and if your system is outside of that range, the certificate is automatically invalid)

**Comment by shwetaCummins** [comment]
I am using self signed certificate with end date expires in next year.

**Comment by sbordet** [comment]
@shwetaCummins are you sure you are not getting "Certificate Unknown" because you're using a self-signed certificate?

**Comment by shwetaCummins** [comment]
I am getting "SSLHandshakeException: Received fatal alert: certificate_unknown" this exception. continuously on Chrome. But for Firefox browser only first time I get after that it does not throw any exception on Firefox.

**Comment by sbordet** [comment]
Chrome the browser does not show you `SSLHandshakeException`, but a friendly page with a security warning where you can click on UI elements to bypass the security warning and proceed.

Unless you explain exactly what you're doing we cannot help you.

**Comment by joakime** [comment]
For Chrome ...

* _Do not use "localhost" or "127.0.0.1"_ in your URL, but the actual hostname to the server you are connecting to. (https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate)
* Do not send `Connection: close` from the  server, you'll just trigger a new TLS request each time causing the error with every new connection. (https://bugs.chromium.org/p/chromium/issues/detail?id=952778)

**Comment by shwetaCummins** [comment]
Apologized I was off this topic due to some other work. I think is my certificate causes this issue? I am using keytool -genkey -keyalg RSA -alias selfsigned -keysize 2048 -storepass 12345asdfgh -validity 3650 -keystore keystore.jks  this command to generate my self signed certificate
