### ISSUE TITLE
Do not hide file Resource exceptions

### ISSUE THREAD

**Issue by peterlynch** [eclipse/jetty.project#522]
If Jetty is booted and the https connector has a file path to a keystore file where the loading of that resource throws an exception, the exception is logged at DEBUG only and an unrelated exception of wrong cause is thrown instead.

Here, exception e2 is not re-thrown.

http://download.eclipse.org/jetty/9.3.8.v20160314/xref/org/eclipse/jetty/util/resource/Resource.html#185

### Expected

Critical exceptions like this should be propagated with the thrown exception, so that the root cause of the resource loading issue is not masked at default log levels.

This example taken from Nexus Repository Manager 3 codebase where Jetty 9.3.7.v20160115 is being used:

```
2016-04-21 14:07:29,719-0700 WARN  [FelixStartLevel] *SYSTEM org.eclipse.jetty.xml.XmlConfiguration - Config error at <Set name="KeyStorePath"><Property name="karaf.etc"/>/ssl/server-keystore.jks</Set>
2016-04-21 14:07:29,726-0700 WARN  [FelixStartLevel] *SYSTEM org.eclipse.jetty.xml.XmlConfiguration - Config error at <New id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory"><Set name="KeyStorePath"><Property name="karaf.etc"/>/ssl/server-keystore.jks</Set><Set name="KeyStorePassword">changeit</Set><Set name="KeyManagerPassword">changeit</Set><Set name="TrustStorePath"><Property name="karaf.etc"/>/ssl/keystore.jks</Set><Set name="TrustStorePassword">OBF:1v2j1uum1xtv1zej1zer1xtn1uvk1v1v</Set><Set name="EndpointIdentificationAlgorithm"/><Set name="NeedClientAuth"><Property name="jetty.ssl.needClientAuth" default="false"/></Set><Set name="WantClientAuth"><Property name="jetty.ssl.wantClientAuth" default="false"/></Set><Set name="ExcludeCipherSuites">
      <Array type="String"><Item>SSL_RSA_WITH_DES_CBC_SHA</Item><Item>SSL_DHE_RSA_WITH_DES_CBC_SHA</Item><Item>SSL_DHE_DSS_WITH_DES_CBC_SHA</Item><Item>SSL_RSA_EXPORT_WITH_RC4_40_MD5</Item><Item>SSL_RSA_EXPORT_WITH_DES40_CBC_SHA</Item><Item>SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA</Item><Item>SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA</Item></Array>
    </Set></New>
2016-04-21 14:07:29,757-0700 ERROR [FelixStartLevel] *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Start failed
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) [na:1.8.0_77]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:488) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:411) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:799) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:423) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:358) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:259) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.sonatype.nexus.bootstrap.jetty.JettyServer.doStart(JettyServer.java:168) [org.sonatype.nexus.bootstrap:3.0.0.03]
	at org.sonatype.nexus.bootstrap.jetty.JettyServer.lambda$0(JettyServer.java:117) [org.sonatype.nexus.bootstrap:3.0.0.03]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_77]
	at org.sonatype.nexus.bootstrap.jetty.JettyServer.start(JettyServer.java:115) [org.sonatype.nexus.bootstrap:3.0.0.03]
	at org.sonatype.nexus.bootstrap.Launcher.start(Launcher.java:129) [org.sonatype.nexus.bootstrap:3.0.0.03]
	at org.sonatype.nexus.bootstrap.Launcher.startAsync(Launcher.java:125) [org.sonatype.nexus.bootstrap:3.0.0.03]
	at org.sonatype.nexus.bootstrap.osgi.LauncherActivator.start(LauncherActivator.java:62) [org.sonatype.nexus.bootstrap:3.0.0.03]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) [org.apache.felix.framework-5.4.0.jar:na]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2226) [org.apache.felix.framework-5.4.0.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144) [org.apache.felix.framework-5.4.0.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) [org.apache.felix.framework-5.4.0.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [org.apache.felix.framework-5.4.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
Caused by: java.lang.IllegalArgumentException: java.net.MalformedURLException: no protocol: /opt/nexus/etc/ssl/server-keystore.jks
	at org.eclipse.jetty.util.ssl.SslContextFactory.setKeyStorePath(SslContextFactory.java:550) [org.eclipse.jetty.util:9.3.7.v20160115]
	... 23 common frames omitted
Caused by: java.net.MalformedURLException: no protocol: /opt/nexus/etc/ssl/server-keystore.jks
	at java.net.URL.<init>(URL.java:593) [na:1.8.0_77]
	at java.net.URL.<init>(URL.java:490) [na:1.8.0_77]
	at java.net.URL.<init>(URL.java:439) [na:1.8.0_77]
	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:166) [org.eclipse.jetty.util:9.3.7.v20160115]
	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:149) [org.eclipse.jetty.util:9.3.7.v20160115]
	at org.eclipse.jetty.util.ssl.SslContextFactory.setKeyStorePath(SslContextFactory.java:546) [org.eclipse.jetty.util:9.3.7.v20160115]
	... 23 common frames omitted
2016-04-21 14:07:29,789-0700 ERROR [FelixDispatchQueue]  org.sonatype.nexus.bootstrap - FrameworkEvent ERROR - org.sonatype.nexus.bootstrap
org.osgi.framework.BundleException: Activator start error in bundle org.sonatype.nexus.bootstrap [46].
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2276) [na:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144) [na:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) [na:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [na:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) [na:1.8.0_77]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:488) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:411) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:799) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:423) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:358) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:259) [org.eclipse.jetty.xml:9.3.7.v20160115]
	at org.sonatype.nexus.bootstrap.jetty.JettyServer.doStart(JettyServer.java:168) [na:na]
	at org.sonatype.nexus.bootstrap.jetty.JettyServer.lambda$0(JettyServer.java:117) [na:na]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_77]
	at org.sonatype.nexus.bootstrap.jetty.JettyServer.start(JettyServer.java:115) [na:na]
	at org.sonatype.nexus.bootstrap.Launcher.start(Launcher.java:129) [na:na]
	at org.sonatype.nexus.bootstrap.Launcher.startAsync(Launcher.java:125) [na:na]
	at org.sonatype.nexus.bootstrap.osgi.LauncherActivator.start(LauncherActivator.java:62) [na:na]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) [na:na]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2226) [na:na]
	... 4 common frames omitted
Caused by: java.lang.IllegalArgumentException: java.net.MalformedURLException: no protocol: /opt/nexus/etc/ssl/server-keystore.jks
	at org.eclipse.jetty.util.ssl.SslContextFactory.setKeyStorePath(SslContextFactory.java:550) [org.eclipse.jetty.util:9.3.7.v20160115]
	... 23 common frames omitted
Caused by: java.net.MalformedURLException: no protocol: /opt/nexus/etc/ssl/server-keystore.jks
	at java.net.URL.<init>(URL.java:593) [na:1.8.0_77]
	at java.net.URL.<init>(URL.java:490) [na:1.8.0_77]
	at java.net.URL.<init>(URL.java:439) [na:1.8.0_77]
	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:166) [org.eclipse.jetty.util:9.3.7.v20160115]
	at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:149) [org.eclipse.jetty.util:9.3.7.v20160115]
	at org.eclipse.jetty.util.ssl.SslContextFactory.setKeyStorePath(SslContextFactory.java:546) [org.eclipse.jetty.util:9.3.7.v20160115]
	... 23 common frames omitted
```

**Comment by gregw** [comment]
Agreed.

In this case, we have already determined the passed resource string does not start with a known URL protocol, so throwing MalformedURLException is not that useful.

We should throw the IOException with the MalformedURLException as a suppressed exception.

However, in 9.3 the method signature does not let me do this, so I'll have to add the IOException as a suppressed exception on the MUE.  I'll switch around in 9.4

**Comment by gregw** [comment]
fixed
