### ISSUE TITLE
Warning ReadPendingException for each http request after migration to 9.4.28.v20200408

### ISSUE THREAD

**Issue by ichigo77** [eclipse/jetty.project#5241]
**Jetty version**: 9.4.28.v20200408
**Apache Camel**: 2.25.1
**CXF**: 3.3.6

**Java version**: 1.8.0_162_x64

**OS type/version**: Windows 10

**Description**:
Hello,

we have a middleware application which uses Apache-Camel and CXF for receiving, processing and forwarding SOAP-WS messages. It runs as a web application in a jetty standalone server. I migrated alle jetty dependencies and the server to 9.4.28.v20200408 from 9.2.19.v20160908. In addition, I migrated the Apache-Camel version to 2.25.1 and the CFX to 3.3.6 as well.
After the migration the middleware works as expected which one exception. The log file has for each http request the following warning:

```
WARN  org.eclipse.jetty.io.FillInterest: Read pending for C.ReadCB@bba5327{HttpConnection@bba5327::SocketChannelEndPoint@756abd2a{/127.0.0.1:57419<->/127.0.0.1:22561,OPEN,fill=FI,flush=-,to=0/30000}{io=0/1,kio=0,kro=1}->HttpConnection@bba5327[p=HttpParser{s=START,0 of -1},g=HttpGenerator@4198a76a{s=START}]=>HttpChannelOverHttp@10e2b3ea{s=HttpChannelState@c15d2af{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}} prevented AC.ReadCB@bba5327{HttpConnection@bba5327::SocketChannelEndPoint@756abd2a{/127.0.0.1:57419<->/127.0.0.1:22561,OPEN,fill=FI,flush=-,to=0/30000}{io=0/1,kio=0,kro=1}->HttpConnection@bba5327[p=HttpParser{s=START,0 of -1},g=HttpGenerator@4198a76a{s=START}]=>HttpChannelOverHttp@10e2b3ea{s=HttpChannelState@c15d2af{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}}
DEBUG org.eclipse.jetty.server.HttpConnection: HttpConnection@bba5327::SocketChannelEndPoint@756abd2a{/127.0.0.1:57419<->/127.0.0.1:22561,OPEN,fill=FI,flush=-,to=0/30000}{io=0/1,kio=0,kro=1}->HttpConnection@bba5327[p=HttpParser{s=START,0 of -1},g=HttpGenerator@4198a76a{s=START}]=>HttpChannelOverHttp@10e2b3ea{s=HttpChannelState@c15d2af{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0} onFillable exit HttpChannelState@c15d2af{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0} null
DEBUG org.eclipse.jetty.io.AbstractConnection: onClose HttpConnection@3d229e0c::SocketChannelEndPoint@72d8641c{/127.0.0.1:57421<->/127.0.0.1:17400,CLOSED,fill=-,flush=-,to=325/30000}{io=0/0,kio=-1,kro=-1}->HttpConnection@3d229e0c[p=HttpParser{s=CLOSED,5696 of 5696},g=HttpGenerator@c6bf530{s=START}]=>HttpChannelOverHttp@7c1f9437{s=HttpChannelState@78200f6c{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}
WARN  org.eclipse.jetty.util.thread.QueuedThreadPool: 
java.nio.channels.ReadPendingException
	at org.eclipse.jetty.io.FillInterest.register(FillInterest.java:58)
	at org.eclipse.jetty.io.AbstractEndPoint.fillInterested(AbstractEndPoint.java:362)
	at org.eclipse.jetty.io.AbstractConnection.fillInterested(AbstractConnection.java:134)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:281)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:745)
```
The SOAP-WS is provived by camel-cxf without any written code. It is done by configuration. The warning did not occur with the old jetty version. 

[LogExcerpt.txt](https://github.com/eclipse/jetty.project/files/5183716/LogExcerpt.txt)

**Comment by joakime** [comment]
Please upgrade your Jetty dependencies to at least 9.4.30, you are subject to a severe security vulnerability with 9.4.28.
See: https://www.eclipse.org/jetty/security-reports.html

The side effect of the vulnerability is that it will break bytebuffer pooling, and this alone can explain many issues, including your ReadPendingException.

**Comment by ichigo77** [comment]
Thanks for the hint.
I upgraded to 9.4.30.v20200611 but sadly the log file still has the same warning entry. Additionally, I found the following Warnings:
```
[2020 09-08 08:51:38.512] WARN  EatWhatYouKill [qtp1164371389-19]: 
java.nio.channels.ReadPendingException
	at org.eclipse.jetty.io.FillInterest.register(FillInterest.java:58)
	at org.eclipse.jetty.io.AbstractEndPoint.fillInterested(AbstractEndPoint.java:362)
	at org.eclipse.jetty.io.AbstractConnection.fillInterested(AbstractConnection.java:134)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:280)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)

[2020 09-08 16:00:45.060] WARN  EatWhatYouKill [qtp1715998167-20]: 
java.lang.IllegalStateException: s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0
	at org.eclipse.jetty.server.HttpChannelState.onError(HttpChannelState.java:763)
	at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:606)
	at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:488)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:535)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)

```

What can I do to gain any insights?

**Comment by ichigo77** [comment]
The issue was caused by our source code. To prevent class leaks, the application had a servlet filter which removes all references from ThreadLocals.
Thanks for your support.
