### ISSUE TITLE
Review async-demo

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#5289]
**Jetty version**
10.0.0-SNAPSHOT

```
2020-09-17 09:36:17.530:INFO :oejc.ResponseNotifier:HttpClient@24800026-38: Exception while notifying listener org.eclipse.jetty.example.asyncrest.AsyncRestServlet$1@4ee05075
java.lang.NullPointerException
	at org.eclipse.jetty.example.asyncrest.AsyncRestServlet$AsyncRestRequest.onComplete(AsyncRestServlet.java:190)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:532)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:512)
	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:608)
	at org.eclipse.jetty.client.HttpReceiver.responseFailure(HttpReceiver.java:504)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.failAndClose(HttpReceiverOverHTTP.java:414)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:386)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1590)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:274)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:196)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:92)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:95)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:195)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:324)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:528)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:377)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:163)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:106)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:790)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:912)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by gregw** [comment]
@lachlan-roberts can you try to reproduce???? This appears for me in about 1 in 10 reloads of the page.
Looking at the code, I do not understand how it could even happen?!?!?

**Comment by gregw** [comment]
... and it feels rather slow as well???

**Comment by gregw** [comment]
I think this was just ebay having problems.  We could perhaps improve the error handling, but for now this doesn't need to be fixed in a hurry.
Perhaps reivew, refresh and update at some stage.
