### ISSUE TITLE
EofException during flush

### ISSUE THREAD

**Issue by ChaitanyaKiranPVN** [eclipse/jetty.project#5318]
**Jetty version**
Jetty version 9.4.5 
**Java version**
jdk1.8
**Question**
Recently iam getting the below issue in the Prod Enviornment 

org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:384)
	at org.eclipse.jetty.io.ChannelEndPoint$3.run(ChannelEndPoint.java:139)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:270)
	... 10 more
if i received this error then my server load is increased and the web requests are slow . once i restarted the server then the application is working fine. 
Please let me know what could be the issue and provide the solution . 
Thanks 
Chaitanya Kiran PVN

**Comment by sbordet** [comment]
The stack trace shows that your server was writing to an connection that was TCP congested, and when it resumed writing the connection was closed by the client.

The exception is reported to the application that failed to write, so it has the chance to do something.
If the application lets the exception to flow out, Jetty by default will log it at DEBUG level.

**Comment by joakime** [comment]
> Jetty version 9.4.5

You should upgrade, you are subject to several Security issues with that version of Jetty.

See: https://www.eclipse.org/jetty/security-reports.html
