### ISSUE TITLE
Deadlock in MongoSessionManager

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#534]
Deadlock situation in mongo sessions with session idle passivation enabled:

"qtp1365202186-1034":
        at org.eclipse.jetty.server.session.AbstractSessionIdManager.newSessionId(AbstractSessionIdManager.java:127)
        - waiting to lock <0x00000000e3293928> (a org.eclipse.jetty.nosql.mongodb.MongoSessionIdManager)
        at org.eclipse.jetty.server.session.AbstractSession.<init>(AbstractSession.java:73)

"qtp1365202186-28":
        at org.eclipse.jetty.nosql.mongodb.MongoSessionManager.save(MongoSessionManager.java:223)
        - waiting to lock <0x00000000e349c448> (a org.eclipse.jetty.nosql.mongodb.MongoSessionManager)
        at org.eclipse.jetty.nosql.NoSqlSession.save(NoSqlSession.java:182)
        - locked <0x00000000e6670798> (a org.eclipse.jetty.nosql.NoSqlSession)
        at org.eclipse.jetty.nosql.NoSqlSessionManager.addSession(NoSqlSessionManager.java:73)
        at org.eclipse.jetty.server.session.AbstractSessionManager.addSession(AbstractSessionManager.java:692)
        - locked <0x00000000e3293928> (a org.eclipse.jetty.nosql.mongodb.MongoSessionIdManager)
        at org.eclipse.jetty.server.session.AbstractSessionManager.newHttpSession(AbstractSessionManager.java:576)

"Scheduler-1552787810":
        at org.eclipse.jetty.server.session.AbstractSession.getAccessed(AbstractSession.java:131)
        - waiting to lock <0x00000000e6b6b078> (a org.eclipse.jetty.nosql.NoSqlSession)
        at org.eclipse.jetty.nosql.mongodb.MongoSessionManager.idle(MongoSessionManager.java:597)
        - locked <0x00000000e349c448> (a org.eclipse.jetty.nosql.mongodb.MongoSessionManager)
        at org.eclipse.jetty.nosql.mongodb.MongoSessionIdManager.idle(MongoSessionIdManager.java:705)

"qtp1365202186-62":
        at org.eclipse.jetty.nosql.mongodb.MongoSessionManager.save(MongoSessionManager.java:223)
        - waiting to lock <0x00000000e349c448> (a org.eclipse.jetty.nosql.mongodb.MongoSessionManager)
        at org.eclipse.jetty.nosql.NoSqlSession.save(NoSqlSession.java:182)
        - locked <0x00000000e6b6b078> (a org.eclipse.jetty.nosql.NoSqlSession)
        at org.eclipse.jetty.nosql.NoSqlSession.complete(NoSqlSession.java:157)

**Comment by janbartel** [comment]
Fix checked in and undergoing testing.
