### ISSUE TITLE
NPE from WebInfConfiguration.deconfigure during WebAppContext shutdown 

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5480]
**Jetty version**
9.4.x

**Description**
When shutting down WebAppContext, there occasionally is seen a NullPointerException.

```
java.lang.NullPointerException
	at org.eclipse.jetty.util.IO.delete(IO.java:368)
	at org.eclipse.jetty.webapp.WebInfConfiguration.deconfigure(WebInfConfiguration.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1433)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1115)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:297)
	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:547)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
```

**Comment by joakime** [comment]
It's easy to add the safety checks for this, but why was `WebAppContext.getTempDirectory()` null during `WebInfConfiguration.deconfigure(WebAppContext context)` ?

**Comment by joakime** [comment]
The only ways that `context.getTempDirectory()` could return a null during `WebInfConfiguration.deconfigure()` is ...

1. There was never a Temp Directory setup for the context.
2. A process outside of Jetty intentionally called `context.setTempDirectory(null)`
3. The `WebInfConfiguration.deconfigure(WebAppContext)` was run twice against the same WebAppContext.

For scenario 1, that's not really possible if `WebInfConfiguration` is in play.
As the `WebInfConfiguration.preConfigure(WebAppContext)` ensures a Temp Directory.

For scenario 2, the safety checks will help, nothing we can do about that.

For scenario 3, the safety checks will help again, but that's a bad configuration on the installation side.

**Comment by joakime** [comment]
Opened PR #5481
