### ISSUE TITLE
BadMessageException in the log coming from QueuedThreadPool

### ISSUE THREAD

**Issue by janikgithub** [eclipse/jetty.project#5487]
**Jetty version**   9.4.31.v20200723

**Java version** JDK   1.1.8.0_181-b13

**OS type/version** Oracle Linux Server 7.4

**Description** Exceptions in the log file

I see exception below in the application log file. I am trying to figure out application issues  related to the `ScheduledExecutorService` and was wondering if this is relevant,

Thanks

```
2020-10-20 22:22:27 {qtp1237598030-17553} DEBUG [Server] [B0CC744E51AAD11FE0531D11000AF587] org.eclipse.jetty.http.HttpParser - HEADER --> END
2020-10-20 22:22:27 {qtp1237598030-17553} DEBUG [Server] [B0CC744E51AAD11FE0531D11000AF587] org.eclipse.jetty.http.HttpParser - Parse exception: HttpParser{s=END,0 of -1} for HttpChannelOverHttp@f022385{r=1,c=false,c=false/false,a=IDLE,uri=//my-servername.com
./././././././././././././././././././././././././././././././././././././././././././././././././././././.
/././././././././././././././././././././././././././././././././././././././././././../../../../../../../../,age=0}
org.eclipse.jetty.http.BadMessageException: 400: Bad URI
        at org.eclipse.jetty.server.Request.setMetaData(Request.java:1806)
        at org.eclipse.jetty.server.HttpChannel.onRequest(HttpChannel.java:698)
        at org.eclipse.jetty.server.HttpChannelOverHttp.headerComplete(HttpChannelOverHttp.java:389)
        at org.eclipse.jetty.http.HttpParser.handleHeaderContentMessage(HttpParser.java:588)
        at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1213)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1502)
        at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:369)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
2020-10-20 22:22:27 {qtp1237598030-17553} DEBUG [Server] [B0CC744E51AAD11FE0531D11000AF587] org.eclipse.jetty.http.HttpParser - END --> CLOSE
```

**Comment by joakime** [comment]
Looks like someone is trying to find weaknesses and vulnerabilities in your Jetty server.

As you can see this is just a DEBUG level logging event, it's of no real consequence, Jetty determined it was a malicious URI and responded accordingly.
You might want to setup a RequestLog to track these requests (including their IPs) for audit reasons.

**Comment by janikgithub** [comment]
Thank you @joakime
