### ISSUE TITLE
ResourceCollection NPE in list()

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#5521]
**Jetty version**
9.4.x

**Description**
```
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
    at java.util.Collections.addAll (Collections.java:5592)
    at org.eclipse.jetty.util.resource.ResourceCollection.list (ResourceCollection.java:423)
    at org.eclipse.jetty.util.resource.Resource.getAllResources (Resource.java:886)
    at org.eclipse.jetty.annotations.AnnotationParser.parseDir (AnnotationParser.java:777)
    at org.eclipse.jetty.annotations.AnnotationParser.parse (AnnotationParser.java:735)
    at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call (AnnotationConfiguration.java:172)
    at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run (AnnotationConfiguration.java:465)
```

**Comment by joakime** [comment]
Looks like the last commit broken jetty-maven-plugin's classloader.

It failed, consistently, across all JDKs.

```
Exception in thread "Thread-190" java.lang.NoClassDefFoundError: org/testcontainers/utility/PathUtils
	at org.testcontainers.utility.MountableFile.lambda$deleteOnExit$0(MountableFile.java:292)
       at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.testcontainers.utility.PathUtils
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
```

**Comment by gregw** [comment]
Still work needed in jetty-10
