### ISSUE TITLE
1 page refresh and I get: java.io.IOException: enhance_your_calm_error/invalid_priority_frame_rate

### ISSUE THREAD

**Issue by oleg-astakhov** [eclipse/jetty.project#5528]
Following advice given here: https://www.eclipse.org/lists/jetty-users/msg09622.html raising this issue.

**Jetty version**
`Embedded 9.4.31`

**Java version**
```
openjdk 11.0.9 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)
```

**Spring Boot version**
`2.3.4 `

**OS type/version**
`Windows 7, x86_64`

**Browser**
`Chrome `
`Version 86.0.4240.111 (Official Build) (64-bit)`

**Server specific dependencies in Gradle**
```
    implementation 'org.springframework.boot:spring-boot-starter-jetty'
    implementation 'org.eclipse.jetty:jetty-alpn-conscrypt-server'
    implementation 'org.eclipse.jetty.http2:http2-server'    
```

**Other configuration which might be of interest**
```
server.http2.enabled=true
server.compression.enabled=true
server.compression.min-response-size=1024
```
plus `server.ssl.*` configuration

**Description**

Http requests get "dropped" due to `rate control` feature of Jetty and as a result resources do not get downloaded which results in half-loaded web pages. I get the following exceptions in logs:

```
2020-10-28 16:55:26,961 DEBUG [] [] [] [qtp1453347620-96] (org.eclipse.jetty.server.HttpChannelState:422) - nextAction(false) TERMINATED HttpChannelState@63c4bfb3{s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0}
2020-10-28 16:55:26,961 DEBUG [] [] [] [qtp1453347620-82] (org.eclipse.jetty.server.HttpChannel$SendCallback:1215) - Commit failed
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:167) [http2-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.http2.HTTP2Stream.notifyFailure(HTTP2Stream.java:661) [http2-common-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.http2.HTTP2Stream.onFailure(HTTP2Stream.java:406) [http2-common-9.4.31.v20200723.jar:9.4.31.v20200723]

        ...

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: enhance_your_calm_error/invalid_priority_frame_rate
	at org.eclipse.jetty.http2.HTTP2Session.toFailure(HTTP2Session.java:582) ~[http2-common-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.http2.HTTP2Session.onConnectionFailure(HTTP2Session.java:538) ~[http2-common-9.4.31.v20200723.jar:9.4.31.v20200723]
	... 19 more
```

```
2020-10-28 16:55:26,958 DEBUG [] [] [] [qtp1453347620-28] (org.eclipse.jetty.server.HttpChannel:588) - /fonts/Roboto-Regular-webfont.woff
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:167) ~[http2-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.http2.HTTP2Stream.notifyFailure(HTTP2Stream.java:661) ~[http2-common-9.4.31.v20200723.jar:9.4.31.v20200723]

        ....

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:830) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323) ~[http2-server-9.4.31.v20200723.jar:9.4.31.v20200723]

                ...

		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
		at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: enhance_your_calm_error/invalid_priority_frame_rate
	at org.eclipse.jetty.http2.HTTP2Session.toFailure(HTTP2Session.java:582) ~[http2-common-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.http2.HTTP2Session.onConnectionFailure(HTTP2Session.java:538) ~[http2-common-9.4.31.v20200723.jar:9.4.31.v20200723]
	... 19 more
```

I just load single server-rendered page, do not do any heavy load testing. 1 user, 1 page load, on localhost, on HTTP/2. Chrome reports 49 requests have been made after full page load. For requests which were dropped due to `rate control` Chrome status column says `(failed)net::ERR_HTTP2_PROTOCOL_ERROR`

I have attached log, which contains logs only from app startup + 2 web page refreshes only
This `Caused by: java.io.IOException: enhance_your_calm_error/invalid_priority_frame_rate` is listed 140 times in the log.

[jetty-log.zip](https://github.com/eclipse/jetty.project/files/5453108/jetty-log.zip)

The default value that is set for `rate control` is 20 events per second. This https://www.eclipse.org/lists/jetty-users/msg09182.html mail suggests increasing to 40.

Since I could not find any way to configure `jetty.http2.rateControl.maxEventsPerSecond` via Spring Boot, by digging into Jetty source code I was able to write this solution:

```java
@Configuration
public class JettyRateControlFactoryReinitializationService implements WebServerFactoryCustomizer<ConfigurableJettyWebServerFactory> {

    @Override
    public void customize(ConfigurableJettyWebServerFactory factory) {
        factory.addServerCustomizers(
                server -> {
                    if (0 == server.getConnectors().length) {
                        throw new RuntimeException("Unexpected number of server connectors. At least one is expected at this point");
                    }
                    final List<AbstractHTTP2ServerConnectionFactory> connectionFactories = 
                            (server.getConnectors()[0]).getConnectionFactories()
                            .stream()
                            .filter(it -> it instanceof AbstractHTTP2ServerConnectionFactory)
                            .map(it -> (AbstractHTTP2ServerConnectionFactory)it)
                            .collect(Collectors.toList());
                    if (connectionFactories.isEmpty()) {
                        throw new RuntimeException("Unexpected number of connection factories at this point");
                    }
                    final AbstractHTTP2ServerConnectionFactory http2ServerConnectionFactory = connectionFactories.iterator().next();


                    // default is 20 and seems like not enough
                    http2ServerConnectionFactory.setRateControlFactory(new WindowRateControl.Factory(40)); 
                }
        );
    }
}
````

After I re-initialized rate control factory as described above, I no longer receive such exceptions and all resources load fine.

The aim of this issue is to find out whether the default value of 20 events per second is too small and whether it needs to be increased, as I am constantly getting the behavior I described when it is set to 20, and not doing any load testing at all.

[jetty-log.zip](https://github.com/eclipse/jetty.project/files/5453108/jetty-log.zip)

**Comment by joakime** [comment]
This might be simpler ...

``` java
server.getBeans(ServerConnector.class)
    .stream()
    .map((sc) -> sc.getConnectionFactory(AbstractHTTP2ServerConnectionFactory.class))
    .filter(Objects::nonNull)
    .forEach((fact) -> fact.setRateControlFactory(new WindowRateControl.Factory(40)));
```

It will only work against `ServerConnector` instances (not the other Connector types that are irrelevant here).
And then, only ones with ServerConnectors that have an `AbstractHTTP2ServerConnectionFactory` instance.

I skipped iterating through the entire list of `ConnectionFactories` for two (or more) cases of `AbstractHTTP2ServerConnectionFactory`, which is rather atypical.
You would basically have both `http2` and `http2c` connection factories active on the same `ServerConnector` at the same time, which is possible (Jetty doesn't prevent this kind of configuration), it is just a strange configuration.

**Comment by oleg-astakhov** [comment]
Thank you @joakime, noted!
I also have some customization code in place, which I removed for brevity (there I added another Connector so that I could perform redirection from HTTP to HTTPS).

But regarding multiple instances of `AbstractHTTP2ServerConnectionFactory` , yes, I will change it.

**Comment by sbordet** [comment]
@gregw so the problem currently stems from the fact that the page indeed loads a lot of resources (but that's to be expected and we should not complain), and the fact that PRIORITY frames can be either standalone or embedded in a HEADERS frame - however we don't distinguish the case.

Standalone ones are possible source of attack, but embedded ones are typically not (they belong to a proper HEADERS frame for a request).

So perhaps skip the embedded ones from rate control?

**Comment by sbordet** [comment]
@gregw cancel the comment above, I was mistaken.
Embedded PRIORITY frames are not parsed by the `PriorityBodyParser`.

Looking better at the logs, it is indeed Chrome that sends a gazillion PRIORITY frames after the requests.

At this point I'm not sure what to do. The normal Chrome behavior is indistinguishable from an attack.
We can raise the default value, but it would be tripped by a page with more resources for which Chrome decides to reprioritize.

Grepped from the logs:
```
2020-10-28 16:54:38,114 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@61f0668a#45/#41{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15540184,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,115 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@697105af#43/#75{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15523800,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,116 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@7701b6aa#51/#47{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15507416,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,117 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@2388f069#49/#43{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,118 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@41ae06a4#67/#57{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,120 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@20133f43#65/#49{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,121 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@5a5d690d#45/#39{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,122 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@3e32c197#41/#65{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,124 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@f186bd3#55/#51{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,125 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@3648a454#53/#41{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,126 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@76ca691#45/#37{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,127 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@2f7af192#39/#53{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,128 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@63f0515d#45/#35{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,130 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@10693373#37/#39{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,134 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@72d357c1#45/#33{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,135 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@a5dce68#35/#37{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,138 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@6bc60cc7#51/#45{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,142 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@32ed4867#47/#35{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,146 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@5a687ca4#67/#55{weight=147,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15491032,recvWindow=1048576,streams=19,NOT_CLOSED,null}
2020-10-28 16:54:38,150 DEBUG [] [] [] [qtp1453347620-79] (org.eclipse.jetty.http2.HTTP2Session:293) - Received PriorityFrame@3ea2c70f#57/#47{weight=220,exclusive=true} on HTTP2ServerSession@7a9f12c2{l:/0:0:0:0:0:0:0:1:8443 <-> r:/0:0:0:0:0:0:0:1:50127,sendWindow=15489284,recvWindow=1048576,streams=19,NOT_CLOSED,null}
```

There are 20 PRIORITY frames in 36 milliseconds, and I guess the number is only limited because we produce an error thinking it's an attack.

Many streams (e.g. 35, 39) are reprioritized multiple times :facepalm:

**Comment by gregw** [comment]
@sbordet do we need to make the acceptable rate of priority frames proportional to the number of streams.   It is easy to have 100s or 1000s of streams, so even a single priority message per stream will blow a fixed per connection rate easily.  There is a difference between 1 stream with 100 priority frames and 100 streams with 1 priority frame.

**Comment by joakime** [comment]
Doesn't the Rate only apply at the Parser level?

**Comment by gregw** [comment]
Rate does apply at the parser level, so it is a rate of events per connection as the parser is per connection.
I'm thinking that perhaps every time we open a new stream we allow several priority frames before we start counting them as events?

**Comment by sbordet** [comment]
> I'm thinking that perhaps every time we open a new stream we allow several priority frames before we start counting them as events?

That would be another configurable parameter, which I'm not keen adding as it seems ad-hoc.

I would prefer if we can make the current parameter "relative" as you propose.
With 100 streams, an attacker would be able to send 2000 PRIORITY frames per second though.

**Comment by sbordet** [comment]
We have increased the default value in #6369, and in particular cases such as this issue the value could be set to an even higher value.

Chrome sending so many priority frames seems totally unnecessary, and in general priorities are being phased out as they are not supported in HTTP/3 anymore, and new RFCs such as [Early Hints](https://www.rfc-editor.org/rfc/rfc8297.html) replace the priority mechanism (see for example here: https://developer.chrome.com/blog/early-hints/).
