### ISSUE TITLE
jetty-cdi + narayana-jta : CreationException

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse/jetty.project#5530]
**Jetty version**
9.4.33.v20201020

**Java version**
OpenJDK 12

**OS type/version**
Debian stable

**Description**
Adding `org.eclipse.jetty:jetty-cdi:9.4.33.v20201020` to the class path breaks the TransactionManager of narayana.

To reproduce: 
1. clone the [jta-1_2-standalone](https://github.com/jbosstm/quickstart/tree/master/jta-1_2-standalone) quickstart project from Narayana (explained [here](http://jbossts.blogspot.com/2019/04/jta-and-cdi-integration.html))
2. change `<version.narayana>5.10.7.Final-SNAPSHOT</version.narayana>` to `<version.narayana>5.10.6.Final</version.narayana>`
3. add `org.eclipse.jetty:jetty-cdi:9.4.33.v20201020` to the POM
4. run the `CDITransactionServicesTestCase` test.

This yields the following stack trace.

```
javax.enterprise.inject.CreationException
	at com.arjuna.ats.jta.cdi.NarayanaTransactionManager.getDelegate(NarayanaTransactionManager.java:249)
	at com.arjuna.ats.jta.cdi.NarayanaTransactionManager.<init>(NarayanaTransactionManager.java:178)
	at com.arjuna.ats.jta.cdi.NarayanaTransactionManager.<init>(NarayanaTransactionManager.java:150)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:119)
	at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallbacks(ConstructorInjectionPoint.java:92)
	at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:78)
	at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:112)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:186)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
	at com.arjuna.ats.jta.cdi.NarayanaTransactionManager$Proxy$_$$_WeldClientProxy.begin(Unknown Source)
	at org.jboss.narayana.quickstarts.jta.CDIBindingTestCase.testTransactionScoped(CDIBindingTestCase.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: javax.naming.NameNotFoundException; remaining name 'TransactionManager'
	at org.eclipse.jetty.jndi.NamingContext.lookup(NamingContext.java:449)
	at org.eclipse.jetty.jndi.NamingContext.lookup(NamingContext.java:505)
	at org.eclipse.jetty.jndi.java.javaRootURLContext.lookup(javaRootURLContext.java:101)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	at com.arjuna.ats.jta.cdi.JTASupplier.get(JTASupplier.java:100)
	at com.arjuna.ats.jta.cdi.NarayanaTransactionManager.getDelegate(NarayanaTransactionManager.java:246)
	... 49 more
```

**Expected**
The test case should work after adding jetty-cdi, as it works without jetty-cdi.

**Practical annoyance**
As a result of this apparent incompatibility, I can’t make Narayana work with Jetty and intercept `@Transactional` methods as I would like.

**Comment by joakime** [comment]
It's not finding the JNDI "TransactionManager"

Seeing as the [CDIBindingTestCase](https://github.com/jbosstm/quickstart/blob/master/jta-1_2-standalone/src/test/java/org/jboss/narayana/quickstarts/jta/CDIBindingTestCase.java) makes special provisions for this, and the [beans.xml](https://github.com/jbosstm/quickstart/blob/master/jta-1_2-standalone/src/main/resources/META-INF/beans.xml) has notes about this, I'm reasonably confident that this is not a Jetty issue.

**Comment by joakime** [comment]
The JNDI "TransactionManager" needs to come from somewhere.
Jetty isn't adding it. (that's not the role of Jetty, or the CDI layer in Jetty)

Does weld? (then this is a weld issue)
Does narayana? (then this is a narayana issue)
Does jta? (then this is a jta issue)

**Comment by joakime** [comment]
Merely adding `jetty-cdi` to the pom simply changes your dependencies.
Nothing about adding `jetty-cdi` causes any change in execution on that project, as nothing in that project, nor that `CDITransactionServicesTestCase` is using the features that `jetty-cdi` provides.

I suspect you are just accidentally changing dependencies / dependency versions of WELD and that is causing you your headaches.

**Comment by oliviercailloux** [comment]
Thanks, these observations put me on the right track. 

**The problem**
Turns out that it is actually `jetty-jndi` that creates the problem with Narayana. Replacing `jetty-jndi` with `jetty-util` restores the test success. I guess Narayana does something differently when it detects some JNDI implementation in the classpath (?).

**Versions comparison**
The version of weld, or anything else, does not change at all. Here is a comparison of all dependencies.

With jetty-jndi (the test fails):
```
mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:tree | less -R

[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ jta-1_2-standalone ---
[INFO] org.jboss.narayana.quickstart.jta:jta-1_2-standalone:jar:5.10.7.Final-SNAPSHOT
[INFO] +- org.eclipse.jetty:jetty-jndi:jar:9.4.33.v20201020:compile
[INFO] |  \- org.eclipse.jetty:jetty-util:jar:9.4.33.v20201020:compile
[INFO] +- org.jboss.narayana.jta:narayana-jta:jar:5.10.6.Final:compile
[INFO] |  +- org.jboss:jboss-transaction-spi:jar:7.6.0.Final:compile
[INFO] |  \- org.jboss.spec.javax.resource:jboss-connector-api_1.7_spec:jar:1.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
[INFO] +- org.jboss.naming:jnpserver:jar:5.0.3.GA:compile
[INFO] |  \- org.jboss:jboss-common-core:jar:2.2.10.GA:compile
[INFO] +- org.jboss.weld.se:weld-se-core:jar:3.1.0.Final:compile
[INFO] |  +- org.jboss.weld.environment:weld-environment-common:jar:3.1.0.Final:compile
[INFO] |  +- org.jboss.weld.probe:weld-probe-core:jar:3.1.0.Final:compile
[INFO] |  +- javax.enterprise:cdi-api:jar:2.0.SP1:compile
[INFO] |  |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  \- org.jboss.classfilewriter:jboss-classfilewriter:jar:1.2.3.Final:compile
[INFO] +- org.jboss.weld.module:weld-jta:jar:3.1.0.Final:compile
[INFO] |  +- org.jboss.weld:weld-api:jar:3.1.Final:compile
[INFO] |  +- org.jboss.weld:weld-core-impl:jar:3.1.0.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:1.0.0.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.el:jboss-el-api_3.0_spec:jar:1.0.13.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec:jar:1.0.0.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.2.1.Final:compile
[INFO] |  \- org.jboss.weld:weld-spi:jar:3.1.Final:compile
[INFO] \- junit:junit:jar:4.13.1:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```
With jetty-util (the test passes):
```
mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:tree | less -R

[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ jta-1_2-standalone ---
[INFO] org.jboss.narayana.quickstart.jta:jta-1_2-standalone:jar:5.10.7.Final-SNAPSHOT
[INFO] +- org.eclipse.jetty:jetty-util:jar:9.4.33.v20201020:compile
[INFO] +- org.jboss.narayana.jta:narayana-jta:jar:5.10.6.Final:compile
[INFO] |  +- org.jboss:jboss-transaction-spi:jar:7.6.0.Final:compile
[INFO] |  \- org.jboss.spec.javax.resource:jboss-connector-api_1.7_spec:jar:1.0.0.Final:compile
[INFO] +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
[INFO] +- org.jboss.naming:jnpserver:jar:5.0.3.GA:compile
[INFO] |  \- org.jboss:jboss-common-core:jar:2.2.10.GA:compile
[INFO] +- org.jboss.weld.se:weld-se-core:jar:3.1.0.Final:compile
[INFO] |  +- org.jboss.weld.environment:weld-environment-common:jar:3.1.0.Final:compile
[INFO] |  +- org.jboss.weld.probe:weld-probe-core:jar:3.1.0.Final:compile
[INFO] |  +- javax.enterprise:cdi-api:jar:2.0.SP1:compile
[INFO] |  |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  \- org.jboss.classfilewriter:jboss-classfilewriter:jar:1.2.3.Final:compile
[INFO] +- org.jboss.weld.module:weld-jta:jar:3.1.0.Final:compile
[INFO] |  +- org.jboss.weld:weld-api:jar:3.1.Final:compile
[INFO] |  +- org.jboss.weld:weld-core-impl:jar:3.1.0.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:1.0.0.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.el:jboss-el-api_3.0_spec:jar:1.0.13.Final:compile
[INFO] |  |  +- org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec:jar:1.0.0.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.2.1.Final:compile
[INFO] |  \- org.jboss.weld:weld-spi:jar:3.1.Final:compile
[INFO] \- junit:junit:jar:4.13.1:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```
`diff` confirms that the only difference is the `jetty-jndi` dependency.

**(Temporary?) conclusion**
I suppose it is more or less safe to conclude that Jetty is doing nothing wrong here. (Arguably, IMHO, it is quite unexpected that Narayana changes its behavior when JNDI is available, but that may be a feature and not a bug, and is to be discussed with them, I suppose.)

**Comment by gregw** [comment]
I think the issue is probably that `org.jboss.naming:jnpserver` is also a JNDI implementation and that it is not that jetty is adding JNDI, but rather that you have 2 JNDIs on the classpath that does not work.
Thanks for updating us.

**Comment by oliviercailloux** [comment]
Just tried without `org.jboss.naming:jnpserver:5.0.3`: same behavior. That is, the `CDITransactionServicesTestCase` test passes without `org.eclipse.jetty:jetty-jndi:9.4.33.v20201020` and fails with `org.eclipse.jetty:jetty-jndi:9.4.33.v20201020`. (Also removing `org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec` preserves the strange behavior.)

There really seems to be something odd going on with `org.eclipse.jetty:jetty-jndi`, `org.jboss.narayana.jta:narayana-jta` and Weld.

I have posted a question to the [Narayana Forum](https://groups.google.com/g/narayana-users), let’s see how it unfolds.
