### ISSUE TITLE
Jetty + CDI miss provider

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5540]
**Jetty version**
9.4.19.v20190610
**Java version**
1.8
**Question**
CDI：use --module=cdi

i got a error
`

java.lang.RuntimeException: java.lang.IllegalStateException: Unable to access CDI
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:69)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:350)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:281)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:256)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at com.thunisoft.tas.server.jetty.server.handler.TasInfoHandler.doStart(TasInfoHandler.java:94)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1797)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1746)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:490)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
	at com.thunisoft.tas.server.StartMain.main(StartMain.java:27)
Caused by: java.lang.IllegalStateException: Unable to access CDI
	at javax.enterprise.inject.spi.CDI.current(CDI.java:65)
	at org.jboss.weld.servlet.WeldInitialListener.contextInitialized(WeldInitialListener.java:94)
	at org.jboss.weld.servlet.api.helpers.ForwardingServletListener.contextInitialized(ForwardingServletListener.java:34)
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:66)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:64)
	... 47 common frames omitted

`

![image](https://user-images.githubusercontent.com/33625419/97825321-4d0c0580-1cf9-11eb-9b2a-cfb6058d9648.png)

Why is there no PROVIDER for CDI? Am I missing something to depend on?

**Comment by janbartel** [comment]
@zhengshundong01 I don't think this is a jetty issue. As you say, you might be missing some dependencies, or have something else wrong with your environment.

Try comparing your setup with a fresh installation of the jetty distro, cd to the demo-base/ directory and add the cdi module (using java -jar ../start.jar --add-to-startd=cdi). Then start the demo (java -jar ../start.jar). You should see log output similar to the following:

> 
> 2020-11-02 10:15:41.861:INFO::main: Logging initialized @559ms to org.eclipse.jetty.util.log.StdErrLog
> 2020-11-02 10:15:42.015:WARN:oejx.XmlConfiguration:main: Deprecated method public void org.eclipse.jetty.server.HttpConfiguration.setBlockingTimeout(long) in file:///home/janb/usr_local_java/jetty/jetty-distribution-9.4.19.v20190610/etc/jetty.xml
> 2020-11-02 10:15:42.172:WARN::main: demo test-realm is deployed. DO NOT USE IN PRODUCTION!
> 2020-11-02 10:15:42.174:INFO:oejs.Server:main: jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 11.0.2+9-LTS
> 2020-11-02 10:15:42.193:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/janb/usr_local_java/jetty/jetty-distribution-9.4.19.v20190610/demo-base/webapps/] at interval 1
> 2020-11-02 10:15:42.499:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=81ms
> 2020-11-02 10:15:42.504:WARN::main: test webapp is deployed. DO NOT USE IN PRODUCTION!
> Nov. 02, 2020 10:15:42 AM org.jboss.weld.environment.servlet.EnhancedListener onStartup
> INFO: WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
> Nov. 02, 2020 10:15:42 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
> INFO: WELD-000900: 2.4.3 (Final)
> Nov. 02, 2020 10:15:42 AM org.jboss.weld.bootstrap.WeldStartup startContainer
> INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
> Nov. 02, 2020 10:15:43 AM org.jboss.weld.environment.servlet.WeldServletLifecycle findContainer
> INFO: WELD-ENV-001002: Container detection skipped - custom container class loaded: org.jboss.weld.environment.jetty.JettyContainer.
> Nov. 02, 2020 10:15:43 AM org.jboss.weld.environment.jetty.JettyContainer initialize
> INFO: WELD-ENV-001200: Jetty 7.2+ detected, CDI injection will be available in Servlets and Filters. Injection into Listeners should work on Jetty 9.1.1 and newer.


Assuming you see the same, compare the setup of the cdi stuff in demo-base with your webapp to see what is different.

**Comment by joakime** [comment]
I agree with @janbartel 

Also, Upgrade your version of Jetty.
9.4.19 is over a year old. (and is subject to several security advisories - https://www.eclipse.org/jetty/security-reports.html)

Try 9.4.33.v20201020 (it has a few updates for jetty-cdi as well)

**Comment by janbartel** [comment]
I'm going to close this issue, as it looks like a setup problem with the environment, rather than a bug in jetty. If you feel differently, please reopen the issue and provide all config files, logs etc.
