### ISSUE TITLE
WELD-001456: Argument resolvedBean must not be null

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5541]
Jetty version
9.4.19.v20190610
Java version
1.8
Question
CDI：use --module=cdi

```
2582314 [qtp1776374725-20] WARN  o.eclipse.jetty.server.HttpChannel - /insurance/index.jsf 
javax.servlet.ServletException: javax.servlet.ServletException: WELD-001456: Argument resolvedBean must not be null
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:168)
	at com.thunisoft.tas.core.handler.TasStatisticsHandler.handle(TasStatisticsHandler.java:55)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at com.thunisoft.tas.server.jetty.server.handler.TasInfoHandler.handle(TasInfoHandler.java:155)
	at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:178)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: WELD-001456: Argument resolvedBean must not be null
	at javax.faces.webapp.FacesServlet.service(Unknown Source)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1625)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1612)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	... 14 common frames omitted
Caused by: org.jboss.weld.exceptions.IllegalArgumentException: WELD-001456: Argument resolvedBean must not be null
	at org.jboss.weld.util.Preconditions.checkArgumentNotNull(Preconditions.java:40)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:810)
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:358)
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:369)
	at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
	at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:117)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:159)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:758)
	at org.jboss.weld.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
	at org.jboss.weld.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
	at org.jboss.weld.environment.servlet.util.ForwardingELResolver.getValue(ForwardingELResolver.java:49)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(Unknown Source)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(Unknown Source)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:94)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:137)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(Unknown Source)
	at javax.faces.component.ComponentStateHelper.eval(Unknown Source)
	at javax.faces.component.ComponentStateHelper.eval(Unknown Source)
	at javax.faces.component.UIOutput.getValue(Unknown Source)
	at javax.faces.component.UIInput.getValue(Unknown Source)
	at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getValue(Unknown Source)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getCurrentValue(Unknown Source)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeEnd(Unknown Source)
	at javax.faces.component.UIComponentBase.encodeEnd(Unknown Source)
	at javax.faces.component.UIComponent.encodeAll(Unknown Source)
	at javax.faces.render.Renderer.encodeChildren(Unknown Source)
	at javax.faces.component.UIComponentBase.encodeChildren(Unknown Source)
	at javax.faces.component.UIComponent.encodeAll(Unknown Source)
	at javax.faces.component.UIComponent.encodeAll(Unknown Source)
	at javax.faces.component.UIComponent.encodeAll(Unknown Source)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(Unknown Source)
	at com.sun.faces.application.view.MultiViewHandler.renderView(Unknown Source)
	at javax.faces.application.ViewHandlerWrapper.renderView(Unknown Source)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(Unknown Source)
	at com.sun.faces.lifecycle.Phase.doPhase(Unknown Source)
	at com.sun.faces.lifecycle.LifecycleImpl.render(Unknown Source)
	... 35 common frames omitted

```

i debug this error, i found When the loginBean is loaded, it is found that its dependencies（PolicyHolderRegistration） are not caused in the beanManager。

```
@RequestScoped
@Named("loginBean")
public class LoginBean implements Serializable {
    @Inject
    private PolicyHolderRegistration policyHolderRegistration;
}
```

```
@Stateless
@Path("/registration")
@Produces({"application/json"})
public class PolicyHolderRegistration {
}
```

It looks as if he does not support stateless beans for loading

**Comment by janbartel** [comment]
Hi @zhengshundong01.  I don't see any involvement from jetty in this, other than being the servlet container in which you are running faces and weld. I suggest you ask the weld project if they can help with this error.
