### ISSUE TITLE
GracefulStopTest fails on Windows

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#561]
The `GracefulStopTest#testGracefulComplete()` fails with the following

```plain
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

2016-05-10 13:51:14.566:INFO::main: Logging initialized @420ms
2016-05-10 13:51:14.783:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2016-05-10 13:51:14.827:INFO:oejs.AbstractConnector:main: Started ServerConnector@3abfe836{HTTP/1.1,[http/1.1]}{0.0.0.0:55068}
2016-05-10 13:51:14.828:INFO:oejs.Server:main: Started @682ms
java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Thread.sleep(Native Method)
	at org.eclipse.jetty.server.GracefulStopTest$1.run(GracefulStopTest.java:235)
2016-05-10 13:51:24.933:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@3abfe836{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
```

This is the line it fails on ...

https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/test/java/org/eclipse/jetty/server/GracefulStopTest.java#L235

This smells like the old Java timer resolution issue on Windows

**Comment by gregw** [comment]
Strange, as it uses nanotime which should not go backwards.  Anyway, added Max(1,end-now) to the timer.
