### ISSUE TITLE
Distro argument --list-all-modules does not work

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#5679]
**jetty-10.0.x**

[938] java -jar ../jetty-home/start.jar --list-all-modules

Modules [*]:
============
java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$1.remove(Collections.java:4712)
	at java.base/java.util.AbstractCollection.remove(AbstractCollection.java:299)
	at org.eclipse.jetty.start.Modules.listModules(Modules.java:173)
	at org.eclipse.jetty.start.Main.listModules(Main.java:268)
	at org.eclipse.jetty.start.Main.start(Main.java:408)
	at org.eclipse.jetty.start.Main.main(Main.java:78)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information

**Comment by joakime** [comment]
were you in a jetty.base when you ran that?
I cannot replicate with `jetty-10.0.x` head.

**Comment by gregw** [comment]
I replicated this in a fresh base with http and deploy enabled
