### ISSUE TITLE
Failure in RoundRobinConnectionPoolTest.testRoundRobin([5] FCGI)

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5687]
**Jetty version**
jetty-10.0.x HEAD

**Description**
Stacktrace
```
java.lang.AssertionError: 
HttpClient@69fd1522{STARTED} - STARTED
+= HttpClientTransportOverFCGI@74a65d54{STARTED} - STARTED
|  += ClientConnector@49f116d9{STARTED} - STARTED
|     += QueuedThreadPool[client]@1e414c99{STARTED,8<=8<=200,i=6,r=1,q=0}[ReservedThreadExecutor@1d268d97{s=1/1,p=0}] - STARTED
|     |  += ReservedThreadExecutor@1d268d97{s=1/1,p=0} - STARTED
|     |  +> threads size=8
|     |  |  +> client-12166 TIMED_WAITING tid=12166 prio=5 RESERVED
|     |  |  +> client-12170 TIMED_WAITING tid=12170 prio=5 IDLE
|     |  |  +> client-12167 RUNNABLE tid=12167 prio=5 SELECTING
|     |  |  +> client-12169 TIMED_WAITING tid=12169 prio=5 IDLE
|     |  |  +> client-12168 TIMED_WAITING tid=12168 prio=5 IDLE
|     |  |  +> client-12164 TIMED_WAITING tid=12164 prio=5 IDLE
|     |  |  +> client-12171 TIMED_WAITING tid=12171 prio=5 IDLE
|     |  |  +> client-12165 TIMED_WAITING tid=12165 prio=5 IDLE
|     |  +> jobs size=0
|     +- org.eclipse.jetty.io.MappedByteBufferPool@76e87fa0
|     += ScheduledExecutorScheduler@3062c0d4{STARTED} - STARTED
|     |  +> java.base@11.0.9/jdk.internal.misc.Unsafe.park(Native Method)
|     |  +> java.base@11.0.9/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
|     |  +> java.base@11.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
|     |  +> java.base@11.0.9/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
|     |  +> java.base@11.0.9/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
|     |  +> java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
|     |  +> java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
|     |  +> java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
|     |  +> java.base@11.0.9/java.lang.Thread.run(Thread.java:834)
|     += Client@71644fdf[provider=null,keyStore=null,trustStore=null] - STARTED
|     |  +> trustAll=false
|     |  +> Protocol Selections
|     |  |  +> Enabled size=4
|     |  |  |  +> TLSv1
|     |  |  |  +> TLSv1.1
|     |  |  |  +> TLSv1.2
|     |  |  |  +> TLSv1.3
|     |  |  +> Disabled size=2
|     |  |     +> SSLv2Hello - ConfigExcluded:'SSLv2Hello'
|     |  |     +> SSLv3 - ConfigExcluded:'SSLv3' JVM:disabled
|     |  +> Cipher Suite Selections
|     |     +> Enabled size=27
|     |     |  +> TLS_AES_128_GCM_SHA256
|     |     |  +> TLS_AES_256_GCM_SHA384
|     |     |  +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
|     |     |  +> TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
|     |     |  +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
|     |     |  +> TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
|     |     |  +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
|     |     |  +> TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
|     |     |  +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
|     |     |  +> TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
|     |     |  +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
|     |     |  +> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
|     |     |  +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
|     |     |  +> TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
|     |     |  +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
|     |     |  +> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
|     |     |  +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
|     |     |  +> TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
|     |     |  +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
|     |     |  +> TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
|     |     |  +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
|     |     |  +> TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
|     |     |  +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
|     |     |  +> TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
|     |     |  +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
|     |     |  +> TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
|     |     |  +> TLS_EMPTY_RENEGOTIATION_INFO_SCSV
|     |     +> Disabled size=18
|     |        +> TLS_DHE_DSS_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_DHE_DSS_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_DHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_DHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_ECDH_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_ECDH_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
|     |        +> TLS_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$'
|     |        +> TLS_RSA_WITH_AES_128_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|     |        +> TLS_RSA_WITH_AES_128_GCM_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|     |        +> TLS_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$', ConfigExcluded:'^TLS_RSA_.*$'
|     |        +> TLS_RSA_WITH_AES_256_CBC_SHA256 - ConfigExcluded:'^TLS_RSA_.*$'
|     |        +> TLS_RSA_WITH_AES_256_GCM_SHA384 - ConfigExcluded:'^TLS_RSA_.*$'
|     += ClientSelectorManager@58072e51{STARTED} - STARTED
|        += ManagedSelector@6d275f8e{STARTED} id=0 keys=0 selected=0 updates=0 - STARTED
|           += EatWhatYouKill@4be5469e/SelectorProducer@182ce28a/PRODUCING/p=false/QueuedThreadPool[client]@1e414c99{STARTED,8<=8<=200,i=6,r=1,q=0}[ReservedThreadExecutor@1d268d97{s=1/1,p=0}][pc=0,pic=0,pec=1,epc=5]@2020-11-18T21:49:13.159094Z - STARTED
|           |  +- SelectorProducer@182ce28a
|           |  +~ QueuedThreadPool[client]@1e414c99{STARTED,8<=8<=200,i=6,r=1,q=0}[ReservedThreadExecutor@1d268d97{s=1/1,p=0}] - STARTED
|           +> updates @ 2020-11-18T21:49:13.158875Z size=0
|           +> keys @ 2020-11-18T21:49:13.158979Z size=0
+- org.eclipse.jetty.client.ProtocolHandlers@79b82278
|  +> java.util.LinkedHashMap@29ed4841{size=5}
|     +@ continue = org.eclipse.jetty.client.ContinueProtocolHandler@2eb4d9ee
|     +@ redirect = org.eclipse.jetty.client.RedirectProtocolHandler@4f04ab10
|     +@ www-authenticate = org.eclipse.jetty.client.WWWAuthenticationProtocolHandler@30c338c8
|     +@ proxy-authenticate = org.eclipse.jetty.client.ProxyAuthenticationProtocolHandler@8d0774a
|     +@ upgrade = org.eclipse.jetty.client.UpgradeProtocolHandler@a3b417
+- org.eclipse.jetty.client.HttpClient$ContentDecoderFactorySet@6a15d338(size=1)
|  +: org.eclipse.jetty.client.GZIPContentDecoder$Factory@30a95a
+- org.eclipse.jetty.util.SocketAddressResolver$Sync@4339a3ca
+= HttpDestination[Origin@678872d7[http://localhost:42695,tag=null,protocol=Protocol@92001cc9[proto=[fastcgi/1.1],nego=false]]]@4858e6c0,queue=0,pool=RoundRobinConnectionPool@55c6e0d0[c=0/0/3,a=0,i=0] - STARTED
|  += RoundRobinConnectionPool@55c6e0d0[c=0/0/3,a=0,i=0] - STARTED
|  |  +- Pool@118e6543[size=0 closed=false pending=0]
|  |     +> entries size=0
|  +> exchanges size=0
+> requestListeners size=0
key: +- bean, += managed, +~ unmanaged, +? auto, +: iterable, +] array, +@ map, +> undefined
[41240, 41238, 41244, 41246, 41248]
Expected: <41246>
     but: was <41240>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.eclipse.jetty.http.client.RoundRobinConnectionPoolTest.testRoundRobin(RoundRobinConnectionPoolTest.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:92)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:212)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:192)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:139)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:107)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:107)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:42)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```
Standard Error
```
Running org.eclipse.jetty.http.client.RoundRobinConnectionPoolTest.testRoundRobin([5] FCGI)
2020-11-18 21:49:13.128:INFO :oejs.Server:main: jetty-10.0.0-SNAPSHOT; built: 2020-11-18T21:17:11.375Z; git: 899e5fc0f9ba40e95bd4bc6000aa8464b5d738b6; jvm 11.0.9+11
2020-11-18 21:49:13.131:INFO :oejs.AbstractConnector:main: Started ServerConnector@7fc6a598{fcgi/1.0, (fcgi/1.0)}{0.0.0.0:42695}
2020-11-18 21:49:13.131:INFO :oejs.Server:main: Started Server@1f50d106{STARTING}[10.0.0-SNAPSHOT,sto=0] @602273ms
2020-11-18 21:49:13.162:INFO :oejs.Server:main: Stopped Server@1f50d106{STOPPING}[10.0.0-SNAPSHOT,sto=0]
2020-11-18 21:49:13.162:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@7fc6a598{fcgi/1.0, (fcgi/1.0)}{0.0.0.0:0}
```

**Comment by sbordet** [comment]
Fixed by 9caabea.
