### ISSUE TITLE
Test MavenLocalRepoFileInitializerTest#testDownloadSnapshotRepoWithExtractDefault should not depends on external resources

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#5727]
if  https://oss.sonatype.org is not available the test is broken...

```
java.io.IOException: URL GET Failure [502/Bad Gateway] on https://oss.sonatype.org/content/repositories/jetty-snapshots/org/eclipse/jetty/test-jetty-webapp/11.0.0-SNAPSHOT/maven-metadata.xml
	at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:147)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileInitializer.download(MavenLocalRepoFileInitializer.java:303)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileInitializer.create(MavenLocalRepoFileInitializer.java:159)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileInitializerTest.testDownloadSnapshotRepoWithExtractDefault(MavenLocalRepoFileInitializerTest.java:262)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
```

**Comment by joakime** [comment]
Add the `@Tag("External")` to that test.

**Comment by olamy** [comment]
might be better to use the local repo to get the artifacts?
