### ISSUE TITLE
ArithmeticException "/ by zero" from jetty-util pool

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#5731]
**Jetty version**
10.0.x

**Description**
Was working on some WebSocket test and got this error from the `ConnectionPool`
```
java.lang.ArithmeticException: / by zero
	at org.eclipse.jetty.util.Pool.acquire(Pool.java:253)
	at org.eclipse.jetty.client.AbstractConnectionPool.activate(AbstractConnectionPool.java:276)
	at org.eclipse.jetty.client.AbstractConnectionPool.acquire(AbstractConnectionPool.java:183)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:317)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:306)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:299)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:276)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:253)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:560)
	at org.eclipse.jetty.client.HttpRequest.sendAsync(HttpRequest.java:823)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:810)
	at org.eclipse.jetty.websocket.core.client.CoreClientUpgradeRequest.send(CoreClientUpgradeRequest.java:197)
	at org.eclipse.jetty.websocket.core.client.CoreClientUpgradeRequest.sendAsync(CoreClientUpgradeRequest.java:202)
	at org.eclipse.jetty.websocket.core.client.WebSocketCoreClient.connect(WebSocketCoreClient.java:101)
	at org.eclipse.jetty.websocket.javax.client.internal.JavaxWebSocketClientContainer.connect(JavaxWebSocketClientContainer.java:133)
	at org.eclipse.jetty.websocket.javax.client.internal.JavaxWebSocketClientContainer.connect(JavaxWebSocketClientContainer.java:192)
	at org.eclipse.jetty.websocket.javax.client.internal.JavaxWebSocketClientContainer.connectToServer(JavaxWebSocketClientContainer.java:244)
	at org.eclipse.jetty.websocket.javax.tests.server.PrimitivesBinaryEchoTest.testPrimitiveEcho(PrimitivesBinaryEchoTest.java:145)
```

**Comment by lorban** [comment]
This can happen when the pool is in the middle of acquiring a connection while another thread removes the last one from the pool.

The fix is to simply add a `if (size == 0) return null;` check.

**Comment by marcphilipp** [comment]
Any chance this can get backported to 9.4.x?

**Comment by marcphilipp** [comment]
I did some digging. Looks like this was broken in ba22c08fde5362fe2e89e9c417d2a90658c74283 which was released in 9.4.32.v20200930.

@lorban Could you please backport this change to 9.4.x? We'll be stuck on JDK 8 for a while and hence cannot upgrade to 10.0.x or 11.0.x.

**Comment by joakime** [comment]
@marcphilipp the Pool on 9.4.35.v20201120 (which is in maintenance mode) is not the same as the Pool on 10.0.0 (active development branch).
It's a completely different codebase.
This issue isn't really possible on 9.4.x, as the cause of the divide by zero was the result of a throwable from the use of the Trie in 10, (9.4.x's Pool doesn't use Trie)

If you are having an issue, please open a new issue, with the details you are experiencing.

**Comment by marcphilipp** [comment]
Thanks for the reply! It looked so similar that I apparently didn't look closely enough.

I've now raised #5819 for 9.4.x.
