### ISSUE TITLE
Unusually high amount of ManagedSelector$$Lambda instances

### ISSUE THREAD

**Issue by chietti** [eclipse/jetty.project#5749]
**Jetty version**
9.4.30 (embedded)

**Java version**
OpenJDK 64-Bit Server VM, Version: 11.0.8, Vendor: AdoptOpenJDK

**Question**
I formulate this as a question since I cannot rule out a problem with our own setup but would like to get some more insight into the Jetty code in this area.

After an internal system update we observed a big increase in active Jetty threads being shown by our threadpool monitoring although nothing has changed on our side. Java and Jetty version are the same, configuration also did not change.

I took some thread dumps and observed that in addition to the normal threads in the ReservedThreadExecutor we now see also a lot of threads "busy" in this state:

```
"jetty-134" #134 daemon prio=5 os_prio=0 cpu=2.09ms elapsed=776857.88s tid=0x00007f5371852800 nid=0xa50f runnable  [0x00007f538ccf5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.8/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.8/Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.8/Unknown Source)
	- locked <0x00007f56e86728a0> (a sun.nio.ch.Util$2)
	- locked <0x00007f56e8672690> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.8/Unknown Source)
	at org.eclipse.jetty.io.ManagedSelector.nioSelect(ManagedSelector.java:149)
	at org.eclipse.jetty.io.ManagedSelector.select(ManagedSelector.java:156)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:572)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:509)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$7537/0x00007f538c3f7058.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(java.base@11.0.8/Unknown Source)
```

As far as I understand the Jetty code this is the initial setup of the ManagedSelector when the Jetty server is started (doStart() where the lambda is executed). Btw: Its interesting that all of these threads have literally no cpu time (as seen in the snippet above).

The total number of these thread states is equal to half of the number of CPU cores in the systems I checked (e.g. we have a system with 176 cores and I see 88 threads in this state - this never changes even after more than 2 weeks). 

But shouldn't the amount of lambdas be limited by the max threads in the QueuedThreadPool we are using (also the  configuration has not changed here)? We use (and always used) a QueuedThreadPool with max. 200 Threads so the maximum number of these lambdas should be 12 per SelectorManager, right?

Can you think of any scenario where this number is so much higher?

The only thing I can come up with is that the "instanceof" check in SelectorManager does not work anymore although we use the default QueuedThreadPool which implements this interface. We are still investigating of this could be a ClassLoader problem.

```
> private static int defaultSelectors(Executor executor)
>     {
>         if (executor instanceof ThreadPool.SizedThreadPool)
>         {
>             int threads = ((ThreadPool.SizedThreadPool)executor).getMaxThreads();
>             int cpus = ProcessorUtils.availableProcessors();
>             return Math.max(1, Math.min(cpus / 2, threads / 16));
>         }
>         return Math.max(1, ProcessorUtils.availableProcessors() / 2);
>     }
```

Can you confirm that although those threads are showing as "busy" by the pool they are actually waiting for input and are not somehow stuck or blocked? We did not observe any changes in responsiveness or throughput yet.

Thanks,
Stefan

**Comment by sbordet** [comment]
@chietti it's very strange and yes, it may be a class loader issue.

The selector threads are shown as `RUNNABLE` but in fact are blocked in the `select()` operation -- this is expected and normal.

**Comment by chietti** [comment]
Shouldn't all of these thread states disappear over time and switch to states where the thread is executing a ReservedThread?
Like this:
```
"jetty-65104" #65104 daemon prio=5 os_prio=0 cpu=111585.18ms elapsed=14307.38s tid=0x00007f9b703d1000 nid=0xa2b83 runnable  [0x00007f904bbfa000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.8/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.8/Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.8/Unknown Source)
	- locked <0x00007f9dc20d6b68> (a sun.nio.ch.Util$2)
	- locked <0x00007f9dc20d6ad8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.8/Unknown Source)
	at org.eclipse.jetty.io.ManagedSelector.nioSelect(ManagedSelector.java:149)
	at org.eclipse.jetty.io.ManagedSelector.select(ManagedSelector.java:156)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:572)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:509)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(java.base@11.0.8/Unknown Source)
```

This btw has a lot of CPU time on it.

ReservedThreads  are handled specifically in the QueuedThreadPool when we ask it for the "busy" threads in our monitoring.

**Comment by sbordet** [comment]
> Shouldn't all of these thread states disappear over time and switch to states where the thread is executing a ReservedThread?

No, why you think so?

The thread state depends on what the thread is doing, so if it's selecting it's selecting and the state would be that of the selecting operation.

> ReservedThreads are handled specifically in the QueuedThreadPool when we ask it for the "busy" threads in our monitoring.

Yes, see #2568.

**Comment by chietti** [comment]
As far as I understand the EatWhatYouKill strategy I think that at some point the initial lambda execution would end since it runs into an EPC scenario where it dispatches a new thread and handles the job itself. Then the new thread would do the select but it would not stem from the initial lambda execution but from the ReservedThreadExecutor as seen in the second thread dump snippet:

```
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
```
vs.
```
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$7537/0x00007f538c3f7058.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
```

It sounds nitpicky, it's still doing the same (namely select) but in terms of being considered "busy" by the QueuedThreadPool it is treated differently.

**Comment by jmcc0nn3ll** [comment]
@chietti Since we are going into final releases of Jetty 10 and 11 soon, let me know if you are interested in having a google hangout to discuss and make sure there isn't something we are missing here.  Ping me at jesse@webtide.com and I'll get it set up.

**Comment by chietti** [comment]
Hi Jesse, thanks for the invitation but I don't think that there is something wrong with Jetty in this case. I wanted to get some more insight into the internal behavior to get a clue on what must have changed in our own environment for Jetty to behave that way. As I mentioned we did not change anything in the Jetty environment at all (Jetty version and configuration, Java version, etc.) so I am sure the root cause comes from somewhere else. I read the webtide article about EatWhatYouKill (very helpful) and now am at least sure that the many Selectors we see are still handling jobs and are not somehow stuck and not available anymore. We can fix the problem by manually configuring the selectors but still I really want to know the reason for the change in behavior.
