### ISSUE TITLE
NullPointerException raised when server shutdown

### ISSUE THREAD

**Issue by quaff** [eclipse/jetty.project#5782]
**Jetty version**
works fine with `jetty-all-9.4.20.v20190813-uber.jar` and previous version
broken since `jetty-all-9.4.21.v20190926-uber.jar`

**Description**
I'm using `jetty-all` to build a runnable WAR, It's a bit difficult for me to provide a minimized reproducible example, paste code instead, hope it will helps.
```java
import java.io.File;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.URL;

import org.eclipse.jetty.annotations.AnnotationConfiguration;
import org.eclipse.jetty.security.ConstraintSecurityHandler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.StatisticsHandler;
import org.eclipse.jetty.servlet.DefaultServlet;
import org.eclipse.jetty.servlet.ErrorPageErrorHandler;
import org.eclipse.jetty.servlet.ServletHandler;
import org.eclipse.jetty.servlet.ServletHandler.Default404Servlet;
import org.eclipse.jetty.util.thread.QueuedThreadPool;
import org.eclipse.jetty.webapp.Configuration;
import org.eclipse.jetty.webapp.JettyWebXmlConfiguration;
import org.eclipse.jetty.webapp.WebAppContext;
import org.eclipse.jetty.webapp.WebInfConfiguration;

public class JettyLauncher {

	public static void start(URL warUrl) throws Exception {
		int port = -1;
		String p = System.getProperty("port.http");
		if (p == null)
			p = System.getProperty("jetty.http.port");
		if (p != null && p.trim().length() > 0)
			port = Integer.parseInt(p);
		if (port == -1) {
			port = 8080;
			if (System.getenv("CONTAINER") == null) {
				while (getTempDirectory(port).exists() || !isAvailable(port))
					port++;
				System.setProperty("port.http", String.valueOf(port));
			}
		}
		File tempDir = getTempDirectory(port);
		tempDir.mkdirs();
		Server server = new Server(port);
		server.addBean(new QueuedThreadPool(Integer.getInteger("jetty.maxThreads", 200)));
		Configuration.ClassList classlist = Configuration.ClassList.setServerDefault(server);
		classlist.addBefore(JettyWebXmlConfiguration.class.getName(), AnnotationConfiguration.class.getName());
		WebAppContext context = new WebAppContext(null, new ConstraintSecurityHandler(), new ServletHandler(),
				new ErrorPageErrorHandler());
		String webInfoJarPattern = System.getProperty(WebInfConfiguration.WEBINF_JAR_PATTERN);
		if (webInfoJarPattern == null)
			webInfoJarPattern = ".*/ironrhino-[^/]*\\.jar$";
		if (!webInfoJarPattern.isEmpty())
			context.setAttribute(WebInfConfiguration.WEBINF_JAR_PATTERN, webInfoJarPattern);
		context.setContextPath("/");
		context.setInitParameter(DefaultServlet.CONTEXT_INIT + "dirAllowed", "false");
		String webappDir = System.getProperty("webapp.dir");
		if (webappDir != null) {
			context.setWar(webappDir);
			System.out.println("Webapp - " + webappDir);
		} else if (warUrl != null) {
			context.setWar(warUrl.toExternalForm());
			System.out.println("War - " + warUrl.getPath());
			System.setProperty("executable-war", warUrl.getPath());
		}
		context.setTempDirectory(tempDir);
		context.addServlet(context.addServlet(Default404Servlet.class, "*.class"), "/BOOT-INF/*");
		context.setServer(server);
		StatisticsHandler statisticsHandler = new StatisticsHandler();
		statisticsHandler.setHandler(context);
		server.setHandler(statisticsHandler);
		server.setStopAtShutdown(true);
		server.start();
		server.join();
	}

	private static File getTempDirectory(int port) {
		return new File(new File(System.getProperty("user.home")), ".jetty" + port);
	}

	private static boolean isAvailable(int port) {
		try (ServerSocket ignored = new ServerSocket(port)) {
			return true;
		} catch (IOException e) {
			return false;
		}
	}

}
```
It will raise NPE when server shutdown, stack trace is base on latest `9.4.35.v20201120`
```
WARN:oejs.ServletHandler:JettyShutdownThread: EXCEPTION 
java.lang.NullPointerException
	at org.eclipse.jetty.servlet.ListenerHolder.doStop(ListenerHolder.java:114)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:329)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:108)
	at org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:437)
	at org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:425)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:108)
	at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:1061)
	at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:386)
	at org.eclipse.jetty.webapp.WebAppContext.stopWebapp(WebAppContext.java:1462)
	at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1428)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1115)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:297)
	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:547)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:108)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStop(StatisticsHandler.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:108)
	at org.eclipse.jetty.server.Server.doStop(Server.java:470)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:128)

```

**Comment by quaff** [comment]
Any clue?

**Comment by joakime** [comment]
Just so you know, we maintain an example project that builds a live war file using embedded Jetty properly.
And it doesn't use jetty-all (which is deprecated, and fully removed in Jetty 10.0.0+)

See: https://github.com/jetty-project/embedded-jetty-live-war

**Comment by gregw** [comment]
I can kind of see something wrong in ContextHandler.doScope, but I can't make a reproduction so I can't be sure.
Anything you can tell us about your webapp with regards to listeners and servlet container initializers?

**Comment by gregw** [comment]
@quaff can you look at #5836 and try it against your usage.   It may fix the problem but without a reproduction I can't be sure.

**Comment by quaff** [comment]
You remind me, I'm hacking threadLocals on `ServletContextListener::contextDestroyed` to eliminate tomcat warnings, I will fix it, thanks for your help.
