### ISSUE TITLE
UnrecoverableKeyException when upgrading from 9.3.8.v20160314 to 9.3.9.v20160517

### ISSUE THREAD

**Issue by annorax** [eclipse/jetty.project#583]
The very same configuration and keyfile that work with 9.3.8 fail with 9.3.9. Here are the properties that I've configured:

```java
jetty.http.port=80
jetty.httpConfig.securePort=443
jetty.ssl.port=443
jetty.sslContext.keyStorePath=???
jetty.sslContext.keyStorePassword=???
jetty.sslContext.keyStoreType=PKCS12
jetty.sslContext.trustStorePath=???
jetty.sslContext.trustStorePassword=???
jetty.sslContext.trustStoreType=PKCS12
```

And here is the stack trace of the exception thrown on app start:

```java
2016-05-22 03:03:27.092:INFO:oejs.Server:main: jetty-9.3.9.v20160517
2016-05-22 03:03:27.117:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/jetty/webapps/] at interval 1
2016-05-22 03:03:27.165:INFO:oejs.AbstractConnector:main: Started ServerConnector@33bfd931{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2016-05-22 03:03:27.265:INFO:oejus.SslContextFactory:main: x509=X509@724af044(1,h=[???],w=[???]) for SslContextFactory@4678c730(file:///???,file:///???)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
	at org.eclipse.jetty.start.Main.start(Main.java:457)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: java.security.UnrecoverableKeyException: Get Key failed: Given final block not properly padded
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:410)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1078)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:381)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:260)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:390)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
	... 7 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:966)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824)
	at com.sun.crypto.provider.PKCS12PBECipherCore.implDoFinal(PKCS12PBECipherCore.java:399)
	at com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndDESede.engineDoFinal(PKCS12PBECipherCore.java:431)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:348)
	... 29 more

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information

```

**Comment by sbordet** [comment]
I think you have some other problem.

For example, read this: http://stackoverflow.com/questions/8049872/given-final-block-not-properly-padded.

We need more evidence to consider this a Jetty bug. If you have, please reopen or file a new issue with a reproducible test case.
