### ISSUE TITLE
Used Http Keep-Alive，Jetty Throw ClosedChannelException And Close Connection

### ISSUE THREAD

**Issue by james-z-repo** [eclipse/jetty.project#5849]
**Jetty version**
9.4.19.v20190610
**Java version**
1.8
**OS type/version**
centos6.5
**Description**

1、I used http/1.1 keep-alive with jetty，i got a error with :
```
20:42:29.255 [qtp388043093-233] DEBUG org.eclipse.jetty.server.HttpChannel - Could not perform ERROR dispatch, aborting
java.lang.IllegalStateException: Committed
	at org.eclipse.jetty.server.HttpChannel.resetBuffer(HttpChannel.java:930)
	at org.eclipse.jetty.server.HttpOutput.resetBuffer(HttpOutput.java:1080)
	at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1100)
	at org.eclipse.jetty.server.Response.resetForForward(Response.java:1093)
	at org.eclipse.jetty.server.Response.reset(Response.java:1042)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:415)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
20:42:29.267 [qtp388043093-233] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@6b5d717d{IDLE}->null
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:492)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353)
	at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:215)
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175)
	at org.eclipse.jetty.server.HttpConnection.abort(HttpConnection.java:570)
	at org.eclipse.jetty.server.HttpChannel.abort(HttpChannel.java:968)
	at org.eclipse.jetty.server.HttpChannelOverHttp.abort(HttpChannelOverHttp.java:495)
	at org.eclipse.jetty.server.HttpChannel.minimalErrorResponse(HttpChannel.java:656)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:453)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
```
2、i have a tcpdump is:

![image](https://user-images.githubusercontent.com/33625419/103396086-15d89a00-4b6c-11eb-8ac9-c5e756b7e4e8.png)

my question is: 
Q1 : Why should the server close HTTPS long connections after reporting an error of 500, rather than keep HTTP long connections open?

Q2: Why didn't the client be notified to stop using the HTTP1.1 long connection after the server closed the connection?
According to RFC2616, when the server actively closes an HTTP long connection, the client needs to be notified that the long connection is no longer being used。
```
 If the server chooses to close the connection immediately after sending the response, it SHOULD send a Connection header including the connection-token close.
```

https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html

**Comment by sbordet** [comment]
Can you please upgrade to Jetty 9.4.35 and see if the issue is still present?

Also please post the full DEBUG logs, so that we have a better context of what request actually failed.

**Comment by joakime** [comment]
You are using HTTP/1.1 per your pcap.

That means you as subject to RFC7230 specs (not the obsoleted RFC2616 spec, which was rendered obsolete back in June 2014)
The up to date specs, point out that the header `Connection: keep-alive` is meaningless. (the token `keep-alive` is not used on HTTP/1.1, that's a HTTP/1.0 token)
See:
 * https://tools.ietf.org/html/rfc2616 - obsolete HTTP/1.1 spec (see top header for list of replacement specs)
 * https://tools.ietf.org/html/rfc7230 - current HTTP/1.1 spec

One interesting note, Jetty doesn't put a `Cache-Control` header on it's unhandled 500 errors. (in fact, it does the opposite, it specifically removes `Cache-Control` header on error responses that Jetty itself produces, as a result of the the [resetContent](https://github.com/eclipse/jetty.project/blob/jetty-9.4.35.v20201120/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java#L1178-L1205) during [the send error logic](https://github.com/eclipse/jetty.project/blob/jetty-9.4.35.v20201120/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L408-L416))

Jetty will only add a `Connection: close` header on HTTP/1.1 error responses (not HTTP/1.0 or HTTP/2) if it's handling the error, not the application, and the connection cannot remain persistent. (such as the application not reading the entire request body content).   The 500 status code alone isn't special enough to warrant a `Connection: close` on the response headers.

The fact that Jetty saw a `ClosedChannelException` and then closed the connection wouldn't generate a 500 response to the client (from Jetty's point of view, there's no connection to generate a response to)

What is this `Server: Tas v2.8.9`?  A proxy? a load balancer? (if so, then it's that server's responsibility to put the `Connection: close` header on connection issues)

**Comment by james-z-repo** [comment]
on the http/1.1, When will Jetty send a Connection: close on the Response Headers ? I want debug to look at the code

And，I have a question, jetty close the tcp connection(when request have keep-alive), why jetty did't send ```connection: close``` header ? 

Tas v2.8.9 is i changed jetty's header

**Comment by sbordet** [comment]
@zhengshundong01 the answer to your questions will be just guesses and we won't proceed at solving this issue.
Can you reproduce the issue? Do you have DEBUG logs? The DEBUG logs will tell us what happened.

What _could_ have happened is the following:

* The application received the `/getToken` request.
* The application itself replied with a 500 explicitly (Jetty does not add "Request failed." as the response message, so it must be an application doing that).
* The 500 response from the application is flushed, but its final processing causes an error (or the application causes an error) that is caught by Jetty, which sees that the response is already committed and therefore cannot add the `Connection: close` header, but does close the connection.
* The client tries to reuse a closed connection, so for the last request Jetty never receives the request bytes (you should a TCP RST in wireshark).

**Comment by janbartel** [comment]
@zhengshundong01 has you question been answered? If so, please go ahead and close the issue. If not, please provide the information requested otherwise we can't progress this issue.
