### ISSUE TITLE
NullPointerException when calling Request.getParameterNames()

### ISSUE THREAD

**Issue by chietti** [eclipse/jetty.project#5878]
**Jetty version**
9.4.35 (embedded)

**Java version**
OpenJDK 64-Bit Server VM, Version: 11.0.8, Vendor: AdoptOpenJDK

**OS type/version**
Linux 

**Description**

We observed this NPE once in one of our automated test setups:

```
 18:31:16.516 [Collector] INFO  Collector : java.lang.NullPointerException
 18:31:16.516 [Collector] INFO  Collector : 	at org.eclipse.jetty.server.Request.getParameters(Request.java:456)
 18:31:16.516 [Collector] INFO  Collector : 	at org.eclipse.jetty.server.Request.getParameterNames(Request.java:1090)
 18:31:16.516 [Collector] INFO  Collector : 	at javax.servlet.ServletRequestWrapper.getParameterNames(ServletRequestWrapper.java:212)
 18:31:16.516 [Collector] INFO  Collector : 	at com.compuware.apm.communication.api.RequestForwarderUtil.copyQueryParameters(RequestForwarderUtil.java:92)
 18:31:16.516 [Collector] INFO  Collector : 	at com.compuware.apm.communication.RestRequestForwarderImpl.setupHttpRequest(RestRequestForwarderImpl.java:165)
 18:31:16.516 [Collector] INFO  Collector : 	at com.compuware.apm.communication.RestRequestForwarderImpl.internalSend(RestRequestForwarderImpl.java:126)
 18:31:16.516 [Collector] INFO  Collector : 	at com.compuware.apm.communication.RestRequestForwarderImpl.internalForward(RestRequestForwarderImpl.java:106)
 18:31:16.516 [Collector] INFO  Collector : 	at com.compuware.apm.communication.RestRequestForwarderImpl.forward(RestRequestForwarderImpl.java:85)
 18:31:16.516 [Collector] INFO  Collector : 	at com.compuware.apm.collector.rest.resource.tenantspecific.RestRequestForwarderUtilImpl.forward(RestRequestForwarderUtilImpl.java:58)
 18:31:16.517 [Collector] INFO  Collector : 	at com.compuware.apm.collector.rest.resource.tenantspecific.DeploymentResource.lambda$getAgentInstallerAvailableVersions$1(DeploymentResource.java:275)
 18:31:16.517 [Collector] INFO  Collector : 	at com.compuware.apm.rest.shared.api.util.AsyncResponseExecutorImpl$Builder$AsyncResponseExecutorTask.run(AsyncResponseExecutorImpl.java:167)
 18:31:16.517 [Collector] INFO  Collector : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 18:31:16.517 [Collector] INFO  Collector : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 18:31:16.517 [Collector] INFO  Collector : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 18:31:16.517 [Collector] INFO  Collector : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 18:31:16.517 [Collector] INFO  Collector : 	at java.lang.Thread.run(Thread.java:748)
```

The request is handled asynchronously in a worker thread (as seen in the stack above). To me it looks like the request is recycled in between these calls in **org.eclipse.jetty.server.Request.getParameters()**:

```
...
        if (_queryParameters == null)
        {
            try
            {
                extractQueryParameters();
            }
            catch (IllegalStateException | IllegalArgumentException e)
            {
                throw new BadMessageException("Unable to parse URI query", e);
            }
        }

 ========== "recycle" called ? ==========

        // Do parameters need to be combined?
        if (isNoParams(_queryParameters) || _queryParameters.size() == 0)
            _parameters = _contentParameters;

```

**Comment by janbartel** [comment]
@chietti  how is the Request passed into your async handling code? Is it obtained from javax.servlet.ServletRequest.startAsync() or javax.servlet.ServletRequest.startAsync(ServletRequest,ServletResponse)? Or are you holding a reference to the original Request and accessing that?  There's not enough jetty code references in the stacktrace to be diagnostic, so you'll have to provide more information around how your code is accessing the request.

**Comment by chietti** [comment]
Hard to say. The request is injected by Jersey since it is a REST resource. The resource looks like this:

```
@GET
@Path("<some path>")
@Produces(APPLICATION_JSON)
public void getSomething(
		@Suspended final AsyncResponse asyncResponse,
		@Context final RequestContext requestContext,
		@Context final HttpServletRequest request) {
	...
}
```

I will follow up with our REST framework team to get info about how Jersey is doing the whole async request injection

**Comment by gregw** [comment]
@chietti I do not believe it is safe to call most request methods asynchronously because not only can the request be recycled, it can change significantly with regards to servletPaths and pathInfos etc.

Best practise is to extract the information you need from the request before starting the async processing.    Or alternately defer the call to AsyncContext.complete to the async thread so that at least recycling cannot happen whilst async thread is acting.

If the async thread is just racing against the completion of the request normally, then that is an application bug.  Re-open you think I have analysed incorrectly.

**Comment by chietti** [comment]
sounds plausible, thanks!
