### ISSUE TITLE
CDI tests broken in Java 16

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#5885]
**Jetty version**
9.4.x

**Description**
Since Java 16-ea-28 deep reflection on Java classes is forbidden, and Weld wants to call `protected ClassLoader.defineClass()`.

```
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @554e218
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.jboss.weld.util.bytecode.ClassFileUtils$1.run(ClassFileUtils.java:67)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.jboss.weld.util.bytecode.ClassFileUtils.makeClassLoaderMethodsAccessible(ClassFileUtils.java:60)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.jboss.weld.bootstrap.WeldStartup.startContainer(WeldStartup.java:220)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.jboss.weld.bootstrap.WeldBootstrap.startContainer(WeldBootstrap.java:72)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.jboss.weld.bootstrap.WeldBootstrap.startContainer(WeldBootstrap.java:67)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:183)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:62)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:137)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:54)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:368)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1316)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:862)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:305)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
2021-01-15 16:25:53.089:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:516)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:168)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:430)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:56)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:755)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:721)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:628)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:509)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:140)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:246)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.server.Server.start(Server.java:469)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.server.Server.doStart(Server.java:414)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1839)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1782)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:226)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.start.Main.start(Main.java:502)
2021-01-15 16:25:53.090:INFO :oejtd.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.start.Main.main(Main.java:73)
```

**Comment by sbordet** [comment]
This can be worked around with a command line argument `--illegal-access=debug`.

Or the test can be disabled until Weld fixed the issue.

**Comment by joakime** [comment]
Weld issue is https://issues.redhat.com/browse/WELD-2620 - currently unresolved.
