### ISSUE TITLE
Proxy timeout when downloading file

### ISSUE THREAD

**Issue by ysuei** [eclipse/jetty.project#5896]
**Jetty version**
9.4.35.v20201120

**Java version**
openjdk version "1.8.0_252"

**OS type/version**
OSX 10.15.7

**Description**
When attempting to download a large file from a server, the proxy will timeout with the following exception:

```
2021-01-19 15:56:49.983:DBUG:oeji.ManagedSelector:HttpClient@971d0d8-scheduler-1: Wakeup ManagedSelector@65d09a04{STARTED} id=3 keys=1 selected=0 updates=0
2021-01-19 15:56:49.983:DBUG:oejut.QueuedThreadPool:HttpClient@971d0d8-scheduler-1: queue org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint@f6b1c0c startThread=0
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannelState:HttpClient@971d0d8-scheduler-1: complete HttpChannelState@62575c71{s=WAITING rs=ASYNC os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-19 15:56:49.983:DBUG:oejut.QueuedThreadPool:qtp486898233-24: run org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint@f6b1c0c in QueuedThreadPool[qtp486898233]@1d057a39{STARTED,8<=22<=200,i=0,r=16,q=0}[ReservedThreadExecutor@16022d9d{s=2/16,p=0}]
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannel:HttpClient@971d0d8-scheduler-1: handle http://igor:2101/downloadFile.htm?fn=cov-analysis-macosx-2020.09.sh HttpChannelOverHttp@6668d464{s=HttpChannelState@62575c71{s=WOKEN rs=COMPLETE os=ABORTED is=IDLE awp=false se=false i=false al=0},r=6,c=false/false,a=WOKEN,uri=http://igor:2101/downloadFile.htm?fn=cov-analysis-macosx-2020.09.sh,age=60008} 
2021-01-19 15:56:49.983:DBUG:oeji.ManagedSelector:qtp486898233-33: Selector sun.nio.ch.KQueueSelectorImpl@3434d18b woken with none selected
2021-01-19 15:56:49.983:DBUG:oeji.ManagedSelector:qtp486898233-33: Selector sun.nio.ch.KQueueSelectorImpl@3434d18b woken up from select, 0/0/0 selected
2021-01-19 15:56:49.983:DBUG:oeji.ManagedSelector:qtp486898233-33: Selector sun.nio.ch.KQueueSelectorImpl@3434d18b processing 0 keys, 0 updates
2021-01-19 15:56:49.983:DBUG:oeji.ManagedSelector:qtp486898233-33: updateable 0
2021-01-19 15:56:49.983:DBUG:oeji.ManagedSelector:qtp486898233-33: updates 0
2021-01-19 15:56:49.983:DBUG:oeji.ManagedSelector:qtp486898233-33: Selector sun.nio.ch.KQueueSelectorImpl@3434d18b waiting with 0 keys
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannelState:HttpClient@971d0d8-scheduler-1: handling HttpChannelState@62575c71{s=WOKEN rs=COMPLETE os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannelState:HttpClient@971d0d8-scheduler-1: nextAction(true) COMPLETE HttpChannelState@62575c71{s=HANDLING rs=COMPLETING os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannel:HttpClient@971d0d8-scheduler-1: action COMPLETE HttpChannelOverHttp@6668d464{s=HttpChannelState@62575c71{s=HANDLING rs=COMPLETING os=ABORTED is=IDLE awp=false se=false i=false al=0},r=6,c=false/false,a=HANDLING,uri=http://igor:2101/downloadFile.htm?fn=cov-analysis-macosx-2020.09.sh,age=60008}
2021-01-19 15:56:49.983:DBUG:oeji.ManagedSelector:qtp486898233-24: Destroyed SocketChannelEndPoint@68af3701{l=/127.0.0.1:51106,r=/127.0.0.1:51142,CLOSED,fill=-,flush=-,to=38/30000}{io=0/0,kio=-1,kro=-1}->HttpConnection@2755de5f[p=HttpParser{s=CONTENT,0 of -1},g=HttpGenerator@1638dbc1{s=COMMITTED}]=>HttpChannelOverHttp@6668d464{s=HttpChannelState@62575c71{s=HANDLING rs=COMPLETING os=ABORTED is=IDLE awp=false se=false i=false al=0},r=6,c=false/false,a=HANDLING,uri=http://igor:2101/downloadFile.htm?fn=cov-analysis-macosx-2020.09.sh,age=60008}
2021-01-19 15:56:49.983:DBUG:oejs.HttpOutput:HttpClient@971d0d8-scheduler-1: complete(org.eclipse.jetty.util.Callback$3@2e77a4bb) s=CLOSING,api=BLOCKED,sc=false,e=null s=false e=, c=DirectByteBuffer@6361a189[p=0,l=20220,c=32768,r=20220]={<<<;[VI\x1f\xAc`\xBd\xB5\xF1P\xBe\xEc6KU*\xEc\xA3\xAe03>\x8b\x9d...=\xA9`Z>o\x7f7\xE3\xD6\x01\x93\xCa!\x12\x81\x1fQ\xE3lkL\x0f>>>\xE6zv\xEa\xAe\xA2\xCc\xE0\xE9...\xEc\xD1N\xD9zfo}
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannel:HttpClient@971d0d8-scheduler-1: sendResponse info= content=DirectByteBuffer@6361a189[p=0,l=20220,c=32768,r=20220]={<<<;[VI\x1f\xAc`\xBd\xB5\xF1P\xBe\xEc6KU*\xEc\xA3\xAe03>\x8b\x9d...=\xA9`Z>o\x7f7\xE3\xD6\x01\x93\xCa!\x12\x81\x1fQ\xE3lkL\x0f>>>\xE6zv\xEa\xAe\xA2\xCc\xE0\xE9...\xEc\xD1N\xD9zfo} complete=true committing=false callback=org.eclipse.jetty.server.HttpOutput$WriteCompleteCB@77d41863
2021-01-19 15:56:49.983:DBUG:oeji.AbstractConnection:qtp486898233-24: onClose HttpConnection@2755de5f::SocketChannelEndPoint@68af3701{l=/127.0.0.1:51106,r=/127.0.0.1:51142,CLOSED,fill=-,flush=-,to=38/30000}{io=0/0,kio=-1,kro=-1}->HttpConnection@2755de5f[p=HttpParser{s=CONTENT,0 of -1},g=HttpGenerator@1638dbc1{s=COMMITTED}]=>HttpChannelOverHttp@6668d464{s=HttpChannelState@62575c71{s=HANDLING rs=COMPLETING os=ABORTED is=IDLE awp=false se=false i=false al=0},r=6,c=false/false,a=HANDLING,uri=http://igor:2101/downloadFile.htm?fn=cov-analysis-macosx-2020.09.sh,age=60008}
2021-01-19 15:56:49.983:DBUG:oejut.QueuedThreadPool:qtp486898233-24: ran org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint@f6b1c0c in QueuedThreadPool[qtp486898233]@1d057a39{STARTED,8<=22<=200,i=0,r=16,q=0}[ReservedThreadExecutor@16022d9d{s=2/16,p=0}]
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannel:HttpClient@971d0d8-scheduler-1: Commit failed
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:708)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$300(HttpConnection.java:667)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:526)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:915)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:987)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:284)
	at org.eclipse.jetty.server.HttpOutput.complete(HttpOutput.java:480)
	at org.eclipse.jetty.server.Response.completeOutput(Response.java:926)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:538)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:340)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1520)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1206)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:714)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:72)
	at org.eclipse.jetty.proxy.AbstractProxyServlet.sendProxyResponseError(AbstractProxyServlet.java:749)
	at org.eclipse.jetty.proxy.AbstractProxyServlet.onProxyResponseFailure(AbstractProxyServlet.java:708)
	at org.eclipse.jetty.proxy.ProxyServlet$ProxyResponseListener.onComplete(ProxyServlet.java:233)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:557)
	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:149)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:818)
	at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51)
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-01-19 15:56:49.983:DBUG:oejs.HttpOutput:HttpClient@971d0d8-scheduler-1: onWriteComplete(true,org.eclipse.jetty.io.EofException) s=CLOSING,api=BLOCKED,sc=false,e=null->s=CLOSED,api=BLOCKING,sc=false,e=null c=null cb=org.eclipse.jetty.util.Callback$3@2e77a4bb w=false
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannelState:HttpClient@971d0d8-scheduler-1: completed HttpChannelState@62575c71{s=HANDLING rs=COMPLETING os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannelState:HttpClient@971d0d8-scheduler-1: unhandle HttpChannelState@62575c71{s=HANDLING rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannelState:HttpClient@971d0d8-scheduler-1: nextAction(false) TERMINATED HttpChannelState@62575c71{s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannel:HttpClient@971d0d8-scheduler-1: action TERMINATED HttpChannelOverHttp@6668d464{s=HttpChannelState@62575c71{s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0},r=6,c=true/false,a=IDLE,uri=http://igor:2101/downloadFile.htm?fn=cov-analysis-macosx-2020.09.sh,age=60008}
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannel:HttpClient@971d0d8-scheduler-1: onCompleted for /downloadFile.htm written=20643619
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannelState:HttpClient@971d0d8-scheduler-1: recycle HttpChannelState@62575c71{s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-19 15:56:49.983:DBUG:oejh.HttpParser:HttpClient@971d0d8-scheduler-1: close HttpParser{s=CONTENT,0 of -1}
2021-01-19 15:56:49.983:DBUG:oejh.HttpParser:HttpClient@971d0d8-scheduler-1: CONTENT --> CLOSE
2021-01-19 15:56:49.983:DBUG:oejs.HttpChannel:HttpClient@971d0d8-scheduler-1: !handle TERMINATED HttpChannelOverHttp@6668d464{s=HttpChannelState@62575c71{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=6,c=false/false,a=IDLE,uri=null,age=0}
2021-01-19 15:56:49.983:DBUG:oejpP.f9d5:HttpClient@971d0d8-scheduler-1: 2077111110 proxying complete
2021-01-19 15:56:49.983:DBUG:oejc.HttpExchange:HttpClient@971d0d8-scheduler-1: Aborted (true) while active HttpExchange@59b0b48e{req=HttpRequest[GET /downloadFile.htm HTTP/1.1]@21ef0904[TERMINATED/null] res=HttpResponse[HTTP/1.1 200 null]@76ba06fe[TERMINATED/java.util.concurrent.TimeoutException: Total timeout 60000 ms elapsed]}: {}
java.util.concurrent.TimeoutException: Total timeout 60000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51)
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-01-19 15:57:10.357:DBUG:oejut.ReservedThreadExecutor:qtp486898233-50: ReservedThreadExecutor@16022d9d{s=2/16,p=0}@40558dd5 task=
2021-01-19 15:57:10.357:DBUG:oejut.ReservedThreadExecutor:qtp486898233-50: ReservedThreadExecutor@16022d9d{s=2/16,p=0}@40558dd5 IDLE
2021-01-19 15:57:10.357:DBUG:oejut.ReservedThreadExecutor:qtp486898233-50: ReservedThreadExecutor@16022d9d{s=1/16,p=0}@40558dd5 Exited
2021-01-19 15:57:10.357:DBUG:oejut.QueuedThreadPool:qtp486898233-50: ran ReservedThreadExecutor@16022d9d{s=1/16,p=0}@40558dd5 in QueuedThreadPool[qtp486898233]@1d057a39{STARTED,8<=22<=200,i=1,r=16,q=0}[ReservedThreadExecutor@16022d9d{s=1/16,p=0}]
```
-----

Any idea how we could fix this?  Thanks

**Comment by sbordet** [comment]
> java.util.concurrent.TimeoutException: Total timeout 60000 ms elapsed

You have configured the request to the server with a total timeout, and it elapsed while downloading the large file.
Increase the timeout, or speed up things in proxy or server or both (more hardware).

**Comment by ysuei** [comment]
Thanks.  How can I increase the timeout?
I am simply starting a proxy as such:


        proxy = new Server(new QueuedThreadPool());
        proxyConnector = new ServerConnector(proxy);
        proxyConnector.setHost(host);
        proxyConnector.setPort(port);
        proxy.addConnector(proxyConnector);
       proxy.addConnector(proxyConnector); 
       proxy.setHandler(new ConnectHandler());
       ServletContextHandler proxyHandler = new ServletContextHandler(connectHandler, "/");
       proxyHandler.addServlet(new ServletHolder(new ProxyServlet()), "/*");

       proxy.start();

**Comment by sbordet** [comment]
```java
ServletHolder holder = new ServletHolder(new ProxyServlet());
holder.setInitParameter("timeout", "120000"); // 2 minutes; value 0 disables total timeout (not particularly recommended).
```

**Comment by ysuei** [comment]
> ```java
> ServletHolder holder = new ServletHolder(new ProxyServlet());
> holder.setInitParameter("timeout", "120000"); // 2 minutes; value 0 disables total timeout (not particularly recommended).
> ```

Thanks so much !!!  Greatly appreciated.

**Comment by ysuei** [comment]
> > ```java
> > ServletHolder holder = new ServletHolder(new ProxyServlet());
> > holder.setInitParameter("timeout", "120000"); // 2 minutes; value 0 disables total timeout (not particularly recommended).
> > ```
> 

I added this to the code, but it is still failing with the same message.  The total timeout is still 60000ms.
Below is the log:

HttpChannel:HttpClient@67e2d983-scheduler-1: Commit failed
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:708)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$300(HttpConnection.java:667)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:526)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:915)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:987)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:284)
	at org.eclipse.jetty.server.HttpOutput.complete(HttpOutput.java:480)
	at org.eclipse.jetty.server.Response.completeOutput(Response.java:926)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:538)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:340)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1520)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1206)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:714)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:72)
	at org.eclipse.jetty.proxy.AbstractProxyServlet.sendProxyResponseError(AbstractProxyServlet.java:749)
	at org.eclipse.jetty.proxy.AbstractProxyServlet.onProxyResponseFailure(AbstractProxyServlet.java:708)
	at org.eclipse.jetty.proxy.ProxyServlet$ProxyResponseListener.onComplete(ProxyServlet.java:233)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:557)
	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:149)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:818)
	at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51)
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-01-22 14:56:12.798:DBUG:oejs.HttpOutput:HttpClient@67e2d983-scheduler-1: onWriteComplete(true,org.eclipse.jetty.io.EofException) s=CLOSING,api=BLOCKED,sc=false,e=null->s=CLOSED,api=BLOCKING,sc=false,e=null c=null cb=org.eclipse.jetty.util.Callback$3@44aa72c7 w=false
2021-01-22 14:56:12.798:DBUG:oejs.HttpChannelState:HttpClient@67e2d983-scheduler-1: completed HttpChannelState@2387ca6e{s=HANDLING rs=COMPLETING os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-22 14:56:12.798:DBUG:oejs.HttpChannelState:HttpClient@67e2d983-scheduler-1: unhandle HttpChannelState@2387ca6e{s=HANDLING rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-22 14:56:12.798:DBUG:oejs.HttpChannelState:HttpClient@67e2d983-scheduler-1: nextAction(false) TERMINATED HttpChannelState@2387ca6e{s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-22 14:56:12.798:DBUG:oejs.HttpChannel:HttpClient@67e2d983-scheduler-1: action TERMINATED HttpChannelOverHttp@63b299cb{s=HttpChannelState@2387ca6e{s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0},r=6,c=true/false,a=IDLE,uri=http://igor:2101/downloadFile.htm?fn=cov-analysis-macosx-2020.09.sh,age=60009}
2021-01-22 14:56:12.798:DBUG:oejs.HttpChannel:HttpClient@67e2d983-scheduler-1: onCompleted for /downloadFile.htm written=17963563
2021-01-22 14:56:12.798:DBUG:oejs.HttpChannelState:HttpClient@67e2d983-scheduler-1: recycle HttpChannelState@2387ca6e{s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0}
2021-01-22 14:56:12.798:DBUG:oejh.HttpParser:HttpClient@67e2d983-scheduler-1: close HttpParser{s=CONTENT,0 of -1}
2021-01-22 14:56:12.798:DBUG:oejh.HttpParser:HttpClient@67e2d983-scheduler-1: CONTENT --> CLOSE
2021-01-22 14:56:12.798:DBUG:oejs.HttpChannel:HttpClient@67e2d983-scheduler-1: !handle TERMINATED HttpChannelOverHttp@63b299cb{s=HttpChannelState@2387ca6e{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=6,c=false/false,a=IDLE,uri=null,age=0}
2021-01-22 14:56:12.798:DBUG:oejpP.d59286:HttpClient@67e2d983-scheduler-1: 2092353653 proxying complete
2021-01-22 14:56:12.798:DBUG:oejc.HttpExchange:HttpClient@67e2d983-scheduler-1: Aborted (true) while active HttpExchange@27a34b7{req=HttpRequest[GET /downloadFile.htm HTTP/1.1]@4670fdd9[TERMINATED/null] res=HttpResponse[HTTP/1.1 200 null]@1cc5e44a[TERMINATED/java.util.concurrent.TimeoutException: Total timeout 60000 ms elapsed]}: {}
java.util.concurrent.TimeoutException: Total timeout 60000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51)
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by sbordet** [comment]
@ysuei can we close this issue then?

**Comment by ysuei** [comment]
Thanks.  Closing the issue.
