### ISSUE TITLE
Provide more context when server responds with 401 Unauthorized that violates HTTP specification

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#5912]
**Jetty version** 11.0.0

**Java version** 15.0.1

**OS type/version** 10.0.19042.746

**Description**

I don't know if all cloudfront instances violate the HTTP specification, but here is what a `DEBUG` log shows one such server returning:

```
03:37:18.205 [HttpClient@53fe15ff-29] DEBUG o.eclipse.jetty.client.HttpReceiver.responseHeaders() - Response headers HttpResponse[HTTP/1.1 401 Unauthorized]@56681eaf
Content-Type: application/json
Content-Length: 27
Connection: keep-alive
Date: Sun, 24 Jan 2021 08:37:18 GMT
x-amzn-RequestId: ba2aee60-1c8e-4e66-ae50-cfba3a65fa8f
x-amzn-ErrorType: UnauthorizedException
x-amz-apigw-id: ZpS1wFVoPHcFhjg=
X-Cache: Error from cloudfront
Via: 1.1 4c93e73408f10048e0ca42d0347c4a28.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: YTO50-C1
X-Amz-Cf-Id: XRAP555kNMXJU9sq6L6fPMhFin3rttJLp6dkWClR5Rj5mNnkPX7IOw==
```

Subsequently jetty fails with:

```
org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
	at org.eclipse.jetty.client.AuthenticationProtocolHandler$AuthenticationListener.onComplete(AuthenticationProtocolHandler.java:162)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:483)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:463)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:426)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:374)
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:586)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1719)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1548)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:218)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:158)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:92)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:95)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:195)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:324)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:528)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:377)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:163)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:106)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:790)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:912)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

It's rather annoying to track down this problem because the response is only logged when `DEBUG` logs are enabled. Can you please log the response context with the exception when you throw it?

**Comment by cowwoc** [comment]
I guess I wanted to ask three things here:

1. Is it possible to add more context when this exception is thrown?
2. Has it been your experience that cloudfront servers always violate the HTTP specification this way?
3. Is it possible to configure the client to still return HTTP 401 to the caller?

In my case, I'd know what to do with an HTTP 401 even without a header. Is the only way for me to handle this to catch the exception and parse the string? This would be fragile.

**Comment by sbordet** [comment]
@cowwoc RFC 7235 [states](https://tools.ietf.org/html/rfc7235#section-3.1):

> The server generating a 401 response MUST send
   a WWW-Authenticate header field (Section 4.1) containing at least one
   challenge applicable to the target resource.

> 1. Is it possible to add more context when this exception is thrown?

What do you mean by "context"?

> 2. Has it been your experience that cloudfront servers always violate the HTTP specification this way?

I'm not sure whether it's cloudfront not sending the header, or it is being stripped by something in the middle.

> 3. Is it possible to configure the client to still return HTTP 401 to the caller?

Currently not possible.
It's a rather major violation of the HTTP specification but I guess there is not much work to do to be able to be more lenient.

I'll put up a PR, would you be able to try it out?

**Comment by cowwoc** [comment]
> What do you mean by "context"?

Show the full HTTP request/response leading to this failure. HTTP method, URL, headers, body... That sort of thing.

> I'll put up a PR, would you be able to try it out?

Digging into this further, I think we can leave things as-is: keep on throwing that exception and users can check for `HttpResponseException.getResponse().getStatus() == UNAUTHORIZED_401`. The only thing we're really missing at this point is a more helpful exception message as mentioned above.

**Comment by sbordet** [comment]
@cowwoc don't you have everything already available?

```java
Request request = httpClient.newRequest(...);
try {
    ContentResponse response = request.send();
} catch (HttpResponseException x) {
    // Got both Request and Response here.
}
```

**Comment by cowwoc** [comment]
In my case, the exception catching occurs further up the stack from the code sending the request. I don't want to handle this exception lower down because I want a single retry loop across multiple requests.

Any chance of adding `HttpResponseException.getRequest()` or would that cause its own set of problems?

**Comment by joakime** [comment]
> Any chance of adding `HttpResponseException.getRequest()` or would that cause its own set of problems?

The `Response.getRequest()` API not working for you for some reason?

**Comment by cowwoc** [comment]
>The `Response.getRequest()` API not working for you for some reason?

🤣 Well played. I wasn't aware this even existed.

We can close this ticket. I wish this information was more discoverable but in any case I've now got everything I need. Thank you!

**Comment by cowwoc** [comment]
@joakime Sorry. I have a follow-up question. `Request.send()` returns `ContentResponse` but `HttpResponseException.getResponse()` returns a `Response`. Why does the latter not return a `ContentResponse`? Am I supposed to check it using `instanceof` and cast it as needed? Or is something else going on?

**Comment by sbordet** [comment]
Why do you need to cast it down?

**Comment by cowwoc** [comment]
@sbordet If the request was successful I invoke `ContentResponse.getContentAsString()` and parse the response body.

**Comment by sbordet** [comment]
But the response is not successful -- you just got an exception and you're pulling a `Response` out of the exception.

The exception reports a `Response` and not a `ContentResponse` because in case of I/O exceptions you may not even received a response, or maybe only some part of it.

**Comment by cowwoc** [comment]
That makes sense. Thank you for the clarification.
