### ISSUE TITLE
Javadoc build triggers maven error on java.lang.NoSuchMethodError: 'org.apache.http.HttpHost org.apache.http.client.utils.URIUtils.extractHost(java.net.URI)'

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#5924]
**Jetty version**
jetty-10.0.x build

**Java version**
Java 11 and Java 15

**OS type/version**
Unix / Linux

**Description**

Full reactor build fails in `javadoc` module on Jetty 10.0.x

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:09 h
[INFO] Finished at: 2021-01-27T19:15:35Z
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/conf/logging/
constituent[1]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/jansi-1.17.1.jar
constituent[2]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-slf4j-provider-3.6.3.jar
constituent[3]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-resolver-transport-wagon-1.4.1.jar
constituent[4]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-resolver-connector-basic-1.4.1.jar
constituent[5]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/wagon-file-3.3.4.jar
constituent[6]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/jcl-over-slf4j-1.7.29.jar
constituent[7]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/jsoup-1.12.1.jar
constituent[8]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/wagon-http-3.3.4-shaded.jar
constituent[9]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/commons-cli-1.4.jar
constituent[10]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/cdi-api-1.0.jar
constituent[11]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/org.eclipse.sisu.plexus-0.3.4.jar
constituent[12]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/wagon-provider-api-3.3.4.jar
constituent[13]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/plexus-interpolation-1.25.jar
constituent[14]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-compat-3.6.3.jar
constituent[15]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/plexus-component-annotations-2.1.0.jar
constituent[16]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/org.eclipse.sisu.inject-0.3.4.jar
constituent[17]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-resolver-spi-1.4.1.jar
constituent[18]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-resolver-impl-1.4.1.jar
constituent[19]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-resolver-provider-3.6.3.jar
constituent[20]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-artifact-3.6.3.jar
constituent[21]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-repository-metadata-3.6.3.jar
constituent[22]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-core-3.6.3.jar
constituent[23]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/commons-lang3-3.8.1.jar
constituent[24]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/slf4j-api-1.7.29.jar
constituent[25]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/plexus-cipher-1.7.jar
constituent[26]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/plexus-sec-dispatcher-1.4.jar
constituent[27]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/plexus-utils-3.2.1.jar
constituent[28]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/jsr250-api-1.0.jar
constituent[29]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/javax.inject-1.jar
constituent[30]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/guava-25.1-android.jar
constituent[31]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/guice-4.2.1-no_aop.jar
constituent[32]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/commons-io-2.5.jar
constituent[33]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-shared-utils-3.2.1.jar
constituent[34]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-resolver-util-1.4.1.jar
constituent[35]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-resolver-api-1.4.1.jar
constituent[36]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-builder-support-3.6.3.jar
constituent[37]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-model-builder-3.6.3.jar
constituent[38]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-model-3.6.3.jar
constituent[39]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-plugin-api-3.6.3.jar
constituent[40]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-settings-builder-3.6.3.jar
constituent[41]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-settings-3.6.3.jar
constituent[42]: file:/home/jenkins/agent/tools/hudson.tasks.Maven_MavenInstallation/maven3/apache-maven-3.6.3/lib/maven-embedder-3.6.3.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoSuchMethodError: 'org.apache.http.HttpHost org.apache.http.client.utils.URIUtils.extractHost(java.net.URI)'
	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:122)
	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:71)
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:104)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:129)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:155)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:107)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:496)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:106)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:182)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:286)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:244)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecution(DefaultLifecycleExecutionPlanCalculator.java:169)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:154)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:130)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:144)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:97)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:111)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by joakime** [comment]
Running locally with a pristine maven local repository and using this command line can occasionally trigger the issue.

```
mvn -Pci -V -B -e clean install -Perrorprone -DskipTests
```

This is a flaky behavior at the low level Maven build (not a specific plugin like dependency or javadoc).
I can see from the downloaded content in my local repository that apache httpclient 4.0.2 was downloaded.

Here's my local failure (looks identical)

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:57 min
[INFO] Finished at: 2021-01-27T14:42:49-06:00
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/home/joakim/java/apache-maven-3.6.3/conf/logging/
constituent[1]: file:/home/joakim/java/apache-maven-3.6.3/lib/jansi-1.17.1.jar
constituent[2]: file:/home/joakim/java/apache-maven-3.6.3/lib/plexus-component-annotations-2.1.0.jar
constituent[3]: file:/home/joakim/java/apache-maven-3.6.3/lib/commons-lang3-3.8.1.jar
constituent[4]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-slf4j-provider-3.6.3.jar
constituent[5]: file:/home/joakim/java/apache-maven-3.6.3/lib/guice-4.2.1-no_aop.jar
constituent[6]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-settings-builder-3.6.3.jar
constituent[7]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-resolver-provider-3.6.3.jar
constituent[8]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-shared-utils-3.2.1.jar
constituent[9]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-resolver-spi-1.4.1.jar
constituent[10]: file:/home/joakim/java/apache-maven-3.6.3/lib/commons-cli-1.4.jar
constituent[11]: file:/home/joakim/java/apache-maven-3.6.3/lib/plexus-sec-dispatcher-1.4.jar
constituent[12]: file:/home/joakim/java/apache-maven-3.6.3/lib/javax.inject-1.jar
constituent[13]: file:/home/joakim/java/apache-maven-3.6.3/lib/cdi-api-1.0.jar
constituent[14]: file:/home/joakim/java/apache-maven-3.6.3/lib/plexus-cipher-1.7.jar
constituent[15]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-settings-3.6.3.jar
constituent[16]: file:/home/joakim/java/apache-maven-3.6.3/lib/wagon-file-3.3.4.jar
constituent[17]: file:/home/joakim/java/apache-maven-3.6.3/lib/slf4j-api-1.7.29.jar
constituent[18]: file:/home/joakim/java/apache-maven-3.6.3/lib/guava-25.1-android.jar
constituent[19]: file:/home/joakim/java/apache-maven-3.6.3/lib/plexus-utils-3.2.1.jar
constituent[20]: file:/home/joakim/java/apache-maven-3.6.3/lib/jsoup-1.12.1.jar
constituent[21]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-resolver-impl-1.4.1.jar
constituent[22]: file:/home/joakim/java/apache-maven-3.6.3/lib/wagon-provider-api-3.3.4.jar
constituent[23]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-builder-support-3.6.3.jar
constituent[24]: file:/home/joakim/java/apache-maven-3.6.3/lib/plexus-interpolation-1.25.jar
constituent[25]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-resolver-util-1.4.1.jar
constituent[26]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-artifact-3.6.3.jar
constituent[27]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-embedder-3.6.3.jar
constituent[28]: file:/home/joakim/java/apache-maven-3.6.3/lib/jsr250-api-1.0.jar
constituent[29]: file:/home/joakim/java/apache-maven-3.6.3/lib/jcl-over-slf4j-1.7.29.jar
constituent[30]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-model-builder-3.6.3.jar
constituent[31]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-repository-metadata-3.6.3.jar
constituent[32]: file:/home/joakim/java/apache-maven-3.6.3/lib/org.eclipse.sisu.plexus-0.3.4.jar
constituent[33]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-compat-3.6.3.jar
constituent[34]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-plugin-api-3.6.3.jar
constituent[35]: file:/home/joakim/java/apache-maven-3.6.3/lib/commons-io-2.5.jar
constituent[36]: file:/home/joakim/java/apache-maven-3.6.3/lib/wagon-http-3.3.4-shaded.jar
constituent[37]: file:/home/joakim/java/apache-maven-3.6.3/lib/org.eclipse.sisu.inject-0.3.4.jar
constituent[38]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-core-3.6.3.jar
constituent[39]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-resolver-transport-wagon-1.4.1.jar
constituent[40]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-resolver-connector-basic-1.4.1.jar
constituent[41]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-model-3.6.3.jar
constituent[42]: file:/home/joakim/java/apache-maven-3.6.3/lib/maven-resolver-api-1.4.1.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoSuchMethodError: 'org.apache.http.HttpHost org.apache.http.client.utils.URIUtils.extractHost(java.net.URI)'
	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:122)
	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:71)
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:104)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:129)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:155)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:107)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:496)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:106)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:182)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:286)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:244)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecution(DefaultLifecycleExecutionPlanCalculator.java:169)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:154)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:130)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:144)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:97)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:111)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by jmcc0nn3ll** [comment]
On a fresh checkout and build with ci profile (and errorprone is what I had) you can build and it will fail, if you then comment out every module aside from jetty-documentation and build it will fail (so just two modules in the reactor).  Then you remove the jetty-documentation module and build it will pass, downloading some new jars and then it will just work from then on it seems.

This is what looks like was downloaded once jetty-documentation is commented out.

[INFO] ---------------------< org.eclipse.jetty:javadoc >----------------------
[INFO] Building Jetty :: Javadoc Build 10.0.1-SNAPSHOT                    [2/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/3.2.0/maven-javadoc-plugin-3.2.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/3.2.0/maven-javadoc-plugin-3.2.0.pom (20 kB at 67 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/3.2.0/maven-javadoc-plugin-3.2.0.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/3.2.0/maven-javadoc-plugin-3.2.0.jar (492 kB at 5.5 MB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.5.2/maven-plugin-annotations-3.5.2.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.5.2/maven-plugin-annotations-3.5.2.pom (1.6 kB at 56 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-tools/3.5.2/maven-plugin-tools-3.5.2.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-tools/3.5.2/maven-plugin-tools-3.5.2.pom (15 kB at 480 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.5.2/maven-plugin-annotations-3.5.2.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.5.2/maven-plugin-annotations-3.5.2.jar (14 kB at 460 kB/s)
[INFO]

**Comment by joakime** [comment]
This triggered the failure for me.

```
mvn -Dmaven.repo.local=$HOME/tmp/repository2 -Pci -V -B -e -Djetty.testtracker.log=true clean install -Perrorprone -Dunix.socket.tmp=/tmp/unixsocket -DskipTests -pl jetty-documentation,javadoc
```

**Comment by joakime** [comment]
I captured the failure during `mvn --debug`.

[build-docdebug.log.gz](https://github.com/eclipse/jetty.project/files/5883285/build-docdebug.log.gz)

**Comment by joakime** [comment]
Olivier, here's the rundown of all of the downloaded artifacts in the local repo, and which ones have the `org.apache.http.client.utils.URIUtils` class.

Command line used to generate this:

```
find . -name "*.jar" -print -exec javap -cp {} org.apache.http.client.utils.URIUtils \; | tee build-javap.log
```

[build-javap.log.gz](https://github.com/eclipse/jetty.project/files/5883387/build-javap.log.gz)

You'll see that only the actual httpclient artifacts have that class.
And only version 4.0.2 is missing the `.extractHost(java.net.URI)` method.

```
./org/apache/httpcomponents/httpclient/4.0.2/httpclient-4.0.2.jar
Compiled from "URIUtils.java"
public class org.apache.http.client.utils.URIUtils {
  public static java.net.URI createURI(java.lang.String, java.lang.String, int, java.lang.String, java.lang.String, java.lang.String) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost, boolean) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost) throws java.net.URISyntaxException;
  public static java.net.URI resolve(java.net.URI, java.lang.String);
  public static java.net.URI resolve(java.net.URI, java.net.URI);
}
./org/apache/httpcomponents/httpclient/4.5.12/httpclient-4.5.12.jar
Compiled from "URIUtils.java"
public class org.apache.http.client.utils.URIUtils {
  public static final java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag> NO_FLAGS;
  public static final java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag> DROP_FRAGMENT;
  public static final java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag> NORMALIZE;
  public static final java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag> DROP_FRAGMENT_AND_NORMALIZE;
  public static java.net.URI createURI(java.lang.String, java.lang.String, int, java.lang.String, java.lang.String, java.lang.String) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost, boolean) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost, java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag>) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURIForRoute(java.net.URI, org.apache.http.conn.routing.RouteInfo) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURIForRoute(java.net.URI, org.apache.http.conn.routing.RouteInfo, boolean) throws java.net.URISyntaxException;
  public static java.net.URI resolve(java.net.URI, java.lang.String);
  public static java.net.URI resolve(java.net.URI, java.net.URI);
  public static java.net.URI normalizeSyntax(java.net.URI) throws java.net.URISyntaxException;
  public static org.apache.http.HttpHost extractHost(java.net.URI);
  public static java.net.URI resolve(java.net.URI, org.apache.http.HttpHost, java.util.List<java.net.URI>) throws java.net.URISyntaxException;
  static {};
}
./org/apache/httpcomponents/httpclient/4.5.8/httpclient-4.5.8.jar
Compiled from "URIUtils.java"
public class org.apache.http.client.utils.URIUtils {
  public static final java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag> NO_FLAGS;
  public static final java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag> DROP_FRAGMENT;
  public static final java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag> NORMALIZE;
  public static final java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag> DROP_FRAGMENT_AND_NORMALIZE;
  public static java.net.URI createURI(java.lang.String, java.lang.String, int, java.lang.String, java.lang.String, java.lang.String) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost, boolean) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost, java.util.EnumSet<org.apache.http.client.utils.URIUtils$UriFlag>) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURIForRoute(java.net.URI, org.apache.http.conn.routing.RouteInfo) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURIForRoute(java.net.URI, org.apache.http.conn.routing.RouteInfo, boolean) throws java.net.URISyntaxException;
  public static java.net.URI resolve(java.net.URI, java.lang.String);
  public static java.net.URI resolve(java.net.URI, java.net.URI);
  public static java.net.URI normalizeSyntax(java.net.URI) throws java.net.URISyntaxException;
  public static org.apache.http.HttpHost extractHost(java.net.URI);
  public static java.net.URI resolve(java.net.URI, org.apache.http.HttpHost, java.util.List<java.net.URI>) throws java.net.URISyntaxException;
  static {};
}
```

**Comment by joakime** [comment]
PR #5925 merged.

**Comment by joakime** [comment]
Reopening as `<module>javadoc</module>` is still disabled in main `pom.xml`

Both in the `eclipse-release` profile ...

https://github.com/eclipse/jetty.project/blob/fb4ecf09e91c07d4ede7a89810b4861fad5d5685/pom.xml#L1320-L1326

and the `ci` profile ...

https://github.com/eclipse/jetty.project/blob/fb4ecf09e91c07d4ede7a89810b4861fad5d5685/pom.xml#L1386-L1403

**Comment by joakime** [comment]
Still happening!  grrr ....

**Comment by joakime** [comment]
A slightly faster build command line to trigger this issue ...

Assuming your local repository is in `~/.m2/repository/` ...

```
rm -rf ~/.m2/repository/org/apache/maven/plugins/maven-javadoc-plugin/ && \
mvn clean install -Pci -Pfast -pl :jetty-documentation,:javadoc
```

**Comment by olamy** [comment]
should not affect profile `eclipse-release` because we download m-javadoc-p earlier to build every module javadoc-jar file.
simple workaround could be to run per default javadoc:jar for jetty-util

**Comment by olamy** [comment]
should be fixed by https://github.com/eclipse/jetty.project/pull/5932
