### ISSUE TITLE
[JDBCSessionManager] Problem expiring sessions on class changes

### ISSUE THREAD

**Issue by laeubi** [eclipse/jetty.project#593]
When expiring a session and an InvalidClassException occured, the session cannot be invalidated. In general jetty should always be able to invalidate a session regardless of any error reading it so broken (or simply old) sessions can be cleaned up.

```
09:47:06.350 WARN  (JDBCSessionManager.java:865) Problem expiring sessions [Scheduler-1444066154] []
java.io.InvalidClassException: org.apache.wicket.Session; incompatible types for field pageId
	at java.io.ObjectStreamClass.matchFields(ObjectStreamClass.java:2299) ~[na:1.8.0_73]
	at java.io.ObjectStreamClass.getReflector(ObjectStreamClass.java:2193) ~[na:1.8.0_73]
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:669) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_73]
	at java.util.HashMap.readObject(HashMap.java:1396) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_73]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_73]
	at org.eclipse.jetty.server.session.JDBCSessionManager$1.run(JDBCSessionManager.java:970) ~[org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1266) ~[org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
	at org.eclipse.jetty.server.session.JDBCSessionManager.loadSession(JDBCSessionManager.java:992) ~[org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
	at org.eclipse.jetty.server.session.JDBCSessionManager.expire(JDBCSessionManager.java:840) ~[org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
	at org.eclipse.jetty.server.session.JDBCSessionIdManager.scavengeSessions(JDBCSessionIdManager.java:1378) [org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
	at org.eclipse.jetty.server.session.JDBCSessionIdManager.scavenge(JDBCSessionIdManager.java:1288) [org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
	at org.eclipse.jetty.server.session.JDBCSessionIdManager.access$000(JDBCSessionIdManager.java:60) [org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
	at org.eclipse.jetty.server.session.JDBCSessionIdManager$Scavenger.run(JDBCSessionIdManager.java:606) [org.eclipse.jetty.server_9.3.8.v20160314.jar:9.3.8.v20160314]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_73]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_73]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_73]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
```

**Comment by janbartel** [comment]
@laeubi  if a session can't be loaded during expiry then it will stay in the database a little longer, but it will eventually be deleted by the scavenger: the last act by the scavenger in each pass is to look for sessions that are in the database that have been expired for a long time, try to load them and call all the listeners for them, but if they cannot be loaded, then they will just be deleted.

**Comment by laeubi** [comment]
But does not the call from "JDBCSessionIdManager.scavengeSessions" means it is about to scavenge sessions?
The problem currently is that on each call a stack-trace for all invalid sessions is produced and printed to the log, beside this, the problem won't go away, so would it be possible to just delete (and WARN) about those sessions if they have serious problems, or only log at debug e.g. "can't expire session because of xyzexception now retry later..." and only warn (maybe with full trace) on the "delete-long-expired" ones?
