### ISSUE TITLE
Update documentation to Obfuscate and De-obfuscate passwords

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#5930]
**Jetty version**
10.x
Because of slf4j the simple command doesn't work anymore:
```
java -cp jetty-util/target/jetty-util-10.0.1-SNAPSHOT.jar org.eclipse.jetty.util.security.Password
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.eclipse.jetty.util.security.Credential.<clinit>(Credential.java:43)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

**Comment by joakime** [comment]
Also related to #7063

**Comment by joakime** [comment]
Closing in favor of solution in #7063
