### ISSUE TITLE
Error Caused by

### ISSUE THREAD

**Issue by cbrendible** [eclipse/jetty.project#5972]
java.lang.NoSuchMethodError: setNvmeInfo
	at com.micron.msd.api.ApiNative.getAllDriveInfo(Native Method)
	at com.micron.msd.api.ApiAccess.getAllDriveInfo(ApiAccess.java:308)
	at com.micron.msd.gui.web.system.DrivesModel.load(DrivesModel.java:48)
	at com.micron.msd.gui.web.system.DrivesModel.load(DrivesModel.java:22)
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:128)
	at org.apache.wicket.Component.getDefaultModelObject(Component.java:1574)
	at org.apache.wicket.markup.html.list.ListView.getViewSize(ListView.java:218)
	at org.apache.wicket.markup.html.list.ListView.onPopulate(ListView.java:472)
	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:124)
	at org.apache.wicket.Component.beforeRender(Component.java:937)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1754)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3793)
	at org.apache.wicket.Page.onBeforeRender(Page.java:789)
	at com.micron.msd.gui.web.MainPage.onBeforeRender(MainPage.java:52)
	at org.apache.wicket.Component.beforeRender(Component.java:937)
	at org.apache.wicket.Page.renderPage(Page.java:991)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:202)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:914)
	at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:282)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:275)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:206)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:299)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

**Comment by joakime** [comment]
This error is not happening in Jetty.
The `com.micron.msd.api` library is causing it.
