### ISSUE TITLE
FastFileServer Example throws exception on any GET file due to wrong Content-Length value

### ISSUE THREAD

**Issue by hauk3wu1ff** [eclipse/jetty.project#598]
Hello,
The following issue occurs with the org.eclipse.jetty.embedded.FastFileServer example code from branch jetty-9.3.x:
Any GET file request, e.g. curl http://localhost:8080/pom.xml results in FastFileServer returning a "HTTP/1.1 500 Server Error". The root-cause for the error is the following line in handle() 
`response.setDateHeader("Content-Length", file.length());`
which attempts to set the content-length header using a date-function. Deleting the above line fixes the error: The Jetty HTTP-classes set the content-length correctly.

Please see related server-side stacktrace below. I'm submitting a pull request with the proposed fix for the issue.
Best regards.

`org.eclipse.jetty.server.HttpChannel handleException Could not send response error 500, already committed
org.eclipse.jetty.http.BadMessageException: 500: For input string: "Thu, 01 Jan 1970 00:00:04 GMT"
        at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:414)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:690)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:521)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:692)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:746)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:179)
        at org.eclipse.jetty.server.HttpOutput$ReadableByteChannelWritingCB.process(HttpOutput.java:1244)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
        at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:632)
        at org.eclipse.jetty.embedded.FastFileServer$FastFileHandler.handle(FastFileServer.java:139)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "Thu, 01 Jan 1970 00:00:04 GMT"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.valueOf(Long.java:803)
        at org.eclipse.jetty.http.HttpGenerator.generateHeaders(HttpGenerator.java:618)
        at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:399)
        ... 26 more`

**Comment by gregw** [comment]
Thanks for the PR!
