### ISSUE TITLE
Threadpool settings are ignored because system is using an Integer parameter instead of an int.

### ISSUE THREAD

**Issue by SeanRoy** [eclipse/jetty.project#6007]
**9.4.36.v20210114**

**java-8**

**ubuntu 14.04 LTS**

**Threadpool settings are ignored because system is using an Integer parameter instead of an int.**

Here's the debug output from the console:

2021-02-24 17:52:57.643:DBUG:oejx.XmlConfiguration:main: XML call setOut
2021-02-24 17:52:57.644:DBUG:oejx.XmlParser:main: resolveEntity(-//Jetty//Configure//EN, http://www.eclipse.org/jetty/configure_9_3.dtd)
2021-02-24 17:52:57.645:DBUG:oejx.XmlParser:main: Redirected entity http://www.eclipse.org/jetty/configure_9_3.dtd --> jar:file:/opt/jetty-home-9.4.36.v20210114/lib/jetty-xml-9.4.36.v20210114.jar!/org/eclipse/jetty/xml/configure_9_3.dtd
2021-02-24 17:52:57.651:DBUG:oejx.XmlConfiguration:main: Configure file:///var/jetty/etc/jetty-threadpool.xml
2021-02-24 17:52:57.651:DBUG:oejx.XmlConfiguration:main: XML new org.eclipse.jetty.util.thread.QueuedThreadPool
2021-02-24 17:52:57.665:DBUG:oejx.XmlConfiguration:main: XML QueuedThreadPool[qtp1389647288]@52d455b8{STOPPED,8<=0<=200,i=0,r=-1,q=0}[NO_TRY].setMinThreads(1025) [NEW]
2021-02-24 17:52:57.667:IGNORED:oejx.XmlConfiguration:main:
java.lang.NoSuchMethodException: org.eclipse.jetty.util.thread.QueuedThreadPool.setMinThreads(java.lang.Integer)
        at java.lang.Class.getMethod(Class.java:1786)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:601)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:509)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1022)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:521)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380)
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1893)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

<?xml version="1.0"?><!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

The contents of /var/jetty/etc/jetty-threadpool.xml:

```
<Configure>
  <!-- =========================================================== -->
  <!-- Configure the Server Thread Pool.                           -->
  <!-- The server holds a common thread pool which is used by      -->
  <!-- default as the executor used by all connectors and servlet  -->
  <!-- dispatches.                                                 -->
  <!--                                                             -->
  <!-- Configuring a fixed thread pool is vital to controlling the -->
  <!-- maximal memory footprint of the server and is a key tuning  -->
  <!-- parameter for tuning.  In an application that rarely blocks -->
  <!-- then maximal threads may be close to the number of 5*CPUs.  -->
  <!-- In an application that frequently blocks, then maximal      -->
  <!-- threads should be set as high as possible given the memory  -->
  <!-- available.                                                  -->
  <!--                                                             -->
  <!-- Consult the javadoc of o.e.j.util.thread.QueuedThreadPool   -->
  <!-- for all configuration that may be set here.                 -->
  <!-- =========================================================== -->
  <New id="threadPool" class="org.eclipse.jetty.util.thread.QueuedThreadPool">
    <Set name="minThreads" type="int"><Property name="jetty.threadPool.minThreads" deprecated="threads.min" default="10"/>25</Set>
    <Set name="maxThreads" type="int"><Property name="jetty.threadPool.maxThreads" deprecated="threads.max" default="200"/>300</Set>
    <Set name="reservedThreads" type="int"><Property name="jetty.threadPool.reservedThreads" default="-1"/></Set>
    <Set name="idleTimeout" type="int"><Property name="jetty.threadPool.idleTimeout" deprecated="threads.timeout" default="60000"/></Set>
    <Set name="detailedDump" type="boolean"><Property name="jetty.threadPool.detailedDump" default="false"/></Set>
  </New>
</Configure>
```

Looking at org.eclipse.jetty.util.thread.QueuedThreadPool::setMinThreads in jetty.project, the signature is:
public void setMinThreads(int minThreads) and the exception is org.eclipse.jetty.util.thread.QueuedThreadPool.setMinThreads(java.lang.Integer), so either this method needs to be overloaded with a primitive parameter, or the caller needs to convert.  I see the same exception for setMaxThreads, setIdleTimeout, setReservedThreads, etc.  I need to be able to tune the thread pool.

**Comment by sbordet** [comment]
This line:

```
2021-02-24 17:52:57.665:DBUG:oejx.XmlConfiguration:main: XML QueuedThreadPool[qtp1389647288]@52d455b8{STOPPED,8<=0<=200,i=0,r=-1,q=0}[NO_TRY].setMinThreads(1025) [NEW]
```

says that you the value read from the XML is `1025`, which does not match what you report in the XML.

The next line:

```
2021-02-24 17:52:57.667:IGNORED:oejx.XmlConfiguration:main:
java.lang.NoSuchMethodException: org.eclipse.jetty.util.thread.QueuedThreadPool.setMinThreads(java.lang.Integer)
```

is logged at `IGNORED` level and it's the attempt to match the signature (that failed) and the algorithm continues with other attempts.

I suspect you have _another_ XML file where you read from, with `<Set name="minThreads" type="Integer">...` (note `Integer` not `int` on the `type` attribute) and a different value (or malformed XML so multiple values are read as `1025`).

The default files work correctly and you can configure the thread pool.
However, you should do it through a `$JETTY_BASE` with properties, and not modifying XML files.

```
$ mkdir /path/to/jetty.base
$ cd /path/to/jetty.base
$ java -jar $JETTY_HOME/start.jar --add-to-startd=threadpool,http
```

Edit `/path/to/jetty.base/start.d/threadpool.ini` and change the property `jetty.threadPool.minThreads` as you like.

**Comment by SeanRoy** [comment]
That's how I got to copying the jetty-threadpool.xml file from jetty.home/etc to jetty.base/etc.  I originally hadn't touched any xml files and just updated minThreads in threadpool.ini when I was getting these exceptions.  The 1025 value you mentioned was from a prior run where I had set the value to that to distinguish where the value was being picked up.  I neglected to get the  proper log run that corresponded with it.  To demonstrate this, I'll do the following:
1. Removed jetty.base/etc/jetty-threadpool.xml
2. Updated jetty.home/etc/jetty-threadpool.xml to give a new default value that we can recognize.  I'll use 123:

```xml
<?xml version="1.0"?><!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure>
  <!-- =========================================================== -->
  <!-- Configure the Server Thread Pool.                           -->
  <!-- The server holds a common thread pool which is used by      -->
  <!-- default as the executor used by all connectors and servlet  -->
  <!-- dispatches.                                                 -->
  <!--                                                             -->
  <!-- Configuring a fixed thread pool is vital to controlling the -->
  <!-- maximal memory footprint of the server and is a key tuning  -->
  <!-- parameter for tuning.  In an application that rarely blocks -->
  <!-- then maximal threads may be close to the number of 5*CPUs.  -->
  <!-- In an application that frequently blocks, then maximal      -->
  <!-- threads should be set as high as possible given the memory  -->
  <!-- available.                                                  -->
  <!--                                                             -->
  <!-- Consult the javadoc of o.e.j.util.thread.QueuedThreadPool   -->
  <!-- for all configuration that may be set here.                 -->
  <!-- =========================================================== -->
  <New id="threadPool" class="org.eclipse.jetty.util.thread.QueuedThreadPool">
    <Set name="minThreads" type="int"><Property name="jetty.threadPool.minThreads" deprecated="threads.min" default="123"/></Set>
    <Set name="maxThreads" type="int"><Property name="jetty.threadPool.maxThreads" deprecated="threads.max" default="200"/></Set>
    <Set name="reservedThreads" type="int"><Property name="jetty.threadPool.reservedThreads" default="-1"/></Set>
    <Set name="idleTimeout" type="int"><Property name="jetty.threadPool.idleTimeout" deprecated="threads.timeout" default="60000"/></Set>
    <Set name="detailedDump" type="boolean"><Property name="jetty.threadPool.detailedDump" default="false"/></Set>
  </New>
</Configure>
```

3. Use 32  in jetty.base/start.d/threadpool.ini:
```
# --------------------------------------- 
# Module: threadpool
# Enables the Server thread pool.
# --------------------------------------- 
--module=threadpool


### Server Thread Pool Configuration
## Minimum Number of Threads
jetty.threadPool.minThreads=32

## Maximum Number of Threads
jetty.threadPool.maxThreads=200

## Number of reserved threads (-1 for heuristic)
#jetty.threadPool.reservedThreads=-1

## Thread Idle Timeout (in milliseconds)
jetty.threadPool.idleTimeout=60000

## Whether to Output a Detailed Dump
jetty.threadPool.detailedDump=true
```

I restarted jetty and the log spat this out:
`2021-02-25 11:57:46.601:DBUG:oejx.XmlConfiguration:main: XML call setOut
2021-02-25 11:57:46.602:DBUG:oejx.XmlParser:main: resolveEntity(-//Jetty//Configure//EN, http://www.eclipse.org/jetty/configure_9_3.dtd)
2021-02-25 11:57:46.603:DBUG:oejx.XmlParser:main: Redirected entity http://www.eclipse.org/jetty/configure_9_3.dtd --> jar:file:/opt/jetty-home-9.4.36.v20210114/lib/jetty-xml-9.4.36.v20210114.jar!/org/eclipse/jetty/xml/configure_9_3.dtd
2021-02-25 11:57:46.609:DBUG:oejx.XmlConfiguration:main: Configure file:///opt/jetty-home-9.4.36.v20210114/etc/jetty-threadpool.xml
2021-02-25 11:57:46.609:DBUG:oejx.XmlConfiguration:main: XML new org.eclipse.jetty.util.thread.QueuedThreadPool
2021-02-25 11:57:46.624:DBUG:oejx.XmlConfiguration:main: XML QueuedThreadPool[qtp1389647288]@52d455b8{STOPPED,8<=0<=200,i=0,r=-1,q=0}[NO_TRY].setMinThreads(32) [NEW]
2021-02-25 11:57:46.625:IGNORED:oejx.XmlConfiguration:main:
java.lang.NoSuchMethodException: org.eclipse.jetty.util.thread.QueuedThreadPool.setMinThreads(java.lang.Integer)
        at java.lang.Class.getMethod(Class.java:1786)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:601)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:509)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1022)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:521)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380)
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1893)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
        at org.eclipse.jetty.start.Main.start(Main.java:491)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
`

**Comment by joakime** [comment]
> IGNORED:oejx.XmlConfiguration:main: java.lang.NoSuchMethodException

That is an IGNORED exception.
It's just a step in the attempts to use the defined `<Set>`, a subsequent step worked (as it didn't produce an error or failure to start).

Just take a look at the implementation of `<Set>`

https://github.com/eclipse/jetty.project/blob/jetty-9.4.37.v20210219/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java#L598-L736

Anywhere you see `LOG.ignore(x)` is where that kind of IGNORED logging event occurs.

**Comment by SeanRoy** [comment]
ok thank you for your time.

**Comment by sbordet** [comment]
@SeanRoy so we think it actually works, just don't look at IGNORED exceptions (they should be ignored 😃).

Verify in this way:

```
$ java -jar $JETTY_HOME/start.jar --add-to-startd=threadpool,jmx
# edit threadpool.ini like you describe above
$ java -jar $JETTY_HOME/start.jar
```

Now start a JMX console such as JMC, connect to the Jetty JVM you started above, navigate the MBeans under `org.eclipse.jetty.util:type=queuedthreadpool,id=0` and you should see the values with which the `QueuedThreadPool` is configured, and they should match what you expect.

**Comment by joakime** [comment]
@SeanRoy run your logging at `DEBUG` level, not `ALL` level (which includes IGNORE/TRACE/FINE/FINER/FINEST etc), it will help you avoid getting caught up in minutiae that has no impact your goals.

**Comment by joakime** [comment]
You can even use `start.jar jetty.server.dumpAfterStart=true` and see the Jetty Server (state) dump which will list your actual (runtime) QTP configuration.
