### ISSUE TITLE
Error starting jetty-10: Provider org.eclipse.jetty.websocket.javax.client.JavaxWebSocketShutdownContainer not found

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#6024]
When the jetty-10 demo webapps are deployed, there are errors logged, which are logged at INFO level:

> INFO :oeja.AnnotationConfiguration:main: Error:  for o.e.j.w.WebAppContext......

It's a bit obscure to work out what is happening, but I discovered that the following error is being thrown:

Caused by: java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider org.eclipse.jetty.websocket.javax.client.JavaxWebSocketShutdownContainer not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)

**Comment by joakime** [comment]
This on `jetty-10.0.x` HEAD, or one of the releases?

**Comment by janbartel** [comment]
HEAD jetty-10.0.x
