### ISSUE TITLE
Flaky test DuplicateCookieTest.testMultipleIdenticalSessionCookies 

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#6138]
**Jetty version**
10.0.x

**Description**
Failed test on jenkins `DuplicateCookieTest.testMultipleIdenticalSessionCookies()`.
see https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-6010/18/tests

```
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:611)
	at org.eclipse.jetty.server.session.DuplicateCookieTest.testMultipleIdenticalSessionCookies(DuplicateCookieTest.java:360)
```

**Comment by janbartel** [comment]
Doesn't seem to have failed again?

**Comment by janbartel** [comment]
I see the problem: the test needs to wait to check the requests in the sessions until the request has fully completed, not just after the response has been returned to the client. Raised PR #6307
