### ISSUE TITLE
Threads locked up because of Scalatra Gzip deflation

### ISSUE THREAD

**Issue by SeanRoy** [eclipse/jetty.project#6147]
We run a scalatra REST api on jetty and threads are getting locked up in gzip deflate bytes.  Eventually all 8 of the cpu cores get stuck and our load goes through the roof, resulting in poor performance unless someone is constantly keeping an eye on them and restarting jetty as needed.  I've seen many reports on this bug, but I thought we were between minGzipSize > 0, and the java and jetty versions.  Any assistance would be greatly appreciated.

``` none
Jetty version: 9.4.36.v20210114
Java version: 1.8.0_101-b13
root@nrby-api1:/var/jetty# java -jar /opt/jetty/start.jar --list-config

Java Environment:
-----------------
 java.home = /usr/lib/jvm/java-8-oracle/jre (null)
 java.vm.vendor = Oracle Corporation (null)
 java.vm.version = 25.101-b13 (null)
 java.vm.name = Java HotSpot(TM) 64-Bit Server VM (null)
 java.vm.info = mixed mode (null)
 java.runtime.name = Java(TM) SE Runtime Environment (null)
 java.runtime.version = 1.8.0_101-b13 (null)
 java.io.tmpdir = /tmp (null)
 user.dir = /var/jetty (null)
 user.language = en (null)
 user.country = US (null)

Jetty Environment:
-----------------
 jetty.version = 9.4.36.v20210114
 jetty.tag.version = master
 jetty.home = /opt/jetty-home-9.4.36.v20210114
 jetty.base = /var/jetty

Config Search Order:
--------------------
 <command-line>
 ${jetty.base} -> /var/jetty
 ${jetty.home} -> /opt/jetty-home-9.4.36.v20210114


JVM Arguments:
--------------
 (no jvm args specified)

System Properties:
------------------
 (no system properties specified)

Properties:
-----------
 java.version = 1.8.0_101
 java.version.major = 1
 java.version.micro = 0
 java.version.minor = 8
 java.version.platform = 8
 jetty.base = /var/jetty
 jetty.base.uri = file:///var/jetty
 jetty.gzip.minGzipSize = 32
 jetty.home = /opt/jetty-home-9.4.36.v20210114
 jetty.home.uri = file:///opt/jetty-home-9.4.36.v20210114
 jetty.http.idleTimeout =  30000
 jetty.http.port =  9080
 jetty.httpConfig.outputBufferSize = 32768
 jetty.httpConfig.requestHeaderSize = 8192
 jetty.jmxremote.rmiregistryhost = 10.10.161.61
 jetty.jmxremote.rmiserverhost = 10.10.161.61
 jetty.threadPool.detailedDump = true
 jetty.threadPool.idleTimeout = 60000
 jetty.threadPool.maxThreads = 200
 jetty.threadPool.minThreads = 10

Jetty Server Classpath:
-----------------------
Version Information on 13 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    (dir) | ${jetty.base}/resources
 1:                    3.1.0 | ${jetty.home}/lib/servlet-api-3.1.jar
 2:                 3.1.0.M0 | ${jetty.home}/lib/jetty-schemas-3.1.jar
 3:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-http-9.4.36.v20210114.jar
 4:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-server-9.4.36.v20210114.jar
 5:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-xml-9.4.36.v20210114.jar
 6:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-util-9.4.36.v20210114.jar
 7:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-io-9.4.36.v20210114.jar
 8:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-security-9.4.36.v20210114.jar
 9:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-servlet-9.4.36.v20210114.jar
10:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-webapp-9.4.36.v20210114.jar
11:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-deploy-9.4.36.v20210114.jar
12:         9.4.36.v20210114 | ${jetty.home}/lib/jetty-jmx-9.4.36.v20210114.jar

Jetty Active XMLs:
------------------
 ${jetty.home}/etc/jetty-bytebufferpool.xml
 ${jetty.home}/etc/console-capture.xml
 ${jetty.home}/etc/jetty-threadpool.xml
 ${jetty.home}/etc/jetty.xml
 ${jetty.home}/etc/jetty-webapp.xml
 ${jetty.home}/etc/jetty-deploy.xml
 ${jetty.home}/etc/jetty-gzip.xml
 ${jetty.home}/etc/jetty-http.xml
 ${jetty.home}/etc/jetty-jmx.xml
 ${jetty.home}/etc/jetty-jmx-remote.xml
```

```
"qtp1389647288-22" #22 prio=5 os_prio=0 tid=0x00007f55c4624000 nid=0x2878 runnable [0x00007f5547cf8000]
   java.lang.Thread.State: RUNNABLE
        at java.util.zip.Deflater.deflateBytes(Native Method)
        at java.util.zip.Deflater.deflate(Deflater.java:444)
        - locked <0x00000006c6d4b790> (a java.util.zip.ZStreamRef)
        at java.util.zip.Deflater.deflate(Deflater.java:366)
        at java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:159)
        at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
        at org.scalatra.EncodedOutputStream.close(ContentEncoding.scala:150)
        at org.scalatra.servlet.RichResponse.end(RichResponse.scala:84)
        at org.scalatra.ContentEncodingSupport$$anonfun$org$scalatra$ContentEncodingSupport$$encodedResponse$1$$anonfun$apply$1.apply(ContentEncodingSupport.scala:20)
        at org.scalatra.ContentEncodingSupport$$anonfun$org$scalatra$ContentEncodingSupport$$encodedResponse$1$$anonfun$apply$1.apply(ContentEncodingSupport.scala:20)
        at org.scalatra.ScalatraBase$$anonfun$runRenderCallbacks$1.apply(ScalatraBase.scala:74)
        at org.scalatra.ScalatraBase$$anonfun$runRenderCallbacks$1.apply(ScalatraBase.scala:74)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatra.ScalatraBase$.runRenderCallbacks(ScalatraBase.scala:74)
        at org.scalatra.ScalatraBase$class.renderResponseBody(ScalatraBase.scala:421)
        at com.ping4.v4.V4ApiServlet.renderResponseBody(V4ApiServlet.scala:37)
        at org.scalatra.ScalatraBase$class.renderResponse(ScalatraBase.scala:378)
        at com.ping4.v4.V4ApiServlet.renderResponse(V4ApiServlet.scala:37)
        at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:195)
        at com.ping4.v4.V4ApiServlet.executeRoutes(V4ApiServlet.scala:37)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:123)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:123)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:123)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
        at com.ping4.v4.V4ApiServlet.withResponse(V4ApiServlet.scala:37)
        at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
        at com.ping4.v4.V4ApiServlet.withRequest(V4ApiServlet.scala:37)
        at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
        at com.ping4.v4.V4ApiServlet.withRequestResponse(V4ApiServlet.scala:37)
        at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:122)
        at com.ping4.v4.V4ApiServlet.org$scalatra$servlet$ServletBase$$super$handle(V4ApiServlet.scala:37)
        at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
        at com.ping4.v4.V4ApiServlet.org$scalatra$ContentEncodingSupport$$super$handle(V4ApiServlet.scala:37)
        at org.scalatra.ContentEncodingSupport$$anonfun$handle$1.apply$mcV$sp(ContentEncodingSupport.scala:12)
        at org.scalatra.ContentEncodingSupport$$anonfun$handle$1.apply(ContentEncodingSupport.scala:12)
        at org.scalatra.ContentEncodingSupport$$anonfun$handle$1.apply(ContentEncodingSupport.scala:12)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
        at com.ping4.v4.V4ApiServlet.withResponse(V4ApiServlet.scala:37)
        at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
        at com.ping4.v4.V4ApiServlet.withRequest(V4ApiServlet.scala:37)
        at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
        at com.ping4.v4.V4ApiServlet.withRequestResponse(V4ApiServlet.scala:37)
        at org.scalatra.ContentEncodingSupport$class.handle(ContentEncodingSupport.scala:11)
        at com.ping4.v4.V4ApiServlet.org$scalatra$servlet$FileUploadSupport$$super$handle(V4ApiServlet.scala:37)
        at org.scalatra.servlet.FileUploadSupport$class.handle(FileUploadSupport.scala:95)
        at com.ping4.v4.V4ApiServlet.org$scalatra$CorsSupport$$super$handle(V4ApiServlet.scala:37)
        at org.scalatra.CorsSupport$$anonfun$handle$1.apply$mcV$sp(CORSSupport.scala:221)
        at org.scalatra.CorsSupport$$anonfun$handle$1.apply(CORSSupport.scala:209)
        at org.scalatra.CorsSupport$$anonfun$handle$1.apply(CORSSupport.scala:209)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
        at com.ping4.v4.V4ApiServlet.withResponse(V4ApiServlet.scala:37)
        at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
        at com.ping4.v4.V4ApiServlet.withRequest(V4ApiServlet.scala:37)
        at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
        at com.ping4.v4.V4ApiServlet.withRequestResponse(V4ApiServlet.scala:37)
        at org.scalatra.CorsSupport$class.handle(CORSSupport.scala:208)
        at com.ping4.v4.V4ApiServlet.handle(V4ApiServlet.scala:37)
        at org.scalatra.ScalatraServlet$class.service(ScalatraServlet.scala:65)
        at com.ping4.v4.V4ApiServlet.service(V4ApiServlet.scala:37)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1452)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:50)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:766)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel$$Lambda$96/1247980385.dispatch(Unknown Source)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by joakime** [comment]
> at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:50)

Get rid of your `GzipFilter` (in your webapp descriptor), that doesn't work in Servlet 3.1 (aka Jetty 9)

> at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
> at org.scalatra.EncodedOutputStream.close(ContentEncoding.scala:150)
> at org.scalatra.servlet.RichResponse.end(RichResponse.scala:84)

That points at Scalatra doing the Gzip, not Jetty.

I see you have GzipHandler active, so either Jetty does it, or Scalatra does it (properly).
Perhaps you should just disable Scalatra compression, and just configure your GzipHandler to compress the content instead.

>  but I thought we were between minGzipSize > 0, and the java and jetty versions. Any assistance would be greatly appreciated.

GzipHandler is not involved in your stacktrace, it's scalatra writing a compressed response itself.

> Jetty version: 9.4.36.v20210114

Upgrade your version of Jetty, 9.4.36 is subject to several [security advisories](https://www.eclipse.org/jetty/security_reports.php).

> Java version: 1.8.0_101-b13

Ditto, your version of [Java is expired as of November 19, 2016](https://www.oracle.com/java/technologies/javase/8u101-relnotes.html)

**Comment by joakime** [comment]
Make sure you are using Scalatra 2.6.0 (or newer), as it's own internal Gzip implementation is broken and is not thread safe.

* https://github.com/scalatra/scalatra/issues/249 - Gzip Support is broken
* https://github.com/scalatra/scalatra/issues/659 - Remove Gzip Support

**Comment by joakime** [comment]
Closing as issue in Scalatra version you are using.
Not a Jetty issue.

**Comment by SeanRoy** [comment]
Thanks.  I knew about GzipSupoort.  I was using 2.6.5 but still had a servlet that had ContentEncodingSupport mixed in.  GzipSupport code was rolled into ContentEncodingSupport, but apparently it's still broken there.   Once I removed ContentEncodingSupport to rely on jetty it worked.  Thanks again.

**Comment by joakime** [comment]
Thanks for the update.
That will no doubt help others in the future.
