### ISSUE TITLE
Allow CDI injection of HttpSession into WebSocket endpoints.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#6174]
**Jetty version**
10.0.x

**Description**
With the improvements from PR #6119, we are able to inject the `HttpSession` into the WebSocket Endpoint.

However it uses some sort of proxy wrapper around the `HttpSession` and can only be accessed from within the same thread as the call to `doFilter` otherwise it will throw it will throw `ContextNotActiveException`. The class of the wrapper instance is `org.jboss.weldx.servlet.http.HttpSession$$Proxy$_$$_WeldClientProxy`. 

The websocket connection is maintained long after `doFilter()` has returned so using the injected `HttpSession` gives us this `ContextNotActiveException`. We would need to find a way to associate the CDI context with the threads when they are being used by WebSocket, and maybe even propagate the context so it stays active for the life of the WebSocket connection.

```
Caused by: org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.SessionScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89)
	at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)
	at org.jboss.weldx.servlet.http.HttpSession$$Proxy$_$$_WeldClientProxy.getId(Unknown Source)
	at org.eclipse.jetty.cdi.tests.websocket.JavaxWebSocketCdiTest$CdiHttpSessionSocket.onMessage(JavaxWebSocketCdiTest.java:401)
```

**Comment by joakime** [comment]
Closing, fixed in PR #6119
