### ISSUE TITLE
By default, Jetty with HTTPS accepts *any* signature algorithm

### ISSUE THREAD

**Issue by seisvelas** [eclipse/jetty.project#6239]
**Jetty version**

10.0.2

**Java version**

openjdk 11.0.11 2021-04-20

**OS type/version**

Ubuntu 18.04

**Description**

Consider the publicly available Jetty application https://webtide.com/. We can scan it with sslscan, which produces the following results:

```
➜  ✗ sslscan --no-groups --show-sigs webtide.com
Version: 2.0.10-static
OpenSSL 1.1.1l-dev  xx XXX xxxx

Connected to 107.22.210.238

Testing SSL server webtide.com on port 443 using SNI name webtide.com

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   enabled

  TLS Fallback SCSV:
Server does not support TLS Fallback SCSV

  TLS renegotiation:
Session renegotiation not supported

  TLS Compression:
Compression disabled

  Heartbleed:
TLSv1.3 not vulnerable to heartbleed
TLSv1.2 not vulnerable to heartbleed

  Supported Server Cipher(s):
Preferred TLSv1.3  256 bits  TLS_AES_256_GCM_SHA384        Curve 25519 DHE 253
Accepted  TLSv1.3  128 bits  TLS_AES_128_GCM_SHA256        Curve 25519 DHE 253
Accepted  TLSv1.3  256 bits  TLS_CHACHA20_POLY1305_SHA256  Curve 25519 DHE 253
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-CHACHA20-POLY1305   Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve 25519 DHE 253

  Server Signature Algorithm(s):
TLSv1.3  Server accepts all signature algorithms.

  SSL Certificate:
Signature Algorithm: sha256WithRSAEncryption
RSA Key Strength:    2048

Subject:  blogs.webtide.com
Altnames: DNS:blogs.webtide.com, DNS:webtide.com, DNS:www.webtide.com
Issuer:   R3

Not valid before: Mar 30 06:07:59 2021 GMT
Not valid after:  Jun 28 06:07:59 2021 GMT
```

I also tried using cipherscan

```
➜  cipherscan git:(master) ✗ ./cipherscan --sigalg webtide.com
.................Traceback (most recent call last):
  File "cscan.py", line 6, in <module>
    from tlslite.messages import ClientHello, ServerHello, ServerHelloDone, Alert
  File "/home/alex/Code/cipherscan/tlslite/__init__.py", line 25, in <module>
    from tlslite.api import *
  File "/home/alex/Code/cipherscan/tlslite/api.py", line 5, in <module>
    from .constants import AlertLevel, AlertDescription, Fault
  File "/home/alex/Code/cipherscan/tlslite/constants.py", line 11, in <module>
    from .utils.compat import a2b_hex
  File "/home/alex/Code/cipherscan/tlslite/utils/compat.py", line 14, in <module>
    import ecdsa
  File "/home/alex/Code/cipherscan/ecdsa/__init__.py", line 3, in <module>
    import six
ImportError: No module named six
........
Target: webtide.com:443

prio  ciphersuite                  protocols  pfs                 curves
1     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2    ECDH,P-521,521bits  prime256v1,secp384r1,secp521r1
2     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2    ECDH,P-521,521bits  prime256v1,secp384r1,secp521r1
3     ECDHE-RSA-AES256-SHA384      TLSv1.2    ECDH,P-521,521bits  prime256v1,secp384r1,secp521r1
4     ECDHE-RSA-AES128-SHA256      TLSv1.2    ECDH,P-521,521bits  prime256v1,secp384r1,secp521r1

Certificate: trusted, 2048 bits, sha256WithRSAEncryption signature
TLS ticket lifetime hint: None
NPN protocols: None
OCSP stapling: not supported
Cipher ordering: server
Curves ordering: client - fallback: no
Server supports secure renegotiation
Server supported compression methods: NONE

TLSv1.2 ephemeral sigalgs:
no PFS ECDSA ciphers detected
RSA test: intolerant of sigalg removal
Client side sigalg ordering

Supported PFS RSA signature algorithms
prio  sigalg
1     SHA512
2     SHA384
3     SHA256
4     SHA224
5     SHA1

TLS Tolerance: yes
```

As far as I can tell, this problem is true of any Jetty instance. It will accept any signature algorithm. 

Is this intended to be the default behavior? And in either case, how does one configure Jetty to be more stringent about what signature algorithms it will accept?

**Comment by seisvelas** [comment]
I searched for random Jetty servers using Shodan, and it appears that this is quite common. For example, using this random Jetty server that popped up on Shodan:

```
➜  cipherscan git:(master) ✗ sslscan --no-groups --no-ciphersuites --no-heartbleed --no-renegotiation --no-compression --no-cipher-details --show-sigs 154.118.230.22
Version: 2.0.10-static
OpenSSL 1.1.1l-dev  xx XXX xxxx

Connected to 154.118.230.22

Testing SSL server 154.118.230.22 on port 443 using SNI name 154.118.230.22

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   enabled

  TLS Fallback SCSV:
Server does not support TLS Fallback SCSV


  Server Signature Algorithm(s):
TLSv1.3  Server accepts all signature algorithms.

  SSL Certificate:
Signature Algorithm: sha256WithRSAEncryption
RSA Key Strength:    2048

Subject:  tams.judiciary.go.tz
Altnames: DNS:tams.judiciary.go.tz
Issuer:   R3

Not valid before: Apr 30 00:26:52 2021 GMT
Not valid after:  Jul 29 00:26:52 2021 GMT
```

A few didn't have this problem (but they also accepted lots of weak signature algorithms nevertheless), giving me hope that this is configurable!

(sorry if this is super simple, I'm not very experienced with Java and Jetty)

**Comment by sbordet** [comment]
@seisvelas can you detail why you would like the server to _not_ accept all signature schemes? Just curious.

AFAIK, Java does not offer an API to specify signature schemes, but instead it relies on a system property: `jdk.tls.server.SignatureSchemes`, a comma separated list of signature scheme standard names, as defined [here](https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html).

If you start the JVM that runs Jetty with that system property configured with the signature schemes you want, you should be good.

Let us know if that works for you, so that others that have this problem will have a reference. Thanks!

**Comment by seisvelas** [comment]
Thanks for the quick response! 

>can you detail why you would like the server to not accept all signature schemes? Just curious.

Yes - TLS 1.2 in particular accepts some hashes to be used for signatures that are no longer considered secure, like SHA-1. (see https://tools.ietf.org/html/rfc5246#section-7.4.1.4.1)

>AFAIK, Java does not offer an API to specify signature schemes, but instead it relies on a system property: jdk.tls.server.SignatureSchemes, a comma separated list of signature scheme standard names, as defined here.
>
>If you start the JVM that runs Jetty with that system property configured with the signature schemes you want, you should be good.

Awesome, thanks! I'll update this issue to let you know whether this works or not.

**Comment by seisvelas** [comment]
That totally worked. Thanks a lot!
