### ISSUE TITLE
AsyncContext.onCompleted called twice

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#624]
at [this point in the 9.3.x branch](https://github.com/eclipse/jetty.project/tree/f4c13e5f544a581e9489f2531f532b63a6d4b9fd) the CI system gave the following error:
````
Error Message

expected:<0> but was:<1>
Stacktrace

java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.jetty.server.LocalAsyncContextTest.spinAssertEquals(LocalAsyncContextTest.java:657)
	at org.eclipse.jetty.server.LocalAsyncContextTest.spinAssertEquals(LocalAsyncContextTest.java:633)
	at org.eclipse.jetty.server.LocalAsyncContextTest.testTwoCycles(LocalAsyncContextTest.java:224)
Standard Error

2016-06-08 02:05:08.730:INFO:oejs.Server:main: jetty-9.3.10-SNAPSHOT
2016-06-08 02:05:08.736:INFO:oejs.AbstractConnector:main: Started LocalConnector@33cb5951{HTTP/1.1,[http/1.1]}
2016-06-08 02:05:08.736:INFO:oejs.Server:main: Started @46163ms
java.lang.Throwable
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:553)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:680)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:897)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:695)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:451)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:897)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:597)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:99)
	at org.eclipse.jetty.server.LocalAsyncContextTest$SuspendHandler$1.run(LocalAsyncContextTest.java:420)
java.lang.Throwable
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:553)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:680)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:897)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:695)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:451)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
2016-06-08 02:05:09.053:WARN:oejs.HttpChannelState:qtp225290371-418: 
java.lang.IllegalStateException
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:559)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:680)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:897)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:695)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:451)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
2016-06-08 02:05:19.050:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@33cb5951{HTTP/1.1,[http/1.1]}
````

This indicates that onComplete has been called twice!      It is strange that the HttpChannel.run has been called twice, but even if it has been, the atomic state should protect against the double invocation.

**Comment by gregw** [comment]
This is still failing!  @sbordet let's make a time to go over this in fine detail!

```
Regression

org.eclipse.jetty.server.LocalAsyncContextTest.testTwoCycles

Failing for the past 1 build (Since Unstable#329 )
Took 10 sec.
Error Message

expected:<0> but was:<1>
Stacktrace

java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.jetty.server.LocalAsyncContextTest.spinAssertEquals(LocalAsyncContextTest.java:657)
	at org.eclipse.jetty.server.LocalAsyncContextTest.spinAssertEquals(LocalAsyncContextTest.java:633)
	at org.eclipse.jetty.server.LocalAsyncContextTest.testTwoCycles(LocalAsyncContextTest.java:224)
Standard Error

2016-06-10 20:25:28.748:INFO:oejs.Server:main: jetty-9.3.10-SNAPSHOT
2016-06-10 20:25:28.779:INFO:oejs.AbstractConnector:main: Started LocalConnector@33cb5951{HTTP/1.1,[http/1.1]}
2016-06-10 20:25:28.779:INFO:oejs.Server:main: Started @45814ms
java.lang.Throwable
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:553)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:678)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:693)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:451)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ByteArrayEndPoint$1.run(ByteArrayEndPoint.java:55)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
java.lang.Throwable
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:553)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:678)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:693)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:451)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:595)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:99)
	at org.eclipse.jetty.server.LocalAsyncContextTest$SuspendHandler$1.run(LocalAsyncContextTest.java:420)
2016-06-10 20:25:28.782:WARN:oejs.HttpChannelState:Thread-366: 
java.lang.IllegalStateException
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:559)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:678)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:693)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:451)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:595)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:99)
	at org.eclipse.jetty.server.LocalAsyncContextTest$SuspendHandler$1.run(LocalAsyncContextTest.java:420)
2016-06-10 20:25:39.099:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@33cb5951{HTTP/1.1,[http/1.1]}
```

**Comment by gregw** [comment]
b40c2ae is an instrumentation commit.  It should capture the location that HttpChannel is dispatched from.  There are dispatches in HttpInput, HttpOutput and in the HttpChannelState.    So we are still clearly getting an extra dispatch.    Also the previous patch obviously did not protect from duplicate dispatches, so we need to review that as well!

The commit must be reverted once we have debugged

**Comment by gregw** [comment]
It failed again: 
```
Failed

org.eclipse.jetty.server.LocalAsyncContextTest.testTwoCycles

Failing for the past 2 builds (Since Unstable#329 )
Took 10 sec.
Error Message

expected:<0> but was:<1>
Stacktrace

java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.jetty.server.LocalAsyncContextTest.spinAssertEquals(LocalAsyncContextTest.java:704)
	at org.eclipse.jetty.server.LocalAsyncContextTest.spinAssertEquals(LocalAsyncContextTest.java:680)
	at org.eclipse.jetty.server.LocalAsyncContextTest.testTwoCycles(LocalAsyncContextTest.java:239)
Standard Error

2016-06-11 00:40:49.206:INFO:oejs.Server:main: jetty-9.3.10-SNAPSHOT
2016-06-11 00:40:49.212:INFO:oejs.AbstractConnector:main: Started LocalConnector@33cb5951{HTTP/1.1,[http/1.1]}
2016-06-11 00:40:49.212:INFO:oejs.Server:main: Started @47418ms
First onCompleted dispatched from:
java.lang.Throwable
	at org.eclipse.jetty.server.HttpChannel.getRunnable(HttpChannel.java:274)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:595)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:99)
	at org.eclipse.jetty.server.LocalAsyncContextTest$SuspendHandler$1.run(LocalAsyncContextTest.java:435)
First onCompleted:
java.lang.Throwable
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:570)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:678)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:693)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel$1.run(HttpChannel.java:283)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:595)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:99)
	at org.eclipse.jetty.server.LocalAsyncContextTest$SuspendHandler$1.run(LocalAsyncContextTest.java:435)
Second onCompleted dispatched from:
java.lang.Throwable
	at org.eclipse.jetty.server.HttpChannel.getRunnable(HttpChannel.java:274)
	at org.eclipse.jetty.server.HttpChannelState.scheduleDispatch(HttpChannelState.java:751)
	at org.eclipse.jetty.server.HttpChannelState.dispatch(HttpChannelState.java:471)
	at org.eclipse.jetty.server.AsyncContextState.dispatch(AsyncContextState.java:121)
	at org.eclipse.jetty.server.LocalAsyncContextTest$SuspendHandler$4.run(LocalAsyncContextTest.java:533)
java.lang.Throwable
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:570)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:678)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:693)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel$1.run(HttpChannel.java:283)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
2016-06-11 00:40:49.529:WARN:oejs.HttpChannelState:qtp225290371-417: 
java.lang.IllegalStateException
	at org.eclipse.jetty.server.LocalAsyncContextTest$1.onComplete(LocalAsyncContextTest.java:590)
	at org.eclipse.jetty.server.HttpChannelState$3.run(HttpChannelState.java:678)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:895)
	at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:693)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:476)
	at org.eclipse.jetty.server.HttpChannel$1.run(HttpChannel.java:283)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
2016-06-11 00:40:59.542:INFO:oejs.AbstractConnector:main: Stopped LocalConnector@33cb5951{HTTP/1.1,[http/1.1]}
```

**Comment by sbordet** [comment]
@gregw had a look, does not make any sense.

Assuming you are running the code that is in the `jetty-9.3.x` branch, the test explicitly sets `completeAfter=-1`.
However, the first stack trace reported above shows that the first `complete()` comes from line 435, which is inside an `if` block that is only executed when `completeAfter>0`, that is why it does not make sense.

There are a few `static` variables in that test, which are unnecessary and may "remember" things from a previous test.
I'll rewrite the test getting rid of the `static`s.

**Comment by gregw** [comment]
This was a false alarm and the problem was bad statics in the unit tests.

**Comment by gregw** [comment]
The problem is a race with setting the async timeout in the [HttpChannelState.unhandle](https://github.com/eclipse/jetty.project/blob/jetty-9.3.9.v20160517/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java#L368-L420) method.   The async event is copied within the locked block, but then tested and used to set the timer after the lock is released.  If the thread is preempted before setting the timer, another thread can complete the async context, so when the timer is eventually set, it is done on a subsequent usage of the request object.

The solution appears to be to set the timer while the lock is held.

**Comment by gregw** [comment]
@joakime @jmcc0nn3ll Can we re-roll 9.3.10 release to include this fix?
