### ISSUE TITLE
Server can throw NullPointerException when cleaning up dead HTTP2 connections

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#6248]
**Jetty version**
10.0.2, 11.0.2

**Description**

When the server processes HTTP2 connections and the client abruptly closes the TCP connection (for instance because the client process crashed) the server way end up tripping on a NPE while trying to cleanup the dead connection.

Here is the NPE's stack trace:

```
java.lang.NullPointerException: null
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.failAllContent(HttpChannelOverHTTP2.java:590)
	at org.eclipse.jetty.server.AsyncContentProducer.consumeAll(AsyncContentProducer.java:183)
	at org.eclipse.jetty.server.HttpInput.consumeAll(HttpInput.java:155)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.consumeInput(HttpChannelOverHTTP2.java:682)
	at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:676)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:194)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:177)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:172)
	at org.eclipse.jetty.http2.HTTP2Stream.notifyFailure(HTTP2Stream.java:822)
	at org.eclipse.jetty.http2.HTTP2Stream.onFailure(HTTP2Stream.java:530)
	at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:353)
	at org.eclipse.jetty.http2.HTTP2Session.failStream(HTTP2Session.java:582)
	at org.eclipse.jetty.http2.HTTP2Session.onFailure(HTTP2Session.java:557)
	at org.eclipse.jetty.http2.HTTP2Session.abort(HTTP2Session.java:544)
	at org.eclipse.jetty.http2.HTTP2Session$StreamsState.onShutdown(HTTP2Session.java:1824)
	at org.eclipse.jetty.http2.HTTP2Session.onShutdown(HTTP2Session.java:964)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:214)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:161)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:384)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.Invocable.invokeNonBlocking(Invocable.java:64)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.invokeTask(EatWhatYouKill.java:345)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:300)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lorban** [comment]
Besides logging the NPE this is pretty much harmless as the root cause is that there are two threads competing to cleanup the same data, so the NPE is logged but ignored by the server and all resources are eventually freed.

Adding a simple null-check in the code to make the `HttpChannelOverHTTP2.failAllContent()` method do nothing if the `getStream()` method returns null should be all it takes to solve this problem.
