### ISSUE TITLE
If jmx and websocket is enabled, redploying a context produces a NullPointerException

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#633]
Reproduceable on jetty-9.3.x and master, so I assume also jetty-9.4.x too.

Here's the log trace showing the problem from jetty-9.3.x:

[1146] java -jar ../start.jar
2016-06-10 17:51:15.694:INFO::main: Logging initialized @224ms
2016-06-10 17:51:15.858:INFO:oejs.Server:main: jetty-9.3.10-SNAPSHOT
2016-06-10 17:51:15.871:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/janb/src/jetty-eclipse/jetty-9.3.x/jetty-distribution/target/distribution/janb-base/webapps/] at interval 1
2016-06-10 17:51:16.093:WARN::main: test webapp is deployed. DO NOT USE IN PRODUCTION!
2016-06-10 17:51:16.097:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /test, did not find org.eclipse.jetty.jsp.JettyJspServlet
2016-06-10 17:51:16.291:INFO:oejsh.ManagedAttributeListener:main: update PushFilter null->org.eclipse.jetty.servlets.PushCacheFilter@305b7c14 on o.e.j.w.WebAppContext@5b87ed94{/test,file:///tmp/jetty-test.war-_test-any-7997797429805663963.dir/webapp/,STARTING}{/test.war}
2016-06-10 17:51:16.292:INFO:oejsh.ManagedAttributeListener:main: update QoSFilter null->org.eclipse.jetty.servlets.QoSFilter@bccb269 on o.e.j.w.WebAppContext@5b87ed94{/test,file:///tmp/jetty-test.war-_test-any-7997797429805663963.dir/webapp/,STARTING}{/test.war}
2016-06-10 17:51:16.293:WARN:oeju.DeprecationWarning:main: Using @Deprecated Class org.eclipse.jetty.servlets.MultiPartFilter
2016-06-10 17:51:16.294:WARN:oejs.ServletHolder:main: Unable to make package for jsp /jsp/foo/foo.jsp trying jsp.foo.foo.jsp instead
2016-06-10 17:51:16.294:WARN:oejs.ServletHolder:main: Unable to make identifier for jsp foo.jsp trying foo_jsp instead
2016-06-10 17:51:16.309:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@5b87ed94{/test,file:///tmp/jetty-test.war-_test-any-7997797429805663963.dir/webapp/,AVAILABLE}{/test.war}
2016-06-10 17:51:16.336:INFO:oejs.Server:main: Started @866ms

2016-06-10 17:51:55.733:WARN:oejd.DeploymentManager:Scanner-0: Unable to reach node goal: undeployed
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
	at org.eclipse.jetty.jmx.MBeanContainer.beanRemoved(MBeanContainer.java:221)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.removeEventListener(ContainerLifeCycle.java:565)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.remove(ContainerLifeCycle.java:534)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.removeBean(ContainerLifeCycle.java:519)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.removeEventListener(ContainerLifeCycle.java:568)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.remove(ContainerLifeCycle.java:534)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.removeBean(ContainerLifeCycle.java:519)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.removeEventListener(ContainerLifeCycle.java:568)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.remove(ContainerLifeCycle.java:534)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.removeBean(ContainerLifeCycle.java:519)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.unmanage(ContainerLifeCycle.java:453)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.unmanage(ContainerLifeCycle.java:437)
	at org.eclipse.jetty.deploy.bindings.StandardStopper.processBinding(StandardStopper.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:459)
	at org.eclipse.jetty.deploy.DeploymentManager.removeApp(DeploymentManager.java:410)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileChanged(ScanningAppProvider.java:192)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileChanged(WebAppProvider.java:415)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileChanged(ScanningAppProvider.java:70)
	at org.eclipse.jetty.util.Scanner.reportChange(Scanner.java:664)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:532)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:329)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
2016-06-10 17:51:55.844:WARN::Scanner-0: test webapp is deployed. DO NOT USE IN PRODUCTION!
2016-06-10 17:51:55.845:INFO:oejw.StandardDescriptorProcessor:Scanner-0: NO JSP Support for /test, did not find org.eclipse.jetty.jsp.JettyJspServlet
2016-06-10 17:51:55.878:INFO:oejsh.ManagedAttributeListener:Scanner-0: update PushFilter null->org.eclipse.jetty.servlets.PushCacheFilter@2fe36b7c on o.e.j.w.WebAppContext@46e5620b{/test,file:///tmp/jetty-test.war-_test-any-1236960566626231429.dir/webapp/,STARTING}{/test.war}
2016-06-10 17:51:55.880:INFO:oejsh.ManagedAttributeListener:Scanner-0: update QoSFilter null->org.eclipse.jetty.servlets.QoSFilter@67a01fdd on o.e.j.w.WebAppContext@46e5620b{/test,file:///tmp/jetty-test.war-_test-any-1236960566626231429.dir/webapp/,STARTING}{/test.war}
2016-06-10 17:51:55.881:WARN:oeju.DeprecationWarning:Scanner-0: Using @Deprecated Class org.eclipse.jetty.servlets.MultiPartFilter
2016-06-10 17:51:55.881:WARN:oejs.ServletHolder:Scanner-0: Unable to make package for jsp /jsp/foo/foo.jsp trying jsp.foo.foo.jsp instead
2016-06-10 17:51:55.882:WARN:oejs.ServletHolder:Scanner-0: Unable to make identifier for jsp foo.jsp trying foo_jsp instead
2016-06-10 17:51:55.892:INFO:oejsh.ContextHandler:Scanner-0: Started o.e.j.w.WebAppContext@46e5620b{/test,file:///tmp/jetty-test.war-_test-any-1236960566626231429.dir/webapp/,AVAILABLE}{/test.war}
^C2016-06-10 17:52:35.663:INFO:oejsh.ManagedAttributeListener:Thread-1: update PushFilter org.eclipse.jetty.servlets.PushCacheFilter@2fe36b7c->null on o.e.j.w.WebAppContext@46e5620b{/test,file:///tmp/jetty-test.war-_test-any-1236960566626231429.dir/webapp/,UNAVAILABLE}{/test.war}
2016-06-10 17:52:35.664:INFO:oejsh.ManagedAttributeListener:Thread-1: update QoSFilter org.eclipse.jetty.servlets.QoSFilter@67a01fdd->null on o.e.j.w.WebAppContext@46e5620b{/test,file:///tmp/jetty-test.war-_test-any-1236960566626231429.dir/webapp/,UNAVAILABLE}{/test.war}
2016-06-10 17:52:35.664:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@46e5620b{/test,file:///tmp/jetty-test.war-_test-any-1236960566626231429.dir/webapp/,UNAVAILABLE}{/test.war}

**Comment by joakime** [comment]
@janbartel what's in your `/janb-base/` ?

Also, why are you deploying deprecated concepts in your base?
> 2016-06-10 17:51:16.293:WARN:oeju.DeprecationWarning:main: Using @Deprecated Class org.eclipse.jetty.servlets.MultiPartFilter

**Comment by janbartel** [comment]
I deployed the standard test.war from demo-base.

**Comment by gregw** [comment]
I incorrectly labelled the following two commits for #663 instead of #633
0e5de87d49217c2034a47b0a2c2639e7ccb44be1
a8e315a3f5509ae15d1a1478e840668554fd3cab
