### ISSUE TITLE
i found a lot of threads "waiting on condition" status

### ISSUE THREAD

**Issue by xinguangduan** [eclipse/jetty.project#6337]
**Jetty version** 
9.4.40.v20210413
**Java version**
 jdk1.8
**Question**
i found a lot of threads "waiting on condition" status,and CPU up to 289%,like as below, need i to tune the thread pool? 

current thread pool config:

threadPool.setMinThreads(100);
threadPool.setMaxThreads(2000);
threadPool.setDetailedDump(false);

and the server info: 4 core 32G mem

who can answer my question? thanks a lot !

"qtp740827140-461545" #461545 prio=5 os_prio=0 tid=0x0000000007b79800 nid=0x5f0d2 waiting on condition [0x00007f44568d4000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004fab3bb58> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:656)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.access$800(QueuedThreadPool.java:46)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:720)
        at java.lang.Thread.run(Thread.java:748)

**Comment by gregw** [comment]
That stacktrace is of an idle thread in the thread pool waiting for a new job.  Those threads should be using no CPU, so the 289% is likely coming from other threads.
I think this is normal behaviour, no tuning is needed as if you have excess idle threads they will decay over time.
