### ISSUE TITLE
Jetty Client Http2 Connection gracefulShutdown customize

### ISSUE THREAD

**Issue by linking12** [eclipse/jetty.project#6368]
**Jetty version**
  Jetty 9.4.41
**Java version**
  JDK8
**Question**
when use Jetty h2c client on prod, we got some exception;
```
Caused by: java.nio.channels.AsynchronousCloseException
at org.eclipse.jetty.http2.client.http.HttpConnectionOverHTTP2.close(HttpConnectionOverHTTP2.java:133)
at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2.onClose(HttpClientTransportOverHTTP2.java:170)
at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2$SessionListenerPromise.onClose(HttpClientTransportOverHTTP2.java:232)
at org.eclipse.jetty.http2.api.Session$Listener.onClose(Session.java:214)
at org.eclipse.jetty.http2.HTTP2Session.notifyClose(HTTP2Session.java:1071)
at org.eclipse.jetty.http2.HTTP2Session$StreamsState.terminate(HTTP2Session.java:1988)
```
i think jetty not graceful shutdown connection. 

my Question is:
1: if my guess is right,  i can not find any way to set graceful shutdown timeout, for netty, there is some configuration to set graceful shutdown like this
   ```
 HttpToHttp2ConnectionHandler connectionHandler =
            new HttpToHttp2ConnectionHandlerBuilder().frameListener(listener)//
                .headerSensitivityDetector(Http2HeadersEncoder.ALWAYS_SENSITIVE)//
                .frameLogger(new ProxyConnectionHttp2FrameLogger(LogLevel.INFO, this))
                .gracefulShutdownTimeoutMillis(proxyServer.getReadTimeout() * 1000L) // set gracefulshutdowntimeout
   ```
2: if my guess is wrong, why we got this exception， we do not have any exception on server （Tomcat）

**Comment by sbordet** [comment]
Please report the whole stack trace, not just part of it.

You need to clarify what you mean by "graceful shutdown". 
If the server sent a GOAWAY, the connection will be closed.

We have implemented a more "graful" shutdown in Jetty 10, but not backported to 9, see https://github.com/eclipse/jetty.project/issues/5645.

Can you try Jetty 10?

**Comment by linking12** [comment]
> Please report the whole stack trace, not just part of it.
> 
> You need to clarify what you mean by "graceful shutdown".
> If the server sent a GOAWAY, the connection will be closed.
> 
> We have implemented a more "graful" shutdown in Jetty 10, but not backported to 9, see #5645.
> 
> Can you try Jetty 10?

I think this is our mistake；
Tomcat H2C keepaliveTime is 20S，but we set jetty idleTimeout to 55s, we must set Tomcat keepaliveTime to 60s.
