### ISSUE TITLE
Unused caching in ImportHandler

### ISSUE THREAD

**Issue by benjamindahon** [eclipse/jetty.project#637]
Hi,

We are experiencing performance issues on our production systems. We are using jetty 9.3.8.v20160314.

After some investigation, most threads were busy loading classes, with stacks like

```
at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	- locked &lt;0x000000078842bfd0&gt; (a java.lang.ClassNotFoundException)
	at java.lang.Throwable.&lt;init&gt;(Throwable.java:287)
	at java.lang.Exception.&lt;init&gt;(Exception.java:84)
	at java.lang.ReflectiveOperationException.&lt;init&gt;(ReflectiveOperationException.java:75)
	at java.lang.ClassNotFoundException.&lt;init&gt;(ClassNotFoundException.java:82)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	- locked &lt;0x00000006460743e0&gt; (a java.lang.Object)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	- locked &lt;0x00000006459834b0&gt; (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:460)
	- locked &lt;0x0000000645a615f0&gt; (a java.lang.Object)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
	at javax.el.ImportHandler.findClass(ImportHandler.java:195)
	at javax.el.ImportHandler.resolveClass(ImportHandler.java:164)
	at javax.servlet.jsp.el.ScopedAttributeELResolver.getValue(ScopedAttributeELResolver.java:62)
	at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:110)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:80)
	at org.apache.el.parser.AstEmpty.getValue(AstEmpty.java:46)
	at org.apache.el.parser.AstChoice.getValue(AstChoice.java:44)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
	at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:9

```

After debugging the code, I found that the cache in the javax.el.ImportHandler class is not properly used. This class is instanciated by javax.el.ELContext (through org.apache.el.lang.EvaluationContext).

Whenever an expression is created, a new instance of ImportHandler is also created. ImportHandler holds a reference to a local cache (ConcurrentHashMap) which is an instance variable (not static), and therefore it nevers gets used longer than an expression lifetime. ImportHandler is responsible of loading classes. 

I changed the code to make use of static caches. The result we got are far better. For instance with Apache AB, we got the following results:

Before the change:

> Requests per second:    10.47 [#/sec] (mean)
> Time per request:       954.681 [ms] (mean)

After the change:

> Requests per second:    21.28 [#/sec] (mean)
> Time per request:       470.022 [ms] (mean)

I am happy to make a PR for these changes, if you think this is actually a bug / improvement

Thanks,
Benjamin

**Comment by joakime** [comment]
WebAppClassLoader used to have class caching, but it was ripped out due to the increasing number of new bugs it produced in other 3rd party libraries (in spring, weld, hibernate, and jersey to name a few).

How would you propose to fix this WITHOUT reintroducing class caching in the WebAppClassLoader?

**Comment by benjamindahon** [comment]
No I didn't change the ClassLoader. I only changed javax.el.ImportHandler class. I think this class ought to be either a singleton or have static attributes. 

I went for the static option, as this was well easier to test.

**Comment by sbordet** [comment]
`javax.el.ImportHandler` is a class provided by the specification, [JSR 341](https://www.jcp.org/en/jsr/detail?id=341). We cannot change it in the Jetty project.

You may want to report this to the specification lead and/or to the Apache project that implements `javax.el`. 

I doubt, however, that is only a matter of making data structures `static`, because caching loaded classes can interfere with applications as reported by @joakime.

**Comment by benjamindahon** [comment]
Will do. Thanks
