### ISSUE TITLE
Jetty 10 + slf4j 1.7.31 + logback 1.2.3: NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by jnehlmeier** [eclipse/jetty.project#6466]
**Jetty version**

10.0.5

**Question**

I am trying to upgrade our jetty 9.x setup to jetty 10 and since we used SLF4J 1.7.31 and Logback 1.2.3 before I wanted to continue using it with Jetty 10. However it seems like that Jetty 10 logging modules do not add slf4j-api.jar into the lib folder which likely causes the `NoClassDefFoundError: org/slf4j/LoggerFactory`. When I use the default library versions that Jetty 10 uses (SLF4J 2.0.0-alpha1 and Logback 1.3.0.alpha5) the issue does not appear (even though `slf4j-api.jar` is still not in the lib folder)

Working default case:
```
java -jar ../jetty-home-10.0.5/start.jar --add-module=logging-jul-capture,logging-logback,webapp --approve-all-licenses


➜  jetty-base-logging-test> ls -la lib/logging 
total 1472
drwxr-xr-x  5 jens  staff     160 23 Jun 17:04 .
drwxr-xr-x  3 jens  staff      96 23 Jun 17:04 ..
-rw-r--r--  1 jens  staff    4775 23 Jun 17:04 jul-to-slf4j-2.0.0-alpha1.jar
-rw-r--r--  1 jens  staff  246724 23 Jun 17:04 logback-classic-1.3.0-alpha5.jar
-rw-r--r--  1 jens  staff  493163 23 Jun 17:04 logback-core-1.3.0-alpha5.jar


➜  jetty-base-logging-test> java -jar ../jetty-home-10.0.5/start.jar                                                                               
17:05:18.393 [INFO] :main: (org.eclipse.jetty.server.Server) - jetty-10.0.5; built: 2021-06-11T14:18:43.438Z; git: dc21b2d73cafd78a56e8e532cf50863739bd7027; jvm 15.0.2+7
17:05:18.420 [INFO] :main: (org.eclipse.jetty.server.Server) - Started Server@557caf28{STARTING}[10.0.5,sto=5000] @395ms
``` 

Failing case:
```
➜  jetty-base-logging-test> java -jar ../jetty-home-10.0.5/start.jar --add-module=logging-jul-capture,logging-logback,webapp slf4j.version=1.7.31 logback.version=1.2.3 --approve-all-licenses


➜  jetty-base-logging-test> ls -la lib/logging                                                                                                                                                
total 1512
drwxr-xr-x  5 jens  staff     160 23 Jun 17:06 .
drwxr-xr-x  3 jens  staff      96 23 Jun 17:06 ..
-rw-r--r--  1 jens  staff    4592 23 Jun 17:06 jul-to-slf4j-1.7.31.jar
-rw-r--r--  1 jens  staff  290339 23 Jun 17:06 logback-classic-1.2.3.jar
-rw-r--r--  1 jens  staff  471901 23 Jun 17:06 logback-core-1.2.3.jar


➜  jetty-base-logging-test> java -jar ../jetty-home-10.0.5/start.jar slf4j.version=1.7.31 logback.version=1.2.3
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.eclipse.jetty.xml.XmlConfiguration.<clinit>(XmlConfiguration.java:83)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

I have seen that Jetty 10 has a module `logging/slf4j` which puts `slf4j-api` on classpath, but it seems like no logging related module has a `[files]` section to actually download the api and put it into `lib/logging`. When I manually download `slf4j-api-1.7.31.jar` and put it into `lib/logging` then the `NoClassDefFoundError` disappears and jetty starts.

So I guess there is some issue in your module files and you should make sure that the SLF4J api ends up on classpath?

Also as a side question:

When I am not using the default versions of libraries that modules are defining, then I always have to add these versions to the command line (e.g. as seen above or for example `--list-config slf4j.version=1.7.31 logback.version=1.2.3`) so that jetty finds the jars with their version. Wouldn't it make sense to store the version properties used to create the jetty base folder somewhere inside the jetty base folder? So we don't have to repeat them for every command? Or do you expect users to create a custom module that only sets version properties and then add that custom module to jetty?

**Comment by joakime** [comment]
Please run with `.../start.jar --list-config` in your failing case and report back it's output.

**Comment by jnehlmeier** [comment]
```
➜  jetty-base-logging-test> java -jar ../jetty-home-10.0.5/start.jar --add-module="logging-jul-capture,logging-logback,webapp" slf4j.version=1.7.31 logback.version=1.2.3 --approve-all-licenses
INFO  : All Licenses Approved via Command Line Option
INFO  : mkdir ${jetty.base}/start.d
INFO  : webapp          initialized in ${jetty.base}/start.d/webapp.ini
INFO  : logging-jul-capture initialized in ${jetty.base}/start.d/logging-jul-capture.ini
INFO  : server          transitively enabled, ini template available with --add-module=server
INFO  : security        transitively enabled
INFO  : servlet         transitively enabled
INFO  : logging-logback initialized in ${jetty.base}/start.d/logging-logback.ini
INFO  : resources       transitively enabled
INFO  : threadpool      transitively enabled, ini template available with --add-module=threadpool
INFO  : logging/slf4j   dynamic dependency of logging-jul-capture
INFO  : logging/slf4j   transitive provider of logging/slf4j for logging-logback
INFO  : bytebufferpool  transitively enabled, ini template available with --add-module=bytebufferpool
INFO  : mkdir ${jetty.base}/lib/logging
INFO  : download https://repo1.maven.org/maven2/org/slf4j/jul-to-slf4j/1.7.31/jul-to-slf4j-1.7.31.jar to ${jetty.base}/lib/logging/jul-to-slf4j-1.7.31.jar
INFO  : mkdir ${jetty.base}/resources
INFO  : copy ${jetty.home}/modules/logging/jul/resources/java-util-logging-bridge.properties to ${jetty.base}/resources/java-util-logging.properties
INFO  : copy ${jetty.home}/modules/logging/logback/resources/logback.xml to ${jetty.base}/resources/logback.xml
INFO  : download https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar to ${jetty.base}/lib/logging/logback-classic-1.2.3.jar
INFO  : download https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar to ${jetty.base}/lib/logging/logback-core-1.2.3.jar
INFO  : Base directory was modified



➜  jetty-base-logging-test> java -jar ../jetty-home-10.0.5/start.jar --list-config slf4j.version=1.7.31 logback.version=1.2.3

Enabled Modules:
----------------
    0) resources       transitive provider of resources for logging-logback
    1) logging/slf4j   dynamic dependency of logging-logback
                       transitive provider of logging/slf4j for logging-jul-capture
                       transitive provider of logging/slf4j for logging-logback
    2) logging-logback ${jetty.base}/start.d/logging-logback.ini
    3) bytebufferpool  transitive provider of bytebufferpool for server
                       init template available with --add-module=bytebufferpool
    4) logging-jul-capture ${jetty.base}/start.d/logging-jul-capture.ini
    5) threadpool      transitive provider of threadpool for server
                       init template available with --add-module=threadpool
    6) server          transitive provider of server for servlet
                       init template available with --add-module=server
    7) security        transitive provider of security for webapp
    8) servlet         transitive provider of servlet for webapp
    9) webapp          ${jetty.base}/start.d/webapp.ini

Java Environment:
-----------------
 java.home = /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home (null)
 java.vm.vendor = AdoptOpenJDK (null)
 java.vm.version = 15.0.2+7 (null)
 java.vm.name = OpenJDK 64-Bit Server VM (null)
 java.vm.info = mixed mode, sharing (null)
 java.runtime.name = OpenJDK Runtime Environment (null)
 java.runtime.version = 15.0.2+7 (null)
 java.io.tmpdir = /var/folders/5f/snlsg3v94c5chmb8b412czvh0000gn/T/ (null)
 user.dir = /Users/jens/Entwicklung/Servers/jetty-base-logging-test (null)
 user.language = de (null)
 user.country = DE (null)

Jetty Environment:
-----------------
 jetty.version = 10.0.5
 jetty.tag.version = jetty-10.0.5
 jetty.build = dc21b2d73cafd78a56e8e532cf50863739bd7027
 jetty.home = /Users/jens/Entwicklung/Servers/jetty-home-10.0.5
 jetty.base = /Users/jens/Entwicklung/Servers/jetty-base-logging-test

Config Search Order:
--------------------
 <command-line>
 ${jetty.base} -> /Users/jens/Entwicklung/Servers/jetty-base-logging-test
 ${jetty.home} -> /Users/jens/Entwicklung/Servers/jetty-home-10.0.5

JVM Arguments:
--------------
 -Djava.util.logging.config.file=${jetty.base}/resources/java-util-logging.properties

System Properties:
------------------
 (no system properties specified)

Properties:
-----------
 java.version = 15.0.2
 java.version.major = 15
 java.version.micro = 2
 java.version.minor = 0
 java.version.platform = 15
 jetty.base = /Users/jens/Entwicklung/Servers/jetty-base-logging-test
 jetty.base.uri = file:///Users/jens/Entwicklung/Servers/jetty-base-logging-test
 jetty.home = /Users/jens/Entwicklung/Servers/jetty-home-10.0.5
 jetty.home.uri = file:///Users/jens/Entwicklung/Servers/jetty-home-10.0.5
 jetty.webapp.addServerClasses = ch.qos.logback.,org.slf4j.
 logback.version = 1.2.3
 runtime.feature.alpn = true
 slf4j.version = 1.7.31

Jetty Server Classpath:
-----------------------
Version Information on 13 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    (dir) | ${jetty.base}/resources
 1:                    1.2.3 | ${jetty.base}/lib/logging/logback-classic-1.2.3.jar
 2:                    1.2.3 | ${jetty.base}/lib/logging/logback-core-1.2.3.jar
 3:                   1.7.31 | ${jetty.base}/lib/logging/jul-to-slf4j-1.7.31.jar
 4:                    4.0.6 | ${jetty.home}/lib/jetty-servlet-api-4.0.6.jar
 5:                   10.0.5 | ${jetty.home}/lib/jetty-http-10.0.5.jar
 6:                   10.0.5 | ${jetty.home}/lib/jetty-server-10.0.5.jar
 7:                   10.0.5 | ${jetty.home}/lib/jetty-xml-10.0.5.jar
 8:                   10.0.5 | ${jetty.home}/lib/jetty-util-10.0.5.jar
 9:                   10.0.5 | ${jetty.home}/lib/jetty-io-10.0.5.jar
10:                   10.0.5 | ${jetty.home}/lib/jetty-security-10.0.5.jar
11:                   10.0.5 | ${jetty.home}/lib/jetty-servlet-10.0.5.jar
12:                   10.0.5 | ${jetty.home}/lib/jetty-webapp-10.0.5.jar

Jetty Active XMLs:
------------------
 ${jetty.home}/etc/jetty-bytebufferpool.xml
 ${jetty.home}/etc/jetty-threadpool.xml
 ${jetty.home}/etc/jetty.xml
 ${jetty.home}/etc/jetty-webapp.xml



➜  jetty-base-logging-test> java -jar ../jetty-home-10.0.5/start.jar slf4j.version=1.7.31 logback.version=1.2.3 
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.eclipse.jetty.xml.XmlConfiguration.<clinit>(XmlConfiguration.java:83)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

**Comment by jnehlmeier** [comment]
I think it generally looks fine, except the missing api library. Maybe newer Logback versions include some api classes so that the issue does not appear with the default Logback version that jetty 10 uses.

**Comment by joakime** [comment]
In the case of ...

```
java -jar ../jetty-home-10.0.5/start.jar --list-config slf4j.version=1.7.31 logback.version=1.2.3
```

The `logging-logback` can be refreshed with `--create-files`, but the `logging/slf4j` dynamic module will not refresh, as it's both a dynamic/internal module, and it detects the slf4j-api present on the `${jetty.home}` path.

Perhaps we should make `logging/slf4j` more formalized?

You can always call `--download=<uri>` for example ...

``` shell
$ java -jar ../../jetty-home-10.0.5/start.jar --download=maven://org.slf4j/slf4j-api/1.7.31/jar\|lib/logging/slf4j-api-1.7.31.jar
INFO  : download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.31/slf4j-api-1.7.31.jar to ${jetty.base}/lib/logging/slf4j-api-1.7.31.jar
INFO  : Base directory was modified
$ java -jar ../../jetty-home-10.0.5/start.jar --list-config slf4j.version=1.7.31 logback.version=1.2.3

Enabled Modules:
----------------
    0) resources       transitive provider of resources for logging-logback
    1) logging/slf4j   dynamic dependency of logging-logback
                       transitive provider of logging/slf4j for logging-logback
    2) logging-logback ${jetty.base}/start.d/logging-logback.ini
    3) bytebufferpool  transitive provider of bytebufferpool for server
                       init template available with --add-module=bytebufferpool
    4) threadpool      transitive provider of threadpool for server
                       init template available with --add-module=threadpool
    5) server          transitive provider of server for servlet
                       init template available with --add-module=server
    6) security        transitive provider of security for webapp
    7) servlet         transitive provider of servlet for webapp
    8) webapp          transitive provider of webapp for deploy
                       init template available with --add-module=webapp
    9) deploy          ${jetty.base}/start.d/deploy.ini

Java Environment:
-----------------
 java.home = /home/joakim/java/jvm/jdk-11.0.10+9 (null)
..(snip)..

Jetty Environment:
-----------------
 jetty.version = 10.0.5
 jetty.tag.version = jetty-10.0.5
 jetty.build = dc21b2d73cafd78a56e8e532cf50863739bd7027
 jetty.home = /home/joakim/code/jetty/distros/jetty-home-10.0.5
 jetty.base = /home/joakim/code/jetty/distros/bases/logging-10-base

Config Search Order:
--------------------
 <command-line>
 ${jetty.base} -> /home/joakim/code/jetty/distros/bases/logging-10-base
 ${jetty.home} -> /home/joakim/code/jetty/distros/jetty-home-10.0.5

JVM Arguments:
--------------
 (no jvm args specified)

System Properties:
------------------
 (no system properties specified)

Properties:
-----------
 java.version = 11.0.10
 java.version.major = 11
 java.version.micro = 10
 java.version.minor = 0
 java.version.platform = 11
 jetty.base = /home/joakim/code/jetty/distros/bases/logging-10-base
 jetty.base.uri = file:///home/joakim/code/jetty/distros/bases/logging-10-base
 jetty.home = /home/joakim/code/jetty/distros/jetty-home-10.0.5
 jetty.home.uri = file:///home/joakim/code/jetty/distros/jetty-home-10.0.5
 jetty.webapp.addServerClasses = ch.qos.logback.,org.slf4j.
 logback.version = 1.2.3
 runtime.feature.alpn = true
 slf4j.version = 1.7.31

Jetty Server Classpath:
-----------------------
Version Information on 14 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    (dir) | ${jetty.base}/resources
 1:                   1.7.31 | ${jetty.base}/lib/logging/slf4j-api-1.7.31.jar
 2:                    1.2.3 | ${jetty.base}/lib/logging/logback-classic-1.2.3.jar
 3:                    1.2.3 | ${jetty.base}/lib/logging/logback-core-1.2.3.jar
 4:                    4.0.6 | ${jetty.home}/lib/jetty-servlet-api-4.0.6.jar
 5:                   10.0.5 | ${jetty.home}/lib/jetty-http-10.0.5.jar
 6:                   10.0.5 | ${jetty.home}/lib/jetty-server-10.0.5.jar
 7:                   10.0.5 | ${jetty.home}/lib/jetty-xml-10.0.5.jar
 8:                   10.0.5 | ${jetty.home}/lib/jetty-util-10.0.5.jar
 9:                   10.0.5 | ${jetty.home}/lib/jetty-io-10.0.5.jar
10:                   10.0.5 | ${jetty.home}/lib/jetty-security-10.0.5.jar
11:                   10.0.5 | ${jetty.home}/lib/jetty-servlet-10.0.5.jar
12:                   10.0.5 | ${jetty.home}/lib/jetty-webapp-10.0.5.jar
13:                   10.0.5 | ${jetty.home}/lib/jetty-deploy-10.0.5.jar

Jetty Active XMLs:
------------------
 ${jetty.home}/etc/jetty-bytebufferpool.xml
 ${jetty.home}/etc/jetty-threadpool.xml
 ${jetty.home}/etc/jetty.xml
 ${jetty.home}/etc/jetty-webapp.xml
 ${jetty.home}/etc/jetty-deploy.xml

```

**Comment by jnehlmeier** [comment]
Oh I see, and `jetty.home` provides the `2.0.0-alpha1` version, that's why it works in the default case.

Do you absolutely have to provide `slf4j-api-2.0.0-alpha1` through `jetty.home`? Adding a `[files]` section to `logging/slf4j` that downloads the correct file would be preferable as it is consistent. However then you must make sure that this module is always active because Jetty requires SLF4J API to be always available, right?

**Comment by janbartel** [comment]
@jnehlmeier maybe something like this would be possible, although undesirable that you couldn't run jetty straight out of the box without incurring a download. This will be part of the discussion of how we could support an older version of slf4j api that was raised in #6385.

**Comment by gregw** [comment]
We should just add the jar from it's maven coordinates.  It wont be downloaded because we put the file in place in the distro, but if the version is changed then the new jar will be downloaded

**Comment by janbartel** [comment]
@gregw  unfortunately I don't think this will work:  the target destination of the `maven:` download directive is always relative to `$jetty.base` and is copied directly from the maven local repo to `$jetty.base`; if there is no local repo, then it would be downloaded from maven central. Thus, on some production machines there won't be a local repo, so jetty would always need to do a download from maven central at install time - I think we want to avoid that.
