### ISSUE TITLE
Thread stuck on parsing infinite loop on invalid HTTP chunked response

### ISSUE THREAD

**Issue by baranvtek** [eclipse/jetty.project#6528]
**Jetty version(s)**
Jetty client 9.3.16.v20170120
**Java version/vendor** `(use: java -version)`
jdk1.8.0_281

**OS type/version**
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Description**
We discovered this issue during E2E integration with another company's team which was sending invalid chunked response and it will be fixed on their end. Nevertheless it might worth to fix also on jetty client as well.

When endpoint responds with 2 HTTP chunked responses with HTTP Status 200, and the second response ends with only 2 chunk endings:
0\r\n
\r\n
0\r\n
\r\n 

Jetty parser hangs at:
"http-bio-7140-exec-161" #495328 daemon prio=5 os_prio=0 tid=0x00007f4e5c0e1000 nid=0x1ad42 runnable [0x00007f4cae7cc000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:159)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:111)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.access$200(HttpReceiverOverHTTP.java:39)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP$1.resume(HttpReceiverOverHTTP.java:249)
	at org.eclipse.jetty.util.CompletableCallback.succeeded(CompletableCallback.java:82)
	at org.eclipse.jetty.util.IteratingNestedCallback.onCompleteSuccess(IteratingNestedCallback.java:59)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:325)
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:365)
	at org.eclipse.jetty.client.ResponseNotifier$ContentCallback.succeeded(ResponseNotifier.java:286)
	at org.eclipse.jetty.client.util.InputStreamResponseListener$Input.read(InputStreamResponseListener.java:339)

Because it can't revind data buffer to end with parser in END state(due to second '0'), causing high load for every such case.

**How to reproduce?**
Respond with 2 HTTP responses for one request with to chunk ends at the end of second one:

HTTP/1.1 200 OK\r\n
Transfer-Encoding: chunked\r\n
\r\n
2800\r\n
Response with some chunks ........ \r\n
\r\n
0\r\n
\r\n
HTTP/1.1 200 OK\r\n
Transfer-Encoding: chunked\r\n
\r\n
0\r\n
\r\n
0\r\n
\r\n

**Comment by joakime** [comment]
Jetty 9.3.x is EOL / End of Life.

See: https://www.eclipse.org/jetty/download.php#version-table

Does this still happen with Jetty 9.4.43.v20210629?

https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.43.v20210629

**Comment by baranvtek** [comment]
Hi,

I have checked version 9.4.43.v20210629 it unit test and looks like it was fixed.

Thanks!

**Comment by joakime** [comment]
Closing as fixed in newer version of Jetty.
