### ISSUE TITLE
Request.isSecure() and scheme does return true for HTTPS

### ISSUE THREAD

**Issue by ritesh3d** [eclipse/jetty.project#6546]
**Jetty version(s)**
9.4.38.v20210224

**Java version/vendor** `(use: java -version)`
IBM java 8
**OS type/version**
Linux and windows
**Description**
When HTTPS request is sent from external source the Request parameters" isSecure" is set to "false" and getScheme() also returns "http" rather than "https".

I have seen there is a bug reported and fixed in jetty 10.x . Will the same fix and clean up will be provided for jetty 9 version. We are on IBM Java version 8 and can upgrade to jetty 10 version.
**How to reproduce?**

Invoke a request from external tool like "Postman" and "SoapUI" and observe the following Request parameters
1. isSecure()
2. getScheme()

**Comment by sbordet** [comment]
Looks like you did not configure the `SecureRequestCustomizer`.
See for example: https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-server-http-connector-protocol-http11-tls.

**Comment by ritesh3d** [comment]
@sbordet Thank you for responding and this suggestion has worked. However i have run into 

javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException: Closed
	at com.ibm.xml.xlxp.api.stax.msg.StAXMessageProvider.throwXMLStreamException(StAXMessageProvider.java:64)
	at com.ibm.xml.xlxp.api.stax.XMLStreamWriterImpl.close(XMLStreamWriterImpl.java:631)
	at com.ibm.xml.xlxp.api.stax.XMLOutputFactoryImpl$XMLStreamWriterProxy.close(XMLOutputFactoryImpl.java:146)
	at com.sun.xml.ws.util.xml.XMLStreamWriterFilter.close(XMLStreamWriterFilter.java:67)


I am checking on this , If you have some pointer that would help.

**Comment by sbordet** [comment]
There is nothing related to Jetty in your XML stack trace.

**Comment by ritesh3d** [comment]
@sbordet this is the full stack trace.


javax.xml.stream.XMLStreamException: org.eclipse.jetty.io.EofException: Closed
	at com.ibm.xml.xlxp.api.stax.msg.StAXMessageProvider.throwXMLStreamException(StAXMessageProvider.java:64)
	at com.ibm.xml.xlxp.api.stax.XMLStreamWriterImpl.close(XMLStreamWriterImpl.java:631)
	at com.ibm.xml.xlxp.api.stax.XMLOutputFactoryImpl$XMLStreamWriterProxy.close(XMLOutputFactoryImpl.java:146)
	at com.sun.xml.ws.util.xml.XMLStreamWriterFilter.close(XMLStreamWriterFilter.java:67)
	at com.approuter.module.webservice.transport.http.server.WSSHttpHandler.writeSOAPFault(WSSHttpHandler.java:231)
	at com.approuter.module.webservice.transport.http.server.WSSHttpHandler.handleExchange(WSSHttpHandler.java:195)
	at com.approuter.module.webservice.transport.http.server.WSSHttpHandler.handle(WSSHttpHandler.java:145)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
2021-07-28 10:33:48.585:INFO:oejs.AbstractConnector:AWT-EventQueue-0: Stopped ServerConnector@70d5eb3b{SSL, (ssl, http/1.1)}{9.202.181.76:443}
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel$$Lambda$80/0x0000000014da0820.dispatch(Unknown Source)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.lang.Thread.run(Thread.java:822)
Caused by: org.eclipse.jetty.io.EofException: Closed
	at org.eclipse.jetty.server.HttpOutput.checkWritable(HttpOutput.java:768)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:792)
	at com.ibm.xml.xlxp.api.stax.serializer.StAXWriter.flushInternal(StAXWriter.java:68)
	at com.ibm.xml.xlxp.api.stax.serializer.StAXWriter.flush(StAXWriter.java:73)
	at com.ibm.xml.xlxp.api.stax.XMLStreamWriterImpl.close(XMLStreamWriterImpl.java:623)
	... 34 more


Is this expected after using SecureRequestCustomizer, because this have cause this EOF exception , if this is reported inputs, can you please suggest solution related to this.

**Comment by joakime** [comment]
> 2021-07-28 10:33:48.585:INFO:oejs.AbstractConnector:AWT-EventQueue-0: Stopped ServerConnector@70d5eb3b{SSL, (ssl, http/1.1)}{9.202.181.76:443}

That says you were stopping your connector.  
If that's what you did, of course it's going to EOF.

**Comment by sbordet** [comment]
> ```2021-07-28 10:33:48.585:INFO:oejs.AbstractConnector:AWT-EventQueue-0: Stopped ServerConnector@70d5eb3b{SSL, (ssl, http/1.1)}{9.202.181.76:443}```

You are getting the `EofException` because the `ServerConnector` has been stopped as reported in the line above.

The fact that it has been stopped by the AWT thread is really a surprise.
Is this a Swing client application that starts Jetty as a server?

This is likely an application mistake and not a Jetty issue.
I recommend you double check what your application is doing.

**Comment by ritesh3d** [comment]
@sbordet Thank you for all the help.

**Comment by sbordet** [comment]
@ritesh3d what was the problem, just curious?

**Comment by ritesh3d** [comment]
we are still working  on the EOF issue, there seems to be some issue with socket closing in windows platform , we don't see this issue in linux box. As of now we have put a workaround for it while we get the root cause for this.
