### ISSUE TITLE
h2c upgrade request failed when request body is big

### ISSUE THREAD

**Issue by qingdaoheze** [eclipse/jetty.project#6593]
**Jetty version**
9.4.41.v20210516

**Java version**
1.8

**Tomcat version**
9.0.45

**Question**
The Tomcat server supports both HTTP1.1 and H2C. If the request body of the first upgrade request is larger than 1MB and Tomcat receives the request header but does not complete the request body, it will conclude that the upgrade is successful based on the request header and close the socket connection. However, Jetty still tries to send subsequent data. Causes the following exception to be thrown:

```
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:279) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.process(HttpSenderOverHTTP.java:258) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:65) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:212) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:84) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:128) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:233) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:260) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:122) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:381) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:336) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:315) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpDestination.succeeded(HttpDestination.java:247) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.AbstractConnectionPool.proceed(AbstractConnectionPool.java:313) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.succeeded(AbstractConnectionPool.java:533) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.succeeded(AbstractConnectionPool.java:511) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.Promise$Wrapper.succeeded(Promise.java:130) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:130) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:324) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:402) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.ManagedSelector.access$2100(ManagedSelector.java:65) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:1069) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	... 1 more
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:1.8.0_251]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:1.8.0_251]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_251]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:1.8.0_251]
	at java.nio.channels.SocketChannel.write(SocketChannel.java:502) ~[?:1.8.0_251]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:273) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.process(HttpSenderOverHTTP.java:258) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:65) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:212) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:84) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:128) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:233) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:260) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:122) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:381) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:336) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:315) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.HttpDestination.succeeded(HttpDestination.java:247) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.AbstractConnectionPool.proceed(AbstractConnectionPool.java:313) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.succeeded(AbstractConnectionPool.java:533) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.succeeded(AbstractConnectionPool.java:511) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.Promise$Wrapper.succeeded(Promise.java:130) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:130) ~[jetty-client-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:324) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:402) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.ManagedSelector.access$2100(ManagedSelector.java:65) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:1069) ~[jetty-io-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) ~[jetty-util-9.4.41.v20210516.jar:9.4.41.v20210516]
	... 1 more
```

How can I workaround it? Because tomcat has return 101 status, so I should be able to recall it by h2c protocol.

**Comment by joakime** [comment]
Can you run with full DEBUG logging on Jetty side, and reproduce the issue?
We would like to see the DEBUG logs.

**Comment by sbordet** [comment]
@qingdaoheze you should look at why the server closed the connection. Does not look like a Jetty issue.

**Comment by qingdaoheze** [comment]
I think it is a correct action that the server received the headers, concluded the server do support the h2c, and it return the http status 101. When the jetty client receives the 101 response code, there is no need to continue sending data, whatever problems arise afterwards.

In org.eclipse.jetty.io.WriteFlusher#flush method, the following statement has sent some data to the server, and the next call caused the exception. I think it would be a good place to check if there is a 101 response code.
boolean flushed = _endPoint.flush(buffers);

**Comment by sbordet** [comment]
@qingdaoheze I don't understand.

Why are you sending an upgrade request with a body in the first place, if you just want to test if the server supports `h2c`?

Furthermore, if the server supports `h2c` why does it close the connection?

As I said, I don't think this is a Jetty issue -- Jetty is behaving as expected by actually sending request content, it's just that the server closes the connection and the client must report this failure to the application.
For your application the failure may not be important, but in general it is.
