### ISSUE TITLE
SniSslConnectionFactoryTest on Windows fails due to TLS behavior differences

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#6609]
**Jetty version(s)**
9.4.43, 10.0.6, and 11.0.6

**Java version/vendor** `(use: java -version)`
AdoptOpenJDK 8, and 11
Adoptium 8, 11, and 16

**OS type/version**
Windows 10

**Description**
The TLS behaviors that `SniSslConnectionFactoryTest` is testing cannot be reliably tested on Windows 10 due to apparent TLS implementation differences.

The tests that expected a  `javax.net.ssl.SSLHandshakeException` from the client side got a `java.net.SocketException` instead.

* `testWrongSNIRejectedConnection()`
* `testWrongSNIRejectedFunction()`
* `testWrongSNIRejectedConnectionWithNonSNIKeystore()`

Merely forcing the server side to use only TLSv1.2 will resolve these failures, but that's not a good long term solution.
It either hints at a JVM bug, a Windows networking behavior bug, or a Jetty implementation bug.

```
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <javax.net.ssl.SSLHandshakeException> but was: <java.net.SocketException>

	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3007)
	at org.eclipse.jetty.server@10.0.7-SNAPSHOT/org.eclipse.jetty.server.ssl.SniSslConnectionFactoryTest.testWrongSNIRejectedConnection(SniSslConnectionFactoryTest.java:262)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1426)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1336)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at org.eclipse.jetty.server@10.0.7-SNAPSHOT/org.eclipse.jetty.server.ssl.SniSslConnectionFactoryTest.getResponse(SniSslConnectionFactoryTest.java:545)
	at org.eclipse.jetty.server@10.0.7-SNAPSHOT/org.eclipse.jetty.server.ssl.SniSslConnectionFactoryTest.lambda$testWrongSNIRejectedConnection$8(SniSslConnectionFactoryTest.java:262)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
```

**Comment by joakime** [comment]
Including text from discovery.

This code (in `private void start(BiConsumer<SslContextFactory.Server, SecureRequestCustomizer> config) throws Exception` of `SniSslConnectionFactoryTest`) would make things work in Windows.

``` java
        if (OS.WINDOWS.isCurrentOs())
        {
            // Restrict behavior in this testcase to how TLSv1.2 operates.
            // This is because of behavior differences in TLS between Linux and Windows.
            // On Linux TLS on client side will always return a javax.net.ssl.SSLHandshakeException
            // in those test cases that expect it.
            // However, on Windows, there are differences between using OpenJDK 8 and OpenJDK 11.
            // Only the TLSv1.2 implementation will return a javax.net.ssl.SSLHandshakeException,
            // all other TLS versions will result in a
            // javax.net.ssl.SSLException: Software caused connection abort: recv failed
            sslContextFactory.setIncludeProtocols("TLSv1.2");
        }
```

**Comment by joakime** [comment]
PR #6581 disabled these problematic tests on Windows.
