### ISSUE TITLE
java.lang.UnsupportedOperationException: Pipelined requests not supported for PUT requests

### ISSUE THREAD

**Issue by cryoshida** [eclipse/jetty.project#6884]
Hi! We're using HttpClient for both PUT and POST requests. Occasionally we get the following bug
```
java.lang.UnsupportedOperationException: Pipelined requests not supported
	at org.eclipse.jetty.client.HttpChannel.associate(HttpChannel.java:74)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:199)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:242)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:121)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:362)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:320)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:310)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:285)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:262)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:570)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:754)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:746)
``` 
for both of them. I understand that pipelining should not be used for POST requests, and so we added `Connection: close` header for those. However, why would this exception be thrown for PUT requests in the first place? And is there other practices that can be done to prevent this exception?

**Comment by sbordet** [comment]
This exception belong to category "this should never happen".

Can you detail how your application sends those requests? Concurrently? Do you use an explicit `Connection` to send a request, or you always send them via `Request.send()`?

Do you have a reproducible code that we can try ourselves?

**Comment by joakime** [comment]
Also, what version of Jetty are you using?

**Comment by joakime** [comment]
@sbordet is this another case of someone reusing a `Request` object?

**Comment by cryoshida** [comment]
Jetty version is **9.4.24v20191120**.

We do something like
```
Request request = client
    .newRequest(url)
    .method(HttpMethod.POST);    // or HttpMethod.PUT

InputStreamResponseListener listener = new InputStreamResponseListener();
request.send(listener);
```
for each request (only the `client` is reused), and the requests are not sent concurrently either.

I do not have a reproducible code at hand since our customer has been the only one who has been able to reproduce the issue.

**Comment by sbordet** [comment]
We have many tests with the code you show above, and none fail, so it must be something else.
We need more information about your failing case. 
If you can get DEBUG logs or the code producing the error, or some other evidence will be great.
So far there is not much we can work on.

**Comment by joakime** [comment]
Is that really a POST or PUT without a request body?

**Comment by cryoshida** [comment]
Apologies for the delayed response. Was trying to get a green light on sharing snippets of our customer's log...

> Is that really a POST or PUT without a request body?

No, that was a really reduced example. Our production code does use `.content(new StringContentProvider(...))`.

> So far there is not much we can work on.

Understandable. Here is a snippet of the redacted debug log (let me know if you need a bit more of the log).

```
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Exchanges in conversation 1, override=null, listeners=[org.eclipse.jetty.client.util.InputStreamResponseListener@a07675d] (org.eclipse.jetty.client.HttpConversation)
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Queued HttpRequest[POST /security HTTP/1.1]@33f3e88c for HttpDestination[<REDACTED-DESTINATION>]@33f3a728,queue=1,pool=DuplexConnectionPool@669d1a6f[c=0/7/64,a=2,i=5] (org.eclipse.jetty.client.HttpDestination)
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Connection active HttpConnectionOverHTTP@51da5611::DecryptedEndPoint@35a110e1{<REDACTED-DESTINATION>,CLOSED,fill=-,flush=-,to=161/0} (org.eclipse.jetty.client.AbstractConnectionPool)
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Processing exchange HttpExchange@3b50ceee req=PENDING/null@null res=PENDING/null@null on HttpConnectionOverHTTP@51da5611::DecryptedEndPoint@35a110e1{<REDACTED-DESTINATION>,CLOSED,fill=-,flush=-,to=161/0} of HttpDestination[<REDACTED-DESTINATION>]@33f3a728,queue=0,pool=DuplexConnectionPool@669d1a6f[c=0/7/64,a=3,i=4] (org.eclipse.jetty.client.HttpDestination)
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Failed HttpExchange@3b50ceee req=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@5b59c1f5 res=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@5b59c1f5: req=true/rsp=true {} (org.eclipse.jetty.client.HttpExchange)
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Aborted before association HttpExchange@3b50ceee req=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@5b59c1f5 res=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@5b59c1f5: {} (org.eclipse.jetty.client.HttpExchange)
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Content failure (org.eclipse.jetty.client.util.InputStreamResponseListener)
java.lang.UnsupportedOperationException: Pipelined requests not supported
	at org.eclipse.jetty.client.HttpChannel.associate(HttpChannel.java:74)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:199)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:242)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:121)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:362)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:320)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:310)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:285)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:262)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:570)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:754)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:746)
	<OUR STACK>
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:85)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101)
	<OUR STACK>
	at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:561)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:502)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:439)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:555)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Result failure (org.eclipse.jetty.client.util.InputStreamResponseListener)
java.lang.UnsupportedOperationException: Pipelined requests not supported
	at org.eclipse.jetty.client.HttpChannel.associate(HttpChannel.java:74)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:199)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:242)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:121)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:362)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:320)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:310)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:285)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:262)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:570)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:754)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:746)
	<OUR STACK>
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:85)
	at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101)
	<OUR STACK>
	at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:561)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:502)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:439)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:555)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
[2021-07-26 14:47:09,485] DEBUG [qtp176514124-149] Released HttpConnectionOverHTTP@51da5611::DecryptedEndPoint@35a110e1{<REDACTED-DESTINATION>:44728,CLOSED,fill=-,flush=-,to=162/0} (org.eclipse.jetty.client.HttpDestination)
[2021-07-26 14:47:09,485] DEBUG [qtp176514124-149] Connection idle HttpConnectionOverHTTP@51da5611::DecryptedEndPoint@35a110e1{<REDACTED-DESTINATION>,CLOSED,fill=-,flush=-,to=162/0} (org.eclipse.jetty.client.AbstractConnectionPool)
[2021-07-26 14:47:09,485] DEBUG [qtp176514124-149] Send failed org.eclipse.jetty.client.SendFailure@7b54db9b[failure=org.eclipse.jetty.client.HttpRequestException: Could not associate request to connection,retry=false] for HttpExchange@3b50ceee req=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@5b59c1f5 res=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@5b59c1f5 (org.eclipse.jetty.client.HttpDestination)
```

**Comment by sbordet** [comment]
I agree with @joakime that this looks suspiciously a reuse of the same `Request` object for 2 different requests.
Requests are logged with their hashcode, for example from the logs above:

```
[2021-07-26 14:47:09,484] DEBUG [qtp176514124-149] Queued HttpRequest[POST /security HTTP/1.1]@33f3e88c for HttpDestination[<REDACTED-DESTINATION>]@33f3a728,queue=1,pool=DuplexConnectionPool@669d1a6f[c=0/7/64,a=2,i=5] (org.eclipse.jetty.client.HttpDestination)
```

Search _before_ that log line if a request `@33f3e88c` has already been sent.

**Comment by cryoshida** [comment]
I see. But unfortunately no, only the connection `HttpConnectionOverHTTP@51da5611` is reused again and again for destination `33f3a728`. The request itself only shows up for this one time. If you would like and possible, is there a private email to send the full logs since it contains our stack and other sensitive information?

I'm mainly trying to understand in what cases could we have `abort=True` in `HttpChannel::associate()` which causes the `Pipelined requests not supported` error? Because we get the same error for `PUT` requests. I understand that this exception belongs to "it should have never happened", but put is idempotent and shouldn't it been allowed for pipelined requests?

```
[2021-07-26 14:47:09,512] DEBUG [qtp176514124-124] Exchanges in conversation 1, override=null, listeners=[org.eclipse.jetty.client.util.InputStreamResponseListener@677c5c38] (org.eclipse.jetty.client.HttpConversation)
[2021-07-26 14:47:09,482] DEBUG [HttpClient@2faa55bb-79] Parsed false, remaining 295 HttpParser{s=END,127 of 127} (org.eclipse.jetty.client.HttpReceiver)
[2021-07-26 14:47:09,512] DEBUG [qtp176514124-124] Queued HttpRequest[PUT /security/1.0/authorize HTTP/1.1]@7c7f68cf for HttpDestination[https://<REDACTED>]@33f3a728,queue=1,pool=DuplexConnectionPool@669d1a6f[c=0/7/64,a=2,i=5] (org.eclipse.jetty.client.HttpDestination)
[2021-07-26 14:47:09,512] DEBUG [qtp176514124-124] Connection active HttpConnectionOverHTTP@51da5611::DecryptedEndPoint@35a110e1{<REDACTED><->/171.135.102.63:44728,CLOSED,fill=-,flush=-,to=190/0} (org.eclipse.jetty.client.AbstractConnectionPool)
[2021-07-26 14:47:09,513] DEBUG [qtp176514124-124] Processing exchange HttpExchange@64d2f054 req=PENDING/null@null res=PENDING/null@null on HttpConnectionOverHTTP@51da5611::DecryptedEndPoint@35a110e1{<REDACTED><->/171.135.102.63:44728,CLOSED,fill=-,flush=-,to=190/0} of HttpDestination[https://<REDACTED>]@33f3a728,queue=0,pool=DuplexConnectionPool@669d1a6f[c=0/7/64,a=3,i=4] (org.eclipse.jetty.client.HttpDestination)
[2021-07-26 14:47:09,515] DEBUG [qtp176514124-124] Failed HttpExchange@64d2f054 req=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@d8101c1 res=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@d8101c1: req=true/rsp=true {} (org.eclipse.jetty.client.HttpExchange)
[2021-07-26 14:47:09,518] DEBUG [qtp176514124-124] Aborted before association HttpExchange@64d2f054 req=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@d8101c1 res=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@d8101c1: {} (org.eclipse.jetty.client.HttpExchange)
[2021-07-26 14:47:09,518] DEBUG [qtp176514124-124] Content failure (org.eclipse.jetty.client.util.InputStreamResponseListener)
java.lang.UnsupportedOperationException: Pipelined requests not supported
	<SIMILAR STACK>
[2021-07-26 14:47:09,519] DEBUG [qtp176514124-124] Released HttpConnectionOverHTTP@51da5611::DecryptedEndPoint@35a110e1{<REDACTED><->/171.135.102.63:44728,CLOSED,fill=-,flush=-,to=196/0} (org.eclipse.jetty.client.HttpDestination)
[2021-07-26 14:47:09,519] DEBUG [qtp176514124-124] Connection idle HttpConnectionOverHTTP@51da5611::DecryptedEndPoint@35a110e1{<REDACTED><->/171.135.102.63:44728,CLOSED,fill=-,flush=-,to=196/0} (org.eclipse.jetty.client.AbstractConnectionPool)
[2021-07-26 14:47:09,519] DEBUG [qtp176514124-124] Send failed org.eclipse.jetty.client.SendFailure@81911d5[failure=org.eclipse.jetty.client.HttpRequestException: Could not associate request to connection,retry=false] for HttpExchange@64d2f054 req=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@d8101c1 res=COMPLETED/java.lang.UnsupportedOperationException: Pipelined requests not supported@d8101c1 (org.eclipse.jetty.client.HttpDestination)
```
Similarly, `HttpRequest@7c7f68cf` only shows up this one time.

**Comment by joakime** [comment]
A reproduction case/project would be useful.

**Comment by sbordet** [comment]
I see that the decrypted endpoint is CLOSED, which is strange.
Also, maybe #8719 is related?
