### ISSUE TITLE
org.eclipse.jetty.io.EofException: Early EOF

### ISSUE THREAD

**Issue by Masber** [eclipse/jetty.project#6926]
**Jetty version(s)**
9.4.27.v20200227

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)

**OS type/version**
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)

**Description**
I have been having this issue for weeks and can't reproduce it. For some unknown reason the server response gives error with EOF. Log traces below.

```
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: Caused by: org.eclipse.jetty.io.EofException: Early EOF
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1141)
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1129)
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:321)
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: at org.apache.cxf.helpers.IOUtils.copyAtLeast(IOUtils.java:224)
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: at org.apache.cxf.interceptor.LoggingInInterceptor.logInputStream(LoggingInInterceptor.java:205)
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: ... 39 more
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: Sep 23, 2021 6:27:03 PM org.apache.cxf.interceptor.LoggingOutInterceptor
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: INFO: Outbound Message
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: ---------------------------
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: ID: 918
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: Response-Code: 500
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: Encoding: UTF-8
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: Content-Type:
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: Headers: {}
Sep 23 18:27:03 ip-192-168-10-204.ap-southeast-2.compute.internal java[10228]: Payload: <ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat"><ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">org.eclipse.jetty.io.EofException: Early EOF</ns1:faultstring></ns1:XMLFault>
```

**How to reproduce?**
I don't know how to reproduce this, synthetic tests with the same requests works

**Comment by lachlan-roberts** [comment]
This exception means that the client has terminated the connection before sending all the expected content. Could be a bug in the client code or maybe just the client had a network failure before it had sent all its content.

**Comment by janbartel** [comment]
@Masber seems your question is answered - the client has closed the connection when the server side is expecting some content in order to log it.
