### ISSUE TITLE
AsyncListener.onComplete() is sometimes not called

### ISSUE THREAD

**Issue by MacX19** [eclipse/jetty.project#6951]
**Jetty version(s)**
9.4.43.v20210629

**Java version/vendor** `(use: java -version)`
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

**OS type/version**
Windows 10 1809

**Description**
I use StatisticsHandler to perform a graceful shutdown. Sometimes server.stop() waits until timeout. There are no active requests at this time. My investigation revealed that AsyncListener.onComplete() is sometimes not called. This happens when the request is canceled by the client and the response is sent by HttpOutput.sendContent(ByteBuffer content, Callback callback).

**How to reproduce?**
I was able to reproduce the problem with the following code:

```
package server.net;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.*;
import javax.servlet.*;
import javax.servlet.http.*;

import org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory;
import org.eclipse.jetty.http.HttpVersion;
import org.eclipse.jetty.http2.HTTP2Cipher;
import org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory;
import org.eclipse.jetty.server.*;
import org.eclipse.jetty.servlet.ServletHandler;
import org.eclipse.jetty.util.Callback;
import org.eclipse.jetty.util.ssl.SslContextFactory;

public class JettyTest {
  private static final int PORT = 8443;
  private static final AtomicInteger requestCounter = new AtomicInteger();
  private static final AtomicInteger completeCounter = new AtomicInteger();
  private static final AtomicInteger timeoutCounter = new AtomicInteger();
  private static final AtomicInteger errorCounter = new AtomicInteger();
  private static final Logger logger;

  static {
    logger = Logger.getLogger(JettyTest.class.getName());
    try {
      FileHandler fileHandler = new FileHandler("jetty.log");
      fileHandler.setFormatter(new SimpleFormatter());
      logger.addHandler(fileHandler);
      logger.setUseParentHandlers(false);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  public static void main(String[] args) {
    Server server = new Server();

    HttpConfiguration httpsConfig = new HttpConfiguration();
    httpsConfig.setSecurePort(PORT);

    SslContextFactory sslContextFactory = new SslContextFactory.Server();
    sslContextFactory.setKeyStorePath("keystore");
    sslContextFactory.setKeyStorePassword("OBF:1vny1zlo1x8e1vnw1vn61x8g1zlu1vn4");
    sslContextFactory.setKeyManagerPassword("OBF:1u2u1wml1z7s1z7a1wnl1u2g");
    sslContextFactory.setCipherComparator(HTTP2Cipher.COMPARATOR);

    HTTP2ServerConnectionFactory h2 = new HTTP2ServerConnectionFactory(httpsConfig);
    ALPNServerConnectionFactory alpn = new ALPNServerConnectionFactory();
    alpn.setDefaultProtocol(HttpVersion.HTTP_1_1.asString());
    SslConnectionFactory ssl = new SslConnectionFactory(sslContextFactory, alpn.getProtocol());
    ServerConnector https = new ServerConnector(server, ssl, alpn, h2, new HttpConnectionFactory(httpsConfig));
    https.setPort(PORT);

    server.setConnectors(new Connector[]{https});

    ServletHandler handler = new ServletHandler();
    handler.addServletWithMapping(AsyncServlet.class, "/");

    server.setHandler(handler);
    try {
      server.start();
      server.join();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static class AsyncServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
      int request = requestCounter.incrementAndGet();
      long time = Long.parseLong(req.getParameter("time"));
      byte[] bytes = new byte[16802];
      resp.setStatus(HttpServletResponse.SC_OK);
      resp.setContentType("image/jpeg");
      resp.setContentLength(bytes.length);
      HttpOutput out = (HttpOutput) resp.getOutputStream();
      AsyncContext asyncContext = req.startAsync();
      asyncContext.addListener(new MyAsyncListener(request));
      asyncContext.start(() -> {
        try {
          Thread.sleep(time);
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
        ThreadLocalRandom.current().nextBytes(bytes);
        out.sendContent(ByteBuffer.wrap(bytes), new AsyncCallback(asyncContext, request));
      });
    }
  }

  private static class AsyncCallback implements Callback {
    private final AsyncContext asyncContext;
    private final int request;

    private AsyncCallback(AsyncContext asyncContext, int request) {
      this.asyncContext = asyncContext;
      this.request = request;
    }

    @Override
    public void succeeded() {
      try {
        asyncContext.complete();
      } catch (Exception e) {
        logger.log(Level.WARNING, "request=" + request + "|succeeded|complete", e);
      }
    }

    @Override
    public void failed(Throwable t) {
      logger.log(Level.WARNING, "request=" + request + "|failed", t);
      try {
        asyncContext.complete();
      } catch (Exception e) {
        logger.log(Level.WARNING, "request=" + request + "|failed|complete", e);
      }
    }

    @Override
    public InvocationType getInvocationType() {
      return InvocationType.NON_BLOCKING;
    }
  }

  private static class MyAsyncListener implements AsyncListener {
    private final int request;

    public MyAsyncListener(int request) {
      this.request = request;
    }

    @Override
    public void onComplete(AsyncEvent event) throws IOException {
      int complete = completeCounter.incrementAndGet();
      System.out.println("request=" + request + ", complete=" + complete + ", timeout=" + timeoutCounter.get() + ", error=" + errorCounter.get());
    }

    @Override
    public void onTimeout(AsyncEvent event) throws IOException {
      timeoutCounter.incrementAndGet();
    }

    @Override
    public void onError(AsyncEvent event) throws IOException {
      errorCounter.incrementAndGet();
      Throwable t = event.getThrowable();
      if (t != null) logger.log(Level.WARNING, "request=" + request + "|onError", t);
    }

    @Override
    public void onStartAsync(AsyncEvent event) throws IOException {
    }
  }
}
```
I am using curl 7.78.0 (x86_64-pc-win32) to send requests. Requests are canceled after 1 second.
test.cmd:
`for /L %%B in (1,1,1000) do curl.exe -k --http2 -m 1 "https://localhost:8443/?time=965"`

Console output:
```
request=1, complete=1, timeout=0, error=1
request=2, complete=2, timeout=0, error=2
request=3, complete=3, timeout=0, error=3
request=4, complete=4, timeout=0, error=3
request=5, complete=5, timeout=0, error=3
request=6, complete=6, timeout=0, error=4
request=7, complete=7, timeout=0, error=4
request=8, complete=8, timeout=0, error=4
request=9, complete=9, timeout=0, error=4
request=10, complete=10, timeout=0, error=4
request=11, complete=11, timeout=0, error=4
request=12, complete=12, timeout=0, error=4
request=13, complete=13, timeout=0, error=4
request=14, complete=14, timeout=0, error=4
request=15, complete=15, timeout=0, error=4
request=16, complete=16, timeout=0, error=4
request=17, complete=17, timeout=0, error=4
request=18, complete=18, timeout=0, error=4
request=19, complete=19, timeout=0, error=4
request=20, complete=20, timeout=0, error=4
request=21, complete=21, timeout=0, error=4
request=22, complete=22, timeout=0, error=4
request=23, complete=23, timeout=0, error=4
request=24, complete=24, timeout=0, error=4
request=25, complete=25, timeout=0, error=4
request=26, complete=26, timeout=0, error=4
request=27, complete=27, timeout=0, error=4
request=28, complete=28, timeout=0, error=4
request=29, complete=29, timeout=0, error=4
request=30, complete=30, timeout=0, error=4
request=31, complete=31, timeout=0, error=4
request=32, complete=32, timeout=0, error=4
request=33, complete=33, timeout=0, error=4
request=34, complete=34, timeout=0, error=4
request=35, complete=35, timeout=0, error=4
request=36, complete=36, timeout=0, error=4
request=37, complete=37, timeout=0, error=4
request=38, complete=38, timeout=0, error=4
request=39, complete=39, timeout=0, error=4
request=40, complete=40, timeout=0, error=4
request=41, complete=41, timeout=0, error=4
request=42, complete=42, timeout=0, error=4
request=43, complete=43, timeout=0, error=4
request=44, complete=44, timeout=0, error=4
request=45, complete=45, timeout=0, error=4
request=46, complete=46, timeout=0, error=4
request=47, complete=47, timeout=0, error=4
request=48, complete=48, timeout=0, error=4
request=49, complete=49, timeout=0, error=4
request=50, complete=50, timeout=0, error=4
request=51, complete=51, timeout=0, error=4
request=52, complete=52, timeout=0, error=4
request=53, complete=53, timeout=0, error=4
request=54, complete=54, timeout=0, error=4
request=56, complete=55, timeout=0, error=5
request=57, complete=56, timeout=0, error=5
request=58, complete=57, timeout=0, error=5
request=59, complete=58, timeout=0, error=5
request=60, complete=59, timeout=0, error=5
request=61, complete=60, timeout=0, error=5
request=62, complete=61, timeout=0, error=5
request=63, complete=62, timeout=0, error=5
request=64, complete=63, timeout=0, error=5
request=65, complete=64, timeout=0, error=5
request=66, complete=65, timeout=0, error=5
request=67, complete=66, timeout=0, error=5
request=68, complete=67, timeout=0, error=5
request=69, complete=68, timeout=0, error=5
request=70, complete=69, timeout=0, error=5
request=71, complete=70, timeout=0, error=5
request=72, complete=71, timeout=0, error=5
request=73, complete=72, timeout=0, error=5
request=74, complete=73, timeout=0, error=5
request=75, complete=74, timeout=0, error=5
request=76, complete=75, timeout=0, error=5
request=77, complete=76, timeout=0, error=5
request=78, complete=77, timeout=0, error=5
request=79, complete=78, timeout=0, error=5
request=80, complete=79, timeout=0, error=5
request=81, complete=80, timeout=0, error=5
request=82, complete=81, timeout=0, error=5
request=83, complete=82, timeout=0, error=5
request=84, complete=83, timeout=0, error=5
request=85, complete=84, timeout=0, error=5
request=86, complete=85, timeout=0, error=5
request=87, complete=86, timeout=0, error=5
request=88, complete=87, timeout=0, error=5
request=89, complete=88, timeout=0, error=5
request=90, complete=89, timeout=0, error=5
request=91, complete=90, timeout=0, error=5
request=92, complete=91, timeout=0, error=5
request=93, complete=92, timeout=0, error=5
request=94, complete=93, timeout=0, error=5
request=95, complete=94, timeout=0, error=5
request=96, complete=95, timeout=0, error=5
request=97, complete=96, timeout=0, error=5
request=98, complete=97, timeout=0, error=5
request=99, complete=98, timeout=0, error=5
request=100, complete=99, timeout=0, error=5
```
Console shows that request 55 did not call the AsyncListener.onComplete()

jetty.log:
```
oct 01, 2021 11:11:55 AM server.net.JettyTest$MyAsyncListener onError
WARNING: request=6|onError
org.eclipse.jetty.io.EofException: Reset stream_closed_error
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:159)
	at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:657)
	at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:399)
	at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:311)
	at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:317)
	at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onReset(Parser.java:372)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyReset(BodyParser.java:144)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.onReset(ResetBodyParser.java:97)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.parse(ResetBodyParser.java:66)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:198)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:127)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:261)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:183)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:138)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:361)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:895)
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:203)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:173)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:160)
		... 33 more

oct 01, 2021 11:11:55 AM server.net.JettyTest$AsyncCallback failed
WARNING: request=6|failed
java.io.IOException: cannot sendContent(), output already committed
	at org.eclipse.jetty.server.HttpOutput.prepareSendContent(HttpOutput.java:1305)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:1242)
	at server.net.JettyTest$AsyncServlet.lambda$doGet$0(JettyTest.java:92)
	at org.eclipse.jetty.server.AsyncContextState$1.run(AsyncContextState.java:151)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)

oct 01, 2021 11:11:55 AM server.net.JettyTest$AsyncCallback failed
WARNING: request=6|failed|complete
java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:52)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:72)
	at server.net.JettyTest$AsyncCallback.failed(JettyTest.java:119)
	at org.eclipse.jetty.server.HttpOutput.prepareSendContent(HttpOutput.java:1305)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:1242)
	at server.net.JettyTest$AsyncServlet.lambda$doGet$0(JettyTest.java:92)
	at org.eclipse.jetty.server.AsyncContextState$1.run(AsyncContextState.java:151)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)

oct 01, 2021 11:12:45 AM server.net.JettyTest$MyAsyncListener onError
WARNING: request=55|onError
org.eclipse.jetty.io.EofException: Reset stream_closed_error
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:159)
	at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:657)
	at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:399)
	at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:311)
	at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:317)
	at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onReset(Parser.java:372)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyReset(BodyParser.java:144)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.onReset(ResetBodyParser.java:97)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.parse(ResetBodyParser.java:66)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:198)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:127)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:261)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:183)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:138)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:361)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:895)
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:203)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:173)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:160)
		... 33 more

oct 01, 2021 11:12:45 AM server.net.JettyTest$AsyncCallback failed
WARNING: request=55|failed
org.eclipse.jetty.io.EofException: Reset stream_closed_error
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:159)
	at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:657)
	at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:399)
	at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:311)
	at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:317)
	at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onReset(Parser.java:372)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyReset(BodyParser.java:144)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.onReset(ResetBodyParser.java:97)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.parse(ResetBodyParser.java:66)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:198)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:127)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:261)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:183)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:138)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:361)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Throwable: HttpInput failure
		at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:895)
		at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:203)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onFailure(HTTP2ServerConnectionFactory.java:173)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:160)
		... 33 more
```

**Comment by sbordet** [comment]
You are waiting 965 ms on the server and cancelling after 1 second on the client, and this leads to races.

Sometimes you can complete, sometimes you cannot write, sometimes you get a reset.

`onComplete()` is only called for a successful `complete()`.

For the failure cases, you have the other methods.

As long as the total number of notifications you get is correct (complete+error+failed=total), then I think this is expected behavior.

**Comment by MacX19** [comment]
If so, the StatisticsHandler would not work properly when I set `gracefulShutdownWaitsForRequests` to `true`
https://github.com/eclipse/jetty.project/blob/9f1f1fea1bd84590739cdf26b04e92052a1fa465/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java#L264-L273
StatisticsHandler uses onComplete() for graceful shutdown:
https://github.com/eclipse/jetty.project/blob/9f1f1fea1bd84590739cdf26b04e92052a1fa465/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java#L102-L122
The documentation for the method says: "should wait for all requests to complete including async requests". But if onComplete() is not called, `numRequests` will not decrease to 0. Also statistics for asynchronous requests will not be collected correctly. I think onComplete() should be called for each request. But maybe i'm wrong...

**Comment by gregw** [comment]
Hmmmm there indeed could be an issue with the `StatisticHandler`, as it may need to decrement some more counters in `onError`... but I'm not sure we can entirely distinguish between a final onError call vs one that might be called before a onComplete?   Hmmm the listener may need to be stateful?

@olamy do you have any spare cycles  to write a test for this... probably adding a test to StatisticsHandlerTest and using LocalEndPoint.close to simulate an error?

**Comment by MacX19** [comment]
I also noticed that the `_errors` variable
https://github.com/eclipse/jetty.project/blob/4aed1f33772a685689ff48af9e178dd62951a112/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java#L61
is missing in the statsReset() method 
https://github.com/eclipse/jetty.project/blob/ca8d147ec4de9bc9174594a53f3ff0002c493466/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java#L121-L139

**Comment by joakime** [comment]
Closing, as Jetty 9.4.x is now at End of Community Support.

* #7958 

If this occurs on a supported version of Jetty 10, Jetty 11, or Jetty 12, let us know.
