### ISSUE TITLE
LocalConnector.getResponse() doesn't find close if using HTTP/1.1 w/Connection: close

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#696]
In the following testing example ...

``` java
HttpTester.Request request = HttpTester.newRequest();

request.setMethod("GET");
request.setVersion(HttpVersion.HTTP_1_1);
request.setHeader("Host", "tester");
request.setHeader("Connection", "close");
request.setURI("/testdir/");

String response = localConnector.getResponse(BufferUtil.toString(request.generate()));
```

The `localConnector.getResponse()` never returns, as its waiting on the connection close at ...

```
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.io.ByteArrayEndPoint.waitForOutput(ByteArrayEndPoint.java:286)
	at org.eclipse.jetty.server.LocalConnector$LocalEndPoint.waitForResponse(LocalConnector.java:403)
	at org.eclipse.jetty.server.LocalConnector.getResponse(LocalConnector.java:244)
	at org.eclipse.jetty.server.LocalConnector.getResponse(LocalConnector.java:226)
	at org.eclipse.jetty.server.handler.AllowSymLinkAliasCheckerTest.testAccessTestDir(AllowSymLinkAliasCheckerTest.java:149)
```

Removing the two lines ...

``` java
request.setVersion(HttpVersion.HTTP_1_1);
request.setHeader("Connection", "close");
```

allows the test to continue, but this seems like a bug in `LocalConnector`

**Comment by gregw** [comment]
I have already fixed a closing bug that may be this one in 9.4.x - did you see it there or in 9.3.x?   What was the server side of this test?

**Comment by joakime** [comment]
Saw this in 9.3.x - you can replicate pretty easily by adding these 2 headers to the usage found in the `AllowSymLinkAliasCheckerTest.testAccess()` method.

``` java
request.setVersion(HttpVersion.HTTP_1_1);
request.setHeader("Connection", "close");
```

**Comment by gregw** [comment]
@joakime That works fine for me in HEAD of jetty-9.3.x so assuming I have already fixed.  Closing for now, please reopen if you see again.
