### ISSUE TITLE
Getting 404 failures when trying to enable `logging-log4j` module.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#6969]
**Jetty version(s)**
9.4.44, and does not occur in 9.4.43 or earlier.

**Description**
Getting 404 failures when trying to enable `logging-log4j` module.

```
$ java -jar ../jetty-home-9.4.44.v20210927/start.jar  --approve-all-licenses --add-to-startd=logging-log4j
WARN  : --add-to-startd is deprecated! Instead use: --create-startd --add-to-start=logging-log4j
INFO  : All Licenses Approved via Command Line Option
MKDIR : ${jetty.base}/start.d
INFO  : slf4j-api       transitively enabled
INFO  : log4j-impl      transitively enabled
INFO  : resources       transitively enabled
INFO  : slf4j-log4j     transitively enabled
INFO  : logging-log4j   initialized in ${jetty.base}/start.d/logging-log4j.ini
MKDIR : ${jetty.base}/lib/slf4j
COPY  : /home/lachlan/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar to ${jetty.base}/lib/slf4j/slf4j-api-1.7.32.jar
MKDIR : ${jetty.base}/lib/log4j
DOWNLD: https://repo1.maven.org/maven2/log4j/log4j/@log4j.version@/log4j-@log4j.version@.jar to ${jetty.base}/lib/log4j/log4j-@log4j.version@.jar
java.io.IOException: URL GET Failure [404/Not Found] on https://repo1.maven.org/maven2/log4j/log4j/@log4j.version@/log4j-@log4j.version@.jar
	at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:143)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileInitializer.download(MavenLocalRepoFileInitializer.java:238)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileInitializer.create(MavenLocalRepoFileInitializer.java:141)
	at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
	at org.eclipse.jetty.start.Main.start(Main.java:440)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
MKDIR : ${jetty.base}/resources
COPY  : ${jetty.home}/modules/log4j-impl/resources/log4j.xml to ${jetty.base}/resources/log4j.xml
COPY  : /home/lachlan/.m2/repository/org/slf4j/slf4j-log4j12/1.7.32/slf4j-log4j12-1.7.32.jar to ${jetty.base}/lib/slf4j/slf4j-log4j12-1.7.32.jar
WARN  : Failed to process all file resources.
 - [IOException] URL GET Failure [404/Not Found] on https://repo1.maven.org/maven2/log4j/log4j/@log4j.version@/log4j-@log4j.version@.jar - lib/log4j/log4j-@log4j.version@.jar
java.lang.RuntimeException: Failed to process all file resources.
 - [IOException] URL GET Failure [404/Not Found] on https://repo1.maven.org/maven2/log4j/log4j/@log4j.version@/log4j-@log4j.version@.jar - lib/log4j/log4j-@log4j.version@.jar
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:342)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
	at org.eclipse.jetty.start.Main.start(Main.java:440)
	at org.eclipse.jetty.start.Main.main(Main.java:77)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

**Comment by olamy** [comment]
temporary workaround is to start jetty:
`java -jar start.jar log4j.version=1.2.17`
