### ISSUE TITLE
ELContextCleaner failed because cannot access a member of class javax.el.BeanELResolver with modifiers "private static final"

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#6980]
**Jetty version(s)**
10.0.6

stacktrace:
```
[main] WARN org.eclipse.jetty.servlet.listener.ELContextCleaner - Cannot purge classes from javax.el.BeanELResolver
java.lang.IllegalAccessException: class org.eclipse.jetty.servlet.listener.ELContextCleaner cannot access a member of class javax.el.BeanELResolver with modifiers "private static final"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
	at java.base/java.lang.reflect.Field.get(Field.java:416)
	at org.eclipse.jetty.servlet.listener.ELContextCleaner.purgeEntries(ELContextCleaner.java:91)
	at org.eclipse.jetty.servlet.listener.ELContextCleaner.contextDestroyed(ELContextCleaner.java:56)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:1047)
```

**Comment by olamy** [comment]
even if it's only a warning and do not cause more issues. It simply doesn't work the field use by reflection must be marked as accessible.

**Comment by janbartel** [comment]
@olamy what jvm was this using?

**Comment by olamy** [comment]
`Java version: 11.0.12, vendor: Eclipse Foundation, runtime: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home` 
I discovered this by implementing jetty-10 support for Arquillian. 
https://github.com/arquillian/arquillian-container-jetty/pull/71

**Comment by charlieslade** [comment]
Having the same problem when stopping embedded jetty server.

Is this problem with my code or jetty specific?

jetty version: 10.0.5
jvm version (openjdk): 11.0.10

**Comment by joakime** [comment]
@charlieslade this is a flaw in the EL API code that Jetty is attempting to work around.

We've filed an issue about this with the Jakarta EL group at https://github.com/eclipse-ee4j/el-ri/issues/171
Our attempted work around is currently buggy in Jetty 10 and Java 9+ (which changed the reflection rules).
PR #6981 is the fix we need.

**Comment by charlieslade** [comment]
Got it, thanks!
