### ISSUE TITLE
Attempting to add the slf4j-log4j is resulting in 404 errors

### ISSUE THREAD

**Issue by pbtura** [eclipse/jetty.project#6989]
I'm currently in the process of setting up a new jetty 9.4 server. I'm trying to add the slf4j implementation module for logging. When I run the command `java -jar start.jar --add-to-start=slf4j-log4j` the maven download is failing with an http 404 error. Looking at the stacktrace, it seems like it doesn't know which version of log4j it is supposed to be downloading. Is there a configuration step I missed somewhere or is this a bug? For reference the stack trace I'm getting is:

```
INFO  : log4j-impl      transitively enabled
INFO  : resources       transitively enabled
INFO  : slf4j-log4j     initialized in ${jetty.base}/start.ini
MKDIR : ${jetty.base}/lib/log4j
DOWNLD: https://repo1.maven.org/maven2/log4j/log4j/@log4j.version@/log4j-@log4j.version@.jar to ${jetty.base}/lib/log4j/log4j-@log4j.version@.jar
java.io.IOException: URL GET Failure [404/Not Found] on https://repo1.maven.org/maven2/log4j/log4j/@log4j.version@/log4j-@log4j.version@.jar
	at org.eclipse.jetty.start.FileInitializer.download(FileInitializer.java:143)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileInitializer.download(MavenLocalRepoFileInitializer.java:238)
	at org.eclipse.jetty.start.fileinits.MavenLocalRepoFileInitializer.create(MavenLocalRepoFileInitializer.java:141)
	at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:285)
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:322)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
	at org.eclipse.jetty.start.Main.start(Main.java:440)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
MKDIR : ${jetty.base}/resources
COPY  : ${jetty.home}/modules/log4j-impl/resources/log4j.xml to ${jetty.base}/resources/log4j.xml
DOWNLD: https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.32/slf4j-log4j12-1.7.32.jar to ${jetty.base}/lib/slf4j/slf4j-log4j12-1.7.32.jar
WARN  : Failed to process all file resources.
 - [IOException] URL GET Failure [404/Not Found] on https://repo1.maven.org/maven2/log4j/log4j/@log4j.version@/log4j-@log4j.version@.jar - lib/log4j/log4j-@log4j.version@.jar
java.lang.RuntimeException: Failed to process all file resources.
 - [IOException] URL GET Failure [404/Not Found] on https://repo1.maven.org/maven2/log4j/log4j/@log4j.version@/log4j-@log4j.version@.jar - lib/log4j/log4j-@log4j.version@.jar
	at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:342)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:253)
	at org.eclipse.jetty.start.Main.start(Main.java:440)
	at org.eclipse.jetty.start.Main.main(Main.java:77)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

**Comment by olamy** [comment]
@pbtura have a look at the same issue https://github.com/eclipse/jetty.project/issues/6969
there is a workaround
`java -jar start.jar --add-to-start=slf4j-log4j log4j.version=1.2.17`
