### ISSUE TITLE
Jetty 9.4.44 - Failed to instantiate SLF4J LoggerFactory

### ISSUE THREAD

**Issue by greatpsi** [eclipse/jetty.project#7002]
Basic Jetty startup produces SLF4J exception:

me@awesome00:~/jetty/jetty-distribution-9.4.44.v20210927$ java -jar start.jar
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:36)
	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:30)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.eclipse.jetty.util.log.Log.initialized(Log.java:158)
	at org.eclipse.jetty.util.log.Log.getLogger(Log.java:278)
	at org.eclipse.jetty.util.log.Log.getLogger(Log.java:267)
	at org.eclipse.jetty.xml.XmlConfiguration.<clinit>(XmlConfiguration.java:88)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more
2021-10-15 15:36:48.698:INFO::main: Logging initialized @149ms to org.eclipse.jetty.util.log.StdErrLog
2021-10-15 15:36:48.906:WARN:oejs.HomeBaseWarning:main: This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at https://www.eclipse.org/jetty/documentation/current/startup.html
2021-10-15 15:36:48.965:INFO:oejs.Server:main: jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
2021-10-15 15:36:49.034:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/colclcm1/jetty/jetty-distribution-9.4.44.v20210927/webapps/] at interval 1
2021-10-15 15:36:49.091:INFO:oejs.AbstractConnector:main: Started ServerConnector@72d1ad2e{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-10-15 15:36:49.120:INFO:oejus.SslContextFactory:main: x509=X509@77c2494c(jetty,h=[jetty.eclipse.org],a=[],w=[]) for Server@3eb738bb[provider=null,keyStore=file:///home/colclcm1/jetty/jetty-distribution-9.4.44.v20210927/etc/keystore,trustStore=file:///home/colclcm1/jetty/jetty-distribution-9.4.44.v20210927/etc/keystore]
2021-10-15 15:36:49.121:INFO:oejus.SslContextFactory:main: x509=X509@5bda8e08(mykey,h=[jetty server],a=[],w=[]) for Server@3eb738bb[provider=null,keyStore=file:///home/colclcm1/jetty/jetty-distribution-9.4.44.v20210927/etc/keystore,trustStore=file:///home/colclcm1/jetty/jetty-distribution-9.4.44.v20210927/etc/keystore]
2021-10-15 15:36:49.237:INFO:oejs.AbstractConnector:main: Started ServerConnector@11922bd6{SSL, (ssl, http/1.1)}{0.0.0.0:8443}
2021-10-15 15:36:49.239:INFO:oejs.Server:main: Started @693ms

**Comment by joakime** [comment]
@greatpsi  have a look at the same issue #6969
there is a workaround
```
java -jar start.jar --add-to-start=logging-log4j log4j.version=1.2.17
```

**Comment by greatpsi** [comment]
**Workaround suppresses error message, but Jetty does not start.**  

_Console output follows:_

`me@awesome00:~/jetty/jetty-distribution-9.4.44.v20210927$ java -jar start.jar --add-to-start=logging-log4j log4j.version=1.2.17 --approve-all-licenses`
INFO  : All Licenses Approved via Command Line Option
INFO  : slf4j-api       transitively enabled
INFO  : log4j-impl      transitively enabled
INFO  : slf4j-log4j     transitively enabled
INFO  : logging-log4j   initialized in ${jetty.base}/start.ini
MKDIR : ${jetty.base}/lib/slf4j
DOWNLD: https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar to ${jetty.base}/lib/slf4j/slf4j-api-1.7.32.jar
MKDIR : ${jetty.base}/lib/log4j
DOWNLD: https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar to ${jetty.base}/lib/log4j/log4j-1.2.17.jar
COPY  : ${jetty.base}/modules/log4j-impl/resources/log4j.xml to ${jetty.base}/resources/log4j.xml
DOWNLD: https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.32/slf4j-log4j12-1.7.32.jar to ${jetty.base}/lib/slf4j/slf4j-log4j12-1.7.32.jar
INFO  : Base directory was modified

**Note: No oejs.Server:main: Started message returned**

_Execute ps -ef, looking for java 
There are no processes running java - Jetty did not start
Confirmed via a separate console window_

```
me@awesome00:~/jetty/jetty-distribution-9.4.44.v20210927$
me@awesome00:~/jetty/jetty-distribution-9.4.44.v20210927$ ps -ef|grep java
me    3532    3427  0 07:15 pts/0    00:00:00 grep --color=auto java
```

**No output returned from `ps`**

**Comment by joakime** [comment]
Of course, the command line you ran did what you told it to do.

`--add-to-start=<modules>` is terminal, it configures and exits.

The option `log4j.version=1.2.17` is the key piece to your issue.

Using it with `--add-to-start=<modules>` will satisfy that one step, configuring your start for log4j.

Now execute jetty like before.

If you still have issues, make sure to add the line `log4j.version=1.2.17` to one of the following ...

* Your command line argument when you execute Jetty (eg: `java -jar start.jar log4j.version=1.2.17`)
* Or add it to your `${jetty.base}/start.ini` (as a new line at the end of the file)
* Or add it to your your `${jetty.base}/start.d/logging-log4j.ini` (as a new line at the end of the file)

Then start Jetty again.
