### ISSUE TITLE
Inconsistent exception (SSLException or SocketException) returned when client is untrusted (needClientAuth=true)

### ISSUE THREAD

**Issue by christrotteradhoc** [eclipse/jetty.project#7021]
**Jetty version(s)**
10.0.7, others not tested.

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

**OS type/version**
MacOS 10.15.7

**Description**
With jetty configured for SSL with needClientAuth=true, a connection from a client with an untrusted certificate usually results in an SSLException but intermittently results in a SocketException due to a socket write failure on the client.

**How to reproduce?**
Start jetty with https and ssl modules with needClientAuth=true and configure keystore and truststore on the server.
Attempt to connect with a client that is not trusted.
May require multiple runs to observe the SocketException.

This unit test was used for the client:

```
  @Test(expected = SSLException.class)
  public void accessDeniedForClientCertThatIsNotTrusted() throws Exception {
    SSLContextBuilder sslContextBuilder = SSLContexts.custom();

    sslContextBuilder.loadKeyMaterial(
        Paths.get("..", "dev", "ssl-stores").resolve("client-untrusted-keystore.jks").toFile(),
        "changeit".toCharArray(),
        "changeit".toCharArray());

    sslContextBuilder.loadTrustMaterial(
        Paths.get("..", "dev", "ssl-stores").resolve("client-truststore.jks").toFile(),
        "changeit".toCharArray());

    SSLContext sslContext = sslContextBuilder.build();

    try (CloseableHttpClient httpClient =
            HttpClientBuilder.create().setSSLContext(sslContext).build();
        CloseableHttpResponse httpResponse =
            httpClient.execute(new HttpGet("https://127.0.0.1:9833/")); ) {
      Assert.assertEquals(200, httpResponse.getStatusLine().getStatusCode());
    }
  }
```

The output on the client:

```
{"timestamp":"2021-10-20T16:56:16.387+0000","level":"INFO","thread":"main","logger":"org.apache.http.impl.execchain.RetryExec","message":"I/O exception (java.net.SocketException) caught when processing request to {s}->https://127.0.0.1:9833: Broken pipe (Write failed)","context":"default"}
{"timestamp":"2021-10-20T16:56:16.401+0000","level":"INFO","thread":"main","logger":"org.apache.http.impl.execchain.RetryExec","message":"Retrying request to {s}->https://127.0.0.1:9833","context":"default"}
{"timestamp":"2021-10-20T16:56:16.506+0000","level":"INFO","thread":"main","logger":"org.apache.http.impl.execchain.RetryExec","message":"I/O exception (java.net.SocketException) caught when processing request to {s}->https://127.0.0.1:9833: Broken pipe (Write failed)","context":"default"}
{"timestamp":"2021-10-20T16:56:16.506+0000","level":"INFO","thread":"main","logger":"org.apache.http.impl.execchain.RetryExec","message":"Retrying request to {s}->https://127.0.0.1:9833","context":"default"}
{"timestamp":"2021-10-20T16:56:16.585+0000","level":"INFO","thread":"main","logger":"org.apache.http.impl.execchain.RetryExec","message":"I/O exception (java.net.SocketException) caught when processing request to {s}->https://127.0.0.1:9833: Broken pipe (Write failed)","context":"default"}
{"timestamp":"2021-10-20T16:56:16.585+0000","level":"INFO","thread":"main","logger":"org.apache.http.impl.execchain.RetryExec","message":"Retrying request to {s}->https://127.0.0.1:9833","context":"default"}

java.lang.Exception: Unexpected exception, expected<javax.net.ssl.SSLException> but was<java.net.SocketException>

	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:30)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:319)
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1224)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flush(SessionOutputBufferImpl.java:144)
	at org.apache.http.impl.BHttpConnectionBase.doFlush(BHttpConnectionBase.java:174)
	at org.apache.http.impl.DefaultBHttpClientConnection.flush(DefaultBHttpClientConnection.java:183)
	at org.apache.http.impl.conn.CPoolProxy.flush(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:241)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
...
```

Output from Jetty:

```
...
2021-10-20 12:55:59.855:INFO :oejs.AbstractConnector:main: Started ServerConnector@1ed4ae0f{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:9833}
2021-10-20 12:55:59.857:INFO :oejs.AbstractConnector:main: Started ServerConnector@1acaf3d{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-10-20 12:55:59.870:INFO :oejs.Server:main: Started Server@50dfbc58{STARTING}[10.0.7,sto=5000] @2536ms
2021-10-20 12:56:16.378:DEBUG:oejs.NegotiatingServerConnection:qtp728115831-33: Unable to fill from endpoint DecryptedEndPoint@78cb5ccb{l=null,r=null,CLOSED,fill=-,flush=-,to=36/30000}
javax.net.ssl.SSLHandshakeException: Empty client certificate chain
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1194)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1181)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:647)
	at org.eclipse.jetty.server.NegotiatingServerConnection.fill(NegotiatingServerConnection.java:147)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:92)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:548)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:397)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-20 12:56:16.379:DEBUG:oejs.NegotiatingServerConnection:qtp728115831-33: ALPNServerConnection@4a45d143::DecryptedEndPoint@78cb5ccb{l=null,r=null,CLOSED,fill=-,flush=-,to=36/30000} detected close on client side
2021-10-20 12:56:16.505:DEBUG:oejs.NegotiatingServerConnection:qtp728115831-33: Unable to fill from endpoint DecryptedEndPoint@4e463c00{l=null,r=null,CLOSED,fill=-,flush=-,to=13/30000}
javax.net.ssl.SSLHandshakeException: Empty client certificate chain
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1194)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1181)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:647)
	at org.eclipse.jetty.server.NegotiatingServerConnection.fill(NegotiatingServerConnection.java:147)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:92)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:548)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:397)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-20 12:56:16.505:DEBUG:oejs.NegotiatingServerConnection:qtp728115831-33: ALPNServerConnection@3a49716e::DecryptedEndPoint@4e463c00{l=null,r=null,CLOSED,fill=-,flush=-,to=13/30000} detected close on client side
2021-10-20 12:56:16.584:DEBUG:oejs.NegotiatingServerConnection:qtp728115831-33: Unable to fill from endpoint DecryptedEndPoint@6199ee64{l=null,r=null,CLOSED,fill=-,flush=-,to=7/30000}
javax.net.ssl.SSLHandshakeException: Empty client certificate chain
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1194)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1181)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:647)
	at org.eclipse.jetty.server.NegotiatingServerConnection.fill(NegotiatingServerConnection.java:147)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:92)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:548)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:397)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-20 12:56:16.585:DEBUG:oejs.NegotiatingServerConnection:qtp728115831-33: ALPNServerConnection@1e40786b::DecryptedEndPoint@6199ee64{l=null,r=null,CLOSED,fill=-,flush=-,to=8/30000} detected close on client side
2021-10-20 12:56:16.648:DEBUG:oejs.NegotiatingServerConnection:qtp728115831-33: Unable to fill from endpoint DecryptedEndPoint@22d94a87{l=null,r=null,CLOSED,fill=-,flush=-,to=8/30000}
javax.net.ssl.SSLHandshakeException: Empty client certificate chain
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1194)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1181)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:647)
	at org.eclipse.jetty.server.NegotiatingServerConnection.fill(NegotiatingServerConnection.java:147)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:92)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:548)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:397)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-20 12:56:16.648:DEBUG:oejs.NegotiatingServerConnection:qtp728115831-33: ALPNServerConnection@c9d7a76::DecryptedEndPoint@22d94a87{l=null,r=null,CLOSED,fill=-,flush=-,to=9/30000} detected close on client side
```

**Comment by sbordet** [comment]
Closing, as I don't think this is a Jetty issue.

The client is writing data to the server while reading data from it.

It happens that sometimes the write is finished without errors, and the read reads a TLS alert that yields the `SSLHandshakeException`.

Some other time, the read happens before the write finishes, or a TCP RST arrives before the write, so the write fails with a `SocketException`.

I don't think there is much that we can do on the Jetty side, as the server is probably replying to the client with exactly the same bytes.
It's just a timing issue on the client.
