### ISSUE TITLE
Error in parse parameter in broken UTF-8 encoding

### ISSUE THREAD

**Issue by Okapist** [eclipse/jetty.project#7073]
**Jetty version(s)**
9.4.44.v20210927

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

**OS type/version**
Any

**Description**
Jetty fail with 5xx with error
```
HTTP ERROR 500 org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 0<
org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 0
        at org.eclipse.jetty.util.Utf8Appendable.checkCharAppend(Utf8Appendable.java:108)
        at org.eclipse.jetty.util.Utf8Appendable.append(Utf8Appendable.java:116)
        at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:364)
        at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:228)
        at org.eclipse.jetty.server.Request.mergeQueryParameters(Request.java:2535)
        at org.eclipse.jetty.server.Server.handleAsync(Server.java:550)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$2(HttpChannel.java:408)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:408)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
in async Spring call

**How to reproduce?**

Controller
```
    @RequestMapping(value = { "/handler"}, method = RequestMethod.GET)
    @PreAuthorize("permitAll()")
    @ResponseBody
    @Async
    public CompletableFuture<String> ping(HttpServletResponse resp,
                                                   @RequestParam(required = false)
                                                           String searchString) {
        return CompletableFuture.completedFuture("result");
    }

```

Call
`curl "http://localhost:8080/handler?searchString=%E8."`

**Comment by joakime** [comment]
That is a bad URI.  (Google Chrome Javascript agrees)

![issue-7073-bad-uri](https://user-images.githubusercontent.com/191721/139921038-398456b7-f537-4737-b868-6ef655ef82fa.png)

**Comment by joakime** [comment]
If you were attempting to use LATIN SMALL LETTER E WITH GRAVE -> `è`

https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=e8&mode=hex

Hex Code Point: 00E8
Hex UTF-8 Bytes: C3 A8

The correct URL would be ..

```
http://localhost:8080/handler?searchString=%C3%A8
```

**Comment by joakime** [comment]
OpenJDK 11.0.12's JShell agrees with Jetty as well.

That is a bad URI.

![issue-7073-bad-uri-query](https://user-images.githubusercontent.com/191721/139921968-eb485e92-c7f3-40de-b776-7f8cc8d2a4ea.png)

Notice that the bad character is replaced with the **�** character?
This is the UTF-8 "Replacement Character", meaning it's bad.

See: 

* https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character
* https://www.compart.com/en/unicode/U+FFFD

**Comment by joakime** [comment]
Closing as "Not a bug".

**Comment by Okapist** [comment]
I know that it's malformed URL, but 5xx response looks bad.
May be change it to some 4xx code? Or put null into parameter and work normally?

Users make those requests by some scripts or other software without validation. 5xx response look for them like server work incorrectly. Not like incorrect request.

**Comment by joakime** [comment]
The 500 response is not being returned by Jetty.
Jetty produces a 400 response.

**Jetty 10.0.7 example ...**

```
$ curl -vvvv http://localhost:8080/test/dump/info?search=%E8.
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test/dump/info?search=%E8. HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Set-Cookie: visited=yes
< Set-Cookie: JSESSIONID=node03cmf6lujdd0egoghjpl8alht2.node0; Path=/test
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 6157
< Connection: close
< Server: Jetty(10.0.7)
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Unable to parse URI query</title>
</head>
<body><h2>HTTP ERROR 400 Unable to parse URI query</h2>
<table>
<tr><th>URI:</th><td>/test/dump/info</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Unable to parse URI query</td></tr>
<tr><th>SERVLET:</th><td>Dump</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.http.BadMessageException: 400: Unable to parse URI query</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 36</td></tr>
</table>
<h3>Caused by:</h3><pre>org.eclipse.jetty.http.BadMessageException: 400: Unable to parse URI query
	at org.eclipse.jetty.server.Request.extractQueryParameters(Request.java:494)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:460)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:1049)
	at com.acme.Dump.doGet(Dump.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder$RunAs.service(ServletHolder.java:1371)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1624)
	at com.acme.TestFilter.doFilter(TestFilter.java:91)
```

**And Jetty 9.4.44 example ...**

```
$ curl -vvvv http://localhost:8080/test/dump/info?search=%E8.
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test/dump/info?search=%E8. HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Set-Cookie: visited=yes
< Set-Cookie: JSESSIONID=node011nac4ldnpwgw3p7783in8px20.node0; Path=/test
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 5537
< Connection: close
< Server: Jetty(9.4.44.v20210927)
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Unable to parse URI query</title>
</head>
<body><h2>HTTP ERROR 400 Unable to parse URI query</h2>
<table>
<tr><th>URI:</th><td>/test/dump/info</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Unable to parse URI query</td></tr>
<tr><th>SERVLET:</th><td>Dump</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.http.BadMessageException: 400: Unable to parse URI query</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 36</td></tr>
</table>
<h3>Caused by:</h3><pre>org.eclipse.jetty.http.BadMessageException: 400: Unable to parse URI query
	at org.eclipse.jetty.server.Request.getParameters(Request.java:454)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:1075)
	at com.acme.Dump.doGet(Dump.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$RunAs.service(ServletHolder.java:1411)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at com.acme.TestFilter.doFilter(TestFilter.java:107)
```

**Comment by joakime** [comment]
Even if all you talk is `application/json` to Jetty you'll get a 400 response from Jetty.

```
$ curl -vvvv -H "Accept: application/json" http://localhost:8080/test/dump/info?search=%E8.
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test/dump/info?search=%E8. HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Set-Cookie: visited=yes
< Set-Cookie: JSESSIONID=node0hjhqn2g2oosl17yquha2cy6i1.node0; Path=/test
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: application/json
< Content-Length: 297
< Connection: close
< Server: Jetty(9.4.44.v20210927)
< 
{
"cause1":"org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 36",
"servlet":"Dump",
"cause0":"org.eclipse.jetty.http.BadMessageException: 400: Unable to parse URI query",
"message":"Unable to parse URI query",
"url":"/test/dump/info",
"status":"400"
* Closing connection 0
}
```

This is the behavior of the Server level `ErrorHandler` btw.

**Comment by joakime** [comment]
I'm reopening to check the specific use case ...

```
        at org.eclipse.jetty.server.Request.mergeQueryParameters(Request.java:2535)
        at org.eclipse.jetty.server.Server.handleAsync(Server.java:550)
```

**Comment by Okapist** [comment]
Check async. Sync work correct.
```
curl "http://localhost:8082/ping?search_string=%E8." -vvv
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /ping?uid_real=870143455&search_string=%E8. HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 500 Server Error
< Set-Cookie: JSESSIONID=node011a86k6j5bvq3a83i3djakeol1.node0; Path=/
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 2198
< Connection: close
< Server: Jetty(9.4.44.v20210927)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 0</title>
</head>
<body><h2>HTTP ERROR 500 org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 0</h2>
<table>
<tr><th>URI:</th><td>/ping</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 0</td></tr>
<tr><th>SERVLET:</th><td>faced</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 0</td></tr>
</table>
<h3>Caused by:</h3><pre>org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! char appended in state 0
        at org.eclipse.jetty.util.Utf8Appendable.checkCharAppend(Utf8Appendable.java:108)
        at org.eclipse.jetty.util.Utf8Appendable.append(Utf8Appendable.java:116)
        at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:364)
        at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:228)
        at org.eclipse.jetty.server.Request.mergeQueryParameters(Request.java:2535)
        at org.eclipse.jetty.server.Server.handleAsync(Server.java:550)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$2(HttpChannel.java:408)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:408)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:834)
</pre>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.44.v20210927</a><hr/>

</body>
</html>
* Closing connection 0
```

**Comment by joakime** [comment]
Using `startAsync` with bad query does not produce an error 400 or 500.

Opened PR #7075 with testcase.

**Comment by joakime** [comment]
PR #7075 has been merged.

It has 2 tests of `AsyncContext.dispatch(String)`

1. Client provided mistake in query encoding. (aka: original query)
    Ensure that it results in a 400 error.
2. Application provided mistake in query encoding. (aka: new query)
    Ensure that it results in a 500 error.
