### ISSUE TITLE
Resource.addPath(String) should encode quote (") character

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#715]
When an addPath(String) is used, the quote character is not encoded, and it should be.

Seen in `jetty-dev` mailing list ([post from Michele Rossi](https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg02759.html)) :

```
14:21:49.211|WARN |   o.e.j.s.DefaultServlet|7C662196D528189A4E|a_bates   |UBSW_LON| EXCEPTION 
java.nio.file.InvalidPathException: Illegal char <"> at index 66: C:\Work\Workspaces\idr\iod-aggregator\iod-html\src\main\js\dist\/["dojo/_base/lang"]/</p.hitch/<@http://localhost:8686/js/html5/lib/gridx/gridx/grid-all.js
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at org.eclipse.jetty.util.resource.PathResource.<init>(PathResource.java:202)
	at org.eclipse.jetty.util.resource.PathResource.addPath(PathResource.java:293)
	at org.eclipse.jetty.servlet.DefaultServlet.getResource(DefaultServlet.java:401)
	at org.eclipse.jetty.server.ResourceCache.getContent(ResourceCache.java:202)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:468)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
```

**Comment by sbordet** [comment]
@mrossi975, I would double check that you're not doing something wrong on your client.

The path looks like a path built by Dojo to fetch dependencies, but it does not look right, so I am guessing some misconfiguration on your client.

**Comment by joakime** [comment]
This is actually a limitation in the Windows FileSystem implementation in Java (it won't accept quotes)

To follow along, we have:

 1. A Base Resource of `C:\Work\Workspaces\idr\iod-aggregator\iod-html\src\main\js\dist\`
 2. A Raw Request Path Info of `[%22dojo/_base/lang%22]/%3C/p.hitch/%3C@http://localhost:8686/js/html5/lib/gridx/gridx/grid-all.js`
 3. Which arrives to Jetty and is decode as `/["dojo/_base/lang"]/</p.hitch/<@http://localhost:8686/js/html5/lib/gridx/gridx/grid-all.js`
 4. [`PathResource.addPath() #L293`](https://github.com/eclipse/jetty.project/blob/jetty-9.3.10.v20160621/jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java#L293) - is where we enter the `PathResource`
 5. [`PathResource() #L202`](https://github.com/eclipse/jetty.project/blob/jetty-9.3.10.v20160621/jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java#L202) is where the decoded path is sent to [`Files.getPath(String, String...)`](http://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPath-java.lang.String-java.lang.String...-) and is rejected by Java for having a character forbidden by its Windows FileSystem implementation.

At this point, we have a few options ...

 * We can throw a better Exception, perhaps one for bad Resources?
 * We can catch this InvalidPathException in .addPath() and return a null resource?
 * The user of the Resource API can fix the bad request path info to not include illegal characters for static file resources.
