### ISSUE TITLE
Jetty does not deal well when no body is returned in the response

### ISSUE THREAD

**Issue by aaronjwhiteside** [eclipse/jetty.project#7170]
**Jetty version(s)**
9.4.44.v20210927

We upgraded from 9.4.24.v20191120, which didn't exhibit this problem.

**Java version/vendor** `(use: java -version)`
```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macosx) (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macosx) (build 25.312-b07, mixed mode)
```
**OS type/version**
```
Darwin xxxx.local 18.7.0 Darwin Kernel Version 18.7.0: Mon May  3 20:41:19 PDT 2021; root:xnu-4903.278.68~1/RELEASE_X86_64 x86_64
```

**Description**
It seems there is some issue with handling responses with no body, jetty throws two exceptions and closed the socket, but only after the response has actually been sent.

```
2021-11-29 14:32:50.008 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.io.WriteFlusher        : update WriteFlusher@f62e3dc{IDLE}->null:WRITING-->IDLE
2021-11-29 14:32:50.008 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.server.HttpConnection  : generate: DONE for SendCallback@1d24a67c[PROCESSING][i=HTTP/1.1{s=501,h=9,cl=0},cb=org.eclipse.jetty.server.HttpChannel$SendCallback@4bd9a77e] ([p=325,l=325,c=8192,r=0],[p=0,l=0,c=0,r=0],false)@COMMITTED
2021-11-29 14:32:50.008 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.server.HttpOutput      : onWriteComplete(false,null) s=OPEN,api=BLOCKED,sc=true,e=null->s=OPEN,api=BLOCKING,sc=true,e=null c=null cb=null w=false
2021-11-29 14:32:50.008 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.server.session         : Leaving scope org.eclipse.jetty.server.session.SessionHandler546685745==dftMaxIdleSec=1800 dispatch=REQUEST, async=false, session=null, oldsession=null, oldsessionhandler=null
2021-11-29 14:32:50.008 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.server.Server          : handled=true async=false committed=true on HttpChannelOverHttp@7f6fa809{s=HttpChannelState@1ceadf86{s=HANDLING rs=BLOCKING os=COMMITTED is=READY awp=false se=true i=true al=0},r=5,c=false/false,a=HANDLING,uri=//localhost:64771/user-auth/api/v1/roles/0,age=40}
2021-11-29 14:32:50.009 DEBUG 47788 --- [tp1363127070-25] o.eclipse.jetty.server.HttpChannelState  : unhandle HttpChannelState@1ceadf86{s=HANDLING rs=BLOCKING os=COMMITTED is=READY awp=false se=true i=true al=0}
2021-11-29 14:32:50.009 DEBUG 47788 --- [tp1363127070-25] o.eclipse.jetty.server.HttpChannelState  : nextAction(false) SEND_ERROR HttpChannelState@1ceadf86{s=HANDLING rs=BLOCKING os=COMMITTED is=READY awp=false se=false i=false al=0}
2021-11-29 14:32:50.009 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.server.HttpChannel     : action SEND_ERROR HttpChannelOverHttp@7f6fa809{s=HttpChannelState@1ceadf86{s=HANDLING rs=BLOCKING os=COMMITTED is=READY awp=false se=false i=false al=0},r=5,c=false/false,a=HANDLING,uri=//localhost:64771/user-auth/api/v1/roles/0,age=41}
2021-11-29 14:32:50.009 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.server.HttpChannel     : Could not perform ERROR dispatch, aborting
java.lang.IllegalStateException: Committed
	at org.eclipse.jetty.server.HttpChannel.resetBuffer(HttpChannel.java:1006) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpOutput.resetBuffer(HttpOutput.java:1467) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.Response.resetContent(Response.java:1170) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:421) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_312]
```

```
2021-11-29 14:32:50.012 DEBUG 47788 --- [tp1363127070-32] o.e.jetty.util.thread.QueuedThreadPool   : ran org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint@4a7329e3 in QueuedThreadPool[qtp1363127070]@513fab1e{STARTED,8<=10<=200,i=0,r=-1,q=0}[ReservedThreadExecutor@6d6712b7{reserved=1/12,pending=0}]
2021-11-29 14:32:50.012 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.server.HttpChannel     : sendResponse info=null content=HeapByteBuffer@1b22e9bd[p=0,l=0,c=0,r=0]={<<<>>>} complete=true committing=false callback=org.eclipse.jetty.server.HttpOutput$WriteCompleteCB@4329edd9
2021-11-29 14:32:50.013 DEBUG 47788 --- [tp1363127070-25] org.eclipse.jetty.server.HttpChannel     : Commit failed
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:735) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$300(HttpConnection.java:694) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:553) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:927) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:999) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:285) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpOutput.complete(HttpOutput.java:515) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.Response.completeOutput(Response.java:926) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:550) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_312]
```

The issue affects the next request sent on the connection, if the client was unlucky enough to not pick-up that the connection was closed by the server.

Please see full log attached: [jetty log](https://github.com/eclipse/jetty.project/files/7615377/jetty.log)

**How to reproduce?**
Request and Response is in the logs, basically return a response with no body.

Request:
```
DELETE http://localhost:64771/user-auth/api/v1/roles/0 HTTP/1.1
Accept: application/json, application/cbor, application/*+json
Accept-Encoding: gzip,deflate
Authorization: XXX
Connection: keep-alive
Content-Length: 0
Host: localhost:64771
User-Agent: Apache-HttpClient/4.5.13 (Java/1.8.0_312)
X-B3-Sampled: 1
X-B3-SpanId: fb0e856bd331e4a7
X-B3-TraceId: 61a449e16e85a7a8fb0e856bd331e4a7
```

Response:
```
HTTP/1.1 501 Not Implemented
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Length: 0
Date: Mon, 29 Nov 2021 03:32:49 GMT
Expires: 0
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-YapStone-Trace-ID: 61a449e16e85a7a8fb0e856bd331e4a7
```

**Comment by aaronjwhiteside** [comment]
You can compare the log output to one with a response body.

[jetty log with a response body.log](https://github.com/eclipse/jetty.project/files/7615403/jetty.log.with.a.response.body.log)

**Comment by joakime** [comment]
I'm trying to replicate this reported issue.

> The issue affects the next request sent on the connection, if the client was unlucky enough to not pick-up that the connection was closed by the server.

BTW, If a client failed this, then that would be a badly implemented client not following the HTTP spec.
The server is free to close the connection at any point per spec.

**Comment by joakime** [comment]
Small note, your Apache HttpClient is still sending ...

```
Connection: keep-alive
```

... on HTTP/1.1 requests.
Make sure you configure your Apache HttpClient to not do that.
That token `keep-alive` has absolutely no meaning to any HTTP/1.1 server. (it's specifically not present in the HTTP/1.1 spec)
That's an HTTP/1.0 concept and feature, and should not be sent to HTTP/1.1 endpoints.
This header can trip up many proxy server and load balancers, that make (bad) assumptions that are not true.

**Comment by joakime** [comment]
I tried to replicate in a simple testcase which can be found at ...

https://github.com/joakime/jetty-issue-7170-no-body-response

It simply has a `WebAppContext` with a servlet on url-pattern `/nobody` that just returns status code 501 on method DELETE and does nothing else.
This produces a response with no body, as expected, without the issues seen in your logs.

Your logs with `org.eclipse.jetty.server.HttpChannel : Commit failed` are telling me that you have something happening after commit.
Some bad piece of code that is attempting to do something to the response that is not supported after `HttpServletResponse.isCommitted() == true`.

Feel free to clone the above test repo and alter it to produce the issue you are seeing.

**Comment by janbartel** [comment]
@aaronjwhiteside nudge? Any comments in response to @joakime's test code?
