### ISSUE TITLE
Logging in AbstractConnection.onFillInterestedFailed should not trigger exception

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7178]
**Jetty version(s)**
10.0.7

**Java version/vendor** `(use: java -version)`
11

**OS type/version**
Linux

**Description**
When logging at DEBUG level is on, and the connection is closed, the logging at `AbstractConnection.onFillInterestedFailed` can trigger an exception when it attempts to get the remote address.
This should not fail like this, the attempt to retrieve the socket address should return an "unavailable" style value/output in the logging if it fails instead.

```
2021-11-29 09:28:55.175:DEBUG:oeji.SocketChannelEndPoint:qtp895281180-32: Could not retrieve remote socket address
java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:160)
	at java.base/sun.nio.ch.SocketChannelImpl.getRemoteAddress(SocketChannelImpl.java:204)
	at org.eclipse.jetty.io.SocketChannelEndPoint.getRemoteSocketAddress(SocketChannelEndPoint.java:181)
	at org.eclipse.jetty.io.AbstractEndPoint.toEndPointString(AbstractEndPoint.java:506)
	at org.eclipse.jetty.io.SocketChannelEndPoint.toEndPointString(SocketChannelEndPoint.java:443)
	at org.eclipse.jetty.io.AbstractEndPoint.toString(AbstractEndPoint.java:489)
	at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3031)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2908)
	at java.base/java.util.Formatter.format(Formatter.java:2673)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at org.eclipse.jetty.io.AbstractConnection.toString(AbstractConnection.java:304)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:291)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:263)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:225)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:160)
	at org.eclipse.jetty.logging.StdErrAppender.format(StdErrAppender.java:162)
	at org.eclipse.jetty.logging.StdErrAppender.emit(StdErrAppender.java:93)
	at org.eclipse.jetty.logging.JettyLogger.emit(JettyLogger.java:631)
	at org.eclipse.jetty.logging.JettyLogger.debug(JettyLogger.java:172)
	at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:168)
	at org.eclipse.jetty.server.HttpConnection.onFillInterestedFailed(HttpConnection.java:534)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:325)
	at org.eclipse.jetty.io.FillInterest.onClose(FillInterest.java:147)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:386)
	at org.eclipse.jetty.io.SocketChannelEndPoint.onClose(SocketChannelEndPoint.java:237)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:376)
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:261)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:225)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:208)
	at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:262)
	at org.eclipse.jetty.util.IO.close(IO.java:407)
	at org.eclipse.jetty.io.ManagedSelector$CloseConnections.update(ManagedSelector.java:1012)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processUpdates(ManagedSelector.java:566)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:537)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:446)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:239)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by joakime** [comment]
This has been solved in Jetty 12.
