### ISSUE TITLE
Slow CONNECT request causes NPE

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#7348]
**Jetty version(s)**
9.4.x+

**Description**
When `HttpClient` is configured with an `HttpProxy`, and a request is made through the proxy, this NPE may happen:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()" because "this.networkBuffer" is null
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.onUpgradeFrom(HttpReceiverOverHTTP.java:123)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onUpgradeFrom(HttpConnectionOverHTTP.java:179)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:432)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.tunnelSucceeded(HttpProxy.java:220)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.lambda$tunnel$0(HttpProxy.java:189)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpSender.terminateRequest(HttpSender.java:411)
	at org.eclipse.jetty.client.HttpSender.someToSuccess(HttpSender.java:331)
	at org.eclipse.jetty.client.HttpSender$CommitCallback.process(HttpSender.java:744)
	at org.eclipse.jetty.client.HttpSender$CommitCallback.succeeded(HttpSender.java:710)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.onCompleteSuccess(HttpSenderOverHTTP.java:307)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:326)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:65)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:212)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:84)
	at org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:125)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:241)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:269)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:88)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:120)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.tunnel(HttpProxy.java:180)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.succeeded(HttpProxy.java:150)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.succeeded(HttpProxy.java:131)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:133)
	at org.eclipse.jetty.io.ssl.SslConnection.onOpen(SslConnection.java:372)
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:324)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:402)
	at org.eclipse.jetty.io.ManagedSelector.access$2100(ManagedSelector.java:65)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:1069)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sbordet** [comment]
The cause for the NPE is that the CONNECT request completion happens _after_ the response completion, so the upgrade to a tunnel happens from the request side rather than, more commonly, from the response side.

Since the response is already completed, the `networkBuffer` has already been disposed, and when also the request completes, the code attempts to upgrade and finds `networkBuffer` to be `null`, causing the NPE.

Note that the upgrade is performed from the _complete_ event, so there is no thread race here, just a wrong assumption on the order of events, in particular that the request completes before the response, which may not be the case.
