### ISSUE TITLE
Error while starting up http server - java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by 4devwithgit** [eclipse/jetty.project#7415]
**Jetty version(s)** - 9_4_40

**Java version/vendor** `(use: java -version)` - IBM JDK8 SR6 FP20

**OS type/version** - Linux

**Description**
During the startup of the http server based on jetty 9.4.40, we are seeing below error,

[2021-12-29 11:51:57.83] DEBUG JettyPsServerConnector.buildCACert(): adding cert id:9090151641236f173node1
[2021-12-29 11:51:57.857] ERROR PSHttpAdapterImpl.startHttpServer() - Exception thrown while starting up http server adapter  
[2021-12-29 11:51:57.857] ERROR 
[2021-12-29 11:51:57.857] ERROR PSHttpAdapterImpl.startupAdapter() - Unable to start the adapter [PNC_HTTPServer_N1_21443_HttpServerAdapter_node1] with configuration HTTP Server Adapter with port [21443], perimeterServer [local], cluster [node1]] due to an exception:
[2021-12-29 11:51:57.857] ERROR [1640796717857] null
[2021-12-29 11:51:57.857] ERRORDTL [1640796717857]java.nio.channels.ClosedChannelException
	at java.nio.channels.spi.AbstractSelectableChannel.configureBlocking(AbstractSelectableChannel.java:300)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:238)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.sterlingcommerce.woodstock.services.pshttp.jetty.impl.HttpServer.startHttpServer(HttpServer.java:124)
	at com.sterlingcommerce.woodstock.services.pshttp.PSHttpAdapterImpl.startHTTPJettyServer(PSHttpAdapterImpl.java:425)
	at com.sterlingcommerce.woodstock.services.pshttp.PSHttpAdapterImpl.startupAdapter(PSHttpAdapterImpl.java:270)
	at com.sterlingcommerce.woodstock.services.IAdapterImpl.startAdapter(IAdapterImpl.java:265)
	at com.sterlingcommerce.woodstock.services.controller.StartAdapterThread.run(StartAdapterThread.java:104)
	at java.lang.Thread.run(Thread.java:822)

**How to reproduce?**

**Comment by joakime** [comment]
The `PSHttpAdapterImpl` and `JettyPsServerConnector` have bugs.

Not a Jetty issue.

**Comment by joakime** [comment]
Also, Jetty 9.4.40 is subject to several security advisories, would suggest upgrading.

https://www.eclipse.org/jetty/security_reports.php

**Comment by joakime** [comment]
I think @sreedharj would be able to answer this.

**Comment by sreedharj** [comment]
This issue is happening when starting the HTTP Server,   Where as the issue which I reported was at runtime where HTTP Server Adapter had stopped processing the request.

@4devwithgit   please collect the perimeter server logs and jett server logs in debug mode
