### ISSUE TITLE
Miconfigured headerCacheSize in can result in IllegalArgumentException

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7569]
Recently upgraded to jetty-9.4.45.v20220128 to get the ALPN fix, but believe I am running into this issue. This does not happen in 9.4.44.

```
2022-02-11 09:12:13,507,DEBUG,org.eclipse.jetty.http.HttpParser - [qtp848102479-250]  [::] Parse exception: HttpParser{s=HEADER,0 of -1} for HttpChannelOverHttp@2bef0009{s=HttpChannelState@46d6747c{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=0,c=false/false,a=IDLE,uri=null,age=0}
org.eclipse.jetty.http.BadMessageException: 400: Bad Request
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1640) [jetty-http-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:381) [jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:265) [jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.IllegalArgumentException: Capacity 131072 > 65534
	at org.eclipse.jetty.util.ArrayTernaryTrie.<init>(ArrayTernaryTrie.java:151) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.ArrayTernaryTrie.<init>(ArrayTernaryTrie.java:133) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.http.HttpParser.parsedHeader(HttpParser.java:1077) ~[jetty-http-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1258) ~[jetty-http-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1528) [jetty-http-9.4.45.v20220203.jar:9.4.45.v20220203]
	... 12 more
```

_Originally posted by @jeffreyb-canon in https://github.com/eclipse/jetty.project/issues/7496#issuecomment-1036265012_

**Comment by joakime** [comment]
@jeffreyb-canon you have an `HttpConfiguration.setHeaderCacheSize(int)` that is far too large.

The default value for `headerCacheSize` is 1024.
The maximum value is 65534 - as defined in `ArrayTernaryTrie.MAX_CAPACITY`.

A value at 131072 is far too large, prior to Jetty 9.4.45 that configuration would result in quietly lost data (if you somehow managed to have a cache that exceeded 65534 characters, which is extremely unlikely).

This is a legitimate failure due to an oversized headerCacheSize.
However, it's failing far too late IMO, we should fail this earlier, during startup, with a clear message instead.

**Comment by joakime** [comment]
The changes that triggered this IllegalArgumentException come from ...

* Issue #7271 
* PR #7405

**Comment by canon-CMI-jeffrey-brydges** [comment]
@joakime Thank you for the clarification and quick reply. Is there an exposed constant which I can reference to use as our max size?

**Comment by joakime** [comment]
@jeffreyb-canon there is currently no public constant.

https://github.com/eclipse/jetty.project/blob/4a0c91c0be53805e3fcffdcdcc9587d5301863db/jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTernaryTrie.java#L72-L77

The PR I just opened #7570 will make that constant available.
Along with a exception when the `headerCacheSize` is set too large at server startup.

**Comment by joakime** [comment]
@jeffreyb-canon I would actually suggest you don't set the headerCacheSize too big.

Historically the default value started out at 512 and the cache was always full and inefficiently used.
Then we bumped the default value to 4096 and had many reports of increased memory usage.
It was brought down to 1024 to better fit with the real world usages.

At 65534 you would be barely using 5% of that memory with your typical web browser, and 15% with an aggressive REST client.   
To use all 65534 bytes you would need a single connection, with well over 128,000 unique requests, where each request has headers that are completely unique (meaning ALL headers, even the header names) from the previous request, and even then, no request is even benefiting from the cache.

Don't overdo it with that value.
Why are you setting it that large in the first place?

**Comment by canon-CMI-jeffrey-brydges** [comment]
A client needed to send many ranges in the url to avoid sending many requests, which was valid in the API standard we were implementing. It looks like the header buffer size was set arbitrarily high to deal with this a while back and was never set to a reasonable number once support for these ranges in request body was implemented. 

We are in the process of validating the need for this large value now and appreciate the feedback.

**Comment by joakime** [comment]
I think you are confusing configurations.

header buffer size is the size of the buffer allowed to fit all of the headers for a single request (or response).
header cache size is the size of the cache used to minimize memory stress between requests on a single connection. (aka HTTP/1.1 persistent connection)

Adjusting the buffer size is common enough.
Adjusting cache size is very uncommon.

**Comment by joakime** [comment]
PR #7570 merged.
