### ISSUE TITLE
I have a problem about jetty thread BLOCKED

### ISSUE THREAD

**Issue by lijunyong** [eclipse/jetty.project#760]
"dw-27-acceptor-1@7af8c3e4-application@2d7a9786{HTTP/1.1}{0.0.0.0:8990}" #27 prio=5 os_prio=0 tid=0x00007f1c7d1ad800 nid=0x6ed1 waiting for monitor entry [0x00007f1c5c875000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:233)
	- waiting to lock <0x0000000083a2e478> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None
"dw-29-acceptor-0@fa2fec1-application@2d7a9786{HTTP/1.1}{0.0.0.0:8990}" #29 prio=5 os_prio=0 tid=0x00007f1c7d1b1000 nid=0x6ed3 runnable [0x00007f1c5c673000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	- locked <0x0000000083a2e478> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

**Comment by joakime** [comment]
What version of Jetty?

**Comment by sbordet** [comment]
This is completely normal.

Jetty uses multiple threads to accept connections, but the `accept()` operation is synchronized at the JDK level. While one thread is waiting to accept the connection, another thread is blocked waiting its turn to call `accept()`.

**Comment by lijunyong** [comment]
@sbordet How to solve this problem

**Comment by lijunyong** [comment]
@sbordet But the application always has no response

**Comment by sbordet** [comment]
That thread in blocked state is completely normal. 

If your application does not respond, you have a different problem. Try to take a JVM thread dump and analyze it. Make sure the Jetty thread pool has plenty of threads (use the default configuration if in doubt). It is most likely not a Jetty problem.

**Comment by lijunyong** [comment]
@sbordet thanks
