### ISSUE TITLE
java.nio.BufferOverflowException in IBM JDK

### ISSUE THREAD

**Issue by yanxinyuan** [eclipse/jetty.project#776]
When we did the high concurrency testing on our system with using IBM jdk, we found our embed jetty will throw the exception sometimes and when we changed to Oracle jdk, it will not throw this exception, 
and we do a lot of testing, and the results are the same, till now i can't find the issue which occurs.

Jetty: 
./DEventProcessor/lib/jetty-util-9.2.9.v20150224.jar
./DEventProcessor/lib/jetty-webapp-9.2.9.v20150224.jar
./DEventProcessor/lib/jetty-annotations-9.2.9.v20150224.jar
./DEventProcessor/lib/jetty-servlet-9.2.9.v20150224.jar
./DEventProcessor/lib/jetty-security-9.2.9.v20150224.jar
./DEventProcessor/lib/jetty-xml-9.2.9.v20150224.jar
./DEventProcessor/lib/jetty-server-9.2.9.v20150224.jar
./DEventProcessor/lib/jetty-http-9.2.9.v20150224.jar
./DEventProcessor/lib/jetty-io-9.2.9.v20150224.jar

JDK: 
java version "1.7.0"
Java(TM) SE Runtime Environment (build pxa6470_27sr3fp40-20160422_01(SR3 FP40))
IBM J9 VM (build 2.7, JRE 1.7.0 Linux amd64-64 Compressed References 20160406_298393 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR3_20160406_0942_B298393
JIT  - tr.r13.java_20160328_114186
GC   - R27_Java727_SR3_20160406_0942_B298393_CMPRSS
J9CL - 20160406_298393)
JCL - 20160421_01 based on Oracle jdk7u101-b14

Exception:
[2016-07-26 13:55:11:734] [qtp1623907514-272 - /dashboard/summary?] [com.delta.atm.servlet.DashBoardSummaryServlet.doGet.75] [ERROR] - Exception:
java.nio.BufferOverflowException: null
	at java.nio.Buffer.nextPutIndex(Buffer.java:525) ~[na:1.7.0]
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:163) ~[na:1.7.0]
	at org.eclipse.jetty.util.BufferUtil.append(BufferUtil.java:383) ~[jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:458) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.Iso88591HttpWriter.write(Iso88591HttpWriter.java:47) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:71) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at java.io.Writer.write(Writer.java:155) ~[na:1.7.0]
	at java.io.PrintWriter.newLine(PrintWriter.java:491) ~[na:1.7.0]
	at java.io.PrintWriter.println(PrintWriter.java:640) ~[na:1.7.0]
	at java.io.PrintWriter.println(PrintWriter.java:768) ~[na:1.7.0]
	at com.delta.atm.servlet.DashBoardSummaryServlet.handleGetSummary(DashBoardSummaryServlet.java:131) ~[na:na]
	at com.delta.atm.servlet.DashBoardSummaryServlet.doGet(DashBoardSummaryServlet.java:73) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [servlet-api-3.1.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
	at com.delta.atm.container.JettyAPIFilter.doFilter(JettyAPIFilter.java:101) [services.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
	at java.lang.Thread.run(Thread.java:809) [na:1.7.0]

**Comment by gregw** [comment]
Hi,
it is very unlikely that we will be able to investigate this issue as it is for an old version and IBM JDK.    If you can reproduce the problem on jetty 9.3, then we are more likely to be able to investigate as an open source issue.

If you cannot upgrade to jetty 9.3, then I suggest that you look to commercial support from webtide.com

**Comment by yanxinyuan** [comment]
ok, i will try 9.3 and see the result, thanks

**Comment by gregw** [comment]
OK, I'm closing this for now, please reopen if you can reproduce on 9.3
