### ISSUE TITLE
Failure in Jetty 12 HTTP/2 TrailersTest: RetainableByteBuffer already released

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#7775]
**Description**

Got once off failure when running `org.eclipse.jetty.http2.tests.TrailersTest#testRequestTrailerInvalidHpackReceived`.
I ran the test again a few times but did not reproduce the error.

Looks like there is a race where sometimes the buffer is released twice.

```
2022-03-24 15:22:59.555:INFO :oejs.Server:main: jetty-12.0.0-SNAPSHOT; built: unknown; git: ; jvm 17.0.2+8-LTS-86
2022-03-24 15:22:59.556:INFO :oejs.AbstractConnector:main: Started ServerConnector@341814d3{h2c, (h2c)}{0.0.0.0:35555}
2022-03-24 15:22:59.556:INFO :oejs.Server:main: Started Server@59cba5a{STARTING}[12.0.0-SNAPSHOT,sto=0] @10025ms
2022-03-24 15:22:59.562:WARN :oeju.Blocking:server-345: Blocking.Callback incomplete
2022-03-24 15:22:59.563:WARN :oejsh.ContextRequest:server-345: java.lang.IllegalStateException: already released RetainableByteBuffer@1e122a5{DirectByteBuffer@6be72e92[p=0,l=0,c=32768,r=0]={<<<>>>\x00\x00\x05\x00\x00\x00\x00\x00\x01...\x00\x00\x00\x00\x00\x00\x00},r=0} org.eclipse.jetty.server.HttpChannel$ErrorResponse@180669a1
java.lang.IllegalStateException: already released RetainableByteBuffer@1e122a5{DirectByteBuffer@6be72e92[p=0,l=0,c=32768,r=0]={<<<>>>\x00\x00\x05\x00\x00\x00\x00\x00\x01...\x00\x00\x00\x00\x00\x00\x00},r=0}
	at org.eclipse.jetty.io.RetainableByteBuffer.lambda$release$2(RetainableByteBuffer.java:109)
	at java.base/java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:281)
	at org.eclipse.jetty.io.RetainableByteBuffer.release(RetainableByteBuffer.java:106)
	at org.eclipse.jetty.http2.internal.HTTP2Connection$NetworkBuffer.completed(HTTP2Connection.java:472)
	at org.eclipse.jetty.http2.internal.HTTP2Connection$NetworkBuffer.succeeded(HTTP2Connection.java:461)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:398)
	at org.eclipse.jetty.http2.internal.HTTP2Session$DataCallback.succeeded(HTTP2Session.java:1458)
	at org.eclipse.jetty.http2.internal.HTTP2Stream.lambda$readData$1(HTTP2Stream.java:369)
	at org.eclipse.jetty.http2.IStream$Data.complete(IStream.java:224)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.release(HttpStreamOverHTTP2.java:181)
	at org.eclipse.jetty.server.Content$6.run(Content.java:408)
	at org.eclipse.jetty.server.Content.consumeAll(Content.java:422)
	at org.eclipse.jetty.server.Content.consumeAll(Content.java:380)
	at org.eclipse.jetty.http2.tests.TrailersTest$9.process(TrailersTest.java:352)
	at org.eclipse.jetty.server.Server.customizeHandleAndProcess(Server.java:162)
	at org.eclipse.jetty.server.HttpChannel$HandlerInvoker.run(HttpChannel.java:584)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
	at org.eclipse.jetty.http2.internal.HTTP2Connection.produce(HTTP2Connection.java:209)
	at org.eclipse.jetty.http2.internal.HTTP2Connection.onFillable(HTTP2Connection.java:156)
	at org.eclipse.jetty.http2.internal.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:379)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:833)
Suppressed: 
	|java.io.IOException: Content not consumed
	|	at org.eclipse.jetty.server.HttpStream.consumeAll(HttpStream.java:65)
	|	at org.eclipse.jetty.server.HttpChannel$ChannelCallback.failed(HttpChannel.java:1184)
	|	at org.eclipse.jetty.server.Server.customizeHandleAndProcess(Server.java:168)
	|	at org.eclipse.jetty.server.HttpChannel$HandlerInvoker.run(HttpChannel.java:584)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
	|	at org.eclipse.jetty.http2.internal.HTTP2Connection.produce(HTTP2Connection.java:209)
	|	at org.eclipse.jetty.http2.internal.HTTP2Connection.onFillable(HTTP2Connection.java:156)
	|	at org.eclipse.jetty.http2.internal.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:379)
	|	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	|	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	|	at java.base/java.lang.Thread.run(Thread.java:833)
2022-03-24 15:23:04.563:INFO :oejs.Server:main: Stopped Server@59cba5a{STOPPING}[12.0.0-SNAPSHOT,sto=0]
2022-03-24 15:23:04.564:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@341814d3{h2c, (h2c)}{0.0.0.0:0}

org.opentest4j.AssertionFailedError: 
Expected :true
Actual   :false
<Click to see difference>
```

**Comment by iiliev2** [comment]
@sbordet I am also seeing this error. I am using `AsyncMiddleManServlet` to build a transparent proxy. When the proxy is heavily utilised(5000 long running response streaming ~ minutes), and then all those requests get aborted by the clients at the same time, jetty seems to have a hard time executing all the `javax.servlet.WriteListener#onError` callbacks. I therefore modified the particular implementation(`org.eclipse.jetty.proxy.AsyncMiddleManServlet.ProxyWriter#onError`) to just execute in a separate thread(not the jetty server threads) and then this issue is easily reproducible.
I am using micrometer's `TimedHandler` to track the waiting server async contexts. Without my "fix" I am observing that most(thousands) of the async contexts don't get closed, or at least the `AsyncListener` is not being called to decrement the metric. With my "fix" a lot less contexts don't get closed(tens).

**Comment by sbordet** [comment]
@iiliev2 please open a new issue, with as many details as possible for your use case, and a reproducer, if you have it.
At least we need clear indications of what you have modified exactly (code snippets).
