### ISSUE TITLE
OSGi - java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.server.WebSocketServerFactory not found by org.eclipse.jetty.util 

### ISSUE THREAD

**Issue by greengooru** [eclipse/jetty.project#7835]
Using version 9.4.46
I am writing a simple WebSocket Server in OSGi. The Service is configured and initialized properly and it starts, however, when it receives the first connection, the Server fails to initialize and returns the following exception: `java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.server.WebSocketServerFactory not found by org.eclipse.jetty.util `

The file `org.eclipse.jetty.websocket.servlet.WebSocketServletFactory` at line 51 

`Class<? extends WebSocketServletFactory> wsClazz = Class.forName("org.eclipse.jetty.websocket.server.WebSocketServerFactory", true, Thread.currentThread().getContextClassLoader());`

fails to load the implementation even when the implementation bundle is present. Any sson solution/workaround for this?

**Comment by joakime** [comment]
Can you detail how you have started your OSGi environment.
Including which bundles you are using. (all of them, including any from the jetty-osgi sub-project bundles that you might have present)
Also include any ServiceLoader configurations you have for your OSGi environment as well (eg: spifly or equivalent).

**Comment by greengooru** [comment]
Hello @joakime 
I use this class to start the WebSocket:

```
public class WebSocketServer {
    private Server server = null;

    public void startServer(String wsHost, int wsPort, String wsPath) throws Exception {
        server = new Server();
        ServerConnector connector = new ServerConnector(server);
        connector.setHost(wsHost);
        connector.setPort(wsPort);
        server.addConnector(connector);

        ServletContextHandler context = new ServletContextHandler(server, "/", ServletContextHandler.SESSIONS);
        context.addServlet(MessagingServlet.class, "/"+wsPath);
        server.start();
    }

    public void stopServer() throws Exception {
        if (server != null)
            server.stop();
    }
}

```

```
public class MessagingServlet extends WebSocketServlet {
    @Override
    public void configure(WebSocketServletFactory factory) {
        factory.register(EventSocket.class);
    }
}

```

And finally: 
```
public class EventSocket extends WebSocketAdapter {
    private final CountDownLatch closureLatch = new CountDownLatch(1);

    @Override
    public void onWebSocketConnect(Session sess) {
        super.onWebSocketConnect(sess);
    }

    @Override
    public void onWebSocketText(String message) {
        super.onWebSocketText(message);
    }

    @Override
    public void onWebSocketClose(int statusCode, String reason) {
        super.onWebSocketClose(statusCode, reason);
        closureLatch.countDown();
    }

    @Override
    public void onWebSocketError(Throwable cause) {
        super.onWebSocketError(cause);
    }
}

```

The Bundles I am using with `<jettyVersion>9.4.46.v20220331</jettyVersion>`:

        <dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>websocket-api</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        **<dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>websocket-server</artifactId>        
            <version>${jettyVersion}</version>
        </dependency>**
        <dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>websocket-servlet</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>websocket-common</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-client</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.serviceloader</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-http</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-io</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util-ajax</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>${jettyVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-security</artifactId>
            <version>${jettyVersion}</version>
        </dependency>

It all compiles, starts well, until the first connection to the Server happens.

**Comment by joakime** [comment]
Your listed dependencies have no ServiceLoader support for OSGi.

``` xml
    <dependency>
        <groupId>org.osgi</groupId>
        <artifactId>org.osgi.service.serviceloader</artifactId>
        <version>1.0.0</version>
    </dependency>
```

That artifact is merely an OSGi declaration of the serviceloader namespace, and does not actually provide the ServiceLoader SPI that OSGi and Jetty needs.

Consider installing an OSGi ServiceLoader SPI (eg: Apache SpiFly) and try again.

**Comment by greengooru** [comment]
Perhaps if you could be a little more specific about what Bundle exactly should be added in order to make it work. I just tried with this SpiFly dependency:

```
        <dependency>
            <groupId>org.apache.aries.spifly</groupId>
            <artifactId>org.apache.aries.spifly.static.tool</artifactId>
            <version>1.3.4</version>
        </dependency>
```
But still the same issue. Is there one dependency you know about?
Here bellow you can see the StackTrace of the exception:

```
java.lang.RuntimeException: Unable to load org.eclipse.jetty.websocket.server.WebSocketServerFactory
        at org.eclipse.jetty.websocket.servlet.WebSocketServletFactory$Loader.load(WebSocketServletFactory.java:54)
        at org.eclipse.jetty.websocket.servlet.WebSocketServlet.init(WebSocketServlet.java:140)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632)
        at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:486)
        at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:759)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.lang.Thread.run(Unknown Source)
Caused by:
java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.server.WebSocketServerFactory not found by org.eclipse.jetty.util [63]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1585)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.eclipse.jetty.websocket.servlet.WebSocketServletFactory$Loader.load(WebSocketServletFactory.java:48)
        at org.eclipse.jetty.websocket.servlet.WebSocketServlet.init(WebSocketServlet.java:140)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632)
        at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:486)
        at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:759)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.lang.Thread.run(Unknown Source)

```

**Comment by janbartel** [comment]
I think you're missing some setup.  Take a look at this example project here: https://github.com/jetty-project/embedded-jetty-websocket-examples/tree/9.4.x/native-jetty-websocket-example.  It shows you the code you need, plus the `pom.xml` should show you the list of jars/bundles you need on the classpath.

**Comment by greengooru** [comment]
Thank you @janbartel , but it needs to be an OSGi WebSocket. The example you share is for a standalone application. In a standalone application it surely works normally.

It is in OSGi where the exception occurs.

**Comment by janbartel** [comment]
@greengooru what I'm trying to tell you is that you have setup missing in your server setup class - it should be about the same as the standalone code in the example.

**Comment by joakime** [comment]
How can the ClassNotFoundException be triggered **from** `org.eclipse.jetty.websocket.servlet.WebSocketServletFactory` saying it cannot find `org.eclipse.jetty.websocket.servlet.WebSocketServletFactory` ?

It seems to indicate that `org.eclipse.jetty.util` is attempting to access `org.eclipse.jetty.websocket.servlet.WebSocketServletFactory`, but nothing in util even knows about websocket.

**Comment by greengooru** [comment]
Thanks @janbartel , @joakime 
The CkassNotFoundException is triggered because of this line:
`Class.forName("org.eclipse.jetty.websocket.server.WebSocketServerFactory"...);`
Line 51, in the `ServletFactory` of the WebSocket. We all know that using `Class.forName` in OSGi is not a good idea, nevertheless, if the library already has an explicit requirement to `org.eclipse.jetty.websocket.servlet.WebSocketServletFactory`, then why hide it behind a `Class.forName`? decoupling? 

Notice that the names are very similar, one is `Servlet` and the other is `Server`. So, is there any way we can remove the `Class.forName`? This is the problem.

**Comment by janbartel** [comment]
@greengooru there are many many places in jetty where we use dynamic class loading. We do some special work in our own osgi infrastructure to ensure that this style of classloading works (see eg https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-osgi/jetty-osgi-boot/src/main/java/org/eclipse/jetty/osgi/boot/internal/webapp/OSGiWebappClassLoader.java).  I think this dynamic loading here is because the jetty-websocket-servlet jar is intended to be included inside webapps, but it cannot depend on the jetty-websocket-server jar explicitly (because that shouldn't be included in a webapp).

**Comment by greengooru** [comment]
Yes, but this particular classloader does not work in OSGi. There are other sites who also report the same problem ([http://eriklievaart.com/web/osgiwebsockets.html](url)), so it has been there for some time.

The question is: Is there any workaround to this? In that website they propose one, but I am afraid that for newer versions, it does not work.

Or perhaps, you should create an OSGi version with an explicit dependency to the websocket-server.

**Comment by janbartel** [comment]
@greengooru you could certainly work around it by using TinyBundles, wrapping the existing `websocket-servlet` bundle and adding a manifest entry for the import of the `org.eclipse.jetty.websocket.server` classes. If you let me know that works, I'll look at adding a similar manifest-only entry to the `websocket-servlet` bundle.

**Comment by janbartel** [comment]
@greengooru also I should have said that you should try jetty-10, as websockets are implemented differently and no longer seems to contain the problematic classloading in the WebSocketServletFactory. See the doco at https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-server-websocket-jetty

**Comment by greengooru** [comment]
That is a curiosity, because the `websocket-servlet` already has a `DynamicImport-Package` to `websocket.server`.

Anyways, I will surely try jetty-10 and see how it works. I'll keep you posted on the results.

**Comment by andrewfg** [comment]
@greengooru did you solve this? .. and if so how?

**Comment by kumarman** [comment]
I was able to solve this by registering the servlet in a little different way.

```java
        server = new Server();
        ServerConnector connector = new ServerConnector(server);
        connector.setPort(jettyPort);
        
        // Create ServletContextHandler
        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");
        server.setHandler(context);
        server.setConnectors(new Connector[] {connector});

        //All servlet handlers
        context.addServlet(new ServletHolder(new MyNewServlet()), "/mypath/*");

        server.start();
        server.join();
```
Hopefully this would help.

**Comment by kumarman** [comment]
I was able to solve the issue by registering the servlet in little different way while initializing in OSGI. This workaround does not require any change in plugin MANIFEST.MF. 
JettVersion: 9.4.54.v20240208

```java
  Server server = new Server();
  ServerConnector connector = new ServerConnector(server);
  
  connector.setPort(jettyPort);
  
  // Create ServletContextHandler
  ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
  context.setContextPath("/");
  server.setHandler(context);

  server.setConnectors(new Connector[] {connector});
  
  //All servlet handlers
  context.addServlet(new ServletHolder(new MyNewServlet()), "/mypath/*");

  server.start();
  server.join();
```
