### ISSUE TITLE
New stacktrace from Java 11.0.15+ in org.eclipse.jetty.server.ConnectorTimeoutTest.lambda$testMaxIdleNothingSent

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#7946]
**Jetty version(s)**
9.4.x HEAD

**Java version/vendor** `(use: java -version)`
11.0.15

**OS type/version**
Linux / Ubuntu

**Description**

The CVE fix in the JVM seems to be triggering a new stacktrace on some tests.

Not sure if this means we have a code change we need to make (or not).

```
2022-05-02 10:57:26.165:INFO:oejs.Server:main: jetty-9.4.47-SNAPSHOT; built: 2022-05-02T15:49:43.336Z; git: 23c7b1846d91ff7bc664fbf1ea9a391b6a62da49; jvm 11.0.15+10
2022-05-02 10:57:26.166:INFO:oejus.SslContextFactory:main: x509=X509@58086bd9(jetty,h=[jetty.eclipse.org],a=[],w=[]) for Server@5cc1c780[provider=null,keyStore=file:///home/joakim/code/jetty/jetty.project-9.4.x/jetty-server/src/test/resources/keystore,trustStore=file:///home/joakim/code/jetty/jetty.project-9.4.x/jetty-server/src/test/resources/keystore]
2022-05-02 10:57:26.167:INFO:oejs.AbstractConnector:main: Started ServerConnector@68be702f{SSL, (ssl, http/1.1)}{0.0.0.0:44995}
2022-05-02 10:57:26.167:INFO:oejs.Server:main: Started @166822ms
2022-05-02 10:57:28.573:WARN:oejs.ConnectorTimeoutTest:junit-timeout-thread-6: 
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1696)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:921)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1012)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at org.eclipse.jetty.util.IO.copy(IO.java:229)
	at org.eclipse.jetty.util.IO.copy(IO.java:137)
	at org.eclipse.jetty.util.IO.toString(IO.java:340)
	at org.eclipse.jetty.util.IO.toString(IO.java:309)
	at org.eclipse.jetty.server.ConnectorTimeoutTest.lambda$testMaxIdleNothingSent$4(ConnectorTimeoutTest.java:546)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:102)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:138)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: 
java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:921)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1012)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at org.eclipse.jetty.util.IO.copy(IO.java:229)
	at org.eclipse.jetty.util.IO.copy(IO.java:137)
	at org.eclipse.jetty.util.IO.toString(IO.java:340)
	at org.eclipse.jetty.util.IO.toString(IO.java:309)
	at org.eclipse.jetty.server.ConnectorTimeoutTest.lambda$testMaxIdleNothingSent$4(ConnectorTimeoutTest.java:546)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:102)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:138)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-05-02 10:57:28.574:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@68be702f{SSL, (ssl, http/1.1)}{0.0.0.0:0}
```

**Comment by joakime** [comment]
Closing, hasn't repeated in a while.
