### ISSUE TITLE
Jetty-12 already completed exception in http2.tests.MaxConcurrentStreamsTest

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8033]
**Jetty version(s)**
jetty-12

**Description**
```
[INFO] Running org.eclipse.jetty.http2.tests.MaxConcurrentStreamsTest
2022-05-21 12:03:42.546:INFO :oejs.Server:main: jetty-12.0.0-SNAPSHOT; built: 2022-05-21T01:44:39.165Z; git: 73c88bce2313dbc8780e4b4afc05b9f91fb7b05f; jvm 17.0.2+8-Debian-1
2022-05-21 12:03:42.551:INFO :oejs.AbstractConnector:main: Started ServerConnector@31da6b2e{h2, (h2)}{0.0.0.0:40899}
2022-05-21 12:03:42.552:INFO :oejs.Server:main: Started oejs.Server@70242f38{STARTING}[12.0.0-SNAPSHOT,sto=0] @120124ms
2022-05-21 12:03:43.568:INFO :oejs.Server:main: Stopped oejs.Server@70242f38{STOPPING}[12.0.0-SNAPSHOT,sto=0]
2022-05-21 12:03:43.569:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@31da6b2e{h2, (h2)}{0.0.0.0:0}
2022-05-21 12:03:44.569:WARN :oejut.QueuedThreadPool:server-1919: Job failed
java.lang.IllegalStateException: already completed
        at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.lockedOnComplete(HttpChannelState.java:1402)
        at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.failed(HttpChannelState.java:1347)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sbordet** [comment]
Fixed by the work in #9684.
Re-enabled the test.
