### ISSUE TITLE
TLD not found

### ISSUE THREAD

**Issue by lukaszlenart** [eclipse/jetty.project#8050]
**Jetty version(s)**

9.4.46.v20220331

**Java version/vendor** `(use: java -version)`

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

**OS type/version**

macOS Monterey

**Description**

When running from a root folder of the project I will get the error below, once I enter `apps/showcase` and run `mvn verify` everything is ok. Any hint would be appreciated :)

```
2022-05-23 21:36:53.181:INFO:oejs.Server:main: jetty-9.4.46.v20220331; built: 2022-03-31T16:38:08.030Z; git: bc17a0369a11ecf40bb92c839b9ef0a8ac50ea18; jvm 1.8.0_292-b10
2022-05-23 21:36:53.326:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.m.p.JettyWebAppContext@3cb5cdba{Struts Showcase Application,/struts2-showcase,[file:///Users/lukaszlenart/Projects/Apache/struts/apps/showcase/src/main/webapp/],UNAVAILABLE}
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:86)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:74)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:399)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1412)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:397)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.maven.plugin.Starter.run(Starter.java:162)
	at org.eclipse.jetty.maven.plugin.Starter.main(Starter.java:243)
Caused by:
java.lang.IllegalArgumentException: TLD not found: file:///Users/lukaszlenart/Projects/Apache/struts/apps/showcase/core/target/classes/META-INF/struts-tags.tld
	at org.eclipse.jetty.quickstart.QuickStartDescriptorProcessor.visitContextParam(QuickStartDescriptorProcessor.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:86)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:74)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:399)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1412)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:397)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.maven.plugin.Starter.run(Starter.java:162)
	at org.eclipse.jetty.maven.plugin.Starter.main(Starter.java:243)
2022-05-23 21:36:53.357:INFO:oejs.AbstractConnector:main: Started ServerConnector@13c27452{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-05-23 21:36:53.360:INFO:oejs.Server:main: Started @463ms
```

**How to reproduce?**

Clone https://github.com/apache/struts/ and run `mvn verify`

**Comment by janbartel** [comment]
@lukaszlenart the _only_ jetty-maven-plugin goal that is designed for use with a binding in the `pom.xml` is `start`.  See the doco here: https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-maven-plugin and scroll down to `jetty:start`. You don't want to use any of the `***-run` goals with a binding, because they kick off a completely parallel build to build the project up to a certain point - you don't want to be doing that as part of a build sequence. All of the `***-run` goals are designed to be used at the command line only, as per the `mvn jetty:help` instructions:

>  Jetty maven plugins
> 
> This plugin has 10 goals:
> 
> jetty:deploy-war
>   This goal is used to run Jetty with a pre-assembled war.
>   
>   It accepts exactly the same options as the run-war goal. However, it doesn't
>   assume that the current artifact is a webapp and doesn't try to assemble it
>   into a war before its execution. So using it makes sense only when used in
>   conjunction with the war configuration parameter pointing to a pre-built WAR.
>   
>   This goal is useful e.g. for launching a web app in Jetty as a target for
>   unit-tested HTTP client components.
>   Deploy a pre-assembled war
> 
> jetty:effective-web-xml
>   This goal runs the jetty quickstart feature on an unassembled webapp in order
>   to generate a comprehensive web.xml that combines all information from
>   annotations, webdefault.xml and all web-fragment.xml files. By default, the
>   web.xml is generated to the console output only. Use the effectiveWebXml
>   parameter to provide a file name into which to save the output. See
>   https://www.eclipse.org/jetty/documentation for more information on this and
>   other jetty plugins. Runs jetty on the unassembled webapp to generate the
>   effective web.xml
> 
> jetty:help
>   Display help information on jetty-maven-plugin.
>   Call mvn jetty:help -Ddetail=true -Dgoal=<goal-name> to display parameter
>   details.
> 
> jetty:run
>   This goal is used in-situ on a Maven project without first requiring that the
>   project is assembled into a war, saving time during the development cycle.
>   The plugin forks a parallel lifecycle to ensure that the 'compile' phase has
>   been completed before invoking Jetty. This means that you do not need to
>   explicitly execute a 'mvn compile' first. It also means that a 'mvn clean
>   jetty:run' will ensure that a full fresh compile is done before invoking
>   Jetty.
>   
>   Once invoked, the plugin can be configured to run continuously, scanning for
>   changes in the project and automatically performing a hot redeploy when
>   necessary. This allows the developer to concentrate on coding changes to the
>   project using their IDE of choice and have those changes immediately and
>   transparently reflected in the running web container, eliminating development
>   time that is wasted on rebuilding, reassembling and redeploying.
>   
>   You may also specify the location of a jetty.xml file whose contents will be
>   applied before any plugin configuration. This can be used, for example, to
>   deploy a static webapp that is not part of your maven build.
>   
>   There is a reference guide to the configuration parameters for this plugin.
>   Runs jetty directly from a maven project
> 
> jetty:run-distro
>   This goal is used to deploy the unassembled webapp into a jetty distribution.
>   If the location of an existing unpacked distribution is not supplied as the
>   configuration param jettyHome, this goal will download and unpack the jetty
>   distro matching the version of this plugin before deploying the webapp. The
>   webapp will execute in the distro in a forked process. The stopKey, stopPort
>   configuration elements can be used to control the stopping of the forked
>   process. By default, this plugin will launch the forked jetty instance and
>   wait for it to complete (in which case it acts much like the jetty:run goal,
>   and you will need to Cntrl-C to stop). By setting the configuration element
>   waitForChild to false, the plugin will terminate after having forked the jetty
>   process. In this case you can use the jetty:stop goal to terminate the
>   process. This goal does NOT support the scanIntervalSeconds parameter: the
>   webapp will be deployed only once. See
>   https://www.eclipse.org/jetty/documentation for more information on this and
>   other jetty plugins. Runs unassembled webapp in a locally installed jetty
>   distro
> 
> jetty:run-exploded
>   This goal is used to assemble your webapp into an exploded war and
>   automatically deploy it to Jetty.
>   
>   Once invoked, the plugin runs continuously, and can be configured to scan for
>   changes in the pom.xml and to WEB-INF/web.xml, WEB-INF/classes or WEB-INF/lib
>   and hot redeploy when a change is detected.
>   
>   You may also specify the location of a jetty.xml file whose contents will be
>   applied before any plugin configuration. This can be used, for example, to
>   deploy a static webapp that is not part of your maven build.
> 
> jetty:run-forked
>   This goal is used to deploy your unassembled webapp into a forked JVM.
>   You need to define a jetty.xml file to configure connectors etc. You can use
>   the normal setters of o.e.j.webapp.WebAppContext on the webApp configuration
>   element for this plugin. You may also need context xml file for any
>   particularly complex webapp setup.
>   
>   Unlike the other jetty goals, this does NOT support the scanIntervalSeconds
>   parameter: the webapp will be deployed only once.
>   
>   The stopKey, stopPort configuration elements can be used to control the
>   stopping of the forked process. By default, this plugin will launch the forked
>   jetty instance and wait for it to complete (in which case it acts much like
>   the jetty:run goal, and you will need to Cntrl-C to stop). By setting the
>   configuration element waitForChild to false, the plugin will terminate after
>   having forked the jetty process. In this case you can use the jetty:stop goal
>   to terminate the process.
>   
>   See https://www.eclipse.org/jetty/documentation for more information on this
>   and other jetty plugins. Runs Jetty in forked JVM on an unassembled webapp
> 
> jetty:run-war
>   This goal is used to assemble your webapp into a war and automatically deploy
>   it to Jetty.
>   
>   Once invoked, the plugin runs continuously and can be configured to scan for
>   changes in the project and to the war file and automatically perform a hot
>   redeploy when necessary.
>   
>   You may also specify the location of a jetty.xml file whose contents will be
>   applied before any plugin configuration. This can be used, for example, to
>   deploy a static webapp that is not part of your maven build.
>   Runs jetty on a war file
> 
> jetty:start
>   This goal is similar to the jetty:run goal, EXCEPT that it is designed to be
>   bound to an execution inside your pom, rather than being run from the command
>   line.
>   
>   When using it, be careful to ensure that you bind it to a phase in which all
>   necessary generated files and classes for the webapp will have been created.
>   If you run it from the command line, then also ensure that all necessary
>   generated files and classes for the webapp already exist.
>   Runs jetty directly from a maven project from a binding to an execution in
>   your pom
> 
> jetty:stop
>   This goal stops a running instance of jetty. The stopPort and stopKey
>   parameters can be used to configure which jetty to stop. Stops jetty that is
>   configured with <stopKey> and <stopPort>.
>

**Comment by lukaszlenart** [comment]
Great, I was blindly following what we had previously, not it works as expected, thanks a lot!
