### ISSUE TITLE
NPE in WebInfConfiguration for webapp deploy in osgi

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#809]
Affects master only. Involves a bundle that contains 2 webapps. See TestJettyOSGiBootWebAppAsService.

java.lang.NullPointerException
	at org.eclipse.jetty.util.URIUtil.decodePath(URIUtil.java:320)
	at org.eclipse.jetty.webapp.WebInfConfiguration.getCanonicalNameForWebAppTmpDir(WebInfConfiguration.java:516)
	at org.eclipse.jetty.webapp.WebInfConfiguration.makeTempDirectory(WebInfConfiguration.java:239)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:204)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:59)
	at org.eclipse.jetty.webapp.Configurations.preConfigure(Configurations.java:432)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:511)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:536)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
	at org.eclipse.jetty.osgi.boot.ServiceWebAppProvider.serviceAdded(ServiceWebAppProvider.java:227)
	at org.eclipse.jetty.osgi.boot.ServiceWebAppProvider$WebAppTracker.addingService(ServiceWebAppProvider.java:86)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)

**Comment by gregw** [comment]
I could not reproduce this.  In fact the OSGi tests are passing for me.
