### ISSUE TITLE
NPE in jndi Resource

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#817]
Happens at least in jetty-9.2.x.

If you accidentally provide null as the name of the object to bind (eg you effectively call new Resource (null, obj-to-bind)):

Caused by: java.lang.NullPointerException
        at org.eclipse.jetty.plus.jndi.NamingEntry.save(NamingEntry.java:191)
        at org.eclipse.jetty.plus.jndi.Resource.<init>(Resource.java:39)

**Comment by janbartel** [comment]
Fixed in jetty-9.2.19 and above.
