### ISSUE TITLE
Jetty-12 can't serve resources from jar

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8285]
**Jetty version(s)**
Jetty-12

**Description**

After #8106 was merged, the ee9-demo-async-rest webapp is no longer able to server content from it's jar:
```
2022-07-12 12:34:17.703:WARN :oejen.HttpChannel:qtp1955915048-15: /ee9-demo-async-rest/asyncrest/red.png
java.lang.UnsupportedOperationException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$1.map(ZipFileSystem.java:1102)
        at org.eclipse.jetty.util.BufferUtil.toMappedBuffer(BufferUtil.java:1072)
        at org.eclipse.jetty.util.BufferUtil.toMappedBuffer(BufferUtil.java:1065)
        at org.eclipse.jetty.ee9.nested.CachedContentFactory.getMappedBuffer(CachedContentFactory.java:344)
        at org.eclipse.jetty.ee9.nested.CachedContentFactory$CachedHttpContent.getBuffer(CachedContentFactory.java:550)
        at org.eclipse.jetty.ee9.nested.HttpOutput.sendContent(HttpOutput.java:1307)
        at org.eclipse.jetty.ee9.nested.HttpOutput.sendContent(HttpOutput.java:1186)
        at org.eclipse.jetty.ee9.nested.ResourceService.sendData(ResourceService.java:744)
        at org.eclipse.jetty.ee9.nested.ResourceService.doGet(ResourceService.java:300)
        at org.eclipse.jetty.ee9.servlet.DefaultServlet.doGet(DefaultServlet.java:459)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at org.eclipse.jetty.ee9.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
        at org.eclipse.jetty.ee9.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.ee9.servlet.ServletHandler.doHandle(ServletHandler.java:530)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.handle(ScopedHandler.java:127)
        at org.eclipse.jetty.ee9.security.SecurityHandler.handle(SecurityHandler.java:578)
        at org.eclipse.jetty.ee9.nested.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.nextHandle(ScopedHandler.java:207)
        at org.eclipse.jetty.ee9.nested.SessionHandler.doHandle(SessionHandler.java:426)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.nextHandle(ScopedHandler.java:205)
        at org.eclipse.jetty.ee9.nested.ContextHandler.doHandle(ContextHandler.java:891)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.nextScope(ScopedHandler.java:164)
        at org.eclipse.jetty.ee9.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.nextScope(ScopedHandler.java:162)
        at org.eclipse.jetty.ee9.nested.SessionHandler.doScope(SessionHandler.java:420)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.nextScope(ScopedHandler.java:162)
        at org.eclipse.jetty.ee9.nested.ContextHandler.doScope(ContextHandler.java:831)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.handle(ScopedHandler.java:125)
        at org.eclipse.jetty.ee9.nested.ContextHandler.handle(ContextHandler.java:1606)
        at org.eclipse.jetty.ee9.nested.HttpChannel.lambda$handle$0(HttpChannel.java:472)
        at org.eclipse.jetty.ee9.nested.HttpChannel.dispatch(HttpChannel.java:708)
        at org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:470)
        at org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler.process(ContextHandler.java:2568)
        at org.eclipse.jetty.server.Request$WrapperProcessor.process(Request.java:664)
        at org.eclipse.jetty.server.handler.ContextRequest.run(ContextRequest.java:86)
        at org.eclipse.jetty.server.handler.ContextHandler$Context.run(ContextHandler.java:948)
        at org.eclipse.jetty.server.handler.ContextRequest.process(ContextRequest.java:68)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:659)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:440)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:327)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:911)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1055)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by gregw** [comment]
I've pushed a "fix", but I don't think I like it. 
We should consider API that allows us to query capability before attempting an operation like getting an Mapped buffer, so as to avoid unnecessary exceptions.
