### ISSUE TITLE
Logging and toString() should not throw any exception

### ISSUE THREAD

**Issue by Horcrux7** [eclipse/jetty.project#8293]
**Jetty version(s)**
10.0.11
**Java version/vendor** `(use: java -version)`
17
**OS type/version**

**Description**
Logging and toString() should not throw any exception. Especially if you give the objects to a logger.

```
[Webserver,DEBUG ,7/13 11:20:08,#00506] java.nio.channels.ClosedChannelException
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:160)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at java.base/sun.nio.ch.SocketChannelImpl.getLocalAddress(SocketChannelImpl.java:196)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.io.SelectableChannelEndPoint.getLocalSocketAddress(SelectableChannelEndPoint.java:135)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.io.AbstractEndPoint.toEndPointString(AbstractEndPoint.java:463)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.io.SelectableChannelEndPoint.toEndPointString(SelectableChannelEndPoint.java:302)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.io.AbstractEndPoint.toString(AbstractEndPoint.java:457)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3031)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2908)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at java.base/java.util.Formatter.format(Formatter.java:2673)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at java.base/java.util.Formatter.format(Formatter.java:2609)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at java.base/java.lang.String.format(String.java:2897)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.io.AbstractConnection.toString(AbstractConnection.java:304)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.helpers.MessageFormatter.objectArrayAppend(MessageFormatter.java:292)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:270)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:124)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.impl.CRLogger.getMessage(CRLogger.java:100)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.impl.CRLogger.toDebug(CRLogger.java:32)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.slf4j.impl.CRLogger.debug(CRLogger.java:121)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.io.AbstractConnection.onClose(AbstractConnection.java:228)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:554)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:329)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:1113)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
[Webserver,TRACE ,7/13 11:20:08,#00506] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**How to reproduce?**
Enable the debug logging with an slf4j logger.

**Comment by joakime** [comment]
You have TRACE logging enabled.
That's going to be more noisy.

DEBUG level logging doesn't do that.

**Comment by Horcrux7** [comment]
Ok, I had the wrong stacktrace. It was the exception from the log. I have correct this. But for both stacktraces it is calling debug() and not trace().

```
    public void onClose(Throwable cause)
    {
        if (LOG.isDebugEnabled())
        {
            if (cause == null)
                LOG.debug("onClose {}", this);
            else
                LOG.debug("onClose {}", this, cause);
        }

```

PS: Also, if this would only occur on TRACE. This is no cause to fire exceptions through the logging.

**Comment by joakime** [comment]
We definitely want to log at DEBUG in `AbstractConnection.onClose(Throwable)`

https://github.com/eclipse/jetty.project/blob/jetty-10.0.11/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java#L223-L236

https://github.com/eclipse/jetty.project/blob/d988aa016e0bb2de6fba84c1659049c72eae3e32/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java#L223-L236

The resulting `ClosedChannelException` occurs in `SelectableChannelEndPoint.getLocalSocketAddress()` (as seen in your stacktrace)

https://github.com/eclipse/jetty.project/blob/jetty-10.0.11/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java#L129-L143

And it logs at TRACE level.

https://github.com/eclipse/jetty.project/blob/d988aa016e0bb2de6fba84c1659049c72eae3e32/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java#L129-L143

Which your output shows at TRACE level.

**Comment by Horcrux7** [comment]
Now I understand what you means. I can handle this. You make a great job with this project.

I close this issue also if I think on tracing it should not produce/show exception from the logging self.
