### ISSUE TITLE
Test Failure: HttpClientTransportOverHTTP2Test.testLastStreamId()

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#836]
Intermittent failures, but seen a few times already, so needs to be fixed.

```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertNotNull(Assert.java:712)
    at org.junit.Assert.assertNotNull(Assert.java:722)
    at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2Test.testLastStreamId(HttpClientTransportOverHTTP2Test.java:274)
```

**Comment by sbordet** [comment]
Seen failing again: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-9.4.x/474/tests/

**Comment by joakime** [comment]
Keep in mind that build 474 didn't have the double release buffer fix from build 475

**Comment by joakime** [comment]
Build 474 failure text.

```
Error
expected:<3> but was:<1>

Stacktrace
java.lang.AssertionError: expected:<3> but was:<1>
at org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2Test.testLastStreamId(HttpClientTransportOverHTTP2Test.java:306)

Standard Error
Running org.eclipse.jetty.http2.client.http.HttpClientTransportOverHTTP2Test.testLastStreamId()
2018-08-01 17:30:47.961:INFO:oejs.Server:main: jetty-9.4.12-SNAPSHOT; built: 2018-08-01T17:15:48.885Z; git: 34188fdaa81f231a26dfac0b96c3f2e6a73886fc; jvm 1.8.0_181-b13
2018-08-01 17:30:47.975:INFO:oejs.AbstractConnector:main: Started ServerConnector@27f0ad19{h2,[h2]}{0.0.0.0:41339}
2018-08-01 17:30:47.975:INFO:oejs.Server:main: Started @22830ms
2018-08-01 17:30:48.050:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@27f0ad19{h2,[h2]}{0.0.0.0:0}
```

**Comment by sbordet** [comment]
Have not seen this failing lately, closing.
