### ISSUE TITLE
Jetty client test failure

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#84]
Frequently when running full builds in 9.3.x I get:
```
Running org.eclipse.jetty.http.client.HttpChannelAssociationTest.testIdleTimeoutJustBeforeAssociation[transport: FCGI]()
2016-02-16 16:32:35.291:INFO:oejs.Server:main: jetty-9.3.8-SNAPSHOT
2016-02-16 16:32:35.291:INFO:oejs.ServerConnector:main: Started 
ServerConnector@1f010bf0{fcgi/1.0,[fcgi/1.0]}{0.0.0.0:33332}
2016-02-16 16:32:35.291:INFO:oejs.Server:main: Started @51615ms
2016-02-16 16:32:35.292:INFO:oejus.SslContextFactory:main: x509=X509@1921ad94(mykey,h=[],w=[]) for SslContextFactory@ee86bcb(file:///home/gregw/src/jetty-9.3.x/tests/test-http-client-transport/src/test/resources/keystore.jks,file:///home/gregw/src/jetty-9.3.x/tests/test-http-client-transport/src/test/resources/truststore.jks)
2016-02-16 16:32:37.296:INFO:oejs.ServerConnector:main: Stopped ServerConnector@1f010bf0{fcgi/1.0,[fcgi/1.0]}{0.0.0.0:0}
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.134 sec <<< FAILURE! - in org.eclipse.jetty.http.client.HttpChannelAssociationTest
testIdleTimeoutJustBeforeAssociation[transport: H2](org.eclipse.jetty.http.client.HttpChannelAssociationTest)  Time elapsed: 5.009 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.eclipse.jetty.http.client.HttpChannelAssociationTest.testIdleTimeoutJustBeforeAssociation(HttpChannelAssociationTest.java:124)
```

**Comment by sbordet** [comment]
@gregw I put the test in a loop, there is no way it fails for me.

Can you please enable DEBUG logging for `org.eclipse.jetty.client` and see if it fails, and report the logs here ?

**Comment by gregw** [comment]
Now it is not failing for me.  But I have seen it a few times over the last few days.
