### ISSUE TITLE
Not cleaning cached beans: no such field javax.el.BeanELResolver.properties

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8447]
**Jetty version(s)**
12

**Description**
```
2022-08-11 14:01:49.370:INFO :oejs.Server:JettyShutdownThread: Stopped oejs.Server@758705fa{STOPPING}[12.0.0-SNAPSHOT,sto=5000]
2022-08-11 14:01:49.370:INFO :oejs.Server:JettyShutdownThread: Shutdown oejs.Server@758705fa{STOPPING}[12.0.0-SNAPSHOT,sto=5000]
2022-08-11 14:01:50.393:INFO :oejs.AbstractConnector:JettyShutdownThread: Stopped ServerConnector@4273d740{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443}
2022-08-11 14:01:50.395:INFO :oejs.AbstractConnector:JettyShutdownThread: Stopped ServerConnector@6cfd9a54{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-08-11 14:01:50.420:INFO :oejshC.ee10_demo_spec:JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties
2022-08-11 14:01:50.424:INFO :oejes.ServletContextHandler:JettyShutdownThread: Stopped oejew.WebAppContext@60fa3495{EE10 Demo Spec WebApp,/ee10-test-spec,b=null,a=AVAILABLE,h=oejes.SessionHandler@1894593a{STOPPED}}{/home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/ee10-demo-spec.war}
2022-08-11 14:01:50.426:INFO :oejshC.ee10_demo_async_rest:JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties
2022-08-11 14:01:50.428:INFO :oejes.ServletContextHandler:JettyShutdownThread: Stopped oejew.WebAppContext@60d8c0dc{EE10 Demo Async REST WebApp,/ee10-demo-async-rest,b=null,a=AVAILABLE,h=oejes.SessionHandler@ad3324b{STOPPED}}{/home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/ee10-demo-async-rest.war}
2022-08-11 14:01:50.429:INFO :oejshC.ee10_demo_jaas:JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties
2022-08-11 14:01:50.430:INFO :oejes.ServletContextHandler:JettyShutdownThread: Stopped oejew.WebAppContext@51df223b{EE10 Demo JAAS WebApp,/ee10-test-jaas,b=null,a=AVAILABLE,h=oejes.SessionHandler@43f0c2d1{STOPPED}}{/home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/ee10-demo-jaas.war}
2022-08-11 14:01:50.432:INFO :oejshC.ee10_demo_jetty:JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties
2022-08-11 14:01:50.433:INFO :oejes.ServletContextHandler:JettyShutdownThread: Stopped oejew.WebAppContext@5cc126dc{EE10 Demo Jetty WebApp,/ee10-test,b=null,a=AVAILABLE,h=GzipHandler@387bf2d9{STOPPED,min=2048,inflate=-1}}{/home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/ee10-demo-jetty.war}
2022-08-11 14:01:50.433:INFO :oejshC.ee10_demo_jsp:JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties
2022-08-11 14:01:50.434:INFO :oejes.ServletContextHandler:JettyShutdownThread: Stopped oejew.WebAppContext@1991f767{EE10 Demo JSP WebApp,/ee10-demo-jsp,b=null,a=AVAILABLE,h=oejes.SessionHandler@53ac845a{STOPPED}}{/home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/ee10-demo-jsp.war}
2022-08-11 14:01:50.447:INFO :oejshC.ee10_demo_proxy:JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties
2022-08-11 14:01:50.448:INFO :oejes.ServletContextHandler:JettyShutdownThread: Stopped oejew.WebAppContext@46f699d5{EE10 Demo Proxy WebApp,/proxy,b=null,a=AVAILABLE,h=oejes.SessionHandler@7923f5b3{STOPPED}}{/home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/ee10-demo-proxy.war}
2022-08-11 14:01:50.448:INFO :oejshC.root:JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties
2022-08-11 14:01:50.449:INFO :oejes.ServletContextHandler:JettyShutdownThread: Stopped oejew.WebAppContext@74e47444{root,/,b=file:///home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/root/,a=AVAILABLE,h=oejes.SessionHandler@75f2099{STOPPED}}{/home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/root}
2022-08-11 14:01:50.449:INFO :oejshC.ee10_demo_jndi:JettyShutdownThread: Not cleaning cached beans: no such field javax.el.BeanELResolver.properties
2022-08-11 14:01:50.450:INFO :oejes.ServletContextHandler:JettyShutdownThread: Stopped oejew.WebAppContext@5536379e{EE10 Demo JNDI WebApp,/test-jndi,b=null,a=AVAILABLE,h=oejes.SessionHandler@2c42b421{STOPPED}}{/home/gregwilkins/src/jetty-12/jetty-home/target/jetty-home/base/webapps/ee10-demo-jndi.war}
```
**How to reproduce?**

Run ee10 demos, ctl-C server

**Comment by janbartel** [comment]
I think we can delete the ELCleaner from ee10: the BeanELResolver no longer has a static map of properties, so there shouldn't be a leak. Might not even be needed in ee9, but as ee8 derives from ee9 - where it will be needed - we can keep it in ee9.

**Comment by olamy** [comment]
Agree as the `org.eclipse.jetty.ee10.jstl.JstlTest` 

generates this error
```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at org.eclipse.jetty.ee10.servlet.listener.ELContextCleaner.purgeEntries(ELContextCleaner.java:92)
```

**Comment by janbartel** [comment]
Removed ELContextCleaner from ee10 via commit https://github.com/eclipse/jetty.project/commit/52f1c91cca028d671c9441c106b5ffae65593c84
