### ISSUE TITLE
[jetty-proxy] NullPointerException at org.eclipse.jetty.proxy.AsyncMiddleManServlet.onContinue(AsyncMiddleManServlet.java:177)

### ISSUE THREAD

**Issue by garydgregory** [eclipse/jetty.project#8538]
**Jetty version(s)**
9.4.48.v20220622

**Java version/vendor** `(use: java -version)`
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.342-b07, mixed mode)

**OS type/version**
Microsoft Windows [Version 10.0.19042.1889]

**Description**
```
java.lang.NullPointerException
	at org.eclipse.jetty.proxy.AsyncMiddleManServlet.onContinue(AsyncMiddleManServlet.java:177)
	at org.eclipse.jetty.proxy.AbstractProxyServlet$ProxyContinueProtocolHandler.onContinue(AbstractProxyServlet.java:844)
	at org.eclipse.jetty.client.ContinueProtocolHandler$ContinueListener.onSuccess(ContinueProtocolHandler.java:94)
	at org.eclipse.jetty.client.ResponseNotifier.notifySuccess(ResponseNotifier.java:176)
	at org.eclipse.jetty.client.ResponseNotifier.notifySuccess(ResponseNotifier.java:168)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:415)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:374)
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:597)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1668)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:208)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:148)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:80)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
```

**How to reproduce?**

Configure Jetty with a `AsyncMiddleManServlet` and send a `POST` _without_ a body.

**Comment by joakime** [comment]
Was your `POST` one with the `Expect: 100-continue` header or not?

A quick test of Jetty 10.0.11 (the currently supported minimum version of Jetty) using curl with a no-body POST (`curl -X POST http://example.com`, which does not produce an `Expect: 100-continue`) shows that it works.
