### ISSUE TITLE
upgrade jetty version from 9.4.48 to 11.0.11 got some errors

### ISSUE THREAD

**Issue by xinguangduan** [eclipse/jetty.project#8633]
**Jetty version**
11.0.11
**Java version**
Azul Zulu 11.0.14
**Question**
I used jetty as http2 server，when I upgrade jetty version from 9.4.48 to 11.0.11，client access the http2 server got some errors, could you please help me explain what might have caused it?

2022-09-30 19:55:41,705 [qtp785306763-26] DEBUG o.e.j.h.HTTP2Session:547 - Session abort input_shutdown for HTTP2ServerSession@5792b05c{local:/192.168.1.3:8443,remote:/192.168.1.9:52293,sendWindow=65535,recvWindow=65535,state=[streams=0,CLOSING,goAwayRecv=null,goAwaySent=null,failure=java.nio.channels.ClosedChannelException]}
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.http2.HTTP2Session$StreamsState.onShutdown(HTTP2Session.java:1819) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Session.onShutdown(HTTP2Session.java:992) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:313) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:446) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:239) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:155) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:378) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[jetty-util-11.0.11.jar:11.0.11]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-09-30 19:55:41,712 [qtp785306763-26] DEBUG o.e.j.h.HTTP2Connection:225 - Processing session failure on HTTP2ServerSession@5792b05c{local:/192.168.1.3:8443,remote:/192.168.1.9:52293,sendWindow=65535,recvWindow=65535,state=[streams=0,CLOSING,goAwayRecv=null,goAwaySent=null,failure=java.nio.channels.ClosedChannelException]}
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.http2.HTTP2Session$StreamsState.onShutdown(HTTP2Session.java:1819) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Session.onShutdown(HTTP2Session.java:992) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:313) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:446) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:239) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:155) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:378) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[jetty-util-11.0.11.jar:11.0.11]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-09-30 19:55:41,712 [qtp785306763-26] DEBUG o.e.j.h.HTTP2Session:2089 - Terminating HTTP2ServerSession@5792b05c{local:/192.168.1.3:8443,remote:/192.168.1.9:52293,sendWindow=65535,recvWindow=65535,state=[streams=0,CLOSING,goAwayRecv=null,goAwaySent=null,failure=java.nio.channels.ClosedChannelException]}
2022-09-30 19:55:41,712 [qtp785306763-26] DEBUG o.e.j.h.HTTP2Flusher:389 - Terminating HTTP2Flusher@4372c0f3[IDLE][window_queue=0,frame_queue=0,processed/pending=0/0]
2022-09-30 19:55:41,713 [qtp785306763-26] DEBUG o.e.j.h.HTTP2Flusher:161 - Flushing HTTP2ServerSession@5792b05c{local:/192.168.1.3:8443,remote:/192.168.1.9:52293,sendWindow=65535,recvWindow=65535,state=[streams=0,CLOSING,goAwayRecv=null,goAwaySent=null,failure=java.nio.channels.ClosedChannelException]}
2022-09-30 19:55:41,713 [qtp785306763-26] DEBUG o.e.j.h.HTTP2Flusher:360 - Closing, entries processed/pending/queued=0/0/0
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.http2.HTTP2Session$StreamsState.onShutdown(HTTP2Session.java:1819) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Session.onShutdown(HTTP2Session.java:992) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:313) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:446) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:239) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:155) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:378) ~[http2-common-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[jetty-util-11.0.11.jar:11.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[jetty-util-11.0.11.jar:11.0.11]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

**Comment by joakime** [comment]
These are DEBUG messages, not WARN or ERROR or FATAL.
These are normal/common events that occur in various situations.

**Comment by janbartel** [comment]
Seems your question has been answered. If not, please reopen with further information.
