### ISSUE TITLE
HttpRequest.send() returns "Address already in use: no further information"

### ISSUE THREAD

**Issue by cowwoc** [eclipse/jetty.project#8681]
**Jetty version(s)**
11.0.12

**Java version/vendor** `(use: java -version)`
```
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment (build 19+36-2238)
OpenJDK 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
```

**OS type/version**
Microsoft Windows [Version 10.0.19044.2006]

**Description**
I have an application that sends out thousands of requests concurrently. Each request uses a SOCKS proxy that runs over an SSH tunnel.

Every once in a while I get the following unexpected exceptions:

```
java.util.concurrent.ExecutionException: java.net.BindException: Address already in use: no further information
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:113)
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:96)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:772)
        at [...application code...]
Caused by: java.net.BindException: Address already in use: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:340)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:344)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:675)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:533)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:455)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:248)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
	... 1 common frames omitted
```

I am not expecting to get address bind errors from an outgoing HTTP request. Is this indicative of a bug or some sort of user error? I am invoking the synchronous version of `HttpRequest.send()`.

**Comment by sbordet** [comment]
You are running out of local ephemeral ports.
You are on Windows, so no idea how to tune that, but on Linux would be: 

```
$ sysctl net.ipv4.ip_local_port_range
```

**Comment by cowwoc** [comment]
Wow. I would have never thought of that :) Thanks!
