### ISSUE TITLE
MethodType comparison with == instead of equals

### ISSUE THREAD

**Issue by mhalbritter** [eclipse/jetty.project#8710]
**Jetty version(s)**

11.0.12

**Java version/vendor** `(use: java -version)`

```
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
```

**OS type/version**

```
Linux fedora 5.19.14-100.fc35.aarch64 #1 SMP PREEMPT_DYNAMIC Wed Oct 5 21:13:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Description**

In some places in the codebase, `MethodType`s are compared using `==` or `!=` and not with `equals`. This works on the JVM, but fails for example in a native image built with GraalVM.

See for example:

* [ByteBufferMessageSink](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteBufferMessageSink.java#L41)
* [ByteArrayMessageSink](https://github.com/eclipse/jetty.project/blob/059c01e14fcc0dcd4ae06b77b35256f1a1c63c8a/jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java#L40)

When using websockets in a GraalVM native image, I get error messages like this:

```
org.eclipse.jetty.websocket.core.exception.CloseException: org.eclipse.jetty.websocket.core.exception.WebSocketException: StandardWebSocketHandlerAdapter OPEN method error: org.eclipse.jetty.websocket.core.exception.InvalidSignatureException: Invalid MethodHandle void(java.nio.ByteBuffer) - expected void(java.nio.ByteBuffer)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$onOpen$5(WebSocketCoreSession.java:405) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.util.Callback$3.failed(Callback.java:161) ~[na:na]
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onOpen(JakartaWebSocketFrameHandler.java:186) ~[na:na]
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$onOpen$6(WebSocketCoreSession.java:411) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.handle(WebSocketCoreSession.java:118) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onOpen(WebSocketCoreSession.java:411) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onOpen(WebSocketConnection.java:542) ~[na:na]
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:451) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.core.client.CoreClientUpgradeRequest.upgrade(CoreClientUpgradeRequest.java:454) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.core.client.internal.HttpUpgraderOverHTTP.upgrade(HttpUpgraderOverHTTP.java:92) ~[na:na]
	at org.eclipse.jetty.client.UpgradeProtocolHandler$1.onComplete(UpgradeProtocolHandler.java:81) ~[na:na]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:213) ~[na:na]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:205) ~[na:na]
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:477) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:457) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:420) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:385) ~[na:na]
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:585) ~[na:na]
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1653) ~[na:na]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1536) ~[na:na]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:221) ~[na:na]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:160) ~[na:na]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:91) ~[na:na]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:91) ~[na:na]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194) ~[na:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[na:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[na:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933) ~[na:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077) ~[na:na]
	at java.lang.Thread.run(Thread.java:833) ~[websocket-jetty:na]
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705) ~[websocket-jetty:na]
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
Caused by: org.eclipse.jetty.websocket.core.exception.WebSocketException: StandardWebSocketHandlerAdapter OPEN method error: org.eclipse.jetty.websocket.core.exception.InvalidSignatureException: Invalid MethodHandle void(java.nio.ByteBuffer) - expected void(java.nio.ByteBuffer)
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onOpen(JakartaWebSocketFrameHandler.java:185) ~[na:na]
	... 30 common frames omitted
Caused by: java.lang.RuntimeException: org.eclipse.jetty.websocket.core.exception.InvalidSignatureException: Invalid MethodHandle void(java.nio.ByteBuffer) - expected void(java.nio.ByteBuffer)
	at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.<init>(AbstractDecodedMessageSink.java:49) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink$Basic.<init>(AbstractDecodedMessageSink.java:89) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.<init>(DecodedBinaryMessageSink.java:39) ~[websocket-jetty:11.0.12]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[websocket-jetty:na]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[websocket-jetty:na]
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:207) ~[na:na]
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76) ~[websocket-jetty:na]
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0) ~[websocket-jetty:na]
	at java.lang.invoke.LambdaForm$MH/0x00000001018c1400.invoke_MT(LambdaForm$MH) ~[na:na]
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandlerFactory.createMessageSink(JakartaWebSocketFrameHandlerFactory.java:195) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.registerMessageHandler(JakartaWebSocketFrameHandler.java:495) ~[na:na]
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.addMessageHandler(JakartaWebSocketFrameHandler.java:455) ~[na:na]
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketSession.addMessageHandler(JakartaWebSocketSession.java:130) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketSession.addMessageHandler(JakartaWebSocketSession.java:150) ~[websocket-jetty:11.0.12]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onOpen(StandardWebSocketHandlerAdapter.java:87) ~[na:na]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[websocket-jetty:na]
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:221) ~[na:na]
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76) ~[websocket-jetty:na]
	at com.oracle.svm.methodhandles.MethodHandleIntrinsicImpl.execute(MethodHandleIntrinsicImpl.java:177) ~[na:na]
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:142) ~[na:na]
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76) ~[websocket-jetty:na]
	at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:77) ~[na:na]
	at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:964) ~[websocket-jetty:na]
	at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:941) ~[websocket-jetty:na]
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:82) ~[websocket-jetty:na]
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0) ~[websocket-jetty:na]
	at java.lang.invoke.LambdaForm$MH/0x00000001018c1000.invoke_MT(LambdaForm$MH) ~[na:na]
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onOpen(JakartaWebSocketFrameHandler.java:175) ~[na:na]
	... 30 common frames omitted
Caused by: org.eclipse.jetty.websocket.core.exception.InvalidSignatureException: Invalid MethodHandle void(java.nio.ByteBuffer) - expected void(java.nio.ByteBuffer)
	at org.eclipse.jetty.websocket.core.internal.messages.ByteBufferMessageSink.<init>(ByteBufferMessageSink.java:43) ~[na:na]
	at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.newMessageSink(DecodedBinaryMessageSink.java:48) ~[websocket-jetty:11.0.12]
	at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.<init>(AbstractDecodedMessageSink.java:44) ~[websocket-jetty:11.0.12]
	... 57 common frames omitted
```

Changing the reference equality to a call to `equals` should fix that issue and should have no negative side effects.

See https://github.com/oracle/graal/issues/5209

**Comment by joakime** [comment]
Looks like an acknowledged bug in graalvm

https://github.com/oracle/graal/issues/5209#issuecomment-1277327852

**Comment by mhalbritter** [comment]
I wonder if the behavior that you always get the same `MethodType` back is specified or is an implementation detail of the JVM. If it's not specified, using `==` seems risky.

**Comment by joakime** [comment]
The MethodType has to be predictable like this.

Example:

The MethodType tests in the openjdk codebase ...

* https://github.com/openjdk/jdk/blob/master/test/jdk/java/lang/invoke/MethodTypeTest.java

Which uses Junit5 and it's `assertSame(o1, o2)` api.
Which is a comparison with `==` (not `Object.equals(o)`, which would be the `assertEquals(o1, o2)` junit api)

See: https://github.com/junit-team/junit5/blob/main/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertSame.java#L34

**Comment by mhalbritter** [comment]
I see, thanks for the explanation!
