### ISSUE TITLE
override-web.xml configured inside webapp's jetty-web.xml is ignored

### ISSUE THREAD

**Issue by echatman** [eclipse/jetty.project#872]
My webapp's WEB-INF/jetty-web.xml:
```xml
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
	<Set name="overrideDescriptor">/path/to/override-web.xml</Set>
</Configure>
```

This gets ignored by jetty. I attached a debugger and discovered that it seems to be an order of operations issue.

1. [WebXmlConfiguration.preConfigure()](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebXmlConfiguration.java#L66) tries to load [WebAppContent's overrideDescriptors list](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L638) (currently empty) into into [MetaData.java](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/MetaData.java#L212) (MetaData.addOverride [called here](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebXmlConfiguration.java#L73)). This is before jetty-web.xml has been processed.
2. `WebAppContext.configure()` processes jetty-web.xml and populates [WebAppContext. _overrideDescriptors](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L1032) (too late)
3. later in `WebAppContext.startContext()`, [MetaData.resolve()](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/MetaData.java#L404) processes it's (empty) overrideWebs list. At this point, the WebAppContext has override-web.xml in it's list, but MetaData does not, so it never gets processed.

Stack traces:
1.

    "main@1" prio=5 tid=0x1 nid=NA runnable
      java.lang.Thread.State: RUNNABLE
    	  at org.eclipse.jetty.webapp.WebXmlConfiguration.preConfigure(WebXmlConfiguration.java:66)
    	  at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:480)
    	  at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:516)
    	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

2.

    "main@1" prio=5 tid=0x1 nid=NA runnable
      java.lang.Thread.State: RUNNABLE
    	  at org.eclipse.jetty.webapp.WebAppContext.setOverrideDescriptor(WebAppContext.java:1010)
    	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
    	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	  at java.lang.reflect.Method.invoke(Method.java:498)
    	  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:488)
    	  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:411)
    	  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:300)
    	  at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:245)
    	  at org.eclipse.jetty.webapp.JettyWebXmlConfiguration.configure(JettyWebXmlConfiguration.java:102)
    	  at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:491)
    	  at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1336)
    	  at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
    	  at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
    	  at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
    	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

3.

    "main@1" prio=5 tid=0x1 nid=NA runnable
      java.lang.Thread.State: RUNNABLE
    	  at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:371)
    	  at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1339)
    	  at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
    	  at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
    	  at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
    	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

**Comment by joakime** [comment]
That is correct.

You cannot configure many of the components of the WebAppContext in the `jetty-web.xml`

For the `overrideDescriptor` you'll need to use a XML deployable like `${jetty.base}/webapps/myapp.xml`

**Comment by echatman** [comment]
Is that documented anywhere?

**Comment by echatman** [comment]
This is a documentation issue, then, I guess. The documentation clearly states that you should be able to do this:

> You can specify the override-web.xml to use for an individual web application, in that webapp’s jetty-web.xml.

https://www.eclipse.org/jetty/documentation/current/override-web-xml.html

**Comment by echatman** [comment]
https://github.com/eclipse/jetty.project/blob/master/jetty-documentation/src/main/asciidoc/reference/jetty-xml/override-web-xml.adoc

**Comment by joakime** [comment]
@WalkerWatch lets makes sure the documentation is corrected about this.

I tested this to see when it was supported (if it ever was).

 - Created a new `overrideWeb.xml`, added a new `DumpServlet` (url-pattern `/dump`) entry to it.
 - Created a new (servlet 2.5) webapp with a `jetty-web.xml` that had a hardcoded (for my system) reference to this new `overrideWeb.xml` via the `overrideDescriptor` (webapp also has `DumpServlet` in its `WEB-INF/classes`)
 - Deployed to Jetty 9.4.0-SNAPSHOT, and then on increasingly older versions of Jetty until it has the `/dump` servlet present.

I got back to Jetty 7.6.14.v20131031 and the `/dump` servlet still didn't show up.

But if I just simply changed to using a XML deployable, then the `/dump` servlet shows up.

We should check with @janbartel to see what the intention is here.

**Comment by janbartel** [comment]
@joakime is correct and this is an incorrect usage, and thus the documentation needs to be corrected. The purpose of jetty-web.xml is to run last just before the webapp starts and to allow a final override of all foregoing configuration. Thus, by the time that jetty-web.xml executes any context xml file, jetty-env.xml, web.xml, web-fragment.xml and override-web.xml files have already been interpreted.
