### ISSUE TITLE
Error in going to tutorials, C/C++ developments, in Eclipse IDE for C/C++ Developers

### ISSUE THREAD

**Issue by BenBorre** [eclipse/jetty.project#8737]
Getting this error :
!SESSION 2022-10-19 06:00:57.612 -----------------------------------------------
eclipse.buildId=4.25.0.I20220831-1800
java.version=17.0.4.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_BE
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.cpp.product

!ENTRY org.eclipse.egit.ui 2 0 2022-10-19 06:01:38.339
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\acer'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.ui.ide 4 4 2022-10-19 06:06:57.151
!MESSAGE Not properly disposed SWT resource
!STACK 0
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:668)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:275)
	at org.eclipse.jface.resource.DeferredImageDescriptor.createImage(DeferredImageDescriptor.java:80)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:290)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:268)
	at org.eclipse.launchbar.ui.internal.dialogs.NewLaunchConfigTypePage2.createModeItem(NewLaunchConfigTypePage2.java:137)
	at org.eclipse.launchbar.ui.internal.dialogs.NewLaunchConfigTypePage2.populateMode(NewLaunchConfigTypePage2.java:98)
	at org.eclipse.launchbar.ui.internal.dialogs.NewLaunchConfigTypePage2.createControl(NewLaunchConfigTypePage2.java:88)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:744)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:636)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.launchbar.ui.controls.internal.ConfigSelector$3.mouseUp(ConfigSelector.java:182)

Remark : Projects->Properties is greyed out, so that I cannot access to the environment variables

**Comment by olamy** [comment]
this issue tracker is used only for issues related to the Jetty project.
