### ISSUE TITLE
WebSocket thread locking in blockingWrite

### ISSUE THREAD

**Issue by ryryguy** [eclipse/jetty.project#8766]
**Jetty version(s)**
9.4.49.v20220914

**Java version/vendor** 
openjdk version "17.0.4.1" 
OpenJDK Runtime Environment Temurin-17.0.4.1

**OS type/version**
Ubuntu 20.04

**Description**
We're consistently getting locked threads on our production services running in AWS ECS.

There are several similar looking issues which have been resolved, most recently #2061 but we are on a version well past the versions where they were marked fixed.

One thing about our case is that we are making the write on an inbound message thread. The thread is handling a heartbeat message which we immediately echo back to the client. It's not obvious that this would be a problem, but we are making a change to hand off the response writing task to another thread pool to see if that helps. (We haven't deployed that yet so we don't know if it actually has any effect)

Thread dump showing the locked thread:
```
"clientInboundChannel-31" - Thread t@1535
   java.lang.Thread.State: WAITING
	at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
	- parking to wait for <7d12de23> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
	at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
	at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:241)
	at org.eclipse.jetty.websocket.common.BlockingWriteCallback$WriteBlocker.block(BlockingWriteCallback.java:89)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.blockingWrite(WebSocketRemoteEndpoint.java:110)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendBytes(WebSocketRemoteEndpoint.java:260)
	at org.springframework.web.socket.adapter.jetty.JettyWebSocketSession.sendBinaryMessage(JettyWebSocketSession.java:219)
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:109)
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.tryFlushMessageBuffer(ConcurrentWebSocketSessionDecorator.java:190)
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.sendMessage(ConcurrentWebSocketSessionDecorator.java:163)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.sendToClient(StompSubProtocolHandler.java:493)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageToClient(StompSubProtocolHandler.java:483)
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:366)
<application code redacted>
	at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
	at java.base@17.0.4.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base@17.0.4.1/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:569)
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511)
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:524)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:458)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
	at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)

```

**How to reproduce?**
We have not found any reliable repro steps. We have not been able to reproduce the problem in a testing environment, only in production. In production, we're running cluster of 20 services in several regions. We've never observed this in the least loaded region, while on the most heavily loaded region, 2-3 of the services fall victim to this per day. (We can tell because the blocked thread has a lock on a resource that we use to write messages to clients. This service is responsible for forwarding messages from other services to clients, and eventually all the threads in a queue intake thread pool also get blocked waiting for a lock on that resource that is being held by this thread. At that point, no more messages go out to any clients from that service, and we have to kill the service.)

**Comment by lachlan-roberts** [comment]
Note `9.4.x` version is community EOL (see https://github.com/eclipse/jetty.project/issues/7958)

So best step is to upgrade to Jetty to latest  `10.0.x`/`11.0.x` version and it is likely you would not experience this issue. https://www.eclipse.org/jetty/documentation/jetty-10/programming-guide/index.html#pg-migration-94-to-10-websocket

But previous issues with this were resulted from `permessage-deflate` extension, so if you cannot upgrade right now you could try disabling `permessage-deflate` and report back whether you still experience the issue.

**Comment by ryryguy** [comment]
Thanks for the information. We do plan to upgrade to version 10 soon, we're waiting for the Spring updates to be officially released next month so that we can do them all at once.

The change we made to decouple the inbound thread from the message write operation has been in production for about 36 hours now, and we haven't seen the problem occur since then. It's hard to be sure that it has 100% fixed the problem but it seems that at the least it has made it happen less frequently. If we still have problems before we're able to upgrade to v 10, we'll try disabling `permessage-deflate` as you suggested.
