### ISSUE TITLE
HTTP2 PushedResourcesTest.testPushedResources() has NPE

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#8823]
**Jetty version(s)**
12

**Description**
The pushed resources test passes, but has a disturbing exception logged.   If this is really expected, then the stack should be suppressed, but it does not look like a reasonable exception to expect???

```
Running org.eclipse.jetty.http2.tests.PushedResourcesTest.testPushedResources()
2022-11-02 14:31:13.852:INFO :oejs.Server:main: jetty-12.0.0-SNAPSHOT; built: unknown; git: ; jvm 17.0.4+8-Ubuntu-122.04
2022-11-02 14:31:13.867:INFO :oejs.AbstractConnector:main: Started ServerConnector@74ea2410{h2c, (h2c)}{0.0.0.0:46035}
2022-11-02 14:31:13.867:INFO :oejs.Server:main: Started oejs.Server@76b1e9b8{STARTING}[12.0.0-SNAPSHOT,sto=0] @1533ms
2022-11-02 14:31:13.915:WARN :oejut.SerializedInvoker:server-39: Serialized invocation error
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.http.MetaData$Request.getMethod()" because "this._requestMetaData" is null
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.consumeAvailable(HttpStreamOverHTTP2.java:542)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.succeeded(HttpChannelState.java:1365)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:145)
	at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:85)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.succeeded(HttpChannelState.java:1206)
	at org.eclipse.jetty.http2.internal.HTTP2Stream.succeeded(HTTP2Stream.java:711)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:399)
	at org.eclipse.jetty.util.CountingCallback.succeeded(CountingCallback.java:63)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:399)
	at org.eclipse.jetty.http2.internal.HTTP2Session$DataEntry.succeeded(HTTP2Session.java:1412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.jetty.http2.internal.HTTP2Flusher.finish(HTTP2Flusher.java:324)
	at org.eclipse.jetty.http2.internal.HTTP2Flusher.succeeded(HTTP2Flusher.java:316)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:291)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:374)
	at org.eclipse.jetty.http2.internal.HTTP2Flusher.process(HTTP2Flusher.java:293)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:214)
	at org.eclipse.jetty.http2.internal.HTTP2Session$StreamsState.flush(HTTP2Session.java:2229)
	at org.eclipse.jetty.http2.internal.HTTP2Session$StreamsState.createLocalStream(HTTP2Session.java:2136)
	at org.eclipse.jetty.http2.internal.HTTP2Session$StreamsState.push(HTTP2Session.java:2101)
	at org.eclipse.jetty.http2.internal.HTTP2Session.push(HTTP2Session.java:647)
	at org.eclipse.jetty.http2.internal.HTTP2Stream.push(HTTP2Stream.java:141)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.push(HttpStreamOverHTTP2.java:452)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelRequest.push(HttpChannelState.java:1010)
	at org.eclipse.jetty.http2.tests.PushedResourcesTest$2.process(PushedResourcesTest.java:123)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-02 14:31:13.923:WARN :oejut.SerializedInvoker:server-39: Serialized invocation error
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.http.MetaData$Request.getMethod()" because "this._requestMetaData" is null
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.consumeAvailable(HttpStreamOverHTTP2.java:542)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.succeeded(HttpChannelState.java:1365)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:145)
	at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:85)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.succeeded(HttpChannelState.java:1206)
	at org.eclipse.jetty.http2.internal.HTTP2Stream.succeeded(HTTP2Stream.java:711)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:399)
	at org.eclipse.jetty.util.CountingCallback.succeeded(CountingCallback.java:63)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:399)
	at org.eclipse.jetty.http2.internal.HTTP2Session$DataEntry.succeeded(HTTP2Session.java:1412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.jetty.http2.internal.HTTP2Flusher.finish(HTTP2Flusher.java:324)
	at org.eclipse.jetty.http2.internal.HTTP2Flusher.succeeded(HTTP2Flusher.java:316)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:291)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:374)
	at org.eclipse.jetty.http2.internal.HTTP2Flusher.process(HTTP2Flusher.java:293)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:214)
	at org.eclipse.jetty.http2.internal.HTTP2Session$StreamsState.flush(HTTP2Session.java:2229)
	at org.eclipse.jetty.http2.internal.HTTP2Session$StreamsState.createLocalStream(HTTP2Session.java:2136)
	at org.eclipse.jetty.http2.internal.HTTP2Session$StreamsState.push(HTTP2Session.java:2101)
	at org.eclipse.jetty.http2.internal.HTTP2Session.push(HTTP2Session.java:647)
	at org.eclipse.jetty.http2.internal.HTTP2Stream.push(HTTP2Stream.java:141)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.push(HttpStreamOverHTTP2.java:452)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelRequest.push(HttpChannelState.java:1010)
	at org.eclipse.jetty.http2.tests.PushedResourcesTest$2.process(PushedResourcesTest.java:125)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-02 14:31:13.930:INFO :oejs.Server:main: Stopped oejs.Server@76b1e9b8{STOPPING}[12.0.0-SNAPSHOT,sto=0]
2022-11-02 14:31:13.930:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@74ea2410{h2c, (h2c)}{0.0.0.0:0}


```

**How to reproduce?**

**Comment by sbordet** [comment]
Fixed by #8760 which needs approval.
