### ISSUE TITLE
jetty-documentation is using hardcoded 8080 port

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#8901]
When building `jetty-documentation` this logs shows a usage of hardcoded port
```
[INFO] --- asciidoctor-maven-plugin:2.2.2:process-asciidoc (operations-guide) @ jetty-documentation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 6 resources
[INFO] Executing: [/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java, -Djava.io.tmpdir=/Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/target/tests/test-bases/jetty_base_2066819533267966495/work, -jar, /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-home/target/jetty-home/start.jar, /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-home/target/jetty-home/etc/jetty-halt.xml]
[INFO] Working Dir: /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/target/tests/test-bases/jetty_base_2066819533267966495
[INFO] ERROR : No enabled jetty modules found!
[INFO] INFO  : ${jetty.home} = /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-home/target/jetty-home
[INFO] INFO  : ${jetty.base} = /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/target/tests/test-bases/jetty_base_2066819533267966495
[INFO] ERROR : Please create and/or configure a ${jetty.base} directory.
[INFO] 
[INFO] Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
[INFO]        java -jar $JETTY_HOME/start.jar --help  # for more information
[INFO] Executing: [/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java, -Djava.io.tmpdir=/Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/target/tests/test-bases/jetty_base_5200685557688164946/work, -jar, /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-home/target/jetty-home/start.jar, --add-module=http, /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-home/target/jetty-home/etc/jetty-halt.xml]
[INFO] Working Dir: /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/target/tests/test-bases/jetty_base_5200685557688164946
[INFO] INFO  : mkdir ${jetty.base}/start.d
[INFO] INFO  : server          transitively enabled, ini template available with --add-module=server
[INFO] INFO  : logging-jetty   transitively enabled
[INFO] INFO  : http            initialized in ${jetty.base}/start.d/http.ini
[INFO] INFO  : resources       transitively enabled
[INFO] INFO  : threadpool      transitively enabled, ini template available with --add-module=threadpool
[INFO] INFO  : logging/slf4j   dynamic dependency of logging-jetty
[INFO] INFO  : bytebufferpool  transitively enabled, ini template available with --add-module=bytebufferpool
[INFO] INFO  : mkdir ${jetty.base}/resources
[INFO] INFO  : copy ${jetty.home}/modules/logging/jetty/resources/jetty-logging.properties to ${jetty.base}/resources/jetty-logging.properties
[INFO] INFO  : Base directory was modified
[INFO] Executing: [/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java, -Djava.io.tmpdir=/Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/target/tests/test-bases/jetty_base_13654429547197229919/work, -jar, /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-home/target/jetty-home/start.jar, --module=http, /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-home/target/jetty-home/etc/jetty-halt.xml]
[INFO] Working Dir: /Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/target/tests/test-bases/jetty_base_13654429547197229919
[INFO] 2022-11-16 12:14:16.170:INFO :oejs.Server:main: jetty-10.0.13-SNAPSHOT; built: 2022-11-14T05:21:15.240Z; git: 12041da72f403e066d941f91b07540255ff9c823; jvm 17-ea+32-2679
[INFO] 2022-11-16 12:14:16.204:WARN :oejx.XmlConfiguration:main: Unable to execute XmlConfiguration
[INFO] java.security.PrivilegedActionException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
[INFO] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
[INFO] 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1810)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[INFO] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO] 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:229)
[INFO] 	at org.eclipse.jetty.start.Main.start(Main.java:527)
[INFO] 	at org.eclipse.jetty.start.Main.main(Main.java:76)
[INFO] Caused by: 
[INFO] java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
[INFO] 	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
[INFO] 	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304)


```

**Comment by sbordet** [comment]
@olamy as we are running in a container, binding to 8080 should always be possible.
Seems like a container/configuration problem of the build environment to me.

**Comment by olamy** [comment]
`failing` locally because I have something already using port 8080 locally.
The issue is the quiet failure. As we are going to integrate the documentation in the release tarball we need to be sure we do not include bad documentation.

**Comment by joakime** [comment]
Closing, as the documentation is undergoing an overhaul, where this is likely not a concern anymore.
