### ISSUE TITLE
Jetty ThreadPool CLOSE_WAIT causing server to hang

### ISSUE THREAD

**Issue by smohan25** [eclipse/jetty.project#8908]
**Jetty version(s)**
jetty-server-9.2.28.v20190418

**Java version/vendor** `(use: java -version)`
Java 11

**OS type/version**
Linux

**Description**
We have a server that is using jetty as its http server to accept rest requests. During very specific high loads (client connections closed prematurely), we notice that jetty thread pool has all its threads waiting, we see a bunch of CLOSE_WAIT connections, the jetty queue becomes full, and the server becomes unresponsive. Restarting the server fixes the issue.

**How to reproduce?**
Send a lot of traffic to the server and close it prematurely. The server ends up in this state.

Ideally, bad client requests should not cause the server to hang. This issue has been biting us in production and causing our servers to hang. Is this a known bug in 9.2? Is there a safe upgrade? We'd like to know why this is happening. Thanks so much. Attaching some thread dumps

"qtp61137731-86-acceptor-2@26f7cdf8-ServerConnector@7ed9ae94{SSL,[ssl, alpn, h2, http/1.1]}{0.0.0.0:13283}" #86 prio=3 os_prio=0 cpu=7062.40ms elapsed=932996.16s tid=0x00007f48e5189800 nid=0x7613 waiting on condition  [0x00007f46b3cfb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
	- parking to wait for  <0x000000148025be10> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.13/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.13/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.13/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.13/ReentrantLock.java:267)
	at sun.nio.ch.ServerSocketChannelImpl.accept(java.base@11.0.13/ServerSocketChannelImpl.java:275)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:648)
	at com.linkedin.emweb.ThreadPoolWithTracking$QueuedRunnable.run(ThreadPoolWithTracking.java:424)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(java.base@11.0.13/Thread.java:829)

   Locked ownable synchronizers:
	- None

"qtp61137731-87-acceptor-3@376e7531-ServerConnector@7ed9ae94{SSL,[ssl, alpn, h2, http/1.1]}{0.0.0.0:13283}" #87 prio=3 os_prio=0 cpu=7075.12ms elapsed=932996.16s tid=0x00007f48e518b800 nid=0x7614 waiting on condition  [0x00007f46b3bfa000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
	- parking to wait for  <0x000000148025be10> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.13/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.13/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.13/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.13/ReentrantLock.java:267)
	at sun.nio.ch.ServerSocketChannelImpl.accept(java.base@11.0.13/ServerSocketChannelImpl.java:275)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:648)
	at com.linkedin.emweb.ThreadPoolWithTracking$QueuedRunnable.run(ThreadPoolWithTracking.java:424)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(java.base@11.0.13/Thread.java:829)

   Locked ownable synchronizers:
	- None

On the server side we see a bunch of Eof exceptions
org.eclipse.jetty.io.EofException: Reset cancel_stream_error
        at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:156) ~[?:?]
        at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:564) ~[?:?]
        at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:340) ~[?:?]
        at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:251) ~[?:?]
        at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:294) ~[?:?]
        at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onReset(Parser.java:368) ~[?:?]
        at org.eclipse.jetty.http2.parser.BodyParser.notifyReset(BodyParser.java:139) ~[?:?]
        at org.eclipse.jetty.http2.parser.ResetBodyParser.onReset(ResetBodyParser.java:97) ~[?:?]
        at org.eclipse.jetty.http2.parser.ResetBodyParser.parse(ResetBodyParser.java:66) ~[?:?]
        at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:194) ~[?:?]
        at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:123) ~[?:?]
        at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:115) ~[?:?]
        at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:252) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132) ~[?:?]
        at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:171) ~[?:?]
        at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:126) ~[?:?]
        at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:338) ~[?:?]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.2.28.v20190418.jar:9.2.28.v20190418]
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411) ~[jetty-io-9.2.28.v20190418.jar:9.2.28.v20190418]
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305) ~[jetty-io-9.2.28.v20190418.jar:9.2.28.v20190418]
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159) ~[jetty-io-9.2.28.v20190418.jar:9.2.28.v20190418]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.2.28.v20190418.jar:9.2.28.v20190418]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) ~[?:?]
        at org.eclipse.jetty.util.thread.Invocable.invokeNonBlocking(Invocable.java:68) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.invokeTask(EatWhatYouKill.java:345) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:300) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132) ~[?:?]
        at com.linkedin.emweb.ThreadPoolWithTracking$QueuedRunnable.run(ThreadPoolWithTracking.java:424) ~[?:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) ~[jetty-util-9.2.28.v20190418.jar:9.2.28.v20190418]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) ~[jetty-util-9.2.28.v20190418.jar:9.2.28.v20190418]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
        Suppressed: java.lang.Throwable: HttpInput failure
                at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:826) ~[jetty-server-9.2.28.v20190418.jar:9.2.28.v20190418]
                at org.eclipse.jetty.http2.server.HttpChannelOverHTTP2.onFailure(HttpChannelOverHTTP2.java:323) ~[?:?]
                at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onStreamFailure(HTTP2ServerConnection.java:219) ~[?:?]
                at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:156) ~[?:?]
                at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:564) ~[?:?]
                at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:340) ~[?:?]
                at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:251) ~[?:?]
                at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:294) ~[?:?]

**Comment by gregw** [comment]
Jetty-9 is end of community support (see #7958)
Note that you are using an old release of jetty-9 and you could try 9.4.49 to see if the problem has been resolved (or better yet, try jetty-10, which is still supported).

We would only look at jetty-9.2 issues with commercial support.

**Comment by joakime** [comment]
To add to this, Jetty 9.2.x series was declared End of Life back in 2018.
