### ISSUE TITLE
get NoSuchMethodException ofVirtual when building project

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.project#8930]
**Jetty version(s)**
10.0.x

**Java version/vendor** `(use: java -version)`
Java version: 17.0.4, vendor: Eclipse Adoptium

**Description**
Error when building project I think its from the documentation. Still get a green build but see the following error message.

```
[INFO] 2022-11-23 16:42:12.891:WARN :oejx.XmlConfiguration:main: Unable to execute XmlConfiguration
[INFO] java.lang.IllegalStateException: No Method: <Call class="java.lang.Thread" name="ofVirtual"><Call class="java.lang.Thread$Builder" name="name"><Arg>|          <Property name="jetty.threadPool.virtual.namePrefix"><Default><Ref refid="namePrefix"/>-virtual-</Default></Property>|        </Arg><Arg type="long">0</Arg><Call class="java.lang.Thread$Builder" name="allowSet
ThreadLocals"><Arg type="boolean"><Property name="jetty.threadPool.virtual.allowSetThreadLocals" default="true"/></Arg><Call class="java.lang.Thread$Builder" name="inheritInheritableThreadLocals"><Arg type="boolean"><Property name="jetty.threadPool.virtual.inheritInheritableThreadLocals" default="false"/></Arg><Call id="virtualThreadFactory" class="java.lang.Thread$Builder
" name="factory"/></Call></Call></Call></Call> on class java.lang.Thread
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:918)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:464)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:986)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:470)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:417)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:319)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1861)
[INFO]  at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)
[INFO] Caused by: 
[INFO] java.lang.NoSuchMethodException: ofVirtual
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:951)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:910)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:464)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:986)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:470)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:417)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:319)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1861)
[INFO]  at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[INFO]  at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)
[INFO] Exception in thread "main" java.lang.IllegalStateException: No Method: <Call class="java.lang.Thread" name="ofVirtual"><Call class="java.lang.Thread$Builder" name="name"><Arg>
[INFO]           <Property name="jetty.threadPool.virtual.namePrefix"><Default><Ref refid="namePrefix"/>-virtual-</Default></Property>
[INFO]         </Arg><Arg type="long">0</Arg><Call class="java.lang.Thread$Builder" name="allowSetThreadLocals"><Arg type="boolean"><Property name="jetty.threadPool.virtual.allowSetThreadLocals" default="true"/></Arg><Call class="java.lang.Thread$Builder" name="inheritInheritableThreadLocals"><Arg type="boolean"><Property name="jetty.threadPool.virtual.inheritInheritableThreadLocals" default="false"/></Arg><Call id="virtualThreadFactory" class="java.lang.Thread$Builder" name="factory"/></Call></Call></Call></Call> on class java.lang.Thread

```

**Comment by joakime** [comment]
The CI builds for Jetty 10 and 11 are green on JDK 17

**Comment by lachlan-roberts** [comment]
The build is still green but this exception comes up in the logs when building even on JDK17

**Comment by sbordet** [comment]
@lachlan-roberts there is no way around. In order to document virtual threads, we need to run the documentation with Java 19.
We have updated the release profile to require at least Java 19 now.
Please review #8932.

**Comment by lachlan-roberts** [comment]
Ok, so you must build the project with JDK19+ or expect to see this error when building.
