### ISSUE TITLE
Flaky Test `org.eclipse.jetty.http2.client.StreamCloseTest.testRequestDataClosedResponseDataClosedClosesStream`

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9009]
**Jetty version(s)**
Jetty 10.0.13-SNAPSHOT

**Java version/vendor** `(use: java -version)`
JDK 11

**Description**

The `jetty-10.0.x` HEAD is failing CI.

```
org.eclipse.jetty.http2.client@10.0.13-SNAPSHOT/org.eclipse.jetty.http2.client.StreamCloseTest.testRequestDataClosedResponseDataClosedClosesStream
```

This test has failed 3 times in a row now.

```
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
	at org.eclipse.jetty.http2.client@10.0.13-SNAPSHOT/org.eclipse.jetty.http2.client.StreamCloseTest.testRequestDataClosedResponseDataClosedClosesStream(StreamCloseTest.java:182)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

STDERR

```
Running org.eclipse.jetty.http2.client.StreamCloseTest.testRequestDataClosedResponseDataClosedClosesStream()
2022-12-06 13:40:55.505:INFO :oejs.Server:main: jetty-10.0.13-SNAPSHOT; built: 2022-12-06T13:10:56.207Z; git: 390abcccf2826d1660bf1174283c90a8c941dfdf; jvm 11.0.14.1+1
2022-12-06 13:40:55.507:INFO :oejs.AbstractConnector:main: Started ServerConnector@3457cc8d{h2, (h2)}{0.0.0.0:36533}
2022-12-06 13:40:55.507:INFO :oejs.Server:main: Started Server@7994a0d1{STARTING}[10.0.13-SNAPSHOT,sto=0] @196756ms
2022-12-06 13:40:55.516:INFO :oejs.Server:main: Stopped Server@7994a0d1{STOPPING}[10.0.13-SNAPSHOT,sto=0]
2022-12-06 13:40:55.516:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@3457cc8d{h2, (h2)}{0.0.0.0:0}
```

**Comment by sbordet** [comment]
This is a side effect of #8678.

The test asserts for the stream to be closed (which it is), but it's not yet removed from the session's streams, so the assert may spuriously fail.

The fix is to wait a little bit for the streams to go to zero.
