### ISSUE TITLE
Jetty-9.3.11.v20160721 - sendBinary() - java.lang.IllegalArgumentException: message cannot be null

### ISSUE THREAD

**Issue by b6arat6** [eclipse/jetty.project#903]
We plan to use JSR-356 for WebSocket along with Jetty for Production deployment but Server ends in error while using sendBinary().

Could you check it?

--

Error trace:

java.lang.IllegalArgumentException: message cannot be null
	at org.eclipse.jetty.websocket.jsr356.AbstractJsrRemote.assertMessageNotNull(AbstractJsrRemote.java:69)
	at org.eclipse.jetty.websocket.jsr356.JsrAsyncRemote.sendBinary(JsrAsyncRemote.java:61)
	at com.apple.sample.websocket.endpoint.FileServer.onMessage(FileServer.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
	at org.eclipse.jetty.websocket.jsr356.annotations.OnMessageTextCallable.call(OnMessageTextCallable.java:63)
	at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callText(JsrEvents.java:197)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextMessage(JsrAnnotatedEventDriver.java:378)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextFrame(JsrAnnotatedEventDriver.java:360)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:176)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:142)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:85)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jmcc0nn3ll** [comment]
Are you certain you are not trying to send an empty binary message?

**Comment by b6arat6** [comment]
Yes, I am pretty sure that I don't send an empty binary message. The same code works on ApacheTomcat 7/8 without any issues.

**Comment by joakime** [comment]
This is the correct behavior for the JSR356 API.

See the javadoc for .sendBinary():
http://docs.oracle.com/javaee/7/api/javax/websocket/RemoteEndpoint.Async.html#sendBinary-java.nio.ByteBuffer-

We received a data (ByteBuffer) that was null (not empty), and the IllegalArgumentException is telling you that.

Looking at the stacktrace:

 - A Whole Text message was received
 - The `@OnMessage` method `com.apple.sample.websocket.endpoint.FileServer.onMessage`  was called
 - While in this method, a call to `RemoteEndpoint.Async#sendBinary(ByteBuffer)` was called with a value of null for the `data` parameter.

**Comment by b6arat6** [comment]
My bad! I did debugging to ensure again whether null is sent but yes it sends null & hence the exception.

A system property was missed to be added in Jetty, which is required by the application to find the file location whereas its properly added in ApacheTomcat.

Jetty works perfectly.

Thanks jmcc0nn3ll & joakime for the help!

Closing the issue.
