### ISSUE TITLE
Jetty 12 : `org.eclipse.jetty.ee9.websocket.tests.WebSocketOverHTTP2Test.testWebSocketConnectPortDoesNotExist` failing

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9120]
**Jetty version(s)**
Jetty 12

**Java version/vendor** `(use: java -version)`
Java 19

**OS type/version**
Linux

**Description**

Error:

```
Expected: an instance of java.net.ConnectException
     but: <java.io.IOException: frame_size_error/invalid_frame_length> is a java.io.IOException
```

Stacktrace:

```
java.lang.AssertionError: 
Expected: an instance of java.net.ConnectException
     but: <java.io.IOException: frame_size_error/invalid_frame_length> is a java.io.IOException
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.ee9.websocket.tests.WebSocketOverHTTP2Test.testWebSocketConnectPortDoesNotExist(WebSocketOverHTTP2Test.java:256)
```

Output:

```
Running org.eclipse.jetty.ee9.websocket.tests.WebSocketOverHTTP2Test.testWebSocketConnectPortDoesNotExist()
2023-01-02 21:48:32.631:INFO :oejs.Server:main: jetty-12.0.0-SNAPSHOT; built: 2023-01-02T20:54:23.235Z; git: 3498fe4e8134b70fb709e7e603daf87e1980f116; jvm 19+36-2238
2023-01-02 21:48:32.633:INFO :oejsh.ContextHandler:main: Started oeje9n.ContextHandler$CoreContextHandler@3e05586b{ROOT,/,b=null,a=AVAILABLE,h=oeje9n.ContextHandler$CoreContextHandler$CoreToNestedHandler@35b17c06{STARTED}}
2023-01-02 21:48:32.633:INFO :oejs.AbstractConnector:main: Started ServerConnector@343e225a{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:39111}
2023-01-02 21:48:32.643:INFO :oejus.SslContextFactory:main: x509=X509@7e62cfa3(1,h=[localhost],a=[],w=[]) for Server@46e190ed[provider=null,keyStore=file:///home/jenkins/agent/workspace/jetty.project_PR-9118/jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-tests/target/test-classes/keystore.p12,trustStore=null]
2023-01-02 21:48:32.649:INFO :oejs.AbstractConnector:main: Started ServerConnector@36f7d7b{SSL, (ssl, alpn, http/1.1, h2)}{0.0.0.0:46339}
2023-01-02 21:48:32.649:INFO :oejs.Server:main: Started oejs.Server@17dad32f{STARTING}[12.0.0-SNAPSHOT,sto=0] @12934ms
2023-01-02 21:48:32.651:WARN :oejusS.config:main: Trusting all certificates configured for Client@37348491[provider=null,keyStore=null,trustStore=null]
2023-01-02 21:48:32.651:WARN :oejusS.config:main: No Client EndPointIdentificationAlgorithm configured for Client@37348491[provider=null,keyStore=null,trustStore=null]
2023-01-02 21:48:32.657:INFO :oejs.Server:main: Stopped oejs.Server@17dad32f{STOPPING}[12.0.0-SNAPSHOT,sto=0]
2023-01-02 21:48:32.657:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@343e225a{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}
2023-01-02 21:48:32.658:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@36f7d7b{SSL, (ssl, alpn, http/1.1, h2)}{0.0.0.0:0}
2023-01-02 21:48:32.658:INFO :oejewc.WebSocketClient:main: Shutdown WebSocketClient@cca2a347[coreClient=oejwcc.WebSocketCoreClient@4dac121d{STARTED},openSessions.size=0]
```

**Comment by lorban** [comment]
Cannot reproduce.
