### ISSUE TITLE
HTTP Client doStop hang during traffic load

### ISSUE THREAD

**Issue by lisay-yan** [eclipse/jetty.project#9126]
**Jetty version(s)**
`9.4.48.v20220622`

**Java version/vendor** `(use: java -version)`
java11
**OS type/version**
linux
**Description**
During traffic load (maybe queued message), server side down, and httpclient call doStop.
The thread is hang due to countdownlatch can't become 0.

"pool-5-thread-1" Id=54 WAITING on [java.util.concurrent.CountDownLatch$Sync@8b67cb9](mailto:java.util.concurrent.CountDownLatch$Sync@8b67cb9)
    at [java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native](mailto:java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native) Method)
    -  waiting on [java.util.concurrent.CountDownLatch$Sync@8b67cb9](mailto:java.util.concurrent.CountDownLatch$Sync@8b67cb9)
    at [java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)](mailto:java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211))
    at [java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)](mailto:java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715))
    at [java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)](mailto:java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047))
    at [java.base@17.0.3/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)](mailto:java.base@17.0.3/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230))
    at org.eclipse.jetty.io.ManagedSelector.doStop(ManagedSelector.java:140)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
    -  locked [java.lang.Object@5fdd16e8](mailto:java.lang.Object@5fdd16e8)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
    at org.eclipse.jetty.io.SelectorManager.doStop(SelectorManager.java:281)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
    -  locked [java.lang.Object@5b747d81](mailto:java.lang.Object@5b747d81)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
    at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.doStop(AbstractConnectorHttpClientTransport.java:70)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
    -  locked [java.lang.Object@7fe25bd](mailto:java.lang.Object@7fe25bd)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
    at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:279)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
    -  locked [java.lang.Object@3feb47fa](mailto:java.lang.Object@3feb47fa)
    at com.nokia.prs.http.HttpsClientManager.delHttpsClient(HttpsClientManager.java:208)

**How to reproduce?**
Make heavy traffic load, and HttpClient doStop due to server scale in.

Is there any suggestion for handle such cases?
Such as before call HttpClient doStop to check if HttpClient in progress CompleteListeners all are completed.
Or any save code example to call HttpClient doStop and prevent hang?

**Comment by sbordet** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

Please try Jetty 10/11, also because they have an improved stop logic that checks when you are trying to stop the client (and its associated thread pool) from a thread of the client's thread pool.

**Comment by lisay-yan** [comment]
@sbordet  and @joakime 

OK, I will upgrade jetty to 11.0.11 and repeat same testing.
The ticket can be closed if no thread hang at Jetty 11.0.11.
Or maybe change jetty version to 11.0.11 in case thread is still hang. Thanks.

**Comment by joakime** [comment]
11.0.11 is not the latest version.
Please use the latest version in Jetty 11.x when you start to upgrade.

**Comment by lisay-yan** [comment]
Thanks @joakime , I will use latest release version jetty-11.0.13.

**Comment by lisay-yan** [comment]
After upgrade to jetty-11.0.13. Not find hang issue anymore. Thanks.
