### ISSUE TITLE
Proxy request to another server using RequestDispatcher and the jetty ProxyServlet

### ISSUE THREAD

**Issue by lmtjalves** [eclipse/jetty.project#9140]
**Jetty version**
9.4.50

**Java version**
Java 17

**Context**

I have two servers (let's call them A and B) that are both running the same application. This is a Dropwizard application, but as far as I see, the issue doesn't seem related to Dropwizard.

I want to achieve the following: if server A receives a request and a given condition is verified, I want it to proxy the request to server B (to the same endpoint) instead of processing it in server A.

To achieve this, I've done the following:

1. Added a Jetty ProxyServlet in my application, mapped to `/proxy/*`. Configured to proxy requests to server B as follows: if I receive a `GET /proxy/foo/bar` it will send a `GET /foo/bar` to server B.

2. In the resource method(s) whose request I want to be proxy to server B, I'm using a RequestDispatcher to forward the request to the ProxyServlet. I do this as follows:
  
```
@GET
@Path("/foo/{id}")
public Response get(@Context final HttpServletRequest request, @Context final HttpServletResponse response, @PathParam("id") final String id) {
  if (<some-condition>) {
    request.getRequestDispatcher(String.format("/proxy%s", request.getRequestURI())).forward(request, response);
    return null;
  }
  ...
}
```

If I send a `GET /foo/123` (and in a scenario where the condition is verified), I can see this working as expected.

**Problem**
If I instead try to do the same but for a POST request with a body (e.g. `POST /foo` to server A) it doesn't work, I get a Gateway Timeout as a response. I see the following exception in server B, which seems to indicate that there was a timeout on the server B side reading the request content:

```
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.server.HttpInput$ErrorState.noContent(HttpInput.java:1149)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:333)
	at ch.qos.logback.access.servlet.TeeServletInputStream.consumeBufferAndReturnAsByteArray(TeeServletInputStream.java:57)
	at ch.qos.logback.access.servlet.TeeServletInputStream.duplicateInputStream(TeeServletInputStream.java:38)
	at ch.qos.logback.access.servlet.TeeServletInputStream.<init>(TeeServletInputStream.java:31)
	at ch.qos.logback.access.servlet.TeeHttpServletRequest.<init>(TeeHttpServletRequest.java:44)
	at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:49)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:284)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
	at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:439)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
	Suppressed: java.lang.Throwable: HttpInput idle timeout
		at org.eclipse.jetty.server.HttpInput.onIdleTimeout(HttpInput.java:866)
		at org.eclipse.jetty.server.HttpChannelOverHttp.onIdleTimeout(HttpChannelOverHttp.java:406)
		at org.eclipse.jetty.server.HttpConnection.onReadTimeout(HttpConnection.java:501)
		at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:172)
		at org.eclipse.jetty.server.HttpConnection.onFillInterestedFailed(HttpConnection.java:508)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:317)
		at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:140)
		at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407)
		... 8 more
```

The method implementation is similar:

```
@POST
public Response post(@Context final HttpServletRequest request, @Context final HttpServletResponse response, @PathParam("id") final String body) {
  if (<some-condition>) {
    request.getRequestDispatcher(String.format("/proxy%s", request.getRequestURI())).forward(request, response);
    return null;
  }
  ...
}
```

**Other observations**

1. If I instead send a `POST /proxy/foo` to server A (directly to the ProxyServlet), it works as expected. This leads me to believe that the issue is somehow related to the interaction between the RequestDispatcher and the ProxyServlet.
2. The issue is not fixed if I increase the timeout.
3. If I send the POST request without a body, it works as expected.

**Question**

Can you give me some pointers on how I can further debug this issue? Or is this something totally expected and that is not possible to do with Jetty?

**Comment by sbordet** [comment]
The stack trace shows `ch.qos.logback.access.servlet.TeeFilter` trying to read the request content.

I presume the request content has already been fully read, so it cannot be read again.
However, that should not block: if it was not read it will be read by the filter, if it was already read it should immediately return -1.

Does the request correctly send the POST body?

You can debug further by enabling DEBUG level logs for the logger name `org.eclipse.jetty`.
Attach them to this issue.

**Comment by lmtjalves** [comment]
I noticed that on server A, the request that I get is a `TeeHttpServletRequest` (the same issue happens if I remove the TeeFilter and get a `HttpInputOverHTTP`). And it seems that the input stream that I get from calling `request.getInputStream()` was already consumed, which seems to be expected according to the answers here: https://stackoverflow.com/questions/8522568/why-is-httpservletrequest-inputstream-empty.

The issue seems to be that the same input stream (that was already consumed) is what is sent to the ProxyServlet.

I can't find a way to reset the input stream, as it seems that the reset/mark method is not implemented/overridden by the TeeServletInputStream implementation. So, I suspect that under these circumstances it is not possible to make this work.

**Comment by sbordet** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

Please upgrade to Jetty 10/11.

Regardless, you should probably change the order of the filters, or get rid of the `TeeFilter` altogether.
I'm surprised it reads the content, maybe it can be configured to not to?
