### ISSUE TITLE
Invoking the offer method of BlockingArrayQueue is blocked.

### ISSUE THREAD

**Issue by usertree** [eclipse/jetty.project#9146]
**Jetty version(s)**
9.4.48.v20220622
**Java version/vendor** `(use: java -version)`
1.8
**OS type/version**
x86
**Description**
We found that all requests could not be sent to the peer end. After the thread stack is printed, it is found that the stacks of all requests are blocked in the offer method of BlockingArrayQueue.
The thread is waiting for the lock object of 0x00000000aaf6d4a0, but the thread holding the lock cannot be found from the stack.
The thread stack is as follows:

"qtp796750076-896" #896 prio=5 os_prio=0 tid=0x000055e2919ea5b0 nid=0x36b52 waiting on condition [0x00007f0682fca000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000aaf6d4a0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:838)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:872)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1201)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at org.eclipse.jetty.util.BlockingArrayQueue.offer(BlockingArrayQueue.java:257)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:711)
	at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:163)
	at org.eclipse.jetty.io.ManagedSelector.execute(ManagedSelector.java:332)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:355)
	at org.eclipse.jetty.io.ManagedSelector.access$1700(ManagedSelector.java:65)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:676)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:535)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)

[catalinaout.log](https://github.com/eclipse/jetty.project/files/10380015/catalinaout.log)

**Comment by sbordet** [comment]
Jetty 9.x is now at End of Community Support.

* #7958

Please try Jetty 10/11.

**Comment by sbordet** [comment]
Likely you have a misconfiguration of the `BlockingArrayQueue`.

**Comment by usertree** [comment]
@sbordet The problem occurs occasionally and cannot be recovered after it occurs. According to the dump memory, the last thread that holds the lock has ended normally in the log. When is the lock not released?
![image](https://user-images.githubusercontent.com/32734356/211536360-bb045e36-f606-48c2-a452-9b3b66f42c92.png)

**Comment by sbordet** [comment]
As I said, you have to try Jetty 10+ and likely you have a misconfiguration. Try to make the queue unbounded.

**Comment by usertree** [comment]
@sbordet This may be a bug in openjdk，thanks
https://bugs.openjdk.org/browse/JDK-8046936
