### ISSUE TITLE
Jetty 12 - `AbstractConnectionPool.toString()` can trigger NPE

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#9240]
**Jetty version(s)**
Jetty 12

**Description**
Seems the AbstractConnectionPool.toString() can trigger a NPE when attempting to get the Pool.size() during a logging operation.

**How to reproduce?**
Run the jetty-ee10-demo-proxy-webapp with DEBUG turned on.
Hit the URL `http://localhost:8080/proxy/current` and see the output.

```
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 2023-01-31 15:35:51.821:DEBUG:oejuc.ContainerLifeCycle:qtp1333592072-46: [FAILED toString()] added [FAILED toString()]
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: SLF4J: Failed toString() invocation on an object of type [org.eclipse.jetty.client.MultiplexConnectionPool]
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: Reported exception:
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.util.Pool.size()" because "this.pool" is null
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.client.AbstractConnectionPool.getConnectionCount(AbstractConnectionPool.java:174)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.client.AbstractConnectionPool.toString(AbstractConnectionPool.java:531)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:291)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:263)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:225)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:160)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.logging.StdErrAppender.format(StdErrAppender.java:162)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.logging.StdErrAppender.emit(StdErrAppender.java:93)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.logging.JettyLogger.emit(JettyLogger.java:623)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.logging.JettyLogger.debug(JettyLogger.java:163)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:260)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:92)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.client.internal.HttpDestination.doStart(HttpDestination.java:163)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.addManaged(ContainerLifeCycle.java:439)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.client.HttpClient.lambda$resolveDestination$0(HttpClient.java:557)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.client.HttpClient.resolveDestination(HttpClient.java:551)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.client.HttpClient.resolveDestination(HttpClient.java:523)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.client.internal.HttpRequest.send(HttpRequest.java:738)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.ee10.proxy.AbstractProxyServlet.sendProxyRequest(AbstractProxyServlet.java:634)
2023-01-31 15:35:51.822:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.ee10.proxy.ProxyServlet.service(ProxyServlet.java:108)

```

**Comment by sbordet** [comment]
Fixed by #9278.
