### ISSUE TITLE
jetty-jmh 10.013 fails due to "java.lang.AssertionError: No trie for TernaryTrie"

### ISSUE THREAD

**Issue by anianna96** [eclipse/jetty.project#9341]
**Jetty version(s)**
Jetty 10.013

**Java version/vendor**
```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Zulu19.32+13-CA (build 19.0.2+7)
OpenJDK 64-Bit Server VM Zulu19.32+13-CA (build 19.0.2+7, mixed mode, sharing)
```

**OS type/version**
CentOS Linux release 7.9.2009 (3.10.0-957.10.1.el7.x86_64)

**Description**
```
# Run progress: 58.85% complete, ETA 04:23:40
# Fork: 1 of 5
# Warmup Iteration   1: SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
<failure>

java.lang.AssertionError: No trie for TernaryTrie
        at org.eclipse.jetty.util.TrieBenchmark.setUp(TrieBenchmark.java:75)
        at org.eclipse.jetty.util.jmh_generated.TrieBenchmark_testGet_jmhTest._jmh_tryInit_f_triebenchmark0_G(TrieBenchmark_testGet_jmhTest.java:438)
        at org.eclipse.jetty.util.jmh_generated.TrieBenchmark_testGet_jmhTest.testGet_Throughput(TrieBenchmark_testGet_jmhTest.java:71)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)


Benchmark had encountered error, and fail on error was requested
ERROR: org.openjdk.jmh.runner.RunnerException: Benchmark caught the exception
        at org.openjdk.jmh.runner.Runner.runBenchmarks(Runner.java:575)
        at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:310)
        at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
        at org.openjdk.jmh.Main.main(Main.java:71)
Caused by: org.openjdk.jmh.runner.BenchmarkException: Benchmark error during the run
        at org.openjdk.jmh.runner.BenchmarkHandler.runIteration(BenchmarkHandler.java:424)
        at org.openjdk.jmh.runner.BaseRunner.runBenchmark(BaseRunner.java:261)
        at org.openjdk.jmh.runner.BaseRunner.runBenchmark(BaseRunner.java:233)
        at org.openjdk.jmh.runner.BaseRunner.doSingle(BaseRunner.java:138)
        at org.openjdk.jmh.runner.BaseRunner.runBenchmarksForked(BaseRunner.java:75)
        at org.openjdk.jmh.runner.ForkedRunner.run(ForkedRunner.java:72)
        at org.openjdk.jmh.runner.ForkedMain.main(ForkedMain.java:86)
        Suppressed: java.lang.AssertionError: No trie for TernaryTrie
                at org.eclipse.jetty.util.TrieBenchmark.setUp(TrieBenchmark.java:75)
                at org.eclipse.jetty.util.jmh_generated.TrieBenchmark_testGet_jmhTest._jmh_tryInit_f_triebenchmark0_G(TrieBenchmark_testGet_jmhTest.java:438)
                at org.eclipse.jetty.util.jmh_generated.TrieBenchmark_testGet_jmhTest.testGet_Throughput(TrieBenchmark_testGet_jmhTest.java:71)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
                at java.base/java.lang.reflect.Method.invoke(Method.java:578)
                at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
                at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
                at java.base/java.lang.Thread.run(Thread.java:1589)

```
**How to reproduce?**
```
Step 1: export JAVA_HOME=<>
Step 2: mvn -V -B -Dmaven.repo.local=maven_repo  clean install -DskipTests -T6 -e -pl :jetty-jmh -am
Step 3: ${JAVA_HOME}/bin/java --enable-preview --enable-native-access=ALL-UNNAMED -jar ./tests/jetty-jmh/target/benchmarks.jar -rff ./jmh_result.json -rf json  -foe true -i 3 -t 3 -wi 3
```

**Comment by janbartel** [comment]
I haven't been able to reproduce the failure.

I'm using:

`jetty-10.0.x head`

```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```

Here's what I get:


```
[227] java --enable-preview --enable-native-access=ALL-UNNAMED -jar benchmarks.jar -rff ./jmh_result.json -rf json  -foe true -i 3 -t 3 -wi 3 org.eclipse.jetty.util.TrieBenchmark
# JMH version: 1.36
# VM version: JDK 19.0.2, OpenJDK 64-Bit Server VM, 19.0.2+7-44
# VM invoker: /home/janb/java/jvm/jdk-19.0.2/bin/java
# VM options: --enable-preview --enable-native-access=ALL-UNNAMED
# Blackhole mode: compiler (auto-detected, use -Djmh.blackhole.autoDetect=false to disable)
# Warmup: 3 iterations, 10 s each
# Measurement: 3 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 3 threads, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: org.eclipse.jetty.util.TrieBenchmark.testGet
# Parameters: (TRIE_TYPE = ArrayTrie)
 
# Run progress: 0.00% complete, ETA 01:15:00
# Fork: 1 of 5
# Warmup Iteration   1: SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
8250332.947 ops/s
# Warmup Iteration   2: 8292470.259 ops/s
# Warmup Iteration   3: 8505976.523 ops/s
Iteration   1: 8539011.003 ops/s
Iteration   2: 8318529.911 ops/s
```

From the nature of the failure, the problem seems to me to lie with Azul. Worth checking with them.

**Comment by anianna96** [comment]
@janbartel,
I can reproduce the issue with OpenJDK19 as well. It takes a while for the failure to reproduce. The failure is not found as soon as the run has started.

Command Line:
```
java --enable-preview --enable-native-access=ALL-UNNAMED -jar ./jetty.project/tests/jetty-jmh/target/benchmarks.jar  -rff ./jmh_result.json -rf json  -foe true -i 3 -t 3 -wi 3 org.eclipse.jetty.util.TrieBenchmark
```
Java:
```java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```
Console Output
```# Run progress: 6.67% complete, ETA 01:10:35
# Fork: 1 of 5
# Warmup Iteration   1: SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
<failure>

java.lang.AssertionError: No trie for TernaryTrie
        at org.eclipse.jetty.util.TrieBenchmark.setUp(TrieBenchmark.java:75)
        at org.eclipse.jetty.util.jmh_generated.TrieBenchmark_testGet_jmhTest._jmh_tryInit_f_triebenchmark0_G(TrieBenchmark_testGet_jmhTest.java:438)
        at org.eclipse.jetty.util.jmh_generated.TrieBenchmark_testGet_jmhTest.testGet_Throughput(TrieBenchmark_testGet_jmhTest.java:71)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)


Benchmark had encountered error, and fail on error was requested
ERROR: org.openjdk.jmh.runner.RunnerException: Benchmark caught the exception
        at org.openjdk.jmh.runner.Runner.runBenchmarks(Runner.java:575)
        at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:310)
        at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
        at org.openjdk.jmh.Main.main(Main.java:71)
Caused by: org.openjdk.jmh.runner.BenchmarkException: Benchmark error during the run
        at org.openjdk.jmh.runner.BenchmarkHandler.runIteration(BenchmarkHandler.java:424)
        at org.openjdk.jmh.runner.BaseRunner.runBenchmark(BaseRunner.java:261)
        at org.openjdk.jmh.runner.BaseRunner.runBenchmark(BaseRunner.java:233)
        at org.openjdk.jmh.runner.BaseRunner.doSingle(BaseRunner.java:138)
        at org.openjdk.jmh.runner.BaseRunner.runBenchmarksForked(BaseRunner.java:75)
        at org.openjdk.jmh.runner.ForkedRunner.run(ForkedRunner.java:72)
        at org.openjdk.jmh.runner.ForkedMain.main(ForkedMain.java:86)
        Suppressed: java.lang.AssertionError: No trie for TernaryTrie
                at org.eclipse.jetty.util.TrieBenchmark.setUp(TrieBenchmark.java:75)
                at org.eclipse.jetty.util.jmh_generated.TrieBenchmark_testGet_jmhTest._jmh_tryInit_f_triebenchmark0_G(TrieBenchmark_testGet_jmhTest.java:438)
                at org.eclipse.jetty.util.jmh_generated.TrieBenchmark_testGet_jmhTest.testGet_Throughput(TrieBenchmark_testGet_jmhTest.java:71)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
                at java.base/java.lang.reflect.Method.invoke(Method.java:578)
                at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
                at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
                at java.base/java.lang.Thread.run(Thread.java:1589)```
