### ISSUE TITLE
Starting Javalin (which uses Jetty 11) on Android with compileSdk 33 crashing

### ISSUE THREAD

**Issue by kuwapa** [eclipse/jetty.project#9348]
I upgraded Javalin from 4.6.0 to 5.3.2 which uses Jetty 11 and since then, calling start() on Javalin instance, gives this error. The crash is happening on the Jetty server components hence I posted this issue here. 

```
java.lang.NoSuchFieldError: No static field SO_REUSEPORT of type Ljava/net/SocketOption; in class Ljava/net/StandardSocketOptions; or its superclasses (declaration of 'java.net.StandardSocketOptions' appears in /apex/com.android.art/javalib/core-oj.jar)
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:336)
at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304)
at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402)
at org.eclipse.jetty.server.Server$$ExternalSyntheticLambda2.accept(Unknown Source:4)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:203)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:185)
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:133)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:435)
at org.eclipse.jetty.server.Server.doStart(Server.java:398)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
at io.javalin.jetty.JettyServer.start(JettyServer.kt:74)
at io.javalin.Javalin.start(Javalin.java:171)
at io.javalin.Javalin.start(Javalin.java:148)
at com.pedalrhythm.javalintest.MainActivity.onCreate(MainActivity.kt:14)
at android.app.Activity.performCreate(Activity.java:8000)
at android.app.Activity.performCreate(Activity.java:7984)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

This is my Javalin code

```
val serverApp = Javalin.create().start(7000)
serverApp.get("/tiles") { ctx ->
    ctx.result("Hello")
}
```

This error was not happening on Javalin 4.6.7 which depends on Jetty 9. How can I fix this issue? Thanks

**Comment by olamy** [comment]
maybe you should first load an issue in the Javalin project https://github.com/javalin/javalin

**Comment by zugazagoitia** [comment]
> maybe you should first load an issue in the Javalin project https://github.com/javalin/javalin 

We've refered him here since the issue seems to be in the I/O operations performed by Jetty.

If you have any questions about Javalin or how we use Jetty we'd be happy to help.

**Comment by sbordet** [comment]
`StandardSocketOptions.SO_REUSEPORT` is there since Java 9.

Android SDK added this field in API level 33:
https://developer.android.com/reference/java/net/SocketOptions#SO_REUSEPORT

**Comment by kuwapa** [comment]
Thanks @sbordet for pointing that out. I just tried running the Javalin server on Android 13 and it worked without error.
