### ISSUE TITLE
Jetty 10.0.13 not a valid keystore error

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9349]
**Jetty version**
10.0.13
**Java version**
17
**Question**
I am getting below error on starting jetty any suggestion how can this be fixed
Exception in thread "main" java.lang.IllegalStateException: /opt/jetty/file:/opt/keystore/ckms_tls_keystore.jks is not a valid keystore
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:45)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1121)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:291)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:213)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:470)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:415)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1880)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)

**Comment by olamy** [comment]
it looks the path you configured is not correct `/opt/jetty/file:/opt/keystore/ckms_tls_keystore.jks`

**Comment by sushikarwasra** [comment]
@olamy location is correct i can see the .jks file is available at the location

**Comment by olamy** [comment]
> /opt/jetty/file:/opt/keystore/ckms_tls_keystore.jks

you mean `ls "/opt/jetty/file:/opt/keystore/ckms_tls_keystore.jks"` returns the file?? because the path doesn't look correct to me especially including `:`

**Comment by sushikarwasra** [comment]
this one open in ls /opt/keystore/ckms_tls_keystore.jks

**Comment by sbordet** [comment]
@sushikarwasra look more carefully at the file name.
