### ISSUE TITLE
RSA SSLJ fails to connect after upgrade to Jetty 10 and Java 11

### ISSUE THREAD

**Issue by Naziburjec** [eclipse/jetty.project#9384]
**Jetty version**
Jetty 10.0.12
**Java version**
JDK 11
**Question**
Jetty 10 throwing below exceptions while handshake. 
```
Caused by: java.io.IOException: Failed to setup the connection with agent on node memphis-straw.ecs.lab.emc.com
22:41:58      	at com.emc.caspian.fabric.installer.Tasks$SaySomething.sayErrorAndThrowIOException(Tasks.java:1118)
22:41:58      	at com.emc.caspian.fabric.installer.util.AgentConnectionManager.makeConnection(AgentConnectionManager.java:79)
22:41:58      	at com.emc.caspian.fabric.installer.util.AgentConnectionManager.makeConnection(AgentConnectionManager.java:89)
22:41:58      	at com.emc.caspian.fabric.installer.executor.HealthExecutor.validateAgentHealth(HealthExecutor.java:357)
22:41:58      	... 8 more
22:41:58      Caused by: java.io.IOException: Request failed. uri: https://memphis-straw.ecs.lab.emc.com:9240/
22:41:58      	at com.emc.caspian.fabric.client.HttpBackend.invoke(HttpBackend.java:133)
22:41:58      	at com.emc.caspian.fabric.client.ClientProxy$Handler.invoke(ClientProxy.java:88)
22:41:58      	at com.sun.proxy.$Proxy31.manifest(Unknown Source)
22:41:58      	at com.emc.caspian.fabric.agent.client.ClientV1$Agent.manifest(ClientV1.java:103)
22:41:58      	at com.emc.caspian.fabric.installer.util.AgentConnectionManager$AgentConnection.<init>(AgentConnectionManager.java:114)
22:41:58      	at com.emc.caspian.fabric.installer.util.AgentConnectionManager.makeConnection(AgentConnectionManager.java:70)
22:41:58      	... 10 more
22:41:58      Caused by: com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
22:41:58      	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
22:41:58      	at com.sun.jersey.api.client.Client.handle(Client.java:652)
22:41:58      	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
22:41:58      	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
22:41:58      	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
22:41:58      	at com.emc.caspian.fabric.client.HttpBackend.invoke(HttpBackend.java:96)
22:41:58      	... 15 more
22:41:58      Caused by: javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
22:41:58      	at com.rsa.sslj.x.aH.d(Unknown Source)
22:41:58      	at com.rsa.sslj.x.ap.a(Unknown Source)
22:41:58      	at com.rsa.sslj.x.ap.a(Unknown Source)
22:41:58      	at com.rsa.sslj.x.ap.j(Unknown Source)
22:41:58      	at com.rsa.sslj.x.ap.i(Unknown Source)
22:41:58      	at com.rsa.sslj.x.ap.h(Unknown Source)
22:41:58      	at com.rsa.sslj.x.aS.startHandshake(Unknown Source)
22:41:58      	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
22:41:58      	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
22:41:58      	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
22:41:58      	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
22:41:58      	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
22:41:58      	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
22:41:58      	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:253)
22:41:58      	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)
22:41:58      	... 20 more
``` 

If I check the agent or server status, it is showing below exceptions-
```
nile-2111-fec99ce-45:~ # systemctl status fabric-agent -l
* fabric-agent.service - fabric agent
   Loaded: loaded (/usr/lib/systemd/system/fabric-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2023-02-15 10:24:14 UTC; 2h 58min ago
  Process: 97487 ExecStartPre=/opt/emc/caspian/fabric/agent/bin/hs_dump_cleaner.sh (code=exited, status=0/SUCCESS)
  Process: 97485 ExecStartPre=/bin/rm -f /var/run/fabric-agent.pid (code=exited, status=0/SUCCESS)
 Main PID: 97494 (java)
    Tasks: 109 (limit: 4096)
   Memory: 276.9M (limit: 3.0G)
      CPU: 4min 36.287s
   CGroup: /system.slice/fabric-agent.service

Feb 15 10:31:13 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:31:13.856:WARN :oeji.ManagedSelector:qtp1701798620-1554: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:31:43 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:31:43.865:WARN :oeji.ManagedSelector:qtp1701798620-1555: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:32:13 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:32:13.870:WARN :oeji.ManagedSelector:qtp1701798620-1555: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:32:43 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:32:43.874:WARN :oeji.ManagedSelector:qtp1701798620-1555: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:33:13 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:33:13.880:WARN :oeji.ManagedSelector:qtp1701798620-1556: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:33:43 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:33:43.883:WARN :oeji.ManagedSelector:qtp1701798620-1556: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:34:13 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:34:13.887:WARN :oeji.ManagedSelector:qtp1701798620-1556: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:34:43 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:34:43.892:WARN :oeji.ManagedSelector:qtp1701798620-1837: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:35:13 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:35:13.896:WARN :oeji.ManagedSelector:qtp1701798620-1837: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException
Feb 15 10:35:43 nile-2111-fec99ce-45 fabric-agent[97494]: 2023-02-15 10:35:43.901:WARN :oeji.ManagedSelector:qtp1701798620-1837: Could not accept java.nio.channels.SocketChannel[closed]: java.lang.UnsupportedOperationException

``` 

Any suggestions or help on this issue?

**Comment by gregw** [comment]
Not a lot for us to go on there.    We'd need to see the stack trace of that UnsupportedOperationException to start with. Turning debug on in org.eclipse.jetty.io.ManagedSelector will give out the stack trace

**Comment by Naziburjec** [comment]
Hi @gregw please find the logs from below link.

https://github.com/Naziburjec/logs/blob/main/README.md

**Comment by gregw** [comment]
@Naziburjec That is not the debug log info I needed.  That appears to be SSL related debug (including some key information, which if that was for a live key you have just published on a public forum).

See https://www.eclipse.org/jetty/documentation/jetty-11/operations-guide/index.html#og-server-logging-server

**Comment by joakime** [comment]
The problem isn't in Jetty, it's in your `com.rsa.sslj.x.aS.startHandshake`.

This seems like a duplicate of Issue #4961  

Your extra (and non-standard) security providers (RSA) likely have to be upgraded as well.

**Comment by sbordet** [comment]
No reply for OP, closing.
