### ISSUE TITLE
Error are printed as warning in jetty classes

### ISSUE THREAD

**Issue by jimit1210** [eclipse/jetty.project#942]
Hi,

We had issue when java OutOfMemoryError printed as warning in logs and it wasn't caught by monitoring tools. Can you please enhance the catch to log exception as warning and error as error.

Code:
http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.jetty/jetty-util/9.3.2.v20150730/org/eclipse/jetty/util/thread/QueuedThreadPool.java#QueuedThreadPool

   catch (InterruptedException e)
623            {
624                ignore=true;
625                LOG.ignore(e);
626            }
627            catch (Throwable e)
628            {
629                LOG.warn(e);
630            }

Actual Exception Trace:
016-09-14 07:13:18.202  WARN 508 --- [qtp66033352-2837] o.e.jetty.util.thread.QueuedThreadPool   :

java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1855) ~[na:1.8.0_45]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2068) ~[na:1.8.0_45]
        at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:389) ~[jetty-util-9.2.14.v20151106.jar!/:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:531) ~[jetty-util-9.2.14.v20151106.jar!/:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.access$700(QueuedThreadPool.java:47) ~[jetty-util-9.2.14.v20151106.jar!/:9.2.14.v20151106]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:590) ~[jetty-util-9.2.14.v20151106.jar!/:9.2.14.v20151106]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by joakime** [comment]
We don't have an ERROR level in our logging.
Never had.

http://download.eclipse.org/jetty/9.3.12.v20160915/apidocs/org/eclipse/jetty/util/log/Logger.html

Also note, its not possible to catch and log `java.lang.OutOfMemoryError` in code.

See example project at https://github.com/jetty-project/jetty-oome for more details.
