### ISSUE TITLE
Make QuickStartConfiguration check optional

### ISSUE THREAD

**Issue by mvysny** [eclipse/jetty.project#9514]
**Jetty version(s)**
11.0.14

**Enhancement Description**
It's possible to use Jetty with native and GraalVM when using Jetty QuickStart. Unfortunately, there's a check at `QuickStartConfiguration:99` which always fails in native, with `IllegalStateException("Bad Quickstart location")`.

The reason is as follows: the `context.getBaseResource()` needs to reference a resource directory packaged within the native image. The webroot is placed into classpath resource named `/webapp`. Te `/webapp` folder resolves to URL `resource:/webapp` which then resolves to plain `URLResource` (and not a `JarResource` since there's no URLClassLoader and no jars in native). Plain `URLResource` will always return false for the `isDirectory()` probe, hence the exception.

It would be good if the check could be turned off optionally, for example via a context attribute.

**Comment by mvysny** [comment]
Steps to reproduce (I'm using Ubuntu 22.10):

1. Install GraalVM as per https://graalvm.github.io/native-build-tools/latest/gradle-plugin-quickstart.html
2. `git clone https://github.com/mvysny/vaadin-boot-example-gradle`
3. `git checkout native`
4. `./gradlew clean build nativeCompile -Pvaadin.productionMode`
5. `cd build/native/nativeCompile/`
6. Run the `vaadin-boot-example-gradle` binary

You should see the following exception:

```
2023-03-16 13:32:47.747 [main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@1da6646c{/,resource:/webapp,STOPPED}{resource:/webapp}
java.lang.IllegalStateException: Bad Quickstart location
	at org.eclipse.jetty.quickstart.QuickStartConfiguration.preConfigure(QuickStartConfiguration.java:95)
	at org.eclipse.jetty.webapp.Configurations.preConfigure(Configurations.java:496)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:510)
```
