### ISSUE TITLE
Noisy logging (warn + exception) when client disconnects mid-request

### ISSUE THREAD

**Issue by shaunbrockhoff-wk** [eclipse/jetty.project#9525]
**Jetty version**
11.0.14

**Java version**
Java 17 / Corretto

**Question**
Starting with version 11.0.14, we started seeing a new warning in our logs, all similar to:
```
message: Failed callback
exception: {
     message: Close SendCallback@25ab745e[PENDING][i=null,cb=null] in state PENDING
     stacktrace: java.io.IOException: Close SendCallback@25ab745e[PENDING][i=null,cb=null] in state PENDING
 at org.eclipse.jetty.util.IteratingCallback.close(IteratingCallback.java:458)
 at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:551)
 at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:330)
 at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:1113)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
 at java.base/java.lang.Thread.run(Thread.java:833)

     type: java.io.IOException
   }
name: org.eclipse.jetty.io.AbstractConnection
```

This appears to be logged any time a client disconnects in the middle of a request.
We wanted to avoid logging these exceptions, so we currently suppress the `org.eclipse.jetty.io.EofException` (stacktrace below) using an approach similar to [this](https://stackoverflow.com/questions/26752880/clientabortexception-when-using-jersey-2-13/39006980#39006980). However, there does not appear to be a good way to suppress this new warning log. Do you have any suggestions on how we can avoid this logged warning? Note that if we disable our custom filter that suppresses the `EofException`, then we do get both the logged warning and the exception.

<details>
  <summary>Stacktrace</summary>

```
  message: org.eclipse.jetty.io.EofException
     stacktrace: org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
 at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:67)
 at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
 at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
 at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:677)
 at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:385)
 at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:375)
 at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:264)
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
 at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
 at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
 at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
 at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
 at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
 at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
 at jakarta.servlet.http.HttpFilter.doFilter(HttpFilter.java:126)
 at org.my.LoggingFilter.doFilter(LoggingFilter.java:25)
 at jakarta.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)
 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
 at org.my.HeaderFilter.doFilter(HeaderFilter.java:42)
 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1382)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304)
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
 at org.eclipse.jetty.server.Server.handle(Server.java:563)
 at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
 at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
 at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
 at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.jetty.io.EofException: null
 at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:116)
 at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
 at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:377)
 at org.eclipse.jetty.io.SelectableChannelEndPoint$2.run(SelectableChannelEndPoint.java:67)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:370)
 ... 6 common frames omitted
Caused by: java.io.IOException: Broken pipe
 at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
 at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66)
 at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:217)
 at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:153)
 at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:563)
 at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:642)
 at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:110)
 ... 11 common frames omitted
```

</details>

I believe the behavior was introduced with [this change](https://github.com/eclipse/jetty.project/pull/9062/commits/967629b2846bee415bd3445ba177895f0ddee916).

**Comment by joakime** [comment]
This appears to be a warning level log.

https://github.com/eclipse/jetty.project/blob/jetty-11.0.14/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java#L85-L95
https://github.com/eclipse/jetty.project/blob/4601fe8dd805ce75b69c64466c115a162586641b/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java#L85-L95

**Comment by gregw** [comment]
We should probably try to throw QuietException if possible and check for it here.

**Comment by gregw** [comment]
We are actually throwing a QuietException already, but a) it is wrapped by jersey into a normal IOException, and b) we are not checking for it anyway in AbstractConnection.

We should probably add a utility method to ExceptionUtil that checks if an exception or any of its causes are QuietException.  We should then use it in places like above where we log exceptions.
