### ISSUE TITLE
Insufficient documentation on required build tools

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#9536]
**Jetty version(s)**
10

**OS type/version**
linux

**Description**

Doing a full build from the command line results in the following error:
```
[INFO] asciidoctor: DEBUG: Finding 'dot' in attributes
[INFO] asciidoctor: DEBUG: Finding 'dot' in environment
java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at java.base/java.lang.Runtime.exec(Runtime.java:594)
        at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:159)
        at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:119)
        at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:76)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 5 more
```

I believe there is some optional third party documentation system that I need to install to resolve this, but nothing is documented in README.md

**How to reproduce?**

Do a full build

**Comment by gregw** [comment]
@sbordet @joakime @olamy Not sure who is best to document the documentation build system.  Can one of you claim this issue and add a few lines in the README.md about what is needed.

**Comment by joakime** [comment]
I'll work on the README for `jetty-10.0.x` (onwards)

Meanwhile ...
`dot` is a binary from the `graphviz` toolkit.

It is used in the `jetty-documentation` portion of the build.
I thought we setup the `dot` tooling to be optional? (have to look into this)

**Comment by olamy** [comment]
yes It should be optional but generate warning/info/debug (noise?) only in the build output.
if this breaks the build it's definitely a bug

**Comment by gregw** [comment]
Yeah it is optional. Not breaking the build. Just adding noise whilst I'm looking at other build exceptions.

Also i forgot it was graphviz - thanks

**Comment by olamy** [comment]
fixed with https://github.com/eclipse/jetty.project/pull/9545
