### ISSUE TITLE
testParallelContentSourceListenersTotalFailure succeeds with ISE?

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#9538]
**Jetty version(s)**
12

**Description**

When running `org.eclipse.jetty.test.client.transport.HttpClientTest#testParallelContentSourceListenersTotalFailure`

```
2023-03-26 00:00:34.401:INFO :oejct.ResponseListeners:client-11045: Exception while notifying listener org.eclipse.jetty.test.client.transport.HttpClientTest$$Lambda$1063/0x0000000800f8f808@775f1f66
java.lang.IllegalStateException
        at org.eclipse.jetty.client.transport.HttpReceiver$ContentSource.demand(HttpReceiver.java:672)
        at org.eclipse.jetty.client.transport.ResponseListeners$ContentSourceDemultiplexer.registerFailure(ResponseListeners.java:469)
        at org.eclipse.jetty.client.transport.ResponseListeners$ContentSourceDemultiplexer$ContentSource.fail(ResponseListeners.java:626)
        at org.eclipse.jetty.test.client.transport.HttpClientTest.lambda$testParallelContentSourceListenersTotalFailure$34(HttpClientTest.java:1015)
        at org.eclipse.jetty.client.transport.ResponseListeners.notifyContentSource(ResponseListeners.java:229)
        at org.eclipse.jetty.client.transport.ResponseListeners$ContentSourceDemultiplexer.onContentSource(ResponseListeners.java:432)
        at org.eclipse.jetty.client.transport.ResponseListeners.notifyContentSource(ResponseListeners.java:229)
        at org.eclipse.jetty.client.transport.ResponseListeners.notifyContentSource(ResponseListeners.java:196)
        at org.eclipse.jetty.client.transport.HttpReceiver.lambda$responseHeaders$2(HttpReceiver.java:288)
        at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
        at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:117)
        at org.eclipse.jetty.client.transport.HttpReceiver.responseHeaders(HttpReceiver.java:236)
        at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.lambda$headerComplete$2(HttpReceiverOverHTTP.java:435)
        at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:320)
        at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:250)
        at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:76)
        at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
        at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Several issues with this:
 + Should exceptions ever be logged at INFO level? Should this not be a WARN?
 + Should be ever be generating an ISE in this circumstance?
 + If the exception is expected during tests, then the stack should be suppressed.

**Comment by joakime** [comment]
Merged #9543
