### ISSUE TITLE
org.eclipse.jetty.test.client.transport.HttpClientTimeoutTest#testTimeoutOnFuture  H3 logs exception

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.project#9539]
**Jetty version(s)**
12

**Description**

When running `org.eclipse.jetty.test.client.transport.HttpClientTimeoutTest#testTimeoutOnFuture` the h3 variant logs the following exception:

```
2023-03-26 00:01:43.118:WARN :oejs.Response:server-12311: writeError: status=500, message=java.io.IOException: close, response=org.eclipse.jetty.server.internal.HttpChannelState$ErrorResponse@4d1c9506
java.io.IOException: close
        at org.eclipse.jetty.http3.HTTP3Session.failStreams(HTTP3Session.java:721)
        at org.eclipse.jetty.http3.HTTP3Session.onClose(HTTP3Session.java:840)
        at org.eclipse.jetty.http3.server.internal.ServerHTTP3Session.onClose(ServerHTTP3Session.java:189)
        at org.eclipse.jetty.quic.common.ProtocolSession$StreamsProducer.produce(ProtocolSession.java:236)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:507)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:253)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
        at org.eclipse.jetty.quic.common.ProtocolSession.produce(ProtocolSession.java:78)
        at org.eclipse.jetty.quic.server.ServerProtocolSession.lambda$new$0(ServerProtocolSession.java:31)
        at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:436)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
        at org.eclipse.jetty.quic.common.QuicConnection.onFillable(QuicConnection.java:164)
        at org.eclipse.jetty.quic.common.QuicConnection$FillableCallback.succeeded(QuicConnection.java:425)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:436)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:136)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Is this exception expected? If so the test needs to suppress the stack trace.
Why is this only in h3?

**Comment by gregw** [comment]
Note there are several variations of this verbose test stacktrace.  e.g.:
```
Running org.eclipse.jetty.test.client.transport.HttpClientTimeoutTest.testTimeoutOnListenerWithExplicitConnection([5] H3)
2023-03-26 00:03:10.517:INFO :oejs.Server:main: jetty-12.0.0-SNAPSHOT; built: 2023-03-25T22:39:18.027Z; git: 9d69760aa4ac7dd894d2fb83dd9c8d74333ac7e0; jvm 17.0.6+10-Ubuntu-0ubuntu122.04
2023-03-26 00:03:10.520:INFO :oejhs.HTTP3ServerConnector:main: HTTP/3+QUIC support is experimental and not suited for production use.
2023-03-26 00:03:10.544:INFO :oejus.SslContextFactory:main: x509=X509@4468c0ea(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Server@41cf4272[provider=null,keyStore=file:///home/gregw/src/jetty-12.0.x/jetty-core/jetty-tests/jetty-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
2023-03-26 00:03:10.551:INFO :oejs.AbstractConnector:main: Started HTTP3ServerConnector@53d2b827{h3, (h3)}{0.0.0.0:34916}
2023-03-26 00:03:10.569:INFO :oejs.Server:main: Started oejs.Server@105fe81e{STARTING}[12.0.0-SNAPSHOT,sto=0] @516651ms
2023-03-26 00:03:10.569:INFO :oejhc.HTTP3Client:main: HTTP/3+QUIC support is experimental and not suited for production use.
2023-03-26 00:03:10.587:INFO :oejus.SslContextFactory:main: x509=X509@38363e96(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Client@35c95869[provider=null,keyStore=file:///home/gregw/src/jetty-12.0.x/jetty-core/jetty-tests/jetty-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
2023-03-26 00:03:10.595:WARN :oejusS.config:main: No Client EndPointIdentificationAlgorithm configured for Client@35c95869[provider=null,keyStore=file:///home/gregw/src/jetty-12.0.x/jetty-core/jetty-tests/jetty-test-client-transports/src/test/resources/keystore.p12,trustStore=null]
2023-03-26 00:03:11.609:INFO :oejs.Server:main: Stopped oejs.Server@105fe81e{STOPPING}[12.0.0-SNAPSHOT,sto=0]
2023-03-26 00:03:11.610:INFO :oejs.AbstractConnector:main: Stopped HTTP3ServerConnector@53d2b827{h3, (h3)}{0.0.0.0:34916}
2023-03-26 00:03:12.605:WARN :oejs.Response:server-13133: writeError: status=500, message=java.io.IOException: close, response=org.eclipse.jetty.server.internal.HttpChannelState$ErrorResponse@40a190ac
java.io.IOException: close
        at org.eclipse.jetty.http3.HTTP3Session.failStreams(HTTP3Session.java:721)
        at org.eclipse.jetty.http3.HTTP3Session.onClose(HTTP3Session.java:840)
        at org.eclipse.jetty.http3.server.internal.ServerHTTP3Session.onClose(ServerHTTP3Session.java:189)
        at org.eclipse.jetty.quic.common.ProtocolSession$StreamsProducer.produce(ProtocolSession.java:236)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:507)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:253)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
        at org.eclipse.jetty.quic.common.ProtocolSession.produce(ProtocolSession.java:78)
        at org.eclipse.jetty.quic.server.ServerProtocolSession.lambda$new$0(ServerProtocolSession.java:31)
        at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:436)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
        at org.eclipse.jetty.quic.common.QuicConnection.onFillable(QuicConnection.java:164)
        at org.eclipse.jetty.quic.common.QuicConnection$FillableCallback.succeeded(QuicConnection.java:425)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:436)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:136)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
        at java.base/java.lang.Thread.run(Thread.java:833)
Suppressed:
        |java.io.IOException: close
        |       at org.eclipse.jetty.http3.HTTP3Session.failStreams(HTTP3Session.java:721)
        |       at org.eclipse.jetty.http3.HTTP3Session.inwardClose(HTTP3Session.java:669)
        |       at org.eclipse.jetty.http3.server.internal.ServerHTTP3Session.inwardClose(ServerHTTP3Session.java:175)
        |       at org.eclipse.jetty.quic.common.QuicSession.inwardClose(QuicSession.java:396)
        |       at org.eclipse.jetty.quic.common.QuicConnection.close(QuicConnection.java:188)
        |       at org.eclipse.jetty.util.IO.close(IO.java:460)
        |       at org.eclipse.jetty.io.ManagedSelector$CloseConnections.update(ManagedSelector.java:1014)
        |       at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processUpdates(ManagedSelector.java:566)

```

**Comment by joakime** [comment]
@sbordet the fixes in these commits have introduced another flaky `jetty-12.0.x` test.

* org.eclipse.jetty.http3.tests.GoAwayTest.testServerStop

``` 
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
	at org.eclipse.jetty.http3.tests.GoAwayTest.testServerStop(GoAwayTest.java:1239)
```

* org.eclipse.jetty.http2.tests.StreamResetTest.testClientResetConsumesQueuedData

```
Expected: a value greater than <0>
     but: <0> was equal to <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.http2.tests.StreamResetTest.testClientResetConsumesQueuedData(StreamResetTest.java:460)
```

**Comment by sbordet** [comment]
@joakime those failures are unrelated.
I opened https://github.com/eclipse/jetty.project/pull/9548 for the latter.
