### ISSUE TITLE
AnnotationParser cannot scan Java 20 class files (Unsupported class file major version 64) due to outdated asm dependency

### ISSUE THREAD

**Issue by knaccc** [eclipse/jetty.project#9613]
**Jetty version(s)**
Jetty 11.0.11

**Java version/vendor** `(use: java -version)`
```
openjdk version "20" 2023-03-21
OpenJDK Runtime Environment (build 20+36-2344)
OpenJDK 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)
```

**OS type/version**
All

**Description**
Jetty runs fine under OpenJDK 20. However, it is incompatible with class files compiled with JDK20. The jetty.log output is shown below.

Workaround: compile code under JDK19 instead of JDK20.

This can be fixed if Jetty upgrades to to the latest org.objectweb.asm code, where they have fixed this (commit [here](https://gitlab.ow2.org/asm/asm/-/commit/8b7090dc7fc280aeff270473658766179cb2024b))

```
java.lang.IllegalArgumentException: Unsupported class file major version 64
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:896)
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:795)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:730)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:170)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:551)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by knaccc** [comment]
Oops, I thought I was on the latest Jetty release, but I wasn't. Please delete this issue.
