### ISSUE TITLE
Flakey test `QueuedThreadPoolTest.testThreadPool`

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#9622]
**Jetty version(s)**
10.0.x, 11.0.x, 12.0.x

**Description**
`QueuedThreadPoolTest.testThreadPool` started failing with

```
Expected: is <0>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.util@11.0.15-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPoolTest.waitForIdle(QueuedThreadPoolTest.java:714)
	at org.eclipse.jetty.util@11.0.15-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPoolTest.testThreadPool(QueuedThreadPoolTest.java:305)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
```

**Comment by lorban** [comment]
Fixed in 10, merged to 11 and 12.
