### ISSUE TITLE
Jetty 12 Flaky test org.eclipse.jetty.ee10.servlets.CloseableDoSFilterTest.testEvenLowRateIP

### ISSUE THREAD

**Issue by olamy** [eclipse/jetty.project#9654]
Tests `org.eclipse.jetty.ee10.servlets.CloseableDoSFilterTest.testEvenLowRateIP` sounds flaky.

```
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
	at org.eclipse.jetty.ee10.servlets@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlets.AbstractDoSFilterTest.testEvenLowRateIP(AbstractDoSFilterTest.java:159)
```

**Comment by olamy** [comment]
tests marked as flaky and not executed anymore in CI https://github.com/eclipse/jetty.project/pull/9930
