### ISSUE TITLE
 org.eclipse.jetty.io.EofException: null  Suppressed: javax.net.ssl.SSLHandshakeException: null

### ISSUE THREAD

**Issue by patpatpat123** [eclipse/jetty.project#9753]
**Jetty version(s)**
Latest Jetty from Maven as of this writing

**Java version/vendor** `(use: java -version)`
Java 17

**OS type/version**
Issue observed for Windows Unix and Mac

**Description**
I have a very simple reactive project and a jetty http client configured as such:
```
@Bean
    public WebClient webClient(final WebClient.Builder builder) {
        final var sslContextFactory = new SslContextFactory.Client();
        sslContextFactory.setSslContext(getMyCustomSSLContext());
        final var clientConnector = new ClientConnector();
        clientConnector.setSslContextFactory(sslContextFactory);
        final var httpClient = new HttpClient(new HttpClientTransportDynamic(clientConnector));
        return builder.baseUrl(hostAndPort).defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE).clientConnector(new JettyClientHttpConnector(httpClient)).build();
    }
```

reproducible 100% of the time, I am getting this issue while sending requests at high load to a third party server.
The third party server is handling correct requests to others clients when I am failing with this:

```
2023-05-10 09:59:46 1 ERROR --- [HttpClient@787e4357-88] [,] reactor.core.publisher.Operators : Operator called default onErrorDropped
org.springframework.web.reactive.function.client.WebClientRequestException: null
        at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ? Request to POST null [DefaultWebClient]
Original Stack Trace:
                at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
                at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
                at org.eclipse.jetty.reactive.client.internal.AbstractSingleProcessor.onError(AbstractSingleProcessor.java:120)
                at org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.onComplete(ResponseListenerProcessor.java:141)
                at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:213)
                at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:205)
                at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:477)
                at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:457)
                at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:553)
                at org.eclipse.jetty.client.HttpReceiver.responseFailure(HttpReceiver.java:449)
                at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.failAndClose(HttpReceiverOverHTTP.java:428)
                at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:208)
                at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:91)
                at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
                at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194)
                at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1599)
                at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:291)
                at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254)
                at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:386)
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.needsFillInterest(SslConnection.java:923)
                at org.eclipse.jetty.io.AbstractEndPoint$1.needsFillInterest(AbstractEndPoint.java:45)
                at org.eclipse.jetty.io.FillInterest.tryRegister(FillInterest.java:78)
                at org.eclipse.jetty.io.FillInterest.register(FillInterest.java:50)
                at org.eclipse.jetty.io.AbstractEndPoint.fillInterested(AbstractEndPoint.java:367)
                at org.eclipse.jetty.io.AbstractConnection.fillInterested(AbstractConnection.java:135)
                at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.fillInterested(HttpReceiverOverHTTP.java:269)
                at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:192)
                at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:91)
                at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
                at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194)
                at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
                at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
                at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
                at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
                at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
                at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
                at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
                at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
                at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
                at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
                at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
                at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.jetty.io.EofException: null
        at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:116)
        at org.eclipse.jetty.io.ssl.SslConnection.networkFlush(SslConnection.java:486)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1115)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:661)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:180)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:91)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint$IncompleteWriteCallback.succeeded(SslConnection.java:1599)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:291)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:386)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.needsFillInterest(SslConnection.java:923)
        at org.eclipse.jetty.io.AbstractEndPoint$1.needsFillInterest(AbstractEndPoint.java:45)
        at org.eclipse.jetty.io.FillInterest.tryRegister(FillInterest.java:78)
        at org.eclipse.jetty.io.FillInterest.register(FillInterest.java:50)
        at org.eclipse.jetty.io.AbstractEndPoint.fillInterested(AbstractEndPoint.java:367)
        at org.eclipse.jetty.io.AbstractConnection.fillInterested(AbstractConnection.java:135)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.fillInterested(HttpReceiverOverHTTP.java:269)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:192)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:91)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: org.eclipse.jetty.io.EofException: null
                at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:116)
                at org.eclipse.jetty.io.ssl.SslConnection.networkFlush(SslConnection.java:486)
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1115)
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doShutdownOutput(SslConnection.java:1338)
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doClose(SslConnection.java:1434)
                at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:258)
                at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:227)
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1204)
                ... 38 common frames omitted
        Caused by: java.io.IOException: Broken pipe
                at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
                at java.base/sun.nio.ch.SocketDispatcher.writev(Unknown Source)
                at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
                at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
                at java.base/sun.nio.ch.SocketChannelImpl.write(Unknown Source)
                at java.base/java.nio.channels.SocketChannel.write(Unknown Source)
                at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:110)
                ... 45 common frames omitted
        Suppressed: javax.net.ssl.SSLHandshakeException: null
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.handshakeFailed(SslConnection.java:962)
                at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1192)
                ... 38 common frames omitted
        Caused by: [CIRCULAR REFERENCE: org.eclipse.jetty.io.EofException: null]
Caused by: java.io.IOException: Broken pipe
        at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.writev(Unknown Source)
        at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
        at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.write(Unknown Source)
        at java.base/java.nio.channels.SocketChannel.write(Unknown Source)
        at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:110)
        ... 40 common frames omitted
```

Could you please help on this issue?

**Comment by joakime** [comment]
What version of Jetty?

**Comment by joakime** [comment]
```
                at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
                at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
                at org.eclipse.jetty.reactive.client.internal.AbstractSingleProcessor.onError(AbstractSingleProcessor.java:120)
                at org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.onComplete(ResponseListenerProcessor.java:141)
```

This looks like the reactive httpclient, this should be filed at https://github.com/jetty-project/jetty-reactive-httpclient

**Comment by patpatpat123** [comment]
Understood, thank you and closing. Good day!
