### ISSUE TITLE
org.eclipse.jetty.io.EofException: Reset cancel_stream_error when using firefox 

### ISSUE THREAD

**Issue by shanszhao** [eclipse/jetty.project#9763]
**Jetty version(s)**
 10.0.12

**Java version/vendor** `(use: java -version)`
11.0.19

**OS type/version**
 macos 12.6.2 

**Description**
When reloading a web page,  using Firefox 102.11.0esr (64-bit), the exception occurs 

org.eclipse.jetty.io.EofException: Reset cancel_stream_error
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:163)
	at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:843)
	at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:553)
	at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:383)
	at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:320)
	at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onReset(Parser.java:367)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyReset(BodyParser.java:139)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.onReset(ResetBodyParser.java:92)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.parse(ResetBodyParser.java:61)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:193)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:122)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:110)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:278)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:455)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:248)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
	at java.base/java.lang.Thread.run(Thread.java:834)

 
**How to reproduce?**
 It cannot be reproduced on Chrome, only Firefox,  refreshing HTTPS a couple of times, this error occurs

**Comment by sbordet** [comment]
That's normal, as the browser sends a RST_STREAM frame for the in-flight request that is cancelled because of the refresh.

The exception is also a "quiet" one, so I don't understand what problem are you reporting?

**Comment by shanszhao** [comment]
> That's normal, as the browser sends a RST_STREAM frame for the in-flight request that is cancelled because of the refresh.
> 
> The exception is also a "quiet" one, so I don't understand what problem are you reporting?

I hope I interpret the “quiet” correctly . Every time the page refreshes, it prints out the long exception stack trace and fills our log. It causes a lot noise. If it is normal , I wonder the purpose of throwing exception with stack trace except. There is other similar bug also reported in different java framework https://github.com/vaadin/flow/issues/16311 . 
the very least we should be able to turn of the exception, and should not be a warning if there is no actions required.

**Comment by sbordet** [comment]
It is "quiet" in this sense: `org.eclipse.jetty.io.EofException implements QuietException`.
We do not log `QuietExceptions` if not at DEBUG level.

If that's not the case, we need evidence. 
Can you share your logs?

**Comment by shanszhao** [comment]
In our context, we’re using Eclipse Jetty as an embedded web server and are catching the exception. Will handle it as a QuietException going forward.
