### ISSUE TITLE
Flaky test  testBlockingReadInADifferentThread - org.eclipse.jetty.http3.tests.DataDemandTest

### ISSUE THREAD

**Issue by janbartel** [eclipse/jetty.project#9765]
**jetty-12**

https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-9764/1/tests

**Comment by lorban** [comment]
Reproduced, the root cause seems to be this exception:
```
2023-05-22 17:26:51.680:DEBUG:oejh.HTTP3StreamConnection:Thread-442: parse+fill failure on ServerHTTP3StreamConnection@399b20a5::QuicStreamEndPoint@321a6ad5#0[{l=/[0:0:0:0:0:0:0:0]:56685,r=/127.0.0.1:50592,OPEN,fill=-,flush=-,to=7/0}]->[ServerHTTP3StreamConnection@399b20a5[dataMode=true,stream=HTTP3StreamServer@1671f0ed#0[demand=false,stalled=true,last=false,idle=-29999,session=HTTP3SessionServer@69e9fa12[streams=1,NOT_CLOSED]]]]
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.getByteBuffer()" because "this.networkBuffer" is null
	at org.eclipse.jetty.http3.HTTP3StreamConnection.parseAndFill(HTTP3StreamConnection.java:280)
	at org.eclipse.jetty.http3.HTTP3StreamConnection.processDataFrames(HTTP3StreamConnection.java:116)
	at org.eclipse.jetty.http3.HTTP3StreamConnection.receive(HTTP3StreamConnection.java:239)
	at org.eclipse.jetty.http3.HTTP3Stream.readData(HTTP3Stream.java:176)
	at org.eclipse.jetty.http3.tests.DataDemandTest$22.lambda$onRequest$0(DataDemandTest.java:492)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
