### ISSUE TITLE
Jetty version 9.4.45.v20220203 returning java.lang.UnsupportedOperationException during Handshake

### ISSUE THREAD

**Issue by baljeetsingh79** [eclipse/jetty.project#9780]
**Jetty version(s)**
_[Jetty 9.x is now at End of Community Support](https://github.com/eclipse/jetty.project/issues/7958)_
Jetty -- version 9.4.45.v20220203

**Java version/vendor** `(use: java -version)`java -version 8

**OS type/version** Linux

**Description**
_Do not report security issues here! See [Jetty Security Reports](https://www.eclipse.org/jetty/security_reports.php)._
Jetty version 9.4.45.v20220203 returning java.lang.UnsupportedOperationException during Handshake. If Oracle jdk (version 8) is FIPS (Federal Information Processing Standard) enabled then handshake is failing with java.lang.UnsupportedOperationException exception even though JSSE provider is of JDK 8 only. It is working fine for Non FIPS enabled environments. When jetty HTTP client calls for handshake using JettyHttpClientTransport class with default SSL context factory (SslContextFactory.Client()) to Jetty Server it fails with java.lang.UnsupportedOperationException). Following is the stack trace->
org.cometd.client.http.jetty.JettyHttpClientTransport$ResponseListener.onComplete(JettyHttpClientTransport.java:277)
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
    at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:276)
    at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:247)
    at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:164)
    at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:819)
    at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:502)
    at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:252)
    at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.failed(AbstractConnectionPool.java:570)
    at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:136)
    at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:633)
    at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.connectFailed(AbstractConnectorHttpClientTransport.java:138)
    at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.connectionFailed(AbstractConnectorHttpClientTransport.java:188)
    at org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:966)
    at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:1077)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)

**How to reproduce?**
Jetty version 9.4.45.v20220203 returning java.lang.UnsupportedOperationException during Handshake. If Oracle jdk (version 8) is FIPS (Federal Information Processing Standard) enabled then handshake is failing with java.lang.UnsupportedOperationException exception even though JSSE provider is of JDK 8 only.

**Comment by gregw** [comment]
Jetty-9 is end-of-life for community support. Please read https://github.com/eclipse/jetty.project/issues/7958
