### ISSUE TITLE
HttpClient should report HTTP/2 INADEQUATE_SECURITY_ERROR better

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#980]
Currently, when using HttpClient with HTTP/2 and attempting to connect to an HTTP/2 server which sends a GO_AWAY / INADEQUATE_SECURITY_ERROR the HttpClient fails with a simple stacktrace showing ...

```
Caused by: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
    at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
    at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
    at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:652)
    at my code
    ... 34 more
Caused by: java.nio.channels.ClosedChannelException
    at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:498)
    at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onIncompleteFlush(SslConnection.java:409)
    at org.eclipse.jetty.io.AbstractEndPoint$2.onIncompleteFlush(AbstractEndPoint.java:54)
    at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
    at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140)
    at org.eclipse.jetty.http2.HTTP2Flusher.process(HTTP2Flusher.java:243)
    at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
    at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:365)
    at org.eclipse.jetty.http2.HTTP2Flusher.succeeded(HTTP2Flusher.java:258)
    at org.eclipse.jetty.io.WriteFlusher$PendingState.complete(WriteFlusher.java:269)
    at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394)
    at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:101)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    ... 1 more
```

This is a feature request to have the exception be more clear as to why the connection attempt was closed.

Is it possible to have a special Http2Exception or Http2GoAwayException that can indicate that the reason for the closed connection was due to the protocol / server saying so?  
Perhaps even having the message of this exception indicate the INADEQUATE_SECURITY_ERROR piece?

I imagine a stack like this ...

```
Http2GoAwayException: Protocol reported INADEQUATE_SECURITY_ERROR
    at org.eclipse. ...
    ... 13 more
Caused by: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
    at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
    ... 34 more
Caused by: java.nio.channels.ClosedChannelException
    at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:498)
    at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onIncompleteFlush(SslConnection.java:409)
    ... 26 more
```

**Comment by sbordet** [comment]
This is not always possible. The GOAWAY frame is received on the read side by the HTTP/2 code.

The failure reported above comes from the write side in the Jetty TLS code.

When the TLS code receives an IOException, it cannot query some other part of the system to see if the close came with some additional information, and if so report that information.

To get more information about the GOAWAY frames, see #389 and #396.
