### ISSUE TITLE
Flaky test AsyncServletIOTest.testStolenAsyncRead

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#9875]
**Jetty version(s)**
12

**Description**
Assertion failed with:
```
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
	at org.eclipse.jetty.ee10.servlet@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncServletIOTest.testStolenAsyncRead(AsyncServletIOTest.java:839)
```

and stderr containing:

```
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at org.eclipse.jetty.ee10.servlet@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncServletIOTest.lambda$testStolenAsyncRead$0(AsyncServletIOTest.java:824)
	at org.eclipse.jetty.util@12.0.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util@12.0.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util@12.0.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at org.eclipse.jetty.ee10.servlet@12.0.0-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncServletIOTest.lambda$testStolenAsyncRead$0(AsyncServletIOTest.java:824)
	at org.eclipse.jetty.util@12.0.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util@12.0.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util@12.0.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

See https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1253/testReport/junit/org.eclipse.jetty.ee10.servlet/AsyncServletIOTest/Parallel_Stage___Build___Test___JDK19___testStolenAsyncRead/

**Comment by strogiyotec** [comment]
Hello @lorban  I tried to contribute and work on this ticket
I couldn't reproduce the bug with 
```
OpenJDK Runtime Environment Corretto-17.0.7.7.1
mvn test
```
Checking the Jenkins I noticed it uses JDK 19 , just curious why Jenkins uses non LTS JDK ? 
(I will try to replicate the test with JDK 19 later on)

**Comment by lorban** [comment]
@strogiyotec flaky tests are generally stable; it usually requires some persuasion to reproduce them, like automatically re-running the test until it fails, loading the machine on which it is running (saturate the CPU, saturate the network interface, ...), a good sense of improvisation and a great deal of patience.

Flaky tests almost always mean there is a race condition somewhere. It could be in the Jetty codebase, or in the test itself, but it needs to be tracked down, analyzed, justified, and fixed. This usually isn't an easy task and certainly not something I would recommend to a newcomer. But you're nevertheless welcome to give it a try!

As to why we're using JDK 19, we usually run our PR and nightly builds against both the minimally supported JDK (17 in the case of Jetty 12) and the most recent stable release. We still need to upgrade to JDK 20, but it's on our todo list.
