### ISSUE TITLE
Conflict between jetty-maven-plugin and tomcat-jdbc on org.apache.juli.logging.Log

### ISSUE THREAD

**Issue by jeremycod** [eclipse/jetty.project#992]
I have a maven application that uses jetty-maven-plugin 9.3.7 for local development. I am also using tomcat-jdbc 9.0.0.M10, and jetty plugin has a conflict with this dependency on org.apache.juli.logging.Log. Based on some previous discussions, problem seems to be related to the fact Jetty is using modified version of Juli logging which conflicts with the version embedded in tomcat-jdbc.

When I run application using Jetty server, the following exception is fired:

```
Caused by: java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
    at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
    at org.apache.tomcat.jdbc.pool.PoolProperties.<clinit>(PoolProperties.java:36)
    at org.prosolo.core.hibernate.HibernateConfig.dataSource(HibernateConfig.java:112)
    at org.prosolo.core.hibernate.HibernateConfig$$EnhancerBySpringCGLIB$$f615c572.CGLIB$dataSource$1(<generated>)
    at org.prosolo.core.hibernate.HibernateConfig$$EnhancerBySpringCGLIB$$f615c572$$FastClassBySpringCGLIB$$91af07c5.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
    at org.prosolo.core.hibernate.HibernateConfig$$EnhancerBySpringCGLIB$$f615c572.dataSource(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
```

The problem is also described here http://stackoverflow.com/questions/32643530/classpath-issue-between-jetty-maven-plugin-and-tomcat-jdbc-8-0-9-leading-to-ser, but suggested solutions don't work for me. If I exclude tomcat-juli from tomcat-jdbc, Jetty runs fine, but I can't run JUnit tests since Juli is missing and the other exceptions is fired:

```
Caused by: java.lang.ClassNotFoundException: org.apache.juli.logging.LogFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.tomcat.jdbc.pool.PoolProperties.<clinit>(PoolProperties.java:36)
        at org.prosolo.core.hibernate.HibernateConfig.dataSource(HibernateConfig.java:112)
        at org.prosolo.core.hibernate.HibernateConfig$$EnhancerBySpringCGLIB$$6e9ae256.CGLIB$dataSource$0(<generated>)
        at org.prosolo.core.hibernate.HibernateConfig$$EnhancerBySpringCGLIB$$6e9ae256$$FastClassBySpringCGLIB$$ddcf2b49.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
        at org.prosolo.core.hibernate.HibernateConfig$$EnhancerBySpringCGLIB$$6e9ae256.dataSource(<generated>)
```

**Comment by janbartel** [comment]
@jeremycod excluding tomcat-juli from the dependencies is the correct thing to do. It should be possible to only add tomcat-juli as a scope=test or scope=provided. Can you try that?

**Comment by jeremycod** [comment]
@janbartel You're right. This works. I've initially tried it, but I added tomcat-juli as test scope dependency to maven submodule I'm sharing between two projects, and I failed to realize that these dependency is not available in the main project. 
Thanks

**Comment by janbartel** [comment]
OK, good, I'll close this issue.
