### ISSUE TITLE
Error firing onResponseWrite: java.lang.NullPointerException in org.eclipse.jetty.server.handler.EventsHandler.notifyOnResponseWrite(EventsHandler.java:163)

### ISSUE THREAD

**Issue by minduch** [eclipse/jetty.project#9942]
**Jetty version**
Jetty 12.0 beta2

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

**OS type/version**
Windows 11 - Microsoft Windows [Version 10.0.22631.1900]

**Description**
Error firing onResponseWrite: [java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.asReadOnlyBuffer()" because "content" is null

**How to reproduce?**
WebSockets upgrade process calls `response.write(true, null, callback);` in at `org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker.upgradeRequest(AbstractHandshaker.java:142)`

causing the code in `org.eclipse.jetty.server.handler.EventsHandler.notifyOnResponseWrite(EventsHandler.java:163)` to generate a NullPointerException because `content` is `null`:

```java
    private void notifyOnResponseWrite(Request request, boolean last, ByteBuffer content)
    {
        try
        {
            onResponseWrite(request, last, content.asReadOnlyBuffer());
        }
        catch (Throwable x)
        {
            LOG.info("Error firing onResponseWrite", x);
        }
    }
```

The  `org.eclipse.jetty.server.handler.EventsHandler.notifyOnResponseWrite`  should probably look like:

```java
    private void notifyOnResponseWrite(Request request, boolean last, ByteBuffer content)
    {
        try
        {
            onResponseWrite(request, last, (content != null)? content.asReadOnlyBuffer(): null);
        }
        catch (Throwable x)
        {
            LOG.info("Error firing onResponseWrite", x);
        }
    }
```

I have seen this problem also in other handlers, e.g. Gzip and others also performing calls like `response.write(true, null, callback);`.

The NullPointerException is caught in the `notifyOnResponseWrite` method itself, and does therefore not call `onResponseWrite(...)`, and causes a stack trace error to be printed.

In this case, the stack trace looks like:

```
[INFO]    21 Jun 2023  15:23:33.445  <system>  <cij.WSHandler>  [qtp1825204537-64,5,<WebServer-pool>]  Service WebSocket upgrade request: /iizi/app.ws
[INFO]    21 Jun 2023  15:23:33.447  <system>  <oejsh.EventsHandler>  [qtp1825204537-64,5,<WebServer-pool>]  Error firing onResponseWrite: [java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.asReadOnlyBuffer()" because "content" is null
          	at org.eclipse.jetty.server.handler.EventsHandler.notifyOnResponseWrite(EventsHandler.java:163)
          	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:347)
          	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:589)
          	at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
          	at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker.upgradeRequest(AbstractHandshaker.java:142)
          	at org.eclipse.jetty.websocket.core.server.internal.HandshakerSelector.upgradeRequest(HandshakerSelector.java:46)
          	at org.eclipse.jetty.websocket.core.server.WebSocketMappings.upgrade(WebSocketMappings.java:287)
          	at org.eclipse.jetty.websocket.core.server.WebSocketMappings.upgrade(WebSocketMappings.java:262)
          	at org.eclipse.jetty.ee10.websocket.server.JettyWebSocketServlet.service(JettyWebSocketServlet.java:200)
          	at com.iizix.jetty.WSHandler.service(WSHandler.java:173)
          	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
          	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:739)
          	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1601)
          	at com.iizix.jetty.CORSFilter.doFilter(CORSFilter.java:170)
          	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
          	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1573)
          	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1534)
          	at org.eclipse.jetty.ee10.servlet.ServletChannel.lambda$handle$0(ServletChannel.java:427)
          	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:684)
          	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:418)
          	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:458)
          	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:663)
          	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:798)
          	at com.iizix.jetty.ServletContextHandlers.handle(ServletContextHandlers.java:50)
          	at org.eclipse.jetty.server.Handler$Sequence.handle(Handler.java:665)
          	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:611)
          	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:95)
          	at com.iizix.jetty.WSStatisticsHandler.handle(WSStatisticsHandler.java:47)
          	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:611)
          	at org.eclipse.jetty.server.Server.handle(Server.java:177)
          	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:617)
          	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:480)
          	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
          	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
          	at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:554)
          	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:373)
          	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
          	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
          	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
          	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
          	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:436)
          	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
          	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:136)
          	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
          	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
          	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
          	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
          	at java.base/java.lang.Thread.run(Thread.java:833) ]
```

I can provide a "test case" to demonstrate this problem, but it is rather large and a little complex, and as I have seen the same `NullPointerException` in e.g. GzipHandler, I think it may be a more general problem that the `content` is set to `null`.

Let me know if you wish to have this `test case`.

**Comment by minduch** [comment]
Oh, I forgot to mention that it is the Embedded Jetty, not a Jetty using the `start` mechanism, thus the "large test case".

**Comment by lorban** [comment]
Already fixed in https://github.com/eclipse/jetty.project/commit/5d971756866732e1af75ffafbea57ffab6e544cf which got merged yesterday.
