### ISSUE TITLE
Flaky test org.eclipse.jetty.tests.distribution.DemoModulesTests.testRewrite

### ISSUE THREAD

**Issue by lorban** [eclipse/jetty.project#9959]
**Jetty version(s)**
12

**Description**
Seems to have the same cause as https://github.com/eclipse/jetty.project/pull/9952

```
2023-06-23 16:33:29.948:WARN :oejk.KeystoreGenerator:main: Generating Test Keystore: DO NOT USE IN PRODUCTION!
2023-06-23 16:33:31.303:WARN :oejx.XmlConfiguration:main: Deprecated method public void org.eclipse.jetty.security.HashLoginService.setHotReload(boolean) in file:///home/jenkins/agent/workspace/jetty.project_jetty-12.0.x/tests/test-distribution/test-distribution-common/target/tests/oejtd.DemoModulesTests/testRewrite%255B2%255D%2520ee9/etc/jetty-demo-realm.xml
2023-06-23 16:33:31.304:WARN :oe.jetty:main: demo-realm is deployed. DO NOT USE IN PRODUCTION!
2023-06-23 16:33:31.514:INFO :oejs.Server:main: jetty-12.0.0-SNAPSHOT; built: 2023-06-23T15:24:09.128Z; git: dd71db35fd36e7db363c09ec11ea4dfd802edc75; jvm 17.0.7+7
2023-06-23 16:33:31.531:WARN :oejx.XmlConfiguration:main: Unable to execute XmlConfigurationjava.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
 at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
 at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:305)
 at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:529)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
 at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
 at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
 at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
 at org.eclipse.jetty.server.Server.doStart(Server.java:525)
 at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
 at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1983)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
 at org.eclipse.jetty.start.Main.start(Main.java:519)
 at org.eclipse.jetty.start.Main.main(Main.java:76)Caused by: java.net.BindException: Address already in use
 at java.base/sun.nio.ch.Net.bind0(Native Method)
 at java.base/sun.nio.ch.Net.bind(Net.java:555)
 at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
 at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
 at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:340)
 at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:305)
 at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:529)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
 at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
 at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
 at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
 at org.eclipse.jetty.server.Server.doStart(Server.java:525)
 at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
 at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1983)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
 at org.eclipse.jetty.start.Main.start(Main.java:519)
 at org.eclipse.jetty.start.Main.main(Main.java:76)java.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
 at org.eclipse.jetty.start.Main.start(Main.java:519)
 at org.eclipse.jetty.start.Main.main(Main.java:76)Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
 at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
 at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:305)
 at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:529)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
 at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
 at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
 at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
 at org.eclipse.jetty.server.Server.doStart(Server.java:525)
 at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
 at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1983) ... 7 moreCaused by: java.net.BindException: Address already in use
 at java.base/sun.nio.ch.Net.bind0(Native Method)
 at java.base/sun.nio.ch.Net.bind(Net.java:555)
 at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
 at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
 at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:340) ... 22 morejava.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
 at org.eclipse.jetty.start.Main.start(Main.java:519)
 at org.eclipse.jetty.start.Main.main(Main.java:76)Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
 at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
 at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:305)
 at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:529)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
 at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
 at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
 at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
 at org.eclipse.jetty.server.Server.doStart(Server.java:525)
 at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
 at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1983) ... 7 moreCaused by: java.net.BindException: Address already in use
 at java.base/sun.nio.ch.Net.bind0(Native Method)
 at java.base/sun.nio.ch.Net.bind(Net.java:555)
 at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
 at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
 at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:340)
 ... 22 more
Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
java -jar $JETTY_HOME/start.jar --help  # for more information ==> expected: <true> but was: <false>
```

See https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1312/testReport/junit/org.eclipse.jetty.tests.distribution/DemoModulesTests/Parallel_Stage___Build___Test___JDK17___testRewrite_String__2_/

**Comment by olamy** [comment]
fixed with https://github.com/eclipse/jetty.project/commit/f2aee378a38447e8aa61572440bd696001d9de25
